### PR TITLE
Correcting units on accumulated variables in ocean conservation check

### PR DESCRIPTION
**Pull request by darincomeau**
Corrects units on accumulated variables in ocean conservation check, which have been multiplied by area.

[BFB]

### CODE REVIEW

**Comment by darincomeau** [comment]
Copying comment over from https://github.com/E3SM-Project/E3SM/pull/6229

>here's my comment from the Ocean Discussion PR for more context:

@mark-petersen can you check the proposed unit changes in the conservation check analysis member's Registry here https://github.com/E3SM-Ocean-Discussion/E3SM/commit/285be919629f04d40cf3402bf6e69c865d47d580?

@cbegeman and I looked into this and see the flux variables being multiplied by m^2 here:
[E3SM/components/mpas-ocean/src/analysis_members/mpas_ocn_conservation_check.F](https://github.com/E3SM-Project/E3SM/blob/50485d0c929a873b5935ea3c2dc1da4d236319dd/components/mpas-ocean/src/analysis_members/mpas_ocn_conservation_check.F#L954)

Line 954 in [50485d0](https://github.com/E3SM-Project/E3SM/commit/50485d0c929a873b5935ea3c2dc1da4d236319dd)

 sumArray( 1) = sumArray( 1) + areaCell(iCell) * rainFlux(iCell) 

and not divided out again. Also when we look at the values that are written out to the conservation check analysis member, we can back out values in kg m^-2 s^-1 that appear in the ocn.log file from this analysis member by scaling by 1/area again.
The reason we're looking here is we want to use these accumulated*Flux quantities to produce a net AIS runoff time series plot for polar simulations to compare to global ssh anomaly, and to us everything is consistent if these quantities are actually in units kg s^-1.

Also, many thanks @mark-petersen for your work on this analysis member in the past. It's made verification of this coupler budget accounting much easier.

**Review by cbegeman — APPROVED** [review]
I agree that this change is needed.

**Review by mark-petersen — APPROVED** [review]
@darincomeau Thanks, this change is correct. Looking at the output:
```
  MASS CONSERVATION CHECK

 MASS FLUXES
 MPAS-Ocean name          kg/s (F)       coupler name     short name     kg/m^2/s*1e6 (F/A)
 frazilFreshwaterFlux    -9.60609187E+07 o2x_Fioo_frazil  wfreeze             -0.18831740
 seaIceFreshwaterFlux     3.80124701E+09 x2o_Fioi_meltw   wmelt                7.45194768
 rainFlux                 1.35659405E+10 x2o_Faxa_rain    wrain               26.59460915
 snowFlux                 3.95339636E+08 x2o_Faxa_snow    wsnow                0.77502206
 icebergFreshwaterFlux    9.56158749E+07 x2o_Fioi_bergw   wberg                0.18744493
 evaporationFlux         -1.59515036E+10 x2o_Foxx_evap    wevap              -31.27125659
 riverRunoffFlux          6.97379066E+07 x2o_Foxx_rofl    wrunoff              0.13671388
```
those variables are clearly in kg/s, based on both the labels and magnitude of the numbers.

**Comment by jonbob** [comment]
Passes:
* ERS_Ld5.T62_oQU120.CMPASO-NYF.chrysalis_intel
* ERP_Ld3.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-pioroot1

merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
