### PR TITLE
update mpas-source:improve GM drhodx

### PR DESCRIPTION
**Pull request by mark-petersen**
Currently the GM horizontal buoyancy gradient is computed at a fixed vertical index. At a number of places in the ocean this is problematic where layer thickness changes quickly between cells (especially near the bottom for partial bottom cells).

See https://github.com/MPAS-Dev/MPAS-Model/pull/633

[non-BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
Passes
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PET_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-knl_intel
PEM_Ln3_P512.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_intel
```
This is ready to merge to next.

**Comment by jonbob** [comment]
Passed:
* PET_D.T62_oQU240.GMPAS-IAF.anvil_intel
* SMS_D.ne30_oECv3_ICG.A_WCYCL1850S.anvil_intel

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Comment by jonbob** [comment]
Expected DIFFs blessed

**Pull request merged**
