### PR TITLE
Evaluate time-dependent tendencies at correct time for each RK4 stage

### PR DESCRIPTION
**Pull request by sbrus89**
This PR corrects a longstanding issue with RK4 and tendency terms which have an explicit time dependence (see https://github.com/E3SM-Project/E3SM/issues/5364 and https://github.com/MPAS-Dev/MPAS-Model/issues/375). Big thanks to @gcapodag and @jeremy-lilly for providing the fix in their LTS development branch linked in https://github.com/E3SM-Project/E3SM/issues/5364.

Here, I have migrated these changes from their MPAS-Dev branch to E3SM and added the modifications to correct the convergence issues for the manufactured solution test case: https://github.com/E3SM-Project/polaris/pull/72

### CODE REVIEW

**Comment by sbrus89** [comment]
**Testing:**

With this PR, the manufactured solution test case in Polaris converges at 2nd order when refining in space/time:
image

When refining in time only, 4th order convergence is achieved:
image

However, I have not been able to reproduce the 4th order convergence for the hurricane test case from [Lilly et al. 2023](https://doi.org/10.1029/2022MS003327) (Figure 4). The best I have been able to achieve is first order:
convergence
For this result, I ran from `2012-10-13_00:00:00` to `2012-10-13_01:00:00` starting from a `2012-10-13_00:00:00` restart file. I used dt=0.1 as a reference solution.

**Comment by sbrus89** [comment]
Closing to fix branch name.

**Comment by gcapodag** [comment]
> **Testing:**
> 
> With this PR, the manufactured solution test case in Polaris converges at 2nd order when refining in space/time: image
> 
> When refining in time only, 4th order convergence is achieved: image
> 
> However, I have not been able to reproduce the 4th order convergence for the hurricane test case from [Lilly et al. 2023](https://doi.org/10.1029/2022MS003327) (Figure 4). The best I have been able to achieve is first order: convergence For this result, I ran from `2012-10-13_00:00:00` to `2012-10-13_01:00:00` starting from a `2012-10-13_00:00:00` restart file. I used dt=0.1 as a reference solution.

@jeremy-lilly  👀

**Comment by sbrus89** [comment]
Moved to https://github.com/E3SM-Project/E3SM/pull/6695

**Pull request closed without merging**
