### PR TITLE
Add gnu compiler support on Crusher and AMD.

### PR DESCRIPTION
**Pull request by grnydawn**
Changes:
* add crusher configuration in config_machines.xml, config_batch.xml
* create gnu_crusher.cmake
* for testing amdclang and crayclang, cmake configurations for the compilers are also added
* add CPRAMD macro in shr_infnan_mod.F90.in to use ieee arithmetic

[BFB]

### CODE REVIEW

**Comment by ndkeen** [comment]
It might be better to separate the GNU changes in this PR and the AMD compiler changes.

I was going to bring in support for the AMD compiler here https://github.com/E3SM-Project/E3SM/issues/4787

**Comment by rljacob** [comment]
I already delayed this PR that people are waiting on.  It can go ahead with the AMD additions.

**Comment by minxu74** [comment]
@amametjanov could you approve the PR? It shall be the same as the #4793, but has a clean history.

**Review by rljacob — APPROVED** [review]

**Comment by minxu74** [comment]
Okay. I am merging it now

**Review by amametjanov — APPROVED** [review]

**Comment by grnydawn** [comment]
@ndkeen Most of configurations added in this PR for amdclang are isolated to only Crusher system(using amdclang_crusher.cmake). The only configurations that affect to the amdclang compiler on other systems are generic and shown below:

if (compile_threaded)
  string(APPEND FFLAGS " -fopenmp")
  string(APPEND CFLAGS " -fopenmp")
  string(APPEND CXXFLAGS " -fopenmp")
  string(APPEND LDFLAGS " -fopenmp")
endif()
string(APPEND CPPDEFS " -DNO_R16 -DCPRAMD -DFORTRANUNDERSCORE")

**Comment by ndkeen** [comment]
That's fine, I can adjust --  just think it's cleaner to keep PR topics narrowly focused. One undervalued reason is to reduce headaches when we need to go back in history to see which PR's might have caused an issue.

**Pull request merged**
