### PR TITLE
fates phosphatase fix and iteration counters

### LINKED ISSUE #6186: floating invalid in `PhosphorusDynamicsMod.F90` with `SMS_D_Ld20.f45_f45.IELMFATES.pm-cpu_intel.elm-fates_eca`
With Jan23 master and `SMS_D_Ld20.f45_f45.IELMFATES.pm-cpu_intel.elm-fates_eca`

```
119: forrtl: error (65): floating invalid
119: Image              PC                Routine            Line        Source
119: libpthread-2.31.s  000015143EFEF910  Unknown               Unknown  Unknown
119: e3sm.exe           00000000033F60C1  phosphorusdynamic         653  PhosphorusDynamicsMod.F90
119: e3sm.exe           0000000002FAF771  ecosystemdynmod_m         431  EcosystemDynMod.F90
119: e3sm.exe           00000000009CA4D5  elm_driver_mp_elm        1042  elm_driver.F90
119: e3sm.exe           0000000000956157  lnd_comp_mct_mp_l         617  lnd_comp_mct.F90
119: e3sm.exe           00000000004A8323  component_mod_mp_         757  component_mod.F90
119: e3sm.exe           000000000046955B  cime_comp_mod_mp_        2915  cime_comp_mod.F90
119: e3sm.exe           0000000000490BCB  MAIN__                    153  cime_driver.F90
119: e3sm.exe           000000000043336D  Unknown               Unknown  Unknown

```

### PR DESCRIPTION
**Pull request by rgknox**
This implements a fix to the FATES phosphatase dynamics in the capacitance based formulation.  
This had previously been using an uninitialized critical value for phosphatse concentrations. 
An updated scheme has been applied that does not use the critical value (lambda).  
Also, a history diagnostic that tracks the number of iterations necessary for the land-surface energy solve was added.

Fixes #6186 
[non-BFB] fates eca

### CODE REVIEW

**Comment by rgknox** [comment]
Fixes: https://github.com/E3SM-Project/E3SM/issues/6186

**Comment by rgknox** [comment]
FYI, I still need to test this.

**Comment by rgknox** [comment]
I went over the phosphatase changes with @qzhu-lbl , the original author of the phosphatase code.
He thought everything looked ok, and recommended we explicitly set the plant biochem pmin uptake array to zero (it would had already been zero, but this is more explicit).
https://github.com/E3SM-Project/E3SM/pull/6222/files#diff-b1433e63eabef73007a8a053bd3d19d620e7c092642b42343b484af09262f32dR659

I also updated the defaults for nutrient supplementation when fates is active, making this value 'ALL' (synonymous with "yes supplement". I checked in with several stake holders on the FATES team. This is a safer default, as supplementation is most likely the correct choice when FATES is not actively exchanging nutrients, and even when it is, this may still be the better choice depending on the phase of the spin-up procedure.

**Comment by rgknox** [comment]
Tests look good: 
/pscratch/sd/r/rgknox/e3sm_tests/Eb211e59867-F44ba97a8-fates-lamda-tests-v3
Except for this test: SMS.r05_r05.I1850ELMCN.pm-cpu_gnu.elm-qian_1948  with errors that seem unrelated (has to do with the surface dataset and area fractions)

**Comment by glemieux** [comment]
Nice.  That failing test is fixed by #6219.

**Comment by peterdschwartz** [comment]
@rgknox  I don't have permissions to view your testing directory, but I ran your branch after merging to next on chrysalis and go a DIFF in `SMS_Ld20.f45_f45.IELMFATES.chrysalis_intel.elm-fates_eca`.   Looking at the code changes, it makes sense, but just want to confirm that that's expected.

**Comment by rgknox** [comment]
@peterdschwartz , yes, there should definitely be differences in the fates_eca test, thanks for checking.

**Comment by peterdschwartz** [comment]
@rgknox Thanks.  Repo is closed for PRs with DIFFs currently.  Can hopefully get this in after the LUH2 when it opens up.

**Comment by peterdschwartz** [comment]
Merged to next

**Comment by peterdschwartz** [comment]
Note: chrysalis is undergoing maintenance in the morning and may not have a result for the expected fates-eca DIFF

**Comment by peterdschwartz** [comment]
Merged to master.  chrysalis reported in time for this test so no more to do

**Pull request merged**
