### PR TITLE
using YAKL_SCOPE to replace auto for local variables

### PR DESCRIPTION
**Pull request by xyuan**
using YAKL_SCOPE to replace the auto to create local variables that required by SYCL on JLSE

[BFB]

### CODE REVIEW

**Comment by whannah1** [comment]
I ran these two tests on Cori without baseline comparison as a sanity check:
SMS_Ln3.ne4pg2_ne4pg2.F-MMFXX.cori-knl_intel.eam-mmf_use_VT
ERS_Ln3.ne4pg2_ne4pg2.F-MMFXX.cori-knl_intel.eam-mmf_use_ESMT

**Review by whannah1 — APPROVED** [review]

**Review by mrnorman — APPROVED** [review]

**Comment by xyuan** [comment]
@brhillman could you merge this PR this week?

**Comment by rljacob** [comment]
@brhillman please start merging this.

**Comment by brhillman** [comment]
Merged to next.

**Comment by brhillman** [comment]
Merged to master.

**Pull request merged**
