### PR TITLE
Fix the calculations of p3 sedimentation fluxes

### PR DESCRIPTION
**Pull request by yunpengshan2014**
Original calculation in the P3 code: the precipitation (rain and snow) flux (sflx for snow ) is summed over the flux at each sub-timestep during one microphysics timestep: sflx=flux_qit_1+ flux_qit_2+ flux_qit_3+… flux_qit_n, where the flux_qit_i (i=1,2,3,…n) represents the snow flux at each sub-timestep for sedimentation. This should not be correct. The correct flux should be the mean value for each microphysics timestep.

Changed calculation in the current version: In E3SM-P3, since the sub-timestep is not a fixed value, the mean flux over the microphysics timestep should be calculated with: sflx=(flux_qit_1dt1+ flux_qit_2dt2+ flux_qit_3dt3+… flux_qit_ndtn)/( dt1+ dt2+ dt3+… dtn), where dti represents sub-timestep length. This is similar to the equation used to calculate the surface precipitation rate.

This PR does not effect the model simulation results, but only change the diagnostic precipitation flux output.

### CODE REVIEW

**Comment by crterai** [comment]
@yunpengshan2014, would you modify the title of this PR so that it follows the 'Verb object' format? You can see how other PRs are named to get an idea.

**Comment by wlin7** [comment]
The following variables are affected, but not in default eam history output
`precip_liq_flux, precip_ice_flux, ice_flux, rain_flux, cldliq_flux` They would be enabled when `micro_tend_output = .true.`

**Review by wlin7 — APPROVED** [review]
The changes look reasonable and consistent, correctly accounting for difference in dt_sub during substepping to obtain an average over the full microphysics time step.

**Comment by rljacob** [comment]
@wlin7 is this ready?

**Comment by rljacob** [comment]
satus:  ready to merge before the v3alpha03 tag.

**Comment by wlin7** [comment]
Merged to next.

**Comment by wlin7** [comment]
@yunpengshan2014 , this PR appears to affect COSP simulator output (e.g., CALIPSO). Can you please confirm it is expected?

**Comment by yunpengshan2014** [comment]
Yes, this is expected.
Regards,
Yunpeng

**Comment by wlin7** [comment]
Thank you, Yunpeng. All is good now.

**Pull request merged**
