### PR TITLE
Ocean Initialization Reorganization

### PR DESCRIPTION
**Pull request by mattdturner**
This is a transplant from https://github.com/MPAS-Dev/MPAS-Model/pull/852

> The changes here push all ocean mesh initialization very early in the initialization sequence (just after file reads) so that all mesh module variables are available to later module initialization routines. In addition, all mesh initialization has been consolidated into the meshCreate routine and the relevant routines moved into the ocn_mesh module. The exceptions are the advection weights and rbf interpolation variables which may be relocated later, so the mesh update routine in initialization is still necessary to capture these. Also moved edgeArea weights from diagnostics into the mesh and removed from registry (now just an internal mesh module variable).

[BFB]

### CODE REVIEW

**Comment by mattdturner** [comment]
### Testing

Chrysalis (Intel)
```
PASS:
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
PEM_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.chrysalis_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.chrysalis_intel
PET_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
PEM_Ln9_D.T62_oQU240.GMPAS-IAF.chrysalis_intel
```

Anvil (Intel and GNU)
```
PASS:
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.anvil_gnu
PEM_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
PEM_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.anvil_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
SMS_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
PET_Ln3_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_gnu
PEM_Ln9_D.T62_oQU240.GMPAS-IAF.anvil_intel
PEM_Ln9_D.T62_oQU240.GMPAS-IAF.anvil_gnu
```

Compy (PGI + Intel)
```
PASS:
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_intel
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_pgi
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_pgi
PEM_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_intel
PET_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
PET_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
```

BFB tests
```
PASS:
PEM_Ln9.ne30_oECv3.A_WCYCL1850S.chrysalis_intel.C
  - PASS PEM_Ln9.ne30_oECv3.A_WCYCL1850S.chrysalis_intel BASELINE /lcrc/group/e3sm/baselines/chrys/intel/mas
ter:
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel.C
  - PASS SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel BASELINE /lcrc/group/e3sm/baselines/chrys/inte
l/master:

```

**Review by philipwjones — APPROVED** [review]
Approved based on earlier testing for MPAS PR and subsequent testing by Matt in E3SM repo.

**Review by jonbob — APPROVED** [review]
Looks good to me, based on a visual inspection and amount of developers testing

**Comment by jonbob** [comment]
merged to next

**Review by mark-petersen — APPROVED** [review]
This looks good, based on visual inspection and Matt's testing. I also rebased on origin/master and compiled MPAS-Ocean standalone.

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
