### PR TITLE
Update maint-1.1 to bring in science bug fixes

### PR DESCRIPTION
**Pull request by jonbob**
Bring to maint-1.1 bug fixes and changes from master:
- Changes to cime removing bad term from E3SM water budgets
- Replace low-res (half-degree) MOSART file
- Turn off mpas-seaice history files by default
- Fix snow compaction bug that was resulting in sporadic unphysical snow depths
- Bugfix for the IEFLX output
- Update MPAS source to bring in BGC bug fix (but different hash to match the maint-1.1 branch)
- Adds water budget in the land model (and fixes water conservation error)

These changes are requested prior to the start of BGC production runs.

Do not merge until tested

[NML]
[non-BFB]

### CODE REVIEW

**Comment by susburrows** [comment]
This fixes #2568 , correct?

**Comment by rljacob** [comment]
You could ask the original authors of the commits, @bishtgautam and @kaizhangpnl, to check if there's any commits missing.

**Comment by jonbob** [comment]
@susburrows - it does fix #2568, but we can't just cherry-pick the commit for that one like we did with the others because it brings in an updated mpas-source submodule that has changes besides just the factor of five bug fix. So we created the equivalent maint-1.1 branch in the mpas submodule and merged it.

**Comment by jonbob** [comment]
@susburrows - could you please let me know exactly which BGC compsets are most important to test? Thanks

**Comment by susburrows** [comment]
@jonbob - Yes.  The 1850 spinup compsets with CTC+ocnBGC (CNP), and ECA:
BGCEXP_BCRC_CNPRDCTC_1850
BGCEXP_BCRC_CNPECACNT_1850

I think that should cover most of the functionality.  These are also the only two BGC compsets that are covered in the nightly tests currently.

It might also be worth testing a CTC compset that has ocean BGC off, in a transient (20th century) case, which should then cover most of the permutations of configurations we will be using:
BGCEXP_BCRC_CNPRDCTC_20TRS

**Comment by susburrows** [comment]
@rljacob good point.

@kaizhangpnl  and @bishtgautam , would you be willing to take a quick look at this PR to see if it looks OK to you?

**Comment by kaizhangpnl** [comment]
I am not familiar with all the changes, but the fix for IEFLX is implemented correctly. It has no impact on climate, and only affects the diagnostic output.

**Comment by jonbob** [comment]
passed:
* SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
* SMS.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.anvil_intel

built and in the queue:
* SMS.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.anvil_intel
* SMS.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_1850.anvil_intel

**Comment by susburrows** [comment]
Great, thanks @bishtgautam and @kaizhangpnl for the quick response.

**Comment by jonbob** [comment]
Built and in the queue:
* ERS.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_1850.anvil_intel
* PEM.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.anvil_intel

We can't use threading with the mpas-ocean BGC, so I won't run a PET test. Assuming these tests pass, I'll feel comfortable that the functionality of the codebase is fine -- unless someone else would recommend something more. @maltrud has signed to take on a longer test on anvil after that.

**Comment by susburrows** [comment]
Thanks @jonbob .  Let's wait for the longer test of the continued spinup simulation before merging, as long as we can get it merged by the end of next week, so that we can be positioned to start production when everyone is back from the DOE meeting on 11/12.

**Comment by rljacob** [comment]
If that machine update changes things on the machines you're testing on, you may want to rebase this branch to the head of maint-1.1 and rerun a couple of tests.

**Comment by rljacob** [comment]
Reproducing links to other PRs:
#2452 - Changes to cime removing bad term from E3SM water budgets
#2509 - Replace low-res (half-degree) MOSART file
#2511 - Turn off mpas-seaice history files by default
#2544 - Fix snow compaction bug that was resulting in sporadic unphysical snow depths
#2545 - Bugfix for the IEFLX output
#2588 - Update MPAS source to bring in BGC bug fix (but different hash to match the maint-1.1 branch)
#2603 - Adds water budget in the land model (and fixes water conservation error)

**Comment by rljacob** [comment]
From Kate's talk, sounds like this also needs #2593 ?

**Comment by jonbob** [comment]
@rljacob - yes, absolutely. I was waiting for it to get OK'd for master before adding it as well.

**Comment by jonbob** [comment]
#2593 added as well

**Comment by jonbob** [comment]
#2612 also included

**Comment by jonbob** [comment]
removed #2612, because it was deemed not a bug fix from master

**Comment by rljacob** [comment]
So what is keeping this from being merged to maint-1.1?

**Comment by jonbob** [comment]
I had asked Susannah for final blessing for the small pile of commits scheduled to go into maint-1.1. She just gave me the g-ahead, so starting the merges now

**Comment by jonbob** [comment]
merged to maint-1.1

**Pull request merged**
