### PR TITLE
Removes CLM from module name

### PR DESCRIPTION
**Pull request by bishtgautam**
Renames `clm_time_manager` module as `elm_time_manager`.

[BFB]

### CODE REVIEW

**Comment by peterdschwartz** [comment]
So pretty much all tests FAIL to build due to FATES using the `clm_time_manager` module. 
Example error:
```
/gpfs/fs1/home/ac.schwartzpd/integration/E3SM/components/elm/src/external_models/fates/biogeophys/FatesPlantHydraulicsMod.F90(101): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [CLM_TIME_MANAGER]
  use clm_time_manager  , only : get_step_size, get_nstep
```

**Comment by rgknox** [comment]
@peterdschwartz we recently removed this dependency on the FATES. The solution here is for us to point to a more recent version of fates. I'm working on a fix branch for FATES that also fixes another issue with FATES-E3SM. I will submit a PR in the near future for this, which will update the pointer to a recent fates tag.

**Comment by bishtgautam** [comment]
@glemieux @rgknox The F90 files in the latest FATES `main` do not have `clm_time_manager`. Can we update the FATES submodule that is currently in E3SM?

**Comment by rljacob** [comment]
status:  waiting on a FATES PR.

**Comment by rgknox** [comment]
E3SM currently points to FATES tag [sci.1.63.2_api.25.1.0](https://github.com/NGEET/fates/releases/tag/sci.1.63.2_api.25.1.0) (which does reference clm_time_manager)

The most recent FATES tag is [sci.1.64.3_api.25.2.0](https://github.com/NGEET/fates/releases/tag/sci.1.64.3_api.25.2.0) (which does NOT reference clm_time_manager).

There is no changes to the E3SM-FATES code between those two tags, the only difference is that we need to load an updated fates parameter file to the E3SM server, reference the new default and update the submodule pointer so it points to sci.1.64.3_api.25.2.0.  @bishtgautam @glemieux , I didn't see any existing FATES PRs that are imminent, so I think the pragmatic and quicker solution here is to add the simple update mentioned above to this PR.  @bishtgautam would you like me to submit these changes?

**Comment by rgknox** [comment]
Here is a new branch with the changes mentioned above: 

https://github.com/rgknox/E3SM/tree/rgknox/lnd/fates-update-api


Let me know how you would like to proceed.

**Comment by glemieux** [comment]
@rgknox as a reminder for our future selves, we should update the fates pointer on your branch to get https://github.com/NGEET/fates/pull/1041 associated with this update once that pr is integrated.

**Comment by bishtgautam** [comment]
@rgknox, Go ahead and issue a new PR that updates the FATES submodule to [sci.1.66.1_api.25.5.0](https://github.com/NGEET/fates/releases/tag/sci.1.66.1_api.25.5.0). After the new PR is merged to master, I will rebase this PR.

**Comment by rljacob** [comment]
notes:  needs a rebase.

**Comment by bishtgautam** [comment]
@peterdschwartz I rebased this branch and it ready for review/merge.

**Comment by rljacob** [comment]
@peterdschwartz please review and merge.

**Review by peterdschwartz — APPROVED** [review]

**Comment by peterdschwartz** [comment]
merged to next

**Comment by rljacob** [comment]
@peterdschwartz go ahead and merge to master.

**Pull request merged**
