### PR TITLE
 Ocean: Reduce pointer retrievals in shared directory

### PR DESCRIPTION
**Pull request by mark-petersen**
See https://github.com/MPAS-Dev/MPAS-Model/pull/457 by @mattdturner 

Reduce pointer retrievals. This includes scratch allocates and config pointers. We are taking a staged approach, so this PR only alters the `src/core_ocean/shared` directory. See similar changes for analysis and init in previous PR, #3717. Here, we:
1. replace almost all calls to `mpas_allocate_scratch_field` in the ocean model with straight Fortran allocates.  This is done as part of the MPAS framework rewrite, per @philipwjones .  
2. replace almost all calls to `mpas_pool_get_config` in subroutines with definitions in `ocn_config` via `use ocn_config`. 

This PR is labelled as non-BFB, because there could be machine-precision changes that accumulate. In MPAS-Ocean stand-alone testing, comparisons compiled in intel debug, gnu debug, and gnu optimized are all BFB. Comparisons with intel optimized had small differences.

[non-BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
This PR may be non-bfb for optimized compiler settings. We will check that again when this is next in line.

**Comment by mark-petersen** [comment]
Passes:
```
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
```
Running more tests now.

**Comment by mark-petersen** [comment]
Fails
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
```
Looking into it now.

**Comment by jonbob** [comment]
@mark-petersen - did you check if this PR is BFB?

**Comment by jonbob** [comment]
@mark-petersen - and does it pass the tests it had previously been failing?

**Comment by mark-petersen** [comment]
In mpas stand-alone it is bfb with debug on and gnu optimized. intel optimized has machine-precision differences. So in general E3SM will be non-bfb (but it could be bfb). We have not checked in E3SM.

**Comment by jonbob** [comment]
OK, we should change the description to reflect that

**Comment by mark-petersen** [comment]
We have been struggling with those failures in debug mode. The LISIO tests:
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
```
sometimes pass and sometimes fail on any of these four. They sometimes alter between passing and failing on the same code base. This indicates a race condition or some other odd threading thing. Still working on it...

**Comment by jonbob** [comment]
OK, this is not ready then. In that case, could you please make this two PRs, one for the performance changes and one for the config removals?

**Comment by mark-petersen** [comment]
Rebased and updated. We found the problem with the sporadic failures above. Some variables were moved from MPAS scratch to standard allocated arrays, but were not removed from the Registry.xml file.

Passes:
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
```
```

**Comment by mark-petersen** [comment]
@jonbob I updated the description to provide more detail about exactly what was BFB in our testing.

**Comment by jonbob** [comment]
@mark-petersen - please respond to my request to make this two separate PR's, or explain why the two different aspects of this are connected

**Comment by mark-petersen** [comment]
They are not connected. The change in config flag access is simply adding `module use ocn_config` to the top, and deleting all the `mpas_pool_get_config` lines after that.  It was really a clean-up project. @mattdturner did it at the same time as the scratch allocate changes for convenience, after discussing it with me. 

You are right, they really are two separate PRs topic-wise. We will keep that in mind in the future. But it would really be a big project to change it now. The good thing about the config flag changes is that any mistake would come up as an error on compile, so I think those changes are very safe.

**Comment by jonbob** [comment]
@mark-petersen - we are lucky that any problem with the config part of this would come up in compilation, but we have a long-standing guideline that PR's are supposed to address one issue only

**Comment by mark-petersen** [comment]
@jonbob, in our defense, I'd say @mattdturner, @philipwjones and I have taken pains to make all the performance PRs incremental. You can see this simply in the number of PRs:

**Completed:**
1. update mpas-source: remove scratch allocates, analysis & init BFB Ocean #3717 

**Waiting:**

2. Ocean: Remove scratch allocates and calls to get_config Ocean non-BFB performance #3597 opened on May 26
3. Localized OpenMP Threading in MPAS-Ocean Ocean non-BFB performance #3596 opened on May 26 
4. Optimizations for tracer horizontal mixing in MPAS-Ocean BFB Ocean performance #3599 opened on May 26 
5. Ocean/tracer advection optimization BFB Ocean performance #3598 opened on May 26 

For the ones that are higher risk, we have or will further split them into subsections of the code (analysis, forward, shared, etc.). That number of PRs is a significant burden of work because they wait in line for months and need to be rebased and retested.

On this particular PR, you are right that we did include both the scratch allocate changes and removal of the calls to `mpas_pool_get_config` together. I think there is no harm done in that, and I would like to proceed with the merge.

Thanks. One of the toughest things about these big codes is to ensure the quality of the code repository, while still merging PRs at a reasonable rate.

**Comment by jonbob** [comment]
The harm is setting a precedent for combining PRs that should not be together. We had a lot of trouble with that in the past, and it's what pushed us to make this rule. I understand that the performance team is doing a good job with incremental PR's in general and I can appreciate that. But having a number of PRs in the wings is not a reason to push things through like this. It's a moot point today anyway, since next is still closed.

**Comment by mattdturner** [comment]
@jonbob I completely understand the desire to have PRs focus on a single issue.  When I initially started the work that went into this PR, it was a single issue in my mind.  The goal was to reduce the number of pointer retrievals at each timestep, which involved both the removal of the calls to `mpas_pool_get_config` and `mpas_allocate_scratch_field`.

So, (again, in my mind) this PR does indeed address a single issue.  I can see how this could be considered 2 separate issues, though.

**Comment by mark-petersen** [comment]
@jonbob, based on @mattdturner's comment, I revised the title and description to clarify the overall purpose. Hopefully that helps.

**Comment by jonbob** [comment]
@mark-petersen - changing the name doesn't change what it is. But based on @mattdturner's communication, and the fact that he may not have been fully aware of how we try to separate PR's, I'll get this in whenever the repo is open again.

**Comment by jonbob** [comment]
@mark-petersen - I'm not seeing this on e3sm/develop in the MPAS-Dev/MPAS-Model repo?

**Comment by mark-petersen** [comment]
Thanks. The commit was on e3sm/testing before. I pushed that same commit to e3sm/develop. The code in this PR is still identical to the testing that was successful late last week.

**Comment by jonbob** [comment]
@mark-petersen -- this PR has been a disaster

**Comment by mark-petersen** [comment]
Just a sec. I'm looking again, will push up the right thing and test.

**Comment by mark-petersen** [comment]
rebased onto today's master. Testing now...

**Comment by mark-petersen** [comment]
So far, passes:
```
SMS_D_Ln9.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
SMS_D_Ln9.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
SMS_D_Ln9.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
```
others still pending.

**Comment by mark-petersen** [comment]
Passes with gnu
```
PET_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-haswell_gnu
```
Same one passes run but fails compare on this branch and master, with intel
```
PET_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-knl_intel
PET_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-haswell_intel
```

**Comment by mark-petersen** [comment]
This is ready to merge.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Comment by jonbob** [comment]
blessed expected DIFFs which appeared only on compy using pgi

**Pull request merged**
