### PR TITLE
Update machine files for LANL IC

### PR DESCRIPTION
**Pull request by milenaveneziani**
Updates for grizzly and badger.

Tests pass on grizzly, but no longer on badger, after the latest IC update.

### CODE REVIEW

**Comment by jonbob** [comment]
@milenaveneziani - I think we should remove wolf, since it has been decommissioned. I can do that, or leave it to you -- whichever makes sense to you. It's not clear to me if badger works now with these changes?

**Comment by milenaveneziani** [comment]
I will remove wolf, no problem.
Last time I checked with Gennaro, this did not work on badger, but he was going to do more testing today.

**Comment by jonbob** [comment]
OK, let's wait to commit it until we can make it work on badger. Please let me know if you need any help with this.

**Comment by vanroekel** [comment]
Badger won't work until a version of parallel-netcdf is built for the compilers available on badger.  It is possible it may work if you use
```
intel-17.0.1
MVAPICH2-2.2
```
for the compiler and mpi.  Parallel-netcdf (1.8.1) was build for this combo on grizzly and should work for badger as those versions are available.

**Comment by milenaveneziani** [comment]
This is only pending installation of some libraries on badger.
Changes for grizzly work. And machine info for wolf has been removed.

**Comment by jonbob** [comment]
We need to create some modules on one of the machines before we fulfill this PR

**Comment by milenaveneziani** [comment]
@jonbob: I talked with various people about modules and badger, and I think this is very low on the priority list for everybody. So, I would suggest to merge this PR as is, and we can solve the badger module problems when we have time or a need.

**Comment by rljacob** [comment]
@jonbob please merge this PR.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
