### PR TITLE
Update CIME submodule 

### PR DESCRIPTION
**Pull request by jgfouca**
Updating to CIME master: c0b4e0714bf7bd33b8b591c36ca8e16fc324a560
    
Changes:
1) Add a useful check to wait_for_tests to catch when TestStatus file is corrupted
2) Add an optional mask to seq_io_write_av and seq_io_write_avscomp to put lfillvalue where mask =0
3) Use mask when writing i2x or x2i values to coupler history file.
4) NML gen: Facilitate adding defaults for a namelist group conditionally.
5) cpl7: Add memory usage logging
6) SCREAM: Add some missing SCREAM config dirs
7) cime standalone testing: allow nuopc to skip some tests
9) Add support for chrysalis to provenance.py
    
Bug fixes:
1) Fixes an issue in cpl hist avg files that caused the time variable not to be written correctly in pio2
2) Fix cleanup in scripts_regression_tests
3) PIO2: Seq io fix pio2, Don't rely on pio to do data conversions
4) env_batch.xml: need to get queue from case, not batch object
5) Need srun_binding to be an int, not float

DIFFs:
ERIO.ne30_g16_rx1.A.mappy_gnu
ERP_Ln9.ne4_ne4.FC5AV1C-L.mappy_gnu
ERS.f19_g16_rx1.A.mappy_gnu
ERS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.mappy_gnu.eam-thetahy_sl_pg2
ERS.ne30_g16_rx1.A.mappy_gnu
NCK.f19_g16_rx1.A.mappy_gnu
SMS_D_Ln5.ne4_ne4.FC5AV1C-L.mappy_gnu
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.mappy_gnu
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.mappy_gnu.eam-thetahy_pg2
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.mappy_gnu.eam-thetahy_sl_pg2
SMS_Ln9.ne4_ne4.FC5AV1C-L.mappy_gnu.eam-outfrq9s
SMS.ne30_f19_g16_rx1.A.mappy_gnu
SMS.ne4_ne4.FC5AV1C-L.mappy_gnu.eam-cosplite
SMS_R_Ld5.ne4_ne4.FSCM5A97.mappy_gnu.eam-scm

All are due to:
`had differences in fill patterns`
and are caused by the change to how i2x and x2i variables are written.  Only effects compsets with DICE or CICE.

Except for
SMS_R_Ld5.ne4_ne4.FSCM5A97.mappy_gnu.eam-scm

which had this diff:
```
 area   (ncol)
          1        1  (     1) (     1) (     1) (     1)
                   1   0.000000000000000E+00   0.000000000000000E+00 6.0-154  0.000000000000000E+00 1.0E+00  0.000000000000000E+00
                   1   6.013470016999068-154   6.013470016999068-154          6.013470016999068-154          6.013470016999068-154
                   1  (     1) (     1)
          avg abs field values:    0.000000000000000E+00    rms diff: 6.0-154   avg rel diff(npos):  1.0E+00
                                   6.013470016999068-154                        avg decimal digits(ndif):  0.0 worst:  0.0
 RMS area                             6.0135-154            NORMALIZED  2.0000E+00
```

The NML diffs appear to be:
```
Differences in namelist 'cime_pes':
  found extra variable: 'info_mprof'
  found extra variable: 'info_mprof_dt'
```

 [non-BFB] [NML]

### CODE REVIEW

**Comment by rljacob** [comment]
I'm not sure how to read that diff excerpt from the FSCM5A97 but it looks harmless.  Can you tell which commit said something about fill patterns?

**Review by rljacob — CHANGES_REQUESTED** [review]
This has to include the Chrysalis support changes that are in a later version of master:  10675d59ec65fe37.

You could make a branch off of c0b4e0714bf7bd, merge the Chrysalis changes to that and update CIME to that branch.

**Comment by jgfouca** [comment]
@rljacob , thanks. I will bisect to see when the fill pattern diffs were introduced and I will grab the chrysalis changes. I can't just grab a more recent CIME master since that picks up PIO changes that cause problems.

**Comment by jgfouca** [comment]
@rljacob , I bisected the fill-pattern diffs to this CIME PR:

```
Merge pull request #3811 from jedwards4b/seq_io_fix_pio2
    
    Seq io fix pio2
    Don't rely on pio to do data conversions. Note that I used both pio2 and pio1 for these tests.
    
    Test suite: scripts_regression_tests.py, IRT_N2_Ln9.f19_g16_rx1.A.cheyenne_gnu, PET.T62_g16.G.cheyenne_pgi.pop-cice
    Test baseline:
    Test namelist changes:
    Test status: bit for bit
    
    Fixes #3810
    
    User interface changes?:
    
    Update gh-pages html (Y/N)?:
    
    Code review:

```

**Comment by jgfouca** [comment]
I also cherry-picked the crysalis commit.

**Comment by rljacob** [comment]
This PR is also responsible for the filldiffs  https://github.com/ESMCI/cime/pull/3800

**Comment by rljacob** [comment]
The filldiffs are expected and ok.  I'm not sure why that diff is flagged in the SCM test but it looks harmless.

**Review by rljacob — APPROVED** [review]

**Comment by jgfouca** [comment]
Merged to next, thx for the help @rljacob !

**Pull request merged**
