### PR TITLE
Get mappy working again with RHEL9

### PR DESCRIPTION
**Pull request by jgfouca**

### CODE REVIEW

**Review by rljacob — APPROVED** [review]
What kind of testing did you do?

**Review by wadeburgess — COMMENTED** [review]
Do you not need to load a SEMS env? Or run "source /projects/sems/modulefiles/utils/sems-modules-init.sh"

**Comment by rljacob** [comment]
@jgfouca was the overnight testing supposed to work last night?

**Comment by jgfouca** [comment]
@rljacob , I thought it would. Jenkins is able to connect to mappy now and I was able to build and run a couple A cases. Unfortunately, there are more problems coming up. The most concerning is that performance is abysmal and most cases are timing out.

**Pull request merged**
