### PR TITLE
Add script support for ne30_oARRM60to10

### PR DESCRIPTION
**Pull request by jonbob**
This PR brings in script support for fully-coupled cases using the ne30_oARRM60to10 grid resolution. It adds appropriate defaults for mpas-o and mpas-seaice, including spun-up initial conditions from a multi-year G-case run. The coupling frequency is set to a 15-minute default for all components except the ocean, which couples every 30-minutes.

All new mapping and domain files have been staged on the inputdata server.

Since this is a new resolution, all tested configurations are BFB.

[BFB]

### CODE REVIEW

**Comment by stephenprice** [comment]
Thanks Jon. I will admit that I wouldn't necessarily know if there was something wrong here ... but with that caveat in mind, it all looks great to me. Thanks for the help!

**Comment by jonbob** [comment]
Tested with one-year simulation on anvil and passed a smoke test to make sure it found all necessary data out-of-the-box:
SMS.ne30_oARRM60to10_ICG.A_WCYCL1850S.anvil_intel

**Comment by jonbob** [comment]
@stephenprice - we won't know if there are any real issues until we run several years with it. But I think all the pieces are in place to begin that exercise. I'll commit it to maint-1.2 once you review it.

**Comment by stephenprice** [comment]
@jonbob -- consider it 'reviewed', unless by that you mean having us run it out for a bit first. If so, happy to do that from this branch.

**Comment by jonbob** [comment]
@stephenprice - if you have time, could you please officially approve this? There should be a button to add your review... But if not, just let me know and I'll go ahead and merge it without that

**Comment by jonbob** [comment]
Thanks! I'll get it in today so we can crank up a real run whenever we decide it's time

**Comment by jonbob** [comment]
Merged to maint-1.2

**Pull request merged**
