### PR TITLE
[Standalone MPAS-Ocean] Add tracers to dam break initialization

### PR DESCRIPTION
**Pull request by cbegeman**
This PR adds temperature and salinity initialization to the initialization steps for the dam break test case. This is necessary to avoid run time crashes since the fill value feature was merged https://github.com/E3SM-Project/E3SM/pull/5154.

### CODE REVIEW

**Review by sbrus89 — APPROVED** [review]
Approved based on tested this (on Compy) in conjunction with https://github.com/MPAS-Dev/compass/pull/451. Thanks for fixing this @cbegeman!

**Review by xylar — APPROVED** [review]
I tested this on Chrysalis with Intel and Intel-MPI in conjunction with https://github.com/MPAS-Dev/compass/pull/451.  I tested both the 120 cm and 40 cm test cases, with plots attached.

dam_break_comparison_120cm
dam_break_comparison_40cm

**Comment by jonbob** [comment]
passes sanity testing, merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
