### PR TITLE
Update Depends.pgi.cmake to make restarts BFB

### PR DESCRIPTION
**Pull request by amametjanov**
Update Depends.pgi.cmake to make F-compset ERS restarts BFB.

Fixes E3SM-Project/E3SM#4927

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
BFB on a specific platform?

**Comment by rljacob** [comment]
Was this reverted because of the diffs on compy?

**Comment by amametjanov** [comment]
Yes, due to the DIFFs on Compy (https://my.cdash.org/viewTest.php?onlyfailed&buildid=2160265) and new ERP fails on Ascent (https://my.cdash.org/viewTest.php?onlydelta&buildid=2160101)

**Comment by rljacob** [comment]
Notes:  still working on diffs.

**Comment by rljacob** [comment]
What is the status of this PR?

**Comment by amametjanov** [comment]
I'll re-open after isolating the ERP problem.

**Pull request closed without merging**
