### PR TITLE
Remove interface assignment and copy_par subroutine to simplify

### PR DESCRIPTION
**Pull request by ndkeen**
Remove interface assignment and copy_par subroutine as we where not using it anyway.
The nvidia/22.7 compiler was getting confused -- ie, we believe nvidia/22.7 and 22.9 on pm-cpu was doing
something wrong here, but it did point to an issue in the code, which is that because we were not
`include`ing the assignment interface, it was not being used. Which means the default assignment
operation is working fine for this simple data struct and we are confident in removing it.

Note that pm-cpu currently uses nvidia/22.5, which does *not* have this problem. After this PR, I will upgrade to nvidia/22.7.

Unrelated: be more careful about setting initial values for 2 integers in routine.
Example: integer :: ikool=4 is dangerous as we may expect it to be set each entry, but instead, I think it's only set on the first call. Which is fine here as it's only called once, just being more careful.

Fixes https://github.com/E3SM-Project/E3SM/issues/5353
[bfb]

### CODE REVIEW

**Comment by ndkeen** [comment]
Using e3sm_integration, I verified that all tests compare BFB with baselines using GNU, as expected.

**Review by mt5555 — APPROVED** [review]

**Comment by ndkeen** [comment]
merged to next

**Comment by ndkeen** [comment]
Yep!  I see what I did wrong -- was not careful about where the #ifdefs's lie. I guess I need to revert this. fix the branch, and merge again?

**Comment by oksanaguba** [comment]
i think we are allowed to remerge a branch with a fix (when you have a fix), if we can do it quickly. so no need to revert if you could fix it today.

**Comment by ndkeen** [comment]
The branch is updated, but I am not sure how to "remerge"

**Comment by oksanaguba** [comment]
@ndkeen just merge it again, it should work.

**Comment by oksanaguba** [comment]
However, can you run homme suite before merging?

**Comment by ndkeen** [comment]
I reverted the merge.
I checked out next, then did:
```
git revert -m 1 b1fcc593f393260b0ea13cce7128d30ea2d5532f
git push origin next
```

**Comment by rljacob** [comment]
@ndkeen why did you revert instead of just remerging the feature branch (with the fix).  Unless you don't think you can fix it today before testing runs.  Now you have to "revert the revert" when you're ready to remerge this branch.

**Comment by ndkeen** [comment]
It wasn't clear how to do it and I didn't want any more tests to fail because of this silly build error.
We can just make another PR?

**Comment by rljacob** [comment]
Yes you can make a new PR but also rebase the branch (so the hashes are different).

**Pull request closed without merging**
