### PR TITLE
Fixed bug in the stress divergence test case

### PR DESCRIPTION
**Pull request by akturner**
Fixed a bug in the stress divergence test case where extra weight variable was erroneously used in L2 norm calculation

Fixes https://github.com/E3SM-Project/E3SM/issues/4659

[BFB]

### CODE REVIEW

**Review by gcapodag — CHANGES_REQUESTED** [review]
Hi Adrian, per our discussion, I think just that extra weight multiplication has to be removed and no new computation (i.e. the new code) has to be added.
Let's talk on Slack if you'd like. Thanks.

**Comment by rljacob** [comment]
@gcapodag and @akturner is this ready?

**Comment by rljacob** [comment]
@gcapodag and @akturner ping.  Is this ready?

**Comment by gcapodag** [comment]
@rljacob hi! I think I went over the PR last December and left my comments. I do not know if @akturner has implemented them yet.

**Pull request closed without merging**
