### PR TITLE
Update CIME to ESMCI cime5.7.0-4

### PR DESCRIPTION
**Pull request by jgfouca**
Update CIME to ESMCI cime5.7.0-4

Squash merge of jgfouca/branch-for-to-acme-2018-08-09

Features:

* Use information from env_archive.xml to determine history files for baselines and compares.

Bug fixes:
* No python exception with input data server doesn't connect
* improve compiler not support msg

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
I'm still concerned that the commit count is wrong.  The split to ESMCI prior to this had the right amount (83).   The file count and line count is correct here but commits are 1000 or so.

**Comment by rljacob** [comment]
"2192 new commits pushed to `jgfouca/branch-for-to-acme-2018-08-09" is what github said about that branch.

**Comment by jgfouca** [comment]
@rljacob , don't worry, they will be squashed.

**Comment by jgfouca** [comment]
Testing on melvin looks good. Squashing to next.

**Comment by jgfouca** [comment]
This has been squash merged.

**Pull request closed without merging**
