### PR TITLE
Optimze mpibcast for cam/physics and bug fix

### LINKED ISSUE #2461: mpibcast calls with wrong type in cam/src/physics/cam/phys_control.F90
The following was found by @shz0116 in cam/src/physics/cam/phys_control.F90

     integer           :: convproc_method_activate = 2      ! controls activation in the unified convective transport/removal                                                                                                                 
     integer           :: mam_amicphys_optaa   = 0          ! <= 0 -- use old microphysics code (separate calls to gasaerexch,      
     ...          
     call mpibcast(convproc_method_activate,        1 , mpilog,  0, mpicom)
     call mpibcast(mam_amicphys_optaa,              1 , mpilog,  0, mpicom)

Note that the mpibcast calls should use mpiint instead of mpilog.

Shan has a branch that fixes this, and will likely submit a PR in the near future. We do not know how critical this is.

### LINKED ISSUE #2462: inefficient bcast code in cam/src/chemistry/mozart/mo_jlong.F90
The following was identified by @shz0116 in cam/src/chemistry/mozart/mo_jlong.F90 -

     allocate( rsf_tab(nw,nump,numsza,numcolo3,numalb),stat=iret )
     ...
      do w = 1,nw
         call mpibcast( rsf_tab(w,:,:,:,:), numalb*numcolo3*numsza*nump, mpir4, 0, mpicom )
      enddo

This forces internal array copies as well as unnecessary multiple mpibcast calls. The fix, proposed by Shan, is to replace this by

     call mpibcast( rsf_tab, nw*numalb*numcolo3*numsza*nump, mpir4, 0, mpicom )

Shan will be submitting a PR for this, and this is issue will be pointed to by the PR.

### PR DESCRIPTION
**Pull request by shz0116**
1. Change the data type in mpi_bcast for variable
convproc_method_activate and mam_amicphys_optaa from mpilog to mpiint.
2. Change the mpi_bcast in mo_jlong.F90 for variable rsf_tab

Fixes #2461 
Fixes #2462 

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
Can you post a link to the confluence page in the comments here?

**Comment by shz0116** [comment]
Sorry, not sure confluence page you mean.

**Comment by rljacob** [comment]
The PR says "See confluence for a more detailed description about these tags.".

**Comment by shz0116** [comment]
It's automatically generated. I should remove that line.

**Comment by worleyph** [comment]
@shz0116 , I'm editing your PR description, to add the github issue references, for example.

**Comment by singhbalwinder** [comment]
Thanks @shz0116 for creating this PR. It looks good to me. I will wait for @worleyph approval and then integrate it.

**Comment by singhbalwinder** [comment]
merged to next

**Pull request merged**
