### PR TITLE
Add Narwhal, Warhawk, Onyx machines

### PR DESCRIPTION
**Pull request by apcraig**
Port E3SM to several new machines, Narwhal, Warhawk, and Onyx.

A few cases were run on Narwhal, Onyx, and Warhawk to verify port.  Should not affect the scripts or source code nor any other machines.

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
@apcraig does this still need a CIME change with it?

**Comment by apcraig** [comment]
We do need the CIME change, but we'll manage that separately at this point.  It doesn't need to come into E3SM with this PR.  It can come into E3SM whenever it's convenient for E3SM to update CIME.  Until then, it's a one line change in CIME we can do manually if we need it.

**Comment by darincomeau** [comment]
@apcraig I put together a branch with your fix to the mpas component build-namelist scripts to remove use of `Switch`, if you want to test that it works with this branch on these machines:

https://github.com/E3SM-Project/E3SM/tree/darincomeau/scripts/remove-switch-mpas-buildnml

**Comment by apcraig** [comment]
Thanks @darincomeau.  Switch is now installed on two of the DoD platforms and I will test the third when it's available.  It was not available months ago when I did the original port.  While I don't need the Switch fix at the moment, I still think the new implementation that avoids Switch is better and more robust overall and recommend creating a PR request for it.

**Comment by darincomeau** [comment]
Ok thanks @apcraig , that sounds good. I'll start testing that branch on other DOE machines to prepare for a PR.

**Review by darincomeau — APPROVED** [review]
Approving based on developer testing, visual inspection, as well as these mods being used by a user over the last several months in https://github.com/darincomeau/E3SM/tree/E3SMv2-Arctic

**Comment by apcraig** [comment]
FYI, Onyx is back up and confirmed these mods work fine there as well.  All 3 new machines now tested with E3SM master + this PR.

**Comment by jonbob** [comment]
passes sanity testing, merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
