### PR TITLE
Fix restart and area bug in MPAS-SI Conservation Analysis Member

### PR DESCRIPTION
**Pull request by proteanplanet**
This corrects a problem in the MPAS-SeaIce Conservation Analysis member configuration whereby the first month of history after a restart of E3SM was dropped from the analysis history.  Now, with this PR, results from the a restarted simulation are appended to the existing analysis member file for the restart year from the simulation previous to the restart, if such a file exists.   This PR does not change answers in E3SM, but ensures that the new diagnostics on sea ice conservation are able to be calculated seamlessly over hundreds of years, if need be. The PR branch code has been tested in a four-year B-case with annual restarts, for which results are given in comments below subsequent to this pull request. [BFB]

### CODE REVIEW

**Comment by proteanplanet** [comment]
In the figure below, the B-case simulation has been restarted each year for four years, and the data record from the coupler and the Conservation AM for each year have been respectively concatenated, indicating close agreement between the coupler and the analysis member record across restart boundaries. 

20210609_global_0001_0004_NetMass_NetHeat

**Comment by proteanplanet** [comment]
Test simulation output is available at /lcrc/group/e3sm/ac.afroberts/E3SM_simulations/20210609.v2rc2c.ConservationAM.ne30pg2_EC30to60E2r2.chrysalis/run on Chrysalis.

**Review by njeffery — APPROVED** [review]
I tested  the updated conservation analysis member in a 2 month DTEST with restart after one month.  All worked as it should with output written seamlessly between restarts.

**Comment by njeffery** [comment]
@proteanplanet :  There was one odd thing I noticed in the ice.log file.  The Sea ice area diagnostics, which I haven't noticed before,  often exceeds the Earth area and the domain area.

**Comment by proteanplanet** [comment]
@njeffery Thanks for checking the area. I've found (at least) one bug in the area calculations and am testing that now in a B-case. I'll update and ask you to look over the output for a new test soon.

**Comment by proteanplanet** [comment]
This PR now includes the addition of a no-compute on restart for the conservation AM, which does not change results relative to this option being switched off.  In addition, a bug was corrected in the latest commit so that the area statistics provided in the MPAS-SI log files are now correct.  Results follow. Location for test simulation with yearly restart is at:

`/lcrc/group/e3sm/ac.afroberts/E3SM_simulations/20210609.v2rc2c.ConservationAM2.ne30pg2_EC30to60E2r2.chrysalis/run`

20210609_global_0001_0004_NetMass_NetHeat

`===================================================================================
  Conservation checks: 0007-01-01_00:00:00
 -----------------------------------------------------------------------------------
  Area analysis                                 Global             NH             SH

  Earth radius                   (m) =    6.371229E+06
  Earth area                    (m2) =    5.101011E+14
  Domain area                   (m2) =    3.603951E+14   1.537943E+14   2.066007E+14
  Sea-ice area                  (m2) =    2.295497E+13   1.246381E+13   1.049116E+13`

@njeffery and @akturner please review now that the correction has been fixed and tested.

**Review by njeffery — APPROVED** [review]
The sea-ice area diagnostic looks good now.  As well, changing the default to no-compute on restart cleans up the conservation check in the log file.  My approval stands.

**Review by akturner — APPROVED** [review]

**Comment by jonbob** [comment]
@proteanplanet - I hate to say this, but the branch name does not meet the naming conventions

**Pull request closed without merging**
