### PR TITLE
[WIP] NA-WC14to60 RRM coupled configuration

### PR DESCRIPTION
**Pull request by ambrad**
Set up this configuration.

[BFB]

### CODE REVIEW

**Comment by ambrad** [comment]
@tangq this PR sets up the coupled RRM configuration. It runs out of the box on Compy with
```
set compset = A_WCYCL1850
set resolution = northamericax4v1pg2_r0125_WC14to60E2r3 # _ICG for ocn/ice ICs doesn't work yet
set processor_config = S # S,M,L
```
@ndkeen set up some nice S,M,L PE layouts. S in particular runs on Compy's short queue without monopolizing it.

@jonbob and others, I'll ask you to review this PR later, but for now I've marked it as WIP because we shouldn't merge it until Qi tries it out and we complete any necessary iterations. I'll also eventually ask you for what I should do about the _ICG config.

Once Cori-KNL is back, I'll work with Noel to get some nice PE layouts for that machine. That can go in a separate PR if this one is ready to merge sooner.

**Comment by tangq** [comment]
This is great, @ambrad 

What ocn/ice ICs are used in this configuration?

**Comment by ambrad** [comment]
@tangq, for
```
set compset = A_WCYCL1850
set resolution = northamericax4v1pg2_r0125_WC14to60E2r3
```
there are no ocn/ice ICs. The compset _with_ ICs will use
```
set resolution = northamericax4v1pg2_r0125_WC14to60E2r3_ICT
```
but unless anything has changed, there are no ocn/ice ICs available yet. @maltrud or @jonbob, when you have a chance, would you clarify the status of ocn/ice ICs? Also, when they are available, what is the correct setting for the `set compset = ` line? Thanks.

**Comment by ambrad** [comment]
BTW, in case this isn't obvious: This branch is currently up to date with master.

**Comment by jonbob** [comment]
@ambrad - the WC14to60E2r2 PR I merged to next today does point at some IC files to be used with the _ICG configurations. Just know they're spunup just a month, enough that you shouldn't have to worry about initialization issues but not really enough to impact the results much. I imagine they will be replaced later but for now should be functional.

**Comment by ambrad** [comment]
@jonbob, great, thanks. I ran
```
set compset = A_WCYCL1850S_CMIP6
set resolution = northamericax4v1pg2_r0125_WC14to60E2r3_ICG
```
and it reports looking for the ICs
```
ocn/mpas-o/WC14to60E2r3/mpaso.WC14to60E2r3.rstFromG-anvil.201002.nc
ice/mpas-cice/WC14to60E2r3/mpassi.WC14to60E2r3.rstFromG-anvil.201002.nc
```
during configuration. Then it starts time-stepping successfully. So, assuming the `compset` setting is correct, this looks good.

**Comment by jonbob** [comment]
That looks perfect, @ambrad. And I mis-spoke (mis-wrote?) -- I merged that PR to master yesterday, not next. In any case, the compset and resolution both look correct to me

**Comment by maltrud** [comment]
@jonbob just to be clear, the PR you referred to 14 hours ago was for the WC14to60E2r3, not WC14to60E2r2, right?

**Comment by jonbob** [comment]
@maltrud -- thanks for catching that! I'm getting confused by working on the EC30to60E2r2 and WC14to60E2r3 at the same time -- too many r's. The WC14to60E2r3 PR went to master yesterday and the EC30to60E2r2 went to next

**Comment by ambrad** [comment]
@wlin7 this is still a WIP, so let's not integrate until everybody is satisfied with the configuration. Thanks.

**Comment by ambrad** [comment]
@tangq now that Cori-KNL is back up, we can start putting together S,M,L PE layouts. Where are the files on Cori-KNL corresponding to these?

- /compyfs/tang338/ForAndrew/20200106.alpha20.amip.northamericax4v1_r0125_northamericax4v1.cori-knl.cam.i.1981-01-01-00000.nc
- /compyfs/tang338/ForAndrew/20200106.alpha20.amip.northamericax4v1_r0125_northamericax4v1.cori-knl.clm2.r.1981-01-01-00000.nc

Thanks.

**Comment by tangq** [comment]
@ambrad , they are located at /global/cscratch1/sd/tang30/E3SM_simulations/20200106.alpha20.amip.northamericax4v1_r0125_northamericax4v1.cori-knl/archive/rest/1981-01-01-00000

Shall we use the pg2 version? If so, the files are at /global/cscratch1/sd/tang30/E3SM_simulations/20200701.v1like.f2010.northamericax4v1pg2_r0125_northamericax4v1pg2.cori-knl/archive/rest/0012-01-01-00000

**Comment by ambrad** [comment]
Yes, I'll use the pg2 version. Thanks.

**Comment by rljacob** [comment]
What is the status of this PR?

**Comment by ambrad** [comment]
We're working through RRM v2 issues and so far have elected to wait to request to merge this PR until we have established the final settings.

**Comment by rljacob** [comment]
Should this be closed since we're switching to bi-grid?

**Comment by ambrad** [comment]
Yes, that makes sense. We can reopen later if needed.

**Pull request closed without merging**
