### PR TITLE
Shorten BGC coupled tests

### PR DESCRIPTION
**Pull request by rljacob**
Shorten the BGC coupled tests in e3sm_integration to 2 days.
These were taking the most time.

[BFB] but test name will change.

### CODE REVIEW

**Comment by rljacob** [comment]
These are easily some of the most expensive tests in integration.

**Comment by jonbob** [comment]
@rljacob - I have no problem with this, but the results won't be BFB

**Comment by rljacob** [comment]
But the 2 days will be identical in both runs right?  There's no way for our test system to recognize that because the test name changes with the addition of "Ld2".   Did we previously use "non-BFB" for a new test or test name change?

**Comment by jonbob** [comment]
You're right -- it will be a new test name and have new results. I'm not sure how we have documented those kinds of changes before

**Comment by rljacob** [comment]
Lets leave this case as BFB.  The non-BFB tag should be added if any existing test will change answers.

**Comment by jonbob** [comment]
that makes sense -- sorry to make a mess of it

**Pull request merged**
