### PR TITLE
Fixing CFL-related crash in long ne4 F compset runs

### LINKED ISSUE #3430: ne4 fails with FC5AV1C-L compset
The FC5AV1C-L simulation on ne4 using the current master fails midway through month 7 with a "vertical layer thickness" error.

This behavior has been reproduced on several machines:
1) Livermore Computing - quartz - nstep=1705 (user Aaron Donahue)
2) NERSC - Cori-KNL - nstep=1648 (user Chris Terai)
3) Sandiatoss3 - ghost - nstep=1564 (user Ben Hillman)*

git hash: ae200d3bd8f43f1bad7539c659e86794c1a5d463) 
from: Feb 4th, 2020 

*The sandiatoss3 simulation was conducted using the scream-fork but shortly after an upstream merge from e3sm.

### PR DESCRIPTION
**Pull request by oksanaguba**
Reducing remap dt. This ran for 10 years.

Fixes #3430 .

[nonbfb] for most of ne4 tests.

### CODE REVIEW

**Comment by oksanaguba** [comment]
I will run atm_integrator tests before pushing.

**Comment by mt5555** [comment]
the nu_div I think was a false alarm (CFL is not violated).  can we leave that unchanged?

**Comment by oksanaguba** [comment]
Do you mean that what is printed in the output is not accurate in preqx? (i never remember this). i will re-run with old nu_div.

**Comment by mt5555** [comment]
since reducing nu_div alone was insufficient (model still crashes), but other things (with the default nu_div) would allow the model to run, it seems this crash is unrelated to nu_div.   There still could be an issue with nu_div being too large, but lets save that for a different PR.

**Comment by oksanaguba** [comment]
Against corresponding master for atm_integration suite,
```
(base) [onguba@blueslogin1 ~]$ ~/as/cs.status.20200207_133543_hrrq7u  | grep FAIL
    FAIL ERP_Ln9.ne4_ne4.F-EAMv1-AQP1.anvil_intel NLCOMP
    FAIL ERP_Ln9.ne4_ne4.F-EAMv1-AQP1.anvil_intel BASELINE master: DIFF
    FAIL ERS_Ld5.ne4_ne4.FC5AV1C-L.anvil_intel.cam-gust_param NLCOMP
    FAIL ERS_Ld5.ne4_ne4.FC5AV1C-L.anvil_intel.cam-gust_param BASELINE master: DIFF
    FAIL ERS_Ld5.ne4_ne4.FC5AV1C-L.anvil_intel.cam-rrtmgp NLCOMP
    FAIL ERS_Ld5.ne4_ne4.FC5AV1C-L.anvil_intel.cam-rrtmgp BASELINE master: DIFF
    FAIL PEM_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel NLCOMP
    FAIL PEM_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel BASELINE master: DIFF
    FAIL PET_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel.allactive-mach-pet NLCOMP
    FAIL PET_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel.allactive-mach-pet BASELINE master: DIFF
    FAIL REP_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel NLCOMP
    FAIL REP_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel BASELINE master: DIFF
    FAIL SMS_D_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel.cam-cosplite_nhtfrq5 NLCOMP
    FAIL SMS_D_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel.cam-cosplite_nhtfrq5 BASELINE master: DIFF
    FAIL SMS_Ld1.ne4_ne4.F-EAMv1-AQP1.anvil_intel.cam-clubb_only NLCOMP
    FAIL SMS_Ld1.ne4_ne4.F-EAMv1-AQP1.anvil_intel.cam-clubb_only BASELINE master: DIFF
    FAIL SMS_Ld1.ne4_ne4.F-EAMv1-AQP1.anvil_intel.cam-clubb_only TPUTCOMP Error: Computation time increase > 10 pct from baseline
    FAIL SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-preqx_ftype0 NLCOMP
    FAIL SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-preqx_ftype0 BASELINE master: DIFF
    FAIL SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-preqx_ftype1 NLCOMP
    FAIL SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-preqx_ftype1 BASELINE master: DIFF
    FAIL SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-preqx_ftype4 NLCOMP
    FAIL SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-preqx_ftype4 BASELINE master: DIFF
```
All is as expected, theta tests did not fail because they redefine nsplit and rsplit .

**Comment by oksanaguba** [comment]
in next

**Pull request merged**
