### PR TITLE
Update mpas-source: init mode, COMPASS, minor ice shelf diagnostics

### PR DESCRIPTION
**Pull request by mark-petersen**
These changes are all related to the creation of initial conditions for ice shelves. It does not alter forward simulations without ice shelves.

[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
merged to next

**Comment by mark-petersen** [comment]
@jonbob I updated the mpas-source to include: 
Add mpas_ocn_init_smoothing.F to ocean.cmake

Sorry, I'll check that from now on. Stand-alone does not compile with cmake yet.

**Comment by jonbob** [comment]
Really strange to me that my tests passed on anvil? But re-merging now...

**Comment by jonbob** [comment]
re-merged to pick up filename added to ocean.cmake

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
