### PR TITLE
Fixes ELM build for PGI on Compy

### LINKED ISSUE #3196: ELM fails to build on Compy with PGI
```
Errors were:
        Building test for SMS in directory /compyfs/e3smtest/e3sm_scratch/J/SMS_D_Ln5.conusx4v1_conusx4v1.FC5AV1C-L.compy_pgi.JNextIntegration20190923_094740
        ERROR: BUILD FAIL: clm.buildlib failed, cat /compyfs/e3smtest/e3sm_scratch/SMS_D_Ln5.conusx4v1_conusx4v1.FC5AV1C-L.compy_pgi.JNextIntegration20190923_094740/bld/lnd.bldlog.190923-095748
```

### PR DESCRIPTION
**Pull request by bishtgautam**
Minor change to avoid build failure with PGI/18.10 on Compy

Fixes #3196

### CODE REVIEW

**Comment by singhbalwinder** [comment]
I think more people should be aware of issues like these. I ran into exactly the same issue but with some other file. @jgfouca helped me to fix it. The issue itself and the fix doesn't make sense but it is required to make cmake happy.

**Comment by jgfouca** [comment]
This stuff will be fixed when we integrate the big Cmake PR. I'm going to set our default backend to be ninja, which fixes this issue.

**Comment by mrnorman** [comment]
Do we have PGI nightly testing in place on Compy at the moment to keep this from happening again?

**Comment by brhillman** [comment]
Are any nightly tests using PGI? It’d be nice for PGI build issues to be protected against when new PRs are merged. It frequently causes us problems on the ACME-ECP code when we pull changes from E3SM, and as we can only really run with PGI on Summit for our OpenACC code, it’s pretty critical to us.

**Comment by singhbalwinder** [comment]
We have nightly tests running on Compy with PGI. Wade, Rob, Gautam and I are currently working on fixing compile and run time issues with PGI.

I think Summit is also suppose to have tests using PGI but I am not sure about the progress on that front.

**Comment by brhillman** [comment]
@singhbalwinder that’s great we are testing on Compy with PGI now. Summit with PGI tests would be incredibly helpful for us as well.

**Comment by rljacob** [comment]
@minxu74 was going to run them by hand on Summit?

**Comment by minxu74** [comment]
@mrnorman @rljacob I had a script to build (not run) the test suite on Summit and push the results to cdash several months ago. But at that time, it took nearly 12 hours to finish building the test suite using xlf compiler, so I stopped it and I will try it again next week.

**Comment by jqyin** [comment]
Merged #3197

**Pull request merged**
