### PR TITLE
Update descriptions of `dcEdge` and `dvEdge`

### PR DESCRIPTION
**Pull request by xylar**
This PR just updates the metadata that will be produced in files that contain the MPAS mesh.

The description of these two variables has been updated to help developers (and users) better understand what they mean.

### CODE REVIEW

**Comment by xylar** [comment]
This PR was discussed and reviewed in https://github.com/E3SM-Ocean-Discussion/E3SM/pull/99

**Review by proteanplanet — APPROVED** [review]
Previously reviewed in Ocean Discussions, and approved accordingly here.

**Review by matthewhoffman — APPROVED** [review]
Approving based on my review in Ocean-Discussions.

**Comment by jonbob** [comment]
@xylar -- I ran the scripts to make sure the Registry changes didn't impact the old files for any component. It didn't turn up anything due to this PR, but did find a couple of small issues in mpassi that had somehow snuck in. I can either add them to this PR or make a separate PR to clean them up

**Comment by xylar** [comment]
@jonbob, sure, please include them here.

**Comment by jonbob** [comment]
passes sanity testing, merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
