### PR TITLE
Changing default NetCDF format to CDF5 and updating SCORPIO to v1.6.5

### PR DESCRIPTION
**Pull request by jayeshkrishna**
The CDF5/64bit_data format gets rid of limitations (for all practical
purposes) on NetCDF variable size imposed by the older
CDF2/64bit_offset file format.

Also updating SCORPIO to v1.6.5

[BFB]
[NML]

### CODE REVIEW

**Review by dqwu — APPROVED** [review]

**Review by rljacob — APPROVED** [review]

**Comment by jayeshkrishna** [comment]
* This PR assumes that all machines and tools (like cprnc) have support for PnetCDF or NetCDF (> 4.4.0). The cprnc tool on Anvil was re-built by @amametjanov with the latest modules to add support for CDF5.
* This PR also causes runtime issues (when writing large variables) with SCORPIO version < 1.6.5 on machines that do not support PnetCDF (e.g. mappy)

**Review by rljacob — APPROVED** [review]
Update the title and description to mention that SCORPIO is also updated.

**Review by dqwu — APPROVED** [review]

**Comment by jayeshkrishna** [comment]
> The following line should be edited in scorpio submod (potentially with a patch release or something?) https://github.com/E3SM-Project/scorpio/blob/db9ea40da9fed50c8cdf6a7fa7f1a4d8e5aa1b00/CMakeLists.txt#L317

The next release of SCORPIO will include the version check for the NetCDF fortran library (it already includes the check for the NetCDF library) - to verify that it supports CDF5
FYI, this support has been around for a while and all E3SM machines should have a version of NetCDF library that supports CDF5

**Comment by jayeshkrishna** [comment]
This PR introduces NML changes for the tests since it changes the default I/O type in the nameless,
```
Comparison failed between 'xxx_modelio.nml' with 'xxx_modelio.nml'
  BASE: pio_netcdf_format = '64bit_offset'
  COMP: pio_netcdf_format = '64bit_data'
```

**Pull request merged**
