### PR TITLE
Fix gas dry deposition for VBS SOAG gas species

### PR DESCRIPTION
**Pull request by mingxuanwupnnl**
This PR fixes the issue #5963  on dry deposition of VBS SOAG gases. Dry deposition for VBS SOAG gas species, namely SOAG0, SOAG15, SOAG24, SOAG35, SOAG34, SOAG33, SOAG32, SOAG31, is now included in shared seq_drydep_mod.F90 and namelist drydep_list.

[CC]
[NML]

### CODE REVIEW

**Comment by mingxuanwupnnl** [comment]
@mkshriva I'd appreciate if you could help me double check the setting in seq_drydep_mod.F90 Note that I changed molecular weight for SOAG gas from 250._r8 to 250.445_r8, the latter one is used in model. Thank you. 

@wlin7 could you help me double check if changing seq_drydep_mod.F90 under driver-mct/shr is good enough. I saw multiple places having seq_drydep_mod.F90. Also, not sure if changing those four use_case xml files are good. I saw scm xml files also have vbs setting, not sure if anyone use that. Thank you.

@hwangacme could you help me double check the code? In case I made any silly mistakes. Thank you.

**Review by hwangacme — APPROVED** [review]

**Review by mkshriva — APPROVED** [review]

**Comment by wlin7** [comment]
@mingxuanwupnnl , sorry for the late response. The changes are good. Only need to make the changes for driver-mct version for now. When migrating to moab, all files there will be copied over.  The four use_cases files are all that matter at current state. Eventually we do also need to make the changes for SCM and SSP use cases. Esp. for SSP files, they are not ready anyway.

**Comment by wlin7** [comment]
Merged to next.

**Comment by wlin7** [comment]
Merged to master.

**Pull request merged**
