### PR TITLE
Disable land ice frazil unless ISMF is on

### PR DESCRIPTION
**Pull request by cbegeman**
This PR turns land ice frazil off by default and re-enables it when ice-shelf melt fluxes are enabled in standalone or coupled mode. Land ice frazil is not enabled in data ISMF because frazil fluxes are already included in satellite-derived ISMF products.

[NML]
[non-BFB] when ice-shelf cavities are present in the mesh and (ocn_ismf is off or ocn_ismf is data)
[BFB] when ice-shelf cavities are absent from the mesh or ice-shelf cavities are present in the mesh and (ocn_ismf is coupled or ocn_ismf is internal)

### CODE REVIEW

**Comment by cbegeman** [comment]
Further discussion located at https://github.com/E3SM-Ocean-Discussion/E3SM/pull/101

**Review by xylar — APPROVED** [review]
Approving based on code inspection and previous review in https://github.com/E3SM-Ocean-Discussion/E3SM/pull/101

**Comment by xylar** [comment]
This will affect current production runs so will need to wait for `maint-3.0` to be created.

**Review by darincomeau — APPROVED** [review]
Approved based on review in Ocean Discussions PR.

**Comment by jonbob** [comment]
@cbegeman -- would you expect this PR to cause non-BFB behavior for a typical IcoswISC30E3r5 fully-coupled case?

**Comment by xylar** [comment]
@jonbob, that would be expected because there was frazil forming in the otherwise inactive cavities in WCYCL cases.  That is the main reason we wanted to turn it off here -- we don't want that behavior when cavities are inactive.

**Comment by jonbob** [comment]
Thanks @xylar. Do we have a long-ish comparison run to document the changed behavior then? I didn't see anything on the discussions page

**Comment by darincomeau** [comment]
When this first came up several months ago, we quantified the impact of the unintentional land-ice frazil term in a WCYCL1850 case and confirmed it was very small. But we did not actually do a run with the desired behavior added here, where land-ice frazil is off when ice-shelf cavities are otherwise thermodynamically inactive (e.g. WCYCL cases).

I've started that run now on Anvil, will update.

**Comment by rljacob** [comment]
@darincomeau any update?

**Comment by darincomeau** [comment]
>@darincomeau any update?

[The run is in year 20 now](https://acme-climate.atlassian.net/wiki/spaces/PSC/pages/4732452865/20241030.v3.LR.piControl-land-ice-frazil.anvil), I think we were going to assess climate impact (relative to v3 piControl) at year 20 or 30.

**Comment by darincomeau** [comment]
From MPAS-devops call; will evaluate at year 30 to determine if it needs to be run longer.

**Comment by rljacob** [comment]
@darincomeau any update?

**Comment by darincomeau** [comment]
@rljacob sorry for the delay, the run finished 50 years and I've been trying to get comparative analysis run today to post here.

**Comment by darincomeau** [comment]
MPAS-Analysis this PR vs. v3.LR.piControl years 1 - 50:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.dcomeau/E3SMv3_dev/20241030.v3.LR.piControl-land-ice-frazil.anvil/mpas_analysis/vs-piControl/yrs1-50/

**Comment by xylar** [comment]
The results from MPAS-Analysis show ensemble-level variability.  Even in temperature and salinity time series on the Antarctic continental shelf, where the presence or absence of frazil would have the biggest effect, don't show any discernible offset from one another to suggest anything other than ensemble-level differences.

**Comment by cbegeman** [comment]
> The results from MPAS-Analysis show ensemble-level variability. Even in temperature and salinity time series on the Antarctic continental shelf, where the presence or absence of frazil would have the biggest effect, don't show any discernible offset from one another to suggest anything other than ensemble-level differences.

I also took a look at the MPAS-Analysis page and agree with this assessment

**Comment by rljacob** [comment]
@proteanplanet you want this to wait on your approval?

**Review by proteanplanet — APPROVED** [review]
Approved, and also flagging @njeffery in reference to another PR on Frazil in the works for BGC.

**Comment by jonbob** [comment]
Testing with:
* ERP_Ld3.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-pioroot1

shows expected NML and baseline DIFFs

merged to next

**Comment by rljacob** [comment]
Some tests with ne30pg2_r05_IcoswISC30E3r5 had no baseline diffs.  Was that expected?

**Comment by jonbob** [comment]
@rljacob - yes, depending on the ocn_ismf setting

**Comment by xylar** [comment]
And thanks @cbegeman for getting this through!

**Comment by jonbob** [comment]
merged to master and expected NML and baseline DIFFs blessed -- except for pm-cpu where only landice_developer has reported

**Comment by cbegeman** [comment]
Thanks for all your testing @jonbob! And thanks @proteanplanet @xylar @darincomeau for your reviews

**Comment by jonbob** [comment]
pm-cpu also reported, and expected DIFFS blessed

**Pull request merged**
