### PR TITLE
Merge maint-1.1 (and maint-1.0) to master (Feb2020)

### PR DESCRIPTION
**Pull request by rljacob**
Merge of maint-1.1 branch (which had maint-1.0 merged to it) to master.

This should bring master in sync with any developments that were only on maint-1.0 or maint-1.1

Driver: in config_compsets, add more CCSM_CO2_PPMV values

EAM:  Add V100 diag
      Add AODALL to compute total aerosol
      Allow outputting BURDEN variables when history_aero_optics is true.

ELM:  add cbgc land diagnostic variables
      rename the C,N,P veg to cwd fluxes, add corresponding N and P fluxes
      add diagnostic output variable fVegCWDC, due to C4MIP tier 1 requirement
      Fix bugs in  SEN_NLOSS_LITTER and SEN_PLOSS_LITTER diagnostics
      add total litter flux diags
      Support SSP585 compsets
      update ECA paramater files.
      update flanduse_timeseries in 20thC_CMIP6bgc_transient

In EAM and ELM: Convert all use cases to use netcdf3 input files if they were using netcdf4 (mostly CMIP6 cases)

DOCN:, add SSTICE_DATA_FILENAME for
2010_ ne30,  2010_ ne120
add SSTICE_GRID_FILENAME for
2010_ ne120

Add the following compsets:
BGCEXP_BCRC_CNPRDCTC_SSP585_CMIP6

BGCEXP_BCRD_CNPRDCTC_SSP585_CMIP6
BGCEXP_BCRD_CNPRDCTC_SSP585_CMIP6S
BGCEXP_BDRC_CNPRDCTC_SSP585_CMIP6
BGCEXP_BDRC_CNPRDCTC_SSP585_CMIP6S
BGCEXP_BDRD_CNPRDCTC_SSP585_CMIP6
BGCEXP_BDRD_CNPRDCTC_SSP585_CMIP6S

BGCEXP_BCRC_CNPECACNT_SSP585_CMIP6
BGCEXP_BCRC_CNPECACNT_SSP585_CMIP6S
BGCEXP_BCRC_CNPECACNT_20TRS  T

BGCEXP_BCRD_CNPECACNT_SSP585_CMIP6
BGCEXP_BCRD_CNPECACNT_SSP585_CMIP6S
BGCEXP_BCRD_CNPECACNT_20TRS

BGCEXP_BDRC_CNPECACNT_SSP585_CMIP6
BGCEXP_BDRC_CNPECACNT_SSP585_CMIP6S
BGCEXP_BDRC_CNPECACNT_20TRS

BGCEXP_BDRD_CNPECACNT_SSP585_CMIP6
BGCEXP_BDRD_CNPECACNT_SSP585_CMIP6S
BGCEXP_BDRD_CNPECACNT_20TRS

BGCEXP_CNTL_CNPECACNT_1850S  T

F2010C5-CMIP6-LR
F2010C5-CMIP6-HR

Also add testmod directories for cases with a "T" above so the namelist 
settings will be the same as production runs. 

[non-BFB] for 1850 BGC coupled compsets and eca I-cases

### CODE REVIEW

**Comment by rljacob** [comment]
Haven't done any testing yet.

**Comment by rljacob** [comment]
So far testing is showing a problem in the allactive/config_components.xml.   CIME thinks there is a duplicate alias but I can't find it.  It passes an xmllint check.  If anyone else can look at it, I'd appreciate it.  Just try to build any case on this branch to duplicate.  For example. ./create_newcase --case Xtry --compset X --res f19_g16

There's also a CIME issue because the error message isn't helping.  https://github.com/ESMCI/cime/issues/3426

**Comment by rljacob** [comment]
Nevermind.  Found the problem.

**Comment by susburrows** [comment]
@rljacob : Looking this over quickly, it looks like the configuration settings that had been implemented in the run_e3sm script are now in the testmods directory so that the tests will run.  Would it be preferable for those changes (e.g., compile options and default tunings) to be triggered automatically whenever the compset is used (and not only when the test suite is run)?  (or maybe I'm misunderstanding what's been done here for the test suites)

**Comment by rljacob** [comment]
@thorntonpe there are a bunch of history fields that are declared in places like ColumnDataType.F90 but they are still in WaterfluxType.F90 in maint-1.1.  Where should they go?  The merge currently has them in both places which results in a run-time error.

**Comment by thorntonpe** [comment]
@rljacob The history variables that are in the newer files (e.g. ColumnDataType.F90) should be there and not in the older files (e.g. WaterfluxType.F90). I removed those from the older files for my development - I'm a little worried that those deletions are not being merged correctly by default. Do you know why they don't get picked up from my commits?

**Comment by rljacob** [comment]
@thorntonpe there were a lot of conflicts in that older file and I resolved them incorrectly (using mostly the maint-1.1 version).  Now that I know the right way, I can fix it.

@susburrows extra history variables should always be in a test mod (or run script) assuming they are only interesting in production runs.   But other config settings should be in the use-case for the compset if they should always be active for that compset.

**Comment by rljacob** [comment]
e3sm_land_developer passes on compy.

@kvcalvin or @susburrows should "CNTL" be used in the BGC compset names?  This is not consistent between maint-1.1 and master.

For example this longname:
`1850_CAM5%CMIP6_CLM45%CNPRDCTCBC_MPASCICE%BGC_MPASO%OIECOOIDMS_MOSART_SGLC_SWAV_BGC%BCRC
`
Is BGCEXP_CNTL_CNPRDCTC_1850 on maint-1.1 and BGCEXP_BCRC_CNPRDCTC_1850 on master.

**Comment by susburrows** [comment]
Hi Rob, that compset should be "CNTL" as it is on maint-1.1 (since it's the 1850 pre-industrial control).  Are there other examples that conflict?

**Comment by rljacob** [comment]
Yes.  "CNTL" isn't in any of the BGC compsets currently on master.   These also look like they have the wrong name: 
```
 BGCEXP_BCRC_CNPRDCTC_1850S,
BGCEXP_BCRC_CNPECACNT_1850
```
I can fix it on this branch.

**Comment by susburrows** [comment]
Thanks for catching this, Rob,  The 1850 compsets should all be "CNTL".  "BCRC" should only be used for transient compsets.  I remember that we fixed this somewhere along the development path; it must have been after we branch maint-1.1 from master.

**Comment by rljacob** [comment]
Another question:  can restart files from maint-1.1 be read by latest master?  ELM in particular.

**Comment by susburrows** [comment]
I suspect not.  @thorntonpe can you comment?

**Comment by thorntonpe** [comment]
I think restart files are not compatible, in part because of new subgrid architecture, and also new state variables.

**Comment by rljacob** [comment]
The bgc production suite now passes.   The finidat for ELM had to be set to a cold start since the old ones don't work with master.  Also had to add a few history calls.

**Comment by rljacob** [comment]
This is now ready for a more complete review.

Things to check if they look ok or still work:
@wlin7   that your extra EAM diags 
@singhbalwinder  your AODALL diag 
@qzhu-lbl : your extra land diags. Note the hist_addfld1d calls are now all in files in d
ata_types dir
@bishtgautam : your land water budget and diag fixes

To run the bgc test suite on this branch, you can do:
./create_test e3sm_bgcprod

**Comment by rljacob** [comment]
e3sm_integration passes on compy so I will merge this on Thursday unless there are any objections.

**Comment by rljacob** [comment]
Merging today.

**Comment by rljacob** [comment]
For the 1850 BGC compsets, this PR changes  co2vmr_rad	 fomr 284.7 to  284.317 so it will not be BFB for those compsets.

**Comment by rljacob** [comment]
@jayeshkrishna @dqwu I need help debugging a runtime fail on next.  I'm seeing this message:
```
PIO: WARNING: Opening file (/projects/ccsm/inputdata/lnd/clm2/paramdata/CNP_parameters_c180312.nc) with iotype=1 (PIO_IOTYPE_PNETCDF) failed. Retrying with iotype=PIO_IOTYPE_NETCDF
PIO: FATAL ERROR: Aborting... FATAL ERROR: NetCDF: Unknown file format (/gscratch/jenkins/skybridge-slave/workspace/ACME_Skybridge_next/ACME/externals/scorpio/src/clib/pioc_support.c: 2849)
```
But the file on the server, CNP_parameters_c180312.nc, is CDF1.

**Comment by dqwu** [comment]
@rljacob 
Which machine and which test can reproduce this error?

**Comment by rljacob** [comment]
Sandiatoss3.  I think they have a corrupt version of that file so hang on.

**Comment by dqwu** [comment]
@rljacob 
Could be corrupted file on Sandiatoss3. The error messages indicate that even opening it with plain old basic NetCDF fails. I downloaded that input file for anlworkstation and it can be opened with PnetCDF without errors.

**Comment by rljacob** [comment]
The tests that are failing at Sandia are:
```
ERS.f19_g16.I1850CNECACNTBC.sandiatoss3_intel.clm-eca
ERS.f19_g16.I1850CNECACTCBC.sandiatoss3_intel.clm-eca
ERS.f19_g16.I1850GSWCNPECACNTBC.sandiatoss3_intel.clm-eca_f19_g16_I1850GSWCNPECACNTBC
ERS.f19_g16.I20TRGSWCNPECACNTBC.sandiatoss3_intel.clm-eca_f19_g16_I20TRGSWCNPECACNTBC
```

Those tests all passed for me compy using intel.

**Comment by dqwu** [comment]
@rljacob 
On Sanidatoss3, we can use a small PnetCDF application to check that input file.
```
#include <stdio.h>
#include <mpi.h>
#include <pnetcdf.h>

#define ERR { if (err != NC_NOERR) { printf("Error at line = %d: %s\n", __LINE__, ncmpi_strerror(err)); nerrs++; } }

int main(int argc, char** argv)
{
  int err, nerrs = 0;
  int ncid;

  MPI_Init(&argc, &argv);

  err = ncmpi_open(MPI_COMM_WORLD, "/projects/ccsm/inputdata/lnd/clm2/paramdata/CNP_parameters_c180312.nc",
                   NC_NOWRITE, MPI_INFO_NULL, &ncid); ERR

  err = ncmpi_close(ncid); ERR

  MPI_Finalize();

  return nerrs;
}
```
@jayeshkrishna 
Can scorpio's new spio_finfo tool check whether a NetCDF file is corrupted or not?

**Comment by rljacob** [comment]
We verified that the problem was a corrupt file.  A new one was downloaded and tonight's test run should be better.

**Comment by rljacob** [comment]
Sandiatoss fails are now diffs.  But the same file must be bad on melvin.

**Comment by rljacob** [comment]
These tests are failing on sandiatoss3 with no helpful error messages:
```
ERP_Ld3.ne30_oECv3_ICG.A_WCYCL1850S.sandiatoss3_intel
PEM_Ln9.ne30_oECv3_ICG.A_WCYCL1850S.sandiatoss3_intel
SMS_D_Ln5.conusx4v1_conusx4v1.FC5AV1C-L.sandiatoss3_intel
```

**Comment by rljacob** [comment]
The error messages for those 3 cases on sandiatoss 3 look like:
```
[sb1795:170190] *** Process received signal *** 
[sb1795:170183] *** Process received signal *** 
[sb1795:170190] Signal: Bus error (7) 
[sb1795:170190] Signal code:  (4056)
```

Using the same version of next, can not reproduce on compy (intel19) or anvil (Intel17)

**Comment by rljacob** [comment]
Compared namelists for each case using this and previous version of next (4f006929).  The conus case has on differences.  The 2 coupled cases only difference is the latest version  do_budgets = .true.

**Comment by amametjanov** [comment]
Bus errors appear to be memory related. PE-layouts for the three tests with bus errors used to have 128 tasks and now are at 16 tasks.

**Comment by rljacob** [comment]
Yes those pe-layouts were the problem and the 3 tests above now pass.  Thanks @amametjanov !

**Pull request merged**
