### PR TITLE
mpas clean-up: remove compass/ocean, add docs template

### PR DESCRIPTION
**Pull request by mark-petersen**
This merge removes the ocean core from COMPASS, because it has moved to https://github.com/MPAS-Dev/compass. Also adds a template to the docs folder. These changes have no impact on E3SM.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
@jonbob This passed a few E3SM sanity tests. I just rebased, but will rebase again tomorrow after master is updated, so the PR merge is clean.

**Comment by jonbob** [comment]
@mark-petersen - sounds good. I'll merge to master as soon as I can tomorrow, to give you as much time to prep this one

**Review by jonbob — COMMENTED** [review]
@mark-petersen - does this just make changes to the ocean core?

**Comment by mark-petersen** [comment]
Rebased. Now only shows changes for this PR.

> @mark-petersen - does this just make changes to the ocean core?

Yes. It removes all contents of `testing_and_setup/compass/ocean`, which is the part of compass that only pertains to the ocean. It also adds a template to `docs/ocean`.

**Comment by jonbob** [comment]
@mark-petersen - I asked about this PR being ocean-specific because the branch name does not fit with the E3SM naming convention. It probably should be mark-paterson/ocean/mpas_rm_compass. I don't know that it matters this time, but for future reference we should follow that

**Review by jonbob — APPROVED** [review]
Approve based on visual inspection and sanity testing of a test merge

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
