### PR TITLE
fixed a memory caused crash for test SMS_D.f19_g16.I1850ELM.pm-cpu_gnu

### PR DESCRIPTION
**Pull request by jinyuntang**
In the old code of sbetr, the dimension of the array crop is not consistent with that in elm, which caused a memory associated crash, when betr is on. Now the issue is resolved by ensuring the dimensions in elm and sbetr are consistent. 

No answer change is expected.

No answer change is expected.

### CODE REVIEW

**Comment by rljacob** [comment]
@bishtgautam please review.

**Comment by rljacob** [comment]
@bishtgautam any progress on this?

**Comment by bishtgautam** [comment]
@jinyuntang The SBeTR submodule in E3SM master has the following commit graph:
```
* 1fd5a14f (HEAD, origin/bishtgautam/elm-time-manager, bishtgautam/elm-time-manager) Switches to elm_time_manager
*   25c892a5 Merge pull request #60 from BeTR-biogeochemistry-modeling/jinyun/SMS_D.fix
|\
| * 26e0b3bb (origin/jinyun/SMS_D.fix) remove redundant comment
| * 633af5cc bug fix for failed memory access
* | a37d7b09 (master) some small bug fix
|/
*   13fff920 Merge pull request #59 from amametjanov/sbetr/ibm-bld-err-fixes
|\
| * 7a139e80 Add IBM compiler build fixes for OLCF Summit and Ascent
|/
* bab467dd typo fix for variable name
* d5447cce rename for elm-betr coupling
*   f3258d32 Merge pull request #57 from amametjanov/azamat/sbetr-fujitsu-mods
```

Your new updated SBeTR submodule has the following commit graph:
```
* 96e3d318 (HEAD, origin/jytang/cropfix) bug fix for crop array size
*   25c892a5 Merge pull request #60 from BeTR-biogeochemistry-modeling/jinyun/SMS_D.fix
|\
| * 26e0b3bb (origin/jinyun/SMS_D.fix) remove redundant comment
| * 633af5cc bug fix for failed memory access
* | a37d7b09 (master) some small bug fix
```

Your updated submodule is missing `1fd5a14f`. Can you rebase your SBeTR branch `jytang/cropfix` off `bishtgautam/elm-time-manager` branch and then update the SBeTR submodule?  Let me know if you need help.

**Review by bishtgautam — CHANGES_REQUESTED** [review]
See my comment [above](https://github.com/E3SM-Project/E3SM/pull/5893#issuecomment-1791082274)

**Comment by rljacob** [comment]
@jinyuntang please take care of above so this can be merged.

**Comment by rljacob** [comment]
@jinyuntang your attention is needed here.

**Comment by jinyun1tang** [comment]
@rljacob @bishtgautam , will do that late today.

**Comment by jinyun1tang** [comment]
@bishtgautam, I now rebased jytang/cropfix off bishtgautam/elm-time-manager, however, the code failed to build with branch jinyuntang/fix5832, as it still uses clm_time_manager.F90. What should I do in this case? Also, I merged jytang/cropfix into sbetr master, it passed all standalone betr tests.

**Comment by rljacob** [comment]
@jinyun1tang push the rebased branch to this repo please.

**Comment by rljacob** [comment]
@jinyun1tang since this branch is now very old, I'd like you to start over.  Also open an issue with a description of the problem.

**Comment by rljacob** [comment]
Issue is #5832

**Pull request closed without merging**
