### PR TITLE
update cube_to_target

### PR DESCRIPTION
**Pull request by whannah1**
Clean up and simplify the Makefile for the cube_to_target topography generation tool. 

[BFB]

### CODE REVIEW

**Comment by oksanaguba** [comment]
On which machines that we support is it supposed to run, if any?

**Comment by whannah1** [comment]
@oksanaguba I don't know of any requirement to have this running on a supported machine. Someone created a script to allow regular testing, but I don't think we actually run tests. The idea here was to clean it up and make sure it works on Perlmutter and Chrysalis, which seem to be the machines that most  people use most of the time. We can modify this to support other machines as the use cases arise.

**Comment by oksanaguba** [comment]
@whannah1 thanks. so this needs to be tested on PM and chrysalis. did you test on either or should i?

**Comment by whannah1** [comment]
I verified that it builds on both Perlmutter and Chrysalis.

**Review by oksanaguba — APPROVED** [review]

**Pull request merged**
