### PR TITLE
Add F1850SC5 and A_WCYCLSSP585 CIMP6 compsets

### PR DESCRIPTION
**Pull request by rljacob**
Bring in some compsets from maint-1.0

Compset for SSP5_8.5 future scenario for CMIP6 watercycle
simulation. The input files follow the input4MIPS data as closely as
possible.

Adds F1850SC5-CMIP6 compset (letter "S" in the name stands for special), since the following settings will be different from the F1850C5-CMIP6 compset used by the companion coupled compset (piControl, A_WCYCL1850S_CMIP6)

Atmosphere and land initial condition data use results at the end (0501-01-01) of the DECK piControl simulation. This is particularly useful to have a better spun-up land state.
SST and sea ice data use the CMIP6 climatology calculated from 1870-1879.

Created by cherry-picking from maint-1.0.

[BFB] except for the new compsets.

### CODE REVIEW

**Comment by cameronsmith1** [comment]
Hi @rljacob.  I separately implemented the SSP585 compset in maint-1.1 (https://github.com/E3SM-Project/E3SM/pull/2986).  That required a couple of additional changes (because the base code for maint-1.1 was more modern).   Those changes were also a little cleaner because they were in a single commit (rather than the two for main-1.0).  Would it make more sense to cherry-pick from https://github.com/E3SM-Project/E3SM/pull/2986 instead?

**Comment by rljacob** [comment]
If its just one-less commit, not really worth redoing the branch.

Can you put the input data on the server in cam/chem/trop_mozart_aero/emis/CMIP6_SSP585_ne30 ?  It seems to be missing.

**Comment by cameronsmith1** [comment]
> 
> 
> If its just one-less commit, not really worth redoing the branch.

There are also a couple of extra changes related to CLM.   But I am not sure whether the changes that made them necessary on the maint-1.1 branch are also on master.

> Can you put the input data on the server in cam/chem/trop_mozart_aero/emis/CMIP6_SSP585_ne30 ? It seems to be missing.

The data should all be on Blues, but I will check.

**Comment by cameronsmith1** [comment]
UPDATE: those emission files were provided by @hwangacme.   However, it seems they are in the NERSC data location, but not on Blues.   I will contact Hailong.

**Comment by cameronsmith1** [comment]
> UPDATE: those emission files were provided by @hwangacme. However, it seems they are in the NERSC data location, but not on Blues. I will contact Hailong.

Hailong is on vacation, so I will copy them over to Blues.

**Comment by cameronsmith1** [comment]
The emission files should now be correctly on Blues.  However, I don't have a good way to test them.  @rljacob, do you have a machine where you can test them?

**Comment by tangq** [comment]
@rljacob , have you tested these compsets with master? I am not sure the maint-1.0 land input files are compatible with current master.

**Comment by rljacob** [comment]
I'm trying to test it now.  I built a case on compy.
The emission files downloaded fine.
Now the only file missing from blues is clm2/initdata_map/20180215.DECKv1b_H1.ne30_oEC.edison.clm2.r.2015-01-01-00000.nc

**Comment by rljacob** [comment]
Ok the F case did indeed complain about a land file:
```
 /compyfs/inputdata/lnd/clm2/initdata_map/I1850CLM45.ne30_oECv3.edison.intel.36b
 43c9.clm2.r.0001-01-06-00000_c20171023.nc     2097152
 check_dim ERROR: mismatch of input dimension        16368  with expected value
       15865  for variable gridcell
```

**Comment by cameronsmith1** [comment]
This may have been one of the problems I solved in my maint-1.1 PR https://github.com/E3SM-Project/E3SM/pull/2986.

**Comment by rljacob** [comment]
@cameronsmith1 I can't find this file that is needed for the SSP585 case:
clm2/initdata_map/20180215.DECKv1b_H1.ne30_oEC.edison.clm2.r.2015-01-01-00000.nc

**Comment by cameronsmith1** [comment]
That is a restart file, so it isn't really part of the compset. It is from the end of the DECK H1 simulation.  However, for user convenience I archived it (along with all of the other restart files I used to develop and test the SSP585 compset) in the Blues data archive in e3sm_init/SSP585.DECKv1b_H1.ne30_oEC

**Comment by rljacob** [comment]
It *is* part of the compset.  Its what you get for "finidat" when you build A_WCYCLSSP585_CMIP6 in maint-1.0.   For that reason alone, that file needs to be on the input data server.

**Comment by rljacob** [comment]
@bishtgautam the error mentioned in https://github.com/E3SM-Project/E3SM/pull/3118#issuecomment-520098382 is similar to https://github.com/E3SM-Project/E3SM/issues/507 which you said is from the restart file not matching the domain file.  But we haven't changed the domain file in a long time.  So why am I getting that error when using a 1.0 restart as finidat on latest master?

**Comment by cameronsmith1** [comment]
> 
> 
> It _is_ part of the compset. Its what you get for "finidat" when you build A_WCYCLSSP585_CMIP6 in maint-1.0. For that reason alone, that file needs to be on the input data server.

Yes, I did make it the default in the compset.  It is arguable whether it is part of the compset, but I copied it into the place in the data archive on blues where it is expected by default.

Are there any other defaults that are similarly 'missing'?

**Comment by rljacob** [comment]
Thanks.  The file downloaded fine.  But there was a runtime error in pio reading the file with no helpful error from elm.
```
   0:  NetCDF: Variable not found
   0:  NetCDF: Invalid dimension ID or name
   0:  pio_support::pio_die:: myrank=          -1 : ERROR: nf_mod.F90:        1288 :
   0:  NetCDF: Invalid dimension ID or name
   0: Image              PC                Routine            Line        Source
   0: e3sm.exe           00000000032C99BA  Unknown               Unknown  Unknown
   0: e3sm.exe           00000000030A8731  pio_support_mp_pi         118  pio_support.F90
   0: e3sm.exe           00000000030A6752  pio_utils_mp_chec          74  pio_utils.F90
   0: e3sm.exe           000000000308DF62  nf_mod_mp_pio_inq        1288  nf_mod.F90
   0: e3sm.exe           0000000002683204  ncdio_pio_mp_chec         354  ncdio_pio.F90.in
   0: e3sm.exe           0000000001E87211  restfilemod_mp_re        1221  restFileMod.F90
```
So I'm just going to set finidat to empty in both these cases.

**Comment by cameronsmith1** [comment]
> So I'm just going to set finidat to empty in both these cases.

This makes me nervous, because many users won't know that they need to change the default to get a meaningful simulation.

**Comment by rljacob** [comment]
Its either that or someone has to come up with a new init file before this PR can be merged.

**Comment by cameronsmith1** [comment]
Using an empty finidat would let this get pushed to master.  However, the compset won't be useful until someone creates a viable initial condition.

**Comment by rljacob** [comment]
This also needs an update to read netcdf3 input files.

**Comment by bishtgautam** [comment]
@cameronsmith1, @rljacob, Could either one of you tell me the full `./create_newcase` command that is works with `maint-1.0` but fails with `rljacob/compset/addcmip6` branch?

**Comment by cameronsmith1** [comment]
> @cameronsmith1, @rljacob, Could either one of you tell me the full `./create_newcase` command that is works with `maint-1.0` but fails with `rljacob/compset/addcmip6` branch?

I have not yet tried using the rljacob/compset/addcmip6 branch, and I only use run_e3sm scripts.

**Comment by bishtgautam** [comment]
>I have not yet tried using the rljacob/compset/addcmip6 branch, and I only use run_e3sm scripts.

Ok, which run_e3sm script?

**Comment by cameronsmith1** [comment]
The run_script I used for the SSP585 future compset on maint-1.0, and all of the necessary restart files, are on Cori in ```/global/cscratch1/sd/pjc/SSP585_initial_condition```.  The only change that should be needed to the run_script is to change ```acme_tag``` from the branch I was using to ```maint-1.0```.

**Comment by rljacob** [comment]
./create_newcase  --compset A_WCYCLSSP585_CMIP6 --res ne30_oECv3_ICG
and
./create_newcase --compset F1850SC5-CMIP6 --res ne30_ne30

**Comment by bishtgautam** [comment]
@rljacob, I have generated the new initial condition files. Currently, the new files are available on NERSC at:

```
$DIN_LOC_ROOT/lnd/clm2/initdata_map/20180215.DECKv1b_H1.ne30_oEC.edison.clm2.r.2015-01-01-00000.27d91fb47_c20190824.nc
$DIN_LOC_ROOT/lnd/clm2/initdata_map/ne30_ne30.F1850SC5-CMIP6.27d91fb47.clm2.r.0001-01-02-00000_c20190824.nc
```
I have requested ANL to update my ssh public key so I can upload the new input data on E3SM inputdata public server. Should I make a commit in your branch or do you want to make the changes?

**Comment by rljacob** [comment]
@bishtgautam I finally tested this on compy and it didn't work.  Now the error is:
```
 ERROR: Initial conditions file (finidat) was generated from a different surface
  dataset
 than the one being used for the current simulation (fsurdat).
 Current fsurdat: surfdata_ne30np4_simyr1850_2015_c171018.nc
 Surface dataset used to generate initial conditions file:
 surfdata_ne30np4_simyr1850_c180306.nc
```

Also for  F1850SC5-CMIP6 compset, you need to modify use_cases/1850_SCMIP6_control.xml  I don't think the namelist_files/namelist_defaults_clm4_5.xml is necessary.

**Comment by rljacob** [comment]
@bishtgautam I'm turning this over to you to finish and integrate.  The goal is to get the compsets mentioned in https://github.com/E3SM-Project/E3SM/pull/3118#issuecomment-524499016 to build and run on master on all supported platforms.  Note that you will need to set PIO_TYPENAME to netcdf on compy for these.

**Comment by bishtgautam** [comment]
@rljacob In 4294a10, I mistakenly added incorrect initial conditions. I would like to amend that commit and force push. Is that okay?

**Comment by rljacob** [comment]
@bishtgautam yes that's ok.

**Comment by bishtgautam** [comment]
@rljacob, I have successfully run the two compsets on Cori and Compy
@cameronsmith1, This PR is ready for your review

**Comment by rljacob** [comment]
@tangq  please approve or make more review comments.

**Comment by rljacob** [comment]
Works for me too.  Merged to next.

@bishtgautam  can you check the description at the top and change it if its not correct.

**Comment by cameronsmith1** [comment]
This PR is still referring to the Netcdf4 version of the SSP585 emissions.  Hence, I am surprised it ran.  Do we need to wait for PR https://github.com/E3SM-Project/E3SM/pull/3148 ?

The description at the top refers to ```l_ieflx_fix flag```.  I thought this was an obsolete flag, replaced by ```ieflx_opt```.  However, this PR doesn't seem to be changing  ```l_ieflx_fix flag```, so is there a code change missing?  Or does the description just need to be changed?

**Comment by rljacob** [comment]
Probably the description needs an update.

I'm changing to "netcdf" PIO type to run these.  @golaz wanted these so I'm not waiting for the netcdf3 update.

**Comment by bishtgautam** [comment]
The description for land looks good to me.

**Pull request merged**
