### PR TITLE
[WIP] HOMME: added possibility of building libraries instead of execs

### PR DESCRIPTION
**Pull request by bartgol**
This PR allows one to configure Homme via cmake, without building executables, and building 'libraries' instead.

This can be handy if Homme is built as part of a larger cmake project (namely, E3SM, or SCREAM), so that we can simply link against homme's pre-built library, without injecting much of its targets setting into the host project (i.e., simply doing `target_link_library(my_tgt $my_homme_lib)` should be all you need).

### CODE REVIEW

**Comment by rljacob** [comment]
What is the status of this PR?

**Comment by bartgol** [comment]
I paused after some discussion on the hommexx slack channel. There is some disagreement regarding how to treat non-standalone vs standalone build. My goal was to discuss it at the next dycore meeting, but we haven't had one in a while.

I am planning on resuming work on this soon, though. I do think we need this PR (possibly amended, in some form), to go in, in order for SCREAM to properly work.

**Comment by rljacob** [comment]
What is the update on this PR?

**Comment by bartgol** [comment]
@rljacob I'm waiting to finish the PR that brings in homme-nh-xx first (coming today or tomorrow), so that I do cmake changes just once.

**Comment by bartgol** [comment]
I'm closing this PR, since I need to fully test the capability in the SCREAM repo before I can claim the mods are working. When I'm confident the upgrades are completed, I will issue a new PR.

**Pull request closed without merging**
