### PR TITLE
Fix restart error on maint-2.0 

### LINKED ISSUE #6195: maint-2.0 branch appears broken on Perlmutter
The maint-2.0 branch (b583f7d) is having problems on Perlmutter (CPU nodes).  Any run that restarts will fail with the following PIO error in the e3sm.log file.
`
PIO: FATAL ERROR: Aborting... An error occured, Writing variables (number of variables = 180) to file (./20240129.restart_test2.maint_20.elm.h0.0001-02.nc, ncid=143) using PIO_IOTYPE_PNETCDF iotype failed. Non blocking write for variable (TWS_MONTH_BEGIN, varid=205) failed (Number of subarray requests/regions=1, Size of data local to this process = 433). NetCDF: Numeric conversion not representable (err=-60). Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/pscratch/sd/b/beharrop/temp/e3sm_code/20240129/E3SM/externals/scorpio/src/clib/pio_darray_int.c: 395)
`

I tried to reproduce this with a shorter test using `./create_test ERS.ne4_oQU240.F2010`, but that did not reproduce the error. `ERS.ne4_oQU240.F2010.pm-cpu_intel (Overall: PASS)`.  I have also been unable to reproduce this error on either Chrysalis or Compy.  The smallest reproducible setup I've been able to come to that has this error is the following.

```
./create_newcase --case ${casename}  --compset F2010 --res ne4_oQU240 --walltime 00:08:00 --script-root ${casedir} --output-root ${outputdir} -mach pm-cpu

cd ${casedir}

./xmlchange STOP_N=1
./xmlchange STOP_OPTION=nmonths
./xmlchange RESUBMIT=1

./case.setup
./case.build
./case.submit
```

I have been using the intel compiler, and haven't tested any of the others yet.  Has anyone else encountered anything like this?

### PR DESCRIPTION
**Pull request by peterdschwartz**
Add endwb to ELM restart file in maint-2.0. 

[BFB]
Fixes #6195

### CODE REVIEW

**Comment by peterdschwartz** [comment]
Need to check if maint-2.0 will also need PR #5811

**Comment by peterdschwartz** [comment]
I ran ` SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCLSSP370.pm-cpu_intel.allactive-wcprodssp` with no issue, so leaving this as is.

**Comment by ndkeen** [comment]
I might suggest adding in the fix in 5811.  I think I needed that for the tests in maint-2.1 to pass. I had meant to add it here as well anyway, but the e3sm_production tests did pass.

**Comment by peterdschwartz** [comment]
Went ahead and made that change as well.

**Comment by ndkeen** [comment]
OK, you likely know more about why this is or is not a good idea.

I did try `SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCLSSP585.pm-cpu_intel.allactive-wcprodssp`
with and without that finidat and it seemed ok?

**Review by ndkeen — APPROVED** [review]

**Comment by rljacob** [comment]
@ndkeen can an ERS test pass on maint-2.0 without these fixes?

**Comment by ndkeen** [comment]
No, before these changes `ERS_Lm3.ne4_oQU240.F2010` would fail.  But it also fails with even old maint-2.0 checkouts -- ie I think the test would have always failed.

**Comment by rljacob** [comment]
Oh that's right,  you have to run it for a long time.  A standard-length ERS passes.  How long does Lm3 take?  We should add an ERS test to the prod suite for maint-2.0 to catch this.

**Comment by ndkeen** [comment]
My test that passes after this fix used a job that ran for a total of 8:45 on 1 node of pm-cpu.

**Comment by mingxuanwupnnl** [comment]
@peterdschwartz I met the same issue while I was doing production runs. I wonder if this bug fix PR is BFB? Thank you.

**Comment by peterdschwartz** [comment]
> @peterdschwartz I met the same issue while I was doing production runs. I wonder if this bug fix PR is BFB? Thank you.

It's BFB

**Comment by rljacob** [comment]
@rebassoo merged.

**Comment by rebassoo** [comment]
Great, thanks @rljacob!

**Pull request merged**
