### PR TITLE
Update baroclinic parts in SI code

### PR DESCRIPTION
**Pull request by hyungyukang**
- Matching baroclinic parts of SI code with those of the explicit code

So far, the branch passed `PEM_Ln9_D.T62_oQU240.GMPAS-IAF.cori-knl_gnu` and `SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu` using configurations `config_time_integrator = 'split_implicit'` and `config_btr_si_partition_match_mode = .true.`

[BFB] - stealth feature

### CODE REVIEW

**Comment by jonbob** [comment]
@hyungyukang -- is this expected to be BFB?

**Comment by mark-petersen** [comment]
I tested using gnu on chrysalis, both debug and optimized, and commit b35c75423f2873c8b984a0be8407b7f3b82193ae passes bfb against master for both, using the compass nightly suite for MPAS-O stand-alone. @hyungyukang communicated with me that he will rebase the code to the head of master, then I will test again.

**Comment by mark-petersen** [comment]
@jonbob, these changes are only in the semi-implicit time stepping, which is not used in the E3SM tests, so this can be classified as BFB for E3SM testing. All changes are isolated to the semi-implicit module.

**Comment by jonbob** [comment]
Thanks @mark-petersen -- I gave it the stealth label then

**Review by mark-petersen — APPROVED** [review]
Approve by visual inspection, testing with default flags, and Hyun's testing above.

Compiled current head with intel debug and optimized on chrysalis (with openmpi). Both pass bfb against master for nightly suite for MPAS-O standalone compass.

**Comment by hyungyukang** [comment]
> Approve by visual inspection, testing with default flags, and Hyun's testing above.
> 
> Compiled current head with intel debug and optimized on chrysalis (with openmpi). Both pass bfb against master for nightly suite for MPAS-O standalone compass.

@mark-petersen , Thanks a lot for testing the code!

**Review by jonbob — APPROVED** [review]
Approved based on visual inspection and testing

**Comment by jonbob** [comment]
passes:
* SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCLSSP370.chrysalis_intel.allactive-wcprodssp
* SMS_D_Ld3.T62_oQU120.CMPASO-IAF.chrysalis_intel
* ERS.T62_oQU120.CMPASO-IAF.chrysalis_intel

merged to next

**Comment by hyungyukang** [comment]
> passes:
> 
> * SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCLSSP370.chrysalis_intel.allactive-wcprodssp
> * SMS_D_Ld3.T62_oQU120.CMPASO-IAF.chrysalis_intel
> * ERS.T62_oQU120.CMPASO-IAF.chrysalis_intel
> 
> merged to next

@jonbob , Thank you for tests and your approval!

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
