### PR TITLE
Add tests for some grid-IC tools

### PR DESCRIPTION
**Pull request by sarich**
New scripts to test grid utilities. These tests are running nightly on https://jenkins-gce.cels.anl.gov/job/E3SM_grid_tests
This includes test for:
cime/tools/mapping/gen_domain_files (already in cime)
components/eam/tools/topo_tool/cube_to_target
components/eam/tools/mkatmsrffile
components/elm/tools/mksurfdata_map

[BFB]

### CODE REVIEW

**Review by bishtgautam — COMMENTED** [review]
How about adding a help option (`-h` or `--help`) to all shell scripts?
e.g. 
- https://github.com/E3SM-Project/LandParameters/blob/master/create_clm_parameter_netcdf.sh#L18
- https://github.com/E3SM-Project/LandParameters/blob/master/create_clm_parameter_netcdf.sh#L43

**Comment by sarich** [comment]
Adding a help option would definitely improve the scripts, I'll put them in.

**Comment by rljacob** [comment]
merged to next.

**Comment by rljacob** [comment]
@sarich I realized I merged this before you put in the help options.  Can you take care of that?  I'll leave it on next.

**Pull request merged**
