### PR TITLE
Update mpas-source: init mode case

### PR DESCRIPTION
**Pull request by mark-petersen**
See https://github.com/MPAS-Dev/MPAS-Model/pull/724. Only changes MPAS-Ocean init mode. This is not compiled in E3SM.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
Passes sanity tests
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
```

**Review by jonbob — APPROVED** [review]
Based on visual inspection, the changes are limited to init code that E3SM does not use

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
