### PR TITLE
Add initial superBFB tests for OCN

### PR DESCRIPTION
**Pull request by amametjanov**
Add initial superBFB tests for OCN

[BFB]

### CODE REVIEW

**Comment by amametjanov** [comment]
I've checked on Chrysalis, but this should work on any machine with
```
./cime/scripts/create_test e3sm_superbfb_ocn
```

**Comment by jonbob** [comment]
@amametjanov - what does superBFB mean?

**Comment by rljacob** [comment]
https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/3438608385/E3SM+Code+Review+and+New+Feature+Process#Super-BFB-suite

**Review by jonbob — APPROVED** [review]
Approved based on visual inspection and use of current meshes for testing

**Comment by jonbob** [comment]
@amametjanov - the only issue you may run into is that CIME doesn't download files for case2 runs of these ERS and PEM tests. So you may see unexpected failures due to missing graph files and have to stage some by hand

**Pull request merged**
