### PR TITLE
Update run-script example for v3

### PR DESCRIPTION
**Pull request by rljacob**
Update run-script example for v3 and pm-cpu
change user_nl settings to match v3 production config.

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
@wlin7 or @forsyth2 can one of you approve this?

**Comment by forsyth2** [comment]
@rljacob It's been a while since I've done any work on this. I haven't run any v3 simulations to know if these updates are the proper ones. Is there testing I need to do?

**Comment by rljacob** [comment]
I've tested it on pm-cpu.  I just need a review to use the green merge button.

**Review by forsyth2 — COMMENTED** [review]
Ok. Again, I can't say if all these changes are "correct", but since you've tested successfully on Perlmutter, I'll go ahead and approve. Thanks.

**Review by forsyth2 — APPROVED** [review]
Ok. Again, I can't say if all these changes are "correct", but since you've tested successfully on Perlmutter, I'll go ahead and approve. Thanks.

**Pull request merged**
