### PR TITLE
Fix issues with adding atm fields to rof coupling

### LINKED ISSUE #3340: case ne30_oECv3_ICG.A_WCYCL1850S_CMIP6 with allactive-v1cmip6 mods failing
The main v1 fully coupled case (part of e3sm-integration) has been failing since the PR #3133 merged on Nov 27 on some macines.
 integration test:   SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.mach_compiler.allactive-v1cmip6

sandiatoss3-master-int:  fail since Nov28
sandiatoss3-next-int: fail since Nov 27
anvil-next-int:  fail since Nov 27  9b631d03

Runs fine:
theta-next-int:  dc19b1606 passing
bebop-next-int:   dc19b160 passed on Dec 13 (PEND since).

Notably, the production test with the same compset but without debugging has not failed on anvil.
SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.anvil_intel.allactive-v1cmip6

https://my.cdash.org/testDetails.php?test=52192958&build=1739857

### LINKED ISSUE #3467: SMS_D_Ld1.ne30_r05_oECv3.A_WCYCL1850.anvil_intel fails randomly with floating invalid
This issue can be reproduced with latest E3SM master branch on anvil, using default scorpio classic.
`./create_test SMS_D_Ld1.ne30_r05_oECv3.A_WCYCL1850.anvil_intel`

Run command is:
`srun  -l -n 1584 -N 44 --kill-on-bad-exit  --cpu_bind=cores -c 1 -m plane=36 bld/e3sm.exe   >> e3sm.log.$LID 2>&1`

Sometimes, this debug mode test can pass, run time is about 12 mins.

Sometimes, it fails after about 7 mins with stack trace like below:
```
 806: forrtl: error (65): floating invalid
 806: Image              PC                Routine            Line        Source
 806: e3sm.exe           000000000F4E5A61  Unknown               Unknown  Unknown
 806: e3sm.exe           000000000F4E3B9B  Unknown               Unknown  Unknown
 806: e3sm.exe           000000000F48F8E4  Unknown               Unknown  Unknown
 806: e3sm.exe           000000000F48F6F6  Unknown               Unknown  Unknown
 806: e3sm.exe           000000000F40B607  Unknown               Unknown  Unknown
 806: e3sm.exe           000000000F41769D  Unknown               Unknown  Unknown
 806: libpthread-2.17.s  00002AB9B38BE5D0  Unknown               Unknown  Unknown
 806: e3sm.exe           000000000D3A8B07  m_matattrvectmul_         267  m_MatAttrVectMul.F90
 806: e3sm.exe           000000000D3B02E6  m_matattrvectmul_         608  m_MatAttrVectMul.F90
 806: e3sm.exe           000000000080D3F4  seq_map_mod_mp_se         880  seq_map_mod.F90
 806: e3sm.exe           00000000007F8B4C  seq_map_mod_mp_se         319  seq_map_mod.F90
 806: e3sm.exe           00000000005BD254  prep_rof_mod_mp_p         697  prep_rof_mod.F90
 806: e3sm.exe           0000000000454531  cime_comp_mod_mp_        4166  cime_comp_mod.F90
 806: e3sm.exe           000000000043ACD6  cime_comp_mod_mp_        2580  cime_comp_mod.F90
 806: e3sm.exe           0000000000459688  MAIN__                    133  cime_driver.F90
 806: e3sm.exe           0000000000415A2E  Unknown               Unknown  Unknown
 806: libc-2.17.so       00002AB9B600A3D5  __libc_start_main     Unknown  Unknown
 806: e3sm.exe           0000000000415929  Unknown               Unknown  Unknown
```
SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.anvil_intel.allactive-v1cmip6 has the similar issue.

### PR DESCRIPTION
**Pull request by rljacob**
The driver was assuming that all fluxes to the river model were from the land which is not true when temperature of river water is prognostic (rof_heat = .true.).   A mis-sized Attribute Vector from this assumption led to occasional fails for fully coupled cases and consistent fails for one debugging test.  Add additional seq_flds strings to separate fields going  to the river from land and ocean and use them correctly in prep_rof_mod.   Also output content of these and other special seq_flds strings.

Fixes #3340
Fixes #3467 

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
Rebased to head of master.

**Comment by rljacob** [comment]
@jayeshkrishna @dqwu I merged this PR to next over the weekend and testing from Saturday night revealed a bunch of odd errors:
` PIO: FATAL ERROR: Aborting... FATAL ERROR: NetCDF: String match to name in use (/ascldap/users/jenkins/slave/workspace/ACME_Melvin_    next/ACME/externals/scorpio/src/clib/pio_nc.c: 2509)`

These changes should have nothing to do with I/O.   I reverted it off of next.   The results should be here:
https://my.cdash.org/index.php?project=E3SM&date=2020-04-26
This error happened on melvin, sandiatoss3, anvil and probably compy.

**Comment by jayeshkrishna** [comment]
The error message is thrown while a variable is defined. Could be that the application is defining the same variable twice ?

**Comment by rljacob** [comment]
This turned out to be a merge error (there were conflicts with the merge to next) that did result in a variable being added twice to the r2x attribute list.  Later when the coupler history is written, this results in an error (should probably be an error before that).

**Pull request merged**
