### PR TITLE
Fixes a clubb-only test added for running convergence tests

### LINKED ISSUE #2420: SMS_Ld1.ne4_ne4.FC5AV1C-L-AQUAP.cam-clubb_only failing on sandiatoss3
SMS_Ld1.ne4_ne4.FC5AV1C-L-AQUAP.sandiatoss3_intel.cam-clubb_only is failing on both skybridge and chama (same architecture:  sandiatoss3).

### PR DESCRIPTION
**Pull request by singhbalwinder**
Allocation for ptend%s is tested before fetching its value. This ensures
 that the code works even in cases where deep_scheme is set to OFF,
CLUBB_SGS or UNICON

[BFB] - Bit-For-Bit

Fixes #2420

### CODE REVIEW

**Comment by zhangshixuan1987** [comment]
I think the changes are correct and good to merge

**Comment by wlin7** [comment]
@zhangshixuan1987 , can you please approve this PR to complete the procedure. (You can click "Files changed" then "Review Changes" to approve).
It is an interesting fix. We struggled with the CLUBB-SILHS simulations, which set to have deep_scheme off. (Attn: @kaizhangpnl ). Wonder if this could partly be responsible.

**Comment by wlin7** [comment]
Merged to next.

**Comment by kaizhangpnl** [comment]
Thanks for the information, @wlin7 
The bug seems not a problem for SILHS. use_gw_convect is set to False when SILHS is on, so ttend_dp_idx = 0 and the code inside the if-then block is not executed.

**Comment by wlin7** [comment]
Nice to know that, @kaizhangpnl . Thanks.

**Comment by singhbalwinder** [comment]
@wlin7 : @huiwanpnnl took another look at the code and thinks that we should initialize ttend_dp to zeros if ptend%s is not allocated. I will make this change in this branch which would require a re-merge to next.

**Comment by singhbalwinder** [comment]
@wlin7 : I have added a new commit for the change mentioned above.

**Comment by wlin7** [comment]
Merged the updated PR to next.

**Comment by rljacob** [comment]
I made the ticket to bless this test: https://acme-climate.atlassian.net/servicedesk/customer/portal/2/SES-533

**Pull request merged**
