### PR TITLE
Fix no_batch determination in case_submit

### LINKED ISSUE #3166: case.submit error on anlworkstation
This issue seems to be caused by PR #3155.
Not sure if other machines with a non-batch system are also affected.

It can be reproduced by running a simple F case (--compset FC5AV1C-H01B --res ne4_ne4)
on anlworkstation.

Before that PR is merged, the output information is:
```
...
mach anlworkstation 
resubmit_num 0
2019-08-29 11:28:43 CASE.RUN HAS FINISHED
Submitted job case.run with id None
```
After that PR is merged, the output information is:
```
...
mach anlworkstation 
resubmit_num 0
2019-08-29 11:38:43 CASE.RUN HAS FINISHED
ERROR: No result from jobs [('case.run', None)]
```
CaseStatus file also shows:
```
...
2019-08-29 11:38:43: case.run success 
 ---------------------------------------------------
2019-08-29 11:38:43: case.submit error 
ERROR: No result from jobs [('case.run', None)]
```

### PR DESCRIPTION
**Pull request by jgfouca**
Fixes #3166 

[BFB]

### CODE REVIEW

**Comment by jgfouca** [comment]
@jedwards4b , will you take a quick look at this? This bug was introduced into E3SM in a recent CIME update. My hunch is that no_batch should always be true if env_batch.get_batch_system_type() == "none".

**Comment by jedwards4b** [comment]
There is also a bug a couple of lines down:
replace
```
if batch_system != "none" and env_batch_has_changed or external_workflow:
```
with
```
if batch_system != "none" and (env_batch_has_changed or external_workflow):
```

**Comment by jgfouca** [comment]
@jedwards4b , I think you are talking about this line:

```
if batch_system != "none" and env_batch_has_changed and not external_workflow:
```

I believe this line is correct.

**Comment by jedwards4b** [comment]
hmm - you have an and where I have an or - is that logically the same as adding ()?  I'll need to think about it.

**Comment by jgfouca** [comment]
@jedwards4b , we can resolve in the next split.

**Pull request merged**
