### PR TITLE
Implement info_taskmap_comp support in component models

### PR DESCRIPTION
**Pull request by worleyph**
A recent commit added the env_run.xml parameter INFO_TASKMAP_COMP
and the associated cime_pes namelist parameter info_taskmap_comp
to enable (> 0) or disable (<= 0) the output of the
task-to-node mapping for the component models. If enabled,
it further specifies whether to use a compact (== 1) or
a more verbose (> 1) output format. Here the necessary control
logic is added to CAM, CLM, Mosart, mpas-albany-landice,
mpas-ocean, and mpas-seaice.

At the moment, the default for INFO_TASKMAP_COMP is 0, so this removes all component-specific task-to-node mapping information from the log files but allows us to experiment
with this and supports writing out all task-to-node mapping information in the new more compact representation simply by changing the default for INFO_TASKMAP_COMP to 1 (or 2).

BFB

### CODE REVIEW

**Comment by worleyph** [comment]
I have tested this using 

     -compset A_WCYCL1950S_CMIP6_LR -res ne30_oECv3_ICG

on Cori-KNL using the default (realistic) PE layout on 60 nodes, varying INFO_TASKMAP_COMP between 0, 1, and 2 . Results are as expected.

@rljacob , I assigned this to you because you integrated the predecessor PR. Please reassign as appropriate. Thanks.

**Comment by worleyph** [comment]
@rljacob and @mt5555, could you please take a look at this? Thanks.

**Comment by worleyph** [comment]
@rljacob , should I reassign integration for this PR? If so, do you have a suggestion?

**Comment by rljacob** [comment]
Merged to next.

**Pull request merged**
