### PR TITLE
Update top-level docs for v2.1

### PR DESCRIPTION
**Pull request by rljacob**
Update README, LICENSE and codemeta.json for 2.1.  Also add a CITATION.cff file which github and zenodo support.

### CODE REVIEW

**Comment by rljacob** [comment]
Info on CITATION.cff is here:  https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Review by sarats — APPROVED** [review]
Looks good.

**Comment by sarats** [comment]
Perhaps I missed it. Did you find where Github automatically adds "Cite this repository" from the included CITATION file?

**Comment by sarats** [comment]
Never mind. I thought we previously had CITATION file (mixed up with codemeta.json) for the old versions. Apparently not.

Perhaps we ought to update the codemeta file too since we have it.
https://codemeta.github.io/

**Comment by rljacob** [comment]
sure.  I think the citation will show up on the main E3SM github page after its merged.

**Pull request merged**
