### PR TITLE
Backport homme changes from scream fork

### PR DESCRIPTION
**Pull request by bartgol**
This PR contains a few changes in Homme (mostly in the cxx code), that were needed in the scream fork. We issue a PR with the same commits (plus a couple of bug fixes) here, to avoid hard to solve conflicts when we next merge e3sm into scream.

EDIT: this PR should now be completely BFB. There was one non-BFB commit, but it has been reverted.

### CODE REVIEW

**Review by ambrad — APPROVED** [review]

**Comment by ambrad** [comment]
I agree with the init change. I added "[non-BFB] for Hommexx standalone tests only" to your description. Is that qualification of non-BFBness correct?

**Comment by bartgol** [comment]
\

> I agree with the init change. I added "[non-BFB] for Hommexx standalone tests only" to your description. Is that qualification of non-BFBness correct?

I think so, since the non bfb-ness is guarded by the ifdef HOMMEXX_BFB_TESTING, which is only active in standalone builds.

**Comment by bartgol** [comment]
@ambrad On mappy, the homme standalone tests pass against master. I am currently testing on weaver, but I hit some of the internal errors requiring ConstExceptGnu. I will have to add the mod in both branch and master (temporarily) to keep checking.

I'm assuming that e3sm has no nightlies on GPU (at least, none that tests homme), otherwise this error would have been caught? It's probably something that creeped in when the kokkos submodule was upgraded and started requiring c++14, which forced an update in the compilers.

**Comment by bartgol** [comment]
Ok, the unit+dev test label runs fine on both mappy and weaver, when comparing against master baselines (with the aforementioned tweak on master on weaver).

**Review by ambrad — APPROVED** [review]

**Comment by ambrad** [comment]
> @ambrad On mappy, the homme standalone tests pass against master. I am currently testing on weaver, but I hit some of the internal errors requiring ConstExceptGnu. I will have to add the mod in both branch and master (temporarily) to keep checking.
> 
> I'm assuming that e3sm has no nightlies on GPU (at least, none that tests homme), otherwise this error would have been caught? It's probably something that creeped in when the kokkos submodule was upgraded and started requiring c++14, which forced an update in the compilers.

Agreed on all points.

**Comment by ambrad** [comment]
@oksanaguba this PR is now ready for integration. It has some priority for SCREAM, so that HOMMEXX in E3SM and SCREAM match. For my own part, I'm going to rebase a branch I have going on this PR, so I don't need it in master right away. But I'm going to try to then get my own monstrous PR into master pretty soon. :) Thanks.

**Comment by oksanaguba** [comment]
Luca, i lost track of the issue with BFB macros. The code is bfb for gpu impl+macros and the only issue is that diagnostics in set_thermostate is not implemented for the BFB macros + EOS? If so, then was your plan to address the check only? If so, why is this a nonbfb PR?

If indeed this PR is nonbfb and only for that commit, would it be possible to separate this PR into 2, a large bfb PR and a small nonbfb PR? Sorry for not speaking earlier, I could do this change by myself since i did not suggest it before. i see that the PR only touches *pp files otherwise, but still. Thanks!

**Comment by bartgol** [comment]
HOLD ON! Pause everything! I accidentally tested the wrong branch. Turns out that there's an old branch `bartgol/homme_scream_changes` (notice "homme" instead of "hommexx") that got merge in master 9 months ago, and that's the one I checked out. Of course all tests passed.

@oksanaguba THANK YOU for you comments. Indeed, there _should_ be some non-bfb changes, which make the fact that all tests pass a bit suspicious...

I will add the WIP tag, and redo all testing, with and without the non-bfb changes.

I apololgize for the mistake. I went ahead and deleted the old branch from the remote, to make sure nobody else accidentally pulls the wrong branch.

**Comment by bartgol** [comment]
Ok, things weren't _that_ bad after all. @oksanaguba here's an explanation of the bfb vs non-bfb issue.

Without commit 6b12d6b (`HOMME: fix T<->VTheta check in set_thermostate`), this PR is bfb with master, and all unit+dev tests pass on weaver and mappy. That commit changes the impl of set_thermostate in the theta-l model, causing the initial state to not be bfb with what master does. In particular, the changes only show if `HOMMEXX_BFB_TESTING` is defined. These changes are meant to perform some EOS-related calculation in the same way as they are done in the eos module. E.g., use `bfb_pow(a,b)` instead of `a**b`. Without these changes, if HOMMEXX_BFB_TESTING is defined, the conversion T->Theta done in set_thermostate is not the "inverse" of what the eos module does, causing the check at the end of the routine to print lots of warnings.

This PR is back to be ready for integration. @ambrad , I didn't push anything else to this branch, so nothing to worry about even if you already rebased your branch on this one.

Again, sorry for the confusion. I'll  try to use more unique branch names in the future. And also clean up the repo from any old branch I might have. ;)

**Comment by oksanaguba** [comment]
For HOMMEBFB I got all pass on anvil, for optimized homme I got
```
The following tests FAILED:
          1 - verifyBaselineResults (Failed)
          2 - swtc1 (Failed)
          3 - swtc2 (Failed)
          4 - swtc5 (Failed)
          5 - swtc6 (Failed)
          6 - baro2b (Failed)
          7 - baro2c (Failed)
          8 - baro2d (Failed)
```
with nontrivial cprnc differences. Would you know what changes possibly change F code?
Like here
```
 2/32 Test  #2: swtc1 .................................***Failed   16.60 sec
Submitting 1 jobs
Running test swtc1-run ... /lcrc/group/e3sm/ac.onguba/scratch/anvil/HOMME_P24.f19_g16_rx1.A.anvil_intel.C.20210809_193550_dlo6a4/bld/tests/swtc1/swtc1-run.sh
test swtc1-run was run successfully
Test name = swtc1
Examining cprnc reference comparison output files
Test swtc1: no netcdf CHECKREF output files, skipping CHECKREF test.
Examining cprnc baseline comparison output files
file = swtc11.nc
The files are different or missing: DIFF_RESULT=DIFFERENT
############################################################################
CPRNC returned the following RMS differences
 RMS geop                             3.1507E-13            NORMALIZED  3.9335E-14
 RMS u                                6.5178E-15            NORMALIZED  2.6392E-16
 RMS v                                1.3931E-15            NORMALIZED  2.5866E-03
 RMS geop                             5.2920E-13            NORMALIZED  6.6042E-14
 RMS u                                6.5178E-15            NORMALIZED  2.6392E-16
 RMS v                                1.3931E-15            NORMALIZED  2.5866E-03
```

**Comment by oksanaguba** [comment]
atm_integration is all good on anvil.

**Comment by oksanaguba** [comment]
@bartgol  please, edit the description since the commit is reverted, thanks!

**Comment by ambrad** [comment]
@onguba, re: the HOMME standalone optimized-build tests on anvil: Just so we're sure of what we're comparing, I'm looking at the file
`/lcrc/group/e3sm/ac.onguba/scratch/anvil/HOMME_P24.f19_g16_rx1.A.anvil_intel.C.20210809_193550_dlo6a4/bld/tests/baro2c/baro2c.baro2c-run2-jw_baroclinic-000000000-1.nc.out`.
I see
```
 file 1=
 /home/ac.onguba/as/acme-tests/master/HOMME_P24.f19_g16_rx1.A.anvil_intel/tests/
 baseline/baro2c/movies/baro2c-run2-jw_baroclinic-000000000-1.nc
 file 2=
 /lcrc/group/e3sm/ac.onguba/scratch/anvil/HOMME_P24.f19_g16_rx1.A.anvil_intel.C.
 20210809_193550_dlo6a4/bld/tests/baro2c/movies/baro2c-run2-jw_baroclinic-000000
 000-1.nc
```
Where is the build for `/home/ac.onguba/as/acme-tests/master/HOMME_P24.f19_g16_rx1.A.anvil_intel`? I'd like to compare its CMakeCatch.txt with `/lcrc/group/e3sm/ac.onguba/scratch/anvil/HOMM\
E_P24.f19_g16_rx1.A.anvil_intel.C.20210809_193550_dlo6a4/bld/CMakeCache.txt`. Thanks.

**Comment by oksanaguba** [comment]
The build is in /lcrc/group/e3sm/ac.onguba/scratch/anvil/HOMME_P24.f19_g16_rx1.A.anvil_intel.G.20210809_192645_tgjvs3/bld , i do not see anything from comparing cache files.

**Comment by bartgol** [comment]
Should the line ` 1 - verifyBaselineResults (Failed)` be concerning? This PR does not introduce new baselines tests, so how come the baselines verification fails?

**Comment by oksanaguba** [comment]
i think that was an FS issue -- when i looked, baseline files were there and the corresponding tests (bubble) passed, which would not happen without files.

**Comment by bartgol** [comment]
I'm surprised that things changed in the Fortran code base. I'm even more surprised that SW tests are not passing. There were literally zero changes outside of cxx-related folders (the only exception was the element_ops change in theta-l/share, but it got reverted).

**Comment by oksanaguba** [comment]
on skybridge homme optimized build is bfb, I will merge today.

**Comment by oksanaguba** [comment]
in next

**Pull request merged**
