### PR TITLE
Adding SCORPIO to E3SM

### PR DESCRIPTION
**Pull request by jayeshkrishna**
This PR brings in v1.0.0 of SCORPIO to E3SM and includes
CIME changes required to use SCORPIO

* Scorpio classic (derived from PIO1) is now the default I/O library
  used by E3SM.
* E3SM users can choose to use scorpio (derived from PIO2) by
  changing the PIO_VERSION, in env_build.xml, to 2.
* Scorpio and scorpio classic libraries are included as git submodules
* Adding a compile time switch to disable the BGET memory allocator,
  due to its poor performance, in SCORPIO.
* The default rearranger is set to BOX

### CODE REVIEW

**Comment by dqwu** [comment]
@jayeshkrishna 
I have manually tested this branch on anlworkstation,

Both scorpio classic (derived from PIO1) and scorpio (derived from PIO2)
work as expected.

To run a G case with scorpio (PIO2), the only change required is to add
"-D USE_PIO2" flag for the MPAS components in config_compilers.xml.
Otherwise, we will encounter build errors like:
```
Error: Parameter ‘pio_offset’ at (1) has not been declared or is a variable, which does not reduce to a constant expression

Error: Parameter ‘mpas_io_offset_kind’ at (1) has not been declared or is a variable, which does not reduce to a constant expression
```

**Comment by jayeshkrishna** [comment]
MPAS fixes will be merged soon (there is a development branch with the fixes in MPAS repo) that will allow users to use SCORPIO without any changes (to avoid adding "USE_PIO2" compiler flag).

Also note that "scorpio classic" (the default - derived from PIO1) does not need any special flags to be used with MPAS components.

(The MPAS PR will be created once we merge this PR to E3SM master. Without this PR it would be hard to test the code)

**Comment by dqwu** [comment]
@jgfouca 
Based on latest e3sm_developer test results on anlworkation and cori-knl,
this PR does not break existing passed tests.

Could you please start to merge this PR to next/master? Thanks.

[e3sm_developer test results on anlworkstation]
There are 2 failures on anlworkstation with this PR (use GCC 8 and externals/scorpio_classic):
https://my.cdash.org/viewTest.php?onlyfailed&buildid=1696231

These failures are also on anlworkstation with E3SM master branch (use GCC 8 and cime/src/externals/pio1):
https://my.cdash.org/viewTest.php?onlyfailed&buildid=1696145

The 2 failed tests are mentioned in issue #3169

[e3sm_developer test results on cori-knl]
There are 2 failures on cori-knl with this PR (use intel 18 and externals/scorpio_classic):
https://my.cdash.org/viewTest.php?onlyfailed&buildid=1696176

These failures are also on cori-knl with E3SM next branch (use intel 18 and cime/src/externals/pio1):
https://my.cdash.org/viewTest.php?onlyfailed&buildid=1695503

**Comment by jgfouca** [comment]
Merged to next.

**Comment by jgfouca** [comment]
@jayeshkrishna , why was the scorpio submodule set to use http? It should use ssh like the others.

**Comment by dqwu** [comment]
@jgfouca 
Jayesh is on vacation this week.
Is there a reason that ssh is used for other submodules? I personally prefer to use http for all submodules, as it does not require ssh keys to be set up on each testing machine.

**Comment by jgfouca** [comment]
@dqwu ssh makes things much easier for the Jenkins automated testing. It allows us to reuse the same credentials for all the repos, it allows us to avoid http proxy issues, and it allows us to have non-public submodules without having to worry about passwords.

**Comment by dqwu** [comment]
@jgfouca 
Do you want to change the public scorpio submodule to use ssh before merging this PR to master?
Otherwise, if it does not cause issues for your Jenkins automated testing, we can keep http for now.

**Comment by jgfouca** [comment]
@dqwu , yeah I'm happy to do that if Jayesh doesn't mind me modifying his branch. Since he's on vaca, I'll assume he doesn't mind.

**Comment by dqwu** [comment]
@jgfouca 
OK, please go ahead to change http to ssh for the scorpio submodule, thanks.

**Pull request merged**
