### PR TITLE
Fixed missing use_case parameters introduced by clubbv2

### PR DESCRIPTION
**Pull request by wlin7**
Starting with the merge of clubbv2 (PR #2897), clubb_C1 and clubb_C1b,
as well as clubb_gamma_coef and clubb_gamma_coefb are set to be
fully independent namelist variables. Beforehand, clubb_C1b always varies with
clubbb_C1,, while clubb_gamma_coefb varies with clubb_gamma_coef when it
is not specified explicitly. Together with clubbv2 PR, these changes are
designed to be reflected via the use_case files that specifiy either or both clubb_C1
and clubb_gamma_coef. It appears one use_case file missed clubb_C1b and
seversl others missed both. The latter likely did not exist when clubbv2
PR was created.

Following use_case files are affected. Among the tests, only the
aquaplanet test is expected to diff in both the simulation and nml file.

   components/cam/bld/namelist_files/use_cases/1850S_cam5_CMIP6.xml
   components/cam/bld/namelist_files/use_cases/2010S_cam5_CMIP6.xml
   components/cam/bld/namelist_files/use_cases/20TR_cam5_CMIP6.xml
   components/cam/bld/namelist_files/use_cases/SSP585_cam5_CMIP6.xml
   components/cam/bld/namelist_files/use_cases/aquaplanet_EAMv1.xml

[non-BFB]  for the aquaplanet test.
[NML] diff for the aquaplanet test

### CODE REVIEW

**Comment by wlin7** [comment]
Post-clubbv2, not specifying clubb_C1b =1.335 in namelist likely caused the significant discrepencies in several global mean quantities for runs using compset F20TRC5-CMIP5 (or for compsets using 20TR_cam5_CMIP6.xml).

**Comment by kaizhangpnl** [comment]
"Among the tests, only the aquaplanet test is expected to diff in both the simulation and nml file." 
@wlin7 Do you mean the nightly tests?

**Comment by wlin7** [comment]
Note that, with post-clubbv2 master, coupled runs using compset A_WCYCL1850S_CMIP6, like piControl, are not affected.  Coupled runs using A_WCYCL20TRS_CMIP6 for historical run, would be affected.

**Comment by wlin7** [comment]
Yes, @kaizhangpnl , I meant the nightly test. The affected compsets are not used in the nightly tests.

**Comment by rljacob** [comment]
**Should** they be in the nightly tests?

**Comment by wlin7** [comment]
In case of interest, I used cori: ~wlin/bin/txtscan.pl to scan all the use case files, and print those that contain clubb_C1 and/or clubb_gamma_coef but missing clubb_C1b or clubb_gamma_coefb.

**Comment by kaizhangpnl** [comment]
It would be nice to have the "F20TRC5-CMIP6" compset in the nightly tests. This (AMIP type run) is frequently used.

**Comment by wlin7** [comment]
Totally agreed, Kai. Including  carefully selected compsets in  nightly tests would better safeguard the integrity of the repo. FC5AV1C-L (pointing to FC5AV1C-04P2) is used for many of the tests. This compset is considered deprecated now. It is time to replace it with one like F20TRC5-CMIP6.  However, if testing only one such compset would not prevent similar problem -- new nml variable in many use_case files -- from happening. A strict verification, like the script Balwinder and I used, will also help.

**Comment by wlin7** [comment]
@singhbalwinder , thanks for revisiting the original PR and reviewing this. I also believe the original PR missed gamma_coefb in only one file. The other use case files must have been introduced while clubbv2 was under testing and waiting to be merged. 

The extra entry in the three h01b use case files have now been removed. BTW, h01b does intend to use a gamma_coefb that is larger than gamma_coef.

**Comment by singhbalwinder** [comment]
Thanks @wlin7 !

**Comment by kaizhangpnl** [comment]
Well spotted! I didn't notice it when I looked at the "File changed" page.

**Comment by singhbalwinder** [comment]
@wlin7 : This PR is labeled BFB. If you think this PR will change answers for the following test case, should we change it to NBFB?
`SMS_B.ne4_ne4.F-EAMv1-AQP1.melvin_gnu.cam-hommexx`

**Comment by kaizhangpnl** [comment]
Shall we label it as FCC (flag climate changing)?

**Comment by singhbalwinder** [comment]
Thanks @kaizhangpnl. I thought these flags/parameters will be turned on (or used) by default. If that is the case, we should label is NBFB as integrating it will break the AQUA planet test. Please let me know if that is not correct.

**Comment by kaizhangpnl** [comment]
I am not sure if those compsets are included in the nightly tests. If so, I think it should be NBFB.

**Comment by wlin7** [comment]
Hi @singhbalwinder ,  the label is now changed to non-BFB. Both clubb_C1b and clubb_gamma_coefb need to be added for the aquaplanet test.

**Comment by singhbalwinder** [comment]
@wlin7 : I see this file (components/cam/bld/namelist_files/use_cases/aquaplanet_EAMv1.xml) modified in this PR. `clubb_C1b` and `clubb_gamma_coefb` are added to this file. Is there any other file we need to change? Sorry, I didn't follow your suggestion.

**Comment by wlin7** [comment]
@singhbalwinder , no other files affected. We both have examined them all since we noticed the missing parameter issues following the clubbv2 PR. The PR message summarizes the use_case files affected.

**Comment by rljacob** [comment]
@singhbalwinder can this be merged?

**Comment by singhbalwinder** [comment]
Pushed to next.

**Pull request merged**
