### PR TITLE
HOMME: adding HOMME_TEST_TIME_STEP cmake variable to configuration of namelists

### LINKED ISSUE #2594: Some HOMME tests failing due to negative thickness after PR #2531
Following PR #2531, some test in homme started to crash due to negative layer thickness.

In particular, tests preqx-nlev[26|72]-qsize4-r3-moist-[kokkos-]ne4-ndays2 are currently crashing. Notice that the ne2 test does not crash.

The crash happen with both gcc and intel. No datapoint yet on GPU (though I suspect it would fail there too).

### PR DESCRIPTION
**Pull request by bartgol**
PR #2531 contained a hard to detect bug, as explained at the end. Thanks to @ambrad for spotting the issue.

Basically, some tests were run with a time step that was too large, and crashed. However, since the f90 and cxx nc files were identical (only contianing the 1st timestep), tests would pass. Ultimately, this bug could have been spotted right away if HOMME's testing system checked the return code of the run before proceeding with calling cprnc on the outputs. You can see this defect by looking at a *-run.sh file in one of the tests folders (in the build tree).

Note: Fixes #2594 .

### CODE REVIEW

**Comment by mt5555** [comment]
There was a problem generating new baselines, related to PR #2531 
But looking on skybridge, it still has the old baselines from Oct 2.   

One possible thing that could have broken:  PR #2531 I believe changed the location of the test output (it moved the test output to a different directory).  This could have broken CIME's "-g" feature used to generate baselines, so when CIME copies the new baselines into the baseline archive directory, it cant find them.  

Can you amend this PR to address this issue as well?

Here's the error from running
./create_test -g -o HOMME_P24.f19_g16_rx1.A.sandiatoss3_intel -b master




xception during run:
ERROR: Job killed due to receiving signal 15 (SIGTERM)
Traceback (most recent call last):
  File "/gscratch/pwburge/ACME.master/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 14$
    self.run_phase()
  File "/gscratch/pwburge/ACME.master/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/homme.py", line 89, in run_phase
    stat = stat + run_cmd("{} -j 4 baseline".format(gmake), arg_stdout=log, combine_output=True, from_dir=exeroot_strict)[0]
  File "/gscratch/pwburge/ACME.master/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 427, in run_cmd
    output, errput = proc.communicate(input_str)
  File "/projects/sems/install/toss3/sems/compiler/python/2.7.9/lib/python2.7/subprocess.py", line 796, in communicate
    self.wait()
  File "/projects/sems/install/toss3/sems/compiler/python/2.7.9/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/projects/sems/install/toss3/sems/compiler/python/2.7.9/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
  File "/gscratch/pwburge/ACME.master/cime/scripts/Tools/../../scripts/lib/CIME/case/case_test.py", line 33, in _signal_hand$
    expect(False, "Job killed due to receiving signal {:d} ({})".format(signum, name))
  File "/gscratch/pwburge/ACME.master/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 130, in expect
    raise exc_type(msg)
SystemExit: ERROR: Job killed due to receiving signal 15 (SIGTERM)

**Comment by mt5555** [comment]
As the HOMMEXX integration is holding up several other PRs, I'll make the following suggestion:

homme.py is reverted back to its original in this PR.   I dont think CIME's homme.py should have machine dependent code in it.   Nor should homme.py have hardwired paths into individuals home directories.  

the HOMMEXX team should continue to test the kokkos and "strict" builds, but manually, outside of the CIME system.

Work with @jgfouca to develop a strategy to add kokkos support to E3SM.  After this strategy is implemented and tested, enable the kokkos tests in homme.py.

**Comment by bartgol** [comment]
@mt5555 I reverted homme.py to the pre-PR #2531  state. preqx_kokkos will now not be tested in the nightlies. We will work with @jgfouca to find a long term solution; there are a few other issues related to this pr, like c++11 compiler support or creating a kokkos module, so it's probably good to place all these efforts together.

Meanwhile, there should be no further blocking of other PRs when it comes to system test.

**Comment by oksanaguba** [comment]
yes, but it seems that the idea of testing preqx-kokkos in nightlies on sandiatoss is being reverted. i am still waiting for skybridge jobs for the latest change to go through.

**Comment by bartgol** [comment]
> it seems that the idea of testing preqx-kokkos in nightlies on sandiatoss is being reverted.

To be clear, it is only postponed by a bit, so that other PRs can go in and we can get a clean dashboard. I would hope in the next (very) few weeks we can fix the testing issues, and bring the kokkos target tests back online.

**Pull request merged**
