### PR TITLE
fix component namelist creation bugs when NINST>1

### LINKED ISSUE #4648: PGN test not configured for V2
Trying to run the PGN test with V2 results in configure errors with missing data sets.  This test case appears to rely on data that needs to exist in the clm2/initdata/"gridname"_v2_init/ directory.   This data only exists for v1, and the ne4_ne4 grid, running with the FC5AV1C-04P2 compset.   It looks like new data needs to be generated for v2, and for a v2 supported compset.  Instead of ne4_ne4, it might be better to use ne4_oQU240, to allow for the eventual use of F compsets using MPAS-I.  

As this test only runs for 1 timestep, why not use ne30?

Example:
```
./create_test PGN_P24x1.ne4_oQU240.F2010-CICE -q small -g -b master --baseline-root ~/scratch1/baselines/intel
...

        wget failed with output:  and errput --2021-11-08 17:18:30--  https://web.lcrc.anl.gov/public/e3sm/inputdata/lnd/clm2/initdata/ne4_oQU240_v2_init/20210915.v2.ne4_oQU240.F2010.elm.r.0002-06-01-00000.nc
```

### PR DESCRIPTION
**Pull request by mt5555**
A few bug fixes when running with NINST>1, as is done in the E3SM nbfb test suite

MPAS sea ice component should use NTASKS_PER_INST_ICE instead of NTASKS_ICE when determining which partition file to use

Ensure ATM and LND put the initial conditions from all ensemble members into the inputdata file list 

Similar fixes should probably be applied to the MPAS ocean (NTASKS_PER_INST_OCN) and ensemble member inputdata parsing for both MPAS ocean and ice.  Not done in this PR since we currently dont use this capability.  

fixes #4648, #4645

[BFB]

### CODE REVIEW

**Review by jonbob — APPROVED** [review]
Approved based on visual inspection -- and I will make a similar PR for mpaso and MALI

**Review by singhbalwinder — APPROVED** [review]
Looks good to me!

**Comment by rljacob** [comment]
@singhbalwinder please merge this.

**Comment by mt5555** [comment]
@singhbalwinder please merge this.

**Comment by singhbalwinder** [comment]
Merged to next

**Pull request merged**
