### PR TITLE
Replaces CLUBB with new version of CLUBB (V2): For re-merging

### PR DESCRIPTION
**Pull request by singhbalwinder**
NOTE: This PR is created to re-merge changes in PR #2897

The v1 version of CLUBB left pockets of supersaturation for the microphysics. To mitigate this, the
v2 version of CLUBB does CLUBB's saturation adjustment immediately before microphysics when
ipdf_call_placement = ipdf_pre_advance_fields.

CLUBB_v2 includes performance optimizations that may lead to speedups, but also may be vitiated
by a performance degradation in the CLUBB interface that was introduced in order to change the
position of the saturation adjustment.

CLUBB_v2 also adds new options that may be interest when tuning E3SMv2:

CLUBB's gustiness can be enhanced if C_wp2_splat is set to non-zero values. This may enhance the benefits found with Po-Lun Ma connection of CLUBB's gustiness and surface processes.

CLUBB_v2 can now prognose momentum fluxes if l_predict_upwp_vpwp = .true. This is designed to reduce ocean surface stress in cumulus regions.

[NBFB]

### CODE REVIEW

**Comment by wlin7** [comment]
@singhbalwinder , with this new PR, does that mean we don't need to revert the revert for #2897 before merging? I feel  that if we do a revert of the revert anyway, then merge this PR, it would have no harm either. Thanks.

**Comment by rljacob** [comment]
You will have to revert the revert.

**Comment by wlin7** [comment]
Got it. Thanks @rljacob . I am going to merge it this morning.

**Comment by wlin7** [comment]
@rljacob and @singhbalwinder , just to double check with you on the procedure for the remerging of CUBBv2.

1. revert the revert (of PR #2897)
2. merge this PR (#3109)  as usual.

And  no remerging of #2897 after step 1. 

I would like a confirmation from you because before having this new PR (#3109), the procedure we were talking about was to first revert the revert, then remerge the updated #2897 (which includes the changes made in #3109). Thanks.

**Comment by wlin7** [comment]
Merged to next.

**Comment by rljacob** [comment]
You have it right but you have to revert the revert on next as well.

**Comment by wlin7** [comment]
Thanks @rljacob. Done with next. I will wait until tomorrow for master and bless the DIFFs.

**Comment by rljacob** [comment]
@singhbalwinder how did you make this new branch?

**Comment by rljacob** [comment]
@wlin7 you didn't revert the revert on next.  See Slack.

**Comment by wlin7** [comment]
My bad. I did make sure to revert the revert first then merging this PR. I thought I was merging in sequence so I didn't push the revert-revert to remote. Didn't realize the script I used for merging would do a hard reset to origin/next again. It is  meant as an insurance policy for regular merge, but bad outcome in current sequence of actions.

**Comment by wlin7** [comment]
Re-did the merge to next. Note that with proper revert the revert committed, merging this PR did not experience conflict. Previously merging this PR using a script -- and voiding the revert, I did have to resolve "conflict" in clubb_intr.F90. That was a flag raised for me already.

**Comment by singhbalwinder** [comment]
Thanks @wlin7 ! Everything looks good now.

**Comment by wlin7** [comment]
Merged to master. Requests submitted to bless DIFFs on sandiatoss3 (39), melvin (7), anvil (1).

The SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.anvil_intel.allactive-v1cmip6 is a FAIL. It will need to be blessed (due to this PR) after MPAS-O build issue is resolved.

**Comment by wlin7** [comment]
For record, the DIFF SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.anvil_intel.allactive-v1cmip6 partly due to this PR  was blessed via @jonbob 's request following merge of PR #3056 .

**Comment by jonbob** [comment]
Sorry @wlin7 - I knew our MPAS PR had also changed answers but that test was failing for other reasons at the time it went in....

**Pull request merged**
