### PR TITLE
Add TL319_r05_IcoswISC30E3r5 configuration

### PR DESCRIPTION
**Pull request by jonbob**
Add a trigrid configuration for the IcoswISC30E3r5 ocn/ice mesh when using JRA forcing, for C- and G-cases.

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
@fspereira1 please approve.

**Review by fspereira1 — COMMENTED** [review]
It seems ok. I ran two cycles, and all looks good

**Review by fspereira1 — APPROVED** [review]
It seems ok. I ran two cycles, and all looks good

**Comment by jonbob** [comment]
Passes sanity testing with:
* ERS_Ld5.T62_oQU120.CMPASO-NYF.chrysalis_intel

Also passes use of the new configuration with:
* SMS_D_Ld1.TL319_r05_IcoswISC30E3r5.GPMPAS-JRA.chrysalis_intel

merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
