### PR TITLE
Homme: fix ICE

### PR DESCRIPTION
**Pull request by tcclevenger**
In SCREAMv1 runs on summit, with new SurfaceCoupling from https://github.com/E3SM-Project/scream/pull/1780, an ICE arises in homme boundary exchange.

### CODE REVIEW

**Comment by tcclevenger** [comment]
Labeling WIP since maybe this is not needed.

**Comment by oksanaguba** [comment]
Just FYI, anything that touches homme needs to go to E3SM, not scream, thanks.

**Comment by oksanaguba** [comment]
Is it correct that the fix is just to break 1 file into 2?

**Comment by bartgol** [comment]
> Is it correct that the fix is just to break 1 file into 2?

Yes. But we're puzzled as of why this ICE showed up while working in the SCREAM PR. We never touched the homme folder there, so it might be a red herring.

**Comment by oksanaguba** [comment]
my comment about scream PR was due to my confusion, sorry.

**Comment by bartgol** [comment]
Sure.

**Comment by tcclevenger** [comment]
This ICE was a symptom of a different issue. Closing.

**Pull request closed without merging**
