### PR TITLE
Add `e3sm_cryo_developer` test suite

### PR DESCRIPTION
**Pull request by xylar**
This merge adds data iceberg (DIB) and data ice-shelf melt flux (DISMF) files for the oQU240wLI mesh.

It then uses these files in tests added to a new `e3sm_cryo_developer` test suite.

### CODE REVIEW

**Comment by xylar** [comment]
See https://github.com/E3SM-Ocean-Discussion/E3SM/pull/89 for relevant discussion.

**Comment by xylar** [comment]
I tried to test this on Compy but can't log in (a frequent problem for me) and I don't have time to debug this.  Anyone else able to log in and try this out?

**Comment by xylar** [comment]
I got onto Compy again and am testing this now.

**Comment by xylar** [comment]
I successfully ran the `e3sm_cryo_developer` suite on Compy in about 57 minutes:
```
test-scheduler took 3433.970710992813 seconds
```

**Review by darincomeau — APPROVED** [review]
Approved based on testing in https://github.com/E3SM-Ocean-Discussion/E3SM/pull/89

**Review by cbegeman — APPROVED** [review]
Approving based on testing on perlmutter in https://github.com/E3SM-Ocean-Discussion/E3SM/pull/89.

**Comment by xylar** [comment]
@proteanplanet, could you review this when you have time?

**Review by proteanplanet — COMMENTED** [review]
Results from running this test suite on Anvil produces the following results:
```
  ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel (Overall: PASS) details:
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel CREATE_NEWCASE
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel XML
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel SETUP
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel SHAREDLIB_BUILD time=143
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel MODEL_BUILD time=833
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel SUBMIT
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel RUN time=65
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel COMPARE_base_rest
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel MEMLEAK insufficient data for memleak test
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel SHORT_TERM_ARCHIVER
  ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel (Overall: PASS) details:
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel CREATE_NEWCASE
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel XML
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel SETUP
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel SHAREDLIB_BUILD time=144
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel MODEL_BUILD time=836
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel SUBMIT
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel RUN time=62
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel COMPARE_base_rest
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel MEMLEAK insufficient data for memleak test
    PASS ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel SHORT_TERM_ARCHIVER
  PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel (Overall: PASS) details:
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel CREATE_NEWCASE
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel XML
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel SETUP
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel SHAREDLIB_BUILD time=141
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel MODEL_BUILD time=832
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel SUBMIT
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel RUN time=55
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel COMPARE_base_modpes
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel MEMLEAK insufficient data for memleak test
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel SHORT_TERM_ARCHIVER
  PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel (Overall: PASS) details:
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel CREATE_NEWCASE
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel XML
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel SETUP
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel SHAREDLIB_BUILD time=138
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel MODEL_BUILD time=832
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel SUBMIT
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel RUN time=55
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel COMPARE_base_modpes
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel MEMLEAK insufficient data for memleak test
    PASS PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel SHORT_TERM_ARCHIVER
  PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel (Overall: PASS) details:
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel CREATE_NEWCASE
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel XML
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel SETUP
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel SHAREDLIB_BUILD time=146
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel MODEL_BUILD time=1065
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel SUBMIT
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel RUN time=29
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel COMPARE_base_single_thread
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel MEMLEAK insufficient data for memleak test
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.anvil_intel SHORT_TERM_ARCHIVER
  PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel (Overall: PASS) details:
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel CREATE_NEWCASE
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel XML
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel SETUP
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel SHAREDLIB_BUILD time=145
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel MODEL_BUILD time=1066
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel SUBMIT
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel RUN time=36
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel COMPARE_base_single_thread
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel MEMLEAK insufficient data for memleak test
    PASS PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.anvil_intel SHORT_TERM_ARCHIVER
  SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.anvil_intel.mpaso-jra_1958 (Overall: FAIL) details:
    PASS SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.anvil_intel.mpaso-jra_1958 CREATE_NEWCASE
    PASS SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.anvil_intel.mpaso-jra_1958 XML
    PASS SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.anvil_intel.mpaso-jra_1958 SETUP
    PASS SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.anvil_intel.mpaso-jra_1958 SHAREDLIB_BUILD time=124
    PASS SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.anvil_intel.mpaso-jra_1958 MODEL_BUILD time=592
    PASS SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.anvil_intel.mpaso-jra_1958 SUBMIT
    FAIL SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.anvil_intel.mpaso-jra_1958 RUN time=79
```
Note the SMS test fails. That is not to say there is anything wrong with the test suite.  Before approving, perhaps @jonbob can take a look at /lcrc/group/e3sm/ac.afroberts/E3SM-Polar/Test.cryo.CryoTest2.add-e3sm-cryo-developer-suite.xylar.anvil to check on whether the test suite is problematic for the smoke test, or whether there are other issues.  It appears to me that the test suite is working.

**Comment by jonbob** [comment]
@proteanplanet -- I looked at the output from the failed run and I think the job is just too large to run on four anvil nodes. I'm testing on chrysalis

**Comment by jonbob** [comment]
It passed on chrysalis using the config_pes_tests.xml layout:
````
PASS SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.chrysalis_intel.mpaso-jra_1958 CREATE_NEWCASE
PASS SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.chrysalis_intel.mpaso-jra_1958 XML
PASS SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.chrysalis_intel.mpaso-jra_1958 SETUP
PASS SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.chrysalis_intel.mpaso-jra_1958 SHAREDLIB_BUILD time=134
PASS SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.chrysalis_intel.mpaso-jra_1958 MODEL_BUILD time=403
PASS SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.chrysalis_intel.mpaso-jra_1958 SUBMIT
PASS SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.chrysalis_intel.mpaso-jra_1958 RUN time=732
PASS SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.chrysalis_intel.mpaso-jra_1958 MEMLEAK insufficient data for memleak test
PASS SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.chrysalis_intel.mpaso-jra_1958 SHORT_TERM_ARCHIVER
````

**Review by proteanplanet — APPROVED** [review]
With subsequent testing by @jonbob, this test suite won't be able to run as configured on some machines, such as Anvil, but the SMS test failed for a good reason on that machine, and therefore successfully tested the model.   Approved.

**Comment by xylar** [comment]
I rebased to address the conflict with `e3sm_landice_developer`, which was recently added in the same location.

**Comment by jonbob** [comment]
Passes new e3sm_cryo_developer suite on chrysalis, as well as sanity testing. Merged to next

**Comment by jonbob** [comment]
verified the new files are on the inputdata repo and have the correct permissions

**Comment by jonbob** [comment]
merged to master and new baselines blessed -- except for mappy which may need help downloading the new files

**Comment by xylar** [comment]
Thank you @jonbob, @cbegeman, @proteanplanet and @darincomeau for helping to make this happen!

**Pull request merged**
