### PR TITLE
Separate removal of Antarctic river and ice runoff

### PR DESCRIPTION
**Pull request by xylar**
This is needed so we can remove ice (solid) runoff but not river (liquid) runoff.

This merge also removes `totalRemoved*RunoffFlux` variables.  These fields are computed incorrectly (they are missing `areaCell`) and are not currently used for anything within MPAS-Ocean or any diagnostics.

This is part of the design: https://acme-climate.atlassian.net/wiki/spaces/PSC/pages/4210098268/Design+Document+Data+iceberg+and+ice-shelf+melt+flux+patterns+for+E3SM+spin-up+runs
This is a high priority for the Polar team.

See https://github.com/E3SM-Ocean-Discussion/E3SM/pull/105 for some useful discussion and testing

[NML]
[non-BFB] for simulations with DIB and either DISMF or PISMF (data icebergs and data or prognostic melt rates)
[BFB] for simulations with snow-capping (e.g. current E3SM v3 production runs)

### CODE REVIEW

**Comment by xylar** [comment]
@jonbob, could you double check that I haven't messed up the namelist propagation from Registry to E3SM?

**Review by darincomeau — APPROVED** [review]
Approved based on review in Ocean Discussions PR

**Review by cbegeman — APPROVED** [review]
Approved based on review in https://github.com/E3SM-Ocean-Discussion/E3SM/pull/105. Let me know if you'd like any help with further testing.

**Comment by jonbob** [comment]
@xylar -- the bld files all look perfect. Thanks!

**Comment by jonbob** [comment]
I ran e3sm_cryo_developer on chrysalis and got NML DIFFs for all of the tests, but these were otherwise BFB:
````
  ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.chrysalis_intel
  ERS_Ld5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.chrysalis_intel
  PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.chrysalis_intel
  PEM_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.chrysalis_intel
  PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-DISMF.chrysalis_intel
  PET_Ln5.T62_oQU240wLI.GMPAS-DIB-IAF-PISMF.chrysalis_intel
````
only 
````
SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.chrysalis_intel.mpaso-jra_1958
````
was non-BFB. But maybe that makes sense -- CORE-II forcing doesn't have any frozen runoff

**Comment by jonbob** [comment]
A test of
````
ERP_Ld3.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-pioroot1
````
also passes but has a NML DIFF, as expected

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master and expected NML and regular DIFFs blessed

**Pull request merged**
