### PR TITLE
Fix Phosphorus Balance Error in crop model

### LINKED ISSUE #6188: ERROR: Unknown error in `EcosystemBalanceCheckMod.F90` with `SMS_D_Ly2_P1x1.1x1_smallvilleIA.IELMCNCROP.pm-cpu_gnu.elm-fan`
With master of Jan23 and `SMS_D_Ly2_P1x1.1x1_smallvilleIA.IELMCNCROP.pm-cpu_gnu.elm-fan`
Also see fail with intel and DEBUG

```
0:  ERROR: Unknown error submitted to shr_abort_abort.
0: #0  0x234a924 in __shr_abort_mod_MOD_shr_abort_backtrace
0:      at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/share/util/shr_abort_mod.F90:104
0: #1  0x234aada in __shr_abort_mod_MOD_shr_abort_abort
0:      at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/share/util/shr_abort_mod.F90:61
0: #2  0x66f27d in __abortutils_MOD_endrun_vanilla
0:      at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/components/elm/src/main/abortutils.F90:43
0: #3  0x1553a50 in __ecosystembalancecheckmod_MOD_colpbalancecheck
0:      at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/components/elm/src/biogeochem/EcosystemBalanceCheckMod.F90:767
0: #4  0x69823e in __elm_driver_MOD_elm_drv
0:      at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/components/elm/src/main/elm_driver.F90:1335
0: #5  0x65d258 in __lnd_comp_mct_MOD_lnd_run_mct
0:      at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/components/elm/src/cpl/lnd_comp_mct.F90:617
0: #6  0x48441a in __component_mod_MOD_component_run
0:      at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/driver-mct/main/component_mod.F90:734
0: #7  0x467be1 in __cime_comp_mod_MOD_cime_run
0:      at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/driver-mct/main/cime_comp_mod.F90:2920
0: #8  0x481785 in cime_driver
0:      at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/driver-mct/main/cime_driver.F90:153
0: #9  0x4817e8 in main
0:      at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/driver-mct/main/cime_driver.F90:23
```

which looks like caught error in land, where last line in land log: 
```
 warning: FAN cannot spread manure
 column pbalance error =   -9.2743424077828759E-004           6
 Latdeg,Londeg=   40.687800000000003        267.02280000000002
 begpb       =    5.7909734729572468E-003
 endpb       =    6.7184084288024722E-003
 delta store =    9.2743495584522544E-004
 input mass  =    7.1507958115009793E-010
 output mass =    1.2643257705751606E-014
 net flux    =    7.1506693789239220E-010
 ptol_pflux: =    4.1496739374189992E-009
 sminp_to_plant: =    0.0000000000000000
 primp_to_labilep =    7.1507958115009793E-010
 supplement_to_sminp =    0.0000000000000000
 secondp_to_occlp =    1.6315555778758414E-015
 sminp_leached =    1.1011702127875765E-014
 ENDRUN:ERROR in /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/components/elm/src/biogeochem/EcosystemBalanceCheckMod.F90 at line 767                                                                                                                               \
                                                                                                                                                                                                                                                                  \

 ERROR: Unknown error submitted to shr_abort_abort.
```

### PR DESCRIPTION
**Pull request by bbye**
Phosphorus fertilizer wasn't accounted for in balance check.

[BFB] 
Fixes #6188

### CODE REVIEW

**Comment by evasinha** [comment]
@bbye Consider adding a print line if error is found. So adding this at around line 762:
`write(iulog,*)'fert_p_to_sminp = ', fert_p_to_sminp(c)*dt`

**Comment by bbye** [comment]
Thanks for the suggestion @evasinha. I added the print statement.

**Review by evasinha — APPROVED** [review]
@bbye I approve the PR for merge.

**Comment by peterdschwartz** [comment]
Testing shows a FAIL for an ECA test `ERS.f19_g16.I1850CNECACTCBC.pm-cpu_intel.elm-eca`

```
34:  column pbalance error =   1.061249623008545E-008       18210
 34:  Latdeg,Londeg=  -2.84210526315798        140.000000000000
 34:  begpb       =   8.606565047878752E-002
 34:  endpb       =   8.607360374064804E-002
 34:  delta store =   7.953261860524363E-006
 34:  input mass  =   7.932036868076347E-006
 34:  output mass =  -3.183748867810175E-008
 34:  net flux    =   7.963874356754449E-006
 34:  ptol_pflux: =   1.795638493039553E-006
 34:  sminp_to_plant: =   0.000000000000000E+000
 34:  primp_to_labilep =   3.287296012002345E-013
 34:  supplement_to_sminp =   0.000000000000000E+000
 34:  secondp_to_occlp =   4.234904232318074E-025
 34:  sminp_leached =  -3.183748867810175E-008
 34:  ENDRUN:
 34:  ERROR in EcosystemBalanceCheckMod.F90 at line 774
```

**Comment by bbye** [comment]
I see why. This is related to Issue #6052. I forgot I defined the nstep to ensure the modification for the crop model would work once it was added. Do you want me to pull that part out until someone addresses the other issue with the ECA code?

**Comment by peterdschwartz** [comment]
@bbye Yes, go ahead and do that. Hopefully I'll have time in the next couple of weeks to investigate the eca fail.

**Comment by bbye** [comment]
OK, I removed the nstep assignment.

**Comment by peterdschwartz** [comment]
Merged to next.

 testing did not show any diffs in the test suite (at least for pm-cpu_intel)

**Comment by peterdschwartz** [comment]
merged to master -- no diffs on any other machines so I  changed this PR to BFB

**Pull request merged**
