### PR TITLE
Add compsets and associated specs for chemUCI-Linoz

### PR DESCRIPTION
**Pull request by wlin7**
Compsets F20TR_chemUCI-Linozv2 and F20TR_chemUCI-Linozv3 are
added to support the configurations of coupling UCI gas chemistry
with Linozv2 or Linozv3. The configurations use online chemistry
mechanism.

### CODE REVIEW

**Comment by tangq** [comment]
@singhbalwinder , just so you know @wlin7 and I spoke today and more changes will be added to this PR soon.

**Comment by tangq** [comment]
@wlin7 , I see you pushed more commits after we talked. Is this PR already for me to test now? Thanks.

**Review by tangq — APPROVED** [review]
@wlin7 , it looks good to me. Please go ahead and merge it. Could you send me the git commands for merging, so I can do it by myself next time? Thanks!

**Comment by wlin7** [comment]
Merged, @tangq . The command I used is "git merge --no-ff origin/wlin/atm/compsets_chem_uci_linoz". Use the branch in origin in case the checked out one is not up to update, which is likely when there are multiple persons working on the branch.

**Comment by tangq** [comment]
Thank you, @wlin7 !

**Pull request merged**
