### PR TITLE
Control ouput of MPI task to compute node mapping data

### PR DESCRIPTION
**Pull request by worleyph**
A recent PR fixed the output of component-specific MPI task to compute
node mapping for ATM and LND, and added it for ROF, OCN, ICE, and
GLC. The utility of this output for each component is unclear, and a
namelist variable to enable  or disable it is added here. This
variable also allows setting  the format of the output. All component
model task-to-node mapping output is controlled by this single
cime_pes namelist variable info_taskmap_comp, where setting this to 0
disables output,  setting it to 1 uses the more compact format, and
setting it to 2 uses the more verbose format.

Note that a separate component-only PR will be needed for the
components to be aware of info_taskmap_comp and use this as described
above, but this additional code has been used to test this PR.

For symmetry, a cime_pes namelist variable info_taskmap_model
was also added to control the task-to-node mapping output for
the full coupled model, with the same options (0, 1, and 2). The
default here is 2 (preserving the current behavior).

Also for symmetry, output of task-to-node mapping data was added
for the CPL component (and is controlled by info_taskmap_comp the same
as for the other component models).

Finally, the implementation for the whole-model task-to-node mapping
data output was modified to better reflect the (currently incomplete?)
support for running the model with multiple drivers.

The two new namelist parameters were added to env_run.xml, and should
be set from there.

[BFB]
[NML]

### CODE REVIEW

**Comment by worleyph** [comment]
@amametjanov , this supplies the requested control of the task-to-node mapping output. If accepted, I will need to submit a new component-only PR (after #2486 is merged) to finish the job. @rljacob , if this one goes in first, I can add the needed changes to #2486 before you merge it if you wish.

Note: I am often not comfortable modifying CIME, as I do not understand (or remember) important aspects of the overall design. This applies here. The only place that I could add the namelist variables in order for them to be available in time to be used is cime_pes, which seems a reasonable location in my opinion. I then tested by adding these to user_nl_cp to exercise the nondefault options. I did not look at adding them to env_run.xml, because I do not remember how this is done. @amametjanov , please comment on whether you believe that these (info_taskmap_model and info_taskmap_comp) should be exposed in env_run.xml or not, and what I should do to make this happen.

As far as the implementation goes, format statements are used with a couple of different "styles" in cime_comp_mod.F90 . I went with what was easiest for me (same style I used in the component models). I can change to something else - I just need direction. Also, I modified some of the existing code for writing out the task-to-node mapping information in seq_comm_mct.F90 to try to be compatible with the support for multiple drivers. As far as I can tell the multiple driver support is unfinished, but I tried to guess at what would make sense. The implementation works for normal usage in my testing.

**Comment by worleyph** [comment]
This has been tested with A_WCYCL1950S_CMIP6_LR and FC5AV1C compsets on Cori-KNL.

**Comment by worleyph** [comment]
@amametjanov, I decided to go-ahead and add these to env_run.xml . I disabled both by default for  CESM and set INFO_TASKMAP_MODEL=2, INFO_TASKMAP_COMP=0 by default for E3SM. Please check that I did these correctly, and point out what other changes I should make in order to add new namelist and env_run.xml variables. Thanks.

**Comment by worleyph** [comment]
"Figured out" what I should do to make the write format specification in line with what is used elsewhere in this part of the code and pushed an update. Checked that this did not break anything (compiled and ran test on Cori-KNL).

**Comment by jgfouca** [comment]
Waiting for @rljacob to review.

**Comment by worleyph** [comment]
Hi @jgfouca , since the Melvin issues have been resolved and both reviews have come back, can this PR be merged soon? I have one more PR on this topic to submit, but need to wait for this PR to be merged before starting. Thanks.

**Comment by jgfouca** [comment]
@worleyph , sry I forgot about this, pushed to next.

**Comment by worleyph** [comment]
Thanks!

**Comment by worleyph** [comment]
@jgfouca , is this ready to be pushed to master? Thanks.

**Pull request merged**
