### PR TITLE
Removed defunct standalone testing infrastructure

### PR DESCRIPTION
**Pull request by akturner**
Standalone sea ice infrastructure is now in a seperate repo

Fixes https://github.com/E3SM-Project/E3SM/issues/5476

[BFB]

### CODE REVIEW

**Review by eclare108213 — COMMENTED** [review]
It looks like the only changes here are file deletions -- a lot of them -- which should NOT affect E3SM in other configurations.  I'm asking @proteanplanet to take a look too, in case I'm missing something.

**Comment by proteanplanet** [comment]
@akturner Why not follow the suggested approach at https://github.com/E3SM-Project/E3SM/issues/5440?  The stand-alone infrastructure you have built is valuable, and my understanding is that the E3SM project repo is now where MPAS-SeaIce lives. It seems that a lot of valuable work is being deleted, when it should still reside with the sea ice model.

**Comment by akturner** [comment]
@proteanplanet: Everything is available as https://github.com/MPAS-Dev/MPAS-Seaice_standalone_framework. As explained previously it was too difficult to get E3SM reviews for frequent changes to this framework.

**Comment by eclare108213** [comment]
Then the solution OUGHT to be to fix the review process.  Is there a Confluence page somewhere that describes how this is supposed to work?  I've noticed several things about it that seem odd to me, maybe just because I'm unfamiliar.  If it's not working, I do think it's worth trying to adjust.  It's the reason why MPAS was pulled entirely into E3SM, right?  So it's possible to improve such things.

**Comment by proteanplanet** [comment]
This PR seems to open three issues that need to be resolved:
1) My understanding is that the stand-alone testing infrastructure is out of date in the E3SM repo, and therefore needs to be brought up to date from MPAS-Dev rather than just being deleted.
2) It's important the stand-alone testing infrastructure does not disappear from E3SM since it belongs to the project.  We are developing a parallel testing platform that uses E3SM infrastructure, but keeping the stand-alone work as a comparison remains important; the new testing development that uses E3SM infrastructure will span phase 3. 
3) If the review of these development tools is problematic in E3SM, that needs to be addressed rather than abandoned.

**Review by proteanplanet — COMMENTED** [review]
Will approve this request imminently following the plan of action at https://github.com/E3SM-Project/E3SM/issues/5440#issuecomment-1470972018.

**Review by proteanplanet — APPROVED** [review]
Since this testing infrastructure is out of date and not in sync with MPAS-Dev, I approve this PR.  In future, we need a way to make sure that the one place where stand-alone MPAS-SI testing is housed remains accessible and usable within E3SM-Project. Inside Polaris may make sense.

**Review by eclare108213 — APPROVED** [review]
I agree with @proteanplanet. The entire testing infrastructure for MPAS-SI needs to be reviewed, reorganized, and made more user-friendly for E3SM development purposes.  In the meantime, it makes no sense to try to maintain duplicate copies of the standalone tests.

**Comment by jonbob** [comment]
passes sanity testing, merged to next

**Pull request merged**
