### PR TITLE
Update Summit and Ascent machine config

### PR DESCRIPTION
**Pull request by amametjanov**
Update Summit and Ascent machine config:
- add custom Perl install on Ascent
- update CIME syntax for SMT batching on Ascent and Summit
- update Summit's python to 3.7.0
- enable C++14 kokkos builds with IBM compilers on Summit
- add CXXFLAGS for threading on summit+ibm
- add -qnosmp to NOOPT_FILES for summit+ibm
- add a 1-node default pelayout
- replace a goto with a loop exit in COSP2 submodule

Fixes E3SM-Project/E3SM#4420

[NML] - due default pelayout changes

### CODE REVIEW

**Comment by rljacob** [comment]
Can we just do something like this for Theta @sarich ?

**Comment by dqwu** [comment]
@amametjanov 
If the gcc module for summit is upgraded to a higher version in the future, the path /sw/summit/gcc/8.1.1/lib64 also needs to be updated, right?

**Comment by amametjanov** [comment]
Not necessarily (unless they delete `/sw/summit/gcc/8.1.1`).
The latest `xl/16.1.1-10` is still configured with gcc-4.8.5.
Loading of `gcc/8.1.1` unloads any `xl` module.
So we have to be more explicit in linking with newer gcc.

**Comment by dqwu** [comment]
@amametjanov 
parallel-netcdf/1.12.1 and parallel-netcdf/1.12.2 are available on Summit now.
Could you please consider upgrading parallel-netcdf/1.8.1 (out of date) to one of them in this PR? Thanks.

**Review by dqwu — APPROVED** [review]

**Pull request merged**
