### PR TITLE
Refactor of MPAS-Seaice velocity solver

### PR DESCRIPTION
**Pull request by akturner**
Refactor of MPAS sea ice velocity solver to allow easier testing of new options and methods
Move domain reference to within subroutines avoiding messy passing of variables 
Move wachspress basis routines to separate module
Move triangular quadrature rules to new module
Move some mesh related routines to the mesh module 
Rename block variable to blockPtr
Rename all pool types to end in Pool

Fixes https://github.com/E3SM-Project/E3SM/issues/5289

[BFB]

### CODE REVIEW

**Comment by akturner** [comment]
@amametjanov Hi, i added you as a reviewer to make sure my changes don't affect performance

**Comment by jonbob** [comment]
@amametjanov - if you get time, could you please review this? Thanks

**Review by amametjanov — APPROVED** [review]
Everything looks good. Branch also passes
- SMS_Ld1.T62_oEC60to30v3.DTESTM.ascent_pgigpu
- SMS_Ld1.T62_oEC60to30v3.DTESTM.ascent_ibmgpu

**Comment by jonbob** [comment]
passes:
* SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod
* SMS_D_Ld1.T62_oEC60to30v3.DTESTM.chrysalis_intel
* PEM.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod

merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
