### PR TITLE
Fix ne30pg2 domain files

### PR DESCRIPTION
**Pull request by whannah1**
Previous domain files were erroneously created using an ocean mask from the coarse oQU240 grid. This updates the ne30pg2 configuration to use new domain files generated using the gx1v6 grid file for the ocean mask. This clears up issues along coastlines and inland bodies of water, such as the Caspian and Black seas. domain files for the oECv3 grid were also generated and put on the inputdata server, so I've included them as well.

[non-BFB] for ne30pg2, BFB otherwise.

### CODE REVIEW

**Comment by ambrad** [comment]
I have a physgrid run queued on cori-knl using these. I'll report back when it's done. Ping me if a few days pass and I've forgotten.

**Comment by rljacob** [comment]
@ambrad how did your testing go?

**Comment by ambrad** [comment]
@rljacob, thanks for pinging me; I forgot to update this page. The test shows excellent results and is documented in the section "FC5AV1C-L ne30pg2 with good domain files" on the Confluence "Physgrid results" page.

**Comment by rljacob** [comment]
merged to next.

**Pull request merged**
