### PR TITLE
Add a new machine for the singularity container

### PR DESCRIPTION
**Pull request by lukaszlacinski**
An E3SM Singularity container has been created with all prerequisites needed to run the E3SM model within the container. This PR adds machine and compiler config elements for the E3SM Singularity container.

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
"The doc describing how to use the container to run the E3SM model is at https://acme-climate.atlassian.net/wiki/spaces/ED/pages/1429831693/Singularity+container.

(This PR is a re-do of https://github.com/E3SM-Project/E3SM/pull/3572, but from a different branch)."

**Comment by rljacob** [comment]
This is still not working for me.   Build error while building scorpio.
See /gpfs/fs1/home/jacob/projects/e3sm/scratch/singXcase/bld/pio/pio.bldlog.200721-212448
The case dir is in: /gpfs/fs1/home/jacob/E3SM/cime/scripts/singXcase

**Comment by rljacob** [comment]
Did you update the container?  I'm still using the one at https://esgf.anl.gov/monitor/e3sm.sif

**Comment by lukaszlacinski** [comment]
It built successfully about one month ago. Now, when I checked out the repo, I am getting the same error. The model does not build now on ANL compute00[12] nodes either. I am investigating.

**Comment by rljacob** [comment]
Its probably the switch to scorpio.   Building the I/O stack is not easy.  You could just do netcdf-classic in the container (no HDF5).  Or maybe just pnetcdf but I don't know what it means to do parallel I/O from a container.

**Comment by lukaszlacinski** [comment]
1) It turned out that the machine and compiler config files needed HDF5_PATH variable to be added to build the master branch after the recent changes to the I/O stack.
2) I also added '-launcher fork' option to mpirun. Otherwise, when the model was run within the container on Anvil, MPICH Process Manager (Hydra?) was detecting SLURM and tried to launch e3sm.exe processes using srun.

I also updated 'Run the container on Anvil' section on the confluence page, https://acme-climate.atlassian.net/wiki/spaces/ED/pages/1429831693/Singularity+container.

**Comment by rljacob** [comment]
Did you need to update the container or just the config file entries?

**Comment by lukaszlacinski** [comment]
Only the config files entries needed to be changed/added.

**Comment by lukaszlacinski** [comment]
> Did you update the container? I'm still using the one at https://esgf.anl.gov/monitor/e3sm.sif

I use the same container:
$ md5sum e3sm.sif 
23eb21bcfc05496f235c5b06f97702c7  e3sm.sif

**Comment by rljacob** [comment]
Was able to build and run an X case with the container on anvil!

**Comment by rljacob** [comment]
merged to next

**Pull request merged**
