### PR TITLE
Updating Scorpio to 1.2.1

### LINKED ISSUE #4174: Zero values written in MPAS monthly timeseries files with WC on chrysalis, certain PE layouts, and PIO settings
Our v1 highres control production run (as well as the transient run) that we moved from theta to chrysalis was found to have zeros in the `mpaso.hist.am.timeSeriesStatsMonthly.*.nc` file. These runs use the maint-1.0 repo and I've verified the issue is the same for a repo of January 2021 as well as March 18th 2021.  The files written on Theta do not show the issue.
After a fair amount of testing documented here: 

https://acme-climate.atlassian.net/wiki/spaces/SIM/pages/1025639219/Control+Run+HighRes+MIP+theta.20190910.branch+noCNT.A+WCYCL1950S+CMIP6+HR.ne120+oRRS18v3+ICG

Im now able to repeat the issue given the script below.


```
#! /bin/csh                                                                                                                           

#set case = /lcrc/group/e3sm/ac.ndkeen/scratch/chrys/maint10-mar18/v1hires.ne120np4_oRRS18to6v3_ICG.A_WCYCL1950S_CMIP6_HR.n109a.prod-\
unc06g                                                                                                                                
set case = /lcrc/group/e3sm/your_location

create_newcase --case $case --res ne120np4_oRRS18to6v3_ICG --compset A_WCYCL1950S_CMIP6_HR --machine chrysalis --compiler intel --project e3sm

cd $case

xmlchange PIO_VERSION=2
xmlchange PIO_BUFFER_SIZE_LIMIT=134217728
xmlchange PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO=64

xmlchange RUN_STARTDATE=0055-12-01

xmlchange --id CAM_CONFIG_OPTS --append --val=-cosp

xmlchange --id STOP_OPTION --val nmonths
xmlchange --id STOP_N --val 1
xmlchange --id REST_OPTION --val nmonths
xmlchange --id REST_N --val 1
xmlchange --id BUDGETS --val TRUE
xmlchange --id HIST_OPTION --val nyears
xmlchange --id HIST_N --val 1

# use 109 nodes, 64x1                                                                                                                 
xmlchange MAX_MPITASKS_PER_NODE=64
xmlchange MAX_TASKS_PER_NODE=128

xmlchange ATM_NTASKS=5440
xmlchange LND_NTASKS=4672
xmlchange ICE_NTASKS=5120
xmlchange OCN_NTASKS=1536
xmlchange CPL_NTASKS=5440
xmlchange ROF_NTASKS=768

xmlchange ATM_ROOTPE=0
xmlchange LND_ROOTPE=0
xmlchange ICE_ROOTPE=0
xmlchange OCN_ROOTPE=5440
xmlchange CPL_ROOTPE=0
xmlchange ROF_ROOTPE=4672

xmlchange NTHRDS=1

# these aren't important, but just try to be same as run_e3sm                                                                         
xmlchange ESP_NTASKS=1
xmlchange ESP_NTHRDS=1
xmlchange GLC_NTASKS=32
xmlchange GLC_NTHRDS=1
xmlchange WAV_NTASKS=32
xmlchange WAV_NTHRDS=1

xmlchange USER_REQUESTED_QUEUE=compute

cp -p /lcrc/group/e3sm/ac.ndkeen/20180410.A_WCYCL1950_HR.ne120_oRRS18v3_ICG.theta-archive-rest-0136-10-01.unc06/maltrud.streams.seaice SourceMods/src.mpascice/streams.seaice


cat <<EOF >> user_nl_cam                                                                                                              
use_hetfrz_classnuc = .false.                                                                                                         
nhtfrq = 0,-24,-6,-6,-3,-1                                                                                                            
mfilt = 1,30,120,120,240,720                                                                                                          
avgflag_pertape = 'A','A','I','A','I','A'                                                                                             
fincl1 = 'IEFLX','extinct_sw_inp','extinct_lw_bnd7','extinct_lw_inp'                                                                  
fincl2 = 'FLUT','PRECT','U200','V200','U850','V850','Z500','Z200','OMEGA500','UBOT','VBOT','TREFHT','TREFHTMN:M','TREFHTMX:X','QREFHT','TS','PS','TMQ','TUQ','TVQ'                                                                                                         
fincl3 = 'PSL','T200','T500','Z300','Z500','U850','V850','UBOT','VBOT','TREFHT','FLUT','TMQ','TUQ','TVQ'                              
fincl4 = 'FLUT','U200','U850','PRECT','PRECC','OMEGA500','PRECSC','PRECSL'                                                            
fincl5 = 'PRECT:A','PRECC:A'                                                                                                          
                                                                                                                                      
cosp_lite = .true.                                                                                                                    
fexcl1 = 'CFAD_SR532_CAL'                                                                                                             
EOF                                                                                                                                   

cat <<EOF >> user_nl_mpaso                                                                                                            
config_am_timeseriesstatsdaily_write_on_startup = .true.                                                                              
EOF 

cat <<EOF >> user_nl_mpaso                                                                                                            
config_am_timeseriesstatsdaily_write_on_startup = .true.                                                                              
EOF                                                                                                                                   

cat <<EOF >>user_nl_mpascice                                                                                                          
config_reuse_halo_exch = true                                                                                                         
config_am_timeseriesstatsdaily_enable = true                                                                                          
EOF                                                                                                                                   

pwd

case.setup >& csout.txt

echo " building"
case.build >& buildout.txt

ls -l bld/*.exe*

./preview_run >& prout.txt
cat prout.txt

echo " submitting"
case.submit -a="-t 3:40:00" >& submitout.txt
```

The output for the job I ran with this script is here:
```
/lcrc/group/e3sm/ac.ndkeen/scratch/chrys/maint10-mar18/v1hires.ne120np4_oRRS18to6v3_ICG.A_WCYCL1950S_CMIP6_HR.n109a.prod-unc06g
```

To verify if a mpas timeseries file has zeros or not, I've found the following command useful (this output shows zeros):
```
chrlogin2% ncdump -v timeMonthly_avg_activeTracers_temperature run/mpaso.hist.am.timeSeriesStatsMonthly.*.nc | grep -m1 -A3 "data:" | grep ","
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
```

It may be a combination of the PE layout and the PIO settings: 
```
xmlchange PIO_BUFFER_SIZE_LIMIT=134217728
xmlchange PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO=64
```

I'm trying to further narrow down the issue, but as the issue requires a full month of high res, each job is several hours.

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Updating Scorpio from v1.0.1 to v1.2.1 and changing
the default I/O library to Scorpio (PIO_VERSION=2)

Scorpio v1.2.1 includes the following changes after
v1.0.1,

* Scorpio I/O performance statistics
* Performance improvments for the data rearrangers
* Multiple fixes and performance enhancements for
  ADIOS (including the ADIOS to NetCDF converter)
* Updates to use MPI_Isends() by default (instead
  of MPI_Irsends)
* Fixes for standalone HOMME
* Fixes for E3SM ultra high resolution simulations
* Misc bug fixes

Fixes #4174 

[BFB]

### CODE REVIEW

**Comment by ndkeen** [comment]
Weren't we also going to change the default PIO_VERSION from 1 to 2?

**Comment by jayeshkrishna** [comment]
I hadn't added the changes assuming that we might upgrade CIME later.
But after communicating with Rob I am now going to manually modify CIME to change the default to Scorpio (PIO_VERSION=2) on maint-1.0 . I will update the PR once I have merged the new changes.

**Comment by jayeshkrishna** [comment]
I have now changed the default I/O library to Scorpio on maint-1.0

**Comment by ndkeen** [comment]
I just tested `e3sm_developer` on chrysalis and looks fine (amazing how fast it runs there). The only fails were HOMME building and `SMS_R_Ld5.T42_T42.FSCM5A97` setup -- but both have same issue before this change, are clearly not related to scorpio, and not relevant for the production tests anyway.  Also running a e3sm_developer on cori-knl.

And also running on chrysalis is a 1-month test of our v1 hires transient run with a 64-node layout. After 180 ATM timesteps it looks BFB, but will also look at the output files when they are complete -- perhaps after another month to test restart reading.

**Comment by ndkeen** [comment]
On Cori, the `ERIO.ne30_g16_rx1.A` test failed.

```
17: forrtl: error (73): floating divide by zero
17: Image              PC                Routine            Line        Source             
17: e3sm.exe           000000000115C17E  Unknown               Unknown  Unknown
```

As well as the following 3 tests:

```
ERS.f19_g16.I1850CLM45.cori-knl_intel.clm-vst
ERS.f19_g16.I1850CNECACNTBC.cori-knl_intel.clm-eca
ERS.f19_g16.I1850CNECACTCBC.cori-knl_intel.clm-eca
```

I've not verified if these tests pass before this scorpio update.

**Comment by dqwu** [comment]
I have run the following 3 tests on Cori with latest maint-1.0 branch and default scorpio v1.0.1:
```
ERS.f19_g16.I1850CLM45.cori-knl_intel.clm-vst
ERS.f19_g16.I1850CNECACNTBC.cori-knl_intel.clm-eca
ERS.f19_g16.I1850CNECACTCBC.cori-knl_intel.clm-eca
```
They all failed, too.

**Comment by ndkeen** [comment]
Just noting while we are moving forward with the v1hires production runs without this, it still seems to make sense to merge it for any future new cases with maint-1.0.

**Comment by jayeshkrishna** [comment]
@ndkeen can you review/approve the PR ?

**Review by ndkeen — APPROVED** [review]

**Pull request merged**
