### PR TITLE
Update MMF tests

### PR DESCRIPTION
**Pull request by whannah1**
Add new MMF test mods for variance transport and momentum transport options and rename "crmout" test mod for consistency. This also updates MMF integration tests to include the new test mods.

[BFB] (except for 3 MMF tests)

### CODE REVIEW

**Comment by rljacob** [comment]
Note:  I asked Michael Kelleher to add his change to a different test to this PR.  Its just one character on one line.

**Comment by whannah1** [comment]
@rljacob sounds good.

**Comment by brhillman** [comment]
Merged to next.

**Comment by brhillman** [comment]
Merged to master.

**Pull request merged**
