### PR TITLE
Hommexx: Add a missing Kokkos::single to ps update in forcings.

### PR DESCRIPTION
**Pull request by ambrad**
This affects ftype 0 on the GPU.

[BFB]

### CODE REVIEW

**Comment by ambrad** [comment]
When incorporated into SCREAM, passes v1 tests on Summit.

I'll update this comment when I get results from Chrysalis.

**Comment by ambrad** [comment]
Partly addresses SCREAM issue [#1917](https://github.com/E3SM-Project/scream/issues/1917)

**Review by bartgol — APPROVED** [review]

**Comment by ambrad** [comment]
Status: Waiting on some work on ascent to see if anything more is needed in the dycore.

**Comment by ambrad** [comment]
The missing single doesn't affect determinism on the GPU. I also found that it doesn't change answers in a SCREAM ne30pg2_ne30pg2.SCREAMv1 run. But it definitely should be fixed.

I've included an unrelated extra commit that fixes a correctness test.

I'm rerunning testing on Chrysalis now, after which I'll be ready to merge this branch.

**Pull request merged**
