### PR TITLE
Adjust Bebop's pelayouts

### PR DESCRIPTION
**Pull request by amametjanov**
Adjust Bebop's pelayouts :
* Run MALI and WCYCL compsets with larger and better pelayouts
* Add MPI task ID label
* Run with NetCDF for some tests

[BFB]

### CODE REVIEW

**Comment by amametjanov** [comment]
These 2 integration tests need to be addressed separately (known reprosum errors with IntelMPI):
```
azamat@beboplogin4:cdash-tests3$ ./cs.status.20180606_171603_gd9yi8 | grep -i "overall: " | wc -l
48
azamat@beboplogin4:cdash-tests3$ ./cs.status.20180606_171603_gd9yi8 | grep -i "overall: pass" | wc -l
46
azamat@beboplogin4:cdash-tests3$ ./cs.status.20180606_171603_gd9yi8 | grep -i "overall: pend" | wc -l
2
azamat@beboplogin4:cdash-tests3$ ./cs.status.20180606_171603_gd9yi8 | grep -i "overall: pend"
  ERP_Ld3.ne30_oECv3_ICG.A_WCYCL1850S.bebop_intel (Overall: PEND) details:
  PEM_Ln9.ne30_oECv3_ICG.A_WCYCL1850S.bebop_intel (Overall: PEND) details:
```

**Comment by worleyph** [comment]
@amametjanov , are these known Intel MPI issues related to what @ndkeen (and I) have seen on Cori-KNL (#2302). Both Noel and I tested on Bebop and did not see anything with the our reproducers. Is this an issue in reprosum, or simply a NaN that is caught in the test at the beginning?

**Comment by amametjanov** [comment]
They are probably related: both occur at step 3 in atm.log:
```
/lcrc/group/acme/azamat/acme_scratch/bebop/cdash-tests3/ERP_Ld3.ne30_oECv3_ICG.A_WCYCL1850S.bebop_intel.20180606_171603_gd9yi8/run
/lcrc/group/acme/azamat/acme_scratch/bebop/cdash-tests3/PEM_Ln9.ne30_oECv3_ICG.A_WCYCL1850S.bebop_intel.20180606_171603_gd9yi8/run
```
The same cases on Anvil, which runs with mvapich, finish OK.

**Comment by worleyph** [comment]
The failure that I was seeing was during initialization. At first glance, this is different than the failure I was seeing. However, this may be related to what Noel was seeing? I assumed that @ndkeen and I were chasing the same bug, but perhaps not? Again, my reproducer did not have problems on Bebop, and neither did Noel's. Weird.

**Comment by rljacob** [comment]
Bebop is also the only intel compiler that has a problem with FATES.  Something about its particular version (17.0.4)?

**Comment by amametjanov** [comment]
FATES fails during CLM history write: doesn't appear to be related to intel17.

**Pull request merged**
