### PR TITLE
Updates PGI compiler to version 19.10

### PR DESCRIPTION
**Pull request by singhbalwinder**
Updates PGI compiler to version 19.10

Addresses E3SM-Project/E3SM#3337

[BFB] - Bit-For-Bit

### CODE REVIEW

**Comment by worleyph** [comment]
@singhbalwinder , I just now tried to build a case:

     -res ne30_ne30 -compset FC5AV1C-L -mach compy -compiler pgi -project e3sm

with a 2700x1 PE layout. The build failed with

     *** Error in `/qfs/projects/ops/rh7/apps/pgi/19.7/linux86-64-llvm/19.7/bin/pgf901-llvm': corrupted size vs. prev_size: 0x0000000002361228 ***

Your commit is clearly acceptable, and I will approve it if you want me to, unless you want to wait until builds and runs actually work. (At the moment this is a degradation compared to the existing version of PGI pointed at by master.)

**Comment by worleyph** [comment]
Interestingly enough, a compile using a 1350x2 decomposition completed successfully.

**Comment by worleyph** [comment]
I did a clean-all and tried building the 2700x1 PE case again, and got the same failure.

**Comment by worleyph** [comment]
And a 

     -compset A_WCYCL1950S_CMIP6_LR -res ne30_oECv3_ICG -mach compy -compiler pgi

with an MPI-only PE layout (1350x1 for ATM) built without any error messages.

**Comment by worleyph** [comment]
Note that the failed 2700x1 build has these "details":

     gmake[2]: *** [cmake/lnd/CMakeFiles/lnd.dir/__/__/clm/src/external_models/emi/src/emi/ExternalModelInterfaceMod.F90.o] Error 127
     ...
     gmake[1]: *** [cmake/lnd/CMakeFiles/lnd.dir/all] Error 2
     gmake[1]: *** Waiting for unfinished jobs....
     ...
     gmake: *** [all] Error 2

The LND build for this PE layout uses 

             <value compclass="LND">640</value>

**Comment by rljacob** [comment]
This is supposed to be the same compiler version as on Summit.  Does Summit have the same build errors for those layouts?

**Comment by rljacob** [comment]
tagging @minxu74

**Comment by mrnorman** [comment]
What file does the build fail on?

**Comment by worleyph** [comment]
@mrnorman , it appears to be

     clm/src/external_models/emi/src/emi/ExternalModelInterfaceMod.F90

**Comment by rljacob** [comment]
Maybe we should downgrade the compiler to 19.4.  That is what is used on Summit.

**Comment by amametjanov** [comment]
Last two commits are workarounds to get `e3sm_integration` tests building and running with reproducible answers.

**Comment by singhbalwinder** [comment]
pushed to next

**Pull request merged**
