### PR TITLE
Modified parameters for miscanthus and switchgrass

### LINKED ISSUE #4608: An extra 'end if' introduced in commit 07ff719
components/elm/src/cpl/lnd_import_export.F90, Line 754. That 'end if' would cause compiling failure when -DCPL_BYPASS.

### PR DESCRIPTION
**Pull request by evasinha**
Modified parameters for miscanthus and switchgrass based on calibration 
and validation finalized for revised manuscript submitted in GMD https://gmd.copernicus.org/preprints/gmd-2021-244/
Minor edits in estimation of perennial crop harvest.

[nonBFB]  for crop tests.
Fixes #4608

### CODE REVIEW

**Comment by rljacob** [comment]
Is this needed for BGC runs?

**Comment by evasinha** [comment]
@rljacob No, it is not needed for BGC v2 simulation.

**Comment by evasinha** [comment]
@jenniferholm - Is it possible to get this PR approved and merged soon? The deadline for resubmitting my manuscript revision is approaching soon and I am hoping to share a Zenodo link of the repo with the bioenergy updates merged into ELMv2.

**Comment by peterdschwartz** [comment]
Looks like this PR contains the fix for Issue #4608 so I will add that to the description.

**Review by jenniferholm — APPROVED** [review]
This all looks good to me and getting in all the correct parameter updates. Good luck with the manuscript revisions.

**Comment by peterdschwartz** [comment]
merged to next

**Comment by evasinha** [comment]
Thank you @jenniferholm for approving the changes and @peterdschwartz for merging the commit.

**Pull request merged**
