### PR TITLE
Adds a SMS land test for a BGC compset

### PR DESCRIPTION
**Pull request by bishtgautam**
An integration test is added for BGCEXP_BCRC_CNPECACNT_1850 compset

[NML]

### CODE REVIEW

**Comment by jqyin** [comment]
@bishtgautam  It probably doesn't matter, but is it intended to change the length for FC5AV1C-L test in the PR as well?

**Comment by bishtgautam** [comment]
@jqyin, I didn't intend to change the simulation length of conusx4v1_conusx4v1.FC5AV1C-L. I will make a new commit.

**Comment by rljacob** [comment]
Good catch, @jqyin

**Comment by jqyin** [comment]
Merged #2433

**Pull request merged**
