### PR TITLE
Adding compset for JRA55 v1.4 through 2018.

### PR DESCRIPTION
**Pull request by darincomeau**
This PR adds support for the JRA55v1.4 forcing dataset through year 2018 by adding the GMPAS-JRA1p4 compset.

[BFB]

### CODE REVIEW

**Comment by darincomeau** [comment]
I've built a GMPAS-JRA1p4.TL319_oEC60to30v3 to run a 5 day test, currently in the queue. The run directory's datm/drof streams files are pointing to the intended files (with the correct 190528 datestamp for datm files). Note only the drof files changed from v1.3 to v1.4, so the datm files still have the v1.3 tag. Here are the last file from each data streams file:

JRA.v1.3.prec.TL319.2018.190528.nc
JRA.v1.3.lwdn.TL319.2018.190528.nc
JRA.v1.3.swdn.TL319.2018.190528.nc
JRA.v1.3.q_10.TL319.2018.190528.nc
JRA.v1.3.slp.TL319.2018.190528.nc
JRA.v1.3.t_10.TL319.2018.190528.nc
JRA.v1.3.u_10.TL319.2018.190528.nc
JRA.v1.3.v_10.TL319.2018.190528.nc
JRA.v1.4.runoff.2018.190214.nc

**Comment by darincomeau** [comment]
GMPAS-JRA1p4.TL319_oEC60to30v3 5 day test completed successfully.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
