### PR TITLE
Adds wsubmin namelist parameter to gustiness use case

### PR DESCRIPTION
**Pull request by singhbalwinder**
Vince Larson made us aware that gustiness parameterization is missing
wsubmin in the use case file. This PR fixes that. It also changes
the test mod directory to add a shell command to use the use case file
for the gustiness test rather than mentioning namelist parameters
explicitly.

[Non-BFB] - Non Bit-For-Bit
[NML] - Namelist Changing

See confluence for a more detailed description about these tags.

### CODE REVIEW

**Comment by wlin7** [comment]
@singhbalwinder , is it true that only the gustiness parameterization test currently uses this use_case file? I don't see an existing compset using it.

**Comment by singhbalwinder** [comment]
Yes, it is only the gustiness test which uses this compset. Only that test is expected to fail.

**Comment by rljacob** [comment]
@wlin7 what is the status of this PR?

**Comment by wlin7** [comment]
Merged to next. Expect cam-gust_param tests to diff.

**Comment by wlin7** [comment]
Merged to master. 

Request to bless ERS_Ld5.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.cam-gust_param.
compy's cam-gust_param test has been failing before this PR. Still need to be bless after the pre-existing issue is resolved.

**Pull request merged**
