### PR TITLE
Switch on high-frequency coupling in sea ice at 10 iterations

### PR DESCRIPTION
**Pull request by proteanplanet**
This PR is part of a final set of changes to E3SM Version 2 polar changes, and matches a PR from MPAS-SeaIce recently accepted into E3SM Master. It switches on high-frequency coupling in MPAS-SeaIce with an increased number of iterations.

[non-BFB]

### CODE REVIEW

**Review by akturner — APPROVED** [review]

**Review by njeffery — APPROVED** [review]
Verified this by building and running a short (6-day) GCASE.  Small changes observed in ice volume.

**Comment by rljacob** [comment]
Any impact on performance?

**Comment by njeffery** [comment]
GCASE with #3984 and #3983 ran 4.829  sim years/cm-day. master ran 4.778 sim yrs/cm-day

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master and expected DIFFs blessed

**Pull request merged**
