### PR TITLE
Final v2 AMIP theta-SL-pg2 configuration

### PR DESCRIPTION
**Pull request by ambrad**
This PR's primary purpose is to finalize the v2 theta-SL-pg2 configuration.

1. Add a drydep_srf_file XML entry for ne30pg2.
2. Switch the default CEDR algorithm.
3. Fix a consistent but incorrect use of Exner pressure in the physgrid remap algorithms. Consistency meant the bug did not affect climatology, but of course we must fix it. The change is non-BFB.

The combination of the default CEDR algorithm change and this bug fix make this PR non-BFB.

[NBFB] for 3 E3SM pg2 tests

### CODE REVIEW

**Comment by ambrad** [comment]
This branch was used in the r7 runs documented [here](https://acme-climate.atlassian.net/wiki/spaces/COM/pages/1112047753/Physgrid+v2+integration+ne30pg2+r05+oECv3).

**Comment by ambrad** [comment]
HOMME tests pass with the exception of these two expected fails, with normalized diffs having expected magnitudes:
```
The following tests FAILED:
   21 - thetah-sl-test11conv-r1t2-cdr20 (Failed)
   22 - thetah-sl-test11conv-r0t1-cdr30-rrm (Failed)
```

**Comment by ambrad** [comment]
I'm running e3sm_developer overnight and will inspect the expected diff and report here tomorrow.

**Comment by AaronDonahue** [comment]
@ambrad , can you comment on how the changes you've made here relate to the issue that @PeterCaldwell  and I raised awhile back, https://github.com/E3SM-Project/E3SM/issues/2680?

**Comment by AaronDonahue** [comment]
> @ambrad , can you comment on how the changes you've made here relate to the issue that @PeterCaldwell and I raised awhile back, #2680?

Looking one more time I don't think they are directly related because all of your "exner" changes seem contained to just HOMME specific variables.  Although, the fact that you had to fix the definition of exner in HOMME brings back up the point that the state%exner variable in the ATM component isn't correctly defined.

**Comment by ambrad** [comment]
@AaronDonahue, I think there is no relation. This bug fix is localized to the physgrid remap routine and so is relevant only to np4pg2 coupling.

The remap routines intend to conserve potential temperature when remapping T and FT, but instead they were conserving a meaningless quantity. I fix that in this PR.

In the future, I might work out something more complicated for the theta dycore that conserves theta_v rather than theta. For now, I'm sticking with theta, as I haven't observed any effect of details of T remap -- T directly, theta, or incorrect theta -- in time snapshots of DCMIP tests or F-compset climatologies.

**Comment by PeterCaldwell** [comment]
Ok, thanks Andrew!

**Comment by ambrad** [comment]
e3sm_developer completed with:
```
Test 'SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.sandiatoss3_intel' finished with status 'DIFF'
Test 'SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.sandiatoss3_intel.cam-thetahy_pg2' finished with status 'DIFF'
Test 'SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.sandiatoss3_intel.cam-thetahy_sl_pg2' finished with status 'DIFF'
```
I forgot there were three pg2 tests now, not one.

**Comment by oksanaguba** [comment]
in next

**Pull request merged**
