### PR TITLE
Fix for cime's configure tool

### PR DESCRIPTION
**Pull request by jgfouca**
Needed comp_interface.

[BFB]

### CODE REVIEW

**Comment by jgfouca** [comment]
@brhillman , please try this branch.

**Comment by brhillman** [comment]
Perfect, that fixed it. Thanks!

**Comment by jgfouca** [comment]
Skipping integration testing since the changed code could have been being used by anyone since it didn't work.

**Comment by brhillman** [comment]
@jgfouca thanks for the quick fix on this!

**Comment by rljacob** [comment]
What was the problem?

**Comment by jgfouca** [comment]
@rljacob , the API to configure (cime/scripts/lib/CIME/BuildTools/configure.py) changed and this particular user of that API did not get updated. I guess this script is not commonly used.

**Comment by brhillman** [comment]
@jgfouca @rljacob it would be good to have a test for this so that it doesn't break in the future. This is the kind of stuff I end up having to deal with whenever I go back and need to generate a new atmosphere grid that ends up taking so long.

**Comment by rljacob** [comment]
Can one of you make an issue for the record?

**Comment by jgfouca** [comment]
Yes, a test would be good. I'll make an issue over on ESMCI.

**Pull request merged**
