### PR TITLE
Hommexx: Work around a Cuda issue on Perlmutter GPU.

### PR DESCRIPTION
**Pull request by ambrad**
After an upstream merge to SCREAM, we encountered issue https://github.com/E3SM-Project/scream/issues/2146. Some perturbation to the code made something on the Cuda side exhibit a bug related to extended lambdas. This commit works around the bug by moving the code to a functor to avoid the lambda part of the call stack. To be clear, we have a bunch of lambdas; it's just this one that is a problem.

Also remove an unused register_field overload.

[BFB]

### CODE REVIEW

**Comment by ambrad** [comment]
Ran e3sm_scream_v1 and e3sm_scream_v1_long on pm-gpu with this PR merged into the SCREAM repo. Ran ERS.ne4_oQU240.F2010.chrysalis_intel.eam-hommexx, eam_theta_pg2, and homme_integration on Chrysalis.

**Review by bartgol — APPROVED** [review]

**Comment by ambrad** [comment]
e3sm_developer passes on Chrysalis. homme_integration diffs due to PR 5229, as
expected, when tested with this PR on top of current next; otherwise,
homme_integration passes. e3sm_scream_v1 and e3sm_scream_v1_long on pm-gpu pass
with this PR merged into the SCREAM repo.

**Comment by oksanaguba** [comment]
@ambrad homme test diffs on chrysalis, i guess it is from this PR. maybe something went wrong with blessing? i do not see anything else around the time that tests started failing https://my.cdash.org/test/73207094?graph=status .

**Comment by ambrad** [comment]
@oksanaguba no the diffs are from https://github.com/E3SM-Project/E3SM/pull/5229

**Pull request merged**
