### PR TITLE
Additions to ice shelf pressure and test case

### PR DESCRIPTION
**Pull request by mark-petersen**
This PR only changes MPAS-Ocean stand-alone cases with ice shelf cavities. See full description at https://github.com/MPAS-Dev/MPAS-Model/pull/282.

There are new namelist options in the `time_varying_forcing` record, but we ignore that whole namelist record in E3SM, so no E3SM namelist changes are needed.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
Passes these tests:
```
PASS PEM_Ln9.ne30_oECv3wLI.A_WCYCL1850-DIB-ISMF_CMIP6.cori-knl_intel COMPARE_base_modpes
PASS PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_intel COMPARE_base_single_thread
```

**Comment by mark-petersen** [comment]
Rebased. @jonbob this is ready to go when you (and the repo) are.

**Comment by jonbob** [comment]
Merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
