### PR TITLE
Fixes two F2010-CICE tests

### LINKED ISSUE #5292: Setup errors for `twpx4v1_twpx4v1/enax4v1_enax4v1` tests
These two tests in e3sm_extra_coverage have been failing for a long time (on all machines where this suite is run). Can we remove them from the tests?

```
SMS_D_Ln5.twpx4v1_twpx4v1.F2010-CICE
SMS_D_Ln5.enax4v1_enax4v1.F2010-CICE
```

```
Finished SETUP for test SMS_D_Ln5.twpx4v1_twpx4v1.F2010-CICE.cori-knl_intel in 6.487345 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/mfMCS/SMS_D_Ln5.twpx4v1_twpx4v1.F2010-CICE.cori-knl_intel.20221111_094045_tyfest
    Errors were:
        ERROR: Command: '/global/cfs/cdirs/e3sm/ndk/repos/ndk_machinefiles_PM-add-MPICH_COLL_SYNC-MPI_Bcast/components/elm/bld/build-namelist -infile /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/mfMCS/SMS_D_Ln5.twpx4v1_twpx4v1.F2010-CICE.cori-knl_intel.20221111_094045_tyfest/Buildconf/elmconf/namelist  -csmdata /global/cfs/cdirs/e3sm/inputdata -inputdata /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/mfMCS/SMS_D_Ln5.twpx4v1_twpx4v1.F2010-CICE.cori-knl_intel.20221111_094045_tyfest/Buildconf/elm.input_data_list -ignore_ic_year -namelist " &elm_inparm  start_ymd=00010101  /" -use_case 2010_CMIP6_control  -res ne0np4_twpx4v1  -clm_start_type default -envxml_dir /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/mfMCS/SMS_D_Ln5.twpx4v1_twpx4v1.F2010-CICE.cori-knl_intel.20221111_094045_tyfest -l_ncpl 96 -r_ncpl 96 -lnd_frac /global/cfs/cdirs/e3sm/inputdata/share/domains/domain.lnd.twpx4v1_oRRS18to6v3.170629.nc -glc_nec 0 -co2_ppmv 388.717 -co2_type diagnostic  -ncpl_base_period day  -config /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/mfMCS/SMS_D_Ln5.twpx4v1_twpx4v1.F2010-CICE.cori-knl_intel.20221111_094045_tyfest/Buildconf/elmconf/config_cache.xml -bgc sp -mask oRRS18to6v3' failed with error 'File::Glob::glob() will disappear in perl 5.30. Use File::Glob::bsd_glob() instead. at /global/cfs/cdirs/e3sm/ndk/repos/ndk_machinefiles_PM-add-MPICH_COLL_SYNC-MPI_Bcast/components/elm/bld/ELMBuildNamelist.pm line 3553.
        ERROR : CLM build-namelist::ELMBuildNamelist::add_default() : No default value found for fsurdat.
                    Are defaults provided for this resolution and land mask?' from dir '/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/mfMCS/SMS_D_Ln5.twpx4v1_twpx4v1.F2010-CICE.cori-knl_intel.20221111_094045_tyfest/Buildconf/elmconf'
```

### PR DESCRIPTION
**Pull request by bishtgautam**
Adds default ELM surface datasets for the following two resolutions:
- ne0np4_enax4v1
- ne0np4_twpx4v1

Fixes #5292
[BFB]

### CODE REVIEW

**Comment by bishtgautam** [comment]
@ndkeen I only ran `./create_test <....> --no-build` and both tests passed the setup, but I didn't run the tests.

@wlin7 I used the ELM surface dataset corresponding to 2000 for these F2010 compsets, as I could not find a 2010 surface dataset on the E3SM inputdata server. Since these resolutions are for testing and will not be used for any production runs, I think using the 2000 surface dataset should be okay.

**Comment by rljacob** [comment]
There's a PR to remove those tests:  https://github.com/E3SM-Project/E3SM/pull/5505   Should we keep them?

**Comment by rljacob** [comment]
After thinking some more, we should continue to remove these tests unless you feel strongly you should keep them @bishtgautam .  I think those tests were added just to get some RRM coverage when that capability was new.  Now we have a production RRM config and test it in the prod suite.  Unless there's a reason to test these specific configs, we should drop them.

**Review by ndkeen — APPROVED** [review]
Tested e3sm_extra_coverage on pm-cpu, which includes the 2 affected tests and they pass.

**Comment by bishtgautam** [comment]
I'm okay if these tests are removed. I issued this PR because @ndkeen asked me to help fix these failing tests.

**Comment by rljacob** [comment]
Go ahead and merge this.  If someone does want to run those configs, they will work.

**Review by wlin7 — APPROVED** [review]
Changes look good. Ok to use simyr2000 surfdata for F2010 for testing purpose.

**Pull request merged**
