### PR TITLE
Hommexx: Limit HIP team size in debug builds.

### PR DESCRIPTION
**Pull request by ambrad**
Also clean up the team_num_threads_vectors routine to consolidate the rules.

Fixes SCREAM issue 2058.

[BFB]

### CODE REVIEW

**Comment by ambrad** [comment]
With this PR in SCREAM, the following tests pass on Crusher:
* SMS_D_Ln5.ne4pg2_ne4pg2.F2010-SCREAMv1 (previously failed)
* PEM_Ln300.ne30pg2_ne30pg2.F2010-SCREAMv1 (check non-debug build)

**Comment by ambrad** [comment]
I verified on Ascent that this PR doesn't affect the team size in an opt run, as expected.

**Review by bartgol — APPROVED** [review]

**Comment by ambrad** [comment]
e3sm_developer and homme_integration pass on Chrysalis.

**Comment by ambrad** [comment]
In `next`.

**Pull request merged**
