### PR TITLE
fixes bugs in the calculation of two land diagnostic variables

### PR DESCRIPTION
**Pull request by xyk-ornl**
Two diagnostic variables SEN_NLOSS_LITTER and SEN_PLOSS_LITTER are NaN from current ELM runs due to bugs in the calculation. This commit fixes those bugs.

This commit also converts the format of two files in ELM from dos to unix.

### CODE REVIEW

**Comment by xyk-ornl** [comment]
@susburrows @kvcalvin We also need this fix for our CBGC future runs. Should we merge the bug fixes for the two variables into the Main v1.1 branch? Thanks

**Comment by rljacob** [comment]
You can't merge master to maint.  If you want these in maint-1.1, you have to make a new branch off of maint-1.1 and implement them there.

In what sense were these "converted from dos to unix"?

**Comment by xyk-ornl** [comment]
@rljacob these two files are in dos format - all the lines end with ^M. You don't see that when you vi the file but you will see that if you modify the file and then git diff. Converting dos to unix removes  all ^M in the files. Thanks

**Comment by xyk-ornl** [comment]
@rljacob  sure I will submit a separate PR for maint for this. Thanks,

**Comment by rljacob** [comment]
Doing the conversion along with the bug fix makes it impossible to tell which changes are for the bug fix.  Do 2 PRs, one for the conversion, one for the bug fix.

**Comment by xyk-ornl** [comment]
@rljacob will do. Thanks

**Comment by xyk-ornl** [comment]
Two separate PRs were submitted to replace this PR. I am closing this one.

**Pull request closed without merging**
