### PR TITLE
Refactor of Single-column implementation in HOMME (plus bug fix)

### PR DESCRIPTION
**Pull request by bogensch**
Refactor of the implementation of the single-column model (SCM) in the HOMME directory.  Refactored code avoids calling prim_step when SCM is activated and instead calls a new subroutine "prim_step_scm" which updates the floating levels based on the prescribed large-scale vertical velocity.  

Also in this PR is a bug fix in scamMod.F90 where the the IOP longitude is converted from (-180 to 180) to (0 to 360) AFTER this value is read in, rather than before.  This will be an answer changing bug fix for some SCM cases, but for the test case in the e3sm_developer tests (ARM97, for Eulerian dynamical core), it is not answer changing.  

Testing:
All e3sm_developer tests pass.  

NOTE:  Spectral element version of SCM is still in testing mode.  The Eulerian dy-core version of SCM is still the default scientifically supported version of SCM.

### CODE REVIEW

**Comment by oksanaguba** [comment]
This commit passes skybridge standalone homme tests against commit LAST_GIT_COMMIT_SHA:STRING=7c99844d3326d0a70b8122d18b3d7735e471f5f0 .

**Comment by oksanaguba** [comment]
@bogensch , are there SC tests in e3sm? If not, then this is bfb, correct? If yes, then could you decide whether this is supposed to be bfb? If there is a SC test, would you please indicate which one?

**Comment by bogensch** [comment]
Yes, SMS_R_Ld5.T42_T42.FSCM5A97 is the SCM test and should be b4b (was for me).

**Comment by oksanaguba** [comment]
I ran one random test with this branch
`${which}/cime/scripts/create_test -c -b master ERP_Ln9.ne4_ne4.FC5AV1C-L`
and got this fail
`FAIL ERP_Ln9.ne4_ne4.FC5AV1C-L.sandiatoss3_intel NLCOMP` .
It seems unlikely that this PR caused some nl difference, so, I locally merged master and got all passes. I did not try to run SCM test from here.

**Comment by wlin7** [comment]
Merged to next.

**Comment by wlin7** [comment]
Merged.

**Pull request merged**
