### PR TITLE
Added prescribed ice mode to MPAS-Seaice component

### PR DESCRIPTION
**Pull request by akturner**
Added a prescribed ice mode to MPAS-Seaice, where a climatology sets the ice concentration and extent and ice thickness is set. Dynamics is off, thermodynamics is on.

[NML]
[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
@akturner - config_use_prescribed_ice isn't in Registry?

**Comment by vanroekel** [comment]
@jonbob this seems to have a bunch of changes to the ocean code to related to GM.  Is this expected?

@akturner does the base functionality of this remain the same with the results you showed previously on confluence?

**Comment by jonbob** [comment]
@vanroekel - I saw that as well, but I think the PR was made before the last set of ocean changes. When I compare mpas-source to the hash that's currently on master, all the ocean diffs disappear and there's only the seaice Registry

**Comment by akturner** [comment]
@jonbob @vanroekel I think this is related to the previous reversion of the merge of seaice/develop into e3sm/develop

**Comment by jonbob** [comment]
@akturner - I don't believe there's any problem with the previous reversion. The mpas-source hash just changed in between when you made this PR and now. Once I updated the hash to the one used for current master, everything was fine.

**Comment by akturner** [comment]
@jonbob Hopefully the previous issues are fixed

**Comment by jonbob** [comment]
passed SMS.ne4_oQU480.FC5AV1C-L-MPASSI.anvil_intel

**Comment by jonbob** [comment]
failing SMS_D.ne30_oECv3.F2010SC5-CMIP6-MPASSI.anvil_intel with the following traceback:
 ````
672: forrtl: severe (408): fort: (3): Subscript #1 of the array CATEGORYTHICKNESSLIMITS has value 0 which is less than the lower bound of 1
 672:
 672: Image              PC                Routine            Line        Source
 672: e3sm.exe           000000000C7F6DB6  Unknown               Unknown  Unknown
 672: e3sm.exe           0000000008A4B233  seaice_prescribed         280  mpas_seaice_prescribed.f90
 672: e3sm.exe           000000000868B370  seaice_time_integ         138  mpas_seaice_time_integration.f90
 672: e3sm.exe           0000000008638165  ice_comp_mct_mp_i        1080  ice_comp_mct.f90
 672: e3sm.exe           000000000047101B  component_mod_mp_         737  component_mod.F90
 672: e3sm.exe           000000000043BBE3  cime_comp_mod_mp_        2614  cime_comp_mod.F90
 672: e3sm.exe           00000000004591A4  MAIN__                    133  cime_driver.F90

**Comment by jonbob** [comment]
@akturner - can you think of a reason for the history files to come on for this test?
````
-rw-rw----+ 1 ac.jwolfe cels 204588428 Oct 14 18:08 mpassi.hist.0001-01-01_00000.nc

**Comment by jonbob** [comment]
@akturner - I think the bit of code that's giving us trouble is this:
````
                do iCategory = 1, nCategories

                   ! find relevant thickness category
                   if (iceThickness <  categoryThicknessLimits(iCategory) .and. & !!!! index limits
                       iceThickness >= categoryThicknessLimits(iCategory-1)) then
````
When iCategory is 1, the logic is looking at categoryThicknessLimits(0)?

**Comment by jonbob** [comment]
I see that ice has something similar, but I think the arrays are dimensioned 0:ncat

**Comment by akturner** [comment]
@jon: This should fix the bug with the category thickness limits

**Comment by jonbob** [comment]
@akturner - I merged the latest version of the code and got past the previous sticking point but now see this traceback for the a SMS_D.ne30_oECv3.F2010SC5-CMIP6-MPASSI.compy_intel test failure:
````
 33: forrtl: severe (408): fort: (2): Subscript #1 of the array SNOWENTHALPY has value 8 which is greater than the upper bound of 5
 33:
 33: Image              PC                Routine            Line        Source
 33: e3sm.exe           000000000AFF0B76  Unknown               Unknown  Unknown
 33: e3sm.exe           0000000008E48B9E  seaice_prescribed         314  mpas_seaice_prescribed.f90
 33: e3sm.exe           0000000008A44880  seaice_time_integ         138  mpas_seaice_time_integration.f90
 33: e3sm.exe           00000000089EFB8F  ice_comp_mct_mp_i        1080  ice_comp_mct.f90
 33: e3sm.exe           000000000047B3CA  component_mod_mp_         737  component_mod.F90
 33: e3sm.exe           0000000000441831  cime_comp_mod_mp_        2614  cime_comp_mod.F90
 33: e3sm.exe           0000000000462ABB  MAIN__                    133  cime_driver.F90
````

**Comment by jonbob** [comment]
@akturner - I changed this line in the mpas-source submodule and the test is now running:
````
diff --git a/src/core_seaice/shared/mpas_seaice_prescribed.F b/src/core_seaice/shared/mpas_seaice_prescribed.F
index 2e990aa..fe6c16d 100644
--- a/src/core_seaice/shared/mpas_seaice_prescribed.F
+++ b/src/core_seaice/shared/mpas_seaice_prescribed.F
@@ -300,7 +300,7 @@ contains
 
                          ! snow quantities
                          do iSnowLayer = 1, nSnowLayers
-                            snowEnthalpy(iIceLayer,iCategory,iCell) = colpkg_enthalpy_snow(surfaceTemperature(1,iCatego
+                            snowEnthalpy(iSnowLayer,iCategory,iCell) = colpkg_enthalpy_snow(surfaceTemperature(1,iCateg
                          enddo ! iSnowLayer
 
                       endif
````

**Comment by jonbob** [comment]
Now passes SMS_D.ne30_oECv3.F2010SC5-CMIP6-MPASSI.anvil_intel

**Comment by jonbob** [comment]
@proteanplanet, @vanroekel - I believe this is now ready to be merged, if you can add your reviews

**Comment by jonbob** [comment]
Also passed SMS.ne30_oECv3.F2010SC5-CMIP6-MPASSI.anvil_intel and the seaice ran at over 50 sypd on a 144-pe layout and accounted for just over a percent of the run cost

**Comment by jonbob** [comment]
For comparison, the equivalent test with CICE had it running at ~370 sypd - but the total system difference in throughput was small:
SMS.ne30_oECv3.F2010SC5-CMIP6.anvil_intel - 0.65 sypd
SMS.ne30_oECv3.F2010SC5-CMIP6-MPASSI.anvil_intel - 0.64 sypd

**Review by vanroekel — APPROVED** [review]
approved based on visual inspection and testing by @jonbob

**Comment by vanroekel** [comment]
@rljacob this is approved for integration for WC v2 once @proteanplanet approves the PR

**Review by proteanplanet — APPROVED** [review]
I visually reviewed this, and can't find any problems.  Approved.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master and expected NML DIFFs blessed

**Comment by rljacob** [comment]
Why did this cause diffs in a fully coupled case or any case with fully active sea ice?  I thought this only changed an F-case and only if it was using this "new" model.

**Comment by jonbob** [comment]
Just NML DIFFs -- it did have to add a new namelist variable to turn it on

**Comment by rljacob** [comment]
oh ok.

**Pull request merged**
