### PR TITLE
Update CIME to ESMCI cime5.8.7-2

### PR DESCRIPTION
**Pull request by jgfouca**
Update CIME to ESMCI cime5.8.7-2

Squash merge of jgfouca/branch-for-to-acme-2019-08-14

Features:
* Update to latest NCAR PIO2 version
* improve the config_compilers.xml schema to catch case errors

Bug fixes:
* make sure output_root path is abspath
* make sure  ~/.cime/config_compilers.xml file is also checked against schema
* fix indentation bug in get_timing

[BFB]

### CODE REVIEW

**Comment by jgfouca** [comment]
Squash merged to next.

**Comment by sarats** [comment]
@jgfouca Does this change timing file outputs? I need to keep track for importing data into [PACE](https://pace.ornl.gov)

**Comment by jgfouca** [comment]
@sarats , it fixes this bug:
https://github.com/ESMCI/cime/issues/3204

**Comment by worleyph** [comment]
@jgfouca , what caused this bug? Any idea?

**Comment by jgfouca** [comment]
@worleyph , no idea off the top of my head.

```
git log -p get_timing.py
```
^ may reveal the answer.

**Comment by sarats** [comment]
@worleyph Looks like bug was introduced in https://github.com/ESMCI/cime/commit/773e6297245bd9cd9d0691cae111e97d75fc0147
and Az pointed out the problem.

**Comment by worleyph** [comment]
@sarats and @jgfouca , thanks.

**Pull request merged**
