### PR TITLE
Test script for Phase 3 sea ice/polar climate using E3SM infrastructure

### PR DESCRIPTION
**Pull request by proteanplanet**
The first script for testing and developing the sea ice model within the E3SM framework instead of through stand-alone MPAS-SI testing infrastructure.  This script addresses requirements of the Phase 2 code review, including: 1) testing namelist combinations to avoid dysfunctional stealth features entering the coupled code base; 2) adding energy and mass conservation testing that had previously been missing from E3SM coupled polar testing; 3) providing a quick tool for developers to demonstrate their work passes standard E3SM tests on at least two machines (e.g. PEM, ERS) in advance of submitting pull requests. Version 1 of the script provided here establishes basic functionality for ongoing sea ice developments currently underway, Version 2 is planned to refine that functionality in a separate PR as mentioned in the help file for this script.

### CODE REVIEW

**Comment by proteanplanet** [comment]
@erinethomas You must start by cloning from a fork and branch on github, which orders your code in ~/E3SM-Polar/code in an analogous way to E3SM runscripts, just in a different directory.  You only need to clone your code once, and then you can make as many changes to ~/E3SM-Polar/code/<sandbox> as desired without needing to commit and push changes nor clone your code and switch to your branch again.   This follows the same procedure as in standard E3SM runscripts, and is done to deliberately facilitate provenance and clean tracing of what you are testing.  If we set up the script to run on any old sandbox in any old location, their is a danger that changes you did not know you were testing creep into your workflow, and into PRs.

**Comment by njeffery** [comment]
@proteanplanet : I ran a short test on chrysalis with the defaults and -e.  worked really smoothly.  One thing I noticed though is that the 3-month default run with -e option has monthly conservation output.  Is there a way to edit the streams within the script, or should that be down in the case run directory?

**Comment by proteanplanet** [comment]
> @proteanplanet : I ran a short test on chrysalis with the defaults and -e. worked really smoothly. One thing I noticed though is that the 3-month default run with -e option has monthly conservation output. Is there a way to edit the streams within the script, or should that be down in the case run directory?

@njeffery To my knowledge this is the standard conservation output.  Are you wanting just one 3-month average, or something different?  I have always used the monthly data, because it matches CPL monthly output in the log files.

**Comment by njeffery** [comment]
@proteanplanet : For short runs I often use daily output.  It's not critical for this PR.

**Review by njeffery — APPROVED** [review]
Looks good!

**Comment by rljacob** [comment]
Waiting on review/approval from @eclare108213 @erinethomas

**Review by erinethomas — APPROVED** [review]

**Comment by proteanplanet** [comment]
@rljacob I would like  place this on hold for a few weeks. We're incorporating features originally intended for a version 2 right now.  We have a working version under SimulationScripts, and have been asked to present the final version at an all-hands meeting.

**Comment by darincomeau** [comment]
@proteanplanet this PR came up in this morning's mpas-devops call, that maybe it would be better suited to be in https://github.com/E3SM-Seaice-Discussion/E3SM until it's ready to be merged.

**Comment by proteanplanet** [comment]
@darincomeau Maybe I'm misunderstanding the point of a draft PR?

**Comment by darincomeau** [comment]
We use the [ocean](https://github.com/E3SM-Ocean-Discussion/E3SM) and [sea ice](https://github.com/E3SM-Seaice-Discussion/E3SM) Discussion repos for draft or work-in-progress PRs that are likely to be open for some time before being ready, to keep them out of the way as open PRs here in the main repo.

**Comment by proteanplanet** [comment]
I would prefer to keep this as a draft - it was originally ready to go as version 1, but due to developments elsewhere in E3SM (not in ice or polar), a decision was made to include version 2 developments in this PR, which are weeks away at the most. Switching to a discussion session is just creating more administration.

**Comment by rljacob** [comment]
@proteanplanet PRs opened here should be ready to merge.  If its not, move it to the discussion repos.

**Pull request closed without merging**
