### PR TITLE
Update MPAS-Ocean to GPU-optimized EOS

### PR DESCRIPTION
**Pull request by mark-petersen**
Do NOT MERGE - failed testing

This PR updates the mpas-source submodule.  The only change is to the equation of state, but there are non-bfb changes due to order of operations. These changes are intended to optimize that part of the code for GPU's.

[non-BFB]

### CODE REVIEW

**Comment by bishtgautam** [comment]
@mark-petersen, Try the following
```
git submodule sync
git submodule update --init
```

**Comment by jonbob** [comment]
@mark-petersen - have you been able to test this?

**Comment by mark-petersen** [comment]
Yes, the `git submodule sync` worked.  Thanks, @bishtgautam.  I tested:
```
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.edison_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.edison_gnu
```
compiles fine.  Currently in queue.

**Comment by mark-petersen** [comment]
Passed all these on edison.  It's ready to merge.
```
 PEM_Ln9.T62_oQU240.GMPAS-IAF.edison_gnu
 PEM_Ln9.T62_oQU240.GMPAS-IAF.edison_intel
 PET_Ln9.T62_oEC60to30v3.GMPAS-IAF.edison_gnu
 PET_Ln9.T62_oEC60to30v3.GMPAS-IAF.edison_intel
 PET_Ln9.T62_oQU240.GMPAS-IAF.edison_gnu
 PET_Ln9.T62_oQU240.GMPAS-IAF.edison_intel
 SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.edison_gnu
 SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.edison_intel
```

**Comment by jonbob** [comment]
merged to next

**Comment by rljacob** [comment]
@mark-petersen any progress on this PR?

**Comment by philipwjones** [comment]
@rljacob - the test failed on @jgfouca 's machine and a code inspection didn't reveal a problem. Is there a place where these tests are documented to see if I can reproduce that software stack somewhere else.

**Comment by rljacob** [comment]
I found the test results where the fails were reported:
https://my.cdash.org/index.php?project=ACME_Climate&date=2019-01-15

**Comment by rljacob** [comment]
Actually the melvin problems were all baseline diffs which are expected.  The two tests that really failed were fully coupled cases on sandiatoss3:
 PET_Ln9_PS.ne30_oECv3_ICG.A_WCYCL1850S.sandiatoss3_intel.allactive-mach-pet
SMS_P12x2.ne4_oQU240.A_WCYCL1850.sandiatoss3_intel.allactive-mach_mods

@jonbob do you remember if those were the 2 that were not expected?

**Comment by jonbob** [comment]
@rljacob - yes, those were the two unexpected ones. We knew there would be round-off answer changes, but did not expect any outright failures.

**Comment by amametjanov** [comment]
@mark-petersen (and @jonbob), this PR MPAS-Dev/MPAS-Model#170 should fix the issue with the threading tests.

**Comment by rljacob** [comment]
Has this been replaced by PR #2852 ?  If so please close this.  If not, please explain the relationship.

**Comment by mark-petersen** [comment]
Yes, it was indeed replaced.  Closing this one.

**Pull request closed without merging**
