### PR TITLE
Support for ne30np4pg2 in ELM

### PR DESCRIPTION
**Pull request by bishtgautam**
- Adds mapping files for ne30np4pg2
- Adds surface dataset for ne30np4pg2 for 1850 and 2000

[BFB]

### CODE REVIEW

**Comment by bishtgautam** [comment]
The newly generated surface datasets have been uploaded to the E3SM inputdata server.

**Comment by rljacob** [comment]
What were the pg2 runs using before this?

**Comment by jonbob** [comment]
@rljacob - before this we were using the trigrid approach when atm was on ne30pg2, so lnd was running on r05

**Comment by jonbob** [comment]
Thanks @bishtgautam - we'll make a longer test run over the weekend

**Comment by jonbob** [comment]
I added grid configuration support for this new ELM file, so it can run with a variety of ocn/ice v2 meshes

**Review by jonbob — APPROVED** [review]
Test case ran one month smoke test out-of-the box

**Comment by jonbob** [comment]
@bishtgautam - can you please merge this soon? I think it will be necessary for the v2 configurations. Thanks!

**Comment by bishtgautam** [comment]
Sorry, for dropping the ball on this. I will merge this PR in a few hours.

**Pull request merged**
