### PR TITLE
set SCREAM to run with adjust_ps=.false.

### LINKED ISSUE #4693: pressure update due to phase change
At the end of the physics timestep the pressure has to be updated to sources/sinks of water vapor.
in E3SM v1 and v2, this change is made in the surface pressure and then distributed uniformly through the column.
In a vertically lagrangian model, the correct behavior is to change the pressure locally, based on the local changs in water vapor.

This is a small change with minor climate impacts, but implementation is on hold so as to not change v2 behavior.

### PR DESCRIPTION
**Pull request by mt5555**
dont reproduce buggy behavior used in E3SM v1/v2

[BFB]
In the SCREAM model, will be non-BFB, with minor impacts on climate

This address #4693, but only for the scream code base, and thus this PR should not close #4693

### CODE REVIEW

**Comment by rljacob** [comment]
Is there an issue describing this bug?

**Comment by mt5555** [comment]
@rljacob: added an issue for this PR

**Comment by rljacob** [comment]
What's the problem?  I think the buildlib code can set the variable based on the compset long name.

**Comment by mt5555** [comment]
here a description of the issue:

https://github.com/E3SM-Project/scream/issues/1343

**Pull request closed without merging**
