### PR TITLE
Add new h2o temperature field to timeSeriesStatsMonthlyOutput

### PR DESCRIPTION
**Pull request by jonbob**
Adds the new h2o temp field totalFreshWaterTemperatureFlux to the mpas-ocean output in timeSeriesStatsMonthlyOutput.

[BFB]

### CODE REVIEW

**Review by vanroekel — APPROVED** [review]
exactly what we need to diagnose the heat budget.  Thanks @jonbob!

**Comment by jonbob** [comment]
running a quick test and will get it merged

**Comment by jonbob** [comment]
Test with compset WCYCL1850 and res ne30pg2_EC30to60E2r2 ran successfully for a month on anvil, produced the additional expected output in the mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc file

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
