### PR TITLE
Optionally disable alarm calibration in mpas-framework

### LINKED ISSUE #5217: Start time in timeSeriesStats output from MPAS-Ocean not correct after restart
There has been a long-standing bug that the value of `xtimeMonthly_start` is incorrect in the first `timeSeriesStatsMonthly` output file after a restart.  This issue is discussed further here:
https://github.com/E3SM-Project/E3SM/pull/5202#issuecomment-1257252115
in the context of the new CF-compliant `Time` and `Time_bnds` coordinates, which are also affected.

### PR DESCRIPTION
**Pull request by xylar**
This merge allows calls to `mpas_set_clock_time` to disable alarm calibration when setting the current time.  This is useful because re-calibrating alarms has a negative impact on `timeSeriesStats` analysis members in MPAS-Ocean and MPAS-Seaice. The timeSeriesStats AMs get initialized with alarms that should ring after one compute interval.  If alarms are re-calibrated, they ring immediately instead.  However, the analysis members typically do not get computed at the start time, so the alarm actually rings after one time step.  If the time interval desired for timeSeriesStats is not a single time step, the compute alarm should not be ringing but it is on the first time step.

Fixes #5217
[non-BFB] for mpas timeSeriesStats diagnostic output only

### CODE REVIEW

**Comment by xylar** [comment]
This PR seems to be a better solution to the problem that I have been trying to solve in #5218.  That PR will still be needed to solve the "restart" problem for timeSeriesStats but this PR is a cleaner fix to the incorrect start time.

**Comment by xylar** [comment]
@akturner, @mark-petersen and @matthewhoffman, I'm asking you to review because this is a framework change.  I'm happy to discuss on our next MPAS dev-ops PR if you like.

**Comment by xylar** [comment]
## Testing

I ran `SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel`:
```
./create_test SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel --walltime 1:00:00 --wait -c -b master_20221106 --baseline-root /lcrc/group/e3sm/ac.xylar/e3sm_baselines
```
comparing with the latest `master`.  The test passed.

I also ran 1 month and then a second of `GMPAS-JRA1p4_TL319_EC30to60E2r2` on Chrysalis, and found that the resulting `xtime_startDaily`, `xtime_startMonthly`, `Time`, `Time_bnds`, etc. in `timeSeriesStats` looked correct for both MPAS-Seaice and MPAS-Ocean for both months.  Results are here:
```
/lcrc/group/e3sm/ac.xasay-davis/scratch/chrys/20221104.GMPAS-JRA1p4_TL319_EC30to60E2r2.disable-calibrate-alarms.chrysalis/run
```

**Comment by xylar** [comment]
Confirming that I think the new results are right and the old are not, here is `timeDaily_counter` from master:
```

 timeDaily_counter = 23, 24, 24, 24, 24 ;
```
and from this branch:
```
 timeDaily_counter = 24, 24, 24, 24, 24 ;
```
Clearly, the first hour is missing from the test on `master`.

**Comment by xylar** [comment]
@jonbob, could you help me figure out what the BFB flag needs to be when `timeSeriesStats` output is affected but other results are not?

**Review by mark-petersen — APPROVED** [review]
@xylar thanks for your explanation of this at our last meeting. I'm approving based on your testing, showing that it fixed the timing problem. I also ran some ocean stand-alone sanity tests with gnu debug.

**Review by akturner — APPROVED** [review]
Passed standalone tests

**Review by matthewhoffman — APPROVED** [review]
@xylar , this looks like a nice, simple solution after I had time to fully understand it!

**Comment by xylar** [comment]
Thank you for the prompt reviews and testing, @matthewhoffman, @akturner and @mark-petersen.

@jonbob, I believe this is now ready for you to test as you see fit.

**Comment by jonbob** [comment]
Sorry @xylar -- I missed your earlier question about the BFB flag when timeSeriesStats output is affected. It definitely shows this behavior in testing (everything else is BFB, but not timeSeriesStatsDaily), so I'll check with @rljacob

**Comment by rljacob** [comment]
Is that just a diagnostic output file?  No changes to the ocean state itself?

**Comment by jonbob** [comment]
Thanks for jumping in @rljacob. No changes to the ocean or seaice states, just how some output gets time-averaged. But @xylar, please correct me if that's not accurate

**Comment by jonbob** [comment]
PASSes the following tests with the exception of timeSeriesStats files:
* SMS_Ld2.ne30pg2_r05_EC30to60E2r2.BGCEXP_CNTL_CNPECACNT_1850.chrysalis_intel.elm-bgcexp
* ERS.ne11_oQU240.WCYCL1850NS.chrysalis_intel
* SMS_D_Ld3.T62_oQU120.CMPASO-IAF.chrysalis_intel

**Comment by jonbob** [comment]
@rljacob - we'd like to merge this soon, but would appreciate your input on handling the situation where some of the output will not be BFB despite no changes to the ocean state

**Comment by rljacob** [comment]
Just mention that only diagnostics are non-BFB.

**Comment by jonbob** [comment]
tested again and merged to next

**Comment by jonbob** [comment]
@xylar -- we're getting a real FAIL from merging this with test ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.mosart-rof_ocn_2way on a range of platforms. I've verified it's due to this PR and trying to tease it apart a bit. But I'd appreciate any ideas or thoughts you might have about this

**Comment by xylar** [comment]
I'll either need to see the logs or run that test myself. Sorry about that.

**Comment by jonbob** [comment]
That's OK -- let me point you at logs from a test merge of this PR into master. I actually have four tests and I'll give you a quick overview of each as well as the path:

1. master:
ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.chrysalis_intel.mosart-rof_ocn_2way.C.20221130_122937_qznl09

2. master with test merge of this PR:
ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.chrysalis_intel.mosart-rof_ocn_2way.C.20221130_130507_fo7tfy

3. master with test merge but removing the calibrate_alarms settings in the seaice driver (also failed):
ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.chrysalis_intel.mosart-rof_ocn_2way.C.20221130_135234_cjvtto

4. master with test merge but removing the calibrate_alarms settings in the ocean driver:
ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.chrysalis_intel.mosart-rof_ocn_2way.C.20221130_143305_45g16s

As you probably expected, the last one passes the ERS part but does not fix the timeSeriesStats issue in the ocean

**Comment by xylar** [comment]
@jonbob, I had a look and those are, indeed, a mess of changes that weren't expected.

I will go back to the drawing board on this one.  Thank goodness we have good tests to catch this kind of problem before it goes in.

**Comment by jonbob** [comment]
Thanks @xylar -- I also ran a more simple ERS G-case and it failed as well. I'll revert this and hope it's not too onerous to track down

**Comment by xylar** [comment]
Thanks @jonbob.

**Comment by xylar** [comment]
I think it makes sense to close this and have a different branch for an alternative approach.

**Pull request closed without merging**
