### PR TITLE
Fix F2010SC5-CMIP6.northamericax4v1_r0125_northamericax4v1

### PR DESCRIPTION
**Pull request by tangq**
The fix includes two parts: 1) adding ATM2ROF maps between the northamericax4v1 atm grid and the r0125 land grid; 2) turn off atm_c2_rof coupling when atm_prognostic is true.

### CODE REVIEW

**Comment by rljacob** [comment]
If you're doing 1, do you still have to do 2?

**Comment by tangq** [comment]
@rljacob , to answer your question I will need to know more about the behavior of MOZART-heat. If atm_c2_rof coupling does not change the results of other components than MOZART, removing 2) should be fine. Otherwise, it feels saver to keep 2) till we have plans to analyze MOZART-heat results from simulations with prognostic atmosphere.

**Comment by jonbob** [comment]
@tangq - @rljacob makes a good point. MOSART-heat does not feed back to the coupled system at all and the heatflag is off by default anyway. But I know the MOSART developers would like to be able to test without an active atmosphere, so removing 2) is preferable for them.

**Comment by tangq** [comment]
@jonbob , I am a bit confused. I thought what 2) does is to ensure the MOSART tests are done without an active atmosphere, which is desired by the MOSART developers.

I might be wrong about what the developers wanted. But either way if their changes do not feedback to the coupled system as you mentioned above, I don't see a reason to keep 2).

**Comment by tangq** [comment]
I removed the atm_prognostic flag as suggested from the discussions above. It should be ready to go.

**Comment by jonbob** [comment]
@rljacob - is it OK to merge this now? Or do we need to wait for @eroesler to review?

**Comment by jonbob** [comment]
Sorry, @eroesler was a suggestion and not a requested reviewer. I'll merge now

**Comment by jonbob** [comment]
@tangq - is there an issue that this fixes? The "bug fix PR" label means this should have an issue number associated with it

**Comment by tangq** [comment]
@jonbob , this PR provides the atm2rof maps for the F2010SC5-CMIP6.northamericax4v1_r0125_northamericax4v1 configuration. I am not aware of an issue associated with it. I removed the "bug fix PR".

**Comment by jonbob** [comment]
Perfect -- I'll get it merged right away. Thanks

**Comment by jonbob** [comment]
merged to next

**Comment by tangq** [comment]
Thank you, @jonbob

**Comment by jonbob** [comment]
You're welcome, @tangq -- thanks for getting this together and everything to make it work

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
