### PR TITLE
Fixed the name for mpaso stream configuration file in the comment

### PR DESCRIPTION
**Pull request by herrwang0**
In the comment section: 
stream.ocean_forward --> stream.ocean.forward

[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
It's correct that "stream.ocean_forward" is specified in the comments of this file, but the correct name is "stream.ocean" and not "stream.ocean.forward". I'll fix this to be consistent

**Comment by herrwang0** [comment]
Got it. 

A related question: is there a way similar to actually add streams to stream.ocean (rather than providing a full stream.ocean)?

**Comment by jonbob** [comment]
@herrwang0 - no, we've never figured out a good way to do that. Hopefully it's not too hard to copy the streams.ocean file that gets created in the run directory into the SourceMods/src.mpaso location and add streams to that file?

**Comment by herrwang0** [comment]
Thanks for the response. 
Yes, copy and edit streams.ocean works for me

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master.
@herrwang0 - you can delete the branch now if you want

**Pull request merged**
