### PR TITLE
ELM-Erosion bug fixing

### PR DESCRIPTION
**Pull request by tanzeli1982**
Fix a units bug in ELM-Erosion

[B4B]

### CODE REVIEW

**Comment by rljacob** [comment]
@tanzeli1982 are you sure this does not change answers?
@bishtgautam does this impact v2 sims?

**Comment by tanzeli1982** [comment]
@rljacob This bug fix changes soil erosion outputs. But because there is still no test covering the soil erosion model, it is B4B.

**Comment by tanzeli1982** [comment]
@bishtgautam Could you approve the change?

**Review by bishtgautam — APPROVED** [review]

**Comment by rljacob** [comment]
@tanzeli1982 is the soil erosion model turned off by default?  Is it something a v2 sim needs turned on?

**Comment by bishtgautam** [comment]
This is certainly not needed in WC-v2 sims, but might be needed for BGC-v2 sims.

**Comment by tanzeli1982** [comment]
@rljacob It is now turned off by default. It can be turned on by adding "use_eroson = .true." to user_nl_elm. As Gautam said, we plan to include the model in the BGC-v2 campaign.

**Comment by tanzeli1982** [comment]
@rljacob @bishtgautam Any plan to merge this PR?

**Comment by rljacob** [comment]
This can be merged now.

**Comment by tanzeli1982** [comment]
> This can be merged now.

@bishtgautam Could you help merge it?

**Pull request merged**
