### PR TITLE
Update ocn/ice/rof scripts and drivers to fix branch runs

### LINKED ISSUE #4129: branch runs - mpas-o and mpas-si restart files have the wrong name
documenting a possible issue with branch runs using a different case name:

From the CIME documentation:
     -- In a branch run, all components are initialized using a consistent                          
      set of restart files from a previous run (determined by the                                    
      RUN_REFCASE and RUN_REFDATE variables in env_run.xml).  The case name                          
      is generally changed for a branch run, although it does not have to                            
      be. 

when attempting a branch run with a different case name, the mpas-o and mpasi-si rpointer files contain just the date stamp and not the full name of the restart file.  The mpas components then appear to construct the restart filename based on the new case name.  The run will then abort during initialization since these files dont exist.  

The atm and lnd components appear to avoid this issue by putting the full filename of the restat file in the rpointer files.

As CIME stages the restart files from the old case, after seeing the error messages a possible workaround is for the user to add symbolic links from the new names to the original names

### LINKED ISSUE #4285: branch run on Chrysalis
I run into several issues when I conduct a branch run with master
1. The case cannot identify the correct restart files unless I make the following modification:
    $E3SM_CODES/components/mosart/cime_config/buildnml
                    #XZ refdir = os.path.join(din_loc_root, run_refdir, run_refcase, run_refdate)
                    refdir = os.path.join(run_refdir)
    $E3SM_CODES/components/mpas-ocean/cime_config/buildnml
        if run_type == 'hybrid' or run_type == 'branch':  #XZ 20210507
            lines.append('                  filename_template="{}.mpassi.rst.$Y-$M-$D_$S.nc"'.format(run_refcase))
        else:
            lines.append('                  filename_template="{}.mpassi.rst.$Y-$M-$D_$S.nc"'.format(casename))
    $E3SM_CODES/components/mpas-seaice/cime_config/buildnml
        if run_type == 'hybrid' or run_type == 'branch':  #XZ 20210507
            lines.append('                  filename_template="{}.mpassi.rst.$Y-$M-$D_$S.nc"'.format(run_refcase))
        else:
            lines.append('                  filename_template="{}.mpassi.rst.$Y-$M-$D_$S.nc"'.format(casename))
2. The branch simulation is non-BFB to the original simulation
 The test case is /lcrc/group/e3sm/ac.xzheng/E3SM_simulations /20210423.test3.v2rc1d.piControl.ne30pg2_EC30to60E2r2.chrysalis
 The reference case is /lcrc/group/e3sm/ac.xzheng/E3SM_simulations/20210423.v2rc1c.piControl.ne30pg2_EC30to60E2r2.chrysalis

### PR DESCRIPTION
**Pull request by jonbob**
Makes changes to several mpas-ocean and mpas-seaice scripts as well as driver code to fix issues with branch runs not working correctly. Also requires an update to the mosart buildnml script.

Fixes #4129 
Fixes #4285

[BFB] for all tested configurations, only impacts branch runs

### CODE REVIEW

**Comment by jonbob** [comment]
Tested with branch runs made by running one case 11 days but dropping a restart file at day 6, and then making a separate branch case that starts from the restart set of the first case and runs 5 days -- and then comparing coupler history files. Successfully completed branch tests on anvil of:
* T62_oQU240-DTESTM
* T62_oQU240-CMPASO-IAF
* T62_oQU240-GMPAS-IAF
* ne4_oQU240-A_WCYCL1850

**Comment by jonbob** [comment]
@mt5555 - thank you for the suggested fix
@xuezhengllnl - could you please check and see if this fixes the issue you reported?

**Review by rljacob — APPROVED** [review]

**Comment by jonbob** [comment]
Also updated MALI scripts and passed a branch test using T62_oQU120_ais20-MPAS_LISIO_TEST

**Comment by xuezhengllnl** [comment]
Hi @jonbob, Sorry that I didn't receive any notice about the reviewer assignment. I just did a test with your branch jonbob/ocnice/fix-branch-runs

It couldn't build successfully. The mosart buildnml is still not working according to the last few lines of information:
> Create namelist for component mosart
> Calling /gpfs/fs1/home/ac.xzheng/E3SM/code/20210520/components/mosart//cime_config/buildnml
> WARNING:: mosart.buildnml could not find restart file for branch or hybrid start
> ERROR: ERROR mosart.buildnml: GET_REFASE is TRUE, so aborting because couldn't find files

**Comment by jonbob** [comment]
Thanks for testing this, @xuezhengllnl. Can you please point me to the case you're working on? I hadn't run into issues with mosart, but I'm sure I wasn't testing it the way you and Chris typically run so I very much appreciate your help.

**Comment by xuezhengllnl** [comment]
> Thanks for testing this, @xuezhengllnl. Can you please point me to the case you're working on? I hadn't run into issues with mosart, but I'm sure I wasn't testing it the way you and Chris typically run so I very much appreciate your help.

The case is here: /lcrc/group/e3sm/ac.xzheng/E3SM_simulations/20210520.test.branch_v2rc1c.piControl.ne30pg2_EC30to60E2r2.chrysalis
Please let me know if you have any trouble to access the folder.

**Comment by jonbob** [comment]
Thanks @xuezhengllnl -- I can see that run directory just fine. But it looks to me like it should be working, so I'll have to debug. Thanks again

**Comment by xuezhengllnl** [comment]
> Thanks @xuezhengllnl -- I can see that run directory just fine. But it looks to me like it should be working, so I'll have to debug. Thanks again
Please let me know if you need any further information. Thanks!

**Comment by jonbob** [comment]
@rljacob - can I get you to look at the changes I made to the mosart buildnml? There had been some logic to access the get_refcase and refdir settings to grab the restart files -- it's both unnecessary (because CIME does it) and problematic, but I want to make sure you're comfortable with the changes.

**Comment by jonbob** [comment]
@xuezhengllnl - can I ask you to please test it again with my latest update? Thank you

**Review by rljacob — APPROVED** [review]

**Comment by rljacob** [comment]
Looks good to me.  Can you say more about what the MOSART buildnml was duplicating?

**Comment by jonbob** [comment]
@rljacob - sure. The mosart buildnml script was searching the refdir path for the necessary branch/hybrid files, even though CIME now either stages the files in the run directory (GET_REFCASE = TRUE) or assumes the user has staged the files in the run directory (GET_REFCASE = FALSE). It also was creating its own name for the refdir incorrectly, using 
````
                if get_refcase:
                    refdir = os.path.join(din_loc_root, run_refdir, run_refcase, run_refdate)
````
For the case where we're pointing into an archived set of restarts:
````
    <entry id="RUN_REFDIR" value="/lcrc/group/e3sm/ac.xzheng/E3SM_simulations/20210423.v2rc1c.piControl.ne30pg2_EC30to60E2r2.chrysalis/archive/rest/0201-01-01-00000">
    <entry id="RUN_REFCASE" value="20210423.v2rc1c.piControl.ne30pg2_EC30to60E2r2.chrysalis">
````
this caused the scripts to search the following directory for the mosart restart files:
````
refdir = /lcrc/group/e3sm/ac.xzheng/E3SM_simulations/20210423.v2rc1c.piControl.ne30pg2_EC30to60E2r2.chrysalis/archive/rest/0201-01-01-00000/20210423.v2rc1c.piControl.ne30pg2_EC30to60E2r2.chrysalis/0201-01-01
````
which doesn't exist and causes the case to abort. In general, there's no reason for any component to be concerned with searching the refdir -- so I reworked the script to assume the necessary files have been staged in the rundir, as other components do.

**Comment by xuezhengllnl** [comment]
> @xuezhengllnl - can I ask you to please test it again with my latest update? Thank you

The new test has been successfully complied and submitted on chrysalis. I will let you know when it is done and whether it is BFB.

**Comment by xuezhengllnl** [comment]
> @xuezhengllnl - can I ask you to please test it again with my latest update? Thank you

Hi @jonbob The 5-day test is done and it is BFB compared to the original v2rc1c atm.log. I think your fix is good to go. Thank you for fixing this issue!

**Review by xuezhengllnl — APPROVED** [review]

**Comment by jonbob** [comment]
Thank you @xuezhengllnl for all the testing. Merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
