### PR TITLE
Update mpas-source: split explicit bugfix

### LINKED ISSUE #4152: Figure out non-BFB behavior from ocean split-explicit time integration driver cleanup
PR #4146 resulted in unexplained non-BFB results for some, but not all, configurations using the intel compiler in both optimized and debug mode. Because the impacted configurations include the current WaterCycle default, it is critical we understand the cause of the answer changes before moving past.

### PR DESCRIPTION
**Pull request by mattdturner**
This PR reverts a subset of the changes introduced in #4146 that caused non-BFB results for a few of the tests in E3SM.

See https://github.com/MPAS-Dev/MPAS-Model/pull/826

Fixes #4152

[non-BFB]

### CODE REVIEW

**Comment by mattdturner** [comment]
### Testing

Direct Copy from https://github.com/MPAS-Dev/MPAS-Model/pull/826#issuecomment-797790921
---
This branch was tested in MPAS-O nightly regression suite, using `bcde86f8b` to generate the baseline dataset.  It is BFB for:
- Intel v19.0.4 Optimized (failed when testing #781 )
- Intel v19.0.4 Debug
- Gnu v5.3.0 Optimized
- Gnu v5.3.0 Debug

For E3SM testing, baselines were generated using commit `dd5895d0a`.  This branch was then merged, and tests were compared against that baseline.  The following BFB tests passed:
```
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
PET_Ln9_P1024.ne30_oECv3.A_WCYCL1850S.chrysalis_intel
PEM_Ln9_P1024.ne30_oECv3.A_WCYCL1850S.chrysalis_intel
```

The following tests that do not check for BFB passed.  These tests started with E3SM hash `dd5895d0a` and had this branch merged in
```
PEM_Ln9.T62_oQU240.GMPAS-IAF.chrysalis_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.chrysalis_intel
PET_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.chrysalis_intel
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.chrysalis_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
PEM_Ln9_D.T62_oQU240.GMPAS-IAF.chrysalis_intel
PET_Ln3_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.chrysalis_intel
SMS_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.chrysalis_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
```

The following tests that do not check for BFB passed.  These tests started with E3SM hash `7cbaa3353` (the current master) and had this branch merged in
```
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
PEM_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_gnu
PET_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
PEM_Ln9.T62_oQU240.GMPAS-IAF.anvil_gnu
PET_Ln9.T62_oQU240.GMPAS-IAF.anvil_gnu
```

Testing on HEAD of this branch
---
```
PASS:
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_gnu
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_gnu
PEM_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
PEM_Ln9.T62_oQU240.GMPAS-IAF.anvil_gnu
PEM_Ln9.T62_oQU240.GMPAS-IAF.anvil_intel
PEM_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
PET_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
PET_Ln9.T62_oQU240.GMPAS-IAF.anvil_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.anvil_gnu
PET_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
PET_Ln3_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_gnu
PEM_Ln9_D.T62_oQU240.GMPAS-IAF.anvil_gnu
```

**Review by jonbob — APPROVED** [review]
Approved based on visual inspection and thorough testing by the developers

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master and expected DIFFs blessed -- except on sandiatoss3 which was down for maintenance. I'll plan on submitting requests for that platform tomorrow

**Comment by jonbob** [comment]
sandiatoss3 reported and I submitted a request to bless the expected DIFFs

**Pull request merged**
