### PR TITLE
Land Use Translator update for E3SM land surface files

### PR DESCRIPTION
**Pull request by bishtgautam**
Updates the land use translator (LUT) to be consistent between iESM and the ELM tool, 
fixes some bugs, and updates the LUT processing. The new LUT generates identical results
regardless of machine (mac, cori, compy), compiler (gcc or intel), or compiler optimization (0 to 3).
Additionally updates the makefile of mksurfdata and the namelist_defaults_clm4_5_tools.xml to
allow for all 8 CMIP6 future scenarios to be potentially be created.

[BFB]

### CODE REVIEW

**Review by aldivi — APPROVED** [review]
I verified that these are the same changes that I tested over the past 24 hours.
Thanks, Gautam.

**Comment by bishtgautam** [comment]
The PR was not automatically closed because all commits except the last commit were merged. PR-#3829 will merge the last missing commit.

**Comment by rljacob** [comment]
I think you can just add the commit to this branch?

**Comment by rljacob** [comment]
Push the version of the branch that you merged locally.

**Pull request closed without merging**
