### PR TITLE
Add frazil to ice-shelf melt rates

### PR DESCRIPTION
**Pull request by irenavankova**
New variable frazilIceFreshwaterFlux is introduced to keep track of frazil ice formation instanatenously (and not only commulatively over coupling timestep as before)

New variable landIceFreshwaterFluxTotal is introduced to keep track of total melt rates that includes both interface melt/freeze and frazil ice formation, so that landIceFreshwaterFluxTotal = landIceFreshwaterFlux + frazilIceFreshwaterFlux.

Associted changes in MPAS-Analysis reflect this to plot Antarctic meltrate maps with landIceFreshwaterFluxTotal instead of landIceFreshwaterFlux: 
https://github.com/MPAS-Dev/MPAS-Analysis/pull/989

The changes here affect diagnostics only.

Related Ocean Discussion is here:
https://github.com/E3SM-Ocean-Discussion/E3SM/pull/79

### CODE REVIEW

**Review by xylar — APPROVED** [review]
I ran a 5-year `CRYO1850.ne30pg2_r05_IcoswISC30E3r5` simulation with this branch.  The analysis output from just the ice-shelf melting, frazil accretion, and total of the two can be seen here:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis/20240226.CRYO1850.ne30pg2_r05_IcoswISC30E3r5.include_frazil.chrysalis/yrs_5-5/ocean/index.html

This is an important fix for us to include in our model output and analysis!

**Comment by xylar** [comment]
@cbegeman, could you give this another look? Hopefully, it will be quick since you already approved this on Ocean-Discussion.

**Review by cbegeman — APPROVED** [review]
This looks great. Thanks @irenavankova!

**Comment by jonbob** [comment]
passes:
* ERS.ne4pg2_oQU480.WCYCL1850NS.chrysalis_intel
* SMS_D_Ld1.ne30pg2_r05_IcoswISC30E3r5.CRYO1850-DISMF.chrysalis_intel
* ERP_Ld3.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-pioroot1

merged to next

**Comment by xylar** [comment]
Woohoo!  Thanks @jonbob!

**Comment by xylar** [comment]
And thanks very much, @irenavankova!

**Pull request merged**
