### PR TITLE
Added modex machine config files

### PR DESCRIPTION
**Pull request by serbinsh**
PR to add the machine-specific configuration options to the e3sm config files for building and running on the modex compute cluster at BNL.

### CODE REVIEW

**Comment by serbinsh** [comment]
The equivalent files are CESM/CIME.  Is there where I would place a PR like this or should I be doing this somewhere else?

Summary: modex is a 100 core, multi-node cluster that I manage and use in the BNL TEST group (https://www.bnl.gov/envsci/testgroup/) so this doesn't impact any other researcher at any other institution.

**Comment by rljacob** [comment]
@serbinsh this is the right place for adding E3SM specific machines.   Just edit the description above to remove the last 2 sentences.  The description of the PR should be exactly the text you want in the git log.

**Comment by serbinsh** [comment]
OK @rljacob I updated the description above....let me know if you would like any changes or more information.

**Comment by rljacob** [comment]
Is this machine for just your own use?

**Comment by serbinsh** [comment]
@rljacob Its for our groups use so not just mean but me, my postdocs and students, as well as external collaborators whom use the modex cluster.  This is a cluster located at BNL

**Comment by wlin7** [comment]
Merged to next.

**Comment by wlin7** [comment]
Merged to master.

**Pull request merged**
