### PR TITLE
Fix usage of o2r_rx without rof-ocn two way enabled

### LINKED ISSUE #5192: prep_rof_mrg using non-associated and un-allocated pointer O2R_RX
While working on another issue, my debug runs would fail in `prep_rof_mod` with the below traceback, which has happened with all debug land tests that I've tried so far on chrysalis with Intel.

```
**SMS_D_Ld1.hcru_hcru.I1850CRUELMCN.chrysalis_intel**
 77: forrtl: severe (408): fort: (7): Attempt to use pointer O2R_RX when it is not associated with a target
 77:
 77: Image              PC                Routine            Line        Source
 77: libpnetcdf.so.3.0  0000155551014202  for_emit_diagnost     Unknown  Unknown
 77: e3sm.exe           00000000005E105F  prep_rof_mod_mp_p         478  prep_rof_mod.F90
 77: e3sm.exe           0000000000472343  cime_comp_mod_mp_        4404  cime_comp_mod.F90
 77: e3sm.exe           0000000000452604  cime_comp_mod_mp_        2873  cime_comp_mod.F90
 77: e3sm.exe           000000000047CD04  MAIN__                    153  cime_driver.F90
 77: e3sm.exe           000000000041AE22  Unknown               Unknown  Unknown
 77: libc-2.28.so       000015554E665493  __libc_start_main     Unknown  Unknown
 77: e3sm.exe           000000000041AD2E  Unknown               Unknown  Unknown
```

The problem seems to be that `O2R_RX` is only allocated in `prep_rof_init` if both ROF and OCN are both present but `prep_rof_mrg` is called even if OCN is not present.  And my guess is that the fix is to add an if-statement to `cime_run_rof_setup_send` to check for OCN.
```
**from prep_rof_init**
if (rof_present .and. ocn_present) then

       call seq_comm_getData(CPLID, &
            mpicom=mpicom_CPLID, iamroot=iamroot_CPLID)

       lsize_r = mct_aVect_lsize(x2r_rx)

       o2x_ox => component_get_c2x_cx(ocn(1))
       lsize_o = mct_aVect_lsize(o2x_ox)

       allocate(o2racc_ox(num_inst_ocn))
       do eoi = 1,num_inst_ocn
          call mct_aVect_initSharedFields(o2x_ox, x2r_rx, o2racc_ox(eoi), lsize=lsize_o)
          call mct_aVect_zero(o2racc_ox(eoi))
       end do
       o2racc_ox_cnt = 0

       **allocate(o2r_rx(num_inst_rof))**
```

### LINKED ISSUE #5221: Attempt to use pointer O2R_RX when it is not associated with a target using SMS_D.f09_f09.IELM.MACHINE_intel.elm-solar_rad
With `SMS_D.f09_f09.IELM.cori-knl_intel.elm-solar_rad` I get following error using Oct 6th master.

```
 51: forrtl: severe (408): fort: (7): Attempt to use pointer O2R_RX when it is not associated with a target
 51:
 51: Image              PC                Routine            Line        Source
 51: e3sm.exe           0000000007145B56  Unknown               Unknown  Unknown
 51: e3sm.exe           00000000005C8637  prep_rof_mod_mp_p         478  prep_rof_mod.F90
 51: e3sm.exe           0000000000459B40  cime_comp_mod_mp_        4404  cime_comp_mod.F90
 51: e3sm.exe           0000000000439C1B  cime_comp_mod_mp_        2873  cime_comp_mod.F90
 51: e3sm.exe           0000000000464574  MAIN__                    153  cime_driver.F90
 51: e3sm.exe           0000000000402102  Unknown               Unknown  Unknown
 51: e3sm.exe           00000000072C940F  Unknown               Unknown  Unknown
 51: e3sm.exe           0000000000401FEA  Unknown               Unknown  Unknown

```
Same error with `SMS_D_Ld20.f45_f45.IELMFATES.cori-knl_intel.elm-fates_eca`

Verified I see same error on chrysalis.
I also see same fail with GNU compiler on cori-knl.

This is while I'm trying to figure out error here: https://github.com/E3SM-Project/E3SM/issues/5220
This test seems ok in DEBUG:
`SMS_D.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.cori-knl_intel.mosart-rof_ocn_2way`

### PR DESCRIPTION
**Pull request by peterdschwartz**
When ocn_rof_two_way = .false. o2r_rx is not allocated nor associated but elements were still passed to function call.  
Changed to optional argument for subroutine prep_rof_merge.

Fixes #5221
Fixes #5192 
[BFB]

### CODE REVIEW

**Review by ndkeen — CHANGES_REQUESTED** [review]
We probably don't want to add extra whitespaces for those lines do we?

**Comment by rljacob** [comment]
Is this a duplicate of #5225 ?

**Comment by peterdschwartz** [comment]
@ndkeen Updated without whitespace changes

**Review by ndkeen — APPROVED** [review]
Looks good. I checked out the branch and tested `SMS_D.f09_f09.IELM.cori-knl_intel.elm-solar_rad`

**Comment by jonbob** [comment]
passes e3sm_developer on chrysalis, merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
