### PR TITLE
Initial commit to prepend casename to mpas output files

### LINKED ISSUE #3576: Add case names to MPAS output file names
Adding case names to MPAS output files will help to identify origin of the file, facilitating archiving, publication and distribution. @jonbob Please revive your branch on this. And thank you for taking care of it!

### PR DESCRIPTION
**Pull request by jonbob**
This PR prepends the casename to all output files from the three mpas components, to identify origin of the file, facilitating archiving, publication and distribution.

Fixes #3576 

[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
Passes e3sm_developer suite

**Comment by jonbob** [comment]
@rljacob - this could possibly go into the repo at the same time as the switch from CAM to EAM, if that PR will change filenames as well? This PR will mostly impact testing and analysis, but will not change answers

**Review by chengzhuzhang — APPROVED** [review]
Thank you @jonbob!The PR looks good to me. 
@rljacob Would you also review this PR for filename change, just in case anything is missing?

**Comment by jonbob** [comment]
Thanks @chengzhuzhang -- and sorry it took so long

**Comment by chengzhuzhang** [comment]
@jonbob No worries. It's right on time! Thank you.

**Comment by rljacob** [comment]
I think some CIME changes will also be necessary because there were some hacks in the short-term archiving to get around MPAS not having case names that now have to be removed.

**Comment by jonbob** [comment]
@rljacob - do you need me to make the CIME changes?

**Comment by rljacob** [comment]
Is this just for history files?  I think the restart files are the  ones with code in cime.  Its in scripts/lib/CIME/case/case_st_archive.py

**Comment by jonbob** [comment]
@rljacob - it changes all the output files to have the casename as a prefix. I'll try to get the CIME changes taken care of tomorrow morning

**Comment by jonbob** [comment]
@jgfouca - did you ever have a chance to look in CIME at the short-term archiver and this name change?

**Comment by jgfouca** [comment]
@jonbob, trying it now.

**Comment by jgfouca** [comment]
@jonbob, I ran SMS.T62_oQU120_ais20.MPAS_LISIO_TEST on mappy and this is the output I got when I ran $case/case.st_archive:
```
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/cpl.log.201007-172255.gz to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/logs/cpl.log.201007-172255.gz
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/atm.log.201007-172255.gz to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/logs/atm.log.201007-172255.gz
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/ocn.log.201007-172255.gz to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/logs/ocn.log.201007-172255.gz
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/e3sm.log.201007-172255.gz to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/logs/e3sm.log.201007-172255.gz
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/ice.log.201007-172255.gz to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/logs/ice.log.201007-172255.gz
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/rof.log.201007-172255.gz to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/logs/rof.log.201007-172255.gz
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/glc.log.201007-172255.gz to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/logs/glc.log.201007-172255.gz
Cannot find a SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.cpl*.r.*.nc file in directory /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run 
Archiving history files for datm (atm)
Archiving history files for mpassi (ice)
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mpassi.hist.am.regionalStatistics.0001.01.nc to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/ice/hist/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mpassi.hist.am.regionalStatistics.0001.01.nc 
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mpassi.hist.am.regionalStatistics.0001.01.nc.base to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/ice/hist/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mpassi.hist.am.regionalStatistics.0001.01.nc.base 
Archiving history files for mpaso (ocn)
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mpaso.hist.am.globalStats.0001-01-01.nc to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/ocn/hist/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mpaso.hist.am.globalStats.0001-01-01.nc 
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/ocn/hist/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc 
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc.base to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/ocn/hist/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc.base 
Archiving history files for drof (rof)
Archiving history files for mali (glc)
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mali.hist.0001-01-01_00000.nc to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/glc/hist/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mali.hist.0001-01-01_00000.nc 
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mali.hist.am.0001-01-01_00000.nc to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/glc/hist/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mali.hist.am.0001-01-01_00000.nc 
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mali.hist.am.0001-01-01_00000.nc.base to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/glc/hist/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.mali.hist.am.0001-01-01_00000.nc.base 
Archiving history files for drv (cpl)
moving /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/run/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.cpl.hi.0001-01-06-00000.nc to /ascldap/users/jgfouca/acme/scratch/archive/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8/cpl/hist/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.20201007_171853_olsag8.cpl.hi.0001-01-06-00000.nc
```

The output is a bit cluttered, but it does appear as though the CIME st_archiver is seeing these renamed MPAS files. I also checked a baseline comparison and it saw them in that context as well. My feeling is that everything is OK but someone from your team should closely monitor things in the days after this is merged to make sure everything is OK.

**Comment by jgfouca** [comment]
@jonbob , here is the output from the baseline comparison:

```
2020-10-07 17:36:30: Comparing hists for case 'SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.C.20201007_173117_6jucij' dir1='/ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.C.20201007_173117_6jucij/run', su\
ffix1='',  dir2='/sems-data-store/ACME/baselines/mappy/gnu/master/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu' suffix2=''
  comparing model 'datm'
    no hist files found for model datm
  comparing model 'slnd'
    no hist files found for model slnd
  comparing model 'mpassi'
    File 'SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.C.20201007_173117_6jucij.mpassi.hist.am.regionalStatistics.0001.01.nc.base' had no compare counterpart in '/sems-data-store/ACME/baselines/mappy/gnu/master/SMS.T62_oQU120_ais20.MPAS_LIS\
IO_TEST.mappy_gnu' with suffix ''
    File 'mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc.base' had no original counterpart in '/ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.C.20201007_173117_6jucij/run' with suffix ''
  comparing model 'mpaso'
    SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.C.20201007_173117_6jucij.mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc.base did NOT match mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc.base
    cat /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.C.20201007_173117_6jucij/run/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.C.20201007_173117_6jucij.mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00\
.00.nc.base.cprnc.out
  comparing model 'drof'
    no hist files found for model drof
  comparing model 'mali'
    SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.C.20201007_173117_6jucij.mali.hist.am.0001-01-01_00000.nc.base matched mali.hist.am.0001-01-01_00000.nc.base
  comparing model 'swav'
    no hist files found for model swav
  comparing model 'siac'
    no hist files found for model siac
  comparing model 'sesp'
    no hist files found for model sesp
  comparing model 'cpl'
    SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.C.20201007_173117_6jucij.cpl.hi.0001-01-06-00000.nc did NOT match cpl.hi.0001-01-06-00000.nc
    cat /ascldap/users/jgfouca/acme/scratch/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.C.20201007_173117_6jucij/run/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.C.20201007_173117_6jucij.cpl.hi.0001-01-06-00000.nc.cprnc.out
FAIL
  Most recent bless: sha:f6a944d266f2389148de9fa9bbce27135aaa1a3b date:2020-10-02_16:51:43
```

I'm a little surprised that the mali hist file names matched.

**Comment by rljacob** [comment]
Before this PR, MPAS files did 2 things different from other models:  it didn't have a case name and it uses a different date-time string.  My concern was that this line needed to be modified:
https://github.com/ESMCI/cime/blob/master/scripts/lib/CIME/case/case_st_archive.py#L405
so the casename is included like in the else clause below it.   Maybe you can tell from reading it why it still works.

**Comment by jgfouca** [comment]
@rljacob , you mean this segment?

```
        if compname.find('mpas') == 0 or compname == 'mali':
            pattern = compname + r'\.' + suffix + r'\.' + '_'.join(datename_str.rsplit('-', 1))
            pfile = re.compile(pattern)
            restfiles = [f for f in os.listdir(rundir) if pfile.search(f)]
```

This code will still work. It searches the entire filename for the pattern, so having additional stuff come before the pattern doesn't matter.

**Comment by rljacob** [comment]
Yes that's it.  Good!  This can proceed then.

**Review by rljacob — APPROVED** [review]

**Comment by rljacob** [comment]
@golaz or @vanroekel, we'd like to merge this to master.

**Comment by vanroekel** [comment]
@rljacob I think this is fine, but I"d like @xylar to chime in on implications for mpas-analysis

**Comment by jonbob** [comment]
Thanks @jgfouca for jumping in!

**Comment by jonbob** [comment]
@xylar - I think this is waiting on your review

**Review by xylar — APPROVED** [review]
Sorry, I didn't notice that @vanroekel had asked for my input.  This looks good to me.  I believe MPAS-Analysis will work with these changes because it uses the `streams.ocean` file to determine file names.  If not, we can address that in MPAS-Analysis later.

If there is a full year of test output somewhere, I am happy to run MPAS-Analysis now before this gets merged.  Otherwise, please let me know as soon as there *is* a full year with this change so I can test on that and we can all have a bit more peace of mind.

**Comment by xylar** [comment]
Thanks @rljacob.  Let me test on that quickly before this gets merged.

**Comment by xylar** [comment]
MPAS-Analysis seems to be working fine for me on that output.  I just did a quick test on one ocean field and one sea-ice field but those would have failed if there were any problem with the file naming.

I'm running the full analysis just to be sure, but my approval of this PR stands.  Thanks for pointing me to that run and for checking with me on this.

**Comment by vanroekel** [comment]
thanks for reviewing and testing @xylar!  I greatly appreciate the piece of mind from your testing

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
