### PR TITLE
Add seaice developer test suite

### PR DESCRIPTION
**Pull request by jonbob**
Add a small seaice developer test suite to e3sm_developer.

[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
@amametjanov - I think you had done a lot of the work figuring out which tests could use the same compilation and I was hoping you might help understand if that can be done here? If not, the D-cases are small enough that it may not be a big deal. But I will run a test of this suite and see how long it takes

**Review by proteanplanet — COMMENTED** [review]
I have tested this on Anvil and Chrysalis using:

${CODE_ROOT}/cime/scripts/create_test \
         --output-root "${CASE_ROOT}" \
         --srcroot "${CODE_ROOT}" \
         --machine "anvil/chrysalis" \
         --project "condo/e3sm" \
         --wait "e3sm_ice_developer"

         
I get the following outcome on both machines for this branch:

`  ERS_Ld5.T62_oQU240.DTESTM.anvil_intel (Overall: PASS) details:
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel CREATE_NEWCASE
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel XML
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SETUP
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SHAREDLIB_BUILD time=117
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel MODEL_BUILD time=343
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SUBMIT
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel RUN time=52
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel COMPARE_base_rest
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel MEMLEAK insuffiencient data for memleak test
    PASS ERS_Ld5.T62_oQU240.DTESTM.anvil_intel SHORT_TERM_ARCHIVER
  PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel (Overall: FAIL) details:
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel CREATE_NEWCASE
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel XML
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel SETUP
    PASS PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel SHAREDLIB_BUILD time=240
    FAIL PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel MODEL_BUILD time=6
  PET_Ln5.T62_oQU240.DTESTM.anvil_intel (Overall: FAIL) details:
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel CREATE_NEWCASE
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel XML
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel SETUP
    PASS PET_Ln5.T62_oQU240.DTESTM.anvil_intel SHAREDLIB_BUILD time=116
    FAIL PET_Ln5.T62_oQU240.DTESTM.anvil_intel MODEL_BUILD time=4
  SMS_D_Ld1.TL319_oEC60to30v3.DTESTM-JRA1p5.anvil_intel (Overall: PASS) details:
    PASS SMS_D_Ld1.TL319_oEC60to30v3.DTESTM-JRA1p5.anvil_intel CREATE_NEWCASE
    PASS SMS_D_Ld1.TL319_oEC60to30v3.DTESTM-JRA1p5.anvil_intel XML
    PASS SMS_D_Ld1.TL319_oEC60to30v3.DTESTM-JRA1p5.anvil_intel SETUP
    PASS SMS_D_Ld1.TL319_oEC60to30v3.DTESTM-JRA1p5.anvil_intel SHAREDLIB_BUILD time=66
    PASS SMS_D_Ld1.TL319_oEC60to30v3.DTESTM-JRA1p5.anvil_intel MODEL_BUILD time=211
    PASS SMS_D_Ld1.TL319_oEC60to30v3.DTESTM-JRA1p5.anvil_intel SUBMIT
    PASS SMS_D_Ld1.TL319_oEC60to30v3.DTESTM-JRA1p5.anvil_intel RUN time=584
    PASS SMS_D_Ld1.TL319_oEC60to30v3.DTESTM-JRA1p5.anvil_intel MEMLEAK insuffiencient data for memleak test
    PASS SMS_D_Ld1.TL319_oEC60to30v3.DTESTM-JRA1p5.anvil_intel SHORT_TERM_ARCHIVER
`

Why are the PEM and PET tests failing to build?  The answer is in:

ERROR: BUILD FAIL: cmake config e3sm failed, cat /lcrc/group/e3sm/ac.afroberts/E3SM-Polar/Test.ice.jonstest.add-ice-test-suite.E3SM-Project.chrysalis/PEM_Ln5.T62_oQU240wLI.DTESTM.chrysalis_intel.20230403_184408_akjui1/bld/e3sm.bldlog.230403-185023

ERROR: BUILD FAIL: cmake config e3sm failed, cat /lcrc/group/e3sm/ac.afroberts/E3SM-Polar/Test.ice.jonstest.add-ice-test-suite.E3SM-Project.chrysalis/PET_Ln5.T62_oQU240.DTESTM.chrysalis_intel.20230403_184408_akjui1/bld/e3sm.bldlog.230403-184728

**Comment by amametjanov** [comment]
Probably need at least three executables: debug (`_D`), threaded (`PET`), and the third for `ERS`+`PEM`.

For ELM, when grid+compset were not identical, I was doing baseline-gen with old single-build exes, then baseline-comp with shared exes. Having 4 single-exes here is probably okay.

**Review by amametjanov — APPROVED** [review]

**Comment by jonbob** [comment]
Thanks @amametjanov

**Comment by proteanplanet** [comment]
@jonbob I still cannot get the PET and PEM tests to build on Chrysalis nor Anvil.

**Comment by jonbob** [comment]
@proteanplanet - can you point me at the tests that wouldn't build?

**Review by proteanplanet — APPROVED** [review]
With the update in master, this new test suite works on both anvil and chrysalis, and is a welcome addition. Approved.

I encountered an issue with the `create_test` script while checking this suite.  The following code worked:
`${CODE_ROOT}/cime/scripts/create_test  --output-root "${CASE_ROOT}"  --machine "${MACHINE}" --project "${PROJECT}" --wait "e3sm_ice_developer"`
         
while this code did not:
`${CODE_ROOT}/cime/scripts/create_test  --output-root "${CASE_ROOT}"  --srcroot "${CODE_ROOT}" --machine "${MACHINE}" --project "${PROJECT}" --wait "e3sm_ice_developer"`

Am I using `--srcroot` incorrectly?

**Comment by jonbob** [comment]
@proteanplanet -- I'm glad it's working for you now. That would appear to be proper use of the srcroot option, so you might think about making a CIME issue?

**Comment by jonbob** [comment]
@proteanplanet - I was thinking we should move to v2 grids at least, so I propose replacing 
````
SMS_D_Ld1.TL319_oEC60to30v3.DTESTM-JRA1p5
````

with
````
SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5

**Comment by proteanplanet** [comment]
@jonbob Definitely, let's proceed with that.

**Comment by jonbob** [comment]
passes all new test cases

merged to next

**Comment by jonbob** [comment]
overnight everything cleared except the JRA test on mappy

**Pull request merged**
