### PR TITLE
PAM variance transport

### PR DESCRIPTION
**Pull request by whannah1**
Implement the variance transport (VT) feature from SAM++ into PAM as a stealth feature. During testing it became clear that inclusion of strong hyperdiffusion in PAM made the variance transport unnecessary, but reducing the hyperdiffusion in cases with VT enabled led to instabilities. Thus, we will implement the VT capability here and leave it stealth in order to focus on improving the representation of horizontal mixing before revisiting whether VT is needed.

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
@pressel please review.

**Review by pressel — APPROVED** [review]
Thanks, @whannah1. This looks good to me!

**Comment by brhillman** [comment]
Build fails when merging to next:
```
In file included from /gpfs/fs1/home/ac.brhillman/codes/e3sm/branches/pam-variance-transport/components/eam/src/physics/crm/pam/pam_driver.cpp(16):
/gpfs/fs1/home/ac.brhillman/codes/e3sm/branches/pam-variance-transport/components/eam/src/physics/crm/pam/pam_variance_transport.h(174): error: identifier "max" is undefined
      temp_pert_scale(k,n) = max( temp_pert_scale(k,n), pert_scale_min );
```

**Comment by rljacob** [comment]
@pressel please look at above build fail.  Try merging this to next and then building locally.

**Comment by rljacob** [comment]
@whannah1 please look at above build fail. Try merging this to next and then building locally. Does this PR require #5925 ?

**Comment by rljacob** [comment]
@brhillman Is this ready?

**Comment by brhillman** [comment]
Merged to next.

**Comment by brhillman** [comment]
Merged to master.

**Pull request merged**
