### PR TITLE
Remove native_mapping functionality from files in cam/src/dynamics/se

### LINKED ISSUE #2899: Potential issue with SMS_D.ne4_ne4.FC5AV1C-L using intel19 'Attempt to use pointer ELEM when it is not associated with a target'
On Cori, I'm testing using newer versions of Intel MPI (impi) and the v19 compiler.

With `SMS_D_Ln5.ne4_ne4.FC5AV1C-L`, I see:

```
129: forrtl: severe (408): fort: (7): Attempt to use pointer ELEM when it is not associated with a target
129:
129: Image              PC                Routine            Line        Source
129: e3sm.exe           000000000BC8F186  Unknown               Unknown  Unknown
129: e3sm.exe           00000000024EC92E  dyn_comp_mp_dyn_i         189  dyn_comp.F90
129: e3sm.exe           0000000000A8C459  inital_mp_cam_ini          31  inital.F90
129: e3sm.exe           000000000083458A  cam_comp_mp_cam_i         159  cam_comp.F90
129: e3sm.exe           000000000080069F  atm_comp_mct_mp_a         312  atm_comp_mct.F90
129: e3sm.exe           000000000045B652  component_mod_mp_         257  component_mod.F90
129: e3sm.exe           000000000041C570  cime_comp_mod_mp_        1328  cime_comp_mod.F90
129: e3sm.exe           000000000045222D  MAIN__                    122  cime_driver.F90
129: e3sm.exe           000000000040A732  Unknown               Unknown  Unknown
129: e3sm.exe           000000000BD73619  Unknown               Unknown  Unknown
```

### PR DESCRIPTION
**Pull request by ndkeen**
Remove `cam/src/dynamics/se/native_mapping.F90` and 3 calls to this module in `dyn_comp.F90`.
These calls were causing some issues when run with more MPI's than elements (which Intel 19 caught in DEBUG) and rather than correcting this, it was decided this functionality is no longer needed. This code creates mapping files (SE grid to lat/lon grid) and is not used since we make mapping files with ncremap.

Fixes #2899

[bfb]

### CODE REVIEW

**Comment by AaronDonahue** [comment]
Don't you get the same problem with ELEM not being defined again in `dyn_init2` at the lines:
```
    if (inst_index == 1) then
       call write_grid_mapping(par, elem)
    end if
```

**Comment by ndkeen** [comment]
Hmm, I'm pretty sure the run completed after making this change, but I could not find my tests, so I just submitted again.

**Comment by oksanaguba** [comment]
i assume this is supposed to be bfb?

**Comment by ndkeen** [comment]
Yes, it's BFB. We were not calling the functions.

**Comment by AaronDonahue** [comment]
sorry, I thought I was adjusting my own PR.... Too many buttons, too close to each other, especially for early morning github.  I believe everything has been returned to its normal state....

**Comment by oksanaguba** [comment]
in next

**Pull request merged**
