### PR TITLE
Add new scheme SNICAR_AD for snow shortwave radiative properties

### PR DESCRIPTION
**Pull request by chengdang**
Adds a new snow shortwave radiative algorithm SNICAR_AD to land model.
This new algorithm can be selected by a new namelist variable use_snicar_ad = .true./.false.

[BFB] when use_snicar_ad = false (default)
[non-BFB] when use_snicar_ad = true

### CODE REVIEW

**Comment by bishtgautam** [comment]
@chengdang, Have you run tests to ensure your changes are BFB?

**Comment by chengdang** [comment]
@bishtgautam Thanks for the BFB test instructions. This PR changes are BFB.

**Comment by rljacob** [comment]
Re-assigning to @jqyin to balance the work for land integrators.

**Comment by rljacob** [comment]
@bishtgautam still needs a review from you.

**Comment by rljacob** [comment]
@chengdang please add  a pointer to the code review document.

**Comment by chengdang** [comment]
@bishtgautam Thank you for reviewing the code. For the first comment:

- If use_snicar_ad=.true. but use_snicar_frc=.false., the new physics will not be called. But, is there a check for such a scenario?

Actually, when use_snicar_ad = .true. and use_snicar_frc=.false., SNICAR_AD_RT will still be called. If you check the code clm/src/biogeophys/SurfaceAlbedoMod.F90,  lines 730-783, this code block is out of the if use_snicar_frc=.true. loop.

**Comment by bishtgautam** [comment]
@chengdang, Thanks for the clarification. I will approve this PR. Let me know if you want and need any help adding a test for your new physics.

**Comment by rljacob** [comment]
@jqyin don't take any more action on this PR until the code review document is approved.

**Comment by rljacob** [comment]
I see this is from a fork but the merge commit title shouldn't reflect that.  Remove "of https://github.com/chengdang/E3SM"  when you merge to master.

**Comment by chengdang** [comment]
@rljacob @jqyin @bishtgautam thank you for the help on this pull request. 

For the next step, is there anything I could do to assist the code document review? For example, is there anyone I should tag on the code review confluence page?  Also, is the deadline Jun 30th? 

Thanks!

**Comment by rljacob** [comment]
Its under Cryosphere so @stephenprice should approve.

**Pull request merged**
