### PR TITLE
Updates to sea ice bgc registry and history fields

### PR DESCRIPTION
**Pull request by njeffery**
-Corrects units/descriptions of bgc fields in registry 
-Defines column integrated and cell average bgc diagnostics 
-Updates streams build to include new diagnostics for bgc runs

[BFB]

### CODE REVIEW

**Comment by eclare108213** [comment]
@njeffery What kinds of testing have you done on these changes?  We need to confirm BFB with the current code and that all of the new fields and diagnostics have reasonable (hopefully correct) output in them.  Is there a possibility that runs with some BGC options on and other options off could have misleading or NaN output?

**Comment by njeffery** [comment]
@eclare108213 : I've done a very short 2X5 day ocean-ice with bgc+zaerosols test to verify restartability and BFB. I've also plotted the new diagnostics to verify that they're corrected.  I believe the standard checks verify bfb in the physics configuration but @jonbob can confirm. 

There is a possibility that bgc on and zaerosols off will produce Nans in some fields.  Let me fix that.

**Comment by njeffery** [comment]
@eclare108213 :  I've completed a test with zaerosols off and bgc active to verify no NaNs.

I also plotted ocean surface bgc fields and the new sea ice 2D bgc diagnostics to make sure the order of magnitudes are consistent.  All the new fields looked consistent.  Here's a couple of examples:

Sea ice Algal Carbon

[totalVerticalAlgaeCarbonIce-4.pdf](https://github.com/user-attachments/files/17155369/totalVerticalAlgaeCarbonIce-4.pdf)

Ocean surface diatom carbon

[oceanDiatomCarbon.pdf](https://github.com/user-attachments/files/17155374/oceanDiatomCarbon.pdf)


Sea ice nitrate

[totalVerticalNitrateIce.pdf](https://github.com/user-attachments/files/17155376/totalVerticalNitrateIce.pdf)

Ocean surface nitrate


[oceanNitrateSurface.pdf](https://github.com/user-attachments/files/17155378/oceanNitrateSurface.pdf)

**Review by eclare108213 — APPROVED** [review]
This PR only affects output of BGC quantities.  I am approving based on developer testing.  @jonbob will run the complete E3SM test suite to verify there are no other impacts.

**Comment by jonbob** [comment]
Passes:
* e3sm_ice_developer on chrysalis
* SMS_Ld2.ne30pg2_r05_IcoswISC30E3r5.BGCEXP_CNTL_CNPRDCTC_1850.chrysalis_intel.elm-bgcexp

merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
