### PR TITLE
Remove UNICON

### PR DESCRIPTION
**Pull request by whannah1**
This removes all code and support for the unified convection scheme (UNICON). This decision was discussed via confluence decision log. This also removes another unused feature known as "trigmem", which attempted to adjust the deep convective trigger condition to be conditioned on previous convection. The trigmem feature was poorly implemented and not documented, so it needed to be removed. 

[BFB]

### CODE REVIEW

**Comment by whannah1** [comment]
e3sm_atm_developer tests pass baseline comparison on Summit using GNU, except for SMS_R_Ld5.ne4_ne4.FSCM5A97 which fails for master on Summit. The default compiler is IBM and causes PIO build errors for all tests, so I switched to GNU for these tests.

**Comment by jayeshkrishna** [comment]
There was an issue with the IBM compiler that was fixed in Scorpio master (this change will be merged to E3SM master in a week - https://github.com/E3SM-Project/scorpio/pull/353). So if you are using the IBM compiler you can test with the latest Scorpio master (cd <E3SM_SRC_DIR>/externals/scorpio; git fetch origin; git checkout master).

**Comment by whannah1** [comment]
@jayeshkrishna - thanks for that info. I'll try to make sure to re-test with IBM, as well as intel, before this PR gets merged.

**Comment by whannah1** [comment]
@wlin7 can this get reviewed and merged now that the v2 freeze is lifted?

**Comment by rljacob** [comment]
This can proceed.

**Comment by whannah1** [comment]
@wlin7 how soon can we get this PR moving?

**Comment by rljacob** [comment]
@whannah1 did you retest as mentioned in https://github.com/E3SM-Project/E3SM/pull/3877#issuecomment-704463018

**Comment by whannah1** [comment]
@rljacob I don't think I did that, so I'll start some new tests today. That was so long ago I suppose I should rebase first.

**Comment by whannah1** [comment]
@rljacob @wlin7 @jayeshkrishna 
I rebased this branch on the current master and tried to run a test with the IBM compiler on Summit, but I got this build error about the fates submodule:
```
"/autofs/nccs-svm1_home1/hannah6/E3SM/E3SM_SRC3/components/elm/src/external_models/fates/biogeophys/FatesHydroWTFMod.F90", 1513-083 (E) Internal or module function th_sat was not set within the function.
```
This seems separate from the issue that Jayesh mentioned, but I don't have access to any other machine with the IBM compiler.  Not sure what to do next.

**Comment by jayeshkrishna** [comment]
@bishtgautam any pointers on why @whannah1 is getting the error above?

**Comment by whannah1** [comment]
@rljacob @wlin7 @jayeshkrishna This PR really has nothing to do with the land model or scorpio, so we shouldn't hold this up because of an unrelated issue with the IBM compiler.

**Comment by rljacob** [comment]
Yes that's unrelated.  This can go ahead.

**Comment by rljacob** [comment]
@wlin7 wants to look at one block

**Comment by wlin7** [comment]
Merged to next.

No actual conflicts in namelist_defaults_cam.xml (or namelist_defaults_eam.xml).
Conflicts in zm_conv.F90 are due to recent changes to tpertg as argument to the call to cldprp.

**Comment by wlin7** [comment]
> @wlin7 wants to look at one block

For record, the block is in macrop_driver.F90 that conditions on not using UNICON. @whannah1 confirmed it is safe to remove that block. Tests further confirmed this PR has no impact on simulation results with v2 code base.

**Comment by wlin7** [comment]
Merged to master.

**Pull request merged**
