### PR TITLE
Update the atmosphere model tuning and default outputs for BGC compsets

### PR DESCRIPTION
**Pull request by susburrows**
Update the atmospheric use_case files for the BGC 1850 and transient compsets by:
- Changing the clubb_c14 tuning parameter from 1.06 to 1.17 to slightly improve atmospheric radiative balance and climate.
- Using COSP_lite by default (if COSP is turned on).
- Removing specifications for non-default output variables and frequencies (this should be specified in the run_e3sm script instead).
- Updating the formatting for consistency between the two files.

[Non-BFB], [NML] for BGC compsets.

### CODE REVIEW

**Comment by susburrows** [comment]
Hi @acme-y9s ,

Thanks for checking on this!  My motivations for moving the output variable specifications from the use_case files to the runscripts are (1) to simplify the use cases, and (2) for better consistency with the practice established by the water cycle experiment.

Do you think there is a case for leaving the output variable specifications in the use case file, instead?

**Comment by susburrows** [comment]
@acme-y9s if you are ok with the changes, could you please mark this PR as "approved"?

**Comment by rljacob** [comment]
Regarding output variable specification: yes its more common to leave the defaults alone and let user's set those on a per-case basis.  Not every user of these cases will want the 3 extra atmosphere files for example.

**Comment by susburrows** [comment]
Thanks @acme-y9s !

**Comment by singhbalwinder** [comment]
merged with next

**Comment by singhbalwinder** [comment]
merged with next again.

**Pull request merged**
