### PR TITLE
Align minimum concentration and mass limits in MPAS-SeaIce

### PR DESCRIPTION
**Pull request by proteanplanet**
This changes the minimum sea ice concentration and mass per unit area used to solve the sea ice momentum equation to 10^-11 and 10^-10, respectively, aligning the concentration cutoff with the value used in sea ice column physics. The values have been reduced from 10^-3 and 10^-2, respectively.   

Testing has been completed in two categories: The branch passes the e3sm_ice_developer D-case test-suite.   However, the most important test is that this change does not cause numerical exceptions in a B-case simulation of E3SM.  Results from that simulation are provided in the comments below, successfully completed to 160+ years for the v3alpha04_trigrid configuration. This simulation deliberately includes the [bug fix switching PBOT for PSLV in the ocean coupling to the atmosphere](https://github.com/E3SM-Project/E3SM/pull/5999), because it is important to see the results of this PR on top of that change.

The impact of this change is the removal of numerical diffusion in coupling to the ocean, thus sharpening the sea ice edge, and removing "shadow" fields in low-concentration sea ice mass, heat and salt fluxes with the ocean.  This PR does not impact flux conservation between models, nor within MPAS-SeaIce

CC

### CODE REVIEW

**Comment by proteanplanet** [comment]
Improvements in the coupled fields are particularly evident in the Southern Ocean, illustrated here for the salt flux from the sea ice model to the coupler, weighted by 1/(sea ice concentration):

VSLIM_Pull_Request

This is reflected in meltwater and heat also passed to the ocean.  The main impact in the fully coupled system is evident in  Southern Ocean sea ice, summarized below for years 51-100 of the B-case simulation daily sea ice phase average (solid) and interquartile range (gray). Dotted red lines indicate the null hypothesis for days of the year that MPAS-SI with Icepack is different from the standard version of MPAS-SI at the 95% compatibility interval. Traces start on January 1, passing the northward equinox (•), northern solstice (◦), southward equinox (•), and southern solstice (◦) to the end of December (→):

E3SM_sea_ice_lemnisc 0051-0100 PSLV Icedge PI extent volume snow 3

Note above that the winter extreme sea ice extent in the Antarctic is improved relative to the 1980-2014 observations. Icedge indicates the simulation for this PR, PSLV indicates the control simulation.  There is a slight increase in the total kinetic energy of sea ice, graphed here from daily averaged values from years 51-100 of the B-case simulation, but nothing to indicate excessive ice speed:

PSLV_Icedge_KE_histogram

The impact on the climatological velocity fields is primarily a removal of slow ice speeds at the Southern Ocean ice edge, and a slight shift summer streamlines in the Beaufort Sea, noting that the summer Beaufort Sea gyre is now much improved with this and the PSLV bug fix relative to E3SM V2 simulations for years 51-100 (not shown):

PSLV_Icedge south streamline 0051_0100

PSLV_Icedge north streamline 0051_0100

Blue numbers above indicate a slight increase in the average sea ice velocity across the sea ice field relative to the PSLV control. The equivalent sea ice mass and ice edge fields are shown here:

E3SM_Sea_Ice_Thickness_antarctic_PSLV_Icedge_0051_0100

E3SM_Sea_Ice_Thickness_arctic_PSLV_Icedge_0051_0100

Above colors indicate sea ice thickness average for years 51-100, opacity indicates concentration, the blue contour indicates sea ice extent, and the observed sea ice extent is the 1979-1999 ice edge in orange ± 1 standard deviation. 

Overall, the fully coupled simulation has remained stable for its entirety relative to the control, as indicated here for years 01-150:

v3alpha04_trigrid_vslim piControl_glb

Note that sea level rise is not connected with this change, and occurs in the control case as well. Further details about this B-case simulation may be found [here](https://acme-climate.atlassian.net/wiki/spaces/CM/pages/3976396825/20231025.v3alpha04+trigrid+vslim.piControl.chrysalis).

**Review by golaz — APPROVED** [review]

**Comment by golaz** [comment]
Awesome detective work, @proteanplanet. 

We should call this PR the post-Halloween PR. The ghost has been defeated.

**Review by njeffery — APPROVED** [review]
Approved: Based on Andrew's simulations and the 80-year fully coupled test I did with puny for  the advective velocities, I see no indication of instability or excessive sea ice velocities.

**Review by eclare108213 — APPROVED** [review]
Approved based on developer testing and extensive documentation (thank you).

**Comment by proteanplanet** [comment]
This PR has been shifted to a single-commit branch and the replacement PR https://github.com/E3SM-Project/E3SM/pull/6050 has been created.  No further actions needed by reviewers.

**Pull request closed without merging**
