### PR TITLE
Add atmsrf file for ne30pg2

### PR DESCRIPTION
**Pull request by ambrad**
Add a drydep_srf_file XML entry for ne30pg2.

[BFB]

### CODE REVIEW

**Comment by ambrad** [comment]
The new ne30pg2 atmsrf file is compared with the original ne30np4 one [in this comment](https://acme-climate.atlassian.net/wiki/spaces/COM/pages/1112047753/Physgrid+v2+integration%3A+ne30pg2_r05_oECv3?focusedCommentId=1147700249#comment-1147700249).

**Comment by ambrad** [comment]
e3sm_developer passes on sandiatoss3.

**Comment by oksanaguba** [comment]
Would you please confirm that you put file on input server and add some description of this PR?

**Comment by ambrad** [comment]
@oksanaguba, you put the atmsrf file on anvil; thanks. I'll add some description.

**Comment by ambrad** [comment]
A description of how to make the atmsrf file is on [confluence](https://acme-climate.atlassian.net/wiki/spaces/COM/pages/1112047753/Physgrid+v2+integration+ne30pg2+r05+oECv3). The r5 and r7 simulations documented on that page use it.

**Comment by ambrad** [comment]
PR https://github.com/E3SM-Project/E3SM/pull/3435 combines the final v2 theta-SL-pg2 config changes into one PR.

**Pull request closed without merging**
