### PR TITLE
Update CIME to ESMCI cime5.8.2-3

### PR DESCRIPTION
**Pull request by jgfouca**
Update CIME to ESMCI cime5.8.2-3

Squash merge of jgfouca/branch-for-to-acme-2019-06-03

Features:
* Provide default for the number of create_test parallel jobs
* Nuopc cmeps removed (moved to separate repository)
* RCP cmip5 scenarios - these have been removed and replaced in datm with the SSP scenarios of cmip6

Bug fix:
* Use truncated division operator in SEQ SystemTest for py2+3 compatibility

[BFB]

### CODE REVIEW

**Comment by jgfouca** [comment]
@bishtgautam , can you approve the non-BFB datm change?

**Comment by jgfouca** [comment]
The related nml diff is:
```
Comparison failed between '/home/jgfouca/acme/scratch/ERS.f09_g16.I1850CLM45CN.melvin_gnu.clm-bgcinterface.C.20190603_170516_hs9zrk/CaseDocs/datm_in' with '/sems-data-store/ACME/baselines/gnu/master/ERS.f09_g16.I1850CLM45CN.melvin_gnu.clm-b\
gcinterface/CaseDocs/datm_in'
  BASE: streams list item 3 = 'datm.streams.txt.presaero.clim_1850 1 1 1'
  COMP: streams list item 3 = 'datm.streams.txt.presaero.clim_1850 1 1 1850'
```

**Comment by jgfouca** [comment]
Squash-merged to next.

**Comment by rljacob** [comment]
@bishtgautam this is the actual change that matters:
In datm.streams.txt.presaero.clim_1850
Inequivalent lines aerosoldep_monthly_1850_mean_1.9x2.5_c090421.nc != aerosoldep_WACCM.ensmean_monthly_hist_1849-2015_0.9x1.25_CMIP6_c180926.nc

The latter file is now being used.

**Comment by rljacob** [comment]
See https://github.com/ESMCI/cime/pull/3112

**Comment by rljacob** [comment]
@jonbob this also changes answers for 3 MPAS cases:
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST,  SMS.f09_g16_a.IGCLM45_MLI,  ERS_Ld5.T62_oQU120.CMPASO-NYF.

**Comment by jgfouca** [comment]
The dashboard will be pretty red until this is merged to master and DIFFs are blessed, so getting this approved soon would be good. If that's not possible, it should probably be reverted off of next.

**Comment by jonbob** [comment]
@rljacob - I don't think we're concerned much with answer-changes to the LISIO or CMPASO-NYF compsets (those are mostly testing configurations). But I won't claim the IGCLM45_MLI one -- that's lnd with an interface to the landice model and not something we usually work with.

**Comment by rljacob** [comment]
@jgfouca the changes you added here: https://github.com/E3SM-Project/E3SM/commit/11099cfa88777be1ef3bcded4ac4554b58447fa0  to isolate E3SM from aeorsol file updates in https://github.com/ESMCI/cime/pull/2828 have somehow been removed in this PR.  That's causing the new aerosol file to be used and making the diffs.

**Comment by rljacob** [comment]
I'm just removing my block because @bishtgautam has one.

**Comment by jgfouca** [comment]
How irritating! We somehow lost all our e3sm-specific settings. I have pushed a commit to restore them. @rljacob , @bishtgautam , can you re-review?

**Comment by jgfouca** [comment]
Did another squash merge to next.

**Comment by jgfouca** [comment]
Now that the aerosols have been fixed, this PR appears to be BFB!

**Pull request merged**
