### PR TITLE
Reinstate clubbv2

### PR DESCRIPTION
**Pull request by wlin7**
This is  to reinstate clubbv2 by reverting the previous revert of clubbv2 to clubbv1 (PR #3518).
The PR also adds clubb_c_k10h as a namelist variable to control c_K10h value at runtime.

[non-BFB]

### CODE REVIEW

**Comment by singhbalwinder** [comment]
Thanks @wlin7 . It looks good to me.

**Comment by kaizhangpnl** [comment]
@wlin7 It looks good to me too. BTW, based on our previous discussions, it would very useful to print out the tunable parameters during the model initialization. Does this PR also consider this?

**Comment by wlin7** [comment]
Thank you @kaizhangpnl and @singhbalwinder for the quick review.

> @wlin7 It looks good to me too. BTW, based on our previous discussions, it would very useful to print out the tunable parameters during the model initialization. Does this PR also consider this?

Yes, this part of codes are carried over during the back and forth.

**Comment by golaz** [comment]
@wuyin: I'm waiting for my AMIP simulation to be complete before signing off on this. When I configured the model, I did notice that the default value of  clubb_c_K10h was 1.0 so I had to add

` clubb_c_K10h = 0.30`

in user_nl_cam. Can we change the default to be 0.30 for all relevant compsets?

**Comment by wlin7** [comment]
Very true, @golaz. Currently a tuned value for clubb_c_k10h has to go with user_nl_cam. I am going to add to this PR for all use_case files that use a non-default clubb_c_K10, and make clubb_c_k10h=clubb_c_k10 for those compsets.

**Comment by wlin7** [comment]
Hi @singhbalwinder abd @kaizhangpnl , just to let you know I made further changes since your last review. Following Chris's suggestion, clubb_c_K10h will be set automatically after this PR and clubb_c_K10h == clubb_c_K10 are ensured for all use_cases that involve a tuning of c_K10 away from default.  

FYI: The new changes are done automatically using a script on cori, ~wlin/bin/txtscan_c_k10.pl. If you got a chance, you may review the modified use_case files or just how the script works. Thanks.

**Comment by wlin7** [comment]
Merged to next. 

Note that after resolving conflicts in advance_clubb_core_module.F90 as marked by git-merge, it is restored to the exact version of previous clubbv2 as in branch v2alpha-clubbv2. The part of conflicted codes that are in the next before merging exist in clubbv1 but not in clubbv2. The changes are introduced by clubbv2; but no conflict emerge when initially merging clubbv2 (#2897). When reverting to clubbv1, git also reports conflicts on this file.

**Comment by wlin7** [comment]
Merged to master. 

Request submitted to bless diffs for integration next tests on melvin (11), compy(37), sandiatoss3 (46).

**Comment by wlin7** [comment]
The state of master before this PR is saved in branch v2alpha-clubbv1-062620.

**Pull request merged**
