### PR TITLE
Update MPAS-Source: COMPASS and Documentation files

### PR DESCRIPTION
**Pull request by mark-petersen**
This PR updates files unrelated to the E3SM forward model. This includes:
- Move load_compass_env.sh to the ocean dir https://github.com/MPAS-Dev/MPAS-Model/pull/618
- Update ISOMIP+ docs, including tutorial for Ocean0 on LANL IC https://github.com/MPAS-Dev/MPAS-Model/pull/653
- Fix path to docs in Travis CI https://github.com/MPAS-Dev/MPAS-Model/pull/644 (from develop branch)
- atmosphere core init changes https://github.com/MPAS-Dev/MPAS-Model/pull/637 (from develop branch)
- New Mesh: WC14to60kmL60E3SMv2r03 https://github.com/MPAS-Dev/MPAS-Model/pull/628
- Fix ISOMIP+ viz scripts https://github.com/MPAS-Dev/MPAS-Model/pull/642
- Add support for custom critical passages and land blockages https://github.com/MPAS-Dev/MPAS-Model/pull/586
- New Mesh: WC12to60kmL60E3SMv2r01 https://github.com/MPAS-Dev/MPAS-Model/pull/555

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
@matthewhoffman and @akturner this includes a merge from develop in order to get a Travis CI correction in from @xylar's work. It came with an atmosphere change. You can merge the `develop` branch into your cores whenever. Those two changes are never even compiled for our work.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
Passes SMS_D.ne4_oQU240.A_WCYCL1850.anvil_intel sanity test

**Comment by matthewhoffman** [comment]
@mark-petersen , thanks for the head's up.  I'm ok with the src changes because they are only in the atm init code, which E3SM never uses.  I'll plan to merge develop into landice/develop when this is complete.

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
