### PR TITLE
Add machines muller-cpu/muller-gpu as NERSC internal testing machines similar to pm-cpu/pm-gpu

### PR DESCRIPTION
**Pull request by ndkeen**
Initial add of 2 machines that are similar to perlmutter -- muller-gpu =~ pm-gpu, muller-cpu =~ pm-cpu.
I can use these machines to test software stack changes before we use them on permutter.
Only handful of nodes on each.

Also, for one conus test (only tested in scream), I reduced the number of nodes needed for pm-gpu/muller-gpu.

[BFB]

### CODE REVIEW

**Comment by ndkeen** [comment]
Note that I'm testing newer module versions on muller. This PR should yield same config as current pm-cpu/pm-gpu.
I left XML comments to make it easier to switch to the newer module versions. I wanted to do that in a separate PR as there is at least one issue that may take some debugging.

**Review by rljacob — APPROVED** [review]

**Comment by ndkeen** [comment]
Now it says "This branch has conflicts that must be resolved". Does that mean I can't try to merge with next?

**Comment by rljacob** [comment]
No.  Just resolve the conflicts.

**Comment by ndkeen** [comment]
merged to next

**Comment by ndkeen** [comment]
As expected, no problems with tests, merging to master

**Pull request merged**
