### PR TITLE
Fix index in surface area weighted AM in maint-1.2

### LINKED ISSUE #2781: index in ocean surface area weighted AM is incorrect
Index in the ocean surface area weighted AM, which means that surface variables in MPAS-Analysis show the wrong variable, specifically SSH.

### PR DESCRIPTION
**Pull request by mark-petersen**
Fixes indexing issue in ocean SurfaceAreaWeighted AM.  It is bfb in the simulations.  Output file for one ocean analysis member will change.

bfb
fixes #2781

### CODE REVIEW

**Comment by mark-petersen** [comment]
@matthewhoffman @jonbob @xylar  @darincomeau 
I think it's worth making PRs for E3SM into maintenance branches to see each difference and document the change.  Thanks @matthewhoffman for preparing the mpas commits. I think you can approve by visual inspection.

**Comment by jonbob** [comment]
@mark-petersen - giving a PR a bug label means there should be a corresponding bug to fix (and issue number). Did you create one for this problem?

**Comment by rljacob** [comment]
Yes changes to maint branches should be done by PR just like master.

**Comment by mark-petersen** [comment]
Tested this set on this commit:
```
PASS SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu RUN 
PASS SMS_D_Ln9.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel RUN 
```
For these small changes, I think testing E3SM using debug and two compilers is sufficient.

**Comment by jonbob** [comment]
merged to maint-1.2

**Pull request merged**
