### PR TITLE
Use our own version of RRTMGP file i/o routine

### LINKED ISSUE #2917: ERS_Ld5.ne4_ne4.FC5AV1C-L.theta_intel.cam-rrtmgp failing on theta nightly
In e3sm log:
load_and_init(): can't open file /projects/ccsm/acme/inputdata/atm/cam/rad/rrtm
 gp_coefficients_sw_c181004.nc

File exists and is readable:
ncdump -k /projects/ccsm/acme/inputdata/atm/cam/rad/rrtmgp_coefficients_sw_c181004.nc
classic

### PR DESCRIPTION
**Pull request by brhillman**
Create our own version of the RRTMGP example code to read the absorption coefficient data from file. This will be needed for creating an MPI-aware version of this routine (to read the data only once rather than from each rank). This also fixes #2917 by opening files with mode `NF90_NOWRITE` rather than `NF90_WRITE`.

Fixes #2917 

[BFB]

### CODE REVIEW

**Comment by brhillman** [comment]
Note that this *looks* like a lot of code changed, because I brought in a copy of the read routine from components/cam/src/physics/rrtmgp/external/examples, but the routine itself differs only in the line that opens the file (you can checkout the submodule and do a diff of `rrtmgp_coefficients.F90` and `mo_load_coefficients.F90` to see this).

**Comment by rljacob** [comment]
@brhillman was there a particular thing you wanted @sarich to review?

**Comment by brhillman** [comment]
@rljacob not really, he was just the individual who opened the issue this fixes.

**Comment by rljacob** [comment]
Ok then @singhbalwinder you can merge this.

**Comment by singhbalwinder** [comment]
Merged to next

**Pull request merged**
