### PR TITLE
update compatibility with FATES API 6.0.0

### PR DESCRIPTION
**Pull request by rgknox**
This changeset bring E3SM compatibility up to the most recent FATES API 6.0.0.  
This change enables the switching of different plant allocation modules "fates_parteh_mode"
in the namelist file.  This change also added a call in the interface to accomodate preprocessing
some extra information needed to correctly restart the radiation environment.

[non-BFB]

### CODE REVIEW

**Comment by rgknox** [comment]
This PR was tested with e3sm_land_developer, all PASS, cori-knl.
This PR should be B4B with all non-fates tests.  
This PR should not be B4B with any FATES active tests.

**Comment by rgknox** [comment]
This PR also adds a new default fates_paramfile, this has been loaded to the lcrc dataserver (thanks @bishtgautam )

**Comment by rgknox** [comment]
Updated the submodule to point to NGEET/fates.git instead of NGEET/fates-release.git.  NGEET/fates.git is now public.  
@rljacob

**Comment by rljacob** [comment]
Does this version remove use of DEBUG as a Fortran variable?

**Comment by rgknox** [comment]
We did change all debug flags in fates to lowercase.   Does that work?

**Comment by rljacob** [comment]
Yes it does.  Thanks.

**Pull request merged**
