### PR TITLE
SAM++ bug fix

### PR DESCRIPTION
**Pull request by whannah1**
This branch pulls in fixes developed on the INCITE2020 branch. The main fix involves an index/memory error in the C++ scalar diffusion code, which is not present in the SAM fortran code. Other miscellaneous updates include: 
- changes to floating point literal precision
- increase perturbation magnitude in setperturb.cpp
- change max ncycle = 4 in kurant()for both Fortran and C++
- fix aqua planet compset for MMF w/ SAM++
- fix bug in crm_clear_rh variable

[non-BFB] (for MMF tests only)

### CODE REVIEW

**Review by xyuan — APPROVED** [review]
These changes sound good to me

**Review by mrnorman — APPROVED** [review]
Looks good

**Comment by brhillman** [comment]
Results from the MMF suite:
```
FAIL ERS_Ln9_P32x1.ne4pg2_ne4pg2.F-MMF2-ECPP.mappy_gnu (phase MODEL_BUILD)
FAIL SMS_D_Ln3_P32x1.ne4pg2_ne4pg2.F-MMF2.mappy_gnu (phase RUN)
DIFF ERS_Ln9_P32x1.ne4pg2_ne4pg2.F-MMF2.mappy_gnu (phase RUN)
DIFF ERS_Ln9_P32x1.ne4pg2_ne4pg2.F-MMF1.mappy_gnu.eam-crmout (phase RUN)
DIFF ERS_Ln9_P32x1.ne4pg2_ne4pg2.F-MMFXX.mappy_gnu (phase RUN)
PASS ERP_Ln9_P32.ne4pg2_ne4pg2.FC5AV1C-L.mappy_gnu.eam-rrtmgp RUN
DIFF SMS_D_Ln3_P32x1.ne4pg2_ne4pg2.F-MMF1.mappy_gnu (phase RUN)
```

**Comment by whannah1** [comment]
@brhillman those failing tests also fail with master?

**Comment by brhillman** [comment]
@whannah1 yes I believe so, just posting here for reference.

**Comment by brhillman** [comment]
Merged to next.

**Comment by brhillman** [comment]
Merged to master.

**Pull request merged**
