### PR TITLE
Fixes ELM map generation scripts

### PR DESCRIPTION
**Pull request by bishtgautam**
- The script that lists all the maps needed for creating a new ELM surface dataset
  is fixed to account for the name change of the land model to ELM
- ELM tools directory is reorganized by moving all tools from `clm4_5` and `shared`
  directory to one-level up. The old directory structure was inherited from CESM
  in which tools supported two models (`clm4_0` and `clm4_5`) with a common
  `shared` directory.

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
Why is this a WIP ?

**Comment by peterdschwartz** [comment]
Will there be anymore changes for this PR?

**Comment by rljacob** [comment]
@bishtgautam is this ready?

**Comment by bishtgautam** [comment]
This is ready to go.

**Review by peterdschwartz — APPROVED** [review]

**Comment by peterdschwartz** [comment]
passed all e3sm_developer tests on chrysalis and merged to next.

**Pull request merged**
