### PR TITLE
removing sqs command for cori which was introduced by PR #3679

### PR DESCRIPTION
**Pull request by bibiraju**
Removing sqs command for cori which was introduced by PR #3679. This is due the merge conflicts with PR #3704 

Only affects Cori.

[BFB]

### CODE REVIEW

**Comment by ndkeen** [comment]
Hmm, I thought I already merged this change into maint-1.0 here:
https://github.com/E3SM-Project/E3SM/pull/3704

**Comment by bibiraju** [comment]
@ndkeen But the sqs command was re-introduced with this PR #3679. I noticed it only after merging it. So created this one.

**Comment by ndkeen** [comment]
Re-introduced?  By mistake?

**Comment by bibiraju** [comment]
@ndkeen PR #3679 introduced one more occurrence of sqs command in two files. This below line was introduced by PR #3679 which was created before #3704 but merged only after 3704 was merged.
`set nnodes = `sqs -f $jid | grep -F NumNodes | sed 's/ *NumNodes=\([0-9]*\) .*/\1/' ` `

The above line is new code from #3679 and uses sqs command in it. PR #3704 removed other occurrences of sqs but this.

**Comment by ndkeen** [comment]
@bibiraju I would think the right thing to do is revert the change where this happened.

**Comment by bibiraju** [comment]
ok. I will wait for @worleyph as he is the author of the original PR.

**Comment by rljacob** [comment]
@ndkeen no just merge this PR.

**Comment by worleyph** [comment]
@ndkeen , please go ahead and merge this PR.

**Comment by rljacob** [comment]
The maint-1.0 test suite is running fine even though this PR hasn't been merged.  Did NERSC put the sqs command back?

**Comment by ndkeen** [comment]
I just haven't had time to do this -- I wanted to at least run a test.
But, I also noticed that cdash was reporting OK so assumed it wasn't high priority.
I think the sqs command that was in provenance.py *was* changed and allows jobs to run.
However, currently, jobs without this PR would not save info about other jobs on the system which gets saved to perf data.

**Comment by rljacob** [comment]
@ndkeen please finish this PR.

**Pull request merged**
