### PR TITLE
Implementation to use cosp2 as a submodule

### PR DESCRIPTION
**Pull request by wlin7**
COSP2 is introduced as a replacement for the existing COSP.
The core cosp2 simulator codes are imported as a submodule from
git@github.com:CFMIP/COSPv2.0.git. Its branch of CESM_v2.1.4 is
currently used. The interface module for cosp as well as the supporting
cosp modules that depend on a model's physical parameterization (e.g.,
species considered in cloud microphysical parameterization) are
implemented in E3SM repository.
    
MODIS simulator is currently turned off because of a known issue yet to
be resolved. COSP1 codes are removed entirely.
    
[BFB] except for COSP diagnostics

### CODE REVIEW

**Comment by wlin7** [comment]
Notes: This PR is to replace PR #3415 with cosp2 to be imported as a submodule. 
It is using branch CESM_v2.1.4 of the COSPv2 repository. This branch is the same as the tag v2.1.4cesm used in recently released cesm-2.1.2. The core cosp simulator codes contain two new simulator interface modules compared to those in #3415. The main cosp interface module, cospsimulator_intr.F90 still needs to be updated to work with the simulators in v2.1.4.

**Comment by rljacob** [comment]
Looks like you're going to keep the existing cosp?

**Comment by wlin7** [comment]
@rljacob , cosp1 is now removed entirely. @zyuying is actively debugging a hidden issue with MODIS simulator in cosp2. She said she could do that without using cosp1 as a reference. We could still merge this PR but temporarily disable MODIS.

**Comment by golaz** [comment]
@wlin7 and @zyuying : should we go ahead and merge? And then resolve the MODIS issue later?

Need review from @singhbalwinder

**Comment by wlin7** [comment]
@golaz , yes, I am thinking to merge it today with modis off. @zyuying and I went thru several rounds of reviews and testings. The PR should be safe. I am asking @singhbalwinder to take a quick review.

**Comment by wlin7** [comment]
Merged to next. Nightly cosp tests are expected to DIFF.

**Comment by wlin7** [comment]
cdash reported SMS_D_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel.cam-cosplite_nhtfrq5 failed as an experimental test on anvil. The standalone cosp2 tests that are all done on cori-knl didn't have this issue.

```
severe (408): fort: (8): Attempt to fetch from allocatable variable SD_CS when it is not allocated
  6:
  6: Image              PC                Routine            Line        Source
  6: e3sm.exe           000000000B6F8E36  Unknown               Unknown  Unknown
  6: e3sm.exe           000000000225FFC9  cospsimulator_int        2099  cospsimulator_intr.F90
  6: e3sm.exe           000000000134F8B9  radiation_mp_radi        1572  radiation.F90
  6: e3sm.exe           0000000002742CE6  physpkg_mp_tphysb        2767  physpkg.F90
  6: e3sm.exe           000000000270CFA1  physpkg_mp_phys_r        1047  physpkg.F90
  6: e3sm.exe           0000000000856CE6  cam_comp_mp_cam_r         250  cam_comp.F90

```
Investigating ...

**Comment by wlin7** [comment]
The affected allocatable variable SD_CS is only allocated if doing radar simulator, and is supposed to only be used in that case (lradar_sim = .true.). The failed nightly test has cosp_lite = .true., which does not turn on radar simulator.

**Comment by wlin7** [comment]
The failure of cam-cosplite_nhtfrq5 test is now fix (see #3482). The fix is included in this PR and pushed to next.

**Comment by wlin7** [comment]
Merged to master.

Request submitted to bless diffs of  
SMS_D_Ln5.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.cam-cosplite_nhtfrq5
SMS_D_Ln5.ne4_ne4.FC5AV1C-L.compy_pgi.cam-cosplite_nhtfrq5

But the following tests didn't report a diff. At least cam-cosplite_nhtfrq5 is expected to diff: new version of simulators, and modis is currently disabled. Keeping an eye on in the next fews days.

SMS_D_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel.cam-cosplite_nhtfrq5
SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-cosplite
SMS.ne4_ne4.FC5AV1C-L.melvin_gnu.cam-cosplite
SMS.ne4_ne4.FC5AV1C-L.cori-haswell_intel.cam-cosplite
SMS.ne4_ne4.FC5AV1C-L.bebop_intel.cam-cosplite
SMS.ne4_ne4.FC5AV1C-L.bebop_intel.cam-cosplite_nhtfrq5

**Comment by amametjanov** [comment]
Just a note that this affects throughput by ~20% in low-res fully-coupled test runs:
Cori-KNL, next
```
> zgrep "model date" cpl.log.28704477.200310-204438.gz
 tStamp_write: model date =   00010102       0 wall clock = 2020-03-10 20:51:53 avg dt =   217.03 dt =   217.03
 memory_write: model date =   00010102       0 memory =    3492.00 MB (highwater)        988.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 tStamp_write: model date =   00010103       0 wall clock = 2020-03-10 20:55:28 avg dt =   215.92 dt =   214.81
 memory_write: model date =   00010103       0 memory =    3496.00 MB (highwater)        991.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
```
Cori-KNL, baseline
```
> zgrep "model date" /global/cfs/cdirs/acme/baselines/intel/master/SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.cori-knl_intel.allactive-v1cmip6/cpl.log.gz
 tStamp_write: model date =   00010102       0 wall clock = 2020-02-11 20:26:07 avg dt =   172.34 dt =   172.34
 memory_write: model date =   00010102       0 memory =    3400.00 MB (highwater)        933.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 tStamp_write: model date =   00010103       0 wall clock = 2020-02-11 20:29:25 avg dt =   185.18 dt =   198.03
 memory_write: model date =   00010103       0 memory =    3416.00 MB (highwater)        938.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
```

Anvil, next
```
$ zgrep "model date" cpl.log.144564.200310-185530.gz
 tStamp_write: model date =   00010102       0 wall clock = 2020-03-10 19:00:03 avg dt =    86.60 dt =    86.60
 memory_write: model date =   00010102       0 memory =    2477.00 MB (highwater)       1565.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 tStamp_write: model date =   00010103       0 wall clock = 2020-03-10 19:01:25 avg dt =    84.15 dt =    81.69
 memory_write: model date =   00010103       0 memory =    2477.00 MB (highwater)       1565.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
```
Anvil, baseline
```
$ zgrep "model date" /lcrc/group/acme/acme_baselines/intel/master/SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.anvil_intel.allactive-v1cmip6/cpl.log.gz
 tStamp_write: model date =   00010102       0 wall clock = 2020-01-26 18:59:19 avg dt =    71.57 dt =    71.57
 memory_write: model date =   00010102       0 memory =    2430.00 MB (highwater)       1508.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 tStamp_write: model date =   00010103       0 wall clock = 2020-01-26 19:00:32 avg dt =    71.91 dt =    72.25
 memory_write: model date =   00010103       0 memory =    2430.00 MB (highwater)       1508.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
```

**Comment by golaz** [comment]
@amametjanov : thanks for reporting this.

@wlin7 and @zyuying : do you know if this is expected? Do we still only have COSP lite turned on?

**Comment by ambrad** [comment]
Would this show up in the `CPL:COMM` timer?

**Comment by amametjanov** [comment]
No, `CPL:COMM` is mostly MPI messaging.
Looking at `a:cosp_run` the slow-down is ~11x on Anvil.
`next` from 2020-02-15:
```
name                                            on  processes  threads        count      walltotal   wallmax (proc   thrd  )   wallmin (proc   thrd  )
"a:cosp_run"                                     -       1350     1350 6.480000e+04   1.632074e+03     1.582 (     2      0)     0.937 (  1089      0)
```
`next` from 2020-03-10:
```
name                                            on  processes  threads        count      walltotal   wallmax (proc   thrd  )   wallmin (proc   thrd  )
"a:cosp_run"                                     -       1350     1350 6.480000e+04   1.813649e+04    19.555 (  1331      0)     3.589 (  1337      0)
```

**Comment by golaz** [comment]
In my slow simulation, I'm also seeing what looks like a memory leak:

```
cd /compyfs/gola749/E3SM_simulations/20200310.alpha22.piControl.ne30pg2_r05_oECv3_ICG.compy/run
gunzip -c cpl.log.82331.200310-182454.gz | grep highwater | less
memory_write: model date =   00010102       0 memory =    5503.00 MB (highwater)        956.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
memory_write: model date =   00010103       0 memory =    5503.00 MB (highwater)        959.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
memory_write: model date =   00010104       0 memory =    5503.00 MB (highwater)        960.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
memory_write: model date =   00010105       0 memory =    5503.00 MB (highwater)        960.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
[...skipping to the end...]
memory_write: model date =   00060130       0 memory =    5879.00 MB (highwater)       1338.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
memory_write: model date =   00060131       0 memory =    5879.00 MB (highwater)       1338.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
memory_write: model date =   00060201       0 memory =    5893.00 MB (highwater)       1353.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
memory_write: model date =   00060202       0 memory =    5893.00 MB (highwater)       1353.00 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
```

**Comment by golaz** [comment]
I've started a new simulation identical to alpha22.piControl but with a code base just prior to COSP2. The model is running more than **twice as fast**. Maybe there are other issues as play (machine?), but COSP2 is almost undoubtedly a big factor:

```
cd /compyfs/gola749/E3SM_simulations/20200310_xCOSP2.alpha22.piControl.ne30pg2_r05_oECv3_ICG.compy/run
grep 'avg dt' cpl.log.82533.200312-005820
[...]
 tStamp_write: model date =   00060216       0 wall clock = 2020-03-12 07:27:19 avg dt =    12.36 dt =    10.74
 tStamp_write: model date =   00060217       0 wall clock = 2020-03-12 07:27:30 avg dt =    12.36 dt =    11.21
 tStamp_write: model date =   00060218       0 wall clock = 2020-03-12 07:27:41 avg dt =    12.36 dt =    10.85
 tStamp_write: model date =   00060219       0 wall clock = 2020-03-12 07:27:52 avg dt =    12.36 dt =    11.54
```

**Comment by wlin7** [comment]
@golaz , this is unexpected. Thanks @amametjanov for checking on the performance. We are going to investigate, together with the cosp2 developer. If no quick fix, this PR will be reverted.

**Comment by rljacob** [comment]
Did our testing not flag that slowdown?

**Comment by wlin7** [comment]
Would be nice to have a flag like that, Rob. The time column in the cdash report appears to be not reliable. Some timer stats as Az shown in the log file could be used.

Back to the slowdown: The test (allactive one) is using cosp_lite. However, in cosp2, another simulator is turned on for cosp_lite. It is PARASOL which is a simulator of Polarization and Anisotrophy Reflectances (for a lidar based monodirectional reflectance). I will check if this additional simulator account for the 11x slowdown and we can decide if we want this simulator in cosp_lite.

**Comment by wlin7** [comment]
A series of 10-day FC5AV1C-L.ne30_oECv3.cosplite simulations on anvil does show cosp2 is 2x as expensive as cosp1. 

In terms of ratio of cost, cosp2 is 2.1% of total time, while cosp1 is 1.1% of total.

> name                                     on  processes  threads        count      walltotal   wallmax (proc   thrd  )   wallmin (proc   thrd  )
> "a:cosp_run"                              -        144      144 2.534400e+05   5.496951e+03    39.686 (    13      0)    36.693 (    34      0)
> 
> "a:cosp_run"                              -        144      144 2.534400e+05   5.496951e+03    39.686 (    13      0)    36.693 (    34      0)
> 

System is stable during the tests as repeated runs takes nearly identical time. The extra PARASOL simulator in cosp2 does not add significant cost.

**Comment by wlin7** [comment]
Request to bless SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.anvil_intel.allactive-v1cmip6

Test results following the merge of #3508 will be used to bless. History files unchanged with the merge of #3508.

**Pull request merged**
