### PR TITLE
Fix split-explicit upwinded advection

### PR DESCRIPTION
**Pull request by cbegeman**
This PR introduces a new variable to track the baroclinic water column thickness for the barotropic subcycles. The method of storing the baroclinic water column thickness in a `bottomDepthEdge` variable was problematic for upwinding because the upwinded cell can change between the baroclinic cycle and the barotropic subcycle. We now store the baroclinic (upwinded or centered) water column thickness at edges and then apply it along with the barotropic  (upwinded or centered) ssh on edges to determine the barotropic water column thickness at edges.

Fixes https://github.com/E3SM-Project/E3SM/issues/6048
[BFB]

### CODE REVIEW

**Comment by cbegeman** [comment]
### Testing

This PR introduces machine-precision-level changes in the tests included in the compass PR suite, which was run on Chrysalis with intel, openmpi.

This PR was tested with upwinding on for the `drying_slope` compass test cases and produces visually-similar solutions to centered advection.

**Comment by mark-petersen** [comment]
Tested with gnu on chrysalis with both debug and optimized. Passes nightly suite with default flags and matches master bfb as expected. I also added these flags to compass:
```
+++ b/compass/ocean/tests/baroclinic_channel/namelist.forward
+config_thickness_flux_type = 'upwind'

+++ b/compass/ocean/tests/global_ocean/namelist.forward
+config_thickness_flux_type = 'upwind'
```
and this branch passes nightly suite with both gnu debug and optimized. When I compare to master using upwind, I get small differences, as expected:
<details>
<summary> diffs: </summary> <p>

```
pwd
/lcrc/group/e3sm/ac.mpetersen/scratch/runs/n/ocean_model_231116_15fa673c_ch_gfortran_openmp_debug_prUpWind
(base) chr:ocean_model_231116_15fa673c_ch_gfortran_openmp_debug_prUpWind$ grep '0:  l1:' case_outputs/*log -B 1
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log-temperature          Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log:0:  l1: 7.04032014908762e-08  l2: 2.04893843089280e-09  linf: 1.68753899743024e-10
--
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log-salinity             Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log:0:  l1: 1.59303681357414e-11  l2: 3.36440297182654e-13  linf: 7.10542735760100e-15
--
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log-layerThickness       Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log:0:  l1: 8.95675417922348e-06  l2: 1.62869065719156e-07  linf: 6.85603396277656e-09
--
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log-normalVelocity       Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log:0:  l1: 5.87778593955053e-05  l2: 7.34835507954668e-07  linf: 2.49943974198197e-08
--
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log-temperature          Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log:0:  l1: 7.04032014908762e-08  l2: 2.04893843089280e-09  linf: 1.68753899743024e-10
--
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log-salinity             Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log:0:  l1: 1.59303681357414e-11  l2: 3.36440297182654e-13  linf: 7.10542735760100e-15
--
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log-layerThickness       Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log:0:  l1: 8.95675417922348e-06  l2: 1.62869065719156e-07  linf: 6.85603396277656e-09
--
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log-normalVelocity       Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_decomp_test.log:0:  l1: 5.87778593955053e-05  l2: 7.34835507954668e-07  linf: 2.49943974198197e-08
--
case_outputs/ocean_baroclinic_channel_10km_default.log-temperature          Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_default.log:0:  l1: 7.04032014908762e-08  l2: 2.04893843089280e-09  linf: 1.68753899743024e-10
--
case_outputs/ocean_baroclinic_channel_10km_default.log-salinity             Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_default.log:0:  l1: 1.59303681357414e-11  l2: 3.36440297182654e-13  linf: 7.10542735760100e-15
--
case_outputs/ocean_baroclinic_channel_10km_default.log-layerThickness       Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_default.log:0:  l1: 8.95675417922348e-06  l2: 1.62869065719156e-07  linf: 6.85603396277656e-09
--
case_outputs/ocean_baroclinic_channel_10km_default.log-normalVelocity       Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_default.log:0:  l1: 5.87778593955053e-05  l2: 7.34835507954668e-07  linf: 2.49943974198197e-08
--
case_outputs/ocean_baroclinic_channel_10km_restart_test.log-temperature          Time index: 0
case_outputs/ocean_baroclinic_channel_10km_restart_test.log:0:  l1: 2.91517451955770e-07  l2: 7.47537460008951e-09  linf: 5.89929882721663e-10
--
case_outputs/ocean_baroclinic_channel_10km_restart_test.log-salinity             Time index: 0
case_outputs/ocean_baroclinic_channel_10km_restart_test.log:0:  l1: 2.85638179775560e-11  l2: 4.72497563025237e-13  linf: 1.42108547152020e-14
--
case_outputs/ocean_baroclinic_channel_10km_restart_test.log-layerThickness       Time index: 0
case_outputs/ocean_baroclinic_channel_10km_restart_test.log:0:  l1: 2.68098525708638e-05  l2: 4.42096788923310e-07  linf: 1.88044992910363e-08
--
case_outputs/ocean_baroclinic_channel_10km_restart_test.log-normalVelocity       Time index: 0
case_outputs/ocean_baroclinic_channel_10km_restart_test.log:0:  l1: 1.93993060053623e-04  l2: 2.25308228213117e-06  linf: 7.30093800901943e-08
--
case_outputs/ocean_baroclinic_channel_10km_restart_test.log-temperature          Time index: 0
case_outputs/ocean_baroclinic_channel_10km_restart_test.log:0:  l1: 2.91517451955770e-07  l2: 7.47537460008951e-09  linf: 5.89929882721663e-10
--
case_outputs/ocean_baroclinic_channel_10km_restart_test.log-salinity             Time index: 0
case_outputs/ocean_baroclinic_channel_10km_restart_test.log:0:  l1: 2.85638179775560e-11  l2: 4.72497563025237e-13  linf: 1.42108547152020e-14
--
case_outputs/ocean_baroclinic_channel_10km_restart_test.log-layerThickness       Time index: 0
case_outputs/ocean_baroclinic_channel_10km_restart_test.log:0:  l1: 2.68098525708638e-05  l2: 4.42096788923310e-07  linf: 1.88044992910363e-08
--
case_outputs/ocean_baroclinic_channel_10km_restart_test.log-normalVelocity       Time index: 0
case_outputs/ocean_baroclinic_channel_10km_restart_test.log:0:  l1: 1.93993060053623e-04  l2: 2.25308228213117e-06  linf: 7.30093800901943e-08
--
case_outputs/ocean_baroclinic_channel_10km_threads_test.log-temperature          Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_threads_test.log:0:  l1: 7.04032014908762e-08  l2: 2.04893843089280e-09  linf: 1.68753899743024e-10
--
case_outputs/ocean_baroclinic_channel_10km_threads_test.log-salinity             Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_threads_test.log:0:  l1: 1.59303681357414e-11  l2: 3.36440297182654e-13  linf: 7.10542735760100e-15
--
case_outputs/ocean_baroclinic_channel_10km_threads_test.log-layerThickness       Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_threads_test.log:0:  l1: 8.95675417922348e-06  l2: 1.62869065719156e-07  linf: 6.85603396277656e-09
--
case_outputs/ocean_baroclinic_channel_10km_threads_test.log-normalVelocity       Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_threads_test.log:0:  l1: 5.87778593955053e-05  l2: 7.34835507954668e-07  linf: 2.49943974198197e-08
--
case_outputs/ocean_baroclinic_channel_10km_threads_test.log-temperature          Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_threads_test.log:0:  l1: 7.04032014908762e-08  l2: 2.04893843089280e-09  linf: 1.68753899743024e-10
--
case_outputs/ocean_baroclinic_channel_10km_threads_test.log-salinity             Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_threads_test.log:0:  l1: 1.59303681357414e-11  l2: 3.36440297182654e-13  linf: 7.10542735760100e-15
--
case_outputs/ocean_baroclinic_channel_10km_threads_test.log-layerThickness       Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_threads_test.log:0:  l1: 8.95675417922348e-06  l2: 1.62869065719156e-07  linf: 6.85603396277656e-09
--
case_outputs/ocean_baroclinic_channel_10km_threads_test.log-normalVelocity       Time index: 0, 1, 2
case_outputs/ocean_baroclinic_channel_10km_threads_test.log:0:  l1: 5.87778593955053e-05  l2: 7.34835507954668e-07  linf: 2.49943974198197e-08
--
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log-temperature          Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log:0:  l1: 2.75566436533036e-04  l2: 8.29606292738649e-06  linf: 1.94863980240711e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log-salinity             Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log:0:  l1: 8.71703693121617e-05  l2: 5.00682857997115e-06  linf: 2.16146819553842e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log-layerThickness       Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log:0:  l1: 3.97078916161941e-03  l2: 7.88601350610143e-05  linf: 1.83480870177277e-05
--
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log-normalVelocity       Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log:0:  l1: 8.70422701970631e-03  l2: 1.04291407480119e-04  linf: 8.65663152778418e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log-avgVolumeTemperature Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log:0:  l1: 2.53352783197158e-10  l2: 2.35319629935320e-10  linf: 2.34927632902782e-10
--
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log-avgVolumeRelativeVorticityCell Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log:0:  l1: 1.04784253496806e-14  l2: 8.16719556230606e-15  linf: 8.10040422341353e-15
--
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log-temperature          Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log:0:  l1: 2.75566436533036e-04  l2: 8.29606292738649e-06  linf: 1.94863980240711e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log-salinity             Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log:0:  l1: 8.71703693121617e-05  l2: 5.00682857997115e-06  linf: 2.16146819553842e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log-layerThickness       Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log:0:  l1: 3.97078916161941e-03  l2: 7.88601350610143e-05  linf: 1.83480870177277e-05
--
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log-normalVelocity       Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_analysis_test.log:0:  l1: 8.70422701970631e-03  l2: 1.04291407480119e-04  linf: 8.65663152778418e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log-temperature          Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log:0:  l1: 2.75566436533036e-04  l2: 8.29606292738649e-06  linf: 1.94863980240711e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log-salinity             Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log:0:  l1: 8.71703693121617e-05  l2: 5.00682857997115e-06  linf: 2.16146819553842e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log-layerThickness       Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log:0:  l1: 3.97078916161941e-03  l2: 7.88601350610143e-05  linf: 1.83480870177277e-05
--
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log-normalVelocity       Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log:0:  l1: 8.70422701970631e-03  l2: 1.04291407480119e-04  linf: 8.65663152778418e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log-temperature          Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log:0:  l1: 2.75566436533036e-04  l2: 8.29606292738649e-06  linf: 1.94863980240711e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log-salinity             Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log:0:  l1: 8.71703693121617e-05  l2: 5.00682857997115e-06  linf: 2.16146819553842e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log-layerThickness       Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log:0:  l1: 3.97078916161941e-03  l2: 7.88601350610143e-05  linf: 1.83480870177277e-05
--
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log-normalVelocity       Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_decomp_test.log:0:  l1: 8.70422701970631e-03  l2: 1.04291407480119e-04  linf: 8.65663152778418e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_performance_test.log-temperature          Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_performance_test.log:0:  l1: 2.75566436533036e-04  l2: 8.29606292738649e-06  linf: 1.94863980240711e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_performance_test.log-salinity             Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_performance_test.log:0:  l1: 8.71703693121617e-05  l2: 5.00682857997115e-06  linf: 2.16146819553842e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_performance_test.log-layerThickness       Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_performance_test.log:0:  l1: 3.97078916161941e-03  l2: 7.88601350610143e-05  linf: 1.83480870177277e-05
--
case_outputs/ocean_global_ocean_QU240_WOA23_performance_test.log-normalVelocity       Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_performance_test.log:0:  l1: 8.70422701970631e-03  l2: 1.04291407480119e-04  linf: 8.65663152778418e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log-temperature          Time index: 0
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log:0:  l1: 6.56630276610562e-03  l2: 2.40923094382667e-04  linf: 7.38053175837194e-05
--
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log-salinity             Time index: 0
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log:0:  l1: 2.38971958884804e-03  l2: 1.46609778437089e-04  linf: 5.12710479831924e-05
--
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log-layerThickness       Time index: 0
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log:0:  l1: 4.21585587841238e-02  l2: 1.03826547358668e-03  linf: 3.91259372987562e-04
--
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log-normalVelocity       Time index: 0
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log:0:  l1: 1.50046217730810e-01  l2: 2.09729014733650e-03  linf: 2.60616212190812e-04
--
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log-temperature          Time index: 0
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log:0:  l1: 6.56630276610562e-03  l2: 2.40923094382667e-04  linf: 7.38053175837194e-05
--
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log-salinity             Time index: 0
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log:0:  l1: 2.38971958884804e-03  l2: 1.46609778437089e-04  linf: 5.12710479831924e-05
--
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log-layerThickness       Time index: 0
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log:0:  l1: 4.21585587841238e-02  l2: 1.03826547358668e-03  linf: 3.91259372987562e-04
--
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log-normalVelocity       Time index: 0
case_outputs/ocean_global_ocean_QU240_WOA23_restart_test.log:0:  l1: 1.50046217730810e-01  l2: 2.09729014733650e-03  linf: 2.60616212190812e-04
--
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log-temperature          Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log:0:  l1: 2.75566436533036e-04  l2: 8.29606292738649e-06  linf: 1.94863980240711e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log-salinity             Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log:0:  l1: 8.71703693121617e-05  l2: 5.00682857997115e-06  linf: 2.16146819553842e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log-layerThickness       Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log:0:  l1: 3.97078916161941e-03  l2: 7.88601350610143e-05  linf: 1.83480870177277e-05
--
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log-normalVelocity       Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log:0:  l1: 8.70422701970631e-03  l2: 1.04291407480119e-04  linf: 8.65663152778418e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log-temperature          Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log:0:  l1: 2.75566436533036e-04  l2: 8.29606292738649e-06  linf: 1.94863980240711e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log-salinity             Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log:0:  l1: 8.71703693121617e-05  l2: 5.00682857997115e-06  linf: 2.16146819553842e-06
--
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log-layerThickness       Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log:0:  l1: 3.97078916161941e-03  l2: 7.88601350610143e-05  linf: 1.83480870177277e-05
--
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log-normalVelocity       Time index: 0, 1, 2
case_outputs/ocean_global_ocean_QU240_WOA23_threads_test.log:0:  l1: 8.70422701970631e-03  l2: 1.04291407480119e-04  linf: 8.65663152778418e-06
```
</details>

**Review by mark-petersen — APPROVED** [review]
I also reviewed visually. Based on testing, I am approving. Note that this does not affect E3SM mainline simulations.

**Comment by mark-petersen** [comment]
@jonbob I think this should be labeled 'BFB' as it pertains to tested E3SM simulations. We could even add `stealth` since it is an unused feature for our standard configurations.

**Comment by jonbob** [comment]
Thanks for the testing @mark-petersen. I'll change the label but test in E3SM as well before merging

**Comment by cbegeman** [comment]
@mark-petersen Thank you for your review and testing!

**Comment by rljacob** [comment]
notes: ready but low priority

**Comment by jonbob** [comment]
passes:
* ERS_Ld5.T62_oQU120.CMPASO-NYF.chrysalis_intel
* SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod_1850

merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
