### PR TITLE
update mpas-source: framework update

### PR DESCRIPTION
**Pull request by mark-petersen**
See:
- remove unneeded module `use` statements https://github.com/MPAS-Dev/MPAS-Model/pull/797
- other changes are for atmospheric core, not compiled by E3SM

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
Passes MPAS-Ocean nightly regression suite with gnu 5.3 and intel 19, debug and optimized.

**Comment by jonbob** [comment]
@mark-petersen - these are two disconnected changes included in one PR

**Comment by xylar** [comment]
@jonbob, we don't really have a workflow for avoiding this with MPAS framework changes.  I asked about this in https://github.com/MPAS-Dev/MPAS-Model/pull/816 and was told to go ahead and merge without regard to E3SM.

**Comment by mark-petersen** [comment]
I redid the merge from before the intel 19 makefile update. I'll do that one tomorrow.

**Comment by xylar** [comment]
Ah, okay.  I guess there is a way.

**Review by jonbob — APPROVED** [review]
Looks good from a visual inspection

**Comment by mark-petersen** [comment]
Sanity test, passes
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
```

**Comment by jonbob** [comment]
passed sanity testing on anvil, merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
