### PR TITLE
homme: modify printed timestep info, fix init in cxx

### PR DESCRIPTION
**Pull request by oksanaguba**
Small changes for output of homme's dt-related parameters.

Fix of the init of Q in thetaxx version.

[bfb]

### CODE REVIEW

**Comment by mt5555** [comment]
changing reviewer to @ambrad , as he is the one who put in the new V2 timestep system.

What issue is this PR addressing?

**Comment by oksanaguba** [comment]
@mt5555 homme now prints nsplit, dtime, and correct dt_tracers in one place. it also prints which code will be used, the old one, or the one with prim_run_flexible.

these are very minor issues, but I wanted them for scream verification runs, to keep track of code paths in one place.

**Comment by ambrad** [comment]
@oksanaguba I see this as marked "[wip]", so let me know when you're ready for review. One thing I'll suggest is to reconsider the name `which_prim_step`. Perhaps `prim_step_type` or `prim_step_method`?

**Comment by oksanaguba** [comment]
thanks, I will rename the variable. I want to run tests before removing [wip].

**Comment by oksanaguba** [comment]
The last comment seemed to resolve a nonbfb restart issue in runs with hommexx.
Previously, for ne30, dtime1800, 6+5 nsteps setup, ERS test failed for SL transport for
(ftype2, rsplit2, qsplit6), (ftype0,rsplit2,qsplit6),(ftype0,rsplit1,qsplit2) 
(replace rsplit with dt_remap_factor and qsplit with dt_tracer_factor).
The last commit gets these pass.

I can either create a new PR or keep the changes here. I still need to run hommexx standalone on gpu.

**Comment by ambrad** [comment]
Re: "Previously, for ne30, dtime1800, 6+5 nsteps setup, ERS test failed for SL transport for (ftype2, rsplit2, qsplit6), (ftype0,rsplit2,qsplit6),(ftype0,rsplit1,qsplit2)": Do you mean that in the 6+5 nsteps setup, the ERS test passes when using Eulerian transport but not SL transport?

That aside, now that you think you have found and fixed the discrepancy, I suggest you run a longer ERS test, something like a few months in total length, as a stronger check.

pull_q is definitely better than the previous C++-side initialization of Q. However, at the moment I don't see why it should fix the problem. I speculate that what might actually be happening is that the code modification changes the IC at time 0, since now Q is BFB-consistent with the `(runtype==0 .or. runtype==2)` block in `prim_init2` that pertains to an initial rather than restart run. I'm speculating that this perturbation to the IC might then make the 6+5 test pass by chance. I'm probably wrong, but that's currently my best guess.

**Comment by oksanaguba** [comment]
thanks, i agree that the change would only affect init of the restart, which actually matches F version for runtype=1. however, this was only potential issue that could affect restart. ftype, nsplit, or even broken forcing logic would not break restart, they are not used in init. restart or not, runs start from cam_run1 run with zeroed forcing.

i am running longer ERS tests. I ran ERS.ne30pg2_oECv3.F2010.chrysalis_intel.eam-hommexx.20220510_082629_j0c2fc with the parameters as above and default 6+5 days. all are ok..

i will run even longer tests.

**Comment by oksanaguba** [comment]
Testing the last commit with atm_integration, all is ok
```
[ac.onguba@chrlogin1 ess]$ ./cs.status.20220511_133025_qqkyp5 | grep -i fail
    FAIL ERS_Ld5.ne4_oQU240.F2010.chrysalis_intel.eam-rrtmgpxx TPUTCOMP Error: TPUTCOMP: Computation time increase > 5% from baseline
    FAIL SMS.ne4_oQU240.F2010.chrysalis_intel.eam-preqx_ftype1 MEMCOMP Error: Memory usage increase >5% from baseline's 2015.270000 to 2116.430000
    FAIL SMS.ne4_oQU240.F2010.chrysalis_intel.eam-preqx_ftype4 MEMCOMP Error: Memory usage increase >5% from baseline's 2015.280000 to 2116.430000
    FAIL SMS.ne4_oQU240.F2010.chrysalis_intel.eam-thetahy_ftype0 MEMCOMP Error: Memory usage increase >5% from baseline's 2032.670000 to 2134.810000
    FAIL SMS.ne4_oQU240.F2010.chrysalis_intel.eam-thetanh_ftype0 MEMCOMP Error: Memory usage increase >5% from baseline's 2019.720000 to 2120.880000
    FAIL SMS.ne4_oQU240.F2010.chrysalis_intel.eam-thetanh_ftype1 MEMCOMP Error: Memory usage increase >5% from baseline's 2019.820000 to 2120.870000
    FAIL SMS.ne4_oQU240.F2010.chrysalis_intel.eam-thetanh_ftype2 MEMCOMP Error: Memory usage increase >5% from baseline's 2023.720000 to 2132.880000
```
I will not test on gpu, since the last commit does not do any pulls/pushes.

I will run homme suites next.

**Comment by oksanaguba** [comment]
deleted the last comment, tested wrong clone.

**Comment by ambrad** [comment]
Some background on commit https://github.com/E3SM-Project/E3SM/pull/4857/commits/e00c3fbf8228b35d2e7edad761306eca9a6a77a0:

We noticed a systematic jump in the globally averaged surface pressure (PS) in certain run configurations at restart boundaries. Thus, it became clear there was either one or two issues: a machine roundoff level non-BFBness in restart and/or a systematic error on restart. If there is a roundoff issue, then the commit won't fix that. But the commit does fix the jump.

This is what was happening. n0_qdp was not initialized when it was used to compute q = qdp/dp. The effect was as follows, using an ne4pg2 2-month restart interval as an example. In the first restart, the dycore nstep is 8502. For Eulerian transport, n0_qdp = (8502/1) % 2 = 0, which makes the n0_qdp value of 0 (which it seems to have when not initialized, though I haven't found why that is) correct but for the wrong reason. For SL transport, n0_qdp = (8502/6) % 2 = 1417 % 2 = 1, so the uninitialized n0_qdp value of 0 is wrong; it should be 1.

The downstream effect is that then R* is computed incorrectly, I believe using what turns out to be a 0 specific humidity. However, by the time the physics is called, the Q array is valid again. So the end result is a jump in R*-related quantities followed by everything being basically fine, rather than a catastrophic failure.

The question then arises whether we should use Q as computed from F (as in commit https://github.com/E3SM-Project/E3SM/pull/4857/commits/dff5df901c66d4390fe07a5edbdad7bb0ec7836a) or rather compute q = qdp/dp on the C++ side, now with the correct n0_qdp value. The majority opinion is that we should do it on the C++ side, to match the fact that in the previous time step, q = qdp/dp was computed on the C++ side. This motivates reverting the F-side commit and going with the n0_qdp fix alone. We'll see if all BFB tests pass with this approach...

**Comment by oksanaguba** [comment]
homme suites, atm_integration are ok for this branch merged to today's master against baselines on chrysalis
```
[ac.onguba@chrlogin2 ess]$ ./cs.status.20220511_170127_rlrlwe | grep -i fail
    FAIL ERS_Ld5.ne4_oQU240.F2010.chrysalis_intel.eam-rrtmgpxx TPUTCOMP Error: TPUTCOMP: Computation time increase > 5% from baseline
    FAIL PEM_Ln5.ne4_oQU240.F2010.chrysalis_intel TPUTCOMP Error: TPUTCOMP: Computation time increase > 5% from baseline
    FAIL REP_Ln5.ne4_oQU240.F2010.chrysalis_intel TPUTCOMP Error: TPUTCOMP: Computation time increase > 5% from baseline
    FAIL SMS_Ln1.ne4_oQU240.F2010.chrysalis_intel.eam-chem_pp TPUTCOMP Error: TPUTCOMP: Computation time increase > 5% from baseline
    FAIL SMS.ne4_oQU240.F2010.chrysalis_intel.eam-preqx_ftype1 MEMCOMP Error: Memory usage increase >5% from baseline's 2015.270000 to 2116.530000
    FAIL SMS.ne4_oQU240.F2010.chrysalis_intel.eam-preqx_ftype4 MEMCOMP Error: Memory usage increase >5% from baseline's 2015.280000 to 2116.430000
    FAIL SMS.ne4_oQU240.F2010.chrysalis_intel.eam-thetanh_ftype0 MEMCOMP Error: Memory usage increase >5% from baseline's 2019.720000 to 2120.870000
    FAIL SMS.ne4_oQU240.F2010.chrysalis_intel.eam-thetanh_ftype1 MEMCOMP Error: Memory usage increase >5% from baseline's 2019.820000 to 2120.880000
 
[ac.onguba@chrlogin2 ess]$ ./cs.status.20220511_164238_36x6ve 
20220511_164238_36x6ve: 1 test
  HOMMEBFB_P24.f19_g16_rx1.A.chrysalis_intel (Overall: PASS) details:
    PASS HOMMEBFB_P24.f19_g16_rx1.A.chrysalis_intel CREATE_NEWCASE
    PASS HOMMEBFB_P24.f19_g16_rx1.A.chrysalis_intel XML
    PASS HOMMEBFB_P24.f19_g16_rx1.A.chrysalis_intel SETUP
    PASS HOMMEBFB_P24.f19_g16_rx1.A.chrysalis_intel SHAREDLIB_BUILD time=0
    PASS HOMMEBFB_P24.f19_g16_rx1.A.chrysalis_intel NLCOMP
    PASS HOMMEBFB_P24.f19_g16_rx1.A.chrysalis_intel MODEL_BUILD time=660
    PASS HOMMEBFB_P24.f19_g16_rx1.A.chrysalis_intel SUBMIT
    PASS HOMMEBFB_P24.f19_g16_rx1.A.chrysalis_intel RUN time=1608
    PASS HOMMEBFB_P24.f19_g16_rx1.A.chrysalis_intel BASELINE
    PASS HOMMEBFB_P24.f19_g16_rx1.A.chrysalis_intel SHORT_TERM_ARCHIVER
[ac.onguba@chrlogin2 ess]$ ./cs.status.20220511_165351_1wrwmv 
20220511_165351_1wrwmv: 1 test
  HOMME_P24.f19_g16_rx1.A.chrysalis_intel (Overall: PASS) details:
    PASS HOMME_P24.f19_g16_rx1.A.chrysalis_intel CREATE_NEWCASE
    PASS HOMME_P24.f19_g16_rx1.A.chrysalis_intel XML
    PASS HOMME_P24.f19_g16_rx1.A.chrysalis_intel SETUP
    PASS HOMME_P24.f19_g16_rx1.A.chrysalis_intel SHAREDLIB_BUILD time=0
    PASS HOMME_P24.f19_g16_rx1.A.chrysalis_intel NLCOMP
    PASS HOMME_P24.f19_g16_rx1.A.chrysalis_intel MODEL_BUILD time=445
    PASS HOMME_P24.f19_g16_rx1.A.chrysalis_intel SUBMIT
    PASS HOMME_P24.f19_g16_rx1.A.chrysalis_intel RUN time=344
    PASS HOMME_P24.f19_g16_rx1.A.chrysalis_intel BASELINE
    PASS HOMME_P24.f19_g16_rx1.A.chrysalis_intel SHORT_TERM_ARCHIVER
```

**Comment by oksanaguba** [comment]
also i reran ERS ne30 6+5 nsteps setups from above and got all pass.

this is ready.

**Review by ambrad — APPROVED** [review]

**Comment by oksanaguba** [comment]
Btw the current init in thetaxx still has a small issue, Q is initialized differently from F version, which makes it nonbfb.

**Comment by ambrad** [comment]
Do you think that is the only remaining issue that keeps EAM+hxx from being BFB with EAM+h in a debug build? If so, you could add a flag to init_elements_states_c that says whether to init from the F90 Q ('initial' run) or to compute Q from Qdp and dp3d ('continue' run).

**Comment by oksanaguba** [comment]
Last time i tried, fixing Q init helped with nonbfb in eam+xx vs eam+F only partially. So there might be something besides that. I could not find it. So i am not sure about a flag.

**Comment by rljacob** [comment]
Notes:  this is ready.

**Comment by oksanaguba** [comment]
in next

**Pull request merged**
