### PR TITLE
Add ERA5 (hourly and 6hrly) datm forcing option

### PR DESCRIPTION
**Pull request by chloewhicker**
- Adds support for hourly ERA5 forcing (ELMERA5) and the 6 hourly ERA5 forcing (ERA56HR) from 1979-2021.
- Adds tests for the new compsets.

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
How large is this new forcing data set?  Is it available on the blues data server?

**Comment by bishtgautam** [comment]
@chloewhicker can confirm the following finding. There is an hourly and six-hourly version of ERA5 on Perlmutter

1. Hourly data `/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.0.25d.v5.c180614`
```
1.5T	/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.0.25d.v5.c180614/lwdn
1.5T	/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.0.25d.v5.c180614/pbot
3.0T	/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.0.25d.v5.c180614/prec
5.9T	/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.0.25d.v5.c180614/swdn
1.5T	/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.0.25d.v5.c180614/tbot
1.5T	/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.0.25d.v5.c180614/tdew
5.9T	/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.0.25d.v5.c180614/wind
```

2. Six-hourly data `/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.6HRLY.0.25d.v5.c180614`
```
du -sh /global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.6HRLY.0.25d.v5.c180614/*
100M	/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.6HRLY.0.25d.v5.c180614/domain.lnd.era5_721x1440_rdrlat_EC30to60E2r2.221115.nc
253G	/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.6HRLY.0.25d.v5.c180614/lwdn
253G	/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.6HRLY.0.25d.v5.c180614/pbot
506G	/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.6HRLY.0.25d.v5.c180614/prec
1007G	/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.6HRLY.0.25d.v5.c180614/swdn
253G	/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.6HRLY.0.25d.v5.c180614/tbot
253G	/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.6HRLY.0.25d.v5.c180614/tdew
1007G	/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.ERA.6HRLY.0.25d.v5.c180614/wind
```

We should at least do the following: 
1. Copy 1-yr of hourly and six-hourly data on each supported machine and e3sm inputdata server, and
2. Add two new tests that use hourly and six-hourly ERA5 dataset.

**Comment by chloewhicker** [comment]
Thanks Gautam. The datm forcing files are in the cfs, and should be available on any machines with access to cfs.

**Comment by bishtgautam** [comment]
@rljacob The [table](https://github.com/E3SM-Project/E3SM/pull/6234#issuecomment-1944481171) listing the size of the data is for the whole data set.

@chloewhicker In case you aren't familiar with adding tests, I can add a test in your branch.

**Comment by rljacob** [comment]
Then go ahead and add a year's worth of data to the input data server.

**Comment by bishtgautam** [comment]
Copying @chloewhicker's original first message in the PR:

> We've implimented ERA5 as a new datm forcing option for ELM simulations. This PR includes both the hourly ERA5 forcing (ELMERA5) and the 6 hourly forcing (ERA5_6HR) from 1980-2021. The 6 hourly forcing is significantly faster than the hourly. 
>
>More information about the implementation process can be found here: https://acme-climate.atlassian.net/wiki/spaces/PSC/pages/3709730833/ERA5+Offline+Forcing+Implementation+and+Evaluation
>
>and information about a 1k IG spin up simulation using the 1980s ERA5 datm can be found here: https://acme-climate.atlassian.net/wiki/spaces/FAN/pages/4096557191/Deep+Firn+1k+Spin+Up 
>
>These modifcations only change the output if one selects the ERA5 option in env_run.xml. 
>
>These modifications are complete and have been shown to work properly within E3SM (see simulation information here https://acme-climate.atlassian.net/wiki/spaces/PSC/pages/3709730833/ERA5+Offline+Forcing+Implementation+and+Evaluation and here:https://acme-climate.atlassian.net/wiki/spaces/FAN/pages/4096557191/Deep+Firn+1k+Spin+Up ). 
>
>The relevent code modifications can be found here: https://github.com/chloewhicker/E3SM/tree/cwhicker_m20240206_2_datm-era5  
>
>The implimentation of an ERA5 forced data atmosphere will improve SMB estimates in ELM as ERA5 precipitation has been shown to be more highly correlated with with in situ measurements of net accumulation than other widely used reanalyses (WFDE5, CRUNCEP, and GSWP3) ([Schneider et al., 2023](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2023GL103943)). The ERA5 data forcing option includes 0.25 degree, hourly, and 6 hourly resolution data from 1980-2021, where as other currenly avaiable datm forcing options only extend to 2005 (CLM_QIAN, the current default option) and 2017 (CRUNCEP) and have lower spatial and temporal resolution.

The test in the first message will be reduced as it will be copied/pasted in the commit message.

**Comment by rljacob** [comment]
@bishtgautam can you merge this?

**Comment by bishtgautam** [comment]
@rljacob Even a single year of EAR5 hourly data is quite large (~430GB). Let me see if I can use testmods to reduce the data size required by a factor of 12 as the 5-day tests don't need 12 monthly files.

**Comment by rljacob** [comment]
@bishtgautam is this ready now?

**Review by bishtgautam — APPROVED** [review]

**Pull request merged**
