### PR TITLE
Update machine settings for LANL machines grizzly and badger

### PR DESCRIPTION
**Pull request by jonbob**
This PR updates machine and compiler settings for LANL IC machines grizzly and badger. It reflects the new modules made available by the LANL HPC group, with many thanks to Jennifer Green.

No testing is performed on these machines, so the changes will not impact test results. However, it will likely change answers on cases run on these machines due to new compiler versions.

### CODE REVIEW

**Comment by stephenprice** [comment]
Thanks Jon. These all look good to me. One related question ... I am pretty sure Jennifer also tested and added the necessary libs and (somewhere) gave us the necessary compiler and machine xml file changes to support Badger. I have not tested those yet, so maybe we do that as a part of another PR later on? Probably more important to get this one done and in for now.

**Comment by jonbob** [comment]
I did add the badger settings from the xml files you gave me, but we can update this if she has better ones.

**Comment by stephenprice** [comment]
As far as I can tell, these .xml files do NOT have the updated badger settings in them. I think they are still the old ones. I can add them in on this PR if you like.

**Comment by jonbob** [comment]
@stephenprice - if you have them, let's get them in. The repo is closed anyway, so there's some extra time...

**Comment by stephenprice** [comment]
Will do.

**Comment by stephenprice** [comment]
One more note - Jen's updated machine files have also been written to reduce some of the redundancy w.r.t. mod loads and paths specified for the diff. mpi / compiler combos. While I don't see any issues there, I would like to make sure to test them again quickly just in case. That may take a few more hours (as opposed to just adding the Badger changes and pushing them up)

**Comment by stephenprice** [comment]
The badger builds have all been tested confirmed working now, so I'll push those additions up in a bit.

**Comment by stephenprice** [comment]
The new commits should be correct now (and have also been tested again).

**Comment by rljacob** [comment]
@jonbob you could  merge this to next and master.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
