### PR TITLE
EAM: Fixes high-order physgrid when num MPI ranks > num elements

### LINKED ISSUE #3241: High-order physgrid does not handle the case of MPI ranks having 0 elements.
See https://github.com/E3SM-Project/E3SM/pull/3141#pullrequestreview-303454580. Reported by @amametjanov; thanks!

### PR DESCRIPTION
**Pull request by ambrad**
Previously, high-order physgrid did not handle the case of MPI ranks
having 0 elements. This occurs when number of ranks is greater than
number of SE elements.

This commit fixes this issue by inserting par%dynproc checks in a few
spots.

Fixes #3241.

[BFB]

### CODE REVIEW

**Comment by ambrad** [comment]
I ran
```
$e3sm/cime/scripts/create_test SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.sandiatoss3_intel.cam-thetahy_pg2 --wait -v -p $wcid --force-procs 108
```
without this PR's commit, then with it. The first run failed with the error @amametjanov reported; the second run passed.

I'm running e3sm_developer now and will report back when it's done.

**Comment by rljacob** [comment]
@ambrad can you change the title to be   "Fixes  <short description of problem>".  Issue numbers are not clickable in a github title.

Edit the description to have "Fixes #3421" in the next-to-last line.  In the description, it is clickable and that format will also autoclose the issue when the PR is merged.

**Comment by ambrad** [comment]
e3sm_developer completed, with checks against baselines from master, with one FAIL, ERS.ne30_g16_rx1.A.sandiatoss3_intel, that looks like a file system issue (XML "changed without a corresponding invalidation") and is in any case not affected by this PR's changes to gllfvremap_mod.F90.

**Comment by oksanaguba** [comment]
merged to next without testing, AMB tested.

**Pull request merged**
