### PR TITLE
Updates for Lawrencium-LBNL

### PR DESCRIPTION
**Pull request by bishtgautam**
Updates machine files for lawrencium-lr2 and lawrencium-lr3, while 
new support for lawrencium-lr6 is added.
Additionally, support for GNU compiler for lawrencium-lr6 is added.

[BFB]

### CODE REVIEW

**Comment by rgknox** [comment]
@bishtgautam , are they decomissioning lr2 and lr3?

**Comment by bishtgautam** [comment]
Our `-qos condo_esd2` has [moved to lr6](https://sites.google.com/a/lbl.gov/high-performance-computing-services-group/lbnl-supercluster/lawrencium).

**Comment by rgknox** [comment]
ok.  For our NGEET account, I was not aware that we were tied to a specific partition.  Are you proposing to drop lr2/lr3 just to keep things simpler, is it just an availability thing.  I'm just wondering if we can keep lr2/lr3 with reasonable effort.

**Comment by bishtgautam** [comment]
Ok, I can add back the support for lr2/lr3. What `--qos` do you use for NGEET? `lr_normal`?

**Comment by bishtgautam** [comment]
@rgknox, I just noticed that `lr_esd2` account is only applicable to lr6 partition. What settings (account+qos) are you using to run jobs on LR2/LR3?

**Comment by rgknox** [comment]
Yeah, for lawrencium I was putting in the following directive in config_batch.xml:

>       <directive>--qos=lr_normal</directive>

**Comment by bishtgautam** [comment]
And what was the value for `--account`?

**Comment by rgknox** [comment]
I was passing that in as an environment variable, this seems to interpret it (also in config_batch.xml, also under the <directives> group:
>
>  <directive>--account={{ project }}</directive>

**Comment by bishtgautam** [comment]
Hmm...ok and what is the value of that environment variable?

**Comment by rgknox** [comment]
For the NGEE tropics project, we use PROJECT=ac_ngeet

**Comment by bishtgautam** [comment]
Thanks, Ryan. I will add back the support for lr2/lr3, but will ask you to verify the settings because I'm not a member of PROJECT=ac_ngeet.

**Comment by bishtgautam** [comment]
@rgknox, When you get a chance, could you test out my changes to make sure LR2 and LR3 are supported? Thanks.

**Comment by rgknox** [comment]
will do

**Comment by rgknox** [comment]
Thanks @bishtgautam , looks good to me, tested, works

**Pull request merged**
