### PR TITLE
removing obsolete "compute_ppm_grids_old"

### PR DESCRIPTION
**Pull request by mt5555**
The new compute_ppm_grids() has bug fixes for a new PPM option with better
treatment at the boundary.

[Non-BFB]  Roundoff level changes with Intel -O3.
Would be BFB if dycore compiled with -O2 or with gnu.
will require baseline rebless on skybridge

### CODE REVIEW

**Comment by rljacob** [comment]
@mt5555 you want me to merge this?

**Comment by mfdeakin-sandia** [comment]
I'm surprised this is a nonBFB change? I introduced this in HOMMEXX a few days ago and we didn't need to rebaseline?

**Comment by mfdeakin-sandia** [comment]
I don't understand this, so I ran the version in HOMMEXX with `-fpmodel fast` and `-O3` with `vert_remap_q_alg=1`, but still get BFB results against the old version

**Comment by mt5555** [comment]
in my tests, in standalone HOMME, it was BFB with the old code.  But with an F case, with some HOMME routines compiled with -O3 using Intel, it was not BFB with the old code.  Reducing optimization back to -O2 restores BFBness.  

Thus when this is merged to next, on some platforms it might introduce baseline diffs.

**Comment by mfdeakin-sandia** [comment]
Thanks for the clarification. I'm still surprised by this, but I suppose the tests I did weren't complete enough.

**Comment by rljacob** [comment]
These were the tests that diffed from this PR:

SMS_Ln9.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.cam-outfrq9s 
SMS.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.cam-cosplite
SMS.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_1850.sandiatoss3_intel.clm-bgcexp
SMS.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.sandiatoss3_intel.clm-bgcexp 
REP_Ln5.ne4_ne4.FC5AV1C-L.sandiatoss3_intel
PEM_Ln9.ne30_oECv3_ICG.A_WCYCL1850S.sandiatoss3_inte
PEM_Ln5.ne4_ne4.FC5AV1C-L.sandiatoss3_intel 
ERS_Ln9.ne4_ne4.FC5AV1C-L.sandiatoss3_intel
ERS.ne11_oQU240.A_WCYCL1850.sandiatoss3_intel

**Comment by mt5555** [comment]
out of curiosity, did this merge DIFF against our existing baselines?

**Comment by rljacob** [comment]
Yes, see list in comment above.

**Pull request merged**
