### PR TITLE
Cleanup of sea ice registry

### PR DESCRIPTION
**Pull request by akturner**
Add CF compliant units to registry
Change non-CF compliant units in registry to CF compliant ones
Reformat Registry for clarity
Moved incremental remapping fields to separate registry file

fixes https://github.com/E3SM-Project/E3SM/issues/5023

[BFB]

### CODE REVIEW

**Review by czender — COMMENTED** [review]
Hi Adrian,
As far as I can tell, the new units that are specified are good, i.e., CF-compliant, and the units that were removed should indeed have been removed.
However, I do not know what to make of the dozens of variables that look like they might still need units.

1. For example, in Registry.xml, the all the concentrations for variables whose name begins with "skeletal" or "vertical" (are those vertically integrated?). It seems like the concentrations are examples where units = "1" are appropriate if they are stored as fractions. Example variables are "skeletalDOCConc", "verticalDOCConc", "skeletalDOCConcCell", "verticalDOCConcCell". Some related variables do have units, e.g., "verticalDOCIceCell" has units="mmol m-3". So it's unclear to me whether this PR is complete.

2. The tendency variables like "surfaceTemperatureTend" are also still unitless, though it seems likely a units attribute such as "K second-1" might be appropriate.

3. The alternative atmospheric forcing variables like "latentHeatFluxCouple" still lack units.

4. The drag variables like "oceanDragCoefficient" still lack units.

5. Some pond variables like "pondFreshWaterFlux" lack units.

6. Some biogeochemistry fluxes like "atmosBlackCarbonFlux" lack units.

7. Some SNICAR variables like "aerosolMassExtinctionCrossSection5band" lack units.

You get the idea. The units that are explicitly specified look are CF-compatible and are an improvement. There may be a few score variables that would still benefit from have explicitly specified units. Those units can presumably be added to this PR or a later one.

**Comment by akturner** [comment]
@czender: Hi Charlie, I didn't update BGC or some other lesser variables. I decided they could have units added to them later.

**Comment by akturner** [comment]
@czender, @njeffery: Thanks for the reviews

**Review by czender — APPROVED** [review]

**Comment by jonbob** [comment]
passes:
* SMS_D_Ld1.T62_oEC60to30v3.DTESTM.chrysalis_intel
* SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
* ERS.ne11_oQU240.WCYCL1850NS.chrysalis_intel

merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
