### PR TITLE
Update mask/transect files for oRRS30to10v3 and oRRS18to6v3

### PR DESCRIPTION
**Pull request by jonbob**
Brings in updated mask/transect analysis files used for for mpaso meshes oRRS30to10v3 and oRRS18to6v3. The new files are staged on the inputdata server.

[BFB]

### CODE REVIEW

**Comment by vanroekel** [comment]
Here are a couple figures, first 30to10

image

The red dots are the defined atlantic region, black is the old transect file and blue is the new one, they are now aligned in the new file.

Here is 18to6

image

These plots are based on the files referenced in the PR and in the input data repository.

**Review by vanroekel — APPROVED** [review]
Looks great and the files are as expected.  Thanks @jonbob!

**Comment by jonbob** [comment]
passes sanity testing, merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
