### PR TITLE
COMPASS only, New Mesh: EC15to60E2r4

### PR DESCRIPTION
**Pull request by mark-petersen**
Add mesh generation for EC15to60kmL60E3SMv2r04. Does not change simulation code. See https://github.com/MPAS-Dev/MPAS-Model/pull/740

[BFB]

### CODE REVIEW

**Review by jonbob — APPROVED** [review]
All changes are in the compass testing code and should therefore have no impact on E3SM

**Comment by vanroekel** [comment]
@rljacob I'm approving this for integration to water cycle v2.  It is needed and will have no impact on the model code.

**Review by vanroekel — APPROVED** [review]
approved based on visual inspection

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
