### PR TITLE
Port ocean diagnostics to GPU w/ OpenACC

### PR DESCRIPTION
**Pull request by mattdturner**
This PR is the first phase of porting the ocean diagnostics code to GPUs using OpenACC. It contains a subset of the necessary changes for running on the GPU that retain bit-for-bit accuracy with the current version when running on the CPU.

A phase 2 PR will contain the loop structure changes for optimal GPU performance that result in roundoff-level changes for the CPU code.

This replaces the MPAS-Standalone PR https://github.com/MPAS-Dev/MPAS-Model/pull/813

[BFB]

### CODE REVIEW

**Comment by mattdturner** [comment]
## Testing

### Compy (Intel + PGI)
```
PASS:
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_pgi
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_pgi
PEM_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
PEM_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_intel
PET_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
PET_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
SMS_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_pgi
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
PEM_Ln9_D.T62_oQU240.GMPAS-IAF.compy_intel
```

### Anvil (Intel + GNU)
```
PASS:
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.chrysalis_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
PEM_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.chrysalis_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.chrysalis_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.chrysalis_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.chrysalis_intel
PET_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel 
SMS_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.chrysalis_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
SMS_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.chrysalis_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_gnu
PET_Ln3_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.chrysalis_intel
PEM_Ln9_D.T62_oQU240.GMPAS-IAF.chrysalis_intel
PET_Ln3_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.chrysalis_gnu
PEM_Ln9_D.T62_oQU240.GMPAS-IAF.chrysalis_gnu
```

### Bit-for-bit
```
PEM_Ln9.ne30_oECv3.A_WCYCL1850S.chrysalis_intel.C
  - PASS PEM_Ln9.ne30_oECv3.A_WCYCL1850S.chrysalis_intel BASELINE /lcrc/group/e3sm/baselines/chrys/intel/master: 
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel.C
  - PASS SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel BASELINE /lcrc/group/e3sm/baselines/chrys/intel/master:
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi.C
  - PASS SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi BASELINE /compyfs/e3sm_baselines/pgi/master: 
```

**Review by jonbob — APPROVED** [review]
Approve based on visual inspection and developer testing

**Comment by jonbob** [comment]
passes mpas-developer on chrysalis in a test merge

**Review by philipwjones — APPROVED** [review]
Approved based on previous MPAS-Dev PR inspection. Also re-verified that this is b4b on CPU-only runs with pgi on Summit. And it runs successfully with GPUs on summit resulting in expected round-off level results (single QU240 ocean standalone runs).

**Comment by jonbob** [comment]
Thanks @philipwjones for more testing
Merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
