### PR TITLE
Make dtime calculation dependent on value of NCPL_BASE_PERIOD

### PR DESCRIPTION
**Pull request by jonbob**
This PR modifies the ELM namelist build system so that the coupling frequency it computes, in the form of variable dtime, is dependent on the value of NCPL_BASE_PERIOD. Previously it was hard-wired to assume the base period was one day and LND_NCPL was the number of couplings per day. This update was necessary for getting IG cases working, where the NCPL_BASE_PERIOD is often a year so that the landice code can run on order of days.

Tested by @stephenprice during IG-case development

[BFB]

### CODE REVIEW

**Comment by stephenprice** [comment]
Confirming this fix works in an IG test case.

**Comment by jonbob** [comment]
@bishtgautam - I think added that line because there is similar logic for l_ncpl (LND_NCPL) which also comes from env_run.xml and should be defined as well. But I don't need to make it less clear!

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
