### PR TITLE
Correction to resolve restart bfb error.

### PR DESCRIPTION
**Pull request by pnlfang**
This bug fix is related to the restart bfb error when plant hydraulics is activated.

### CODE REVIEW

**Comment by rljacob** [comment]
Can you explain why this fixed the restart bfb problem?  Its not obvious from looking at the code.

**Comment by pnlfang** [comment]
>

**Comment by pnlfang** [comment]
The error occurs when LAI is close to 0, the flux between the leaf and stem becomes 0 by setting water potential in leaf and stem equal. The original approach caused unconverged solution, which changes the flux after restart. What I did is replacing the flux equation with equal potential equation and that solved the problem.

**Comment by rljacob** [comment]
@peterdschwartz please start merging this.

**Comment by peterdschwartz** [comment]
@rljacob Had to take yesterday off due to the covid booster, but I'll merge it tonight when the tests come back bfb.

**Review by peterdschwartz — APPROVED** [review]

**Comment by peterdschwartz** [comment]
merged to next

**Pull request merged**
