### PR TITLE
Bugfix for naming mismatch in HOMME-ARKode interface

### PR DESCRIPTION
**Pull request by cjvogl**
This will fix a naming mismatch that occurred during the original merge of the HOMME-ARKode interface.  This should be BFB in that it only modifies code within an `ifdef` block that is disabled by default.

### CODE REVIEW

**Comment by mt5555** [comment]
Chris, I'm not sure why this is, but your PRs often have a lot of white space changes.  They are all for the better (removing trailing blanks) but make it hard to review the PR.  Maybe this is a setting in your editor, so that any file you visit is automatically cleaned up?   Any chance you could turn this off?

**Comment by cjvogl** [comment]
Yes, sorry about that: my editor is set to remove trailing whitespace in any file that I save.  I can revert the changes or, if removed whitespace is beneficial, Github does provide the "Hide Whitespace changes" option in  the "Diff settings" dropdown menu on the "Files Changed" tab (which I believe is equivalent to `git diff -w`)

Just let me know if you want to isolate the actual changes via the editor side (by my avoiding using the editor that removes trailing whitespace).

**Comment by mt5555** [comment]
see #2881

**Comment by cjvogl** [comment]
Closing this PR in lieu of #2881

**Pull request closed without merging**
