### PR TITLE
HOMME: fixing some issues with the preqx_kokkos target

### PR DESCRIPTION
**Pull request by bartgol**
One issue this PR fix is #2648 . The other issue it fixes (which was not opened on github) is the duplication of files between preqx and preqx_kokkos targets. In particular, the files in the folder preqx/share were copied verbatim in the folder preqx_kokkos. This causes maintenance issues, and led to a build error when some changes were made in the files in preqx/share but not in the corresponding files in preqx_kokkos. Instead, we now simply include the preqx/share folder content in the list of files to be compiled for the preqx_kokkos target.

Note: there are a few files in preqx that are copied verbatim in preqx_kokkos. It would be tempting to also remove those files in preqx_kokkos, and simply use the files in preqx. This would work in a cmake standalone homme build, but it would be problematic with cime. The reason is that not *all* files in the preqx folder are copied in preqx_kokkos; for instance, `prim_driver_mod.F90` is different. In cmake, we can manually specify the files we want to compile, but in cime, we can only specify the folders where the files are, and cime will glob all source files in those folders.

For now, we are ok with the removal of _some_ duplicate files. We will think about how to remove the other duplicates later.

### CODE REVIEW

**Comment by oksanaguba** [comment]
So, it seems that in folder preqx_kokkos these files are duplicated wrt folder preqx: bndry_mod, derivative_mod, edge_mod, prim_advection_mod, sl_advection, viscosity_mod . Only 2 files are truly different: element_state and prim_driver_mod. 
To avoid doubles, for CAM target, would it be possible to add individual files from preqx folder in cam/bld/configure? For standalone targets individual files are already listed, so, one can just change files from preqx_kokkos/file... to preqx/file... .

**Comment by oksanaguba** [comment]
I tried to build with cam-target=preqx_kokkos on anvil and needed minor changes for that. i cannot push the changes till i am added as a collaborator to Luca's fork @bartgol . Meanwhile the model won't build anyway because of absence of c++11 flag, which is by default is in CXXFLAGS in cime/config/e3sm/machines/config_compilers.xml , but is not picked up. In cime/scripts/Tools/Makefile there is a line
```
CXXFLAGS := $(CFLAGS)
```
which i believe prevents using true cxx flags. Also, in the build line one sees CFLAGS, not CXXFLAGS for mpicxx compiler.

**Comment by oksanaguba** [comment]
As was noted by AMB, this PR is not about preqx_kokkos cam target and should instead be focused on standalone hommexx. I am saving these changes for later, when we go back to the cam target issues:

For anvil one needs:
```
diff --git a/cime/config/e3sm/machines/config_compilers.xml b/cime/config/e3sm/machines/config_compilers.xml
index 0d9efa9..37303b4 100644
--- a/cime/config/e3sm/machines/config_compilers.xml
+++ b/cime/config/e3sm/machines/config_compilers.xml
@@ -725,6 +725,7 @@ for mct, etc.
 </compiler>
 
 <compiler MACH="anvil" COMPILER="intel">
+  <KOKKOS_PATH>$ENV{KOKKOS_ROOT}</KOKKOS_PATH>
   <CFLAGS>
     <append compile_threaded="true"> -static-intel</append>
     <append compile_threaded="true" DEBUG="TRUE">-heap-arrays</append>
diff --git a/cime/scripts/Tools/Makefile b/cime/scripts/Tools/Makefile
index 36c0238..d916a9d 100644
--- a/cime/scripts/Tools/Makefile
+++ b/cime/scripts/Tools/Makefile
@@ -306,7 +306,7 @@ ifeq ($(strip $(USE_KOKKOS)), TRUE)
     INC_KOKKOS:=$(KOKKOS_PATH)/include
     LIB_KOKKOS:=$(KOKKOS_PATH)/lib
   else
-    $(error $(HOMME_TARGET) requires env. variable KOKKOS_ROOT to be set)
+    $(error $(HOMME_TARGET) requires env. variables KOKKOS_ROOT,KOKKOS_PATH to be set)
   endif
        CPPDEFS += -DUSE_KOKKOS_KERNELS
 endif
```
and
```
--- a/cime/scripts/Tools/Makefile
+++ b/cime/scripts/Tools/Makefile
@@ -519,7 +519,8 @@ INCLDIR +=  -I$(INSTALL_SHAREDPATH)/include
 # Use the MCT dir for the cache for all configure calls because it is the first one
 #
 CFLAGS+=$(CPPDEFS)
-CXXFLAGS := $(CFLAGS)
+#CXXFLAGS := $(CFLAGS)
+CXXFLAGS+=$(CPPFDEFS)
 CONFIG_ARGS +=  CC="$(CC)" FC="$(FC)" MPICC="$(MPICC)" \
                 MPIFC="$(MPIFC)" FCFLAGS="$(FFLAGS) $(FREEFLAGS) $(INCLDIR)" \
                 CPPDEFS="$(CPPDEFS)" CFLAGS="$(CFLAGS) -I.. $(INCLDIR)" \
```

**Comment by bartgol** [comment]
@oksanaguba Thanks for taking a look at this. To answer your points:

>   would it be possible to add individual files from preqx folder in cam/bld/configure?

I am not expert of cime (@jgfouca may have a better answer), but I _think_ the cime build system only allows to specify the folders where the source files are, and then it globs all Fortran/C/C++ files it can find in it. This is also why we have the duplicate files you mentioned: I can't add the whole preqx folder, since there is at least one file (prim_driver_mod) that is truly different. I could probably get away with a proper ordering of the folders, which _may_ end up with the compiler only compiling the right prim_driver_mod, but relying on a file overwriting another seems to me a _very_ dangerous solution.

About your kokkos modifications to the compiler scripts: we talked with @jgfouca about adding kokkos as an external in cime. It was a while ago, so I have to refresh my memory, but I think that was the most portable solution for us. The one you mention (which is what I did) relies on the KOKKOS_ROOT env variable being defined, which as I understand is not the desired e3sm/cime policy. I will talk again to jim, and see if we can get the kokkos external in cime done.

Last but not least, I added you as collaborator on my fork, so you can push the mods you already made (if you still have them).

**Comment by oksanaguba** [comment]
Thanks -- just to reiterate: It seems that for this PR we need only to focus on standalone build, not cime. I will get back to this PR next week.

**Comment by jgfouca** [comment]
@bartgol , @oksanaguba , I spoke with the CESM folks about Kokkos and I raised the issue with the SE telecon. If I remember, @rljacob and others suggested a new, top-level directory under E3SM called "externals".

**Comment by oksanaguba** [comment]
Here homme suite for original homme files passes; for a 'strict' build (amending f, c, cxx flags with fp-model and O0) many cxx vs F tests pass, too (first 9 of them). I did not try to run all of them. I guess i will run at least all 'ndays1' tests. otherwise it is ready.

**Comment by oksanaguba** [comment]
I just saw merge commit here (last commit), which luckily is what I tested. however I think merging master into dev branches is discouraged, unless it is really needed.

**Comment by bartgol** [comment]
@oksanaguba Sorry, I can rewrite the history of the branch once it's ready, to delete that. Though this would break the local repo of all people who checked out the branch... Not sure what the policy is in this case.

**Comment by oksanaguba** [comment]
thanks Luca -- that was just a minor comment, I would think it is ok to leave everything as is.

**Comment by oksanaguba** [comment]
Jim @jgfouca , this is ready.

**Comment by jgfouca** [comment]
Merged to next.

**Comment by oksanaguba** [comment]
@jgfouca how would i set USE_KOKKOS to true without using preqx_kokkos cam target? I tried to do it like DEBUG, xmlchange --id DEBUG --val TRUE, but it did not work. thanks!

**Pull request merged**
