### PR TITLE
Add missing omp private variables for data subglacial runoff

### PR DESCRIPTION
**Pull request by jonbob**
Adds some variables were introduced in PR #6508 and not icluded in the appropriate omp private statement. These variables are only used for data subglacial runoff, so this does not impact current tests.

[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
@vanroekel -- did you see any other loops where the new variables didn't get included?

**Comment by jonbob** [comment]
I ran the following test with and without these changes:
* PET_P640.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF-DSGR.chrysalis_intel.mpaso-jra_1958
I didn't see a FAIL in any testing, but it is still worth making these fixes

**Comment by rljacob** [comment]
You may want to add that test to e3sm_gpuomp

**Review by vanroekel — APPROVED** [review]
Approving by visual inspection.  This is the only place I saw some omp variables missing.  Thanks @jonbob

**Review by irenavankova — APPROVED** [review]
Approving based on visual inspection. Thank you for fixing this!

**Comment by jonbob** [comment]
@irenavankova -- that should probably be a new PR. Do you want to make it?

**Comment by irenavankova** [comment]
Yes, I ll make it.

**Comment by rljacob** [comment]
Sure.  And I realized this isn't omp-offload you're talking about so you don't need to move it to gpuomp

**Comment by jonbob** [comment]
Passes:
* PET_P480.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF-DSGR.chrysalis_intel.mpaso-jra_1958 (new test)
* ERP_Ld3.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-pioroot1

merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
