### PR TITLE
Add the 'case.submit' step to the Travis test

### PR DESCRIPTION
**Pull request by lukaszlacinski**
This PR is to check if it is possible to not only build a case, but actually run it on a Travis CI VM which has limited resources (7.5 GB RAM), https://docs.travis-ci.com/user/reference/overview/.

### CODE REVIEW

**Comment by rljacob** [comment]
This does not effect WC and can be merged during v2 freeze.

**Comment by lukaszlacinski** [comment]
Adding the 'case.submit' step to the Travis test revealed a bug in https://github.com/ESMCI/cime/blob/master/scripts/lib/CIME/case/check_input_data.py. https://github.com/ESMCI/cime/pull/3730 that was merged today fixes the bug, but as long as the E3SM repo does not points to the cime repo with with the fix merged, the Travis test will fail.

**Comment by rljacob** [comment]
You mean it will fail on this branch?

**Comment by lukaszlacinski** [comment]
Yes. This E3SM master branch points to cime@54ef8b which is two days old, and the bug fix was merged to the cime master branch today, so the case.submit step this PR adds to the Travis test will fail.

**Comment by rljacob** [comment]
@lukaszlacinski E3SM cime submodule now has the changes this PR needs.  I tried to rerun but looks like there is still a fail.

**Comment by rljacob** [comment]
Looks like its running out of time.  We can try reducing the run length.  Before the ./case.submit command, issue this command:  ./xmlchange STOP_N=1
That will change it to run for 1 day instead of 5.

**Comment by rljacob** [comment]
Still out of time.  Can you capture the output of ./case.submit and show that?  We'll be able to tell if it was still downloading data or actually started a run.

**Comment by rljacob** [comment]
It looks like the default optimization level for gnu is -O which will make it slow.  Try adding this to the singularity entry in config_compilers
```
  <FFLAGS>
    <append DEBUG="FALSE"> -O2  </append>
  </FFLAGS>
```

**Comment by rljacob** [comment]
Note from IG telecon:  this case takes to much memory and also file download time causes it to run out of time.  So can't run it.

**Pull request closed without merging**
