### PR TITLE
Fast DIRK solver for theta-l NH.

### PR DESCRIPTION
**Pull request by ambrad**
Backport the fast DIRK solver from Hommexx (C++) to Homme (F90). First, since
the Jacobian is strictly diagonally dominant, pivoting is not needed for
stability. Second, since pivoting isn't needed, it's natural to batch the solves
in the GLL direction. This leads to perfect vectorization of the tridiagonal
system solve. Third, since the solves are batched along the GLL direction,
everything in the driver loop can be done in Homme's usual fast layout.

[non-BFB] for 4 nonhydrostatic standalone Homme tests and 5 nonhydrostatic e3sm_atm_integration tests

### CODE REVIEW

**Comment by ambrad** [comment]
This PR is not urgent, and it affects only the nonhydrostatic mode of theta-l.

I branched from PR #3594; on the last commit, https://github.com/E3SM-Project/E3SM/pull/3612/commits/1f9d6b432cf4af9f2b2dc935b18ca0dde417e30c, is new in this PR. This should resolve once master gets PR #3594.

**Comment by ambrad** [comment]
With HOMME_IMEX_MKLSOLVE defined and -fp-model strict, Homme standalone tests are BFB. With default optimization and the fast solver code path, the diffs are as follows:
```
The following tests FAILED:
   16 - thetanh-TC (Failed)
   17 - thetanh-TC-nudiv (Failed)
   18 - thetanh-TC-nutop (Failed)
   19 - thetanhwet-TC (Failed)

>> thetanh-TC
 RMS ps     1.2155E-10  NORMALIZED  1.1976E-15
 RMS T      4.8972E-12  NORMALIZED  1.9981E-14
 RMS w      9.3858E-11  NORMALIZED  3.6934E-06
 RMS Q      7.5986E-16  NORMALIZED  1.4844E-13
 RMS Q4     1.0745E-14  NORMALIZED  1.0745E-14
>> thetanh-TC-nudiv
 RMS ps     1.1373E-10  NORMALIZED  1.1205E-15
 RMS T      4.8023E-12  NORMALIZED  1.9593E-14
 RMS w      9.6150E-11  NORMALIZED  5.0936E-06
 RMS Q      6.3192E-16  NORMALIZED  1.2346E-13
 RMS Q4     1.0391E-14  NORMALIZED  1.0391E-14
>> thetanh-TC-nutop
 RMS ps     1.1321E-10  NORMALIZED  1.1153E-15
 RMS T      4.8881E-12  NORMALIZED  1.9944E-14
 RMS w      9.5399E-11  NORMALIZED  4.0963E-06
 RMS Q      7.1229E-16  NORMALIZED  1.3915E-13
 RMS Q4     1.3144E-13  NORMALIZED  1.3144E-13
>> thetanhwet-TC
 RMS ps     1.1318E-10  NORMALIZED  1.1150E-15
 RMS T      4.6974E-12  NORMALIZED  1.9165E-14
 RMS w      9.5371E-11  NORMALIZED  4.0790E-06
 RMS Q      6.5617E-16  NORMALIZED  1.2819E-13
 RMS Q2     1.3722E-17  NORMALIZED  8.5909E-10
```
I also tested this PR using the DIRK unit tester in the homme_theta_kokkos branch.

**Comment by ambrad** [comment]
e3sm_developer is clean, as expected. I'll run e3sm_atm_integration to confirm the 5 thetanh tests diff.

**Comment by oksanaguba** [comment]
in next

**Pull request merged**
