### PR TITLE
Corrected possible division by zero in ice bgc

### PR DESCRIPTION
**Pull request by njeffery**
Fixes issue #4913

1. Sets BGC vertical diffusion to zero when ice thickness is small
2. Also removes trailing spaces in ice_brine.F90

BFB in 10 day test with BGC active.

### CODE REVIEW

**Review by akturner — APPROVED** [review]
Passed testing

**Comment by jonbob** [comment]
@njeffery -- no big deal but for next time the branch naming convention is hyphens and not underscores

**Comment by njeffery** [comment]
Thanks for the reminder!

________________________________
From: Jon Wolfe ***@***.***>
Sent: Tuesday, May 3, 2022 2:51:18 PM
To: E3SM-Project/E3SM
Cc: Jeffery, Nicole; Mention
Subject: [EXTERNAL] Re: [E3SM-Project/E3SM] Corrected possible division by zero in ice bgc (PR #4916)


@njeffery<https://urldefense.com/v3/__https://github.com/njeffery__;!!Bt8fGhp8LhKGRg!XVqNy6jGszFF91-BaQ5UuZTtxVTrV2vmcccmIonkZIK952HLCq5xDJ52KliMr8QsPw$> -- no big deal but for next time the branch naming convention is hyphens and not underscores

**Comment by jonbob** [comment]
Test merge shows there results:
PASS ERS.ne11_oQU240.WCYCL1850NS.chrysalis_intel
PASS SMS_P12x2.ne4_oQU240.WCYCL1850NS.chrysalis_intel.allactive-mach_mods
PASS SMS_D_Ld1.T62_oEC60to30v3.DTESTM.chrysalis_intel

**Comment by jonbob** [comment]
merged to next

**Pull request merged**
