### PR TITLE
Updates the settings for JRA data

### PR DESCRIPTION
**Pull request by bishtgautam**
Removes the hard-coded start and end year for JRA from 1958/2016 to be
the start/end values specified by DATM_CLMNCEP_YR_START/DATM_CLMNCEP_YR_END.

[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
@bishtgautam - I think we'll also have to add the DATM%JRA settings to DATM_CLMNCEP_YR_START and DATM_CLMNCEP_YR_END entries

**Comment by bishtgautam** [comment]
Added the start/end years for JRA in db553a295d4060acf500d4a8611085f3b609f31f.

**Comment by ndkeen** [comment]
One reason for this change is that the new test (like `ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.gcp_gnu.mosart-rof_ocn_2way`) was downloading many years of data into `inputdata/ocn/jra55/v1.3_noleap/`. While this may be needed for machines that will be doing longer campaigns, for machines only used for testing, it was a lot of data that would never be used (and problematic, such as on GCP).  

I tested this branch on GCP after removing the data that had already been attempted to download to that directory. Indeed the test completes with only needing the data from year 2004.

```
-rw-rw-r-- 1 noel         climate 2.3G Feb 11  2019 JRA.v1.3.lwdn.TL319.2004.171019.nc
-rw-rw-r-- 1 jason_sarich climate 2.3G Feb 11  2019 JRA.v1.3.prec.TL319.2004.171019.nc
-rw-rw-r-- 1 noel         climate 2.3G Feb 11  2019 JRA.v1.3.q_10.TL319.2004.171019.nc
-rw-rw-r-- 1 noel         climate 2.3G Feb 11  2019 JRA.v1.3.slp.TL319.2004.171019.nc
-rw-rw-r-- 1 noel         climate 2.3G Feb 11  2019 JRA.v1.3.swdn.TL319.2004.171019.nc
-rw-rw-r-- 1 noel         climate 2.3G Feb 11  2019 JRA.v1.3.t_10.TL319.2004.171019.nc
-rw-rw-r-- 1 noel         climate 2.3G Feb 11  2019 JRA.v1.3.u_10.TL319.2004.171019.nc
-rw-rw-r-- 1 noel         climate 2.3G Feb 11  2019 JRA.v1.3.v_10.TL319.2004.171019.nc
```

The `ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.gcp_gnu.mosart-rof_ocn_2way` now passes.

**Review by ndkeen — APPROVED** [review]

**Comment by amametjanov** [comment]
Can the length of `ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.mosart-rof_ocn_2way` be reduced from the default 11+5 days (Ld11) to Ld3 or shorter?

**Comment by bishtgautam** [comment]
@amametjanov Is this test timing out on a particular machine?

**Comment by amametjanov** [comment]
Yes, on Crusher with gnu running on 1 node with 64 MPI tasks: times out after 1 hour of wall-time.
We can add a 2- or 4-node pelayout to make the test run faster, but I just wanted to check if run-length can be reduced instead.

**Comment by bishtgautam** [comment]
@amametjanov On Cori, the test is using NTASK=512. Would it be too much trouble to have the test also use NTAKS=512 on Crusher?

**Comment by amametjanov** [comment]
Okay. Cori-knl was also timing out of 45 min wall-time with 512 tasks on 8 nodes. E3SM-Project/E3SM#5156 lets it complete in 25 mins on 30 nodes.
E3SM-Project/E3SM#5164 adds more nodes on 2 additional machines.

**Comment by jonbob** [comment]
@bishtgautam - I'm open to just merging this with the JRA stream using the DATM_CLMNCEP_YR_ settings, but I'm also curious if you'd consider another PR where we might rename those to something a bit more generic? Even something as simple as DATM_STRM_YR? Especially as we start getting datm-specific streams for mosart compsets as well as ocn/ice? I think the DATM_CLMNCEP_YR_ settings are a very effective way to manage streams simply. @rljacob -- any thoughts?

**Comment by rljacob** [comment]
I agree with rename.  Leave it for another PR.

**Comment by jonbob** [comment]
passes ERS_Ld5.T62_oQU120.CMPASO-NYF.chrysalis_intel, merged to next

**Comment by jonbob** [comment]
merged to master, and DIFFs for ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.mosart-rof_ocn_2way tests blessed. Even though this PR is nominally BFB, this one test was using DATM_CLMNCEP_YR_START/DATM_CLMNCEP_YR_END to specify the year fo JRA-forcing it was using. Previously to this PR, that defaulted to 1958 and after this PR it is 2004 -- so we expect some differences in the results.

I did verify that SMS_Ld3.TL319_EC30to60E2r2.CMPASO-JRA1p4.chrysalis_intel tests are BFB, before and after this merge, so it should not impact the way the ocean component uses JRA-forcing.

**Comment by ndkeen** [comment]
I was trying to run a test after this merge with `SMS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.gcp_gnu.mosart-rof_ocn_2way` but I still see the job trying to download ~1400 files into `/home/inputdata/ocn/jra55/v1.3_noleap`.
is that expected?

Can I assume that a line such as these would trigger attempt to download it?
```
gcp-e3sm10-login0% grep missing TestStatus.log | head
Model datm missing file file1 = '/home/inputdata/ocn/jra55/v1.3_noleap/JRA.v1.3.prec.TL319.1958.171019.nc'
Model datm missing file file2 = '/home/inputdata/ocn/jra55/v1.3_noleap/JRA.v1.3.prec.TL319.1959.171019.nc'
Model datm missing file file3 = '/home/inputdata/ocn/jra55/v1.3_noleap/JRA.v1.3.prec.TL319.1960.171019.nc'
Model datm missing file file4 = '/home/inputdata/ocn/jra55/v1.3_noleap/JRA.v1.3.prec.TL319.1961.171019.nc'
Model datm missing file file5 = '/home/inputdata/ocn/jra55/v1.3_noleap/JRA.v1.3.prec.TL319.1962.171019.nc'
Model datm missing file file6 = '/home/inputdata/ocn/jra55/v1.3_noleap/JRA.v1.3.prec.TL319.1963.171019.nc'
Model datm missing file file7 = '/home/inputdata/ocn/jra55/v1.3_noleap/JRA.v1.3.prec.TL319.1964.171019.nc'
```

**Comment by rljacob** [comment]
Can you look at CaseState in the case dir and see if these xmlchange commands were made?
```
./xmlchange DATM_CLMNCEP_YR_START=2004
./xmlchange DATM_CLMNCEP_YR_END=2004
```

**Comment by ndkeen** [comment]
There were no xmlchanges:
```
gcp-e3sm10-login0% cat CaseStatus 
2022-10-21 18:25:37: case.setup starting 
 ---------------------------------------------------
2022-10-21 18:26:25: case.setup success 
 ---------------------------------------------------
2022-10-21 18:26:27: case.build (SHAREDLIB_BUILD) starting 
 ---------------------------------------------------
2022-10-21 18:32:47: case.build (SHAREDLIB_BUILD) success 
 ---------------------------------------------------
2022-10-21 18:32:49: case.build (MODEL_BUILD) starting 
 ---------------------------------------------------
2022-10-21 18:38:07: case.build (MODEL_BUILD) success 
 ---------------------------------------------------
2022-10-21 18:39:05: case.submit starting 
 ---------------------------------------------------
2022-10-21 18:39:05: case.submit error 
ERROR: Could not find all inputdata on any server
 ---------------------------------------------------
```

**Comment by ndkeen** [comment]
Ah, you know what -- i'm actually testing with `sarich/machinefiles/gcp-update-gcc-12.2` which I assumed was recent enough master to include that change.  But maybe not!

**Comment by ndkeen** [comment]
Just to conclude, false alarm.  The branch I was testing did not have the changes in this PR.  With todays master it seems to work as expected.  Only 8 files are downloaded and the following tests passes:

`ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.gcp_gnu.mosart-rof_ocn_2way`

**Pull request merged**
