### PR TITLE
HOMME: Removed an old kokkos cmd line flag: kokkos-num-devices

### PR DESCRIPTION
**Pull request by abagusetty**
1. Remove a removed kokkos command line flag not applicable anymore
2. Addresses the print statements from each rank

[BFB]

### CODE REVIEW

**Review by bartgol — APPROVED** [review]
Now Kokkos handles selection of device internally, via round robin, right?

**Comment by rljacob** [comment]
What is parsing these command line strings?  Standalone eamxx ?

**Comment by bartgol** [comment]
> What is parsing these command line strings? Standalone eamxx ?

This is standalone hommexx. That is, when we run the HOMMEXX case in CIME.

**Comment by ambrad** [comment]
It's not clear to me this should work on every machine. The key question is whether each ranks sees one device assigned to it by the job run command or multiple devices. This code addresses the second case.

I suggest as an alternative that this updated approach in EKAT be used: https://github.com/E3SM-Project/EKAT/blob/4e36a487d9ced3951907b36a1a16b13325d796d1/src/ekat/ekat_session.cpp.

**Comment by abagusetty** [comment]
Thanks, The above ekat snippet works when the job-schedulers (slurm/pbs) doesnt do the MPI-binding to the GPUs

**Comment by oksanaguba** [comment]
@abagusetty or @ambrad -- i am not following the above, do you guys think this PR is ok or does it still need some modifications? thanks!

**Review by ambrad — CHANGES_REQUESTED** [review]
The ekat session code should be used here as a replacement to make sure we can run on machines where each rank sees all the GPUs on a node.

**Review by ambrad — APPROVED** [review]

**Pull request merged**
