### PR TITLE
WIP Add anvil, melvin hommebfb cmake files

### PR DESCRIPTION
**Pull request by oksanaguba**

### CODE REVIEW

**Comment by rljacob** [comment]
Why are machine-specific cmake pieces needed for this?

**Comment by oksanaguba** [comment]
The way homme nightly (cime) tests are set is that cime calls `cmake -C ${MACHINE}.cmake ...` command to config homme. So, there is a cmake file for each machine. Now we need another cmake file for BFB runs because those will use different compiler flags. These homme builds do not use what's in cime in config_machines.xml, etc.

**Comment by rljacob** [comment]
Ok I see HOMME already has those.

**Comment by rljacob** [comment]
You're going to have add them for every machine we run e3sm_developer or e3sm_integration.

**Comment by oksanaguba** [comment]
i don't have access to all machines. there may be way to disable hommebfb test on many machines.

**Comment by rljacob** [comment]
We'll talk about this on the Thursday IG telecon.

**Comment by oksanaguba** [comment]
Anvil file is ok, melvin testing is an issue (cprnc is not working on a rhel6 machine). Since now the plan is to separate homme testing from e3sm's, closing this pr for now.

**Pull request closed without merging**
