### PR TITLE
Turn on ocean eddy analysis member for RRSwISC6to18E3r5

### PR DESCRIPTION
**Pull request by cbegeman**
Turn on ocean eddy analysis member for RRSwISC6to18E3r5. This allows us to generate EKE plots in MPAS-Analysis.

### CODE REVIEW

**Comment by cbegeman** [comment]
@vanroekel I found the velocity-squared variables in the `timeSeriesStatsMonthly` stream so we don't need to make any changes there once the AM is turned on.

**Review by vanroekel — APPROVED** [review]
Looks good to me.  Thanks @cbegeman

**Review by jonbob — APPROVED** [review]
approved based on visual inspection and testing

**Comment by jonbob** [comment]
Passes:
* ERP_Ld3.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-pioroot1

Should only impact the RRSwISC6to18E3r5 resolution, merged to next

**Pull request merged**
