### PR TITLE
Point to ekat master branch, and fix usage of deprecated kokkos code in Homme

### PR DESCRIPTION
**Pull request by bartgol**
We just merged the kokkos-4.2 branch in ekat/master, so now we can make e3sm point directly to the ekat/master branch, which avoids conflicts when doing a downstream merge into scream repo.

Also, fix usage of deprecated kokkos code in Homme. The tests on e3sm repo are set so that Kokkos allows using deprecated code (with warnings), but it caused some errors downstream in eamxx. Using the non-deprecated code is a simple fix.

### CODE REVIEW

**Review by jgfouca — APPROVED** [review]

**Comment by jgfouca** [comment]
Merged to next.

**Review by ndkeen — COMMENTED** [review]
Can you copy `cime_config/machines/cmake_macros/gnugpu_pm-gpu.cmake` into `cime_config/machines/cmake_macros/gnugpu_muller-gpu.cmake` so they can be consistent?  Then we don't need the other PR https://github.com/E3SM-Project/E3SM/pull/6423

**Comment by jgfouca** [comment]
Should I merge to master or hold off? I assume the additional cmake modification should be made in this PR.

**Comment by bartgol** [comment]
@noel has another PR where he adds the mod to mueller mach file. Since mueller is not part of nightly testing, it's ok to do a separate merge (or merge here, whatever).

That said, I haven't checked whether the next failures have anything to do with this PR (though I doubt it). If you can quickly figure that out, then we can merge.

**Comment by jgfouca** [comment]
The new failures were just some DIFFs for lnd compsets. I will merge.

**Pull request merged**
