### PR TITLE
Resolving conflicts in the chemUCI branch

### PR DESCRIPTION
**Pull request by wlin7**
This is to resolve part of the conflicts in PR #4707 before merging it.
which will ease the eventual merging, meanwhile bringing in compsets
that were not available previously to support testings.

[BFB] for UCI-chem branch

### CODE REVIEW

**Comment by wlin7** [comment]
Hi @tangq , @keziming , the changes here are to resolve part of the conflicts shown in the UCI-chem PR (#4707). It was based on a test merging of the PR to the master. The changes in PR will simplify the eventual merging. 

I also reviewed the conflicts in the three F90 files. Particularly for conflicts in mo_chm_diags.F90, resolving them without rebasing with master would not work, because there are changes in the code (not conflicted) are linked to prescribed aerosol treatment introduced by scream configuration.

Conflicts shown in DryDepVelocity.F90 are easy to resolved, but the master version contains additional changes in two subroutines. Conflicts in tropopause.F90 are about the change from TROP_ALG_CPP to TROP_ALG_E90. I think we are only going to keep TROP_ALG_E90, and TROP_ALG_CPP must have been added after UCI-chem branch started. The conflict will always show up.

**Comment by keziming** [comment]
@wlin7 I am a little confused here. you mentioned F90 files: mo_chm_diags.F90, DryDepVelocity.F90, but I don't see them in the changed files. Does it means we do not need to care these two files in this PR? This PR is to let PR [4707](https://github.com/E3SM-Project/E3SM/pull/4707)  easy to merge into master, right?

**Comment by wlin7** [comment]
> @wlin7 I am a little confused here. you mentioned F90 files: mo_chm_diags.F90, DryDepVelocity.F90, but I don't see them in the changed files. Does it means we do not need to care these two files in this PR? This PR is to let PR [4707](https://github.com/E3SM-Project/E3SM/pull/4707) easy to merge into master, right?

@keziming , sorry for the confusion. You are right, no need to deal with the F90 files in this PR. I decided not to after reviewing the conflicts. We cannot fix the apparent conflicts using the current branch alone (without rebasing), if we still want to run simulation using the branch.

**Comment by rljacob** [comment]
Why not just push more commits to the tangq/atm/UCI-chem branch?

**Comment by wlin7** [comment]
> Why not just push more commits to the tangq/atm/UCI-chem branch?

Good points. I initially intended to also resolve the conflicts in the F90 codes shown in PR #4707. The PR was created for master as a test to show how well the conflicts being resolved, which was then switched to a PR for UCI-chem branch. After reviewing all the conflicts in test merge, I figured there would be intended complication if resolving the code conflicts in #4707 because of of dependency of some new codes in master on other stuff not available in this UCI-chem branch.

**Comment by rljacob** [comment]
This is a case where you could merge master to the feature branch to resolve conflicts and bring it up to date.

**Pull request closed without merging**
