### PR TITLE
Clean printstate in homme

### PR DESCRIPTION
**Pull request by oksanaguba**
Removing redundant code in computing levels for min and max print statements.

### CODE REVIEW

**Comment by oksanaguba** [comment]
i ran master and this branch with output ne4 for 2 days and saw no differences.

**Comment by oksanaguba** [comment]
i built with -g -traceback  -O0 -fpe0 -check  all -check noarg_temp_created -ftrapuv -init=snan , ran, and saw no messages.

**Comment by rljacob** [comment]
@oksanaguba please add a description for this PR.

**Comment by rljacob** [comment]
@oksanaguba is this PR ready?

**Comment by oksanaguba** [comment]
yes. i will try to merge my prs this week.

**Comment by rljacob** [comment]
@oksanaguba can you take care of this?

**Comment by rljacob** [comment]
@oksanaguba can you merge this this week?

**Comment by oksanaguba** [comment]
Running tests on this branch now, sorry for the delay.

**Comment by oksanaguba** [comment]
eam-theta suite looked ok, all pass and I compared output from 1 test, I also ran SMS_D.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetanh_ftype4, pass, and output is ok.

**Comment by oksanaguba** [comment]
in next

**Pull request merged**
