### PR TITLE
Implement SSP5_8.5 future watercycle compset into BGC (maint-v1.1)

### PR DESCRIPTION
**Pull request by cameronsmith1**
This is a porting of the the SSP5_8.5 future watercycle compset from
maint-1.0 to maint-1.1.

[BFB, except for new compset]

### CODE REVIEW

**Comment by cameronsmith1** [comment]
This PR is porting the watercycle compset from maint-1.0 over to maint-1.1.

For reference, the original compset was put inot maint-1.0 using PR https://github.com/E3SM-Project/E3SM/pull/2905 and https://github.com/E3SM-Project/E3SM/pull/2971

I have tested this new implementation by:
+) Confirming the namelists are identical for this compset on maint-1.0 and 1.1 on Cori (except for some changes that appear to be unrelated, that are presumably caused by the prior addition of BGC).
+) The e3sm_prod testsuite passed on Cori (checks maint-1.0).
+) The BGC testsuite passed on Cori (SMS.ne30_oECv3.BGCEXP_CNTL_CNPECACNT_1850, SMS.ne30_oECv3.BGCEXP_CNTL_CNPRDCTC_1850).

**Comment by bishtgautam** [comment]
@jgfouca, @rljacob, This PR has cime and non-cime changes as a single commit. Should the single commit be split into two to avoid any potential issues related to a future merge of `maint-1.1` into `master`?

**Comment by cameronsmith1** [comment]
FWIW, the previous PR (https://github.com/E3SM-Project/E3SM/pull/2905) had nearly identical changes with cime & non-cime changes.  We didn't do split it up, AFAIK, unless @singhbalwinder did something special.

Is it different because it is a maintenance branch?

**Comment by cameronsmith1** [comment]
BTW, to run the configuration you can use the following (on Cori):
```
/global/cscratch1/sd/pjc/SSP585/run_e3sm.SSP585_BGC.csh
```

**Comment by cameronsmith1** [comment]
> 
> 
> @jgfouca, @rljacob, This PR has cime and non-cime changes as a single commit. Should the single commit be split into two to avoid any potential issues related to a future merge of `maint-1.1` into `master`?

I was planning to put these changes onto master manually as soon as this PR is done.  
+) Will that PR need to be split?
+) Will that change avoid a maint-1.1 to master merge problem?

**Comment by jgfouca** [comment]
@cameronsmith1 , @bishtgautam , no need to split. Git can do that automatically.

**Comment by cameronsmith1** [comment]
> 
> 
> @cameronsmith1 , @bishtgautam , no need to split. Git can do that automatically.

Is this true when merging to master too?

**Comment by jgfouca** [comment]
> Is this true when merging to master too?

Yes, we only ever do git subtree splits on our master branch. Our other branches will never be split-out to ESMCI/CIME do it's not an issue for them.

**Comment by cameronsmith1** [comment]
> 
> 
> > Is this true when merging to master too?
> 
> Yes, we only ever do git subtree splits on our master branch. Our other branches will never be split-out to ESMCI/CIME do it's not an issue for them.

I am going to implement my changes onto master soon, so I need to understand this.  Am I correct that?:

+) For master, do separate PRs for CIME and non-CIME.
+) For branches a combined CIME/non-CIME PR is fine.

**Comment by jgfouca** [comment]
@cameronsmith1 , sorry for the confusion. There is no case where you ever need to worry about splitting CIME changes. I was just explaining that, for master, we have scripts to do the splitting. For other branches, they never need to be split.

**Comment by cameronsmith1** [comment]
Thank you for the clarification.  I have had to split cime/non-cime PRs before, so it is great to hear we scripts to do it now.  Thank you to whoever is responsible for the scripts!

**Comment by jgfouca** [comment]
> Thank you to whoever is responsible for the scripts!

You're welcome! (I wrote the scripts :) )

**Comment by cameronsmith1** [comment]
Susannah is away, so I have added Xiaying as a reviewer.

**Comment by singhbalwinder** [comment]
Thanks @jgfouca. @rljacob told me about it a while back when I had a PR with CIME/non-CIME changes. 
I will merge this as soon as @acme-y9s approves. It looks good to me.

**Comment by acme-y9s** [comment]
@cameronsmith1  I looked through all your changes, and they looks good me. I am only curious about the volcano aerosol, it seems we do not have the transient data for the future period, right?
<prescribed_volcaero_datapath>atm/cam/volc                                             </prescribed_volcaero_datapath>
<prescribed_volcaero_file    >CMIP_DOE ACME_radiation_average_18502014_v3_c20171204.nc</prescribed_volcaero_file    >
<prescribed_volcaero_filetype>VOLC_CMIP6					       </prescribed_volcaero_filetype>
<prescribed_volcaero_type    >CYCLICAL						       </prescribed_volcaero_type    >
<prescribed_volcaero_cycle_yr>1                                                        </prescribed_volcaero_cycle_yr>


Thankhs,
Xiaoying

**Comment by cameronsmith1** [comment]
Correct.  Input4MIPS does not provide a future volcano file.

**Comment by cameronsmith1** [comment]
Hi @acme-y9s , Susannah isn't around.  Are you ready to use this compset?   If so, I suggest we go ahead without Susannah's review.

**Pull request merged**
