### PR TITLE
Fixed seaice output stream bug

### PR DESCRIPTION
**Pull request by akturner**
Corrected output stream name from 'output' to 'none' for several analysis members

Fixes https://github.com/E3SM-Project/E3SM/issues/4652

[NML]
[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
@akturner - just a quick question. How would a user turn on history file output now? Just change the output_interval in the streams file?

**Review by jonbob — APPROVED** [review]
I can verify that this PR gets rid of the unexpected hist files

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
passes e3sm_developer tests with active seaice on chrysalis:
* SMS.T62_oQU120_ais20.MPAS_LISIO_TEST
* SMS_P12x2.ne4_oQU240.WCYCL1850NS.chrysalis_intel.allactive-mach_mods
except for expected NML DIFFs

**Comment by akturner** [comment]
@jonbob: Yes, setting output_interval to something other than 'none' in the output stream would turn this back on.

**Comment by jonbob** [comment]
expected NML DIFFs blessed

**Pull request merged**
