### PR TITLE
update mpas-source: Sea ice index allocation bug

### LINKED ISSUE #4018: Attempt to fetch from allocatable variable INDEX_VERTICALAEROSOLSCONC when it is not allocated
On latest `maint-1.0` branch, `./cime/scripts/create_test SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.chrysalis_intel.allactive-v1cmip6` fails with
```
[164] forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable INDEX_VERTICALAEROSOLSCONC when it is not allocated
[164]
[164] Image              PC                Routine            Line        Source
[164] libpnetcdf.so.4.0  0000155548015892  for_emit_diagnost     Unknown  Unknown
[164] e3sm.exe           0000000006D4007F  seaice_column_mp_        8459  mpas_seaice_column.f90
[164] e3sm.exe           0000000006D36984  seaice_column_mp_        7824  mpas_seaice_column.f90
[164] e3sm.exe           0000000006BE89F3  seaice_column_mp_         228  mpas_seaice_column.f90
[164] e3sm.exe           0000000006DDD00A  seaice_initialize         102  mpas_seaice_initialize.f90
[164] e3sm.exe           0000000006B11B2E  seaice_core_mp_mp         255  mpas_seaice_core.f90
[164] e3sm.exe           0000000006B108EB  seaice_core_mp_se         145  mpas_seaice_core.f90
[164] e3sm.exe           00000000043041BB  ice_comp_mct_mp_i         522  ice_comp_mct.f90
[164] e3sm.exe           00000000004639E9  component_mod_mp_         269  component_mod.F90
[164] e3sm.exe           0000000000426BCF  cime_comp_mod_mp_        1198  cime_comp_mod.F90
[164] e3sm.exe           000000000045971F  MAIN__                     92  cime_driver.F90
[164] e3sm.exe           0000000000414FA2  Unknown               Unknown  Unknown
[164] libc-2.28.so       0000155544DFD6A3  __libc_start_main     Unknown  Unknown
[164] e3sm.exe           0000000000414EAE  Unknown               Unknown  Unknown
```

That array is allocated when `config_use_column_biogeochemistry=.true.`, but
```
$ grep -ir "config_use_column_biogeochemistry" mpassi_in 
 config_use_column_biogeochemistry = .false.
```

Relevant `CPP`-ed lines:
```
  224        ! initialize the column package tracer object
  225        call init_column_tracer_object(domain, ciceTracerObject)
  226 
  227        ! initialize the column package parameters
  228        call init_column_package_parameters(domain, ciceTracerObject)
  229 
  230     endif
  231 
  232   end subroutine seaice_init_column_physics_package_parameters
```
```
 7823     ! set the tracers indices
 7824     call init_column_package_tracer_indices(tracerObject)
 7825 
 7826     ! set the column parameters
 7827     call init_column_package_configs(domain)
 7828 
 7829   end subroutine init_column_package_parameters
```
```
 8459     call colpkg_init_tracer_indices(&
 8460          tracerObject % index_surfaceTemperature, &
 8461          tracerObject % index_iceEnthalpy, &
 8462          tracerObject % index_snowEnthalpy, &
 8463          tracerObject % index_iceSalinity, &
 8464          tracerObject % index_brineFraction, &
 8465          tracerObject % index_iceAge, &
 8466          tracerObject % index_firstYearIceArea, &
 8467          tracerObject % index_levelIceArea, &
 8468          tracerObject % index_levelIceVolume, &
 8469          tracerObject % index_pondArea, &
 8470          tracerObject % index_pondDepth, &
 8471          tracerObject % index_pondLidThickness, &
 8472          tracerObject % index_aerosols, &
 8473          tracerObject % index_verticalAerosolsConc, &
```
```
 4610     ! biogeochemistry
 4611     if (config_use_column_biogeochemistry) then
 4612 
 4613        allocate(tracerObject % index_LayerIndexToDataArray(nZBGCTracers))
 4614        allocate(tracerObject % index_LayerIndexToBioIndex(nZBGCTracers))
 4615 
 4616        ! set all indices for biogeochemistry including parent, ancestor and ancestor mask
 4617        call init_column_tracer_object_for_biogeochemistry(domain, tracerObject)
 4618 
 4619     endif
 4620 
 4621   end subroutine init_column_tracer_object
```

### PR DESCRIPTION
**Pull request by mark-petersen**
Allocates bgc tracerObject indices to dimension 1 when not in use. Corrects a compile time error that appears with intel19 compiler versions. BFB with previous version compilers. See https://github.com/MPAS-Dev/MPAS-Model/pull/878. 

fixes #4018
[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
@amametjanov could you check that this solves your problem?

I tried to test on cori, but maint-1.0 appears to be out of date there. Specifically,
- `SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu` fails to compile
- `SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel` fails to run

But the behavior is identical for this PR and the `maint-1.0` branch, so is unrelated to this work.

**Comment by amametjanov** [comment]
On Chrysalis, tried `SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST` with intel and gnu and got the same error with both compilers further into the run:
```
234: forrtl: severe (408): fort: (7): Attempt to use pointer LAYERTHICKNESS when it is not associated with a target
234:
234: Image              PC                Routine            Line        Source
234: libpnetcdf.so.3.0  000015554B41F232  for_emit_diagnost     Unknown  Unknown
234: e3sm.exe           00000000062CFBF3  ocn_tendency_mp_o         191  mpas_ocn_tendency.f90
234: e3sm.exe           0000000005FBFEF6  ocn_time_integrat        1449  mpas_ocn_time_integration_split.f90
234: e3sm.exe           0000000005F8CE29  ocn_time_integrat         121  mpas_ocn_time_integration.f90
234: e3sm.exe           0000000003C98654  ocn_comp_mct_mp_o         962  ocn_comp_mct.f90
234: e3sm.exe           0000000000476AC1  component_mod_mp_         747  component_mod.F90
234: e3sm.exe           000000000044CECB  cime_comp_mod_mp_        3362  cime_comp_mod.F90
234: e3sm.exe           000000000045D774  MAIN__                    103  cime_driver.F90
```
Could you add a fix (initialize `layerThickness`) in this PR?
```
 187       !
 188       ! surface flux tendency
 189       !
 190 
 191       call ocn_thick_surface_flux_tend(meshPool, fractionAbsorbed, fractionAbsorbedRunoff, layerThickness,  &
 192          surfaceThicknessFlux, surfaceThicknessFluxRunoff, tend_layerThickness, err)
```

**Comment by mark-petersen** [comment]
@amametjanov please test again. I fixed the layerThickness bug (https://github.com/MPAS-Dev/MPAS-Model/pull/880), and this branch now passes
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
```

**Comment by jonbob** [comment]
@mark-petersen - we need to be more careful about following the branch naming convention, which says:
````
Convention:  E3SM branch names must have the form:
<Github username>/<source code area or component>/<feature-description>
Use lower-case for everything.  Even your username.
Use hyphens instead of underscores.
````
Can you please change this to use hyphens instead of underscores?

**Comment by amametjanov** [comment]
Thanks, no further run-time errors with intel compiler. These tests pass:
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.chrysalis_intel.allactive-v1cmip6 (this was failing in E3SM-Project/E3SM#4018)
SMS_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.chrysalis_intel.allactive-v1cmip6

SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_gnu
```

**Comment by jonbob** [comment]
merged to maint-1.0

**Comment by jonbob** [comment]
Thanks @akturner and @mark-petersen !

**Pull request merged**
