### PR TITLE
Update MPAS-Ocean for coastal applications

### PR DESCRIPTION
**Pull request by mark-petersen**
Various additions for MPAS-Ocean coastal applications. Includes:
- Addition of COMPASS test cases for coastal.
- Add implicit Rayleigh drag (default off)
- Alterations for wetting/drying (default off)

BFB

### CODE REVIEW

**Comment by jonbob** [comment]
Note: this PR requires [#3014](https://github.com/E3SM-Project/E3SM/pull/3014) as a prerequisite

**Comment by mark-petersen** [comment]
@jonbob this PR is ready to merge. I ran a quick test:
```
./create_test -p acme -q debug --walltime 00:30:00 \
  PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_intel
```
and it passes.

**Comment by mark-petersen** [comment]
There are some odd lines showing up in the `Files changed` tab that have not actually been changed in this PR. For example, on the tab above you can see:
image
But there was no change in e3sm/develop on that line. For some reason, the github screen differences are wrong. Looks like a github bug. 

Here are the last many merges into e3sm/develop. The top one is this PR.
```
git log --oneline --first-parent
75d4cd00 (HEAD -> e3sm/develop) Merge branch 'ocean/develop' into e3sm/develop
b817c60d Merge branch 'ocean/develop' into e3sm/develop
13c4d571 Merge branch 'develop' into e3sm/develop
e8d75edc Merge seaice/develop into e3sm/develop
908b71b2 Merge commit seaice/develop into e3sm/develop
```
and here is that specific line. It's been unchanged for a while:
```
git blame 75d4cd00  -- src/core_ocean/get_BGC.sh |head -n 4|tail -n 1
55a4f9c49 (Xylar Asay-Davis 2019-06-27 17:37:47 +0100   4) BGC_TAG=5588636
git blame b817c60d  -- src/core_ocean/get_BGC.sh |head -n 4|tail -n 1
55a4f9c49 (Xylar Asay-Davis 2019-06-27 17:37:47 +0100   4) BGC_TAG=5588636
git blame 13c4d571 -- src/core_ocean/get_BGC.sh |head -n 4|tail -n 1
55a4f9c49 (Xylar Asay-Davis 2019-06-27 17:37:47 +0100   4) BGC_TAG=5588636
git blame 908b71b2 -- src/core_ocean/get_BGC.sh |head -n 4|tail -n 1
55a4f9c49 (Xylar Asay-Davis 2019-06-27 17:37:47 +0100   4) BGC_TAG=5588636
```
I think a merge from ocean/develop into ocean/coastal confused the github diff tool. I'll look through carefully for any others, and make sure these are only coastal changes.

**Comment by mark-petersen** [comment]
@jonbob There is a small chance these lines will cause this to be a non-BFB merge:
```
src/core_ocean/shared/mpas_ocn_vmix.F
-      A(1)=0
+      A(1)=0.0_RKIND
-         B(N) = 1 - A(N) + dt*implicitBottomDragCoef &
+         B(N) = 1.0_RKIND - A(N) + dt*implicitBottomDragCoef &
```
The old version makes the compiler convert an integer to an 8-byte real. The newer version is correct. Most likely it is a BFB change.

**Comment by mark-petersen** [comment]
@jonbob sorry for the above confusion. I didn't see that I had made this branch on the `mark-petersen` fork. In the future I'll use `E3SM-Project` so we all use the same procedure.

**Comment by xylar** [comment]
@mark-petersen, I think there's been discussion that we have too many branches on E3SM-Projects/E3SM and that people should please use their own forks if they're comfortable doing so.  @rljacob can chime in if he wants to, but my sense is that you should use your fork as you did here.

**Comment by jonbob** [comment]
@xylar - I think the E3SM branches are OK because I can (and do) delete them once the PR's close.

**Comment by xylar** [comment]
Okay, fair enough.

**Comment by mark-petersen** [comment]
Also passes:
```
./create_test -p acme -q debug --walltime 00:30:00 \
  PEM_Ln9.ne30_oECv3wLI.A_WCYCL1850-DIB-ISMF_CMIP6.cori-knl_intel
```

**Comment by jonbob** [comment]
@mark-petersen - it's also fine to use your fork. It's easy enough to merge from there

**Comment by mark-petersen** [comment]
I had not run a comparison run. I see `create_test` has a `--compare` and `--baseline-name` options.  Trying that now...

**Comment by mark-petersen** [comment]
@jonbob I was able to confirm that this merge is BFB (compared coupling files on `ne30_oECv3wLI.A_WCYCL1850-DIB-ISMF_CMIP6`). I think this is all set.

**Comment by jonbob** [comment]
Perfect -- and thank you. I'll get this merged right away.

**Comment by jonbob** [comment]
merged to next
passed SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel

**Comment by jonbob** [comment]
merged to master
@mark-petersen - you can delete this branch from your fork if you want

**Pull request merged**
