### PR TITLE
Add RRTMGP radiative transfer code

### PR DESCRIPTION
**Pull request by brhillman**
Add RRTMGP as an option for radiation (to replace RRTMG eventually). This is a work in progress with some functionality left to implement. Things that are not working: perturbation growth functionality, and threading. This functionality will be fixed in a future PR, but we want to merge this as soon as possible to keep pace with development.

Things that have changed: we now read in the radiation namelist options using a `radiation_readnl` routine that is provided by each radiation package to handle specific options for different radiation parameterizations. `radiation_readnl` routines have been provided for the old RRTMG implementation, as well as the (probably outdated and broken) CAMRT option.

[BFB]

### CODE REVIEW

**Comment by singhbalwinder** [comment]
> perturbation growth functionality

Thanks @brhillman for working on this. Would you please explain a bit what do you mean by the above? Is it something specific to RRTMGP or is it general perturbation growth functionality that the model have? Thanks!

**Comment by brhillman** [comment]
@singhbalwinder there is some code that was recently added to RRTMG that appears to be required for the general perturbation growth functionality that the model has. I am not sure how this works, so I have not implemented this in the RRTMGP interface I have developed here. This is definitely something we should address, and I would be happy to work with you on understanding this and working this in (it appears you added this section of code in RRTMG). But for the time being, I have just omitted it, so I assume perturbration growth tests will not work as expected with the `-rad rrtmgp` option in CAM_CONFIG_OPTS.

**Comment by singhbalwinder** [comment]
Okay, that is something I added for the test. I will implement it for RRTMGP once it is in the master.

**Comment by polunma** [comment]
I have read through the interface and aerosol/cloud optics. So far so good. I want to confirm that the radiation diagnostics still works and will send you a separate email for settings.

**Comment by brhillman** [comment]
@polunma the radiation diagnostics tests you asked for seem to have ran just fine. I did have a sign error on the output for the LWCF...I just pushed a commit that fixes that. All of the single-level fields looks similar between RRTMG and RRTMGP. A couple examples below, showing the net shortwave and longwave clearsky fluxes for the "1" diag call.

fsntc_1
flntc_1

**Comment by brhillman** [comment]
@singhbalwinder it looks like @polunma has approved this. Should be ready to go.

**Comment by singhbalwinder** [comment]
I will merge this to next today if next is open for merging.

**Comment by singhbalwinder** [comment]
@brhillman : This PR seems to be changing the namelist file, is this PR BFB otherwise?

**Comment by brhillman** [comment]
@singhbalwinder yes, the way the radiation namelist is read is changed, so I'm not surprised there are namelist diffs. The PR should be BFB otherwise, but I will rerun the developer suite to make sure.

**Comment by singhbalwinder** [comment]
@brhillman : As this is a change to the radiation codes, you can just run SMS.ne4_ne4.FC5AV1C-L test to generate baselines and compare against the baselines. You don't need to run the entire suite unless you want to run it to ensure everything else is working.

**Comment by brhillman** [comment]
@singhbalwinder I'm running the e3sm_developer suite on edison, but I got a nastygram for using resources for some reason, so I'm re-running with -j 1. I wanted to re-check to make sure I didn't break anything else. So I guess these will run overnight and I will ping you with results when finished.

**Comment by brhillman** [comment]
@singhbalwinder sorry for the delay, I had some diffs in my baseline compares, rebased on master and the diffs appear to have gone away in the first test I did. I am re-running the developer suite now to make sure that fixed it. Something non-BFB must have changed in master since I branched.

**Comment by brhillman** [comment]
@singhbalwinder the tests that were failing baseline compare seem to pass now. There were a few that timed out, and some that failed the throughput test...not sure why that would be. I pushed my changes, that was just a rebase on current master. Should be good to go. Namelists will differ because I moved radiation stuff to a separate radiation_nl.

**Comment by singhbalwinder** [comment]
Great! Thanks @brhillman for running these tests. I will merge this to next.

**Comment by brhillman** [comment]
Awesome, thank you @singhbalwinder!

**Comment by rljacob** [comment]
@singhbalwinder you could merge this to next today.   I assume this is BFB?

**Comment by rljacob** [comment]
@brhillman can you add a test that turns on RRTMGP?

**Comment by singhbalwinder** [comment]
@rljacob : Yes, this is BFB but NML. I have pushed it to next. I will ask for blessing the NML diffs when they appear.

**Comment by brhillman** [comment]
@rljacob yes, sorry I was on vacation last week. I can setup another PR to add an RRTMGP test.

**Pull request merged**
