### PR TITLE
Remove retired LANL machines grizzly and badger.

### PR DESCRIPTION
**Pull request by mark-petersen**
LANL machines grizzly and badger have been retired. This is a clean-up pull request to remove them.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
Passes 
```
./create_test SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.chicoma-cpu_gnu -p t24_coastal_ocean --walltime 00:30:00
```
when added to #6228.

**Review by jonbob — APPROVED** [review]
Approved based on visual inspection. Thanks Mark

**Comment by jonbob** [comment]
passes sanity testing, merged to next

**Comment by jonbob** [comment]
merged to master

**Comment by xylar** [comment]
Goodby Badger and Grizzly!

**Pull request merged**
