### PR TITLE
MPAS-SeaIce E3SM Version 3 Final BFB Cleanup

### PR DESCRIPTION
**Pull request by proteanplanet**
This PR cleans up MPAS-SeaIce with final BFB changes for Version 3, including:

1) Added or updated checks on configuration settings. Checks on values necessary for coupled runs are done in mpas_seaice_initialize.F, and consistency checks for icepack are done in mpas_seaice_icepack.F. Consistency checks for colpkg were not updated (BFB, author: @eclare108213): a) remove config_couple_biogeochemistry_fields (not used); b) correct listed namelist values for config_snow_redistribution_scheme; c) update config consistency checks for icepack; d) rename seaice_check_constants to seaice_check_constants_coupled; e) add subroutine seaice_check_configs_coupled; f) update comment statements

2) Correction of sea ice velocity solver concentration and mass limit to universal constant seaicePuny consistent with changes made with the introduction of Icepack to the code base. The same constant value is used, but it is drawn from a different part of the code, now centralized in one location of constant declarations for Icepack and the MPAS-SeaIce dycore (BFB, authors: @njeffery and @proteanplanet )

3) Completed wiring of floe diameter and floe shape constants from the namelist into Icepack (BFB, author: @proteanplanet )

Testing for this PR was conducted on each individual listed item above, as well as on the PR as a whole.  For the first item, testing of warnings and aborts was done in D, F, and B cases as detailed in a comment below.  For every item D-cases testing was conducted against master at the time of checkout to ensure each item alone was BFB with master.  In addition, the E3SM_ice_developer test suite, comprising D-case SMS, ERS, PEM, and PET tests, was run on each listed item individually as well as on the PR as a whole, and in all cases passed. The PR as a whole was tested in a D-case against master and confirmed to be BFB.

### CODE REVIEW

**Comment by proteanplanet** [comment]
For the first part of this BFB PR, this is the result of the additions and changes:

Tested aborts and warnings in 1-month D cases by changing the default settings as follows:

 ```
   ! abort (tested individually)
         config_frazil_coupling_type = 'internal'
         config_frazil_coupling_type = 'fresh_ice_correction' 
         config_thermodynamics_type = ‘BL99'
         config_sea_freezing_temperature_type = 'linear_salt'
         config_itd_conversion_type = 'delta function'
         config_use_column_shortwave = .false.
         config_use_column_vertical_thermodynamics = .false.
         config_use_column_ridging = .false.
         config_use_form_drag = .true.
         config_use_ocean_mixed_layer = .true.
         config_calc_surface_stresses = .false.
         config_calc_surface_temperature = .false.
         config_include_pond_freshwater_feedback = .true.
         config_update_ocean_fluxes = .false.
         config_category_bounds_type = ‘single category' 

    ! write warnings (tested in groups)
         config_column_physics_type = 'column_package'
         config_shortwave_type = 'ccsm3'
         config_snow_redistribution_scheme = 'bulk'
         config_snow_redistribution_scheme = 'none'
         config_category_bounds_type = 'new'                         
         config_ridging_participation_function = 'Thorndike75'
         config_ridging_redistribution_function = 'Hibler80'
         config_ocean_heat_transfer_type = 'Cdn_ocn'
         config_salt_flux_coupling_type = 'prognostic'
         config_ocean_surface_type = ‘non-free'
         config_use_column_physics = .false.
         config_use_column_itd_thermodynamics = .false.
         config_use_prescribed_ice = .true.
         config_use_snicar_ad = .false.
         config_use_shortwave_redistribution = .true.
         config_use_column_snow_tracers = .false.
         config_use_snow_liquid_ponds = .false.
         config_use_high_frequency_coupling = .false.
         config_limit_air_temperatures = .true.
         config_use_congelation_basal_melt = .false.
         config_use_lateral_melt = .false.
         config_use_latent_processes = .false.

```
Output:

```
CRITICAL ERROR: seaice_check_configs_coupled: config_frazil_coupling_type must be external
CRITICAL ERROR: seaice_check_configs_coupled: config_thermodynamics_type must be mushy
CRITICAL ERROR: seaice_check_configs_coupled: config_sea_freezing_temperature_type must be mushy
CRITICAL ERROR: seaice_check_configs_coupled: config_itd_conversion_type must be linear remap
CRITICAL ERROR: seaice_check_configs_coupled: config_use_column_shortwave must be true
CRITICAL ERROR: seaice_check_configs_coupled: config_use_column_vertical_thermodynamics must be true
CRITICAL ERROR: seaice_check_configs_coupled: config_use_column_ridging must be true
CRITICAL ERROR: seaice_check_configs_coupled: config_use_form_drag = true is not supported
CRITICAL ERROR: seaice_check_configs_coupled: config_use_ocean_mixed_layer must be false in coupled runs
CRITICAL ERROR: seaice_check_configs_coupled: config_calc_surface_stresses must be true
CRITICAL ERROR: seaice_check_configs_coupled: config_calc_surface_temperature must be true
CRITICAL ERROR: seaice_check_configs_coupled: config_include_pond_freshwater_feedback must be false
CRITICAL ERROR: seaice_check_configs_coupled: config_update_ocean_fluxes must be true

WARNING: seaice_check_configs_coupled: config_column_physics_type /= icepack
WARNING: seaice_check_configs_coupled: config_shortwave_type /= dEdd
WARNING: seaice_check_configs_coupled: config_snow_redistribution_scheme /= ITDrdg
WARNING: seaice_check_configs_coupled: config_category_bounds_type /= original
WARNING: seaice_check_configs_coupled: config_ridging_participation_function /= exponential
WARNING: seaice_check_configs_coupled: config_ridging_redistribution_function /= exponential
WARNING: seaice_check_configs_coupled: config_ocean_heat_transfer_type /= constant
WARNING: seaice_check_configs_coupled: config_salt_flux_coupling_type /= constant
WARNING: seaice_check_configs_coupled: config_ocean_surface_type /= free
WARNING: seaice_check_configs_coupled: config_use_column_physics = false
WARNING: seaice_check_configs_coupled: config_use_column_itd_thermodynamics = false
WARNING: seaice_check_configs_coupled: config_use_column_snow_tracers = false
WARNING: seaice_check_configs_coupled: config_use_snow_liquid_ponds = false
WARNING: seaice_check_configs_coupled: config_use_snicar_ad = false
WARNING: seaice_check_configs_coupled: config_use_shortwave_redistribution = true
WARNING: seaice_check_configs_coupled: config_use_high_frequency_coupling = false
WARNING: seaice_check_configs_coupled: config_limit_air_temperatures = true
WARNING: seaice_check_configs_coupled: config_use_latent_processes is not available in icepack
WARNING: seaice_check_configs_coupled: config_use_lateral_melt is not available in icepack
WARNING: seaice_check_configs_coupled: config_use_congelation_basal_melt is not available in icepack
```

Settings that produce warnings in seaice_check_configs_coupled may abort later, e.g.

```
CRITICAL ERROR: check_column_package_configs: nCategories /= 1 .and. config_category_bounds_type = 'single category'
ERROR: Use config_itd_conversion_type = 'delta function' with config_category_bounds_type = 'original'
CRITICAL ERROR: or for column configurations use config_category_bounds_type = 'single category'
CRITICAL ERROR: Prescribed ice mode: Dynamics must be off (config_use_dynamics = false)
```

1-month F cases (prescribed ice) complete successfully for both icepack and colpkg and are BFB with each other and with the previous version of the code. The pre-existing warning statements are printed, but seaice_check_configs_coupled does not throw a warning.

Note that these 2 settings are different in D and B cases, and thus generate warnings rather than aborts:

```
WARNING: seaice_check_configs_coupled: config_ocean_surface_type /= free
WARNING: seaice_check_configs_coupled: config_limit_air_temperatures = true

```

**Review by eclare108213 — APPROVED** [review]
Approved based on visual inspection and developer testing.

**Review by njeffery — APPROVED** [review]
Approved by inspection and tested the BGC configuration in the stand-alone ISPOL testcase.  BFB

**Review by erinethomas — APPROVED** [review]

**Comment by jonbob** [comment]
@proteanplanet -- this PR seems to encompass more than a single improvement, even if they are all BFB. Would you feel OK about breaking it into multiple PRs, with one topic per PR?

**Comment by proteanplanet** [comment]
@jonbob and I just talked. He will probably split up this PR, but with no needed extra input from any of us as authors and reviewers.

**Comment by rljacob** [comment]
This PR is being split up.

**Pull request closed without merging**
