### PR TITLE
add theta-l namelists for benchmarks

### PR DESCRIPTION
**Pull request by oksanaguba**
NEw namelists are created for theta-l hydro and nonhydro versions for NGGPS and V1 benchmarks for both Euler and SL transport. There will also be namelists for ne1024 (3km). 

Note that all new namelists will use lim9.

wip as these tests probably need to be tried for at least a few time steps.

### CODE REVIEW

**Comment by mt5555** [comment]
my first thought is that this NL is so we can compare the openACC code with HOMMEXX, and hence the theta-l model should be using the same namelist as preqx?

**Comment by ambrad** [comment]
Thanks for preparing these. I'd like clarification on the `-h-` versions.
1. Are these intended to be used by both preqx and theta-l?
2. If so, do the `-h-` versions reflect optimal settings as currently understood?

**Comment by oksanaguba** [comment]
no, only *theta* files are for theta. preqx nl is v1-ne120. for the second question, there should be no differences for H theta and preqx. i tried to reorg parameters tho, just to make it easier to keep track of things. maybe it was a bad idea cause now one cannot use diffs well for control. i may come up with a solution.

**Comment by mt5555** [comment]
One minor change:  we only need one namelist for the hydrostatic model, so can merge the two H namelists into one?

**Comment by oksanaguba** [comment]
I thought this PR should be deleted -- don't we have your PR instead? I must say I won't run namelists from your PR anyway, but I will document which namelists I ran and I will give you diffs (which will be like in statefreq and restartfreq).

**Pull request merged**
