### PR TITLE
Added prescribed ice mode to MPAS-Seaice component

### PR DESCRIPTION
**Pull request by akturner**
Added prescribed ice mode to MPAS-Seaice component. This involves modifications to MPAS-Seaice as well as modifications in E3SM.

[BFB] for all tested configurations

### CODE REVIEW

**Comment by jonbob** [comment]
@akturner - just a couple of things about this PR. First, let me use the automated scripts to regenerate the bld-namelist scripts -- just because we'll get rid of some unexpected diffs. But the file changes in mpas-source also show some ocean files? That doesn't seem right...

**Comment by jonbob** [comment]
OK, the ocean changes in the mpas-source diff was just the wrong base for comparison, so that's not an issue. But many of the changes you've added by hand in the mpas-seaice bld-namelist files don't get automatically generated using the scripts, so either a reference to them is missing from Registry or something is broken. I'm not sure how to proceed

**Review by proteanplanet — APPROVED** [review]
This appears to be correct on inspection.  Importantly, if there are problems, they don't appear to affect any other configuration.  

I would like to make it clear that this _will not_ produce the same results as using CICE in E3SM F-case simulations, and nor should it be expected to.  MPAS-SI includes a number of improvements and fixes that do not exist in the current implementation of CICE in E3SM.   The results that MPAS-SI produces would most likely be more trustworthy than our current prescribed ice mode.

(changes to namelist_defaults_mpassi.xml  and buildnml will be merged with changes from https://github.com/E3SM-Project/E3SM/pull/3846 and coming from branch https://github.com/E3SM-Project/E3SM/tree/proteanplanet/polar/v2output)

**Comment by jonbob** [comment]
merged to next. @akturner - we can talk on Monday if you're happy with the changes. We can revert this PR and rework if necessary

**Comment by jonbob** [comment]
reverted from next -- the build-namelist changes made the new prescribed ice mode non-functional so it will have to be reworked so the automated scripts can generate the build-namelist files correctly. It also caused some build failures using gnu

**Comment by akturner** [comment]
Will redo another branch with changes requested

**Pull request closed without merging**
