### PR TITLE
Hommexx/SCREAM: Fix four SCREAM issues.

### PR DESCRIPTION
**Pull request by ambrad**
* Hommexx: Fix a missing team barrier.
* Hommexx: Fix team size in debug build.
* Hommexx: Fix nsplit<1 message.
* Hommexx: Fix compute_diagnostics rule.
* Hommexx/SL: Fix enum-comparison warning.

Fixes SCREAM issue 1691 (https://github.com/E3SM-Project/scream/issues/1691).
Fixes SCREAM issue 1485 (https://github.com/E3SM-Project/scream/issues/1485).
Fixes SCREAM issue 1749 (https://github.com/E3SM-Project/scream/issues/1749).
Fixes SCREAM issue 1721 (https://github.com/E3SM-Project/scream/issues/1721).

[BFB]

### CODE REVIEW

**Comment by ambrad** [comment]
Changes were tested in SCREAM on Perlmutter. Will report Chrysalis tests later.

**Comment by ambrad** [comment]
e3sm_developer and homme_integration pass on Chrysalis, with the exception of NLFAILs due I think to some blessing issues on master unrelated to this PR.

**Comment by ambrad** [comment]
ne30, statefreq=480, SL transport, 16 GPUs, 1 hour limit ran 4041 steps before running out of time. The qv(1) Homme diagnostic output looks solid.

**Comment by ambrad** [comment]
@bartgol the cmake stuff is orthogonal to this PR. Note that all this particular bug fix does is make RemapFunctor do the right thing. This PR as is has the virtue of being straightforward bug fixes, without cmake mess. A future PR can mod the ExeSpaceDefs stuff if desired to use a cmake-defined symbol. This current PR fixes the issue on both Summit and PM.

**Review by jgfouca — APPROVED** [review]

**Comment by ambrad** [comment]
Re: SCREAM issues 1749 and 1721, I ran with these changes in the SCREAM repo on Perlmutter on 16 GPUs. The nsplit message is printed to e3sm.log just once. homme_atm.log diagnostic output is identical to before the compute_diagnostics fix, and the run is much faster.

**Comment by ambrad** [comment]
I reran eam_theta_pg2,  ERS.ne4_oQU240.F2010.chrysalis_intel.eam-hommexx, and homme_integration withe the new commits and they pass. I'm skipping rerunning e3sm_developer beyond eam_theta_pg2 because the new commits are for Hommexx runs only.

**Review by bartgol — APPROVED** [review]

**Pull request merged**
