### PR TITLE
Add NL tests

### PR DESCRIPTION
**Pull request by oksanaguba**
Add NL tests. Off by default. Needed for very rare occasion when dycore settings change.
Run with
```
test=eam_nl
suff='--no-build'

#generate baseline from master
${master}/cime/scripts/create_test ${suff} -g -o --baseline-root ${baselinefold} -b master ${test}
```

[BFB]

### CODE REVIEW

**Comment by oksanaguba** [comment]
We need to tests grids for preqx and theta dycores.
The list of tests is
```
            "SMS.ne4_ne4.FC5AV1C-L.eam-thetahy_ftype0",
            "SMS.ne11_ne11.FC5AV1C-L.eam-thetahy_ftype0",
            "SMS.ne16_ne16.FC5AV1C-L.eam-thetahy_ftype0",
            "SMS.ne30_ne30.FC5AV1C-L.eam-thetahy_ftype0",
            "SMS.ne45pg2_r05_oECv3.FC5AV1C-L.allactive-thetadycore",
            "SMS.ne120_ne120.FC5AV1C-L.eam-thetahy_ftype0",
            "SMS.ne240_ne240.FC5AV1C-L.eam-thetahy_ftype0",
            "SMS.ne512np4_360x720cru_ne512np4.FC5AV1C-L.allactive-thetadycore",
            "SMS.ne1024np4_360x720cru_ne1024np4.FC5AV1C-L.allactive-thetadycore",
            "SMS.conusx4v1_conusx4v1.FC5AV1C-L.eam-thetahy_ftype0",
            "SMS.enax4v1_enax4v1.FC5AV1C-L.eam-thetahy_ftype0",
            "SMS.northamericax4v1_r0125_northamericax4v1.FC5AV1C-L.eam-thetahy_ftype0",
            "SMS.antarcticax4v1_r0125_antarcticax4v1.FC5AV1C-L.allactive-thetadycore",
            "SMS.antarcticax4v1pg2_r0125_antarcticax4v1pg2.FC5AV1C-L.allactive-thetadycore",
            "SMS.ne4_ne4.FC5AV1C-L.eam-preqx_ftype0",
            "SMS.ne11_ne11.FC5AV1C-L.eam-preqx_ftype0",
            "SMS.ne16_ne16.FC5AV1C-L.eam-preqx_ftype0",
            "SMS.ne30_ne30.FC5AV1C-L.eam-preqx_ftype0",
            "SMS.ne45pg2_r05_oECv3.FC5AV1C-L.allactive-preqxdycore",
            "SMS.ne120_ne120.FC5AV1C-L.eam-preqx_ftype0",
            "SMS.ne240_ne240.FC5AV1C-L.eam-preqx_ftype0",
            "SMS.ne512np4_360x720cru_ne512np4.FC5AV1C-L.allactive-preqxdycore",
            "SMS.ne1024np4_360x720cru_ne1024np4.FC5AV1C-L.allactive-preqxdycore",
            "SMS.conusx4v1_conusx4v1.FC5AV1C-L.eam-preqx_ftype0",
            "SMS.enax4v1_enax4v1.FC5AV1C-L.eam-preqx_ftype0",
            "SMS.northamericax4v1_r0125_northamericax4v1.FC5AV1C-L.eam-preqx_ftype0",
            "SMS.antarcticax4v1_r0125_antarcticax4v1.FC5AV1C-L.allactive-preqxdycore",
            "SMS.antarcticax4v1pg2_r0125_antarcticax4v1pg2.FC5AV1C-L.allactive-preqxdycore",
```
was created from list of grids in EAM in components/eam/bld/namelist_files/namelist_defaults_cam.xml and in config_grids.xml . Some of cime grids did not work, some resolutions in eam config were only available via trigrid setup (so, testsmods for allactive were added).

Running 2 branches takes 10-15 min.

**Comment by rljacob** [comment]
I'm told the SBN test type should work.   Would that be a better way to implement this?

**Comment by oksanaguba** [comment]
@rljacob thanks, switched.

**Comment by rljacob** [comment]
I mean if its broken, thats a bug and it should be fixed then we can use it.  I'm not sure its working in current master.

**Comment by oksanaguba** [comment]
Without no-build it does not work:
```
Starting SHAREDLIB_BUILD for test SBN.ne4_ne4.FC5AV1C-L.anvil_intel.eam-preqx_ftype0 with 1 procs
Finished SHAREDLIB_BUILD for test SBN.ne4_ne4.FC5AV1C-L.anvil_intel.eam-preqx_ftype0 in 0.334281 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /lcrc/group/acme/ac.onguba/acme_scratch/anvil/SBN.ne4_ne4.FC5AV1C-L.anvil_intel.eam-preqx_ftype0.20201125_230823_cehlub
    Errors were:
        Building test for SBN in directory /lcrc/group/acme/ac.onguba/acme_scratch/anvil/SBN.ne4_ne4.FC5AV1C-L.anvil_intel.eam-preqx_ftype0.20201125_230823_cehlub
        ERROR: Test SBN not found, aborting

Due to presence of batch system, create_test will exit before tests are complete.
To force create_test to wait for full completion, use --wait
At test-scheduler close, state is:
FAIL SBN.ne4_ne4.FC5AV1C-L.anvil_intel.eam-preqx_ftype0 (phase SHAREDLIB_BUILD)
```

**Comment by oksanaguba** [comment]
Just to be clear when i switched to SBN tests it worked the same as SMS tests since the suite was called with 'no-build'. So let me knwo what you want me to do, to keep it as is?

**Comment by oksanaguba** [comment]
this needs another change

**Comment by jgfouca** [comment]
We probably need to fix SBN in CIME.

**Comment by oksanaguba** [comment]
this is ready

**Comment by rljacob** [comment]
merged to next

**Pull request merged**
