### PR TITLE
Adding support for ADIOS in MPAS

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Adding support for the ADIOS I/O format

[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
@xylar - can you please take a look at this and make sure it (or PR #5489 which I already merged) won't impact standalone mpas-o?

**Comment by xylar** [comment]
@jonbob, I'm really glad you pinged me because I would have thought this was a no-brainer.  I'm seeing 2 thread decomposition tests failing on Chrysalis with Intel and OpenMPI:
```
ocean/baroclinic_channel/10km/decomp_test
  * step: initial_state
  * step: 4proc
  * step: 8proc
  test execution:      SUCCESS
  test validation:     FAIL
  see: case_outputs/ocean_baroclinic_channel_10km_decomp_test.log
  test runtime:        00:03
ocean/global_ocean/QU240/PHC/decomp_test
  * step: 4proc
  * step: 8proc
  test execution:      SUCCESS
  test validation:     FAIL
  see: case_outputs/ocean_global_ocean_QU240_PHC_decomp_test.log
  test runtime:        00:58
```

@jonbob and @jayeshkrishna, could you take a look and see if there are any obvious changes that might explain threading problems?  The differences across thread counts are at machine precision but aren't bit-for-bit, which we can't allow.

**Comment by xylar** [comment]
My tests are in:
```
/lcrc/group/e3sm/ac.xylar/compass_1.2/chrysalis/test_20230310/pr_adios
```

**Comment by xylar** [comment]
It occurs to me that I haven't tested on the latest `master`.  The treading issue could have come from a previous merge.

**Comment by xylar** [comment]
I see.  This branch is off of a very old branch (from November).  I'll try doing a test merge with the current master and running again.  (Thankfully, my tests on `master` are working fine.)

**Comment by xylar** [comment]
After the merge with `master`, the `pr` test suite passes on Chrysalis with Openmpi.  Sorry for the confusion earlier.

**Review by xylar — APPROVED** [review]

**Comment by jonbob** [comment]
@xylar -- whew, I'm so glad to hear it was OK in the end. I'll be more aware and include you on any PRs that touch those kinds of MPAS files

**Review by jonbob — APPROVED** [review]
Approved based on testing inside E3SM and Xylar's mpas-o tests

**Comment by jonbob** [comment]
passes:
* SMS_D_Ld3.T62_oQU120.CMPASO-IAF.chrysalis_intel
* SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod

merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
