### PR TITLE
Update MPAS framework

### PR DESCRIPTION
**Pull request by mark-petersen**
Merge MPAS framework into mpas-source. This includes the following individual PRs. Some of these are atmospheric PRs. Many are additions to the make files for summit, or optional libraries.
* bc36f1971 Merge PR https://github.com/MPAS-Dev/MPAS-Model/pull/629 'az/azamat/mpas-cmake/mpas-tool-dir' into develop
* 9cb179c8b Merge branch 'init_atmosphere/kd_tree_ties' into develop (PR https://github.com/MPAS-Dev/MPAS-Model/pull/630)
* 30e08d651 Merge PR https://github.com/MPAS-Dev/MPAS-Model/pull/616 'mark-petersen/framework/add_FillValue' into develop
* b1e06735e Merge PR https://github.com/MPAS-Dev/MPAS-Model/pull/613 'mark-petersen/framework/add_lapack_option' into develop
* 6525f330e Merge PR https://github.com/MPAS-Dev/MPAS-Model/pull/578 'amametjanov/framework/nullify-field-pointers' into develop
* 59ab157aa Merge PR https://github.com/MPAS-Dev/MPAS-Model/pull/603 'framework/makefile_e3sm' into develop
* ac75ea7b2 Merge PR https://github.com/MPAS-Dev/MPAS-Model/pull/594 'xylar/framework/make_shell_bash' into develop
* 8969cb572 Merge branch 'registry/missing_value' into develop (PR https://github.com/MPAS-Dev/MPAS-Model/pull/562)
* 0f36b10dc Merge PR https://github.com/MPAS-Dev/MPAS-Model/pull/592 'pwolfram/updates_make_intel_stack' into develop
* 5e12fea2f Merge PR https://github.com/MPAS-Dev/MPAS-Model/pull/449 'az/azamat/framework/pgi-cpr-omp-workaround' into develop
* 067fe20a4 Merge PR https://github.com/MPAS-Dev/MPAS-Model/pull/579 'az/framework/e3sm-cmake-qnosmp-typo' into develop
* 0fda9ab5b Merge branch 'xylar/compass/add_prerequisite_tag' into develop
* b6cb09736 Merge branch 'atmosphere/fix_timekeeping_imports' into develop (PR https://github.com/MPAS-Dev/MPAS-Model/pull/582)
* 1294a6557 Merge pull request #575 from xylar/fix_docs_ci
* 51828a158 Merge PR https://github.com/MPAS-Dev/MPAS-Model/pull/472 'xylar/add_compass_docs' into develop
* 2f75bc526 Merge PR https://github.com/MPAS-Dev/MPAS-Model/pull/536 'philipwjones/framework/summitmake' into develop
* b2178d8b8 Merge branch 'atmosphere/atm_core_cleanup' into develop (PR https://github.com/MPAS-Dev/MPAS-Model/pull/548)
* 1518b36ff Merge branch 'init_atmosphere/parse_geoindex' into develop (PR https://github.com/MPAS-Dev/MPAS-Model/pull/459)
* eff73b1e1 Merge PR https://github.com/MPAS-Dev/MPAS-Model/pull/467 'xylar/compass/add_copy_file' into develop
* 7a7070b69 Merge branch 'init_atmosphere/kd_tree' into develop (PR https://github.com/MPAS-Dev/MPAS-Model/pull/438)
* c2be82f16 Merge branch 'init_atmosphere/mpas_stack' into develop (PR https://github.com/MPAS-Dev/MPAS-Model/pull/426)
* 9d7672405 Merge branch 'operators/add_mpas_in_cell' into develop (PR https://github.com/MPAS-Dev/MPAS-Model/pull/400)

Fixes E3SM-Project/E3SM#3396
Fixes E3SM-Project/E3SM#3236

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
@matthewhoffman and @akturner I compiled ocean, seaice, and landice cores on grizzly with gnu, intel17, and intel19, without any trouble. I ran the ocean nightly regression suite with those with debug and optimized. 

In E3SM, I merged `develop` into `e3sm/develop` and it passes:
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
```
so there doesn't appear to be any trouble.

**Comment by mark-petersen** [comment]
@amametjanov I added you to the reviewer list because you have a number of makefile commits for summit. Please check that this PR runs correctly on summit, and if there is anything missing for  the update.

**Comment by amametjanov** [comment]
Ran `SMS_P36_Ld1.T62_oQU120_ais20.MPAS_LISIO_TEST` on 2 Summit nodes with this branch and 8 combinations of
- ibmgpu and pgigpu
- debug and ndebug
- pureMPI and threaded

All 4 ibmgpu tests PASS. No activity on GPU, because OpenMP_offload for ICE has not been merged yet and no port for OCN yet.

For pgigpu:
1. PASS: SMS_P36_Ld1.T62_oQU120_ais20.MPAS_LISIO_TEST.summit_pgigpu
2. FAIL: SMS_P36_Ld1_D.T62_oQU120_ais20.MPAS_LISIO_TEST.summit_pgigpu, but PASS after updating pgi from 19.9 to 19.10
3. FAIL: SMS_P36x2_Ld1.T62_oQU120_ais20.MPAS_LISIO_TEST.summit_pgigpu -- run-time OOM error
4. FAIL: SMS_P36x2_Ld1_D.T62_oQU120_ais20.MPAS_LISIO_TEST.summit_pgigpu -- run-time OOM error

For cases 3 and 4, increasing `OMP_STACKSIZE` from 128M to 512M did not help: these can be looked into later, errors are not due to this PR.
For case 2, pgi 19.9 is known to cause index out-of-bounds errors in ATM too (ICE here).
In case 1, `nvprof` reported activity on GPU for `ocn_equation_of_state_jm_density` kernels. Good!

**Comment by mark-petersen** [comment]
Rebased. I merged MPAS develop branch into e3sm/develop, so the submodule for this PR is pointing to the final version now.

**Comment by mark-petersen** [comment]
Tested with the rebased code. Passes:
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_gnu
PET_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-knl_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PEM_Ln3_P512.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_intel
```
Also, the ocean core regression suite was bfb with previous using both gnu and intel, in stand-alone MPAS.

**Comment by mark-petersen** [comment]
@matthewhoffman and @akturner if you could approve today based on my testing, or further testing of your own cores, that would be helpful.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
