### PR TITLE
Mosart dam bug fix

### PR DESCRIPTION
**Pull request by hydrotian**
Fixing a bug related to MOSART water management scheme. Move the
dam looping outside of the active stage checking.

### CODE REVIEW

**Review by tanzeli1982 — APPROVED** [review]

**Comment by rljacob** [comment]
@hydrotian which cases will this affect?

**Comment by hydrotian** [comment]
This only affects the cases that turn on MOSART water management feature. Should be BFB as none of the land testing case turns water management on.

**Comment by rljacob** [comment]
Do we have any test cases that turn on the MOSART water management feature?

**Comment by hydrotian** [comment]
So far we don't. I plan to create a test case that turns on all the water related features developed for V2 BGC, after this PR is merged.

**Pull request merged**
