### PR TITLE
Add smaller PE-layouts for tests on Anvil

### PR DESCRIPTION
**Pull request by amametjanov**
Add smaller PE-layouts for tests on Anvil to get faster queue throughput.

[NML] - in cime_pes namelists
[non-BFB] - in mpaso.hist.am.globalStats outputs

### CODE REVIEW

**Comment by amametjanov** [comment]
Baseline-compare run of `e3sm_prod` with this branch: https://my.cdash.org/viewTest.php?=buildid=2309924 .

**Comment by rljacob** [comment]
That baseline compare is reporting diffs but none of the cprnc outputs seem to have a diff.  There shouldn't be any diffs if we just changed to pelyaout.

**Comment by amametjanov** [comment]
It appears that some of the diffs are not getting appended to the output:
```
2023-03-24 19:39:12: Comparing hists for case 'SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850-1pctCO2.anvil_intel.allactive-wcprod_1850_1pctCO2.C.20230324' 
dir1='/lcrc/group/e3sm/azamat/scratch/anvil/pes/20230323/e3sm_prod/SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850-1pctCO2.anvil_intel.allactive-wcprod_1850_1pctCO2.C.20230324/run', suffix1='',
dir2='/lcrc/group/e3sm/baselines/anvil/intel/master/SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850-1pctCO2.anvil_intel.allactive-wcprod_1850_1pctCO2' suffix2=''
...
  comparing model 'mpaso'
    SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850-1pctCO2.anvil_intel.allactive-wcprod_1850_1pctCO2.C.20230324.mpaso.hist.am.globalStats.0001-01-01.nc.base did NOT match mpaso.hist.am.globalStats.0001-01-01.nc.base
    cat /lcrc/group/e3sm/azamat/scratch/anvil/pes/20230323/e3sm_prod/SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850-1pctCO2.anvil_intel.allactive-wcprod_1850_1pctCO2.C.20230324/run/SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850-1pctCO2.anvil_intel.allactive-wcprod_1850_1pctCO2.C.20230324.mpaso.hist.am.globalStats.0001-01-01.nc.base.cprnc.out
```
I think AM-file diffs are expected (due to non-reprosum global sums).

**Review by rljacob — APPROVED** [review]

**Comment by jgfouca** [comment]
@rljacob , no idea

**Comment by jonbob** [comment]
@rljacob -- the NML DIFF looks likes it's due to PR #5541, which added 'config_output_reference_time'?

**Comment by amametjanov** [comment]
I had to double PEs for `ne30pg2_EC30to60E2r2 + WCYCL1850` to avoid OOM in ERP+PEM integration tests (case2 runs).
Baseline compare of `e3sm_prod` has the same outcomes: https://my.cdash.org/viewTest.php?buildid=2311249
Full `e3sm_integration` has same pass/fail outcomes as the current PEs: https://my.cdash.org/viewTest.php?buildid=2311251 .

**Pull request merged**
