### PR TITLE
Add CMPASO-JRA1p4 compset for testing

### PR DESCRIPTION
**Pull request by jonbob**
Adds a new compset with active ocean only but using JRA1p4 forcing for datm and drof.

[BFB] for all tested configurations

### CODE REVIEW

**Review by vanroekel — APPROVED** [review]
approved by visual inspection -- comparison with CMPASO-IAF and GMPAS-JRA1p4 show these changes are as expected.

**Comment by jonbob** [comment]
on a hunch, I cherry-picked the commit from [PR #4589](https://github.com/E3SM-Project/E3SM/pull/4589) which corrects the calculation of the solar zenith angle for some data model applications -- and the exact restart test that previously failed now passes. @proteanplanet, could you please complete your review of that PR soon, since it is impacting some configurations?

**Comment by jonbob** [comment]
@rljacob - is it OK to merge this PR since it only adds a compset alias, even if a typical test using it fails? It is documented as having a support level of "Experimental, under development"

**Comment by rljacob** [comment]
Yes that's fine.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
