### PR TITLE
Fixed column abort bug

### PR DESCRIPTION
**Pull request by akturner**
Fixed bug where an abort in step_therm1 would not abort the code 
Cleaned up abort code in column
Added abort code for step_snow

Fixes https://github.com/E3SM-Project/E3SM/issues/5210

[BFB]

### CODE REVIEW

**Comment by njeffery** [comment]
@akturner :  when I try to compile mpas-seaice on chrysalis with gfortran, debug=true, I get this error:
                                                                                                                                     
mpas_seaice_column.F:2042:17:                                                                                                        
                                                                                                                                     
 2042 |              exit                                                                                                            
      |                 1                                                                                                            
Error: EXIT statement at (1) terminating !$OMP DO loop                                                                               
mpas_seaice_column.F:2450:17:                                                                                                        
                                                                                                                                     
 2450 |              exit                                                                                                            
      |                 1                                                                                                            
Error: EXIT statement at (1) terminating !$OMP DO loop

**Comment by akturner** [comment]
@njeffery: I have made changes that should allow compilation now. Please retest

**Comment by akturner** [comment]
@amametjanov: Changes for omp parallel loop to mpas-seaice removed an exit statement. This broke the abort system. Please review the changes made to fix the abort system and ensure these changes work with the omp pragmas. Thanks!

**Comment by rljacob** [comment]
Needs review by @amametjanov @njeffery

**Review by njeffery — APPROVED** [review]
Passed all mpas standalone tests.  Code changes look good.

**Comment by jonbob** [comment]
@amametjanov - I know you've been on vacation but when you get a chance could you please review this? Thanks!

**Review by amametjanov — APPROVED** [review]

**Comment by jonbob** [comment]
Passes:
* SMS_D_Ld1.T62_oEC60to30v3.DTESTM.chrysalis_intel
* ERS.ne11_oQU240.WCYCL1850NS.chrysalis_intel
* SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod

merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
