### PR TITLE
Add cmake config files to HOMME for the cori-gpu testbed

### PR DESCRIPTION
**Pull request by ndkeen**
Add with/without cuda cmake config files for testing HOMME on cori-gpu with nvidia compilers (formerly pgi).

As an example, to build on cori-gpu with cuda:

```
setenv OMPI_CXX $REPO/components/homme/../../externals/kokkos/bin/nvcc_wrapper
setenv NVCC_WRAPPER_DEFAULT_COMPILER "pgc++"

cmake VERBOSE=1 -C $REPO/components/homme/cmake/machineFiles/cori-gpu-hpcsdk.cmake \
   -DQSIZE_D=10 -DPREQX_PLEV=128 -DPREQX_NP=4 \
   -DKokkos_ENABLE_SERIAL=TRUE \
   -DKokkos_ENABLE_OPENMP=FALSE \
   -DBUILD_HOMME_WITHOUT_PIOLIBRARY=TRUE \
   -DBUILD_HOMME_THETA_KOKKOS=TRUE \
   -DHOMME_ENABLE_COMPOSE=TRUE \
   -DENABLE_OPENMP=FALSE \
   -DENABLE_HORIZ_OPENMP=FALSE \
   -DENABLE_COLUMN_OPENMP=FALSE \
   -DBUILD_HOMME_SWEQX=FALSE \
   -DHOMME_PROJID=e3sm \
   -DBUILD_HOMME_SWIM=FALSE \
   -DHOMMEXX_GB_CONFIG=TRUE \
   -DCMAKE_BUILD_TYPE=Release \
   -DBASE_FFLAGS="" \
   -DCMAKE_Fortran_FLAGS_RELEASE="-gopt -O3" \
   -DPREQX_USE_ENERGY=FALSE $HOMME
```

To build on cori-gpu without cuda:

```
cmake VERBOSE=1 -C $REPO/components/homme/cmake/machineFiles/cori-gpu-nocuda-hpcsdk.cmake \
   -DQSIZE_D=10 -DPREQX_PLEV=128 -DPREQX_NP=4 \
   -DKokkos_ENABLE_SERIAL=TRUE \
   -DKokkos_ENABLE_OPENMP=FALSE \
   -DBUILD_HOMME_WITHOUT_PIOLIBRARY=TRUE \
   -DBUILD_HOMME_THETA_KOKKOS=TRUE \
   -DHOMME_ENABLE_COMPOSE=TRUE \
   -DENABLE_OPENMP=FALSE \
   -DENABLE_HORIZ_OPENMP=FALSE \
   -DENABLE_COLUMN_OPENMP=FALSE \
   -DBUILD_HOMME_SWEQX=FALSE \
   -DHOMME_PROJID=e3sm \
   -DBUILD_HOMME_SWIM=FALSE \
   -DHOMMEXX_GB_CONFIG=TRUE \
   -DCMAKE_BUILD_TYPE=Release \
   -DCMAKE_Fortran_FLAGS_RELEASE="-gopt -O3" \
   -DPREQX_USE_ENERGY=FALSE $HOMME
```

Note I needed to downgrade the default optimizations for the fortran build as I hit internal compiler error. Default includes `-fast` and I found that setting to `-gopt -O3` seems to avoid that issue.

### CODE REVIEW

**Comment by oksanaguba** [comment]
It seems that the gnu code is not running yet? Should this PR wait till the issues are resolved? Also, if you don't mind, would you please post your build and run scripts (and maybe results) somewhere (not in the homme repo), maybe, your fork, for future references? I am not sure there is a need to put these files in homme repo yet but if they are documented, build and run scripts also need to be, with env details, modules, etc. thanks!

**Review by oksanaguba — CHANGES_REQUESTED** [review]
wait till issues with gnu runs are resolved.

**Comment by oksanaguba** [comment]
gpu, not gnu

**Comment by ndkeen** [comment]
I'm debugging the runtime issues when I try on the GPU. But I was thinking having these files in the repo would allow others to also try the same thing.

**Comment by oksanaguba** [comment]
it does not have to be a PR, could be a branch?

**Comment by ndkeen** [comment]
Yea that's fine too.

**Pull request closed without merging**
