### PR TITLE
Nonhydrostatic formulation for MPAS-Ocean

### PR DESCRIPTION
**Pull request by scalandr**
This PR is adding a nonhydrostatic capability to MPAS-Ocean. The formulation has been changed including:

- A new equation for the vertical momentum. 
- A new nonhydrostatic pressure contribution (in addition to the standard hydrostatic one).

At every time-step, a three-dimensional elliptic equation that governs the nonhydrostatic pressure is solved. The external PETSc library is used for the solution of this elliptic equation. A new namelist section named `nonhydrostatic_pressure` is present, where the flag
`config_enable_nonhydrostatic_mode = .true.`
turns on (and off) the nonhydrostatic model.

Two test cases `ocean/nonhydro/solitary_wave` and `ocean/nonhydro/stratified_seiche` are already present in Compass to test this nonhydrostatic model.

### CODE REVIEW

**Comment by jonbob** [comment]
@scalandr - the first test I tried to run failed to build and complained about this omp pragma in mpas_ocn_vmix.F:
````
      !$omp parallel
      !$omp do schedule(runtime) private(viscAv, N, A, B, C, velTemp, k)
````
I took B out because there is no variable with that name. After that, the test built, ran, and was BFB with current master. However, that omp pragma will need some work because I don't believe it's capturing everything that needs to be private

**Comment by scalandr** [comment]
Hi @jonbob, I would change the line this way
`!$omp do schedule(runtime) private(N, Nsurf, C, bTemp, rTemp, k, thickAv, viscAv, A, m, velTemp)`
Do you want me to make the change in the code and push it, or do you prefer to try it out first?

**Comment by jonbob** [comment]
@scalandr -- that change looks right to me. Please push it to your branch and I'll retest

**Comment by jonbob** [comment]
OK, with the new fix it passed PET_Ln9_PS.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-mach-pet, which is a test that changes thread counts

**Comment by rljacob** [comment]
status:  getting some cmake changes for PETSC.

**Comment by jonbob** [comment]
Passes a PET.ne11_oQU240.WCYCL1850NS.chicoma-cpu_gnu test with nonhydro on, using the following user_nl_mpaso:
````
 config_enable_nonhydrostatic_mode = .true.
 config_nonhydrostatic_solve_surface_boundary_condition = 'pressureTopGradientBottom'
 config_nonhydrostatic_remove_rhs_mean = .true.
 config_nonhydrostatic_preconditioner = 'bjacobi'
 config_nonhydrostatic_solver_type = 'cg'
 config_petsc_rtol = 1.0e-10
 config_petsc_atol = 1.0E-10
 config_petsc_maxit = 10000
 config_dt = '02:00:00'
 config_btr_dt = '0000_00:01:00'
 config_use_vertMom_del2 = .true.
 config_vertMom_del2 = 100
````

**Comment by rljacob** [comment]
notes:  need a PETSc build on anvil and chrysalis.

**Comment by rljacob** [comment]
notes:  found someone to build PETSc on anvil and chrysalis.

**Comment by rljacob** [comment]
update:  Jon built PETSc on anvil for testing.  May make a standalone capability.

**Comment by rljacob** [comment]
update:  not being deterministic.  Waiting for Luke to have time.

**Comment by rljacob** [comment]
update:  tough finding effort to work on.

**Pull request closed without merging**
