### PR TITLE
update mpas-source: Simplify computing landIcePressure and vertical grid in ocean init mode

### PR DESCRIPTION
**Pull request by mark-petersen**
see MPAS-Dev/MPAS-Model#812

This does not alter code used in E3SM simulations, only for creating initial conditions in MPAS-Ocean stand-alone. Note `mode_init` directory is no longer compiled by E3SM.

[BFB]

### CODE REVIEW

**Comment by xylar** [comment]
A further note to say that 2 source files (`src/core_ocean/Registry.xml` and `src/core_ocean/shared/mpas_ocn_diagnostics_variables.F`) outside of `mode_init` are also modified, but these changes only affect variables that are (or were once) used in init mode:
* `modifySSHMask` --> `modifyLandIcePressureMask`
* `scratchZMid` deleted
* `scratchMaxLevelCell` deleted

**Comment by mark-petersen** [comment]
Passes 
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
```
@jonbob this is ready to go.

**Review by jonbob — APPROVED** [review]
From a visual inspection, none of these changes should impact E3SM.

**Comment by xylar** [comment]
Thank you very much @mark-petersen and @jonbob!

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
passed sanity testing

**Comment by jonbob** [comment]
merged to master

**Comment by xylar** [comment]
@jonbob, thanks again!

**Comment by jonbob** [comment]
@xylar - you're most welcome. I'm glad we're getting caught up on PRs and the backlog is getting small

**Comment by xylar** [comment]
I agree!  Recent discussions have really enlightened me on the process and its bottlenecks.  They are rather different than I had thought, and I'm excited for a new, more streamlined process in the future where the work can hopefully be distributed more fairly among us.  In the meantime, I really appreciate you and @mark-petersen working so hard to make the best of a pretty clunky workflow.

**Pull request merged**
