### PR TITLE
save e3sm.log and cpl.log files in performance archive

### LINKED ISSUE #2369: Not saving component log files in logs subdirectory eliminates them from perf. archive
The decision not to copy the component and e3sm log files back to $CASE/log has the side effect of also preventing the CPL and E3SM log files from being saved in the performance archive. These logs files containt important performance monitoring data.

Code that no longer works as expected is in provenance.py:

    globs_to_copy.append("logs/e3sm.log.{}.gz".format(lid))
    globs_to_copy.append("logs/cpl.log.{}.gz".format(lid))

(lines 345-346).

### PR DESCRIPTION
**Pull request by worleyph**
The recent change in CIME not to copy the component and e3sm
log files back to $CASE/log had the side effect of also
preventing the cpl and e3sm log files from being saved
in the performance archive. This modification corrects this,
copying the log files instead from the run directory.

[BFB]

Fixes #2369

### CODE REVIEW

**Comment by worleyph** [comment]
Tested on Cori-KNL. @jgfouca , there are two different "styles" used in the glob_to_copy.append commands, one using {} and format(), and the other using %s. I retained the syle used in the original lines referencing e3sm.log and cpl.log . Hope that this was the correct choice. Please correct if not.

**Comment by jgfouca** [comment]
Addressing your other question: "{}".format is python2 and 3 compatible, so that's the one we should be using.

**Comment by worleyph** [comment]
@jgfouca , is a clean-up planned, because {} and format are not used everywhere yet?

**Comment by jgfouca** [comment]
@worleyph , I know Erich Foster ran a conversion script to try to catch them all. I think he caught the vast majority but his script may have missed a couple files including this one. I will clean it up when I get a chance.

**Comment by worleyph** [comment]
There are also other pre-existing uses of '/' in provenance.py . FYI. 

I'm testing your suggestions now. I will commit once I have verified that they work.

**Comment by worleyph** [comment]
@jgfouca , please look again. I used the code that you provided verbatim, and it worked on Cori-KNL.

**Comment by jgfouca** [comment]
@worleyph , looks good. My only concern now is that there may be something wrong with your testing. The previous version of this PR should not have worked.

**Comment by worleyph** [comment]
Why? The test was to check whether the e3sm.log and cpl.log files were copied to the performance archive directory. I looked at the files - they were there and looked fine.

**Comment by worleyph** [comment]
@jgfouca , how was the previous version broken? I assumed that your suggestion was just a stylistic / best practices change over what I used?

**Comment by jgfouca** [comment]
Because, without the ternary operation in the loop, the glob for the logs would have been:

$rundir/$caseroot/$log   , can't imagine that glob would have worked.

**Comment by worleyph** [comment]
I can't even parse this statement - ternary operation in the loop? If the addition of the line 

   glob_to_copy = ...

was necessary, it should have been necessary even with the original, unmodified, code? In any case, this worked before, and it works now. If you have another test that you would like to see, please ask. Note that there are lines like ...

         globs_to_copy.append("/home/%s/%s*OU" % (getpass.getuser(), job_id))

and

         globs_to_copy.append("logs/run_environment.txt.{}".format(lid))

still in this routine. If the first commit shoudl have failed, how should it have failed?

**Comment by jgfouca** [comment]
@worleyph , the original implementation assumed that all the files to be copied lived under the caseroot directory. I think the "/home/.." glob was probably also broken.

Note this line in the previous implementation:

```
for item in glob.glob(os.path.join(caseroot, glob_to_copy)):
```

This forces "$caseroot/" to be prepended to all the globs and will not work if glob_to_copy is an absolute path.

**Comment by jgfouca** [comment]
@worleyph , I apologize, os.path.join does not behave like I thought:

```
>>> cr = '/the/caseroot'
>>> the_glob = '/home/jgfouca/foo'
>>> os.path.join(cr, the_glob)
'/home/jgfouca/foo'
```

I assumed it would produce: "/the/caseroot/home/jgfouca/foo"

So we don't need the ternary at all.

**Comment by worleyph** [comment]
@jgfouca , should I delete that line then and retest?

**Comment by jgfouca** [comment]
@worleyph , yep delete the line. You don't need to retest since the code is functionally the same as your original code.

**Comment by worleyph** [comment]
@jgfouca , you are clearly not paranoid enough to be an integrator. I'll let it pass this time ... and will retest. This should run quickly. If it fails I'll make sure to notify you. Please go ahead and approve the review (if you now to approve) and then add it to your list of PRs to integrate (hopefully soon - if not, please send me a note). thanks.

**Comment by worleyph** [comment]
Test passed on Cori-KNL (F case, 48 processes, 1 node).

**Comment by jgfouca** [comment]
@worleyph , OK. Merged. Thanks for doing this and apologies again for the confusion. After all these years I just now learned that os.path.join, one of the most commonly used functions in python, is smart enough to handle absolute paths.

**Comment by worleyph** [comment]
@jgfouca, thank you.

**Pull request merged**
