### PR TITLE
Update global attributes for EAM, ELM and MOSART

### PR DESCRIPTION
**Pull request by rljacob**
Update and standardize the global attributes in netcdf history files for EAM, ELM
and MOSART.

Add contact email and institution.  Make sure hostname, username, git_version are definied. Add
history for EAM.  Replace "CLM", "CAM", and "RTM" in output.

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
Global attributes now contain blocks as shown below.   case, username, hostname and git_version info is collected from the CIME casedir info (communicated to the models via the cpl7 infobuffer). For reference ,I ran cases called Fcaseout  and Icaseout on compy where I'm jaco316 using commits from this branch.

EAM:
```
		:title = "EAM History file information" ;
		:source = "E3SM Atmosphere Model" ;
		:case = "Fcaseout" ;
		:username = "jaco316" ;
		:hostname = "compy" ;
		:git_version = "ec88d46" ;
		:Conventions = "CF-1.0" ;
		:institution = "E3SM-Project" ;
		:institution_id = "E3SM-Project" ;
		:contact = "E3SM-DATA-SUPPORT@LISTSERV.LLNL.GOV" ;
```
ELM:
```
		:title = "ELM History file information" ;
		:source = "E3SM Land Model" ;
		:case = "Icaseout" ;
		:username = "jaco316" ;
		:hostname = "compy" ;
		:git_version = "de55f05" ;
		:history = "created on 09/30/20 21:37:55" ;
		:institution = "E3SM-Project" ;
		:institution_id = "E3SM-Project" ;
		:contact = "E3SM-DATA-SUPPORT@LISTSERV.LLNL.GOV" ;
		:Conventions = "CF-1.0" ;
```
MOSART
```
		:title = "MOSART History file information" ;
		:comment = "NOTE: None of the variables are weighted by land fraction!" ;
		:source = "MOSART in E3SM" ;
		:case = "Icaseout" ;
		:username = "jaco316" ;
		:hostname = "compy" ;
		:git_version = "de55f05" ;
		:history = "created on 09/30/20 21:37:55" ;
		:institution = "E3SM-Project" ;
		:institution_id = "E3SM-Project" ;
		:contact = "E3SM-DATA-SUPPORT@LISTSERV.LLNL.GOV" ;
		:Conventions = "CF-1.0" ;
```

**Review by bishtgautam — APPROVED** [review]

**Comment by bishtgautam** [comment]
May consider changing `E3SM-DATA-SUPPORT@LISTSERV.LLNL.GOV` to lowercase.

**Comment by golaz** [comment]
@rljacob : you should merge this for v2 when it's ready.

**Comment by chengzhuzhang** [comment]
Maybe remove institution_id = "E3SM-Project",  and keep only: institution = "E3SM-Project"?

**Comment by rljacob** [comment]
Renata said we need both for compatibility with CMIP5.  "CMIP6 needs ‘institution_id’, CMIP5 'institution’ "

**Comment by chengzhuzhang** [comment]
For CMIP publication, we have metadata files to add CMIP required information to cmorized files. Just thought we may not need both in every history files.

**Comment by rljacob** [comment]
Ok I'll remove "institution" since that's the older style.

**Review by hydrotian — APPROVED** [review]

**Review by wlin7 — APPROVED** [review]

**Pull request merged**
