### PR TITLE
Fix EAM Chem PP built with IBM compiler

### PR DESCRIPTION
**Pull request by amametjanov**
Also, do not copy `campp` preprocessor exe to `components/eam/chem_proc`.

Fixes E3SM-Project/E3SM#4499

[BFB]

### CODE REVIEW

**Comment by amametjanov** [comment]
It appears that current xlf version `xl/16.1.1-10` on Summit and Ascent has an internal `STRLEN` function, which gets invoked instead of chempp's `STRLEN` [function](https://github.com/E3SM-Project/E3SM/blob/master/components/eam/chem_proc/src/cam_chempp/mozpp.subs.f#L659). This leads to a seg-fault (at `-O0` too) during case setup:
```
Program terminated with signal 11, Segmentation fault.
#0  0x0000200000d2b5e4 in __memcpy_power7 () from /lib64/libc.so.6
#1  0x00002000001708c4 in ?? () from /sw/ascent/xl/16.1.1-10/lib/libxlf90_r.so.1
#2  0x00002000001a2d94 in ?? () from /sw/ascent/xl/16.1.1-10/lib/libxlf90_r.so.1
#3  0x00002000001a6614 in xl__sigdump () from /sw/ascent/xl/16.1.1-10/lib/libxlf90_r.so.1
#4  0x0000200000196f68 in __xl_handle_segv () from /sw/ascent/xl/16.1.1-10/lib/libxlf90_r.so.1
#5  <signal handler called>
#6  0x0000200000966a50 in ?? () from /sw/ascent/xl/16.1.1-10/lib/libxlf90_r.so.1
#7  0x0000200000370750 in _xliltrm () from /sw/ascent/xl/16.1.1-10/lib/libxlf90_r.so.1
#8  0x000000001003f4e8 in strlen (
    string='\000' <repeats 24 times>, 'A', '\000' <repeats 23 times>, '\260\375W(', '\000' <repeats 20 times>, '\320pa(', '\000' <repeats 12 times>, '!G\000\000\000\000\000\000\300\342k(\000\000\000\000h~*(\000\000\000\000\000\224Z(\000\000\000\000`\224Z(\000\000\000\000\300\224Z(\000\000\000\000 \225Z(\000\000\000\000\200\225Z(\000\000\000\000\340\225Z(\000\000\000\000@\226Z(\000\000\000\000\240\226Z(\000\000\000\000\000\227Z(\000\000\000\000`\227Z(\000\000\000\000\300\227Z(\000\000\000\000'...)
    at /autofs/nccsopen-svm1_home/azamat/repos/E3SM-ascent/components/eam/chem_proc/src/cam_chempp/mozpp.subs.f:673
#9  0x0000200000851998 in _xlf_strlen () from /sw/ascent/xl/16.1.1-10/lib/libxlf90_r.so.1
#10 0x0000200000948050 in getarg_ () from /sw/ascent/xl/16.1.1-10/lib/libxlf90_r.so.1
#11 0x000020000094819c in getarg () from /sw/ascent/xl/16.1.1-10/lib/libxlf90_r.so.1
#12 0x000000001010b338 in mozart_pp ()
    at /autofs/nccsopen-svm1_home/azamat/repos/E3SM-ascent/components/eam/chem_proc/src/cam_chempp/mozpp.main.f:190
```
OS-default GNU (`/usr/bin/gfortran`) in the default `PATH` has no bld or run issues on either of IBM machines.

**Comment by rljacob** [comment]
@singhbalwinder and @wlin7 please review.

**Comment by singhbalwinder** [comment]
@amametjanov : Does Fortran has an intrinsic `strlen` function? I thought only c/c++ has this function. If xlf indeed has strlen intrinsic, an invasive way to fix this issue would be to change `STRLEN` function in chempp codes with some other name (e.g. `STRLEN_PP`), this will avoid the use of STRLEN intrinsic.

Technically, it doesn't matter if chempp is compiled and run by some other compiler (e.g. `gfortran` in this case) than the rest of the code as it generates only F90 files as its output. In the past, I have seen running into problems when the Makefile logic would choose pgi compiler but the environment setup by the model is of Intel. If it is guaranteed that  `gfortran` will always be available on machines with xlf compiler, it is okay to remove `xlf` form the list. If this assumption is not guaranteed, we may run into problems.

**Comment by philipwjones** [comment]
@singhbalwinder LEN_TRIM is the Fortran equivalent

**Comment by singhbalwinder** [comment]
Thanks @philipwjones ! That is good to know. I think replacing STRLEN with LEN_TRIM  would be more portable (and efficient). That way, we won't need to remove xlf from the list of compilers.

**Comment by amametjanov** [comment]
Okay, done: replaced STRLEN with LEN_TRIM.
A run with these changes on Summit is at https://my.cdash.org/viewTest.php?buildid=2138081 .

**Comment by singhbalwinder** [comment]
Thanks @amametjanov ! Is chempp compiled with xlf or gfortran in the above mentioned test?

**Comment by amametjanov** [comment]
It was compiled with xlf95:
```
$ grep "mozpp.main.f" Buildconf/eamconf/chem_proc/MAKE.out 
xlf95 -g -c -qarch=auto -qnosave -qfree=f90 -qmoddir=/gpfs/alpine/cli115/proj-shared/azamat/e3sm_scratch/SMS_Ln1.ne4_oQU240.F2010.summit_ibm.eam-chem_pp.20220307_211631_bzg7lc/Buildconf/eamconf/chem_proc/obj -I /gpfs/alpine/cli115/proj-shared/azamat/e3sm_scratch/SMS_Ln1.ne4_oQU240.F2010.summit_ibm.eam-chem_pp.20220307_211631_bzg7lc/Buildconf/eamconf/chem_proc/obj -qstrict -O3 -o /gpfs/alpine/cli115/proj-shared/azamat/e3sm_scratch/SMS_Ln1.ne4_oQU240.F2010.summit_ibm.eam-chem_pp.20220307_211631_bzg7lc/Buildconf/eamconf/chem_proc/obj/mozpp.main.o /autofs/nccs-svm1_home1/azamat/repos/E3SM/components/eam/chem_proc/src/cam_chempp/mozpp.main.f
1501-510  Compilation successful for file mozpp.main.f.
```

**Comment by singhbalwinder** [comment]
This looks good to me but I would also like @wlin7 and @tangq to take a look at these changes.

We are also removing the code to copy campp exe to the source code in the PR. I think that would mean that the exe would be compiled every time we invoke the preprocessor. Is that right, @amametjanov?

**Comment by tangq** [comment]
@singhbalwinder , I recall that you helped us implement a routine test for the chemistry pre-processor. Is it `SMS_Ln1.ne4_ne4.FC5AV1C-L.*.eam-chem_pp`? I vaguely remember the test will try to build campp and see if it's successful. Is that right? If so, passing the eam-chem_pp test means that campp exe is built successfully, but it doesn't guarantee the fortran code files generated by campp exe stay the same.

Do you think we need to check if the fortran code files (should be located at $casedir/Buildconf/eamconf/) created by campp with and without this PR gives the same chemistry solvers?

**Comment by amametjanov** [comment]
> We are also removing the code to copy campp exe to the source code in the PR. I think that would mean that the exe would be compiled every time we invoke the preprocessor.

Yes, a new `campp` exe will be built for every new case. On machines with multiple compilers like Summit, having `campp` built with xlf can cause issues for cases created with gfortran (and vice versa), if `campp` is copied into E3SM source/repo: e.g. [these comments in the initial issue](https://github.com/E3SM-Project/E3SM/issues/4499#issuecomment-909478779). In my runs, it didn't take long to build `campp`: on the order of a couple of minutes at most during `case.setup`.

Doing just a basic diff between cases built with ibm and gnu compilers shows this (ignoring other obvious path and build output diffs):
```
[azamat@login3.summit SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp.20220307_mybranch]$ diff Buildconf/eamconf/chem_proc/ ../SMS_Ln1.ne4_oQU240.F2010.summit_ibm.eam-chem_pp.20220307_211631_bzg7lc/Buildconf/eamconf/chem_proc/
diff Buildconf/eamconf/chem_proc/MAKE.out ../SMS_Ln1.ne4_oQU240.F2010.summit_ibm.eam-chem_pp.20220307_211631_bzg7lc/Buildconf/eamconf/chem_proc/MAKE.out
1,85c1,178
< gfortran -g -c -ffree-form -J /gpfs/alpine/cli115/proj-shared/azamat/e3sm_scratch/SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp.20220307_mybranch/Buildconf/eamconf/chem_proc/obj -o /gpfs/alpine/cli115/proj-shared/azamat/e3sm_scratch/SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp.20220307_mybranch/Buildconf/eamconf/chem_proc/obj/mozpp.mods.o /autofs/nccs-svm1_home1/azamat/repos/E3SM/components/eam/chem_proc/src/cam_chempp/mozpp.mods.f
---
> xlf95 -g -c -qarch=auto -qnosave -qfree=f90 -qmoddir=/gpfs/alpine/cli115/proj-shared/azamat/e3sm_scratch/SMS_Ln1.ne4_oQU240.F2010.summit_ibm.eam-chem_pp.20220307_211631_bzg7lc/Buildconf/eamconf/chem_proc/obj -I /gpfs/alpine/cli115/proj-shared/azamat/e3sm_scratch/SMS_Ln1.ne4_oQU240.F2010.summit_ibm.eam-chem_pp.20220307_211631_bzg7lc/Buildconf/eamconf/chem_proc/obj -qstrict -O3 -o /gpfs/alpine/cli115/proj-shared/azamat/e3sm_scratch/SMS_Ln1.ne4_oQU240.F2010.summit_ibm.eam-chem_pp.20220307_211631_bzg7lc/Buildconf/eamconf/chem_proc/obj/mozpp.mods.o /autofs/nccs-svm1_home1/azamat/repos/E3SM/components/eam/chem_proc/src/cam_chempp/mozpp.mods.f
...
diff Buildconf/eamconf/chem_proc/chem_mech.dat ../SMS_Ln1.ne4_oQU240.F2010.summit_ibm.eam-chem_pp.20220307_211631_bzg7lc/Buildconf/eamconf/chem_proc/chem_mech.dat
10c10
<    47.998199999999997        34.013599999999997        98.078400000000002        64.064800000000005        62.132400000000004        12.010999999999999        115.10734000000002        12.010999999999999        12.010999999999999        12.010999999999999        135.06403900000001        58.442468000000005        250092.67200000002        1.0074000000000001        115.10734000000002        12.010999999999999        58.442468000000005        250092.67200000002        1.0074000000000001        135.06403900000001        58.442468000000005        115.10734000000002        12.010999999999999        12.010999999999999        12.010999999999999        250092.67200000002        1.0074000000000001        12.010999999999999        12.010999999999999        250092.67200000002        1.0074000000000001     
---
>  47.9981999999999971 34.0135999999999967 98.0784000000000020 64.0648000000000053 62.1324000000000041 12.0109999999999992 115.107340000000022 12.0109999999999992 12.0109999999999992 12.0109999999999992 135.064039000000008 58.4424680000000052 250092.672000000020 1.00740000000000007 115.107340000000022 12.0109999999999992 58.4424680000000052 250092.672000000020 1.00740000000000007 135.064039000000008 58.4424680000000052 115.107340000000022 12.0109999999999992 12.0109999999999992 12.0109999999999992 250092.672000000020 1.00740000000000007 12.0109999999999992 12.0109999999999992 250092.672000000020 1.00740000000000007
...
diff Buildconf/eamconf/chem_proc/chem_mech.inp ../SMS_Ln1.ne4_oQU240.F2010.summit_ibm.eam-chem_pp.20220307_211631_bzg7lc/Buildconf/eamconf/chem_proc/chem_mech.inp
5,7c5,7
< temp_path          = /gpfs/alpine/cli115/proj-shared/azamat/e3sm_scratch/SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp.20220307_mybranch/Buildconf/eamconf/chem_proc/tmp/
< procout_path       = /gpfs/alpine/cli115/proj-shared/azamat/e3sm_scratch/SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp.20220307_mybranch/Buildconf/eamconf/chem_proc/
< output_path        = /gpfs/alpine/cli115/proj-shared/azamat/e3sm_scratch/SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp.20220307_mybranch/Buildconf/eamconf/chem_proc/
---
> temp_path          = /gpfs/alpine/cli115/proj-shared/azamat/e3sm_scratch/SMS_Ln1.ne4_oQU240.F2010.summit_ibm.eam-chem_pp.20220307_211631_bzg7lc/Buildconf/eamconf/chem_proc/tmp/
...
```

**Comment by singhbalwinder** [comment]
Thanks @amametjanov for the diffs. We are mainly concerned about diffs in the F90 files which are generated by the preprocessor. I don't see any diffs in the F90 files from your diffs above. If that is correct, I think it should be good to go.

The test @tangq mentioned would be an extra layer of protection. That test forces the model to run this preprocessor. If we do not see any baseline diffs for that test, that would mean these changes are producing the same F90 files as before.

**Comment by singhbalwinder** [comment]
@tangq : You are right, the diffs we are seeing in these numbers are due to the use of different compilers. I just checked and found out that the trailing significant digits (where we see the diffs) are not being used in the F90 files. For example, if chem_mech.dat file has a number `47.998199999999997 `, in F90 file, `47.998199_r8` is being used. Therefore, the F90 files are exactly the same.

When we compare with the baselines, we do that for the same compiler. In that case, the results should be BFB. `xlf` compiler on this machine may need new baselines (if we are comparing with baselines on this machine) as the code was not even working with the xlf compiler before.

**Comment by tangq** [comment]
@singhbalwinder , thanks for the clarifications. It seems to me that this PR is ready to be merged. Thank you for working on this, @amametjanov, @singhbalwinder .

**Comment by amametjanov** [comment]
> We are mainly concerned about diffs in the F90 files which are generated by the preprocessor. I don't see any diffs in the F90 files from your diffs above. If that is correct, I think it should be good to go.

Yes, that's correct. Recursive diff doesn't show any other notable diff than before (just more pathname diffs). Spot-checked a couple of .F90 files manually -- nothing.

For baseline comparisons, as mentioned, we probably don't want to compare (1) gnu-built `campp` + gnu-built `e3sm.exe` to (2) ibm-built `campp` + gnu-built `e3sm.exe` or any other compiler mix: i.e. we should compare both exe's built with the same compiler.

If so, master+ibm can't be compared with this branch, because master was broken. Baseline comparison with gnu shows BFB: https://my.cdash.org/viewTest.php?buildid=2138425
```
[azamat@login2.summit e3sm_scratch]$ ./cs.status.20220308_mybranch 
20220308_mybranch: 1 test
  SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp (Overall: PASS) details:
    PASS SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp CREATE_NEWCASE
    PASS SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp XML
    PASS SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp SETUP
    PASS SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp SHAREDLIB_BUILD time=160
    PASS SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp NLCOMP
    PASS SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp MODEL_BUILD time=279
    PASS SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp SUBMIT
    PASS SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp RUN time=34
    PASS SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp BASELINE master:
    PASS SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp TPUTCOMP
    PASS SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp MEMLEAK insuffiencient data for memleak test
    PASS SMS_Ln1.ne4_oQU240.F2010.summit_gnu.eam-chem_pp SHORT_TERM_ARCHIVER
```

There is no baseline comparison testing with ibm compiler. Testing with this branch merged to `next` should show if there are any DIFFs for intel or pgi compilers.

**Review by singhbalwinder — APPROVED** [review]

**Review by wlin7 — APPROVED** [review]
Sorry, did I hold up the merge of this PR? The conversations and the changes in the files are all good.

**Pull request merged**
