### PR TITLE
Three small BFB fixes.

### LINKED ISSUE #3587: Homme: Boundary exchange copy threading
I noticed that in bndry_exchangeV_core singlethread_copy was initialized to .false. at declaration, but that means once it's set to .true., it retains that value at next subroutine call via an implicit save attribute. This was preventing the threaded copying from running. The fix is simply to initialize it in the executable part of the subroutine.

However, performance profiling on cori-knl with an F case, ne30pg2, 43 nodes (-pecount S), 32x4 proc x threads per node, shows that the fix actually slows down the boundary exchange. I speculate it's because the memory is not resident in HBM.

I'm working on a v2-performance PR for physgrid and SL transport. I was going to include the fix in it, but it's the one part of the PR that is not leading to clear speedup (again, in fact slowdown). So I'm dropping the commit and just reporting the issue here.

### PR DESCRIPTION
**Pull request by ambrad**
This PR fixes three innocuous bugs, in three separate commits:

1. SL transport was exchanging one more level than necessary in its trajectory calculation. The data were ignored, so fixing this reduces comm by a little but does not change the answer.
1. The dynamics-physics remap module can do a total-area calculation on each grid independent of phys_grid.F90, but previously this was possible only in unit testing and not full simulations. Fix this. 
1. Threading was not working properly from a performance perspective in HOMME's boundary exchange. But it was still giving the correct answer.

Fixes #3587.

[BFB]

### CODE REVIEW

**Comment by ambrad** [comment]
e3sm_atm_integration and e3sm_developer tests all pass on sandiatoss3. HOMME standalone testing is in progress.

**Comment by ambrad** [comment]
Homme standalone passes.

**Comment by ambrad** [comment]
@AaronDonahue pinging you in case you didn't notice this PR.

**Comment by AaronDonahue** [comment]
@ambrad , thanks for pinging me.  I'll begin the merge today.

**Comment by ambrad** [comment]
From a performance study @ndkeen is running:
```
>>> ./ne256pg2tri.F00DY1.s25-sep15.n0128t08xX111X1.nr.24s.nc00c.f2.N144.cin.revap/run/timing.34412563.200915-211124.tar.gz <------ threading bug, 8 ranks/node
"CPL:RUN_LOOP"               1024     1024 2.457600e+04   4.401905e+05   430.677   427.805 
"a:CAM_run1"                 1024     1024 2.560000e+04   8.870457e+04    91.524    83.192 
"a:CAM_run2"                 1024     1024 2.560000e+04   1.989663e+04    20.230    18.822 
"a:CAM_run3"                 1024     1024 2.560000e+04   2.961379e+05   289.718   288.194 
"a:CAM_run4"                 1024     1024 2.560000e+04   3.526180e+03     4.335     3.278 
>>> ./ne256pg2tri.F00DY1.s25-sep15.n0128t08xX111X1.nr.24s.nc00c.f2.N144.cin.3bfb.revap/run/timing.34411465.200915-201143.tar.gz <- fixed, 8 ranks/node
"CPL:RUN_LOOP"               1024     1024 2.457600e+04   3.320718e+05   324.899   322.774 
"a:CAM_run1"                 1024     1024 2.560000e+04   8.846556e+04    91.047    82.765 
"a:CAM_run2"                 1024     1024 2.560000e+04   1.969598e+04    19.889    18.822 
"a:CAM_run3"                 1024     1024 2.560000e+04   1.886514e+05   184.532   183.487 
"a:CAM_run4"                 1024     1024 2.560000e+04   3.956255e+03     4.937     3.686 
>>> ./ne256pg2tri.F00DY1.s25-sep15.n0128t64x211121.nr.24s.nc00c.N144.cin/run/timing.34403832.200915-142217.tar.gz <--------------- bug, 64 ranks/node
"CPL:RUN_LOOP"               8192     8192 1.966080e+05   2.552994e+06   314.193   308.473 
"a:CAM_run1"                 8192     8192 2.048000e+05   6.670615e+05    87.251    76.940 
"a:CAM_run2"                 8192     8192 2.048000e+05   7.909773e+04    10.198     9.156 
"a:CAM_run3"                 8192     8192 2.048000e+05   1.513870e+06   185.162   184.337 
"a:CAM_run4"                 8192     8192 2.048000e+05   3.315646e+04     5.217     3.991 
>>> ./ne256pg2tri.F00DY1.s25-sep15.n0128t64x211121.nr.24s.nc00c.f2.N144.cin.3bfb.revap/run/timing.34411466.200915-201742.tar.gz <- fixed, 64 ranks/node
"CPL:RUN_LOOP"               8192     8192 1.966080e+05   2.516855e+06   309.364   304.648 
"a:CAM_run1"                 8192     8192 2.048000e+05   6.664066e+05    86.911    76.880 
"a:CAM_run2"                 8192     8192 2.048000e+05   8.011820e+04    10.322     9.338 
"a:CAM_run3"                 8192     8192 2.048000e+05   1.475308e+06   180.535   179.588 
"a:CAM_run4"                 8192     8192 2.048000e+05   3.256721e+04     4.950     3.931 
```
So the 64x2 case is roughly the same or slightly better, and the 8x16 case is much better.

**Comment by AaronDonahue** [comment]
@ambrad , This has been merged to master now.  Since the branch is on your fork I'll let you take care of deleting it if you want.

**Pull request merged**
