### PR TITLE
Add RRTMGP regression test

### PR DESCRIPTION
**Pull request by brhillman**
Add an RRTMGP test to the `e3sm_developer` test suite. This is just a short 5-day ERS test at ne4 resolution to test basic functionality of the RRTMGP configuration and BFB reproducibility. Note that this PR is BFB, but the new tests will fail baseline compare since baselines do not exist for RRTMGP yet.

### CODE REVIEW

**Comment by brhillman** [comment]
@singhbalwinder okay I'll modify this and push a commit today. Thanks.

**Comment by brhillman** [comment]
@singhbalwinder I'm having a hard time figuring out how the user mods functionality works. I see the cam-cosplite argument for that test you reference, but where is it pulling in configuration for this? What do I need to add to being to do something like `"ERS.ne4_ne4.FC5AV1C-L", "rad-rrtmgp"`? All that needs to happen is `-rad rrtmgp` needs to be appended to `CAM_CONFIG_OPTS` in `env_build.xml`.

**Comment by singhbalwinder** [comment]
I can't find the confluence page with instruction on how to do it. Here is how we add a "user mods" to a test:
1. create a directory at components/cam/cime_config/testdefs/testmods_dirs/cam/
`cd components/cam/cime_config/testdefs/testmods_dirs/cam/`
`mkdir rrtmgp`
`cd rrtmgp`
2. Create a file in `rrtmgp` folder you just created with name  `shell_commands` and contents:
`./xmlchange --append CAM_CONFIG_OPTS='-rad rrtmgp'`

Now if you create a test `"ERS_Ld5.ne4_ne4.FC5AV1C-L", "cam-rrtmgp"` , it should execute the command(s) in the `shell_commands` file you created above.

Hope this helps. Please let me know if you have any questions.

**Comment by brhillman** [comment]
Great, thanks @singhbalwinder I think I got it. What's the best way of removing my changes to add the RRTMGP compset then? I assume the motivation is to keep the compset list a little cleaner...should I just checkout the files I changed from master and issue a commit to the branch to restore the previous version?

**Comment by brhillman** [comment]
Alright thanks @singhbalwinder I just pushed some commits. Does this look right to you?

**Comment by singhbalwinder** [comment]
Thanks @brhillman . Yes, it looks great!

**Comment by brhillman** [comment]
Awesome thanks @singhbalwinder, let me run a test and make sure it's doing what I think it should and then I will pass it off for integration.

**Comment by brhillman** [comment]
@singhbalwinder it looks like it's good to go. Thanks again for the help!

**Comment by singhbalwinder** [comment]
Pushed to next.

**Comment by brhillman** [comment]
@amametjanov I think this is a problem with the netCDF file type, and I think has to do with PIO. I have a branch where I've updated the input files and I think saved them as the correct type. I haven't submitted the PR for the branch because I needed to verify that it fixed this same issue on Titan (this was not an issue on Cori or Edison, by the way). I will check that out and make sure that is up to date, and then get a PR submitted. In the meantime, you could grab that branch (https://github.com/E3SM-Project/E3SM/tree/brhillman/atm/update-rrtmgp-inputdata) and see if it passes your test on Anvil (I do not have access to Anvil to test this).

**Comment by amametjanov** [comment]
A different error further in the run: on Theta, atm.log had
```
 RRTMGP radiation scheme parameters:
  LW coefficents file: /projects/ccsm/acme/inputdata/atm/cam/rad/rrtmgp_coefficients_lw_c181004.nc
  SW coefficents file: /projects/ccsm/acme/inputdata/atm/cam/rad/rrtmgp_coefficients_sw_c181004.nc
```
and e3sm.log
```
 read_char_vec: can't read variable gas_names
[NID 03834] 2018-11-12 22:01:39 Apid 8289383: initiated application termination
```
and the file is in classic mode
```
> ncdump -k /projects/ccsm/acme/inputdata/atm/cam/rad/rrtmgp_coefficients_sw_c181004.nc
classic
```
Further discussion is at E3SM-Project#2565

**Pull request merged**
