### PR TITLE
Add the SSP85 future compsets for CBGC experiment

### PR DESCRIPTION
**Pull request by acme-y9s**
Add Future compasets for CBGC experiment

### CODE REVIEW

**Comment by rljacob** [comment]
Please fix the title for this PR.

**Comment by rljacob** [comment]
After fixing a typo, yes.  Thanks.

**Comment by jonbob** [comment]
Changed default PIO_TYPENAME to netcdf, tested on anvil with SMS.ne30_oEC.BGCEXP_BCRC_CNPRDCTC_SSP585_CMIP6.anvil_intel. The pio setting was picked up just fine but the run failed with missing CAM files and issues with the machine setup. If anvil is a target platform, we should fix this

**Comment by jonbob** [comment]
merged to maint-1.1

**Pull request merged**
