### PR TITLE
Add necessary diagnostic output variables for CBGC experiment

### PR DESCRIPTION
**Pull request by qzhu-lbl**
Adds the ability to output following land BGC fluxes:
 - total litter flux due to gap mortality
 - total litter flux due to fire mortality
 - total litter flux due to harvest mortality
 - total litter flux due to senescence

[BFB]

### CODE REVIEW

**Comment by qzhu-lbl** [comment]
@susburrows @xyk-ornl  could you please review this PR? Does it look good to you?

**Comment by susburrows** [comment]
Thanks for putting this together Qing! Could you please add a little more summary information to the PR description, explaining the reason for the changes (to improve alignment with the C4MIP variable requests), and that it makes existing (internal) variables accessible as history variables.

**Comment by susburrows** [comment]
Also for the record, the review of the C4MIP land variable requests was documented here: https://acme-climate.atlassian.net/wiki/spaces/SIM/pages/634520057/CBGC+Required+output+variables+-+Land 
Is there any other documentation information that you and @xyk-ornl have already put together (any updates to the table?)

**Comment by xyk-ornl** [comment]
looks good to me. Thanks

**Comment by susburrows** [comment]
The changes look good to me; I will approve them.  @xyk-ornl , perhaps you could cross-check the specific variables that are being lumped together, just so that a second person has reviewed them to reduce the risk of errors ? I didn't check all of them in detail.

**Pull request merged**
