### PR TITLE
Adding ADIOS install paths for Crusher

### PR DESCRIPTION
**Pull request by dqwu**
Adding ADIOS install paths and library dependencies for Crusher
with different compilers.

[BFB]

### CODE REVIEW

**Comment by dqwu** [comment]
@jayeshkrishna 
ADIOS support for "--machine=crusher-scream-cpu --compiler=gnu" and "--machine=crusher-scream-cpu --compiler=amdclang" is not available in this PR so far, see issue #5546.

**Review by jayeshkrishna — APPROVED** [review]

**Comment by grnydawn** [comment]
@dqwu , @jayeshkrishna Can you provide me with some test cases that I can run on Crusher to verify that the functions of ADIOS work properly?

**Comment by dqwu** [comment]
@grnydawn 
See steps below to test a simple ne4 F case with ADIOS type on Crusher. You can test other E3SM cases with ADIOS type similarly.
```
git clone https://github.com/E3SM-Project/E3SM.git
cd E3SM

git merge --no-edit origin/dqwu/test_pio2_07
git merge --no-edit origin/dqwu/machinefiles/crusher/add_adios_install_path
git merge --no-edit origin/jayeshkrishna/cime_config/add_adios_conv_job

git submodule update --init

cd cime
git merge --no-edit origin/jayeshkrishna/adios2_support

cd scripts
./create_newcase --case F2010_ne4_oQU240 --compset F2010 --res ne4_oQU240 --walltime 00:05:00
cd F2010_ne4_oQU240

cat <<EOF >> user_nl_eam
mfilt = 1
nhtfrq = -120
EOF

./xmlchange STOP_N=1
./xmlchange REST_OPTION="none"
./xmlchange PIO_STRIDE=4
./xmlchange PIO_TYPENAME=adios

./case.setup

./case.build

./case.submit
```

**Comment by dqwu** [comment]
@grnydawn 
Please use latest E3SM master branch (with jayeshkrishna/cime_config/add_adios_conv_job branch merged) for testing.

CaseStatus also includes the status of "ADIOS to NetCDF conversion":
```
...
2023-03-24 13:35:28: case.run starting 288818
 ---------------------------------------------------
2023-03-24 13:35:48: model execution starting 288818
 ---------------------------------------------------
2023-03-24 13:36:18: model execution success 288818
 ---------------------------------------------------
2023-03-24 13:36:18: case.run success 288818
 ---------------------------------------------------
2023-03-24 13:36:38: ADIOS to NetCDF conversion starting 
 ---------------------------------------------------
2023-03-24 13:36:43: ADIOS to NetCDF conversion success 
---------------------------------------------------
```

**Comment by grnydawn** [comment]
@dqwu 

> @grnydawn See steps below to test a simple ne4 F case with ADIOS type on Crusher. You can test other E3SM cases with ADIOS type similarly.
> 
> ```
> git clone https://github.com/E3SM-Project/E3SM.git
> cd E3SM
> 
> git merge --no-edit origin/dqwu/machinefiles/crusher/add_adios_install_path
> 
> git submodule update --init
> 
> cd cime
> git merge --no-edit origin/jayeshkrishna/adios2_support
> 
> cd scripts
> ./create_newcase --case F2010_ne4_oQU240 --compset F2010 --res ne4_oQU240 --walltime 00:05:00
> cd F2010_ne4_oQU240
> 
> cat <<EOF >> user_nl_eam
> mfilt = 1
> nhtfrq = -120
> EOF
> 
> ./xmlchange STOP_N=1
> ./xmlchange REST_OPTION="none"
> ./xmlchange PIO_STRIDE=4
> ./xmlchange PIO_TYPENAME=adios
> 
> ./case.setup
> 
> ./case.build
> 
> ./case.submit
> ```
> 
> You can check the output ADIOS BP files in the run directory after the case completes.

@dqwu I tried to run this script but failed with following error:
...
Compset longname is 1850_DATM%GSWP3v1_ELM%CNPRDCTCBC_SICE_SOCN_MOSART_SGLC_SWAV
Compset specification file is /gpfs/alpine/cli133/scratch/grnydawn/e3sm_tests/PRtest/E3SM/components/elm/cime_config/config_compsets.xml
ERROR: Makes no sense to have empty read-only file: /gpfs/alpine/cli133/scratch/grnydawn/e3sm_tests/PRtest/E3SM/driver-nuopc/cime_config/config_component.xml
./runtest.sh: line 7: cd: I1850GSWCNPRDCTCBC_hcru_hcru: No such file or directory
...

Do you have any suggestion for me to look at?

**Comment by jayeshkrishna** [comment]
@grnydawn Maybe check your CIME_MODEL settings (CIME_MODEL="e3sm")?

**Comment by grnydawn** [comment]
> CIME_MODEL

@jayeshkrishna , CIME branch merge seems fine. is it correct way to set CIME_MODEL like "export CIME_MODEL="e3sm""?

In the mean time, I found my error shows that it tries to find "config_component.xml" file under "driver-nuopc/cime_config" directory, but "driver-nuopc" folder does not exist. So far, I have not seen the "driver-nuopc" directory created during my testing. Usually, I have driver-mct or driver-moab. Can you check if it is expected to use driver-nuopc, not driver-mct?

**Comment by jayeshkrishna** [comment]
Do you get the error after setting CIME_MODEL to e3sm (export CIME_MODEL="e3sm")? The builds should be using driver-mct.

**Comment by grnydawn** [comment]
@jayeshkrishna , it seems that there were multiple issues on my testing.

1. The "driver-nuopc" issue is fixed. I installed E3SM on the scratch file system and failed. After installing E3SM on non-scratch file system, the issue is fixed.
2. Still, I have an issue with merging "jayeshkrishna/adios2_support" branch of CIME. It looks that there is not such branch in CIME github. Can you check if the branch exists in CIME github repo?

I was able to build/run the latest E3SM but there is no log related to ADIOS in CaseStatus.

**Comment by dqwu** [comment]
> @jayeshkrishna , it seems that there were multiple issues on my testing.
> 
>     1. The "driver-nuopc" issue is fixed. I installed E3SM on the scratch file system and failed. After installing E3SM on non-scratch file system, the issue is fixed.
> 
>     2. Still, I have an issue with merging "jayeshkrishna/adios2_support" branch of CIME. It looks that there is not such branch in CIME github. Can you check if the branch exists in CIME github repo?
> 
> 
> I was able to build/run the latest E3SM but there is no log related to ADIOS in CaseStatus.

For merging cime, did you try my commands listed above?
```
cd cime
git merge --no-edit origin/jayeshkrishna/adios2_support
```

**Comment by dqwu** [comment]
@grnydawn I think you can first try my commands above to test a simple ne4 F case manually on a Crusher login node, without using a script.

**Comment by grnydawn** [comment]
> git merge --no-edit origin/jayeshkrishna/adios2_support

@dqwu , I think I did. I ran your commands on terminal manually. Following is the output from the merge git command:

~/repos/github/E3SM_ADIOS$ cd cime
~/repos/github/E3SM_ADIOS/cime$ git merge --no-edit origin/jayeshkrishna/adios2_support
merge: origin/jayeshkrishna/adios2_support - not something we can merge

**Comment by dqwu** [comment]
@grnydawn That branch has already been merged to CIME master branch and it was also deleted by the integrator.
Then you just need to use latest CIME master:
```
cd cime
git checkout master
```

**Comment by dqwu** [comment]
> I think you need to do "git fetch origin" after "cd cime".

It seems to be optional with the default cime submodule, but we can always add "git fetch origin" as you suggested.

**Comment by grnydawn** [comment]
@dqwu , my test finished, but CaseStatus does not have any log message related to Adios. How do I check if Adios is actually tested and passed?

 ---------------------------------------------------
2023-03-28 16:02:21: case.build success
 ---------------------------------------------------
2023-03-28 17:02:28: case.run starting 291760
 ---------------------------------------------------
2023-03-28 17:02:44: model execution starting 291760
 ---------------------------------------------------
2023-03-28 17:03:12: model execution success 291760
 ---------------------------------------------------
2023-03-28 17:03:12: case.run success 291760
 ---------------------------------------------------
2023-03-28 17:03:13: case.submit starting
 ---------------------------------------------------
2023-03-28 17:03:13: case.submit success
 ---------------------------------------------------

**Comment by jayeshkrishna** [comment]
Check if you have a dependent job in queue, once the job is completed you should have another log file with output from the conversion job

**Comment by rljacob** [comment]
That conversion job should output something to CaseStatus though.

**Comment by grnydawn** [comment]
@jayeshkrishna , I still can not see any log file that contains Adios-related message. CaseStatus does not have any Adios stuff and I do not see any Adios-related log files in run directory. What is the filename and where I can find it? FYI, I used following script to run my test:

```bash
git clone https://github.com/E3SM-Project/E3SM.git
cd E3SM

#git merge --no-edit origin/dqwu/machinefiles/crusher/add_adios_install_path
git checkout master

git submodule update --init

cd cime
git merge --no-edit origin/jayeshkrishna/adios2_support

cd scripts
./create_newcase --case F2010_ne4_oQU240 --compset F2010 --res ne4_oQU240 --walltime 00:05:00
cd F2010_ne4_oQU240

cat <<EOF >> user_nl_eam
mfilt = 1
nhtfrq = -120
EOF

./xmlchange STOP_N=1
./xmlchange REST_OPTION="none"
./xmlchange PIO_STRIDE=4
./xmlchange PIO_TYPENAME=adios

./case.setup

./case.build

./case.submit
```

**Comment by dqwu** [comment]
> ```shell
> git merge --no-edit origin/dqwu/machinefiles/crusher/add_adios_install_path
> ```

@grnydawn Did you comment out "git merge --no-edit origin/dqwu/machinefiles/crusher/add_adios_install_path" in your script? You need merge this branch test test ADIOS type on Crusher.

**Comment by grnydawn** [comment]
> > ```shell
> > git merge --no-edit origin/dqwu/machinefiles/crusher/add_adios_install_path
> > ```
> 
> @grnydawn Did you comment out "git merge --no-edit origin/dqwu/machinefiles/crusher/add_adios_install_path" in your script? You need merge this branch in order to test ADIOS type on Crusher.

@dqwu , that is right. I mistakenly commented the E3SM branch instead of adios2 CIME branch. I will re-run the test now...

**Comment by dqwu** [comment]
> > > ```shell
> > > git merge --no-edit origin/dqwu/machinefiles/crusher/add_adios_install_path
> > > ```
> > 
> > 
> > @grnydawn Did you comment out "git merge --no-edit origin/dqwu/machinefiles/crusher/add_adios_install_path" in your script? You need merge this branch in order to test ADIOS type on Crusher.
> 
> @dqwu , that is right. I mistakenly commented the E3SM branch instead of adios2 CIME branch. I will re-run the test now...

OK, then your script should use commands below:
```
...

cd E3SM

git merge --no-edit origin/dqwu/machinefiles/crusher/add_adios_install_path

git submodule update --init

cd cime
git checkout master

...
```

**Comment by grnydawn** [comment]
@dqwu , @jayeshkrishna . I verified that the latest test did generate *.bp file in run directory and CaseStatus contains log messages related to Adios to Netcdf conversion. Thanks for your helps.

I think I am going to merge this PR to master because this PR only affects to I/O.

**Review by grnydawn — APPROVED** [review]
This PR is tested on Crusher with a F case that generates expected results.

**Comment by dqwu** [comment]
@grnydawn Could you please merge this feature branch (I have restored it) to next as well? Usually we want to keep next in sync with master.

**Comment by rljacob** [comment]
Yes PR's must always be merged to next AND master.

**Comment by grnydawn** [comment]
> Yes PR's must always be merged to next AND master.

@dqwu , @rljacob I see. I will merge it to next branch, and make sure that it goes through next to master branch from next time.

**Pull request merged**
