### PR TITLE
After switching to hyper-threading on chrysalis, adjust srun flags

### PR DESCRIPTION
**Pull request by ndkeen**
Adjust flags for srun and update MAX_TASKS_PER_NODE.

Fixes E3SM-Project/E3SM#4221

[BFB]

### CODE REVIEW

**Comment by amametjanov** [comment]
Can you also delete these lines here?
```
    <environment_variables MAX_MPITASKS_PER_NODE="!128">
      <env name="SLURM_CPU_BIND">cores</env>
    </environment_variables>
    <environment_variables MAX_MPITASKS_PER_NODE="128">
      <env name="SLURM_CPU_BIND">threads</env>
    </environment_variables>
```

**Review by amametjanov — APPROVED** [review]

**Comment by oksanaguba** [comment]
Not sure this is the best place to post these homme runs. I tried to turn on HT for standalone homme and it did not work till the problem was reduced. Here are runs showing that the gain from 2 HT for 64 ranks is ~7% for smaller problems, and is negative for larger problems.
```
[ac.onguba@chr-0245 run4]$ export SLURM_CPU_BIND=cores
[ac.onguba@chr-0245 run4]$ export OMP_STACKSIZE=128M
[ac.onguba@chr-0245 run4]$ export KMP_AFFINITY=granularity=core,scatter
[ac.onguba@chr-0245 run4]$ export KMP_HOT_TEAMS_MODE=1
[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=1
[ac.onguba@chr-0245 run4]$ 
[ac.onguba@chr-0245 run4]$ 
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 64 -N 1 -K   --cpu_bind=cores  -c 2 -m plane=64 ../bldff/src/preqx/preqx < xxinput-ne10-nmax2000-q1.nl > temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         64       64 4.268800e+04   1.237011e+03    19.329 (    23      0)    19.328 (    48      0)
[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=2
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 64 -N 1 -K   --cpu_bind=cores  -c 2 -m plane=64 ../bldff/src/preqx/preqx < xxinput-ne10-nmax2000-q1.nl > temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         64      128 8.537600e+04   2.310521e+03    18.051 (     5      0)    18.050 (     0      1)

7%



[ac.onguba@chr-0245 run4]$ 
[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=1
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 64 -N 1 -K   --cpu_bind=cores  -c 2 -m plane=64 ../bldff/src/preqx/preqx < xxinput-ne6-nmax2000-q1.nl > temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         64       64 4.268800e+04   5.067095e+02     7.918 (    11      0)     7.917 (    62      0)
[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=2
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 64 -N 1 -K   --cpu_bind=cores  -c 2 -m plane=64 ../bldff/src/preqx/preqx < xxinput-ne6-nmax2000-q1.nl > temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         64      128 8.537600e+04   9.554090e+02     7.464 (    25      1)     7.464 (     0      0)

7%


[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=1
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 64 -N 1 -K   --cpu_bind=cores  -c 2 -m plane=64 ../bldff/src/preqx/preqx < xxinput-ne6-nmax2000-q40.nl >temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         64       64 4.268800e+04   2.889882e+03    45.157 (    14      0)    45.151 (    38      0)
[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=2
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 64 -N 1 -K   --cpu_bind=cores  -c 2 -m plane=64 ../bldff/src/preqx/preqx < xxinput-ne6-nmax2000-q40.nl >temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         64      128 8.537600e+04   5.563917e+03    43.470 (     9      1)    43.465 (    63      0)

4%


[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=1
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 64 -N 1 -K   --cpu_bind=cores  -c 2 -m plane=64 ../bldff/src/preqx/preqx < xxinput-ne10-nmax2000-q40.nl >temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         64       64 4.268800e+04   9.529424e+03   148.904 (    22      0)   148.887 (    40      0)
[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=2
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 64 -N 1 -K   --cpu_bind=cores  -c 2 -m plane=64 ../bldff/src/preqx/preqx < xxinput-ne10-nmax2000-q40.nl >temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         64      128 8.537600e+04   1.865750e+04   145.772 (    32      1)   145.756 (    50      0)

2%



[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=1
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 64 -N 1 -K   --cpu_bind=cores  -c 2 -m plane=64 ../bldff/src/preqx/preqx < xxinput-ne20-nmax100.nl >temp
[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=2
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         64       64 2.176000e+03   1.978949e+03    30.929 (    31      0)    30.908 (    33      0)
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 64 -N 1 -K   --cpu_bind=cores  -c 2 -m plane=64 ../bldff/src/preqx/preqx < xxinput-ne20-nmax100.nl >temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         64      128 4.352000e+03   4.016081e+03    31.385 (    31      0)    31.359 (    33      1)

negative gain

```

**Comment by oksanaguba** [comment]
Here is a run for a different affinity option (which changed nothing):

```
[ac.onguba@chr-0245 run4]$ KMP_AFFINITY=granularity=thread,balanced
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 64 -N 1 -K   --cpu_bind=cores  -c 2 -m plane=64 ../bldff/src/preqx/preqx < xxinput-ne10-nmax2000-q1.nl > temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         64       64 4.268800e+04   1.228344e+03    19.193 (    14      0)    19.193 (    48      0)
[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=2
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 64 -N 1 -K   --cpu_bind=cores  -c 2 -m plane=64 ../bldff/src/preqx/preqx < xxinput-ne10-nmax2000-q1.nl > temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         64      128 8.537600e+04   2.289646e+03    17.888 (    24      1)    17.887 (     0      0)

same 7%

```

**Comment by oksanaguba** [comment]
Here is run 32x2 (no HT) vs 32x4 (2 HT), 7% in the dycore if the problem is smaller:
```
[ac.onguba@chr-0245 run4]$ export KMP_AFFINITY=granularity=core,scatter
[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=2
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 32 -N 1 -K --cpu_bind=cores  -c 4 -m plane=32 ../bldff/src/preqx/preqx < xxinput-ne10-nmax2000-q1.nl > temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         32       64 4.268800e+04   1.231680e+03    19.245 (    10      1)    19.245 (    30      0)
[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=4
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 32 -N 1 -K --cpu_bind=cores  -c 4 -m plane=32 ../bldff/src/preqx/preqx < xxinput-ne10-nmax2000-q1.nl > temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         32      128 8.537600e+04   2.292657e+03    17.912 (    10      3)    17.911 (     0      2)


7%
```

**Comment by oksanaguba** [comment]
The last one, trying 16x4 and 8x8 and comparing to 32x2 and 64x1. No HT in any. The fastest is 32x2.
```
[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=2
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 32 -N 1 -K --cpu_bind=cores  -c 4 -m plane=32 ../bldff/src/preqx/preqx < xxinput-ne20-nmax100.nl >temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         32       64 2.176000e+03   1.921401e+03    30.026 (    10      1)    30.017 (    21      1)
[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=4
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 16 -N 1 -K --cpu_bind=cores  -c 8 -m plane=16 ../bldff/src/preqx/preqx < xxinput-ne20-nmax100.nl >temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         16       64 2.176000e+03   1.951373e+03    30.492 (     6      1)    30.486 (     4      3)
[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=8
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 8 -N 1 -K --cpu_bind=cores  -c 16 -m plane=8 ../bldff/src/preqx/preqx < xxinput-ne20-nmax100.nl >temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -          8       64 2.176000e+03   2.040838e+03    31.892 (     2      0)    31.884 (     4      7)
[ac.onguba@chr-0245 run4]$ export OMP_NUM_THREADS=1
[ac.onguba@chr-0245 run4]$ srun --mpi=pmi2 -l -n 64 -N 1 -K --cpu_bind=cores  -c 2 -m plane=64 ../bldff/src/preqx/preqx < xxinput-ne20-nmax100.nl >temp
[ac.onguba@chr-0245 run4]$ grep prim_run HommeTime_stats 
"prim_run"                      -         64       64 2.176000e+03   1.979783e+03    30.942 (    21      0)    30.917 (    39      0)
```

**Pull request merged**
