### PR TITLE
Move MPAS standalone make from mpas-framework to mpas-CORE directories

### PR DESCRIPTION
**Pull request by mark-petersen**
Change make process for stand-alone MPAS components from:
```
cd components/mpas-framework
make clean CORE=ocean 
make gfortran CORE=ocean
````
to (for the ocean core)
```
cd components/mpas-ocean
make clean 
make gfortran 
```
where other cores are similar.

This does not touch any E3SM cmake files.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
Compiles all three cores successfully, without `CORE=ocean` etc. Ran ocean nightly test suite with head of `compass/master`

**Review by xylar — APPROVED** [review]
These changes look great to me.  I find it very convenient not to need to set the `CORE` environment or make variable.

I tested both the `nightly` and `sia_integration` test suites from `compass/master` with `E3SM/master` as a baseline.  The only test that didn't pass were the ocean RK4 restart test and the land-ice Enthalpy Benchmark A, both of which are known issues unrelated to this PR.

**Comment by akturner** [comment]
I like these changes. It would be helpful though if the testing_and_setup/seaice directory could be moved to mpas-seaice/testing_and_setup/seaice from mpas-framework/testing_and_setup/seaice.

**Review by akturner — CHANGES_REQUESTED** [review]
Move mpas-framework/testing_and_setup/seaice to mpas-seaice/testing_and_setup/seaice

**Comment by mark-petersen** [comment]
@akturner that is a good point. I moved testing_and_setup/seaice from mpas-framework to mpas-seaice.

@matthewhoffman what do you want to do with `components/mpas-framework/testing_and_setup/compass/landice/`? @xylar did we mean to remove `components/mpas-framework/testing_and_setup/compass` altogether? I think so.

**Comment by xylar** [comment]
>  @xylar did we mean to remove components/mpas-framework/testing_and_setup/compass altogether? I think so.

@mark-petersen, that's up to @matthewhoffman.  My impression is that `landice` hasn't moved their workflow to `compass/legacy` yet.  I intentionally only removed the `ocean` directory.  But I do think it's pretty confusing to keep this in E3SM and now is hopefully the time for `landice` to consider the move to the `compass` repo.

**Comment by matthewhoffman** [comment]
Yes, our plan is to transition to the new version of COMPASS at the same time as the repository transition.  A complicating factor is that we have not ported over the higher order test cases yet, so the new COMPASS does not give us complete test coverage.  That said, if there is a desire to eliminate the old COMPASS files now in this PR, we could use the COMPASS setup in the old MPAS-Dev/MPAS-Model repo (but with an exe from the new E3SM repo) in the interim while we finish the transition (which is what we were planning to do anyway - I hadn't realized that anything from testing_and_setup made the transition to the new repo).

**Comment by xylar** [comment]
@matthewhoffman, why not use `compass/legacy` for that purpose instead of `MPAS-Dev/MPAS-Model`?  The purpose of `compass/legacy` in my view is as the "right" place for our old COMPASS test cases to live until they are ported to `compass/master`.

**Comment by matthewhoffman** [comment]
@xylar , you are right about that - the only reason is the automated testing that Mike Kelleher at ORNL set up is currently using the old COMPASS in MPAS-Dev/MPAS-Model.  I was hoping to limit the number of temporary steps for him to retrofit it for before we are fully operational with the new COMPASS and new MPAS.

**Comment by xylar** [comment]
Okay, in that case I would indeed keep using MPAS-Dev/MPAS-Model because moving E3SM doesn't seem any easier than moving to `compass/legacy`.

**Review by matthewhoffman — APPROVED** [review]
Thanks @mark-petersen for working out the kinks in these changes.  I tested with and without Albany and with and without DEBUG mode and everything works as expected.  I also confirmed `make clean` is functional and `make -j 4`.  I didn't test every possible combination, but no issues came up.

**Comment by mark-petersen** [comment]
Rather than overload this PR, I created a new PR with the move and delete of the testing directories, https://github.com/E3SM-Project/E3SM/pull/4310

**Comment by xylar** [comment]
I thinks that's wise.

**Review by akturner — APPROVED** [review]

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
