### PR TITLE
Fixes the ELM's SPBC compset

### PR DESCRIPTION
**Pull request by bishtgautam**
Removes turning on of the subgrid solar topographic radiation scheme.

[BFB]

### CODE REVIEW

**Review by daleihao — COMMENTED** [review]
Should we add SPBCTOP as below
<value compset="_EAM%CMIP6_ELM%[^_]*SPBCTOP" >-bgc sp -solar_rad_scheme top</value>

**Comment by rljacob** [comment]
@daleihao please review

**Review by daleihao — APPROVED** [review]

**Review by rljacob — APPROVED** [review]

**Comment by rljacob** [comment]
@peterdschwartz you can start merging this.

**Comment by rljacob** [comment]
@bishtgautam did you see @daleihao 's question above?

**Comment by bishtgautam** [comment]
I missed @daleihao's comment earlier.

Let's not add the `_EAM%CMIP6_ELM%[^_]*SPBCTOP` because it would be an active EAM that we aren't currently using in the v3 WC campaign.

**Comment by peterdschwartz** [comment]
merged to next

**Pull request merged**
