### PR TITLE
Fix bug in create_chunks

### LINKED ISSUE #2735: innocuous but confusing logic error in create_chunks
In the routine create_chunks in the file

     components/cam/src/physics/cam/phys_grd.F90

is logic to determine the number of columns assigned to each virtual
SMP during the dynamics. As part of this a mapping from each column to
the owner SMP is computed using the physics (lon-lat) ordering of the
columns. To count the number of columns per SMP, this mapping array is
then accessed as if the entries had been assigned using the native
dynamics ordering of the columns. This error however does not prevent
the correct calculation of the number of columns per SMP, and the
column-to-SMP mapping array is then deleted, so the inconsistency is
not repeated and does not introduce an error.

This apparent error in the logic is confusing to the reader (and to the 
author, for that matter) and should be modified to eliminate future 
misunderstandings.

### PR DESCRIPTION
**Pull request by worleyph**
In the routine create_chunks in the file
components/cam/src/physics/cam/phys_grd.F90
is logic to determine the number of columns assigned to each virtual
SMP during the dynamics. As part of this a mapping from each column to
the owner SMP is computed using the physics (lon-lat) ordering of the
columns. To count the number of columns per SMP, this mapping array is
then accessed as if the entries had been assigned using the native
dynamics ordering of the columns. This error however does not prevent
the correct calculation of the number of columns per SMP, and the
column-to-SMP mapping array is then deleted, so the inconsistency is
not repeated and does not introduce an error.

However, when enhancing the load balancing logic to
use data on the computational cost of columns, this
column-to-smp mapping is needed. To introduce clarity in the
current logic and in support of this future enhancement,
the ordering used is changed to that of the natural dynamics
ordering of the columns (not necessarily lon-lat), and used
consistently throughout create_chunks.

Fixes #2735 

[BFB]

### CODE REVIEW

**Comment by worleyph** [comment]
Tested on Titan using 

      --res ne4_ne4 --compset FC5AV1C-L

with a 64x1 stacked PE layout. added diagnostic output and also just compared atm.log for phys_loadbalance=0, 1, 2, and 3 with runs using unmodified code.

**Comment by rljacob** [comment]
@AaronDonahue do you want to review this?  I think you've looked at these routines so assigned a review to you.

**Comment by AaronDonahue** [comment]
@rljacob , Yes, sorry.  I was at AMWG last week so I didn't see the review request.  I'll review it now.

**Comment by worleyph** [comment]
@wlin7, could this be merged soon? I have a subsequent PR to submit that touches the same code, and would prefer not to have to deal with a conflict. Thanks.

**Comment by wlin7** [comment]
Thanks for the reminder @worleyph. Merged to next.

**Comment by wlin7** [comment]
Merged to master.

**Comment by worleyph** [comment]
Thanks!

**Pull request merged**
