### PR TITLE
Switch atmospheric forcing variables to topounit subgrid level

### LINKED ISSUE #2547: Harmless bug in CanopyFluxesMod.F90
@thorntonpe reported that the `c` index within the loop is not updated in In [CanopyFluxesMod.F90#L1085](https://github.com/E3SM-Project/E3SM/blob/master/components/clm/src/biogeophys/CanopyFluxesMod.F90#L1085).  This is a harmless bug because the incorrect 
values in `lbl_rsc_h2o` are presently not being in ELM. @thorntonpe has already fixed this bug
in his branch, which will be merged to master in the future.

### PR DESCRIPTION
**Pull request by thorntonpe**
Moves atmospheric forcing variables from the gridcell level down to the topographic unit sub-grid level. Replaces the atm2lnd data structure with state and flux variables defined at the topographic unit. Includes all the fundamental state and flux variables, as well as the variables derived directly from them, and the accumulated variables based on them. Includes a bug fix for harmless bug.

All tests expected to pass BFB except tests that use a non-null land finidat file. Because dimensionality of accumulated variables has changed, these tests using specified finidat files will fail.

[non-BFB]

Fixes #2547

### CODE REVIEW

**Comment by bishtgautam** [comment]
@thorntonpe, I understand that the grid-level atmospheric states/fluxes now need to be changed to topo-level states/fluxes (i.e. `atm2lnd_vars%forc_rh_grc` --> `top_as%rhbot`). But, why swap column-level variables with topo-level (i.e. `atm2lnd_vars%forc_t_downscaled_col` --> `top_as%tbot`)? Even though, all columns within a given topo-unit might have the same value, wouldn't it be better to keep column-level variables to support a future column-level subdownscaling?

**Comment by bishtgautam** [comment]
@thorntonpe, I can't think of any column-level subdownscaling scenario. Thanks for clarifing why column-level states/fluxes are being swapped with topo level state/fluxes. In that case, how about deleting the column-level states/fluxes variables from atm2lndType.F90 that are not used anymore?

**Comment by thorntonpe** [comment]
@bishtgautam - Yes, the plan is to completely eliminate the atm2lnd data type. There are still a few loose ends to clean up before that can be done, such as deciding what to do with the river-to-land exchange variables. Those got tucked into atm2lnd, I guess because it provided easy access to the coupler interface. This is one place where I can see potential for a column-level forcing (currently gridcell-level). I need to discuss with @lrleung to see what makes the most sense for future plans on river-land coupling. For now I've just left the atm2lnd data structure intact, but have disconnected most of its variables from the science code. Once the loose ends are resolved I thought this could be rolled into a future clean-up PR for v2 architecture work.

**Comment by bishtgautam** [comment]
While the atm2lnd data type is eliminated in the future, how about deleting the following variables in this PR  because they are now not used anywhere else in the code?
```
 forc_q_downscaled_col
 forc_pbot_downscaled_col
 forc_rho_downscaled_col
 forc_rain_downscaled_col
 forc_lwrad_downscaled_col
```

**Comment by thorntonpe** [comment]
Will do.

**Comment by bishtgautam** [comment]
One more question. Does the non-BFB nature of this PR imply existing finidat files will no longer be compatible once this PR is merged to master?

**Comment by thorntonpe** [comment]
That's correct.

**Comment by thorntonpe** [comment]
@bishtgautam , looking back over the usage of *_downscaled_col variables, it is going to be complicated to get rid of those before we re-implement the downscaling algorithms at the topounit level. At the moment, the glacier MEC code still uses those column-level variables, and variables derived from them. The staging of development is like this: I have put in place all of the topounit-level variables, and replaced the use of other forcing variables wherever downscaling is not relevant (outside of the MEC code). Next, @mabrunke will implement the downscaling algorithms at the topounit level. At that point, the glacier MEC code can be switched to the topounit variables. In the meantime, removing the downscaled_col variables will break the glacier MEC code, and the glacier MEC development team wanted to ensure that it stays working through the v2 architecture development. 
For now, I would prefer to put the decomission of atm2lnd type in with a PR after Michael's downscaling work is complete.

**Comment by bishtgautam** [comment]
1. Ok on addressing the refactor of atm2lnd type in a future PR.
2. Breaking compatability of initial conditions might be an issue with the atm team that are using existing land initial conditions. @singhbalwinder, @cameronsmith1, Would breaking the compatibility of existing land initial conditions on master be an issue?

**Comment by singhbalwinder** [comment]
I have a clarification question: Does "breaking compatibility" mean we no longer be able to use existing land initial condition files and new "compatible" files will needs to be generated? I would also like to add @golaz into this discussion so that he is aware of this change.

**Comment by bishtgautam** [comment]
> Does "breaking compatibility" mean we no longer be able to use existing land initial condition files and new "compatible" files will needs to be generated?

Yes.

**Comment by cameronsmith1** [comment]
Hi Gautam,    Will the new land ic files be bfb?   A significantly different climate state?

**Comment by bishtgautam** [comment]
Hi @cameronsmith1, I believe the new files should be BFB. But, your question raises another question regarding generation of new land IC files.

@thorntonpe, Does the interpinic tool need to be updated to handle old IC files? Or, could you make this PR be BFB w.r.t. to older format IC/restart file by querying dimensions in the netcdf file to determine if it is in the new or old format?

**Comment by cameronsmith1** [comment]
Thanks, Gautam.   To expand on my view, I think there are two separate issues:
1) Being able to repeat the CMIP6 watercycle simulations,
2) Being able to do new runs that can be compared scientifically to the CMIP6 simulations.

For #1, that code is on a branch, so as long as the land ic files used in the simulations is archived, then no change to master can destroy this.

For #2, as long as the new ic files only produce round-off type errors, I don't see a problem (especially since the code on master means the simulations won't be exactly comparable anyway).

**Comment by thorntonpe** [comment]
@bishtgautam, I have looked briefly at the interpinic tool, and it does look like it would need to be updated to handle the topounits dimension. I have not used that tool or ever modified that code, so I'm not positive how much work it is to update. I think that a new PR to update this tool is the way to go. Adding conditional code in ELM to check for and use older initial condition files contributes to code clutter, and I think should be avoided. 
Given the input from @cameronsmith1 , I suggest we move ahead with this PR as-is, and start a new branch to update interpinic. 
In terms of the test suite, at one point we discussed removing or modifying all tests that used explicit initial files, going instead with cold-start conditions and restart tests. That prevents test failures when initial file formats change, while still testing the creation and reading of initial/restart conditions. Do we want to update the test suite to follow that, or are there good reasons to keep explicit initial files as part of the tests?

**Comment by bishtgautam** [comment]
> Adding conditional code in ELM to check for and use older initial condition files contributes to code clutter, and I think should be avoided

I agree if-else creates clutter, but the downside of not updating interpinic tool AND not adding if-else statement in this PR is:
- no existing initial condition file can be used by the land model, and
- no existing initial condition file can remapped to the new format.

> In terms of the test suite, at one point we discussed removing or modifying all tests that used explicit initial files, going instead with cold-start conditions and restart tests

Using cold-start for 11-days or 5-days BGC tests might not catch BGC related bugs in new PRs. Thus, I would advocate for not getting rid of initial conditions from test suite in the long run.

>Given the input from @cameronsmith1 , I suggest we move ahead with this PR as-is, and start a new branch to update interpinic.

@cameronsmith1, Do you want the ability "to do new runs that can be compared scientifically to the CMIP6 simulations" be not broken in the master after this PR is merged? Or, are you Ok with the master not having the ability "to do new runs that can be compared scientifically to the CMIP6 simulations" till a new future PR that fixes the interpinic tool is merged in the master?

**Comment by singhbalwinder** [comment]
> In terms of the test suite, at one point we discussed removing or modifying all tests that used explicit initial files, going instead with cold-start conditions and restart tests.

Ideally tests should be run in the exact same configuration (including init files) as one would run the model for scientific explorations. If we run the tests one way and model is run in a different way by the scientists, tests may not be able to catch issues which scientist may discover.

**Comment by bishtgautam** [comment]
>Hi Gautam. Do I understand correctly that: (1) the new ic files will produce bfb results, but (2) are in a different format so won't be read by the new code, until (3) interpinic is updated to regrid the old ic files to the new format?

Yes, that is correct.

**Comment by thorntonpe** [comment]
@cameronsmith1 I like the idea of putting code in place with the current PR that warns the user about an incorrect format for the initial file. I don't have a definitive answer for how involved the update to interpinic would be, but at first glance it seems like a one-week sort of operation. My interest in moving quickly with the current PR is to allow others to move ahead with downscaling implementations in the main code while the initial file issue is addressed with updates to tools.

**Comment by cameronsmith1** [comment]
The risk is that the modifications to interpinic will get forgotten, but as long as that risk is managed (JIRA task?), then I like this plan.

**Comment by rljacob** [comment]
So what happens to the tests using init files once this PR is merged?  They all fail until interpinc is fixed and new files are put in place?

**Comment by rljacob** [comment]
Nevermind, I see that is answered in the description at the top.  How many tests is that?

**Comment by bishtgautam** [comment]
Out of the 56 e3sm_integration tests, 19 of them use a land initial condition file.

**Comment by rljacob** [comment]
I think that's too many to be in the fail state for an unknown amount of time.  This PR will have to wait until the interpinic changes are included, files remade and uploaded to to the server and the tests updated to use the new files.

**Comment by thorntonpe** [comment]
OK, I'll get to work on that.

**Comment by thorntonpe** [comment]
@rljacob, I have evaluated interpinic, and it looks like it works with the new finidat format without modification. I'm now using it to generate the required finidat files. When those are in place and the tests modified to use them, the tests with explicit finidat should pass all steps except the baseline comparison. These comparisons will fail because there are new variables with new dimensions being used in the new files. For tests that don't use an explicit finidat this PR is passing all tests, including baseline comparisons. Just wanted you to be aware of the baseline failures for this subset of tests.

**Comment by thorntonpe** [comment]
@jqyin , is this now ready to merge?

**Comment by jqyin** [comment]
@rljacob @bishtgautam  Can you approve this PR? The current status as described in the email thread: all tests that use a specified land finidat file have a newly generated finidat file that is confirmed to work except SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6, which is a restart other than a startup case.

**Comment by rljacob** [comment]
Does SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6 run at all? 

If there were any changes to interpinic, add them to this PR.

**Comment by thorntonpe** [comment]
SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6 fails in the run step. 
There are no changes to interpinic.

**Comment by rljacob** [comment]
To convert that CMIP6 case back to an initial run, edit cime/config/e3sm/allactive/config_compsets.xml and delete lines 306-337.  Recreate that case and it should run.  Add those changes to this PR.

**Comment by thorntonpe** [comment]
@rljacob, after testing that approach, we see that a new finidat file is pointed to for the initial run. We have two options. 
1) Revise the test definition so that it sues finidat = '' (no finidat file). That forces a land cold start for the initial run. Given the existence of other tests which check for non-coldstart conditions, I think a cold start for this test is fine, and it has the benefit of being able to maintain BFB behavior across mods like the ones I've introduced. This is my preference for how to proceed.
2) Replace the newly pointed finidat file with one that has been modified to include the new variables and dimensions. This is approach will not be BFB, and needs to be updated each time similar mods are made to the finidat file format. This is extra work now and in the future, and not necessary for the purpose of the test. 

Do you have a preference for which approach to use? If you don't, I'd like to go ahead with option 1).

**Comment by rljacob** [comment]
Yes option 1 sounds good.

**Comment by jqyin** [comment]
@rljacob fix commits for option 1 is on the PR now and the test SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.anvil_intel.allactive-v1cmip6 passed on anvil.

**Comment by jqyin** [comment]
Merged #2564

**Pull request merged**
