### PR TITLE
For reviewing the changes made for MPAS G-case benchmark tests

### PR DESCRIPTION
**Pull request by grnydawn**
This PR is not meant for actual merging.

### CODE REVIEW

**Comment by rljacob** [comment]
What needs to be reviewed here and are these changes being merged somewhere?

**Comment by sarats** [comment]
@rljacob We are using this draft PR to look at ongoing work for benchmarking ocean on Frontier and Perlmutter. So, a subsequent PR with most/subset of changes depending on results will be issued for integration into E3SM/master.

**Comment by rljacob** [comment]
Ok.  This kind of thing should be done on a fork.  The PRs here should be near-finished work ready for integration.

**Comment by xylar** [comment]
We have the https://github.com/E3SM-Ocean-Discussion/E3SM fork for exactly such purposes.

**Comment by rljacob** [comment]
You could do this on @grnydawn 's personal fork.

**Comment by sarats** [comment]
These are mostly machine config changes on the verge of completion. 

I don't understand the urgency with cleaning up draft PRs from core E3SM project developers. Anyway, we can close this for now as it doesn't matter that much.

**Pull request closed without merging**
