### PR TITLE
First steps towards pythonizing clm buildnml scripts

### PR DESCRIPTION
**Pull request by jgfouca**
Pythonize the top-level buildnml script.

[BFB]

### CODE REVIEW

**Comment by jgfouca** [comment]
This produces identical namelists to master for every e3sm_integration test.

**Comment by jgfouca** [comment]
We get another nice speedup here:

(on melvin)
BEFORE:
23.945s

AFTER:
1.624s

**Comment by rljacob** [comment]
That's really nuts that its that much faster.  So the xmlquery calls are what take all the time?   Would a bash script with the same xmlquery calls be that slow?

**Comment by jgfouca** [comment]
@rljacob , yes, the calls to xmlquery were the culprit and I'm refocusing my efforts to eliminate those. Any non-python approach to gathering case values would be just as slow.

**Comment by bishtgautam** [comment]
@jgfouca Will [CLMBuildNamelist.pm](https://github.com/E3SM-Project/E3SM/blob/master/components/clm/bld/CLMBuildNamelist.pm) be also converted to python in the future?

**Comment by jgfouca** [comment]
@bishtgautam , since we are losing all our performance in the buildnml scripts, and not the layer below, I'm in no longer in a hurry to convert the huge perl files like CLMBuildNamelist.pm.

**Comment by jgfouca** [comment]
Merged to next.

**Comment by bishtgautam** [comment]
@jgfouca, Thanks for the explanation.

**Pull request merged**
