### PR TITLE
Add pgrad_correction settings to caar_ut.

### PR DESCRIPTION
**Pull request by trey-ornl**
The `caar_ut` test was only using the value `pgrad_correction==0`, while current runs often use `pgrad_correction==1`. Modified the test to compare bit-for-bit answers for both settings. Diff appears to have trouble realizing that the changes to `caar_ut.cpp` are minor, ignoring indentation changes for the new loop level. `git diff -w` looks much cleaner.

Added `frontier-bfb.cmake`, to build `caar_ut` on Frontier.

Fixed `ExecSpaceDefs.hpp` for the newer version of Kokkos. Replaced a dependence on Kokkos implementation details, which no longer works as intended on Frontier, with standard C++ code.

### CODE REVIEW

**Comment by oksanaguba** [comment]
@trey-ornl thanks for making frontier-bfb file. i assume you ran this test and confirmed bfb-ness for caar_ut? i can run hommexx suite on frontier (more tests than just caar_ut) and i will run them on nvidia (only because of the minor change in execspacedef file).

**Comment by trey-ornl** [comment]
@oksanaguba, yes, I confirmed that `caar_ut` passed on Frontier using `frontier-bfb.cmake`.

**Comment by rljacob** [comment]
Does this change answers for regular EAM cases?

**Comment by trey-ornl** [comment]
> Does this change answers for regular EAM cases?

It should not affect EAM results at all. It adds testing to the CAAR unit test.

**Comment by rljacob** [comment]
@oksanaguba is this ready?

**Comment by oksanaguba** [comment]
no, i want to run tests, however redundant they are, will merge next week

**Comment by oksanaguba** [comment]
i merged this into a weaver branch (1 conflict) and most of theta-f* tests look good (did not wait for all theta-fhs*), but caar_ut freezes, so i need to debug.

**Comment by oksanaguba** [comment]
in next. weaver is ok, up to the issue with limiter barriers (has nothing to do with this PR), i will check frontier separately (Trey already did).

**Comment by oksanaguba** [comment]
only fail i saw was from pm-cpu_gnu because of disappeared baselines. ran manually next against today's master and  it passed.

**Review by oksanaguba — APPROVED** [review]

**Pull request merged**
