### PR TITLE
Upgrading PnetCDF lib on anvil

### LINKED ISSUE #3383: Ensure we have at least the min versions of I/O libraries required by Scorpio
Scorpio requires at least the following minimum versions of the I/O libraries,

* NetCDF C/Fortran : 4.3.3
* PnetCDF 1.8.1

This issue is to ensure that all E3SM machines have at least the above version of the libraries installed/available

In this issue we will be looking at the machines listed in the table below (01/13/2020, E3SM v1.1.0-beta-2931-g7622c75). Since different versions of an I/O library can be installed for the different supported compilers on a system, in the table below we include the lowest versions of an I/O library (NetCDF/PnetCDF) across all compilers supported on a given system,

|Machine Name|Current Version of NetCDF|Latest available version of NetCDF|Current Version of PnetCDF|Latest available version of PnetCDF|
|---|---|---|---|---|
|cori-haswell|4.6.1.3|4.6.3.2|1.8.1.4|1.11.1.1
|cori-knl|4.6.1.3|4.6.3.2|1.8.1.4|1.11.1.1
|melvin|4.4.1|_|Not installed|Not installed|
|anlworkstation|4.3.3|4.4.1|1.8.1|1.12.0
|sandiatoss3|4.4.1|_|Not installed|Not installed|
|***anvil***|4.4.1(C), 4.4.4(F)|_|***1.7.0***|1.11.0|
|theta|4.6.3.1|_|1.11.1.0|_|
|compy|4.6.3|_|1.9.0|_|
|summit|4.6.1|4.6.1|1.8.1|1.8.1

The complete list of machines in E3SM is included below,

|Machine Name|Current Version of NetCDF|Latest available version of NetCDF|Current Version of PnetCDF|Latest available version of PnetCDF|
|---|---|---|---|---|
|cori-haswell|
|cori-knl|
|stampede2|
|melvin|
|snl-white|
|snl-blake|
|anlworkstation|
|sandiatoss3|
|ghost|
|blues|
|anvil|
|***bebop***|4.4.1(C), 4.4.4(F)|_|***1.6.1***|1.6.1|
|cetus|
|syrah|
|quartz|
|mira|
|theta|
|jlse|
|sooty|
|cascade|
|constance|
|compy|
|oic5|
|cades|
|titan|
|eos|
|grizzly|
|badger|
|mesabi|
|itasca|
|lawrencium-lr2|
|lawrencium-lr3|
|lawrencium-lr6|
|eddi|
|summitdev|
|summit|

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Upgrading PnetCDF library for the default intel compiler from
1.7.0 to 1.11.0

[BFB]
Fixes #3383

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
Test results with the integration suite : https://my.cdash.org/buildSummary.php?buildid=1787064

There are no new test failures with pnetcdf 1.11.0. However I did notice some throughput and memory check failures. So ran the following test for 1 month and did not see any issues/failures.

https://my.cdash.org/buildSummary.php?buildid=1787066

**Comment by sarich** [comment]
@jayeshkrishna 
SMS_D_Ld1.ne30_r05_oECv3.A_WCYCL1850.anvil_intel is crashing on your branch, but is ok on master. Can you try it out?

**Comment by jayeshkrishna** [comment]
ok, I will try it out

**Comment by jayeshkrishna** [comment]
It looks like the cause of the failure is unrelated to the change in this branch. I was able to recreate the issue and after rebasing the branch with master the test passed on anvil with the Intel compiler.

I rebased the branch and force pushed it, please test it out and let me know if it works for you.

**Pull request merged**
