### PR TITLE
Add cosine bell advection test case

### PR DESCRIPTION
**Pull request by mark-petersen**
Adds initial condition for cosine bell test case, used for converge test of tracer advection. See https://github.com/MPAS-Dev/MPAS-Model/pull/583 and https://github.com/MPAS-Dev/compass/pull/8.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
This shows semi-implicit changes #3977. Will rebase after it is merged.

**Comment by mark-petersen** [comment]
Sanity tests, passes
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PEM_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-haswell_gnu
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
```
This is ready to merge.

**Review by jonbob — APPROVED** [review]
Approved from visual inspection and sanity testing

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
