### PR TITLE
Add the OLCF AF miller machine

### PR DESCRIPTION
**Pull request by minxu74**
The machine settings are for the US Air Force two HPE Cray EX supercomputers
(miller and fawbush) at ORNL. Each system consists of 800 computer nodes.
Each node has two 2nd Gen 7742 Epyc 64-core AMD Rome Processors and 256 GB
memory. Nodes are connected via the 100GB "Slingshot". It also includes 20
GPU nodes on miller supercomputer and each node contains four Nvidia A100 GPUs.

Three compilers are supported on Miller, GNU, Nvidia/nvhpc and AMD/aocc.

### CODE REVIEW

**Comment by rljacob** [comment]
@minxu74 go ahead and merge this.

**Comment by wlin7** [comment]
Hi @minxu74 , it appears the NML diffs for WCYCL1850 (e.g., chrysalis e3sm_integration_next_intel)  on fsurdat are due to this PR. fsurdat and flndtopo are changed to files with an older time stamp (c201220). I think one of the version contains land elevation class (ping @jonbob ). It does not cause difference to the results as the elevation class was not turned on in these tests. 

The changes are not documented in the commit message. I wonder if it is intended. Otherwise we need to revert.

**Comment by wlin7** [comment]
Oh, I saw a commit by @hyungyukang introduces this change. Hyun-Gyu, can you explain why the changes are needed?

**Comment by hyungyukang** [comment]
> Oh, I saw a commit by @hyungyukang introduces this change. Hyun-Gyu, can you explain why the changes are needed?

@wlin7 , please revert it. My mistake. When I ran WCYCL1850 on Miller machine, there was an error when reading fsurdat, so I changed it but forgot to revert it. Sorry for making this trouble.

**Comment by minxu74** [comment]
@wlin7 If you can help us revert this PR, it will be great, otherwise I will work on it tomorrow as I am tied by other things today. Thanks.

**Comment by wlin7** [comment]
No problem, @hyungyukang . Thanks to you both for the quick reply. I merged a PR yesterday while next was closed. So I wanted to make sure the diffs can be accounted for. @minxu74 , since we  need this PR for machine changes, I am going to put in a new PR just to revert the changes to the namelist_defaults.xml. I am going to ask Hyun-Gyu to give a quick review, procedure-wise.

**Comment by hyungyukang** [comment]
> No problem, @hyungyukang . Thanks to you both for the quick reply. I merged a PR yesterday while next was closed. So I wanted to make sure the diffs can be accounted for. @minxu74 , since we need this PR for machine changes, I am going to put in a new PR just to revert the changes to the namelist_defaults.xml. I am going to ask Hyun-Gyu to give a quick review, procedure-wise.

@wlin7 , Got it! Please let me know. Thanks!

**Pull request merged**
