### PR TITLE
Removes domain generation scripts under the land model

### LINKED ISSUE #2635: Domain generation code exists in two different places
The code to generate domain files exists in two different locations within our source tree: `cime/tools/mapping/gen_domain_files` and `components/clm/tools/shared/gen_domain`. At the moment these codes seem to differ by only a CPP directive or two, but PR #2633 makes some updates to the `gen_domain` tool located at `cime/tools/mapping/gen_domain_files` to allow the tool to work with mapping files generated using TempestRemap. This will cause these two codes to diverge, and rather than make sure both versions are up to date (and to prevent confusion in the future) I propose we remove the `gen_domain` source from the CLM component source tree and only use the source within the CIME source tree to generate domain files (especially since these files do not seem to be used by only the land model).

### PR DESCRIPTION
**Pull request by bishtgautam**
The duplicate domain generation code is removed under the land component as
the updated version of those scripts are available under CIME at
cime/tools/mapping/gen_domain_files.

Fixes #2635

[BFB]

### CODE REVIEW

**Comment by thorntonpe** [comment]
Is the functionality regulated by ifdefs in the land code tree version being carried over to the cime version? I last used the domain generation code years ago, so I don't know if that functionality is used or useful. If someone with recent experience (@bishtgautam ?) can say that the the cime version keeps this, or that we don't need it, then I'm fine with the change.

**Comment by bishtgautam** [comment]
- I don't have experience with `components/clm/tools/shared/gen_domain/src/gen_domain.F90`.
- `cime/tools/mapping/gen_domain_files/src/gen_domain.F90` and `components/clm/tools/shared/gen_domain/src/gen_domain.F90` have trivial differences related spaces and indenting.

**Comment by thorntonpe** [comment]
OK, sounds like dropping the duplicate code in the ELM tree is fine.

**Comment by jqyin** [comment]
Merged #2636

**Pull request merged**
