### PR TITLE
Adds a 1D bgc forcing test case and a bgc D-TEST

### PR DESCRIPTION
**Pull request by njeffery**
Atmospheric, ocean and biogeochemical data from the 2004 Ice Station Polarstern (ISPOL) Weddell Sea (67.9S, 54W) experiment from June 16, 2004 to December 31, 2004. Core 2 from the ISPOL location fills out the remainder of the year.

A uniform_1D initial condition was added for flexible initialization of BGC. Atmophere and Ocean forcing use the nCells dimension of 1. A new testcase - single_cell_ispol - was added to
MPAS-Dev/MPAS-Seaice_standalone_framework to verify this forcing and initializtion. https://github.com/MPAS-Dev/MPAS-Seaice_standalone_framework/pull/15

The ISPOL bgc forcing can be used with any of the gridded physics forcing datasets for testing purposes.

[NML]
[BFB]

### CODE REVIEW

**Comment by njeffery** [comment]
This branch was created in response to the concerns of  https://github.com/E3SM-Project/E3SM/pull/5282.  It includes 1D ISPOL forcing for a single column bgc testcase but has been adapted to be used in a BGC D-TEST.  In addition, atm and ocean forcing files include an nCells dimension.

**Comment by njeffery** [comment]
Completed the ispol single sell testcase and a  3-year DTESTM-BGC

**Comment by njeffery** [comment]
The code changes pass the single_cell_ispol test case:
https://github.com/MPAS-Dev/MPAS-Seaice_standalone_framework/pull/18

**Review by eclare108213 — APPROVED** [review]
These changes look fine to me but now there are conflicts that must be resolved.
Nicole tested both single-cell and D cases earlier.

**Comment by jonbob** [comment]
@njeffery -- I pushed changes to that Registry is consistent with the documentation you added in the namelist_files. If you get a chance, could you make sure they're what you wanted? I'l try a test merge and see if the file conflicts are easily resolved during that process

**Review by njeffery — COMMENTED** [review]
@jonbob : Thanks for the clean-up. These changes look good.

**Comment by jonbob** [comment]
passes:
* SMS_D_Ld1.T62_oEC60to30v3.DTESTM.chrysalis_intel
* SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod
* ERS.ne11_oQU240.WCYCL1850NS.chrysalis_intel

with expected NML DIFFs

merged to next

**Comment by jonbob** [comment]
merged to master and expected NML DIFFs blessed on all platforms except mappy -- which did not report

**Comment by njeffery** [comment]
Thanks @jonbob !

**Pull request merged**
