### PR TITLE
Change remove "_p" from area/lat/lon output variables

### PR DESCRIPTION
**Pull request by whannah1**
This changes the area/lat/lon variables in the history output for a physgrid run to not have the "_p" suffix. 

[BFB]

### CODE REVIEW

**Comment by oksanaguba** [comment]
@whannah1 did you run pg2 tests or should I? will there be cprnc errors due to renaming?

**Comment by whannah1** [comment]
I ran an ne4pg2 test and verified that the variable names were changed in the output.

**Comment by whannah1** [comment]
I think the only test that compares history files is an MMF test (crm-out).I'm not sure if this will cause a diff in that file comparison or not.

**Comment by oksanaguba** [comment]
Just in case I ran atm_integration and one of D cases on anvil. All is ok, in next.

**Pull request merged**
