### PR TITLE
HOMME, Aurora: Fix MKL flags from Intel MKL or oneMKL

### PR DESCRIPTION
**Pull request by abagusetty**
Add appropriate flags for MKL
`-mkl` for older Intel MKL modules
`-qmkl` for newer oneMKL modules

`-mkl` is deprecated with newer oneMKL library leading to linking issues referring to the MKL functions

### CODE REVIEW

**Comment by oksanaguba** [comment]
running tests now

**Comment by abagusetty** [comment]
> getting
> 
> ```
> CMake Error at CMakeLists.txt:261 (find_package):
>   By not providing "FindMKL.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "MKL", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "MKL" with any of
>   the following names:
> 
>     MKLConfig.cmake
>     mkl-config.cmake
> 
>   Add the installation prefix of "MKL" to CMAKE_PREFIX_PATH or set "MKL_DIR"
>   to a directory containing one of the above files.  If "MKL" provides a
>   separate development package or SDK, be sure it has been installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> ```

Strange that `find_package(MKL)` doesnt work on this machine. Could you post the name of the files under `$MKLROOT/lib/cmake`

**Comment by oksanaguba** [comment]
there is no `cmake` folder there

```
[ac.onguba@chrlogin2 HOMME_P24.f19_g16_rx1.A.chrysalis_intel.C.20241030_121333_ea825p]$ ls $MKLROOT/lib/cmake
ls: cannot access '/gpfs/fs1/soft/chrysalis/spack/opt/spack/linux-centos8-x86_64/intel-20.0.4/intel-mkl-2020.4.304-g2qaxzf/compilers_and_libraries_2020.4.304/linux/mkl/lib/cmake': No such file or directory
[ac.onguba@chrlogin2 HOMME_P24.f19_g16_rx1.A.chrysalis_intel.C.20241030_121333_ea825p]$ ls $MKLROOT/lib
ia32  ia32_lin  intel64  intel64_lin

```

**Comment by abagusetty** [comment]
Can you find if there are any files with extensions `*.cmake` under $MKLROOT, if there are any let me know the path. Looks like path is the issue here

**Comment by oksanaguba** [comment]
none 
```
[ac.onguba@chr-0493 mkl]$ find  ./ -name *so | wc -l
59
[ac.onguba@chr-0493 mkl]$ find  ./ -name *cmake | wc -l
0
[ac.onguba@chr-0493 mkl]$ pwd
/gpfs/fs1/soft/chrysalis/spack/opt/spack/linux-centos8-x86_64/intel-20.0.4/intel-mkl-2020.4.304-g2qaxzf/compilers_and_libraries_2020.4.304/linux/mkl
```

**Comment by oksanaguba** [comment]
``` [ac.onguba@chr-0493 mkl]$ find  ./ -name *so | wc -l
59
[ac.onguba@chr-0493 mkl]$ find  ./ -name *cmake | wc -l
0
[ac.onguba@chr-0493 mkl]$ pwd
/gpfs/fs1/soft/chrysalis/spack/opt/spack/linux-centos8-x86_64/intel-20.0.4/intel-mkl-2020.4.304-g2qaxzf/compilers_and_libraries_2020.4.304/linux/mkl
```

**Pull request merged**
