### PR TITLE
update google cloud gnu compiler to gcc-11

### PR DESCRIPTION
**Pull request by sarich**
Updates the gnu compiler on google cloud platform from 8.5.0 to 11.1.0

includes new library stack for:
netcdf
pnetcdf
hdf5
blas/lapack

tested on e3sm_integration with no new errors

[BFB]

### CODE REVIEW

**Review by ndkeen — COMMENTED** [review]
I really don't like the module names.  I was using 
```
mkdir .spack
cat > .spack/modules.yaml
modules:
  tcl:
    hash_length: 0
    naming_scheme: '{name}/{version}'
```

**Comment by sarich** [comment]
No problem, I can change the name. But we still need to differentiate between gcc8 and gcc11 versions, do you have a preference for that format?

**Comment by ndkeen** [comment]
Well shouldn't the `{name}/{version}` do that for us?

**Comment by rljacob** [comment]
Waiting to settle on module names

**Comment by ndkeen** [comment]
I see the commit. Module names look ok. Cool. I tested with one simple test and seems ok. Running a e3sm_developer.

**Review by ndkeen — CHANGES_REQUESTED** [review]
Actually, after the PR aptly named "Throttle sbatch submission on Crusher #5132", this flag adjustment is moved to Depends.gnu.cmake.  So you should not longer even need this file.

**Comment by ndkeen** [comment]
I tried one of our failing tests with this branch. `SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCLSSP370.gcp_gnu.allactive-wcprodssp` and it fails in a different way (with FP exception). So could be good to get this in and we can debug.

**Pull request merged**
