### PR TITLE
Update MALI in E3SM with new calving laws

### PR DESCRIPTION
**Pull request by matthewhoffman**
This merge updates MALI in E3SM for the first time since 9/3/2020.
The update serves two purposes:
* Bring in recently added calving laws and some bug fixes with temperature
* Bring E3SM up to date before transitioning from submodules to inline code.

[NML]
[non-BFB] only for MALI configurations

### CODE REVIEW

**Comment by jonbob** [comment]
@matthewhoffman - the automated scripts were unhappy with line 1147 of Registry.xml:
```
                <var name="s0" type="real" dimensions="nCells Time" units="none" time_levs="1"
                     description="a ratio between hydrostatic pressure and the largest principal tensile stress within ice shelf, rho_i * (rho_w - rho_i) * g * h / ( 2 * Tau_xx * rho_w ), where "h" is the ice thickness."
```
confuses it because of the double quotes around h. I made them single quotes and it seems to work fine, but that change will require an MPAS update...

**Comment by jonbob** [comment]
@matthewhoffman - I ran the automated scripts and updated the bld files, but please give them a careful look. There were lots of changes....

**Comment by matthewhoffman** [comment]
Thanks, @jonbob .  I'll take a look at your bld file updates, and I'll fix the quotation problem and update the submodule.

**Comment by jonbob** [comment]
Test merge now passes:
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
ERS.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel

SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel test is non-BFB with current master, differences in the following fields:
g2x_Sg_topo
g2x_Sg_lithop
g2x_Sg_tbot
g2x_Sg_dztbot

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
overnight testing showed a problem on pgi due to an unsupported "isnan" function. Testing of the fix now passes:
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi

**Comment by jonbob** [comment]
merged to master and expected DIFFs/NML-DIFFs blessed

**Pull request merged**
