### PR TITLE
mpas-source: improve performance of diagnostics

### PR DESCRIPTION
**Pull request by mark-petersen**
See https://github.com/MPAS-Dev/MPAS-Model/pull/719

This PR breaks up the diagnostic_solve subroutine, and modifies the split-explicit time-stepping scheme to have 1 of the calls to diagnostic solve only calculate a few of the variables.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
This currently shows compass changes from #3933, which will probably be merged today.

**Comment by mark-petersen** [comment]
From @mattdturner, The following E3SM tests PASS:
```
PET_Ln9_P8192.T62_oRRS18to6v3.GMPAS-IAF.cori-knl_intel
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_gnu
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
```

**Comment by mattdturner** [comment]
This was bfb compared to `ocean/develop` in MPAS-O when running the nightly test suite.

**Comment by mark-petersen** [comment]
Rebased. Only shows these MPAS changes now.

**Comment by jonbob** [comment]
Results were BFB for SMS_D_Ld1.ne30_r05_oECv3.A_WCYCL1850.compy_pgi tests comparing pre- and post-merge

**Review by vanroekel — APPROVED** [review]
approved based on testing by @mattdturner and @jonbob.  This PR is BFB and improves performance, so I'm also approving for inclusion in v2 for water cycle.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
This PR caused a bunch of DIFFs for non-debug compy-pgi tests

**Comment by mattdturner** [comment]
@jonbob Ok.  I'll look at the compy-pgi failures today and see if I can determine why PGI is non-bfb when intel and gnu are bfb

**Comment by jonbob** [comment]
reverted due to non-bfb results

**Comment by mark-petersen** [comment]
Rebased, added bug fix by @mattdturner in https://github.com/MPAS-Dev/MPAS-Model/pull/756.

@mattdturner could you give the head of this PR a quick PGI test to make sure?

**Comment by mattdturner** [comment]
Sure, I'll go ahead and start the test now.

**Comment by mattdturner** [comment]
I only ran 1 test that previously failed, but that test does indeed pass now:
```
    SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi.C.20201113_083804_qd3tez.cpl.hi.0001-01-06-00000.nc matched cpl.hi.0001-01-06-00000.nc
PASS
  Most recent bless: sha:8697827cb20c3290b39f0236937c16c749752883 date:2020-10-12_10:19:36
```

**Comment by mark-petersen** [comment]
Sanity tests: PASSES:
```
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
PEM_Ld5_P512.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_intel
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
```

**Comment by mattdturner** [comment]
Passed another previous failure:
```
    PEM_Ln9.ne30_oECv3_ICG.A_WCYCL1850S.compy_pgi.C.20201113_095740_0p9b9j.cpl.hi.0001-01-01-16200.nc matched cpl.hi.0001-01-01-16200.nc
PASS
  Most recent bless: sha:979af82760633b0c19d4095ca4eb42f98f1f5f9f date:2020-10-15_12:42:00
```

**Comment by jonbob** [comment]
remerged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
