### PR TITLE
Ocean SI code - Update and bug fix

### PR DESCRIPTION
**Pull request by hyungyukang**
This PR updates Ocean SI solver code (baroclinic parts) and fix a bug issued in #5361 when using `config_btr_si_partition_match_mode = .true.`

So far, the branch passed `PEM_Ln9_D.T62_oQU240.GMPAS-IAF.cori-knl_gnu` and `SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu` using configurations `config_time_integrator = 'split_implicit'` and `config_btr_si_partition_match_mode = .true.`

### CODE REVIEW

**Comment by vanroekel** [comment]
Thanks @hyungyukang by visual inspection this appears to address #5361 but I'd like @jonbob or @rljacob input on whether or not it is okay to have a PR that fixes that bug and includes a number of other updates (look performance related) to the SI solver.

**Comment by jonbob** [comment]
@hyungyukang - in general, a PR should have a singular purpose, meaning either fixing a bug or making performance improvements or other updates. Would it be difficult to separate the changes on this branch into two separate PRs?

**Comment by hyungyukang** [comment]
> @hyungyukang - in general, a PR should have a singular purpose, meaning either fixing a bug or making performance improvements or other updates. Would it be difficult to separate the changes on this branch into two separate PRs?

@jonbob got it. Sure, I will separate this PR into two PRs - 1) Update 2) Fix a bug. Is there a way to separate this PR or should I delete this PR then make branches and open PR separately?

**Comment by jonbob** [comment]
@hyungyukang - that may depend on the commits you've included in this branch. If one of them is only the bug fix, you could just keep that one commit in this si-bug-fix and we can easily change the PR description to match. But if the bug fix is intermixed with other changes in the commits, it may be easier to close this PR and make two different branches, each with its own PR.

**Comment by rljacob** [comment]
I suggest making 2 new branches with the separate changes and then a PR for each.  That makes for a cleaner history.

**Comment by hyungyukang** [comment]
> I suggest making 2 new branches with the separate changes and then a PR for each. That makes for a cleaner history.

@rljacob , agreed. I will close this PR and open two new PRs soon. Thanks!

**Pull request closed without merging**
