### PR TITLE
new compets, variables, defaults, etc for CBGC

### PR DESCRIPTION
**Pull request by maltrud**
This replaces #2228 for post-V1 code. This PR modifies CBGC compsets to include marine (ocean and sea ice) BGC, includes CO2 flux to be passed from MPAS-O to the coupler, allows a switch for making the alternate DIC field biotic or abiotic, and sets the default ocean output streams when using BGC.

[NML]
[BFB] for all currently tested compsets that do not include marine BGC

### CODE REVIEW

**Comment by jonbob** [comment]
passed ERS.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel

**Comment by jonbob** [comment]
test pending on SMS.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_1850.anvil_intel

**Comment by jonbob** [comment]
Failed SMS.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.sandiatoss3 due to missing marine BGC file - uploading it right now

Three other failures look like combination of land/ocn BGC:
```
 lnd_inX.YANG debug
 X.YANG debug SUPL NITROGEN and PHOSPHORUS NONE           NONE           
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Variable not found
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Variable not found
 NetCDF: Variable not found
 NetCDF: Variable not found
 NetCDF: Variable not found
 NetCDF: Variable not found
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Invalid dimension ID or name
 NetCDF: Variable not found
 NetCDF: Unknown file format
 pio_support::pio_die:: myrank=          -1 : ERROR: ionf_mod.F90:         235 :
  NetCDF: Unknown file format
Image              PC                Routine            Line        Source             
e3sm.exe           00000000030C666D  Unknown               Unknown  Unknown
e3sm.exe           0000000002E40DE1  pio_support_mp_pi         120  pio_support.F90
e3sm.exe           0000000002E3EECE  pio_utils_mp_chec          74  pio_utils.F90
e3sm.exe           0000000002F4C7F7  ionf_mod_mp_open_         235  ionf_mod.F90
e3sm.exe           0000000002E2FA24  piolib_mod_mp_pio        2834  piolib_mod.F90
e3sm.exe           0000000001DA6D0B  ncdio_pio_mp_ncd_         194  ncdio_pio.F90.in
e3sm.exe           0000000001DEAE1F  soilorder_varcon_         137  soilorder_varcon.F90
e3sm.exe           0000000001C9B6C6  clm_initializemod         241  clm_initializeMod.F90
e3sm.exe           0000000001C83D2A  lnd_comp_mct_mp_l         200  lnd_comp_mct.F90
e3sm.exe           00000000004392C8  component_mod_mp_         267  component_mod.F90
e3sm.exe           0000000000428A2C  cime_comp_mod_mp_        1180  cime_comp_mod.F90
e3sm.exe           00000000004364EC  MAIN__                     92  cime_driver.F90
e3sm.exe           000000000041A56E  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB4337C05  __libc_start_main     Unknown  Unknown
e3sm.exe           000000000041A469  Unknown               Unknown  Unknown
```

**Comment by rljacob** [comment]
There are also  .false. vs false namelist diffs.   I think this came up before and we decided to stick with .false.

**Comment by rljacob** [comment]
Yes that's fine.

**Comment by jonbob** [comment]
@rljacob - those changes from .false. to false are in the seaice model, which uses true/false more often than .true./.false. I agree it would be better to be consistent, so I can change these back if that just makes it easier. But for that model, I believe they want to drop the dots. I'll check with @akturner

**Comment by jonbob** [comment]
@maltrud - what is supposed to happen with the fully-coupled BGCEXP_BCRC_CNPECACNT_1850 compset? It runs if the lnd finidat is set to '' but fails otherwise. Do the lnd people need to make a corresponding change to their scripts? Are you fixing this in user_nl_clm every time otherwise?

**Comment by rljacob** [comment]
@jonbob yes it should be consistent within a model.  If they want to switch conventions, do that for all variables in a separate PR.

**Comment by jonbob** [comment]
@rljacob - agreed. I'll make changes so this PR doesn't change .false. to false, etc -- and then we'll work on consistency separately

**Comment by jonbob** [comment]
remerged to next

**Comment by rljacob** [comment]
Tests are showing BGC related namelist diffs in non-BGC compsets.  Is that expected?
example:
```
  BASE: config_bio_gravity_drainage_length_scale = 0.024
  COMP: config_bio_gravity_drainage_length_scale = 20.
```

in 
ERP_Ld3.ne30_oECv3_ICG.A_WCYCL1850S.sandiatoss3_intel
ERS.ne11_oQU240.A_WCYCL1850.sandiatoss3_intel
PEM_Ln9.ne30_oECv3_ICG.A_WCYCL1850S.sandiatoss3_intel
PET_Ln9_PS.ne30_oECv3_ICG.A_WCYCL1850S.sandiatoss3_intel

**Comment by jonbob** [comment]
@rljacob - That is expected. So far, the mpas components usually output more namelists than it actually uses -- and those changes are all to BGC settings. So even though they aren't pertinent, they are output for all namelists. We can make an issue to specify which namelist sections are output, if that would help.

**Comment by jonbob** [comment]
@rljacob - current testing has us failing one test but just namelist differences for others. The failing test was due to a required input file being on the ornl svn server but not the lcrc one. I've moved it there and requested that the specific test be manually rerun.

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
