### PR TITLE
 remove l_ieflx_fix

### PR DESCRIPTION
**Pull request by kaizhangpnl**
removed l_ieflx_fix in 

- components/cam/bld/namelist_files/namelist_definition.xml
- components/cam/src/physics/cam/phys_control.F90
- use_cases namelist files (under components/cam/bld/namelist_files/use_cases)

[BFB] 

Fixes https://github.com/E3SM-Project/E3SM/issues/2731

### CODE REVIEW

**Comment by rljacob** [comment]
Won't it be BFB for those cases too?  The variable didn't do anything so removing it won't change any answers.

**Comment by tangq** [comment]
For those use cases, ieflx_opt is all set to 2 (apply the energy fixer), which is needed for coupled runs. Same use cases are used by atmosphere-only (F) cases. However, we need ieflx_opt = 0 for F-cases. @rljacob , is there a good way to handle different atmospheric settings for companion coupled and atmosphere-only cases?

**Comment by kaizhangpnl** [comment]
> Won't it be BFB for those cases too? The variable didn't do anything so removing it won't change any answers.

@rljacob Yes, you are right! I was thinking about the problem Qi mentioned above, but it is a different one.

**Comment by rljacob** [comment]
@tangq I think you need to define a different use cases.  Why do F-cases need the fixer turned off?  If F-cases are used to tune the uncoupled atmosphere for coupled runs, the atmosphere settings need to be the same.

**Comment by kaizhangpnl** [comment]
> @tangq I think you need to define a different use cases. Why do F-cases need the fixer turned off? If F-cases are used to tune the uncoupled atmosphere for coupled runs, the atmosphere settings need to be the same.

The fixer is to fix the inconsistency in the energy terms considered between MPAS and EAM. For atm-only simulations, we think it is not needed.

**Comment by tangq** [comment]
> @tangq I think you need to define a different use cases. Why do F-cases need the fixer turned off? If F-cases are used to tune the uncoupled atmosphere for coupled runs, the atmosphere settings need to be the same.

Because this fixer is uniquely needed for the coupled simulations. @kaizhangpnl, the developer of it, can provide more details.

**Comment by tangq** [comment]
Should this change also be applied to maint-1.0?

**Comment by golaz** [comment]
If they don't cause any harm, I agree that the changes could also be applied to maint-1.0.

**Comment by rljacob** [comment]
@singhbalwinder please start merging this when next is clear. 

Note that this branch can't be merged to maint-1.0 because of where it started from.  A new branch will have to be made and PR issued for this fix to be placed on maint-1.0.

**Comment by singhbalwinder** [comment]
pushed to next

**Pull request merged**
