### PR TITLE
Fix a typo in LICENSE

### PR DESCRIPTION
**Pull request by bishtgautam**
Corrects the reference to MPP

[BFB]

### CODE REVIEW

**Comment by bishtgautam** [comment]
@rljacob, @agsalin, Should this minor fix be also added to maint-1.0?

**Comment by rljacob** [comment]
It should.  Which means the branch should start on are before that point.

**Comment by bishtgautam** [comment]
The branch started from maint-1.0. Do you want a separate PR whose merge destination is maint-1.0 instead of master?

**Comment by rljacob** [comment]
No just change the "base" on this PR to maint-1.0

**Comment by bishtgautam** [comment]
But shouldn't this be merged to both master and maint-1.0?

**Comment by rljacob** [comment]
yes but the master update will happen when we merge maint-1.0 to master.

**Comment by agsalin** [comment]
Sorry for my typo. Thanks for catching it. Please merge.

**Comment by rljacob** [comment]
merged to next.

**Pull request merged**
