### PR TITLE
Add ocean option for Redi kappa to be set equal to GM (AMOC PR 3/6)

### PR DESCRIPTION
**Pull request by mark-petersen**
add new option: `config_Redi_closure = 'equalGM'`, sets `RediKappa` equal to `gmBolusKappa` everywhere. Default remains `config_Redi_closure = 'constant'`.

[NML]
[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
This PR was started with the commits in #4835 and #4864. To see the changes relevant to this PR, look at this last commit: [ada0fac](https://github.com/E3SM-Project/E3SM/pull/4867/commits/ada0fac894c9787618cb9bb0d76796a56e6ab384)

**Review by vanroekel — APPROVED** [review]
Assuming @jonbob is happy with the NL changes, the actually code mods look good to me.  Approving by visual inspection.  It would be good though if someone could run a really short test to verify in output rediKappa = gmBolusKappa.  Maybe this has been done already though.

**Comment by mark-petersen** [comment]
@vanroekel I checked the output, and indeed `RediKappa = gmBolusKappa` when `config_Redi_closure = 'equalGM'`. But in the process, I realized that the ramp array, `gmResolutionTaper`, is only applied to GM, and not Redi (unless I missed it in the code). That would be a mistake, so I need to check carefully. It was my intention that the taper is applied uniformly to  `gmBolusKappa` and `RediKappa`. Do you agree?

**Comment by vanroekel** [comment]
Yes you are totally right, good catch there.  I forgot to mention that I passed `gmResolutionTaper` to redi in my implementation.  This could be added here or in #4864 as it is odd to just taper GM

**Comment by darincomeau** [comment]
I've run two 5 year `CRYO1850.ECwISC30to60E2r1` cases with this branch for comparison against the baseline:

[Baseline](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.milena/20220301.CRYO1850.ne30pg2_ECwISC30to60E2r1.chrysalis.CryoBranchBaseline/Years1-5/)

[This branch with config_Redi_closure = 'equalGM'; default GM here is constant](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.dcomeau/20220405.CRYO1850.ne30pg2_ECwISC30to60E2r1.chrysalis.CryoBranchRediEqGM/yrs1-5/)

[This branch with config_Redi_closure = 'equalGM' and config_GM_closure = 'Visbeck', so GM kappa is not constant](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.dcomeau/20220405.CRYO1850.ne30pg2_ECwISC30to60E2r1.chrysalis.CryoBranchRediEqGMVisbeck/yrs1-5/)

**Comment by milenaveneziani** [comment]
I have run a 5-year test with this branch for the SORRM that is equivalent, in terms of settings, to Darin's third set mentioned above:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.milena/20220408.CRYO1850.ne30pg2_SOwISC12to60E2r4.chrysalis.CryoBranchRediEqGM/Years1-5/

**Comment by mark-petersen** [comment]
> I realized that the ramp array, gmResolutionTaper, is only applied to GM, and not Redi ([comment above](https://github.com/E3SM-Project/E3SM/pull/4867#issuecomment-1089288164)) 

Never mind. I did apply horizontal tapering to Redi this whole time. I just did it directly on init, rather than with a coefficient array.
https://github.com/E3SM-Project/E3SM/blob/22db37672ff7bbb9aefe29a010ea824d836ae97b/components/mpas-ocean/src/shared/mpas_ocn_tracer_hmix_redi.F#L546-L560
It’s only with the new ‘RossbyRadius’ tapering option in this PR that the taper changes in time, so changing RediKappa in init made sense.

**Comment by mark-petersen** [comment]
This PR requires the same init and additional tapering variables as #4864, so I am closing this one and adding this single flag addition (`config_Redi_closure = 'equalGM'`) to that PR.

**Pull request closed without merging**
