### PR TITLE
improvements to edge_mod interface to reduce memory

### PR DESCRIPTION
**Pull request by mt5555**
This PR improves the edge_mod pack and unpack interface to make the data structures independent of the amount of data that needs to be exchanged.   This lets the code share a single common edge buffer that is used for all boundary exchanges.  

Memory savings come from consolidating edge3p1, edgeAdv and edgeAdvp1 into a single "edge_g"

additional memory savings also come from removing the the duplicate meta data ( getmap, putmap and reverse) from the edge% struct and we rely only on the meta data already in the elem(ie) struct.

### CODE REVIEW

**Comment by susburrows** [comment]
I added a BFB label based on comment from @mt5555 above

**Comment by mrnorman** [comment]
I've tried:
git remote add mark git@ssh.github.com:mt5555/ACME.git
git remote add mark git@github.com:mt5555/ACME.git

And each time I "git fetch mark", I get:

ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Am I doing something wrong?

**Comment by rljacob** [comment]
Mark needs to add you as a collaborator on his fork.  https://help.github.com/articles/permission-levels-for-a-user-account-repository/

**Comment by rljacob** [comment]
No wait. I think @mt5555 needs to visit his fork and set it to public.  To correspond with the now-public upstream master.

**Comment by mt5555** [comment]
Done.  Sorry for the delay.

**Comment by rljacob** [comment]
@mrnorman can you review now?

**Comment by mt5555** [comment]
@mrnorman : I updated the ACC code to use the variable nlyr interface - and then removed all the edge variables except for "edge_g", used by all routines for boundary data, and edgeminmax, used by the limiter.  

One question:  there is a block of openacc code using "pcopyin" for a bunch of the edge data.  Two of the arrays (putmap and getmap) have been removed, as the new interface uses the original data in elem%putmap and elem%getmap.     

Should this data be added to the pcopyin calls?

**Comment by mt5555** [comment]
@rljacob : I pushed some more commits to this branch in my fork on May 6, but they dont show up in the PR.  any idea why?

**Comment by mrnorman** [comment]
@mt5555 , thanks for doing that. Yes, every member of the edge buffer should have a pcopyin statement. The reason is because most of edgebuffer's members have either allocatable or pointer attributes.

**Comment by mt5555** [comment]
@mrnorman :  just to confirm:  

So there are three arrays:  reverse, putmap and getmap, which used to be in the edge structs. These were precomputed indicies that depended on number of layers that the buffer was going to hold.  I removed these, and instead now use elem(ie)%putmapP and elem(ie)%getmapP arrays ( or the "S" version of those arrays for the minmax).  These are independent of the number of layers, and thus allow us to the same edge buffer for all pack/exchange/unpack.  

Above you wrote "every member of the edge buffer should have a pcopyin statement", which is still true.  

But what about these members of the elem(ie) struct which will now be used during the pack/unpack?

**Comment by mrnorman** [comment]
If elem(ie)%putmapP and elem(ie)%getmapP are pointers or allocatables, then they must also be put separately in a pcopyin() statement. Otherwise, they'll be sent automatically when elem is sent.

For OpenACC, it shouldn't be important to flatten out putmapP and getmapP unless you're passing them as parameters. If you're just passing elem(:) and accessing them through that, then it'll be fine to reference it as elem(ie)%putmapP(...) inside OpenACC kernels in edgeVpack_openacc.

**Comment by mt5555** [comment]
they are allocatable, but there is no reason for that.   I'll change them to static to simplify the code.

**Comment by mt5555** [comment]
I didn't have it quite right.  old code:
subroutine edgeSpack_openacc( edge, ..... )
     j = edge%putmap(i,ie)

new code:  
subroutine edgeSpack_openacc( edge, ..... )
   desc=edge%desc(ie)
   j =  desc%putmapP(i)

So the array edge%putmap is gone now and hence removed from the openacc pcopyin statements. 

the currently look like this:  

  !$acc enter data pcopyin(edgeMinMax         ,edge_g)                                                              
    !$acc enter data pcopyin(edgeMinMax%desc    ,edge_g%desc)                                                         
    !$acc enter data pcopyin(edgeMinMax%moveLength    ,edge_g%moveLength)                                             
    !$acc enter data pcopyin(edgeMinMax%movePtr0      ,edge_g%movePtr0)                                               
    !$acc enter data pcopyin(edgeMinMax%srequest,edge_g%srequest)                                                     
    !$acc enter data pcopyin(edgeMinMax%rrequest,edge_g%rrequest)                                                     
    !$acc enter data pcopyin(edgeMinMax%receive ,edge_g%receive)                                                      
    !$acc enter data pcopyin(edgeMinMax%buf     ,edge_g%buf)

**Comment by mrnorman** [comment]
I would like to rebase my OpenACC branch with this branch, but I don't know how. I still can't seem to add the fork as a remote to my E3SM repo. I'm not sure I can cherry-pick the hashes either without a remote.

**Comment by mt5555** [comment]
So what happens when you type this:
git remote add mt5555 git@github.com:mt5555/ACME.git

Can you add any other public repos as remotes?  i.e. what happens if you type this:
git remote add paullric git@github.com:paullric/tempestremap.git

**Comment by mt5555** [comment]
I've merged your changes in, and this passes all the HOMME regression tests.  I think we can go ahead and merge to master now.

**Comment by mrnorman** [comment]
@mt5555 , what is the difference between nlyr and vlyr in the call to edgeVpack?

**Comment by mrnorman** [comment]
Sorry, nevermind, I see it now.

**Comment by mt5555** [comment]
Replaced by PR #2351

**Pull request closed without merging**
