### PR TITLE
Fixes for bfb restart and partitions tests in E3SM

### LINKED ISSUE #2702: Compsets with ISMF failing ERS tests
The following compsets with ice shelf melt fluxes on (ISMF) are failing ERS tests:

A_WCYCL1850-DIB-ISMF_CMIP6
GMPAS-DIB-IAF-ISMF

@mark-petersen has confirmed that in MPAS-Ocean standalone, configurations with ice shelf melt fluxes on do pass exact restart tests (for the oEC60to30v3wLI grid).

### PR DESCRIPTION
**Pull request by mark-petersen**
There are three changes.

1. Widen halo computation ring for kinetic energy.
2. Widen halo computation ring for melt fluxes.
3. Add halo exchange for surfaceFrictionVelocity

When running E3SM with melt fluxes on, the first is needed for bfb restarts and all three for bfb partition tests (#2739).

fixes #2702 and #2739

### CODE REVIEW

**Comment by jonbob** [comment]
@mark-petersen - I assume these changes are BFB, at least for all the tested configurations?

**Comment by jonbob** [comment]
merged to next

**Comment by mark-petersen** [comment]
bfb with previous except for ISMF tests, which were failing PEM and ERS tests before.

**Comment by rljacob** [comment]
Are PEM and ERS tests with ISMF being added to one of the E3SM test suites?

**Comment by jonbob** [comment]
Thanks @rljacob - I will do that in a follow-on PR

**Comment by jonbob** [comment]
In next, passed:
* ERS_P480.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_intel
* PEM_P480.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.anvil_intel

**Comment by rljacob** [comment]
You could add one to the high-res suite if thats all you have.  Or extra-coverage.   Depends on how slow it is if you need to go all the way down to the low res configs.

**Comment by jonbob** [comment]
There was one unexpected failure during overnight testing of next: ERS.ne11_oQU240.A_WCYCL1850.anvil_intel. I reran it by hand and it passed for me -- so I assume this PR is good to go.

**Comment by jonbob** [comment]
merged to master

**Comment by jonbob** [comment]
Automated testing of these new features in [PR #2749](https://github.com/E3SM-Project/E3SM/pull/2749)

**Pull request merged**
