### PR TITLE
Update mpas-source: modify Eden Greatbatch length scale

### PR DESCRIPTION
**Pull request by mark-petersen**
Includes:
-  Adds modifications to the E&G length scale https://github.com/MPAS-Dev/MPAS-Model/pull/714 
- changes GM config option names for clarity https://github.com/MPAS-Dev/MPAS-Model/pull/717

[NML]
[non-BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
@vanroekel please verify that you want these same values in E3SM:
```
config_gm_EG_kappa_factor = 3.0
config_gm_EG_Rossby_factor = 2.0
config_gm_EG_Rhines_factor = 0.3
```

**Comment by mark-petersen** [comment]
This is ready for the namelist script and then testing. Here are the defaults from MPAS:
```
 54 &mesoscale_eddy_parameterizations
 55     config_eddying_resolution_taper = 'ramp'
 56     config_eddying_resolution_ramp_min = 20e3
 57     config_eddying_resolution_ramp_max = 30e3
 58 /
 59 &Redi_isopycnal_mixing
 60     config_use_Redi = .false.
 61     config_Redi_closure = 'constant'
 62     config_Redi_constant_kappa = 600.0
 63     config_Redi_maximum_slope = 0.3
 64     config_Redi_use_slope_taper = .true.
 65     config_Redi_use_surface_taper = .true.
 66     config_Redi_N2_based_taper_enable = .true.
 67     config_Redi_N2_based_taper_min = 0.1
 68     config_Redi_N2_based_taper_limit_term1 = .true.
 69 /
 70 &GM_eddy_parameterization
 71     config_use_GM = .false.
 72     config_GM_closure = 'EdenGreatbatch'
 73     config_GM_constant_kappa = 600.0
 74     config_GM_constant_gravWaveSpeed = 0.3
 75     config_GM_spatially_variable_min_kappa = 300.0
 76     config_GM_spatially_variable_max_kappa = 1800.0
 77     config_GM_spatially_variable_baroclinic_mode = 1.0
 78     config_GM_Visbeck_alpha = 0.005
 79     config_GM_Visbeck_max_depth = 1000.0
 80     config_GM_EG_riMin = 200.0
 81     config_GM_EG_kappa_factor = 3.0
 82     config_GM_EG_Rossby_factor = 2.0
 83     config_GM_EG_Rhines_factor = 0.3
 84 /
```
We set `config_use_Redi` and `config_use_GM` based on the resolution. @vanroekel can you check the defaults on all the others, for E3SM? For comparison, here are the current lines in E3SM:
```
components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
132 <!-- Redi_isopycnal_mixing -->
133 <config_use_Redi>.true.</config_use_Redi>
134 <config_use_Redi ocn_grid="oRRS30to10">.false.</config_use_Redi>
135 <config_use_Redi ocn_grid="oRRS30to10v3">.false.</config_use_Redi>
136 <config_use_Redi ocn_grid="oRRS30to10wLI">.false.</config_use_Redi>
137 <config_use_Redi ocn_grid="oRRS30to10v3wLI">.false.</config_use_Redi>
138 <config_use_Redi ocn_grid="oRRS18to6">.false.</config_use_Redi>
139 <config_use_Redi ocn_grid="oRRS18to6v3">.false.</config_use_Redi>
140 <config_use_Redi ocn_grid="oRRS15to5">.false.</config_use_Redi>
141 <config_Redi_kappa>400.0</config_Redi_kappa>
142 <config_Redi_kappa ocn_forcing="datm_forced_restoring">400.0</config_Redi_kappa>
143 <config_Redi_set_RediKappa_to_GMKappa>.false.</config_Redi_set_RediKappa_to_GMKappa>
144 <config_Redi_maximum_slope>0.01</config_Redi_maximum_slope>
145 <config_Redi_closure>'constant'</config_Redi_closure>
146 <config_Redi_use_slope_taper>.true.</config_Redi_use_slope_taper>
147 <config_Redi_use_surface_taper>.true.</config_Redi_use_surface_taper>
148 <config_Redi_use_N2_based_taper>.true.</config_Redi_use_N2_based_taper>
149 <config_Redi_N2_limit_term1>.true.</config_Redi_N2_limit_term1>
150
151 <!-- GM_eddy_parameterization -->
152 <config_use_GM>.true.</config_use_GM>
153 <config_use_GM ocn_grid="oRRS30to10">.false.</config_use_GM>
154 <config_use_GM ocn_grid="oRRS30to10v3">.false.</config_use_GM>
155 <config_use_GM ocn_grid="oRRS30to10wLI">.false.</config_use_GM>
156 <config_use_GM ocn_grid="oRRS30to10v3wLI">.false.</config_use_GM>
157 <config_use_GM ocn_grid="oRRS18to6">.false.</config_use_GM>
158 <config_use_GM ocn_grid="oRRS18to6v3">.false.</config_use_GM>
159 <config_use_GM ocn_grid="oRRS15to5">.false.</config_use_GM>
160 <config_GM_kappa>1800.0</config_GM_kappa>
161 <config_GM_kappa ocn_forcing="datm_forced_restoring" ocn_grid="oEC60to30v3wLI">600.0</config_GM_kappa>
162 <config_GM_kappa ocn_forcing="datm_forced_restoring" ocn_grid="ECwISC30to60E1r2">600.0</config_GM_kappa>
163 <config_GM_kappa ocn_forcing="datm_forced_restoring" ocn_grid="EC30to60E2r2">600.0</config_GM_kappa>
164 <config_GM_kappa ocn_forcing="datm_forced_restoring" ocn_grid="WC14to60E2r3">600.0</config_GM_kappa>
165 <config_GM_closure>'visbeck'</config_GM_closure>
166 <config_GM_baroclinic_mode>3.0</config_GM_baroclinic_mode>
167 <config_GM_Visbeck_alpha>0.13</config_GM_Visbeck_alpha>
168 <config_GM_Visbeck_max_depth>1000.0</config_GM_Visbeck_max_depth>
169 <config_GM_Visbeck_min_kappa>300.0</config_GM_Visbeck_min_kappa>
170 <config_GM_Visbeck_max_kappa>1800.0</config_GM_Visbeck_max_kappa>
171 <config_gm_EG_riMin>200.0</config_gm_EG_riMin>
172 <config_gm_EG_kappa_factor>2.0</config_gm_EG_kappa_factor>
173 <config_GM_min_stratification_ratio>0.1</config_GM_min_stratification_ratio>
174 <config_GM_constant_gravWaveSpeed>0.3</config_GM_constant_gravWaveSpeed>
175
176 <!-- mesoscale_eddy_parameterizations -->
177 <config_eddying_resolution_taper>'ramp'</config_eddying_resolution_taper>
178 <config_eddying_resolution_ramp_min>20e3</config_eddying_resolution_ramp_min>
179 <config_eddying_resolution_ramp_max>30e3</config_eddying_resolution_ramp_max>
```

**Comment by jonbob** [comment]
OK, I'm working on the automated scripts to regenerate the bld files

**Comment by vanroekel** [comment]
I think we should change to MPAS defaults except for these changes
```
config_GM_constant_kappa = 1800.0
config_Redi_constant_kappa = 400.0
```

everything else looks good in the mpas list.

**Comment by vanroekel** [comment]
missed one, this should be
```
config_GM_spatially_variable_baroclinic_mode = 3.0
```

**Comment by jonbob** [comment]
in the coupled system we have config_use_Redi set to true by default and false for higher resolution grids. Do we want it true for any grid?

**Comment by jonbob** [comment]
@vanroekel - which defaults do you mean? The ones currently in E3SM or the ones in MPAS Registry?

**Comment by vanroekel** [comment]
@jonbob sorry for the confusion -- relative to the coupled system

1) only have redi on for the RRM grids and EC30to60 (Same as GM)
2) change config_GM_EG_kappa_factor to 3.0
3) change default config_GM_closure to 'EdenGreatbatch'

Looks like the rest just need to be flipped to appropriate naming with the PR, values can stay the same as in E3SM now.

**Review by vanroekel — APPROVED** [review]
approved by visual inspection, thanks @jonbob

**Comment by mark-petersen** [comment]
Passes
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
PET_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-haswell_intel
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
PEM_Ld5_P512.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_intel
```

**Comment by jonbob** [comment]
@mark-petersen, @vanroekel - is this ready to go in today?

**Comment by vanroekel** [comment]
@jonbob yes it's ready

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master and expected DIFFs blessed

**Pull request merged**
