### PR TITLE
Fix SCREAM issue about HOMMEXX_ENABLE_GPU

### PR DESCRIPTION
**Pull request by oksanaguba**
Adding HOMMEXX_ENABLE_GPU to Hommexx_config in order for scream code to pick it up.

Scream builds of homme do not use config file in theta-l_kokkos.

[bfb]

### CODE REVIEW

**Comment by oksanaguba** [comment]
On weaver, last commit:
unit tests pass
preqx-.*ne2 pass for cxx vs F
theta-f.*ne2 pass for cxx vs F


this is ready.

**Comment by ambrad** [comment]
Builds and runs on Summit. I'll make a final comment after SCREAM's AT runs.

**Review by ambrad — APPROVED** [review]

**Comment by oksanaguba** [comment]
@ambrad  thanks -- i will merge it without testing.

**Comment by oksanaguba** [comment]
... nevermind. i will run homme suite on chrysalis anyway.

**Comment by oksanaguba** [comment]
Homme suite on chrysalis passed against machine baselines.

**Comment by oksanaguba** [comment]
in next

**Pull request merged**
