### PR TITLE
Upgrade anlgce-ub18 to anlgce-ub22

### PR DESCRIPTION
**Pull request by dqwu**
Recently, two ANL GCE nodes (compute-01 and compute-02) have been
upgraded from Ubuntu 18.04 to 22.04. Create a new machine named
anlgce-ub22 to replace deprecated anlgce-ub18.

Also remove deprecated CMake macro ZLIB_PATH for anlgce/anlgce-ub22.

[BFB]

### CODE REVIEW

**Review by jayeshkrishna — APPROVED** [review]

**Comment by dqwu** [comment]
@jayeshkrishna This PR was rebased once to fix a typo. It seems that the old PR (before rebase) was merged to next branch instead.

next branch:
`      <env name="NETCDF_PATH">/nfs/gce/projects/climate/software/linux-ubuntu22.04-x86_64/netcdf/4.8.0c-4.3.1cxx-4.5.3f-serial/gcc-11.1.0</env>`

Updated PR:
`      <env name="NETCDF_PATH">/nfs/gce/projects/climate/software/linux-ubuntu22.04-x86_64/netcdf/4.8.0c-4.3.1cxx-4.5.3f-serial/gcc-12.1.0</env>`

Please update next branch accordingly, otherwise next branch and master branch will be different after this PR is merged to master branch.

**Comment by rljacob** [comment]
Looks like it was remerged to next right before your comment.

**Comment by dqwu** [comment]
> Looks like it was remerged to next right before your comment.

It has not been remerged so far to apply the typo fix (i checked latest next branch).

**Comment by dqwu** [comment]
@jayeshkrishna For remerge, there is a merge conflict to be resolved.

**Pull request merged**
