### PR TITLE
bug-fix, moved condition during pftvarcon to be true with fates as well.

### LINKED ISSUE #4582: SMS_D_Ld4.f45_f45.IELMFATES -- Subscript #1 of the array PFTNAME has value 25 which is greater than the upper bound of 24
Using e3sm master and trying: `SMS_D_Ld4.f45_f45.IELMFATES` on cori-knl with intel (likely any machine)

I see: 

```
39: forrtl: severe (408): fort: (2): Subscript #1 of the array PFTNAME has value 25 which is greater than the upper bound of 24
39:
39: Image              PC                Routine            Line        Source
39: e3sm.exe           0000000006C59C16  Unknown               Unknown  Unknown
39: e3sm.exe           0000000000DCED18  pftvarcon_mp_pftc        1020  pftvarcon.F90
39: e3sm.exe           00000000009577F8  elm_initializemod         248  elm_initializeMod.F90
39: e3sm.exe           00000000008A888C  lnd_comp_mct_mp_l         242  lnd_comp_mct.F90
39: e3sm.exe           000000000046B532  component_mod_mp_         257  component_mod.F90
39: e3sm.exe           0000000000414DD9  cime_comp_mod_mp_        1426  cime_comp_mod.F90
39: e3sm.exe           0000000000461FFD  MAIN__                    122  cime_driver.F90
39: e3sm.exe           0000000000401F72  Unknown               Unknown  Unknown
39: e3sm.exe           0000000006DE918F  Unknown               Unknown  Unknown
```

This is a new issue after https://github.com/E3SM-Project/E3SM/issues/4251 was fixed

### PR DESCRIPTION
**Pull request by rgknox**
bug-fix, moved condition during pftvarcon to be true with fates as well.

Fixes #4582

### CODE REVIEW

**Comment by ndkeen** [comment]
OK.  I noted on https://github.com/E3SM-Project/E3SM/issues/4251 that I'm not seeing the error anymore -- can you verify that the PR mentioned there is the fix? I guess we can close it either way, but just might be nice to know what PR fixed it.

**Comment by rgknox** [comment]
Are any FATES tests passing right now on any machines?

**Review by evasinha — APPROVED** [review]

**Comment by peterdschwartz** [comment]
@rgknox  I'm seeing all FATES tests passing from overnight testing on chrysalis, compy, and mappy. [CDash](https://my.cdash.org/index.php?project=E3SM&date=2021-11-09).  Only cori-knl has fails for the fates-eca and fates-rd tests.

**Comment by rgknox** [comment]
Thanks for that info @peterdschwartz and thanks for the review @evasinha !

**Comment by peterdschwartz** [comment]
Merged to next

**Comment by rljacob** [comment]
was this non-BFB for any cases?

**Comment by peterdschwartz** [comment]
@rljacob  Couldn't find any bless requests associated with this PR.

**Pull request merged**
