### PR TITLE
Adding an FC test with theta SL

### PR DESCRIPTION
**Pull request by oksanaguba**
Adding a short test for coupled run with theta-l and SL.

[BFB]

### CODE REVIEW

**Comment by oksanaguba** [comment]
Used qsplit=4 for ne4 resolution. According to this test SMS.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.cam-cosplite rsplit=2 and nsplit=2. 

Tested on anvil via 
```
~/acme-b2//cime/scripts/create_test -g -o --baseline-root ~/as/acme-tests -b test-fc SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl
```
It ran and it used theta and SL.

**Comment by rljacob** [comment]
Do you know how long the test takes to run?

**Comment by oksanaguba** [comment]
Seems like <2 minutes to run. But then i see this
```
Exception during GENERATE:
ERROR: 'SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl.G.20190524_001841_r4u6xy' does not look like a CIME test name, expect TESTCASE.GRID.COMPSET[.MACHINE_COMPILER[.TESTMODS]]
``` -- is it a problem?

**Comment by rljacob** [comment]
@jgfouca ?   See above.

**Comment by jgfouca** [comment]
Yeah, that's a problem. I don't see anything wrong with the testname though.

**Comment by jgfouca** [comment]
I'm trying to duplicate the error on melvin.

**Comment by jgfouca** [comment]
```
% ./create_test -g -o -b fouc SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl --wait
No project info available
Creating test directory /lcrc/group/acme/acmetest/acme_scratch/anvil/SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl.G.20190524_154139_evm0hs
RUNNING TESTS:
  SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl
Starting CREATE_NEWCASE for test SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl with 1 procs
Finished CREATE_NEWCASE for test SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl in 5.405447 seconds (PASS)
Starting XML for test SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl with 1 procs
Finished XML for test SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl in 0.498053 seconds (PASS)
Starting SETUP for test SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl with 1 procs
Finished SETUP for test SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl in 12.108520 seconds (PASS)
Starting SHAREDLIB_BUILD for test SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl with 1 procs
Finished SHAREDLIB_BUILD for test SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl in 436.988415 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /lcrc/group/acme/acmetest/acme_scratch/anvil/SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl.G.20190524_154139_evm0hs
    Errors were:
        Building test for SMS in directory /lcrc/group/acme/acmetest/acme_scratch/anvil/SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl.G.20190524_154139_evm0hs
        ERROR: /blues/gpfs/home/acmetest/ACME/cime/src/build_scripts/buildlib.kokkos FAILED, cat /lcrc/group/acme/acmetest/acme_scratch/anvil/SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl.G.20190524_154139_evm0hs/bld/kokkos.bldlog.190524-154158
```

**Comment by jgfouca** [comment]
```
Failed to find custom kokkos options, using default: --with-serial.
/blues/gpfs/home/acmetest/ACME/externals/kokkos/generate_makefile.bash --with-serial --compiler=icpc --prefix=/lcrc/group/acme/acmetest/acme_scratch/anvil/SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl.G.20190524_154139_evm0hs/bld/intel/mvap\
ich/nodebug/nothreads/mct
Generating Makefiles with options  KOKKOS_SRC_PATH=/blues/gpfs/home/acmetest/ACME/externals/kokkos CXX=/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.0-yko5ui4sbwwehofzpvvdx3k5cii6n63s/co\
mpilers_and_libraries_2017.0.098/linux/bin/intel64/icpc KOKKOS_DEVICES=Serial GTEST_PATH=/blues/gpfs/home/acmetest/ACME/externals/kokkos/tpls/gtest KOKKOS_PATH=/blues/gpfs/home/acmetest/ACME/externals/kokkos

gmake -j 8
cd core; \
        gmake -f /blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/Makefile KOKKOS_SRC_PATH=/blues/gpfs/home/acmetest/ACME/externals/kokkos CXX=/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-profess\
ional.2017.0-yko5ui4sbwwehofzpvvdx3k5cii6n63s/compilers_and_libraries_2017.0.098/linux/bin/intel64/icpc KOKKOS_DEVICES=Serial GTEST_PATH=/blues/gpfs/home/acmetest/ACME/externals/kokkos/tpls/gtest KOKKOS_PATH=/blues/gpfs/home/acmetest/ACME/e\
xternals/kokkos PREFIX=/lcrc/group/acme/acmetest/acme_scratch/anvil/SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl.G.20190524_154139_evm0hs/bld/intel/mvapich/nodebug/nothreads/mct build-lib
gmake[1]: Entering directory `/lcrc/group/acme/acmetest/acme_scratch/anvil/SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl.G.20190524_154139_evm0hs/bld/intel/mvapich/nodebug/nothreads/mct/kokkos/core'
/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.0-yko5ui4sbwwehofzpvvdx3k5cii6n63s/compilers_and_libraries_2017.0.098/linux/bin/intel64/icpc  -I./ -I/blues/gpfs/home/acmetest/ACME/external\
s/kokkos/core/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/containers/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/algorithms/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/eti --std=c++11 -O3 -c /blues/gpf\
s/home/acmetest/ACME/externals/kokkos/core/src/impl/Kokkos_CPUDiscovery.cpp
/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.0-yko5ui4sbwwehofzpvvdx3k5cii6n63s/compilers_and_libraries_2017.0.098/linux/bin/intel64/icpc  -I./ -I/blues/gpfs/home/acmetest/ACME/external\
s/kokkos/core/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/containers/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/algorithms/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/eti --std=c++11 -O3 -c /blues/gpf\
s/home/acmetest/ACME/externals/kokkos/core/src/impl/Kokkos_Core.cpp
/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.0-yko5ui4sbwwehofzpvvdx3k5cii6n63s/compilers_and_libraries_2017.0.098/linux/bin/intel64/icpc  -I./ -I/blues/gpfs/home/acmetest/ACME/external\
s/kokkos/core/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/containers/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/algorithms/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/eti --std=c++11 -O3 -c /blues/gpf\
s/home/acmetest/ACME/externals/kokkos/core/src/impl/Kokkos_Error.cpp
/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.0-yko5ui4sbwwehofzpvvdx3k5cii6n63s/compilers_and_libraries_2017.0.098/linux/bin/intel64/icpc  -I./ -I/blues/gpfs/home/acmetest/ACME/external\
s/kokkos/core/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/containers/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/algorithms/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/eti --std=c++11 -O3 -c /blues/gpf\
s/home/acmetest/ACME/externals/kokkos/core/src/impl/Kokkos_ExecPolicy.cpp
/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.0-yko5ui4sbwwehofzpvvdx3k5cii6n63s/compilers_and_libraries_2017.0.098/linux/bin/intel64/icpc  -I./ -I/blues/gpfs/home/acmetest/ACME/external\
s/kokkos/core/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/containers/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/algorithms/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/eti --std=c++11 -O3 -c /blues/gpf\
s/home/acmetest/ACME/externals/kokkos/core/src/impl/Kokkos_HostBarrier.cpp
/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.0-yko5ui4sbwwehofzpvvdx3k5cii6n63s/compilers_and_libraries_2017.0.098/linux/bin/intel64/icpc  -I./ -I/blues/gpfs/home/acmetest/ACME/external\
s/kokkos/core/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/containers/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/algorithms/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/eti --std=c++11 -O3 -c /blues/gpf\
s/home/acmetest/ACME/externals/kokkos/core/src/impl/Kokkos_HostSpace.cpp
/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.0-yko5ui4sbwwehofzpvvdx3k5cii6n63s/compilers_and_libraries_2017.0.098/linux/bin/intel64/icpc  -I./ -I/blues/gpfs/home/acmetest/ACME/external\
s/kokkos/core/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/containers/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/algorithms/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/eti --std=c++11 -O3 -c /blues/gpf\
s/home/acmetest/ACME/externals/kokkos/core/src/impl/Kokkos_HostSpace_deepcopy.cpp
/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.0-yko5ui4sbwwehofzpvvdx3k5cii6n63s/compilers_and_libraries_2017.0.098/linux/bin/intel64/icpc  -I./ -I/blues/gpfs/home/acmetest/ACME/external\
s/kokkos/core/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/containers/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/algorithms/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/eti --std=c++11 -O3 -c /blues/gpf\
s/home/acmetest/ACME/externals/kokkos/core/src/impl/Kokkos_HostThreadTeam.cpp
/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.0-yko5ui4sbwwehofzpvvdx3k5cii6n63s/compilers_and_libraries_2017.0.098/linux/bin/intel64/icpc  -I./ -I/blues/gpfs/home/acmetest/ACME/external\
s/kokkos/core/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/containers/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/algorithms/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/eti --std=c++11 -O3 -c /blues/gpf\
s/home/acmetest/ACME/externals/kokkos/core/src/impl/Kokkos_MemoryPool.cpp
/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.0-yko5ui4sbwwehofzpvvdx3k5cii6n63s/compilers_and_libraries_2017.0.098/linux/bin/intel64/icpc  -I./ -I/blues/gpfs/home/acmetest/ACME/external\
s/kokkos/core/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/containers/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/algorithms/src -I/blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/eti --std=c++11 -O3 -c /blues/gpf\
s/home/acmetest/ACME/externals/kokkos/core/src/impl/Kokkos_Profiling_Interface.cpp
gmake[1]: Leaving directory `/lcrc/group/acme/acmetest/acme_scratch/anvil/SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl.G.20190524_154139_evm0hs/bld/intel/mvapich/nodebug/nothreads/mct/kokkos/core'
In file included from /blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/Kokkos_Atomic.hpp(71),
In file included from /blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/Kokkos_View.hpp(53),
                 from /blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/impl/Kokkos_HostThreadTeam.hpp(49),
                 from /blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/impl/Kokkos_HostThreadTeam.cpp(46):
                 from /blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/Kokkos_Parallel.hpp(52),
                 from /blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/Kokkos_Serial.hpp(55),
                 from /blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/Kokkos_Core.hpp(53),
                 from /blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/impl/Kokkos_ExecPolicy.cpp(44):
/blues/gpfs/home/acmetest/ACME/externals/kokkos/core/src/Kokkos_HostSpace.hpp(137): error: invalid type for defaulted constructor
    HostSpace( HostSpace && rhs ) = default;
...
```

**Comment by ambrad** [comment]
@jgfouca what is the output of `icpc -v` in the failing build? That compiler error might indicate a pre-4.8 g++ compatibility.

**Comment by jgfouca** [comment]
```
% (source .env_mach_specific.sh && icpc -v)
icpc version 17.0.0 (gcc version 4.4.7 compatibility)
```

I suspected that was the problem; I'm mostly curious how @oksanaguba get her case to build.

**Comment by ambrad** [comment]
Oksana updates her env to use a more recent gcc. I had thought anvil was supposed to move to an intel with >= 4.8 compat. Is this regression a result of the anvil issues recently?

**Comment by jgfouca** [comment]
@sarich

**Comment by oksanaguba** [comment]
@jgfouca I was out on Friday, but I agree with Andrew it is probably gcc. I have this .soft file:
```
+python-2.7
+git-2.5.0
+nco-4.6.7
+imagemagick
#+cmake-2.8.12
+cmake-3.5.2
+ncl-6.1.2
+softenv
+gcc-4.9.3
+lcrc-utils
+os_paths
+user_paths
+mvapich2-2.2-intel-17.0.0-acme
+intel-17.0.0
+netcdf-c-4.4.1-f77-4.4.4-intel-17.0.0-serial
+pnetcdf-1.7.0-intel-17.0.0-mvapich2-2.2-acme
+ncview
```
Also, I assume e3sm still does not clean software env as we talked about before https://github.com/E3SM-Project/E3SM/issues/2591 .

**Comment by oksanaguba** [comment]
Also, I am posting time error that I see in status file after it ran
```
2019-05-24 00:30:33 CASE.RUN HAS FINISHED
Exception during GENERATE:
ERROR: 'SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl.G.20190524_001841_r4u6xy' does not look like a CIME test name, expect TESTCASE.GRID.COMPSET[.MACHINE_COMPILER[.TESTMODS]]
Traceback (most recent call last):
  File "/blues/gpfs/home/onguba/acme-b2/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 346, in _phase_modifying_call
    function()
  File "/blues/gpfs/home/onguba/acme-b2/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 505, in _generate_baseline
    success, comments = generate_baseline(self._case)
  File "/blues/gpfs/home/onguba/acme-b2/cime/scripts/Tools/../../scripts/lib/CIME/hist_utils.py", line 590, in generate_baseline
    return _generate_baseline_impl(case, baseline_dir=baseline_dir, allow_baseline_overwrite=allow_baseline_overwrite)
  File "/blues/gpfs/home/onguba/acme-b2/cime/scripts/Tools/../../scripts/lib/CIME/hist_utils.py", line 575, in _generate_baseline_impl
    testopts = parse_test_name(testcase)[1]
  File "/blues/gpfs/home/onguba/acme-b2/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 625, in parse_test_name
    "'{}' does not look like a CIME test name, expect TESTCASE.GRID.COMPSET[.MACHINE_COMPILER[.TESTMODS]]".format(test_name))
  File "/blues/gpfs/home/onguba/acme-b2/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 139, in expect
    raise exc_type(msg)
CIMEError: ERROR: 'SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl.G.20190524_001841_r4u6xy' does not look like a CIME test name, expect TESTCASE.GRID.COMPSET[.MACHINE_COMPILER[.TESTMODS]]
```

**Comment by oksanaguba** [comment]
Also, here is result for iclc -v 
```
[onguba@b512 SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetasl.G.20190524_001841_r4u6xy]$ (source .env_mach_specific.sh && icpc -v)
icpc version 17.0.0 (gcc version 4.9.3 compatibility)
```

**Comment by jgfouca** [comment]
@oksanaguba , E3SM can clean the environment, but it's at the discretion of the machine configuration (adding a purge in config_machines.xml). Soft is particularly tricky since it lacks a purge command.

**Comment by ambrad** [comment]
I just spoke with @jgfouca. First, the testname issue is independent of this PR and won't actually affect the nightly. Second, the fact that there is a build issue for this test on anvil due to the softenv problem with cleanly getting a gcc >= 4.8 won't affect E3SM_Baselines.

Thus, we should merge this PR into next.

**Comment by oksanaguba** [comment]
great, please, merge then.

**Comment by ambrad** [comment]
pinging @jgfouca in case this slipped under the radar

**Comment by jgfouca** [comment]
Merging now.

**Comment by jgfouca** [comment]
Skipping integration testing.

**Pull request merged**
