### PR TITLE
Add UA and COARE ocean surface flux schemes

### PR DESCRIPTION
**Pull request by JackReevesEyre**
This branch adds two algorithms to calculate ocean surface fluxes (wind stress, latent and sensible heat fluxes) in CIME. The new algorithms are selected by a new CIME namelist variable: 

ocn_surface_flux_scheme = 0  [default] -- original scheme as used in E3SMv1;
                                           = 1               -- COARE v3.0 scheme (from Fairall et al. 2003);
                                           = 2               -- University of Arizona (UA) scheme (from Zeng et al., 1998).

The desired option should be added to user_nl_cpl.

[BFB]
[FCC]
[NML]

EW-108, EW-127

### CODE REVIEW

**Comment by kaizhangpnl** [comment]
@singhbalwinder Jack and I tested the branch independently for BFB. It is also reproducible from a restart. @JackReevesEyre What does the tag FCC mean?

**Comment by JackReevesEyre** [comment]
@kaizhangpnl FCC means "flag climate changing": using the COARE or UA scheme changes the climate of the model compared to the default scheme. The differences are greater than just round off. Is that correct usage of this label?

**Comment by rljacob** [comment]
Yes it is.

**Comment by kaizhangpnl** [comment]
Now I remember seeing this tag before. :) Thanks!

**Comment by singhbalwinder** [comment]
Merged to next

**Comment by kaizhangpnl** [comment]
Thank you, Balwinder!

**Comment by JackReevesEyre** [comment]
Thank you all!

**Pull request merged**
