### PR TITLE
Add E3SM-ARRM (Arctic refined) grid configurations

### PR DESCRIPTION
**Pull request by jonbob**
This PR adds the MPAS-O and MPAS-SI meshes and other configuration files necessary to run a G-case of two E3SM-ARRM (Arctic refined) configurations:

1. the first, lower resolution grid, is EC60to30 in the Southern hemisphere and then transitions from 30 to 10 km in the Northern hemisphere (10km resolution over the whole Arctic);
2. the second, higher resolution grid, is similar to the one in 1), but transitions to 6 km in the Arctic.

Testing has been done on the LANL machine grizzly and on edison. One test ran successfully for 10 years.

[BFB]

### CODE REVIEW

**Comment by milenaveneziani** [comment]
@jonbob: should I make another branch merging this one with the changes we made for the IC machines?

**Comment by jonbob** [comment]
@milenaveneziani - we'll have to make a separate branch that brings in the IC machine changes. I'll work on creating that one as well. Do you need that branch in order to test on IC?

**Comment by milenaveneziani** [comment]
> Do you need that branch in order to test on IC?

yes, that is what I was thinking. We could even do a more thorough testing on badger, since we are at it (Gennaro told me recently that his changes for badger did not work in a recent test, while they had worked before..).

**Comment by jonbob** [comment]
@milenaveneziani - OK, I'll make that branch today. It will just have the IC machine updates, and please feel free to commit any changes to it that you come up with to get badger working.

**Comment by jonbob** [comment]
@milenaveneziani - I made a branch, jonbob/scripts/update-IC-machines, with the machine file changes you had in PR #2589

**Comment by milenaveneziani** [comment]
ah, great. I'll use that one.

**Comment by jonbob** [comment]
you'll have to merge it with this one to get both the grid and machine updates

**Comment by milenaveneziani** [comment]
Could we merge this PR (without deleting the branch) and in the meantime hopefully the pearl modules are restored on IC?

**Comment by jonbob** [comment]
merged to next

**Comment by milenaveneziani** [comment]
Thanks @jonbob.

**Pull request merged**
