### PR TITLE
Adding sediment submodule to MOSART

### PR DESCRIPTION
**Pull request by liho745**
Added a new submodule to MOSART, MOSART-sediment, which simulates suspended sediment transport in the rivers. MOSART-sediment is coupled to ELM. MOSART-sediment can be turned on/off
with a sediflag option in user_nl_mosart.

### CODE REVIEW

**Comment by rljacob** [comment]
Please edit the title so its not just the branch name.  It should describe what the PR is doing.

**Comment by liho745** [comment]
Gautam, is it possible that these conflicts could be avoided by rebasing my branch differently as you did for MOSART-heat?

**Comment by kvcalvin** [comment]
@bishtgautam: What is this PR waiting on?

**Comment by bishtgautam** [comment]
@kvcalvin, This was waiting for #3074 and #3133 to be merged into master first. I will work on integrating this now.

@liho745 Is this PR BFB?

**Comment by kvcalvin** [comment]
Thanks!

**Comment by liho745** [comment]
> @kvcalvin, This was waiting for #3074 and #3133 to be merged into master first. I will work on integrating this now.
> 
> @liho745 Is this PR BFB?

@bishtgautam I think it needs to be rebased to next then be tested for BFB. @hydrotian, do you agree?

**Comment by bishtgautam** [comment]
@liho745, Okay. Please go ahead and rebase it.

**Comment by rljacob** [comment]
@liho745 never rebase to next.  Only to master.

**Comment by liho745** [comment]
@rljacob I meant next on the master. Sorry for the confusion.

**Comment by hydrotian** [comment]
Rebased off [11eca88](https://github.com/E3SM-Project/E3SM/commit/11eca88165825eee2b8d95f4dce55b9070dcf75e). E3SM_land_developer tests passed.

**Comment by jgfouca** [comment]
@hydrotian , something went wrong in Git. It shows me having made commits for this PR.

**Comment by hydrotian** [comment]
@jgfouca Is it because your commits were brought in after I rebased this branch to a recent master?

**Comment by jgfouca** [comment]
@hydrotian , I think you probably rebased a lot of stuff you didn't intend to. You should probably just start over and cherry pick the commits you want. It looks like there's only two

**Comment by hydrotian** [comment]
@jgfouca I guess I messed it up when I try to squash the commits. I will start over and fix this.

**Comment by rljacob** [comment]
Make a new branch off master and redo your changes.  Then make a new PR.

**Pull request closed without merging**
