### PR TITLE
For SCM cases, correct how we store the computed area to write in eam history file

### PR DESCRIPTION
**Pull request by ndkeen**
For SCM cases, we compute area and register it, but as it's a local copy, the value is not available at writing time to netcdf.
This results in the code writing a value for area that is uninitialized and different compilers can have different behavior, which could result in a DIFF between runs (and the incorrect area written to the file).

BFB for all cases, except SCM. And the results are still BFB for SCM, just affects the area written to file.

Fixes https://github.com/E3SM-Project/E3SM/issues/6556

### CODE REVIEW

**Review by rljacob — APPROVED** [review]

**Comment by ndkeen** [comment]
Note the first commit here is cleaning up white-space.
The next commits are the actual change.

I also think there is incorrect logic for when SCM is enabled. I changed
```
if (.not.single_column .or. scm_multcols) then

to

if (single_column .or. scm_multcols) then
```

**Comment by ndkeen** [comment]
I think I incorrectly did the logic for scm -- will fix.

**Review by bogensch — APPROVED** [review]
Thanks for working on this @ndkeen

**Comment by ndkeen** [comment]
merged to next

**Comment by ndkeen** [comment]
merged to master, submitted bless request

**Comment by rljacob** [comment]
@ndkeen did you bless on mappy?  Its still diffing.

**Comment by ndkeen** [comment]
No I did not.  I was actually not aware that this was an issue on any other machine. I can't even login to mappy. Glad it fixed more than one.

**Comment by rljacob** [comment]
Yes please do.

**Pull request merged**
