### PR TITLE
Update mpas-source: Added GPU macros to seaice core

### PR DESCRIPTION
**Pull request by akturner**
Adds GPU macros to MPAS-Seaice to allow some offloading onto GPU

[BFB] on CPU

### CODE REVIEW

**Comment by jonbob** [comment]
@amametjanov - if you're available today, could you please review this PR? Thanks

**Review by amametjanov — APPROVED** [review]
Looks good, thanks!

**Comment by jonbob** [comment]
Thanks @amametjanov

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
