### PR TITLE
Update ocean/seaice defaults for wc

### PR DESCRIPTION
**Pull request by vanroekel**
This PR makes the ocean and seaice configurations identical to water cycle v2 simulations out of the box.

[NML]
[non-BFB]

### CODE REVIEW

**Review by jonbob — APPROVED** [review]
Looks exactly like the settings in 20201217.beta1_01.piControlSI.compy

**Review by proteanplanet — APPROVED** [review]
This review is to approve only the sea ice changes, and I have requested @jonbob to review this with the added changes to MPAS-SI defaults.

**Comment by vanroekel** [comment]
@jonbob I've modified the PR to affect the EC30to60E2r2 only on the ocean side.  Please double check my changes

**Comment by proteanplanet** [comment]
@jonbob @vanroekel: I, too, can just make sure that EC30to60E2r2  is affected here, if you would like?

**Review by jonbob — APPROVED** [review]
Looks perfect. I'll get it merged right away. Thanks to you both

**Comment by jonbob** [comment]
merged to master and expected DIFFs blessed

**Pull request merged**
