### PR TITLE
Keziming/atm/chem uci mosaic mam5

### PR DESCRIPTION
**Pull request by keziming**
This branch adds stratospheric sulfate aerosol feature into UCI-MOSAIC branch (mingxuanwupnnl/atm/chemUCI-chemMZT_AMIP). 
1, I am not sure if pull request is a right thing to do, because we are not merging into master.
2, The code can reproduce BTB UCI-MAM4 simulation, and I do not test if it can reproduce the BTB MOSAIC simulation.
3, There are some automatic changes at the submodule level, which are not belong to EAM. This occured when I push to github. Please check that.

### CODE REVIEW

**Comment by mingxuanwupnnl** [comment]
@keziming I think you are actually merging to master. You may want to cancel/change it and merge it to my branch?
@tangq @hwangacme Could you confirm this? Thank you.

**Comment by tangq** [comment]
@keziming , this PR includes so many commits from other branches, e.g., chemistry and nitrate aerosols. We should be able to submit a PR only for your MAM5 changes, but I am not sure how to do it either.

@rljacob , many NGD aerosol and chemistry developments are on branches based on other branches. We need instructions on how to create the clean PR only for the child branch, not including commits from parent branches. Thanks.

**Comment by tangq** [comment]
I think the plan is to merge to Mingxuan's branch and master simultaneously. It takes longer for merging to master, so we may modify the PR to master if we found changes were needed on the branch.

**Comment by keziming** [comment]
@mingxuanwupnnl @hwangacme @tangq I have change the base to Mingxuan's branch. Thank you for the reminder. I am learning to use github.

**Comment by rljacob** [comment]
First, don't use the main github to merge a branch to another branch.  Do that on a fork.  This is just for merges to master or the maintenance branches.

If the parent branch is going to be merged first, then once it is it will be easier to make new PRs (to master) with the child branches using git rebase.

If the parent branch is not being merged, make a new branch off of master and use git cherry-pick to move the commits from the existing branch to the new one.

**Pull request closed without merging**
