### PR TITLE
Revert "Update tests.py to separate HOMME and HOMMEBFB into a new suite"

### PR DESCRIPTION
**Pull request by wadeburgess**
Reverts E3SM-Project/E3SM#3397

### CODE REVIEW

**Comment by rljacob** [comment]
Why are you reverting it?

**Comment by wadeburgess** [comment]
I didn't merge to next first

**Comment by rljacob** [comment]
You can do it after.  No need to revert the master merge.

**Comment by wadeburgess** [comment]
Okay, so deny or delete this MR?

**Comment by rljacob** [comment]
close it.

**Pull request closed without merging**
