### PR TITLE
update mpas-source: fix incorrect path for ocean cvmix

### PR DESCRIPTION
**Pull request by mark-petersen**
When changing to submodules for the ocean cvmix package, the path to cvmix source had changed, but one instance of this path was not changed, leading to build failures with PGI on Summit. This PR fixes that bad path. See https://github.com/MPAS-Dev/MPAS-Model/pull/494

[bfb]

### CODE REVIEW

**Comment by mark-petersen** [comment]
This is after #3391. All those Redi changes appear here, but will go away after #3391 is merged.

**Comment by jonbob** [comment]
@mark-petersen - I'd prefer to have the COMPASS changes in a separate PR if possible

**Comment by mark-petersen** [comment]
Done. The merge order needs to be: #3391, #3561, then this one #3560.

**Comment by jonbob** [comment]
Perfect -- thanks

**Comment by mark-petersen** [comment]
@jonbob this one-line change to fix a makefile is rebased after the Redi merge, and is the next PR in line.

**Comment by jonbob** [comment]
merged to next

**Comment by mark-petersen** [comment]
@jonbob how did this test go?

**Comment by jonbob** [comment]
There is one unexplained DIFF in a C-case that's keeping it from going to master. I hope it clears itself overnight, because the DIFF makes no sense. Otherwise, next is closed as well until testing is resolved

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
