### PR TITLE
Update mpas-source: cvmix and BGC submodules

### PR DESCRIPTION
**Pull request by mark-petersen**
This is a significant change to the structure of the MPAS repository.
Instead of external code dependencies being downloaded by home-grown
scripts, we instead express the dependency as a git submodule. This will
impact the cvmix and BGC dependencies for core_ocean.

For additional discussion, see #3377 and https://github.com/MPAS-Dev/MPAS-Model/pull/420

[bfb]

### CODE REVIEW

**Comment by mark-petersen** [comment]
@jgfouca this only has the MPAS updates. Please add whatever is needed within the E3SM repo.

**Comment by mark-petersen** [comment]
@jonbob, this can go in after the sea ice change. This pointing to the `e3sm/testing` branch, but that is easy to point back at the last minute.

**Comment by jgfouca** [comment]
I don't think any changes are needed in E3SM.

**Comment by rljacob** [comment]
If a submodule has its own submodules, does "git submodule update --init" at the top level retrieve all of them?   I think this is our first example of that in E3SM.

**Comment by jgfouca** [comment]
@rljacob , all submodule commands will need `--recursive`

**Comment by mark-petersen** [comment]
@jonbob and @jgfouca if you could each test this PR on a different machine, that would ensure everything is working. 

@jgfouca are there any e3sm scripts that need `--recursive` added to a `git submodule update` command, or is that always done before launching e3sm scripts?

**Comment by mark-petersen** [comment]
@jonbob I updated `e3sm/develop` on the mpas repo, so this PR can be merged after testing. I was able to obtain the cvmix and BGC submodules on cori with 
`git submodule update --recursive --init`
so everything appears to work.

**Comment by jonbob** [comment]
Passed SMS.ne4_oQU240.A_WCYCL1850.anvil_intel

**Comment by jonbob** [comment]
merged to next

**Comment by jgfouca** [comment]
> @jgfouca are there any e3sm scripts that need --recursive added to a git submodule update command, or is that always done before launching e3sm scripts?

Jenkins should already be doing that. It's possible there are cron jobs that need updating. I updated the ones in our test script repo.

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
