### PR TITLE
Homme: Rework HOMME_ENABLE_COMPOSE symbol machinery for use in EAMxx.

### PR DESCRIPTION
**Pull request by ambrad**
Modify how HOMME_ENABLE_COMPOSE is defined in HOMME's cmake system, affecting standalone HOMME and EAMxx. This enables running SL transport in EAMxx v1.

[BFB]

### CODE REVIEW

**Comment by ambrad** [comment]
Passes homme_integration on Chrysalis.

**Review by bartgol — APPROVED** [review]
Looks good. Thanks!

**Comment by ambrad** [comment]
homme_integration passes on Chrysalis, but I need to rerun e3sm_developer and test Homme on the GPU.

**Review by bartgol — APPROVED** [review]

**Comment by ambrad** [comment]
Passes compose_ut and *GB-sl*cxx_vs_f90 tests on weaver GPU.

**Comment by ambrad** [comment]
Merged to next.

**Pull request merged**
