### PR TITLE
Add compy and fix some bugs for maint-1.0

### LINKED ISSUE #3020: SCM broke on maint-1.0
running the SMS_R_Ld5.T42_T42.FSCM5A97 test on maint-1.0 provides the following error:

RUNNING TESTS:
  SMS_R_Ld5.T42_T42.FSCM5A97.cori-knl_intel
Starting CREATE_NEWCASE for test SMS_R_Ld5.T42_T42.FSCM5A97.cori-knl_intel with 1 procs
Finished CREATE_NEWCASE for test SMS_R_Ld5.T42_T42.FSCM5A97.cori-knl_intel in 0.123484 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /global/cscratch1/sd/bogensch/acme_scratch/cori-knl/SMS_R_Ld5.T42_T42.FSCM5A97.cori-knl_intel.SCM_devXX
    Errors were:
        **ERROR: Multiple matches**

I've traced it back that this error first appears with the following commit:

commit 524f049d4a64636d2bb712d39c8c3b9cf56a122c
Merge: bf8255ce3 ce8ed40a8
Author: Wuyin Lin <wlin@bnl.gov>
Date:   Wed Jun 12 14:10:19 2019 -0700

    Merge tangq/cam/F2010-HR-compset into maint-1.0 (PR #2758)
    
    This PR created the F2010 HR compset with CMIP6 forcings. The compset name is F2010C5-CMIP6-HR.
    
     - It uses daily 0.25 degree sst_seaice data.
     - atm and lnd initial conditions from an ne120 nudging simulation
     - Classical Nucleation Theory (CNT) for ice deposition growth is turned off
     - Include atm and lnd use_case files specifically for this compset

### LINKED ISSUE #3027: Conditional redefine of MPIFC is broken in maint-1.0
If you try to redefine the mpi compiler wrappers with something like:
`<MPIFC MPILIB="impi"> mpiifort </MPIFC>`
You'll get a compile line that starts like this:
`mpif90  mpiifort <options>  file.F90`

This problem doesn't happen on master.

The config_compilers.xml in maint-1.0 doesn't use that construction in any definitions so we didn't notice it until we tried (on compy).

### PR DESCRIPTION
**Pull request by rljacob**
Add compy to the maint-1.0 machine files.

Allow compiling with PGI or Intel using special wrapper scripts for IntelMPI.
Add pelayouts from master.
Use the settings that were on master as of 88f572f69 except:
Change ne4 pelayouts to be 80 tasks.

Also fix a couple of general maint-1.0 bugs:
Fix a badly defined compset in EAM.
Fix a bug in cime preventing the use of conditionally defined MPI wrappers.

Fixes #3020 
Fixes #3027

### CODE REVIEW

**Comment by rljacob** [comment]
This isn't read yet.  Still need to:
get Intel working.
Build pgi with IntelMPI using the new MPI scripts.

Pgi works for now with IntelMPI by adding -DNO_MPIMOD

**Comment by rljacob** [comment]
This is now in better shape.
@jonbob while trying to build a fully coupled case, I got some netcdf define errors from MPAS.
```
mpas_io.f90(33): error #6592: This symbol must be a defined parameter, an enumerator, or an argument of an inquiry function that evaluates to a compile-time constant.   [NF_FILL_INT]
   integer, parameter :: MPAS_INT_FILLVAL = NF_FILL_INT
--------------------------------------------^
```

Does this mean some part of the netcdf build (a .mod?) is missing?   It builds fine on master and I'm using the same settings in config_machines/compilers.

**Comment by singhbalwinder** [comment]
@rljacob : I think issue #903 addresses that by using pnetcdf. Seems like we do have pnetcdf defined in the machine files. @jayeshkrishna might know what might be missing here.

**Comment by rljacob** [comment]
#903 ?  That's about Mosart and an undefined fortran variable.

**Comment by singhbalwinder** [comment]
sorry, #910

**Comment by rljacob** [comment]
Looks like that worked!

**Comment by rljacob** [comment]
@singhbalwinder this is ready for review.

**Pull request merged**
