### PR TITLE
add support for ne30pg2, WCAtl12to45E2r4 configuration

### PR DESCRIPTION
**Pull request by stephenprice**
Adds grid, domain, mapping file, data forcing (JRA, CORE), ocean restoring file, and ocean/ice namelist default support for new ne30pg2 (atmos) and WCAtl12to45E2r4 (ocean/ice) configuration.

[BFB]

### CODE REVIEW

**Comment by darincomeau** [comment]
Link to the mesh generation PR: https://github.com/MPAS-Dev/compass/pull/60
image

**Comment by vanroekel** [comment]
@jonbob I wasn't sure how to request this since it wasn't changed, but can we change the following
```
<config_eddying_resolution_ramp_min>20e3</config_eddying_resolution_ramp_min>
<config_eddying_resolution_ramp_max>30e3</config_eddying_resolution_ramp_max>
```
To be `30e3` and `40e3` respectively, just for this new grid?

Otherwise everything else looked good, but I would like to try this branch to launch a case with this mesh prior to approving

**Review by vanroekel — APPROVED** [review]
Approved by visual inspection and testing of case setup / build on chrysalis.  Thanks @darincomeau, @stephenprice and @jonbob!

**Comment by darincomeau** [comment]
Approved based on successful 5 day smoke tests of the following compsets.resolutions on Anvil/Chrysalis:

`WCYCL1850.ne30pg2_WCAtl12to45E2r4`
`GMPAS-IAF.T62_WCAtl12to45E2r4`
`GMPAS-JRA1p4.TL319_WCAtl12to45E2r4`

**Review by darincomeau — APPROVED** [review]

**Review by jonbob — APPROVED** [review]
looks good from a visual inspection

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
