### PR TITLE
Remove mpas testing directory, move sea ice testing directory

### PR DESCRIPTION
**Pull request by mark-petersen**
This PR rearranges the directories previously used for MPAS testing:
- Move components/mpas-framework/testing_and_setup/seaice from mpas-framework to mpas-seaice
- Remove remaining components/mpas-framework/testing_and_setup, including compass

It does not alter any executable code for E3SM or MPAS. Compass testing for MPAS is now housed in its own repository, https://github.com/MPAS-Dev/compass

[BFB]

### CODE REVIEW

**Review by xylar — APPROVED** [review]
These changes are what we want.  The `testing_and_setup` directory is gone from `mpas-framework`.

**Review by matthewhoffman — APPROVED** [review]
Thanks, Mark.

**Review by akturner — APPROVED** [review]

**Review by jonbob — APPROVED** [review]
passed e3sm_developer testing

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
