### PR TITLE
EAMxx: Change default value of lambda_high in SHOC to 0.08

### PR DESCRIPTION
**Pull request by bogensch**
This "new" value of 0.08 for lambda_high for SHOC has been used in all recent SCREAM production runs (CESS experiments; decadal) but for some reason was never made default in master.  Correcting that here.  Modified from 0.04 to 0.08 because this improves the representation of marine stratocumulus.

DIFFs are expected.

### CODE REVIEW

**Comment by ndkeen** [comment]
I can approve, but only based on the fact that this is the setting we've been using for all SCREAM production cases.
Any suggestions of how best to test this?  I could run all the current scream nightly tests, but we expect them to be ok, just not BFB.

**Comment by rljacob** [comment]
Will need to be tested overnight on next before merging to master.

**Comment by AaronDonahue** [comment]
Since this PR touches `eam` code it will need to go through the regular E3SM integration process.

**Comment by ndkeen** [comment]
I ran all of the scream tests I found in our testing python script on both pm-cpu and pm-gpu.  All GNU tests pass as expected.  With Intel on pm-cpu, there are some fails, but they are known (with issues created).

```
ERP_D_Lh4.ne4_ne4.F2010-SCREAMv1.pm-cpu_gnu.scream-output-preset-1.e3sm_scream_v1                                                         pass                   nodes=   1 mins=  1.6 state= COMPLETED cancel=0 notes=
ERP_Ln22.conusx4v1pg2_r05_oECv3.F2010-SCREAMv1-noAero.pm-cpu_gnu.scream-bfbhash--scream-output-preset-6.e3sm_scream_v1                    pass                   nodes=   2 mins=  5.0 state= COMPLETED cancel=0 notes=
ERP_Ln22.conusx4v1pg2_r05_oECv3.F2010-SCREAMv1-noAero.pm-cpu_gnu.scream-bfbhash--scream-output-preset-6.e3sm_scream_v1_medres             pass                   nodes=   2 mins=  6.5 state= COMPLETED cancel=0 notes=
ERP_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-cpu_gnu.scream-output-preset-4.e3sm_scream_v1                                                    pass                   nodes=   1 mins=  1.3 state= COMPLETED cancel=0 notes=
ERS_D_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-cpu_gnu.scream-rad_frequency_2--scream-output-preset-5.e3sm_scream_v1                          pass                   nodes=   1 mins=  2.7 state= COMPLETED cancel=0 notes=
ERS_D_Ln22.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.pm-cpu_gnu.atmlndactive-rtm_off--scream-output-preset-1.e3sm_scream_v1                     pass                   nodes=   1 mins=  3.1 state= COMPLETED cancel=0 notes=
ERS_Ln22.ne30_ne30.F2010-SCREAMv1.pm-cpu_gnu.scream-internal_diagnostics_level--scream-output-preset-3.e3sm_scream_v1                     pass                   nodes=   2 mins=  5.3 state= COMPLETED cancel=0 notes=
ERS_Ln22.ne30_ne30.F2010-SCREAMv1.pm-cpu_gnu.scream-internal_diagnostics_level--scream-output-preset-3.e3sm_scream_v1_medres              pass                   nodes=   2 mins=  4.4 state= COMPLETED cancel=0 notes=
ERS_Ln22.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-cpu_gnu.scream-L128--scream-output-preset-4.e3sm_scream_v1                                     pass                   nodes=   2 mins=  5.0 state= COMPLETED cancel=0 notes=
ERS_Ln22.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-cpu_gnu.scream-L128--scream-output-preset-4.e3sm_scream_v1_medres                              pass                   nodes=   2 mins=  4.1 state= COMPLETED cancel=0 notes=
ERS_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-cpu_gnu.scream-small_kernels--scream-output-preset-5.e3sm_scream_v1                              pass                   nodes=   1 mins=  1.9 state= COMPLETED cancel=0 notes=
ERS_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-cpu_gnu.scream-small_kernels_p3--scream-output-preset-5.e3sm_scream_v1                           pass                   nodes=   1 mins=  1.6 state= COMPLETED cancel=0 notes=
ERS_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-cpu_gnu.scream-small_kernels_shoc--scream-output-preset-5.e3sm_scream_v1                         pass                   nodes=   1 mins=  2.4 state= COMPLETED cancel=0 notes=
ERS_Ln9.ne4_ne4.F2000-SCREAMv1-AQP1.pm-cpu_gnu.scream-output-preset-2.e3sm_scream_v1                                                      pass                   nodes=   1 mins=  1.3 state= COMPLETED cancel=0 notes=
ERS_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-cpu_gnu.scream-small_kernels--scream-output-preset-5.e3sm_scream_v1                            pass                   nodes=   2 mins=  7.7 state= COMPLETED cancel=0 notes=
ERS_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-cpu_gnu.scream-small_kernels--scream-output-preset-5.e3sm_scream_v1_medres                     pass                   nodes=   2 mins=  7.3 state= COMPLETED cancel=0 notes=
PEM_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-cpu_gnu.scream-spa_remap--scream-output-preset-4.e3sm_scream_v1                                pass                   nodes=   2 mins=  7.0 state= COMPLETED cancel=0 notes=
PEM_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-cpu_gnu.scream-spa_remap--scream-output-preset-4.e3sm_scream_v1_medres                         pass                   nodes=   2 mins=  9.4 state= COMPLETED cancel=0 notes=
REP_Ld5.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-cpu_gnu.scream-L128--scream-output-preset-6.e3sm_scream_v1                                      pass                   nodes=   2 mins= 18.6 state= COMPLETED cancel=0 notes=
REP_Ld5.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-cpu_gnu.scream-L128--scream-output-preset-6.e3sm_scream_v1_medres                               pass                   nodes=   2 mins= 21.3 state= COMPLETED cancel=0 notes=
SMS_D_Ln5.ne30pg2_oECv3.F2010-SCREAMv1-MPASSI.pm-cpu_gnu.scream-mam4xx-remap_emiss_ne4_ne30.e3sm_scream_v1                                pass                   nodes=   2 mins=  3.8 state= COMPLETED cancel=0 notes=
SMS_D_Ln5.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.pm-cpu_gnu.scream-mam4xx-aci.e3sm_scream_v1                                                 pass                   nodes=   1 mins=  0.9 state= COMPLETED cancel=0 notes=
SMS_D_Ln5.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.pm-cpu_gnu.scream-mam4xx-all_mam4xx_procs.e3sm_scream_v1                                    pass                   nodes=   1 mins=  0.7 state= COMPLETED cancel=0 notes=
SMS_D_Ln5.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.pm-cpu_gnu.scream-mam4xx-drydep.e3sm_scream_v1                                              pass                   nodes=   1 mins=  1.3 state= COMPLETED cancel=0 notes=
SMS_D_Ln5.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.pm-cpu_gnu.scream-mam4xx-optics.e3sm_scream_v1                                              pass                   nodes=   1 mins=  0.9 state= COMPLETED cancel=0 notes=
SMS_D_Ln5.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.pm-cpu_gnu.scream-mam4xx-wetscav.e3sm_scream_v1                                             pass                   nodes=   1 mins=  0.9 state= COMPLETED cancel=0 notes=
SMS_D_Ln9.ne4_ne4.F2010-SCREAMv1-noAero.pm-cpu_gnu.scream-output-preset-3.e3sm_scream_v1                                                  pass                   nodes=   1 mins=  1.6 state= COMPLETED cancel=0 notes=
SMS_Ln300.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-cpu_gnu.scream-perf_test--scream-output-preset-1.e3sm_scream_v1_hires                         pass                   nodes=   2 mins=  7.8 state= COMPLETED cancel=0 notes=


These are the failing Intel compiler cases:
ERP_Ln22.conusx4v1pg2_r05_oECv3.F2010-SCREAMv1-noAero.pm-cpu_intel.scream-bfbhash--scream-output-preset-6.e3sm_scream_v1_medres           fail COMPARE_base_rest nodes=   2 mins=  4.3 state= COMPLETED cancel=0 notes=
ERP_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-cpu_intel.scream-output-preset-4.e3sm_scream_v1_lowres                                           fail COMPARE_base_rest nodes=   1 mins=  3.0 state= COMPLETED cancel=0 notes=
ERS_Ln9.ne4_ne4.F2000-SCREAMv1-AQP1.pm-cpu_intel.scream-output-preset-2.e3sm_scream_v1_lowres                                             fail COMPARE_base_rest nodes=   1 mins=  3.1 state= COMPLETED cancel=0 notes=
PEM_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-cpu_intel.scream-spa_remap--scream-output-preset-4.e3sm_scream_v1_medres                       fail COMPARE_base_modp nodes=   2 mins=  9.0 state= COMPLETED cancel=0 notes=

on pm-gpu, there are still 2 pending jobs:
ERP_D_Lh182.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-gpu_gnugpu.e3sm_scream_v1_long                                                                pend           pending nodes=   0 mins=  0.0 state=           cancel=0 notes=
ERP_D_Lh4.ne4_ne4.F2010-SCREAMv1.pm-gpu_gnugpu.scream-output-preset-1.e3sm_scream_v1                                                      pass                   nodes=   1 mins=  1.9 state= COMPLETED cancel=0 notes=
ERP_Ln22.conusx4v1pg2_r05_oECv3.F2010-SCREAMv1-noAero.pm-gpu_gnugpu.scream-bfbhash--scream-output-preset-6.e3sm_scream_v1                 pass                   nodes=   8 mins=  8.2 state= COMPLETED cancel=0 notes=
ERP_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-output-preset-4.e3sm_scream_v1                                                 pass                   nodes=   1 mins=  2.5 state= COMPLETED cancel=0 notes=
ERS_D_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-rad_frequency_2--scream-output-preset-5.e3sm_scream_v1                       pass                   nodes=   1 mins=  2.8 state= COMPLETED cancel=0 notes=
ERS_D_Ln22.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.pm-gpu_gnugpu.atmlndactive-rtm_off--scream-output-preset-1.e3sm_scream_v1                  pass                   nodes=   1 mins=  2.8 state= COMPLETED cancel=0 notes=
ERS_Ln22.ne30_ne30.F2010-SCREAMv1.pm-gpu_gnugpu.scream-internal_diagnostics_level--scream-output-preset-3.e3sm_scream_v1                  pass                   nodes=   2 mins=  9.1 state= COMPLETED cancel=0 notes=
ERS_Ln22.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-L128--scream-output-preset-4.e3sm_scream_v1                                  pass                   nodes=   2 mins=  3.1 state= COMPLETED cancel=0 notes=
ERS_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-small_kernels--scream-output-preset-5.e3sm_scream_v1                           pass                   nodes=   1 mins=  1.4 state= COMPLETED cancel=0 notes=
ERS_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-small_kernels_p3--scream-output-preset-5.e3sm_scream_v1                        pass                   nodes=   1 mins=  1.9 state= COMPLETED cancel=0 notes=
ERS_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-small_kernels_shoc--scream-output-preset-5.e3sm_scream_v1                      pass                   nodes=   1 mins=  3.0 state= COMPLETED cancel=0 notes=
ERS_Ln362.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.e3sm_scream_v1_long                                                                pass                   nodes=   2 mins=  7.0 state= COMPLETED cancel=0 notes=
ERS_Ln9.ne4_ne4.F2000-SCREAMv1-AQP1.pm-gpu_gnugpu.scream-output-preset-2.e3sm_scream_v1                                                   pass                   nodes=   1 mins=  1.3 state= COMPLETED cancel=0 notes=
ERS_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-small_kernels--scream-output-preset-5.e3sm_scream_v1                         pass                   nodes=   2 mins=  4.0 state= COMPLETED cancel=0 notes=
PEM_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-spa_remap--scream-output-preset-4.e3sm_scream_v1                             pass                   nodes=   2 mins=  2.9 state= COMPLETED cancel=0 notes=
REP_Ld5.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-L128--scream-output-preset-6.e3sm_scream_v1                                   pass                   nodes=   2 mins=  7.3 state= COMPLETED cancel=0 notes=
SMS_D_Ln5.ne30pg2_oECv3.F2010-SCREAMv1-MPASSI.pm-gpu_gnugpu.scream-mam4xx-remap_emiss_ne4_ne30.e3sm_scream_v1                             pass                   nodes=   2 mins=  2.7 state= COMPLETED cancel=0 notes=
SMS_D_Ln5.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.pm-gpu_gnugpu.scream-mam4xx-aci.e3sm_scream_v1                                              pend           pending nodes=   0 mins=  0.0 state=           cancel=0 notes=
SMS_D_Ln5.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.pm-gpu_gnugpu.scream-mam4xx-all_mam4xx_procs.e3sm_scream_v1                                 pass                   nodes=   1 mins=  1.0 state= COMPLETED cancel=0 notes=
SMS_D_Ln5.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.pm-gpu_gnugpu.scream-mam4xx-drydep.e3sm_scream_v1                                           pass                   nodes=   1 mins=  0.8 state= COMPLETED cancel=0 notes=
SMS_D_Ln5.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.pm-gpu_gnugpu.scream-mam4xx-optics.e3sm_scream_v1                                           pass                   nodes=   1 mins=  1.4 state= COMPLETED cancel=0 notes=
SMS_D_Ln5.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.pm-gpu_gnugpu.scream-mam4xx-wetscav.e3sm_scream_v1                                          pass                   nodes=   1 mins=  1.5 state= COMPLETED cancel=0 notes=
SMS_D_Ln9.ne4_ne4.F2010-SCREAMv1-noAero.pm-gpu_gnugpu.scream-output-preset-3.e3sm_scream_v1                                               pass                   nodes=   1 mins=  0.8 state= COMPLETED cancel=0 notes=
SMS_Ln300.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-perf_test--scream-output-preset-1.e3sm_scream_v1_hires                      pass                   nodes=   2 mins=  2.4 state= COMPLETED cancel=0 notes=

```

**Comment by ndkeen** [comment]
What other testing is good for this change?

**Review by ndkeen — APPROVED** [review]

**Comment by AaronDonahue** [comment]
@rljacob do you want to assign an integrator for this PR?

**Review by bartgol — APPROVED** [review]

**Comment by bartgol** [comment]
@bogensch Does it make sense that the DP scream test PASSed while the other ones DIFFed?

**Comment by bogensch** [comment]
@bartgol it actually does, because the case being tested is ARM97 which is a convective/unstable case.  This means that values of lambda (stability parameter) will always be on the low end (close to lambda_low).  Values only approach the lambda_high values for more stratiform regimes.  Just did a sanity test for a DPxx case where I would expect this parameter modification to have an impact (DYCOMS-RF01) and the solution there is different, as expected.

**Comment by tcclevenger** [comment]
I see an email from yesterday saying NEXT is open, is that still the case? What is the best way to find the status of NEXT?

**Comment by rljacob** [comment]
Best way is to ask in the #infrastructure-devops channel on Slack.  Its open today.

**Comment by tcclevenger** [comment]
Merged to next

**Pull request merged**
