### PR TITLE
Set PIO_ROOT=1 for ne30-coupled cases on sandiatoss3

### PR DESCRIPTION
**Pull request by amametjanov**
Set PIO_ROOT=1 for ne30-coupled cases on sandiatoss3 to avoid MEMLEAK test issues.

Fixes E3SM-Project/E3SM#3934

[NML] - due to pio_root changes

### CODE REVIEW

**Comment by amametjanov** [comment]
@jgfouca do you recall why this was set?
```
  <entry id="PIO_BUFFER_SIZE_LIMIT">
    <values>
      <value MACH="sandiatoss3">1</value>
      <value MACH="ghost">1</value>
    </values>
  </entry>
```
Can you check if removing just this will fix the memleak issue (which happens only on sandiatoss3)?

**Comment by jgfouca** [comment]
Nice job, @amametjanov . I apologize, I have no idea why that buffer size was set. Since ghost was included, it was likely some other Sandia person. @oksanaguba ?

@rljacob , can i go ahead and integrate this since it's specific to sandiatoss3 only?

**Comment by oksanaguba** [comment]
@jgfouca I have no idea about this buffer size.

**Comment by rljacob** [comment]
Yes go ahead.

**Comment by amametjanov** [comment]
If nobody knows about `PIO_BUFFER_SIZE_LIMIT=1`, might as well remove it for consistency. All other machines default it to `-1`.

**Comment by jgfouca** [comment]
Merged to next.

**Comment by jayeshkrishna** [comment]
I second what @amametjanov mentioned above, PIO_BUFFER_SIZE_LIMIT is typically set to -1 to indicate that CIME/Scorpio can decide the appropriate value for the buffer size limit (this should be the default case). Its possible that its a bug to set it to 1 (the intention might have been to set it to -1), I cannot think of a reason why the limit needs to be set to such a low value.

**Comment by rljacob** [comment]
ERP_Ld3.ne30_oECv3_ICG.A_WCYCL1850S.sandiatoss3_intel is now passing!

**Comment by rljacob** [comment]
@jgfouca did you update the PIO_BUFFER_SIZE_LIMIT as mentioned above?

**Comment by jgfouca** [comment]
@rljacob , no. Do you want me to open a new PR?

**Comment by amametjanov** [comment]
@jgfouca , E3SM-Project/E3SM#3955 should do it.

**Comment by jgfouca** [comment]
Thanks, @amametjanov !

**Pull request merged**
