### PR TITLE
Update mpas-source: Add ALE options, default off.

### PR DESCRIPTION
**Pull request by mark-petersen**
Some small updates for MPAS-Ocean:
- Add flag for two different types of ALE thickness weighting
- Fix optional weighting in ALE SSH thickness distribution
- Change internal RK4 weight name for clarity
- COMPASS changes

[NML]
[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
```
PASS PEM_Ln9.ne30_oECv3_ICG.A_WCYCL1850S.cori-knl_intel COMPARE_base_modpes
PASS PET_Ln9.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel COMPARE_base_single_thread
```

**Comment by mark-petersen** [comment]
@jonbob, this one is next. I just rebased and tested.

**Comment by jonbob** [comment]
@mark-petersen - this one was made after the PR deadline. It also brings in changes from the Langmuir PR and needs to be remade.

**Comment by jonbob** [comment]
@mark-petersen - I double-checked and apparently the Langmuir namelist variables had gotten in earlier. I just hadn't seen them come through the scripts that auto-generate the E3SM build scripts. Rob had said it was OK to integrate this, just to keep things moving.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master and NML DIFFs blessed

**Pull request merged**
