### PR TITLE
MPAS-Ocean: GM fixes

### LINKED ISSUE #3719: PEM tests with ISMF fail
After #3695 was merged, PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_intel.JMasterExtra_coverage was observed to FAIL. I did some extra testing, and it appears that the problem is with ISMF. Here is the status of testing:

* PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_intel  FAIL
* PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-IAF.compy_intel  PASS
* PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF.compy_intel  PASS
* PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.compy_intel  FAIL

So the issue appears to have something to do with ISMF

### PR DESCRIPTION
**Pull request by mark-petersen**
See https://github.com/MPAS-Dev/MPAS-Model/pull/643

Integrals for computing GM kappa and the phase speed have been reworked to mitigate failures in ISMF simulations without redi. With this PR all configurations of GM work and the old 3DGM (N2_dependent) is recoverable to its original configuration.

This PR will be non BFB in WC and Cryo configs.

fixes #3719

[non-BFB]
[NML]

### CODE REVIEW

**Comment by jonbob** [comment]
@mark-petersen - this one requires fixes to the E3SM side as well, I think?

**Comment by mark-petersen** [comment]
There was one gm flag removed. I did that in the second commit. It didn't seem worth rerunning the namelist scripts for a simple removal.

**Comment by mark-petersen** [comment]
@vanroekel should any namelist default values for GM or Redi change with this PR?

**Comment by mark-petersen** [comment]
@jonbob I'm running a bunch of standard tests. Could you rerun the specific test that you saw fail in #3719?

**Comment by jonbob** [comment]
@mark-petersen - removing that one namelist variable looks very clean, thanks. And I will test merge and rerun the failing test

**Comment by vanroekel** [comment]
@mark-petersen the namelist options should stay the same.  No need to change default values.

**Comment by jonbob** [comment]
Passes:
PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.compy_intel (original failing test)
PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.anvil_intel, with redi on and off

**Comment by jonbob** [comment]
merged to next

**Comment by mark-petersen** [comment]
Passes 
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PET_D_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_gnu
PEM_Ld5_P512.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_intel
```

**Comment by mark-petersen** [comment]
Fails compare for 
```
PET_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-knl_intel
```
but so does the current master.

**Comment by jonbob** [comment]
merged to master

**Comment by jonbob** [comment]
blesses requested for expected DIFFs on all machines except compy, which has not yet reported

**Comment by jonbob** [comment]
some expected DIFFs blessed for compy, but there may be more due to interrupted testing

**Comment by jonbob** [comment]
blessed another set of DIFFs on compy now that the testing ran through completely

**Pull request merged**
