### PR TITLE
Update chicoma-gpu machine files

### LINKED ISSUE #6778: GPU test case fails on Chicoma
Trying to run an existing G case with GPUs (works successfully with CPUs) on Chicoma. Starting with a test case first. Using a branch that updated cpu modules after Sep/Oct maintenance, as discussed [here]( https://github.com/E3SM-Ocean-Discussion/E3SM/pull/112). Think I'm running into module issues, details below. 
```
export E3SM_REPO=/usr/projects/climate/dschlichting/repos/E3SM/updated_ch_modules
cd $E3SM_REPO/cime/scripts
```
Base environment fails:  
```
./create_test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu -p t24_coastal_ocean_g --walltime 00:30:00

create_test will do up to 1 tasks simultaneously
create_test will use up to 160 cores simultaneously
Creating test directory /lustre/scratch5/dschlichting/E3SM/scratch/chicoma-gpu/SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu.20241125_133726_x4whor
RUNNING TESTS:
  SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu
Starting CREATE_NEWCASE for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu with 1 procs
Finished CREATE_NEWCASE for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu in 2.442867 seconds (PASS)
Starting XML for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu with 1 procs
Finished XML for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu in 0.715194 seconds (PASS)
Starting SETUP for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu with 1 procs
Finished SETUP for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu in 60.843878 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /lustre/scratch5/dschlichting/E3SM/scratch/chicoma-gpu/SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu.20241125_133726_x4whor
    Errors were:
        ERROR: module command /usr/share/lmod/lmod/libexec/lmod python load PrgEnv-gnu/8.4.0 gcc/11.2.0 craype-accel-host cray-libsci/23.05.1.4 craype/2.7.21 cray-mpich/8.1.26 libfabric/1.15.2.0 cray-hdf5-parallel/1.12.2.3 cray-netcdf-hdf5parallel/4.9.0.3 cray-parallel-netcdf/1.12.3.3 cmake/3.25.1 failed with message:
        Lmod is automatically replacing "cce/17.0.0" with "gcc/12.2.0".
        
        Lmod has detected the following error: These module(s) or extension(s) exist but cannot be loaded as requested: "cmake/3.25.1"
           Try: "module spider cmake/3.25.1" to see how to load the module(s).

Waiting for tests to finish
FAIL SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu (phase SETUP)
    Case dir: /lustre/scratch5/dschlichting/E3SM/scratch/chicoma-gpu/SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu.20241125_133726_x4whor
Due to presence of batch system, create_test will exit before tests are complete.
To force create_test to wait for full completion, use --wait
test-scheduler took 64.3154673576355 seconds
```
To fix this, 
```
module spider cmake/3.25.1

------------------------------------------------------------------------------------------------------------------------------------------------------
  cmake: cmake/3.25.1
------------------------------------------------------------------------------------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "cmake/3.25.1" module is available to load.

      lanlpe/legacy
```
Before running a ```./create_test```,
```
ml lanlpe/legacy
ml cmake/3.25.1
```
which still fails in ```MODEL_BUILD```
```
./create_test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu -p t24_coastal_ocean_g --walltime 00:30:00
create_test will do up to 1 tasks simultaneously
create_test will use up to 160 cores simultaneously
Creating test directory /lustre/scratch5/dschlichting/E3SM/scratch/chicoma-gpu/SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu.20241125_133117_ncpmjg
RUNNING TESTS:
  SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu
Starting CREATE_NEWCASE for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu with 1 procs
Finished CREATE_NEWCASE for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu in 2.780944 seconds (PASS)
Starting XML for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu with 1 procs
Finished XML for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu in 0.735422 seconds (PASS)
Starting SETUP for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu with 1 procs
Finished SETUP for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu in 13.399406 seconds (PASS)
Starting SHAREDLIB_BUILD for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu with 1 procs
Finished SHAREDLIB_BUILD for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu in 152.755235 seconds (PASS)
Starting MODEL_BUILD for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu with 7 procs
Finished MODEL_BUILD for test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu in 196.077286 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /lustre/scratch5/dschlichting/E3SM/scratch/chicoma-gpu/SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu.20241125_133117_ncpmjg
    Errors were:
        Building test for SMS in directory /lustre/scratch5/.mdt0/dschlichting/E3SM/scratch/chicoma-gpu/SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu.20241125_133117_ncpmjg
        ERROR: BUILD FAIL: build e3sm failed, cat /lustre/scratch5/dschlichting/E3SM/scratch/chicoma-gpu/SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu.20241125_133117_ncpmjg/bld/e3sm.bldlog.241125-133410

Waiting for tests to finish
FAIL SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu (phase MODEL_BUILD)
    Case dir: /lustre/scratch5/dschlichting/E3SM/scratch/chicoma-gpu/SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu.20241125_133117_ncpmjg
Due to presence of batch system, create_test will exit before tests are complete.
To force create_test to wait for full completion, use --wait
test-scheduler took 366.18008065223694 seconds
```

Attached is the log file, ```/lustre/scratch5/dschlichting/E3SM/scratch/chicoma-gpu/SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu.20241125_133117_ncpmjg/bld/e3sm.bldlog.241125-133410```. 
[e3sm_bldlog.txt](https://github.com/user-attachments/files/17908878/e3sm_bldlog.txt)

Highlights are:
```
f951: Warning: Nonexistent include directory
/usr/bin/ld: cannot find -lblas: No such file or directory
/usr/bin/ld: cannot find -llapack: No such file or directory
collect2: error: ld returned 1 exit status
Target /lustre/scratch5/.mdt0/dschlichting/E3SM/scratch/chicoma-gpu/SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu.20241125_133117_ncpmjg/bld/e3sm.exe built in 0.441108 seconds
gmake[2]: *** [cmake/cpl/CMakeFiles/e3sm.exe.dir/build.make:554: /lustre/scratch5/.mdt0/dschlichting/E3SM/scratch/chicoma-gpu/SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu.20241125_133117_ncpmjg/bld/e3sm.exe] Error 1
gmake[2]: Leaving directory '/lustre/scratch5/.mdt0/dschlichting/E3SM/scratch/chicoma-gpu/SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu.20241125_133117_ncpmjg/bld/cmake-bld'
gmake[1]: *** [CMakeFiles/Makefile2:647: cmake/cpl/CMakeFiles/e3sm.exe.dir/all] Error 2
gmake[1]: Leaving directory '/lustre/scratch5/.mdt0/dschlichting/E3SM/scratch/chicoma-gpu/SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu.20241125_133117_ncpmjg/bld/cmake-bld'
gmake: *** [Makefile:94: all] Error 2
```

### PR DESCRIPTION
**Pull request by jonbob**
Updates LANL IC platform chicoma-gpu machine files, after recent upgrade

Fixes #6778
[BFB]

### CODE REVIEW

**Review by mark-petersen — APPROVED** [review]
Thank you @jonbob! This passes 
```
./create_test SMS_Ld3.T62_oQU240.GMPAS-NYF.chicoma-gpu_gnu -p t24_coastal_ocean_g --walltime 00:30:00
```

**Comment by jonbob** [comment]
passes sanity testing on pm-cpu and successfully built tests on chrysalis -- merged to next

**Review by dylanschlichting — COMMENTED** [review]
Thanks for doing this @jonbob . I can compile and run our 1.5 km Gulf of Mexico G case on gpus now. Can also reproduce the same test case that Mark did with no issues.

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
