### PR TITLE
update mpas-source: stand-alone makefile addition

### PR DESCRIPTION
**Pull request by mark-petersen**
Update stand-alone makefile to include intel 19. Does not affect E3SM. See https://github.com/MPAS-Dev/MPAS-Model/pull/816

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
Passes ocean nightly regression suite with intel 19 (intel-mpi) using debug and optimized.

**Comment by mark-petersen** [comment]
Passes sanity test 
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
```

**Review by jonbob — APPROVED** [review]
Looks good from a visual inspection

**Comment by jonbob** [comment]
passed sanity testing

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
