### PR TITLE
Update CIME to ESMCI cime5.8.28

### PR DESCRIPTION
**Pull request by jgfouca**
Update CIME to ESMCI cime5.8.28

Squash merge of jgfouca/branch-for-to-acme-2020-07-13

Features:
* improve error message for create newcase test option
* Clean up screen output & logging in check_input_data
* cpl7 mct driver: updates to dry deposition data
* User mods config grids2
* Allow gptl build to recognize ESMF_LIBDIR

Bug fixes:
* Make cprnc standalone build more robust to current env by using rpath
* Fix non-py3 compatible change in simple_compare.py
* set PIO_REARR_COMM_TYPE: coll for mpi-serial
* fix force_build_smp, did not work after case.setup
* Give the file name that results in the "empty read-only file" error
* share/streams: fix print format issue and turn off debug flags
* Improvement to baseline generation and comparison for the PET multi-submit test.
* When writing .env_mach_specific files, only write settings for main job

Features that don't effect E3SM
* remove nuopc data models to new repo CDEPS
* major refactor of nuopc datamodel caps and share code
* pio2 update
* improved error message for incorrect setting of cime model
* couples HYCOM with data atmosphere for UFS HAFS application
* Start adding option for MizuRoute

[non-BFB] for any full-atmosphere case because of dry-deposition changes.

### CODE REVIEW

**Comment by rljacob** [comment]
I'm pretty sure this will be non-BFB for atmosphere cases because of changes in seq_drydep_mod.F90 .  That's fine because we looked at those earlier and approved them.

**Comment by jgfouca** [comment]
Many thanks, @rljacob. My initial run saw DIFFs for:

```
SMS_P12x2.ne4_oQU240.A_WCYCL1850.mappy_gnu.allactive-mach_mods
ERP_Ln9.ne4_ne4.FC5AV1C-L.mappy_gnu
SMS.ne4_ne4.FC5AV1C-L.mappy_gnu.cam-cosplite
SMS_Ln9.ne4_ne4.FC5AV1C-L.mappy_gnu.cam-outfrq9s
SMS_D_Ln5.ne4_ne4.FC5AV1C-L.mappy_gnu
ERS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.mappy_gnu.cam-thetahy_sl_pg2
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.mappy_gnu
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.mappy_gnu.cam-thetahy_pg2
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.mappy_gnu.cam-thetahy_sl_pg2
``` 

And I was very-much not looking forward to trying to track those down!

**Comment by jgfouca** [comment]
Squashed into next.

**Comment by rljacob** [comment]
@golaz Note that this PR has the version of CIME with updates to dry-deposition parameters as discussed earlier.  Will change answers.

@jgfouca I updated the description.

**Pull request merged**
