### PR TITLE
Update atm namelist default and compsets for v2 WCYCL

### PR DESCRIPTION
**Pull request by wlin7**
Default eam parameters clubb_tk1, gw_convect_hcf are updated to
improve the simulation of mixed-phase clouds and QBO, respectively.

Two new compsets, WCYCL1850-1pctCO2 and WCYCL1850-4xCO2, are added
for the DECK experiments with transident 1% increase in CO2 and
abrupt-4xCO2 relative to the 1850 level of CO2 concentration.

Also update the wcprod testmod to match v2 WCYCL.

[non-BFB] all tests involving EAM affected due to changes in the
                two default parameters.

### CODE REVIEW

**Review by xuezhengllnl — APPROVED** [review]
Hi @wlin7 the changes in the default namelist for v2 WCYCL look good to me. Thanks for updating the default values.

**Review by golaz — APPROVED** [review]
Everything looks good to me. I ran a couple of tests:

- verified that I can BFB reproduce v2.LR.piControl
- verified that 1pctCO2 and 4xCO2 run and have correct CO2 concentrations

Thanks for the quick work on this.

**Comment by wlin7** [comment]
Rebased with master after #4349 merged. Forced pushed.

**Comment by rljacob** [comment]
@wlin7 since you added another commit, does this need another round of testing on next?  It will have to wait until Monday night because your commit was late.

**Comment by wlin7** [comment]
@rljacob , thanks for merging the PR to next. New next tests are not necessary. The new commit, [e291a1c](https://github.com/E3SM-Project/E3SM/pull/4385/commits/e291a1c57dc8a879903dff96ad19558eccebdd08), just added the intended flanduse_timeseries as default. @golaz used it already and previously had to manually specify it.

I can take over to submit the bless requests and merging to master. May I?

**Comment by wlin7** [comment]
The following two tests see nml diff, but having on impact on the results

```
SMS_B.ne4_ne4.F-EAM-AQP1.chrysalis_intel.eam-hommexx
SMS_Ld1.ne4_ne4.F-EAM-AQP1.chrysalis_intel.eam-clubb_only
```

**Comment by rljacob** [comment]
@wlin7 yes go ahead.

**Comment by wlin7** [comment]
Merged to master.
Bless requested submitted for chrysalis, mappy, compy devel and wcprod.

Surprised to see anvil prod tests only has 1 nml diff (allactive).  All 4 tests are  expected to diff in both results and nml.  Looking into it.

**Comment by rljacob** [comment]
Remerged to next (needed to keep next and master in sync).

**Comment by wlin7** [comment]
Some explanations for anvil wcprod tests:

Only allactive.wcprod is updated to use new default settings (removing those set in user_nl). The other three tests still have the original nml settings in user_nl files, overriding the default.

Still, it cannot explain why in allactive.wcprpd, while clubb_tk1 and gw_convect_hcf are correctly updated (and nml diff reported), no results diff reported.

**Comment by rljacob** [comment]
I know what happened.  @jgfouca blessed anvil on Saturday.  That was supposed to be for the compiler flag changes in PR #4378 that were merged on Friday.  So it wound up blessing these diffs as well.

**Comment by wlin7** [comment]
That makes sense, Rob. Just need to bless the nml diff for allactive.wcprod this time (submitting shortly). We still need to update the other three wcprod tests (the equivalent of F20TR and  F2010, and northamericarrm).

**Comment by rljacob** [comment]
If you know what to change, add it to #4393

**Pull request merged**
