### PR TITLE
Update ALCF Sunspot and Aurora machine configs

### PR DESCRIPTION
**Pull request by amametjanov**
Update ALCF Sunspot and Aurora machine configs.

[BFB]

### CODE REVIEW

**Comment by oksanaguba** [comment]
i was tagged to review this. i have no opinion regarding these modules (but removed ones seem not to be used in scream configs). Maybe, it is useful to list what cases you were able to build/run with which compilers for this change?

**Review by oksanaguba — APPROVED** [review]

**Review by omarkahmed — COMMENTED** [review]
@amametjanov , is there a specific reason why you are using the older software stack?  The latest available module on sunspot is oneapi/eng-compiler/2024.04.15.002

**Comment by amametjanov** [comment]
Yes, just a draft to get basics working. I'm testing `oneapi/eng-compiler/2024.04.15.002` and will ping for (re-) review. Thanks.

**Comment by rljacob** [comment]
@mahf708 the CI testing is running even though this a draft PR.  Can we change that?

**Comment by xylar** [comment]
I don't think there's a way to prevent CI from draft PRs. At least I've never seen it.

**Comment by xylar** [comment]
Good to know!

**Comment by amametjanov** [comment]
Testing on Sunspot:
- e3sm_integration + oneapi-ifx: all pass -- https://my.cdash.org/viewTest.php?buildid=2636710
- ...

**Comment by omarkahmed** [comment]
@amametjanov , did you run this branch with oneapi-ifxgpu ?

**Review by omarkahmed — APPROVED** [review]
@amametjanov , your changes look good to me.

I would suggest considering the following changes to the oneapi-ifxgpu config:
-<MAX_MPITASKS_PER_NODE compiler="oneapi-ifxgpu">48</MAX_MPITASKS_PER_NODE>
- <env name="ZEX_NUMBER_OF_CCS">0:4,1:4,2:4,3:4:4:4,5:4,6:4,7:4</env>

This would allow you to run in "4-CCS mode", where you can use 4 MPI ranks per PVC tile with minimal performance differences on the device side (assuming that work is balanced between ranks), but significant speed-up on the host due to the increased number of processes.

**Review by omarkahmed — APPROVED** [review]
@amametjanov , I am seeing some errors on your branch running on aurora with multiple openmp threads.  Removing the "--cpu-bind depth" option to mpiexec appears to resolve things.  Otherwise, things are looking great!

**Comment by rljacob** [comment]
Notes:  Aurora currently down for network upgrade.  Will wait for it to come back up and test again.

**Pull request merged**
