### PR TITLE
Adding default PE layouts for Cryo v2 grids on Anvil/Chrysalis

### PR DESCRIPTION
**Pull request by darincomeau**
Adds default PE layouts for Cryosphere v2 B-cases with ECwISC30to60E2r1 and SOwISC12to60E2r4 ocn/ice grids on Anvil and Chrysalis.

[BFB]

### CODE REVIEW

**Comment by darincomeau** [comment]
@jonbob @stephenprice I've tested each of these six PE layouts using the `-pecount $PELAYOUT` flag in the `./create_newcase` step (where $PELAYOUT=S, M, or L), so I don't think you need to do any testing (although are of course welcome to). We'll use this functionality in our run scripts going forward.

**Comment by jonbob** [comment]
@darincomeau - just a friendly reminder about the naming convention for branches, which includes all lowercase and hyphens instead of underscores. We won't worry this time, but maybe for the next one?

**Comment by darincomeau** [comment]
Ah thanks for pointing that out @jonbob , I'll be more careful next time.

**Review by jonbob — APPROVED** [review]
I like the new restructuring -- approved from a visual inspection and developer testing

**Review by stephenprice — APPROVED** [review]

**Comment by jonbob** [comment]
passes sanity testing, merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
