### PR TITLE
Update mpas-source: seaice regional stats bug

### PR DESCRIPTION
**Pull request by akturner**
Fixes allocation bug with regional statistics in sea ice component

Merges https://github.com/MPAS-Dev/MPAS-Model/pull/815

Fixes https://github.com/E3SM-Project/E3SM/issues/4107

[BFB]

### CODE REVIEW

**Review by njeffery — APPROVED** [review]
This fix enables full functionality of the sea ice regional stats analysis member. I tested the  sea ice changes by running a GCASE with the ice_areal_avg and max region options for various BGC and physical ice.  Without this fix, the code segmentation faults in the streams io. I did not review the ocean changes.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
passes sanity testing after the merge

**Comment by jonbob** [comment]
merged to master. @akturner - you can delete this branch from your fork

**Pull request merged**
