### PR TITLE
Adding restart tests for theta

### PR DESCRIPTION
**Pull request by oksanaguba**
Adding ERS tests for hydro/nonhydro theta dycore. 

[bfb] but will need baselines.

### CODE REVIEW

**Comment by oksanaguba** [comment]
First I tried to add ERs tests into single-exec suite of SMS tests in cam_theta, but building did not work. Then I tried to use single-exec option for this new separate suite, cam_theta_restart, but the second test (the one that is supposed to use build) reported build error. I ended up adding two tests with two new builds.

**Comment by jgfouca** [comment]
@oksanaguba , let me see if I can get single-exec to work for multi-case test cases.

**Comment by jgfouca** [comment]
@oksanaguba , when I added the ERS tests to eam_theta, everything built and ran fine on melvin. I think it should work for you as well.

**Comment by oksanaguba** [comment]
@jgfouca I tried again on anvil, I moved era tests into cam_theta suite and the suite got built. One exec that was built belongs to ERS test. The whole suite then passed except for the second ERS test (the one that did not have exec built) with error 'ERROR: BUILD_COMPLETE is not true' . So, I assumed this time at least building worked because shared exec was from one of ERS suites. So, I moved ERS tests into the middle of the list of tests in cam_theta suite, to force the suite to build with   with exec not from ERS tests. Now even building does not work, I see this: https://gist.github.com/oksanaguba/e6f7343a0c76aaa9c799425bcbc5686e . Thanks!

**Comment by oksanaguba** [comment]
By the way, this is the suite I used:
```
    "eam_theta" : {
        "share"    : True,
        "time"     : "02:00:00",
        "tests"    : (
                 "SMS.ne4_ne4.FC5AV1C-L.cam-thetahy_ftype0",
                 "SMS.ne4_ne4.FC5AV1C-L.cam-thetahy_ftype1",
                 "SMS.ne4_ne4.FC5AV1C-L.cam-thetahy_ftype2",
                 "SMS.ne4_ne4.FC5AV1C-L.cam-thetahy_ftype4",
                 "ERS.ne4_ne4.FC5AV1C-L.cam-thetahy_ftype2",
                 "ERS.ne4_ne4.FC5AV1C-L.cam-thetanh_ftype2",
                 "SMS.ne4_ne4.FC5AV1C-L.cam-thetanh_ftype0",
                 "SMS.ne4_ne4.FC5AV1C-L.cam-thetanh_ftype1",
                 "SMS.ne4_ne4.FC5AV1C-L.cam-thetanh_ftype2",
                 "SMS.ne4_ne4.FC5AV1C-L.cam-thetanh_ftype4",
                 "SMS.ne4_ne4.FC5AV1C-L.cam-thetahy_sl",
                 )
    },
```

**Comment by jgfouca** [comment]
@oksanaguba , ah, i wonder if it's order-dependent. I put the ERS tests at the top and it worked. Let me try to debug.

**Comment by jgfouca** [comment]
@oksanaguba , please rebase this PR on latest master, add the ERS tests to eam_theta, and see if it works.

**Comment by rljacob** [comment]
@oksanaguba take care of the rebase as Jim asked please.

**Comment by oksanaguba** [comment]
Ready to merge. Ran eam_theta suite and all is ok except for thetahy_sl run, which crashes due to gcc 5.3 issue (which is in master, too).

**Pull request merged**
