### PR TITLE
DSS omega in SL transport; fix a unit test; fix Intel 18 build.

### PR DESCRIPTION
**Pull request by ambrad**
1. Omega is needed for diagnostics. DSS it in SL transport, just like it is DSSed in Eulerian transport.
2. An SL unit test had an uninitialized variable. Fix it.
3. An unused feature in SL transport had a bug. Fix it and the test.
4. Intel 18 with -O3 -fp-model-fast has a problem with a vectorization pragma. Comment it out. Comment out a similar one for safety.

[BFB] except on Anvil with Intel 18, where it solves a BFB problem.

### CODE REVIEW

**Comment by oksanaguba** [comment]
It is prob. ok on anvil, too. I run on anvil, default for e3sm is intel 17.

**Comment by mt5555** [comment]
merged to next

**Comment by rljacob** [comment]
There is a diff on sandiatoss3 that we think is from this PR:
SMS.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.cam-thetahy_sl 
https://my.cdash.org/testDetails.php?test=48201170&build=1670233

Can you confirm?

**Comment by mt5555** [comment]
confirmed.  This failure of this test and other tests now also confirm that OMEGA (vertical velocity of pressure surfaces) is now used by the physics for more than diagnostics and changes to OMEGA to impact the solution.

**Comment by rljacob** [comment]
It was unclear if OMEGA was used in the prognostic equations?

**Comment by mt5555** [comment]
no, it was unclear if OMEGA is used by the physics, other than for diagnostics.

**Pull request merged**
