### PR TITLE
get_cime_env: new tool for conveniently loading CIME env

### PR DESCRIPTION
**Pull request by jgfouca**
[BFB]

### CODE REVIEW

**Comment by jgfouca** [comment]
@oksanaguba , @mt5555 , this could be useful for HOMME stuff.

**Comment by oksanaguba** [comment]
YAY!
```
[onguba@skybridge-login1 acme-b]$ cime/scripts/Tools/get_cime_env
source /usr/share/lmod/lmod/init/sh && module purge && module load sems-env sems-git sems-python/2.7.9 sems-cmake/3.12.2 gnu/4.9.2 sems-intel/17.0.0 sems-openmpi/1.10.5 sems-netcdf/4.4.1/exo_parallel && export NETCDFROOT=/projects/sems/install/toss3/sems/tpl/netcdf/4.4.1/intel/17.0.0/openmpi/1.10.5/exo_parallel && export NETCDF_INCLUDES=/projects/sems/install/toss3/sems/tpl/netcdf/4.4.1/intel/17.0.0/openmpi/1.10.5/exo_parallel/include && export NETCDF_LIBS=/projects/sems/install/toss3/sems/tpl/netcdf/4.4.1/intel/17.0.0/openmpi/1.10.5/exo_parallel/lib && export OMP_STACKSIZE=64M && export PNETCDFROOT=/projects/sems/install/toss3/sems/tpl/netcdf/4.4.1/intel/17.0.0/openmpi/1.10.5/exo_parallel
```

**Comment by oksanaguba** [comment]
I am just enjoying it:
```
EXAMPLES:
    # Get the default CIME env 
    > ./get_cime_env
    # Get the default CIME env and load it into your current shell env 
    > eval $(./get_cime_env)
    # Get the CIME env for a different machine or compiler  
    > ./get_cime_env -c SMS.f09_g16.X.mach_compiler
    # Get the CIME env for a different mpi (serial in this case)  
    > ./get_cime_env -c SMS_Mmpi-serial.f09_g16.X
    # Same as above but also load it into current shell env 
    > eval $(./get_cime_env -c SMS_Mmpi-serial.f09_g16.X)
```

**Comment by rljacob** [comment]
Shouldn't this go to the CIME repo first?

**Comment by jgfouca** [comment]
@rljacob , I think it's fine to go in here. It's an E3SM-specific tool.

**Comment by jgfouca** [comment]
@rljacob , any suggestions? Maybe get_cime_case_env? get_case_env?

**Comment by rljacob** [comment]
get_case_env looks good.

**Pull request merged**
