### PR TITLE
Update CIME to ESMCI cime5.8.2

### PR DESCRIPTION
**Pull request by jgfouca**
Update CIME to ESMCI cime5.8.2

Squash merge of jgfouca/branch-for-to-acme-2019-04-22

Features:
* Adds a stub for Integrated Assessment Component (IAC)
* Allow specific tests to ignore field list differences

Bug fixes:
* Minor

[BFB]

### CODE REVIEW

**Comment by jgfouca** [comment]
Testing and visual inspection look good. Merging to next.

**Comment by rljacob** [comment]
What kind of testing are you doing?

**Comment by jgfouca** [comment]
> What kind of testing are you doing?

on melvin: ./create_test -c -b master e3sm_developer

**Comment by rljacob** [comment]
Changing title/description to CIME 5.8.2 since that tag was made immediately after this

**Pull request merged**
