### PR TITLE
Adding ADIOS install paths

### LINKED ISSUE #5486: buildlib.pio failed with HDF5 linker errors on bebop using GNU compilier
Not reproducible with the default intel compiler.

Steps to reproduce
```
ssh bebop.lcrc.anl.gov

git clone https://github.com/E3SM-Project/E3SM.git
cd E3SM

git submodule update --init

cd cime/scripts
./create_newcase --machine=bebop --compiler=gnu --case X_f19_g16 --compset X --res f19_g16

cd X_f19_g16

./case.setup

./case.build
```
Linker errors in pio.bldlog
```
/blues/gpfs/software/centos7/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/netcdf-4.4.1-xkjcghm/lib/libnetcdf.a(libnetcdf4_la-nc4file.o): In function `nc4_create_file':
nc4file.c:(.text+0x52b): undefined reference to `H5P_CLS_FILE_ACCESS_ID_g'
nc4file.c:(.text+0x5f7): undefined reference to `H5P_CLS_FILE_CREATE_ID_g'
/blues/gpfs/software/centos7/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/netcdf-4.4.1-xkjcghm/lib/libnetcdf.a(libnetcdf4_la-nc4file.o): In function `read_type':
nc4file.c:(.text+0x215e): undefined reference to `H5free_memory'
...
```

Possible fix: set HDF5_PATH for bebop in config_machines.xml and gnu_bebop.cmake.

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Adding ADIOS install paths and library dependencies for the
different machines+compilers

Fixes #5486

[BFB]

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
To use ADIOS to write E3SM outputs the following changes are needed,

- PR #5490 (for MPAS components)
- PR #5492 
- PR #5494 
- Merging https://github.com/ESMCI/cime/tree/jayeshkrishna/adios2_support to ESMCI CIME Master and updating it in E3SM (PR #5492 is a pre-req for merging this branch in CIME)

**Comment by dqwu** [comment]
@jayeshkrishna 
In this PR, ADIOS2 libs are added to cmake macros for Cori and Theta, but corresponding ADIOS install paths are not added for
Cori and Theta in config_machines.xml. Since Cori will retire soon and we will probably never need to run E3SM on Theta,  we can create a future PR to fix this minor issue.

**Comment by dqwu** [comment]
@jayeshkrishna 
ADIOS install path is also missing for anvil. We can create a future PR to add it (together with Cori and Theta).

**Comment by dqwu** [comment]
@jayeshkrishna 
When testing ADIOS type on compy and bebop, there are some minor issues encountered, but they are unrelated to ADIOS type.
* On compy, there is a confirmed setup issue with --mpilib=mvapich2 (#5487).
* On bebop, there is a confirmed build issue with GNU compiler (#5486). This will be fixed in a separate PR.

**Comment by dqwu** [comment]
@jayeshkrishna 
When testing on bebop, --machine=bebop must be explicitly specified, see issue #5485

**Comment by dqwu** [comment]
@jayeshkrishna 
On Summit, there are build errors for ADIOS type with "--compiler=ibmgpu"
This is because we actually do not have ibmgpu_summit.cmake (we do have ibmgpu_ascent.cmake) to add ADIOS library dependencies.

Shall we fix this issue in a future PR?

**Comment by jayeshkrishna** [comment]
> @jayeshkrishna On Summit, there are build errors for ADIOS type with "--compiler=ibmgpu" This is because we actually do not have ibmgpu_summit.cmake (we do have ibmgpu_ascent.cmake) to add ADIOS library dependencies.
> 
> Shall we fix this issue in a future PR?

Let us fix that in a future PR since its not related to ADIOS support (please create an issue for it, if needed)

**Comment by dqwu** [comment]
> > @jayeshkrishna On Summit, there are build errors for ADIOS type with "--compiler=ibmgpu" This is because we actually do not have ibmgpu_summit.cmake (we do have ibmgpu_ascent.cmake) to add ADIOS library dependencies.
> > Shall we fix this issue in a future PR?
> 
> Let us fix that in a future PR since its not related to ADIOS support (please create an issue for it, if needed)

Actually ibmgpu_summit.cmake is not required for PnetCDF type so far. We can create an issue for ADIOS type after this PR is merged.

**Comment by jayeshkrishna** [comment]
Not sure why ibmgpu_summit.cmake is not required for the PnetCDF type (and required for ADIOS), but let us use a separate issue to discuss it further (maybe a detailed issue description, for the new issue, would help).

**Comment by jayeshkrishna** [comment]
@dqwu in his testing found that ADIOS paths were missing for Anvil (but the ADIOS libs were listed as dependencies) and this caused build failures on Anvil. This issue has now been fixed and the branch was rebased.

Also, as part of the rebase process the ADIOS settings for Anvil/Cori/Theta were restored (these settings can be deleted later, if needed, along with the machine configs) & a fix for PR #5486 was also added

The fix for PR #5486 was to add the paths to the HDF5 library in the config machines and cmake macro files for gnu on bebop.

**Comment by dqwu** [comment]
@jayeshkrishna 
FYI, I have rebased this branch again to upgrade installed ADIOS2 libs from 2.7.0 to 2.8.3 for anvil, bebop and compy. The old 2.7.0 libs were not configured to support latest BP5 format used by SCORPIO.

So far, ADIOS 2.7.0 is only used by anlworkstation (already retired), cori-haswell (to be retired), and theta (we will probably never need to run E3SM on it).

**Comment by dqwu** [comment]
@jayeshkrishna 
There are some known issues with IBM XL compiler on Summit, and users can use GNU or PGI compilers to test ADIOS type so far.

**Review by dqwu — APPROVED** [review]

**Comment by jayeshkrishna** [comment]
@ndkeen & @grnydawn please review this PR when you get a chance (Note: As discussed above you need couple of other PRs to start using ADIOS out of the box. You might just want to review that the changes in this PR does not break anything for you.).

**Review by ndkeen — COMMENTED** [review]
If I'm reading this correctly, it looks like we are adding quite a few libs to the link line -- even if a case is not using ADIOS.  Is that right?

**Comment by jayeshkrishna** [comment]
Yeah, the ADIOS support is added during the SCORPIO build (yeah, and ADIOS adds a number of dep libs) and the user then has the choice to use ADIOS at runtime (PIO_TYPENAME in env_run.xml).

**Comment by ndkeen** [comment]
It doesn't look like it's adding much to the executable, but it does seem like it makes sense to only link with libraries that are actually needed. But, as you note, it's the norm to have XML settings that can toggle options such as this.

**Review by ndkeen — APPROVED** [review]

**Comment by grnydawn** [comment]
@jayeshkrishna adios2 setting is missing for Crusher. Also we may need a future PR for Frontier support 

In config_machines.xml, "ADIOS2_DIR" is missing for crusher machine
In several *_crusher.cmake files in cmake_macros folder, adios2 library setting is missing.

On Crusher( and on Frontier) adios2 is installed through Spack and can be loaded using module.

**Comment by jayeshkrishna** [comment]
Yeah, this PR does not include support for ADIOS on all the machines. @dqwu is working on adding support for ADIOS on the remaining E3SM machines.

**Comment by ndkeen** [comment]
The cori-knl tests failed with:
```
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -ladios2_c_mpi
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -ladios2_c
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -ladios2_core_mpi
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -ladios2_core
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -ladios2_evpath
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -ladios2_ffs
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -ladios2_dill
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -ladios2_atl
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -ladios2_enet
```

**Comment by jayeshkrishna** [comment]
@dqwu has fixed the permissions for the ADIOS install directories on Cori (that caused the missing adios* libs issue above)

**Pull request merged**
