### PR TITLE
Update mapping and domain files created with an incorrect T62 scrip file

### PR DESCRIPTION
**Pull request by jonbob**
Several configurations have mapping and domain files made from a T62 scrip file that did not extend to the North pole, which is incorrect and causes some problems in the moab driver. This PR updates those files using a correct T62 scrip file for currently used resolutions.

[NML]
[non-BFB] for tests using T62

### CODE REVIEW

**Review by rljacob — APPROVED** [review]

**Comment by iulian787** [comment]
@jonbob Hi Jon, I tried this case  on chrysalis,  --compset GMPAS-IAF --res T62_oQU240wLI , this is the case folder:
/lcrc/group/e3sm/iulian/CASES/T62o240_jon
source code is here:
/lcrc/group/e3sm/iulian/E3SM, it is at this commit: 565a93ead6085
check input data is not finding a file:

Model datm missing file domainfile = '/lcrc/group/e3sm/data/inputdata/share/domains/domain.lnd.T62_oQU240wLI_mask.240513.nc'

What machine should I try?

**Comment by jonbob** [comment]
Sorry @iulian787 -- we had changed a filename convention and I missed it when I updated to the new files. Could you please try a clean checkout and try again?

**Comment by iulian787** [comment]
Thanks @jonbob ,  it works now! 
I rebased my data rof branch off your branch, and it works now with the new files, without other modifications :)

**Review by iulian787 — APPROVED** [review]
I tested --compset GMPAS-IAF --res T62_oQU240wLI  with this branch, and the files can be successfully processed now by MOAB and tempestremap

**Comment by rljacob** [comment]
@jonbob can you merge this?  I can do it if you're busy.

**Comment by jonbob** [comment]
@rljacob -- I'll do that today. I need to make sure all the new files are on the inputdata server

**Comment by jonbob** [comment]
testing shows NML and regular DIFF as expected for:
* ERS_Ld5.T62_oQU120.CMPASO-NYF.chrysalis_intel

Also passes, as expected:
* ERP_Ld3.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-pioroot1

merged to next

**Comment by jonbob** [comment]
merged to master and expected NML and regular DIFFs blessed

**Pull request merged**
