### PR TITLE
Introduce our own copy of CIME share code

### PR DESCRIPTION
**Pull request by rljacob**
Add our own copy of the CIME share code to E3SM in E3SM/share

This includes all of the following from cime/src/share
RandNum/  esmf_wrf_timemgr/  include/  nuopc/	streams/  test/  timing/  unit_test_stubs/  util/

Include all relevant git commit history from those directories (constructed using filter-repo). Code taken from cime master b95a28b41.

Modify cime/config/e3sm/config_files to use E3SM locations by point to new buildlib scripts in E3SM/share/build

Update CIME submodule to point to branch with above config_files change.  Otherwise identical to previous cime submodule pointer.

[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
@rljacob - I tried to check this out and it was unhappy with the CIME submodule

**Comment by rljacob** [comment]
Looks like I forgot to push that cime branch and its also not in my local copy anymore.  Hang on.

**Comment by rljacob** [comment]
@jonbob ok try again.

**Comment by jonbob** [comment]
Thanks @rljacob - that worked.

**Comment by jonbob** [comment]
Passed tests as-is and with cime/src/share deleted.

**Review by jonbob — APPROVED** [review]
Passed testing for me

**Review by jgfouca — APPROVED** [review]

**Comment by rljacob** [comment]
merged to next

**Pull request merged**
