### PR TITLE
Fixes support for user-defined ELM grid

### PR DESCRIPTION
**Pull request by bishtgautam**
This code modification restores the support for user-defined land grid that
was broken when the name of the land model was changed. A new test is
added for `--res ELM_USRDAT`.

[BFB]

### CODE REVIEW

**Review by rljacob — CHANGES_REQUESTED** [review]
Replace CLM_USRDAT with ELM_USRDAT everywhere.

**Comment by bishtgautam** [comment]
@rljacob You wanted me to rename local variables as in https://github.com/E3SM-Project/E3SM/pull/3884/commits/615ba48a48cd30029b0aa6e95ed8483aa386e56f? Or, do you want me to rename namelist variables such that `case.get_value("CLM_CO2_TYPE")` changes to `case.get_value("ELM_CO2_TYPE")`?

**Review by rljacob — APPROVED** [review]

**Comment by rljacob** [comment]
Nevermind.  I thought I saw some more instances of CLM_USRDAT in elm but I think you got them al.

**Comment by rgknox** [comment]
Thanks @bishtgautam , these grids are very useful for FATES runs

**Pull request merged**
