### PR TITLE
update mpas-source: Add the option for inactive top cells

### PR DESCRIPTION
**Pull request by mark-petersen**
See https://github.com/MPAS-Dev/MPAS-Model/pull/825. Inactive top cells are introduced to add flexibility to the vertical coordinate below ice shelves. For all existing mesh configurations, this simply substitutes arrays with values of 1 rather than a fixed character 1 for the lower bound of vertical loops in the code.

[non-BFB] only for compy with PGI optimized (BFB in debug mode)
 

E3SM tests that are bit-for-bit:

```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
PEM_Ln9_P1024.ne30_oECv3.A_WCYCL1850S.cori-knl_intel
PEM_Ln9_P1024.ne30_oECv3.A_WCYCL1850S.anvil_intel
PET_Ln9_P1024.ne30_oECv3.A_WCYCL1850S.anvil_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
PET_Ln9_P1024.ne30_oECv3.A_WCYCL1850S.compy_intel

SMS_PS.northamericax4v1pg2_WC14to60E2r3.A_WCYCL1850S_CMIP6.chrysalis_intel.allactive-wcprodrrm
SMS_Ld1.ne30pg2_r05_EC30to60E2r2.A_WCYCL1850S_CMIP6.chrysalis_intel.allactive-wcprod
```

Tests that passed (but were not compared with `E3SM/master`):

```
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.anvil_gnu
PEM_Ln9.T62_oQU240.GMPAS-IAF.anvil_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_pgi 
```

Tests with diffs:
```
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
PEM_Ln9_P1024.ne30_oECv3.A_WCYCL1850S.compy_pgi
```

[nonBFB]

### CODE REVIEW

**Comment by cbegeman** [comment]
@mark-petersen I am not able to edit your comment but feel free to copy this list

All the following E3SM tests are bit-for-bit:
`PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel`
`PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel`
`SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel` (comparison with e3sm/develop)
`PEM_Ln9_P1024.ne30_oECv3.A_WCYCL1850S` (comparison e3sm/develop)

**Comment by xylar** [comment]
## Performance
https://github.com/MPAS-Dev/MPAS-Model/pull/825#issuecomment-804371629 and subsequent comments discuss performance. For many tests, performance differences appear to be in the noise but we are seeing 1-2% slowdown with Intel on Grizzly and with both Intel and PGI on Compy in some smaller tests.

**Comment by xylar** [comment]
## Non-bit-for-bit

As discussed here: https://github.com/MPAS-Dev/MPAS-Model/pull/825#issuecomment-803564199, the non-bit-for-bit results have been tracked down to 2 loops in the `ocn_vel_pressure_grad_tend` module.  The old loops looked like:
``` Fortran
do k=2,kMax
```
while the new loops are:
``` Fortran
do k=kMin+1,kMax
```
The results are bit-for-bit with PGI compilers on Compy in debug mode but have diffs in optimized mode for both test I ran:
```
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
PEM_Ln9_P1024.ne30_oECv3.A_WCYCL1850S.compy_pgi
```
**Note:** I wasn't able to run `PEM_D_Ln9_P1024.ne30_oECv3.A_WCYCL1850S.compy_pgi`, the debug version of the test above because the baseline run failed with a seg fault.

**Comment by vanroekel** [comment]
@mark-petersen @xylar @mattdturner @jonbob -- I'm extremely uncomfortable merging in a nonBFB PR that was expected to be BFB even though it is just PGI in optimized on compy, especially since WCv2 is not finalized yet.  I would like to suggest a few paths forward for this PR
1) Expand testing to include the official water cycle configuration ne30pg2+EC30to60E2r2 with WCYCL1850 on chrysalis and compy with intel -- optimized + debug
2) Understand the pgi failure to be BFB

or

1) add flags around the offending loops in `ocn_vel_pressure_grad_tend` that can put us back to the original loops for WCYCL runs

or

1) wait for this PR to merge until v2 is finalized for water cycle.

cc'ing @golaz

**Comment by xylar** [comment]
@vanroekel

> Expand testing to include the official water cycle configuration ne30pg2+EC30to60E2r2 with WCYCL1850 on chrysalis and compy with intel -- optimized + debug

Could you give me a specific test to run?  I'm not very good with E3SM tests yet.

> Understand the pgi failure to be BFB

Could you clarify what would satisfy this requirement?  I don't know what I can do to satisfy this.

> add flags around the offending loops in ocn_vel_pressure_grad_tend that can put us back to the original loops for WCYCL runs

I think this is the most likely path.  There isn't a clear flag to put around it right now because we don't have a flag that says, `minLevel*` is being used.  But we could add something for this purpose for now.

> wait for this PR to merge until v2 is finalized for water cycle.

I'm not keen on this because this work has been delayed (mostly becuase of me not taking the time to do it) for years as it is, and @cbegeman has a lot of work waiting on this.

**Comment by golaz** [comment]
I share @vanroekel  hesitancy here. We have heard similar stories in the past, only to discover unexpected changes. The comparison is probably not fair, but CLUBBv2 is a prime example.

If this really needs to go in now, I would suggest a more extensive test. Is someone who is not actively working on critical Water Cycle issues willing to come forward and volunteer to rerun a recent v2 configurations to demonstrate that the changes are indeed minor?

**Comment by vanroekel** [comment]
as an alternative, could we show BFB with current WC configs on compy and chrysalis (I can provide this to a cryo volunteer) and ask @rljacob if we can ignore the PGI result as it is rarely used?

**Comment by rljacob** [comment]
Yes you could ignore that PGI result.

**Comment by vanroekel** [comment]
@xylar here are the WC production tests. If you could run these on compy and chrysalis with intel and they pass, I'm okay proceeding with this PR even without the flags on the loops
```
SMS_Ld1.ne30pg2_r05_EC30to60E2r2.A_WCYCL1850S_CMIP6.anvil_intel.allactive-wcprod
SMS_PS.northamericax4v1pg2_WC14to60E2r3.A_WCYCL1850S_CMIP6.anvil_intel.allactive-wcprodrrm
```

**Comment by xylar** [comment]
Thanks @vanroekel and @rljacob.

@cbegeman, I'm running the baselines for these 2 tests on chrysalis right now.  Could you try your hand and running them on Compy?  (Change `anvil` to `compy`.)

**Comment by cbegeman** [comment]
Thanks, @vanroekel @rljacob and @golaz for weighing in! Sounds like we have a reasonable path forward. 

@xylar I'll run these tests on compy.

**Comment by xylar** [comment]
As I noted above, both tests requested by @vanroekel passed and are bit-for-bit with E3SM/master on Chrysalis.

**Comment by cbegeman** [comment]
Both tests pass on Compy and are bit-for-bit with E3SM/master:
```
SMS_Ld1.ne30pg2_r05_EC30to60E2r2.A_WCYCL1850S_CMIP6.compy_intel.allactive-wcprod
SMS_PS.northamericax4v1pg2_WC14to60E2r3.A_WCYCL1850S_CMIP6.compy_intel.allactive-wcprodrrm
```
@mark-petersen We're ready to proceed with the merge.

**Comment by vanroekel** [comment]
Thank you @cbegeman and @xylar for the extra tests!  @jonbob, I'm okay with proceeding on this pr.

**Review by jonbob — APPROVED** [review]
Approved based on visual inspection and level of testing by developers

**Comment by jonbob** [comment]
merged to next

**Comment by xylar** [comment]
Thanks so much @vanroekel and @golaz for the feedback, and @mark-petersen and @jonbob for the work getting this PR in.  It really means a lot to us!

**Pull request merged**
