### PR TITLE
New MPAS-SI + WW3 compset (D-compset plus ww3)

### PR DESCRIPTION
**Pull request by erinethomas**
New WW3 compset option for MPAS-SI plus waves. For testing purposes only. 
Modification to D-JRA compset alias - should include 'TEST' in alias. 

[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
@erinethomas - did you decide you wanted "TEST" in the compset alias to help indicate that any runs with this compset may not be scientifically valid?

**Comment by erinethomas** [comment]
I removed 'TEST' in the alias to follow the alias convention used by the new D-JRA1p5 compset made by @darincomeau. 
I think both compsets (D-JRA - defined in mpas-si, and the D-JRA-WW3 compset defined in ww3) should match. 
Possibly they should both include 'TEST' in the alias to indicate they are not scientifically validated.

**Comment by jonbob** [comment]
passes sanity testing, merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
