### PR TITLE
Initial implementation of BGC carbon budget in the coupler

### PR DESCRIPTION
**Pull request by jonbob**
Brings in a new coupler carbon budget which is implemented similarly to the current heat and water budgets, but in a separate source file. The output is intermingled with that from the other budgets, so that the monthly budget tables are all output before the annual ones, for example. The BGC budget is controlled overall by the BUDGETS flag found in env_run.xml but also has its own "do_bgc_budgets" flag that is included in the driver seq_infodata_inparm namelist and can be set by user_nl_cpl. By default it is off unless the compset includes BGC fluxes, in which case it is set to true.

[NML]
[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
Test merges passes:
* SMS_D_Ld1.T62_oEC60to30v3.DTESTM.chrysalis_intel
with expected NML DIFF.

Waiting on:
* SMS_Ld2.ne30pg2_r05_EC30to60E2r2.BGCEXP_CNTL_CNPECACNT_1850.chrysalis_intel.elm-bgcexp

**Review by rljacob — APPROVED** [review]

**Review by susburrows — APPROVED** [review]
I just did a quick visual inspection of the code changes.  Thanks for putting this together, Jon.

I saw that you also added a central definition for the molecular weights of carbon, oxygen and CO2 here, which is great.  We should make sure that the rest of the BGC group is aware of this addition, so that folks can be referencing this central definition when they work on other parts of the code that use those constants.

**Comment by jonbob** [comment]
Thanks for the reviews. The only issue I'm aware of is that it has restart issues but only with one term in the budget. That's confusing to me, but maybe points to a sequencing problem  with when each part of the budget is calculated. I'll keep working on it, but we could also merge this as-is and create an issue for the restart being non-bfb

**Comment by susburrows** [comment]
Jon, that sounds like a good approach to me if @rljacob is ok with it.  It would be nice to have this PR merged soon so that it can be part of the v2.1 tag.

**Comment by rljacob** [comment]
Yes that's fine with me.

**Comment by jonbob** [comment]
Passes sanity testing, merged to next

**Comment by susburrows** [comment]
Thanks Jon!

**Comment by jonbob** [comment]
@susburrows - anytime. I'll work on the restart issue next

**Comment by jonbob** [comment]
merged to master and expected NML DIFFs blessed

**Pull request merged**
