### PR TITLE
Add r0125_r0125_oRRS15to5 grid

### PR DESCRIPTION
**Pull request by wlin7**
This grid is added for I-case configuration.

[BFB]

### CODE REVIEW

**Comment by wlin7** [comment]
This grid intends to be used to run I-case at 1/8 degree and oRRS15to5 domain mask, such as spin up clm to generate land IC for ne1024 configuration.

**Comment by tangq** [comment]
The changes look good to me.

**Comment by wlin7** [comment]
Merged to next.

**Comment by wlin7** [comment]
Merged to master.

**Pull request merged**
