### PR TITLE
Add snow-vegetation interactions, NGEE Arctic IM3

### PR DESCRIPTION
**Pull request by thorntonpe**
Change handling for how snow burial of shrubs is calculated, with parameterization for bending of stems. 
Change the treatment of surface weather downscaling on topounits, so that the downscaling happens when using the coupler bypass code branch.
Introduce four new parameters controlling the burial of shrubs by snow into vegetation physiology file.
If new parameters are not included on the physiology file the code replaces with default values, which then produce BFB results with code before this PR.
The four new parameters are: taper, stocking, bendresist, and vegshape. 
[BFB]
Development Lead: Rich Fiorella <rfiorella@lanl.gov>
Development Team: Katrina Bennett <kbennett@lnl.gov>, Cade Trotter <ctrotter@lanl.gov>, Claire Bachand <cbachand@lanl.gov>

### CODE REVIEW

**Comment by thorntonpe** [comment]
@peterdschwartz and @bishtgautam My branch is rebased to the current master. I think it should pass the land_developer test suite BFB.

**Review by bishtgautam — APPROVED** [review]
@thorntonpe, the PR looks good to me.

I believe you inadvertently deleted a lot of whitespaces in this PR (e.g., https://github.com/E3SM-Project/E3SM/pull/6607/files#diff-f9276b0713e2af1bcd0495bdbd37de680e27b15dcf180b1d8da1ec0243ba17dfL39). Maybe the setting of your editor is such that it removes whitespaces automatically at the end of the line of the current cursor location and you can try avoiding whitespace deletion in the future.

**Comment by thorntonpe** [comment]
@bishtgautam yes, the whitespace deletion was due to an editor setting from one of the LANL developers. I'll ask that they change that setting for future development.

**Comment by thorntonpe** [comment]
Based on discussion yesterday at ORNL I looked into the CPP flags that might have some influence on the use of shared executables for land developer tests. I'm not seeing any obvious issues. Could we do a test integration of this PR?

**Comment by bishtgautam** [comment]
We are waiting for the last [two open PRs for the v3.0.1 tag](https://github.com/E3SM-Project/E3SM/pulls?q=is%3Aopen+is%3Apr+milestone%3Av3.0.1) to be merged. Then, we should be able to begin integrating this PR.

**Comment by thorntonpe** [comment]
I'm seeing the pm-cpu results show most tests passing, but I was expecting to see a fail (no baseline) for the new test in this PR:
ERS.ELM_USRDAT.I1850CNPRDCTCBC.elm-snowveg_arctic
That test is not showing up in either the PASS or FAIL lists.

**Comment by thorntonpe** [comment]
@peterdschwartz Realizing now that your test suite was probably submitted outside the test dashboard. Ignore previous comment.

**Comment by peterdschwartz** [comment]
@thorntonpe I did get several DIFFs while running the test suite:
```
ERS.ELM_USRDAT.I1850CNPRDCTCBC.pm-cpu_gnu.elm-snowveg_arctic (Overall: DIFF) details:
  ERS.ELM_USRDAT.I1850CNPRDCTCBC.pm-cpu_gnu.elm-usrpft_codetest_I1850CNPRDCTCBC (Overall: DIFF) details:
  ERS.ELM_USRDAT.I1850CNPRDCTCBC.pm-cpu_gnu.elm-usrpft_default_I1850CNPRDCTCBC (Overall: DIFF) details:
  ERS.ELM_USRDAT.IELM.pm-cpu_gnu.elm-surface_water_dynamics (Overall: DIFF) details:
  ERS.f09_g16.I1850ELMCN.pm-cpu_gnu.elm-bgcinterface (Overall: DIFF) details:
  ERS.f19_f19.I1850ELMCN.pm-cpu_gnu (Overall: DIFF) details:
  ERS.f19_f19.I20TRELMCN.pm-cpu_gnu (Overall: DIFF) details:
  ERS.f19_g16.I1850ELM.pm-cpu_gnu.elm-betr (Overall: DIFF) details:
  ERS.f19_g16.I1850ELM.pm-cpu_gnu.elm-vst (Overall: DIFF) details:
  ERS_Ln9.ne4pg2_ne4pg2.F2010-MMF1.pm-cpu_gnu.eam-mmf_crmout (Overall: DIFF) details:
  ERS.r05_r05.IELM.pm-cpu_gnu.elm-lnd_rof_2way (Overall: DIFF) details:
  ERS.r05_r05.IELM.pm-cpu_gnu.elm-V2_ELM_MOSART_features (Overall: DIFF) details:
  SMS_Ld1.hcru_hcru.I1850CRUELMCN.pm-cpu_gnu (Overall: DIFF) details:
  SMS_Ly2_P1x1.1x1_smallvilleIA.IELMCNCROP.pm-cpu_gnu.elm-fan (Overall: DIFF) details:
  SMS_Ly2_P1x1.1x1_smallvilleIA.IELMCNCROP.pm-cpu_gnu.elm-force_netcdf_pio (Overall: DIFF) details:
  SMS_Ly2_P1x1.1x1_smallvilleIA.IELMCNCROP.pm-cpu_gnu.elm-per_crop (Overall: DIFF) details:
  SMS.r05_r05.I1850ELMCN.pm-cpu_gnu.elm-qian_1948 (Overall: DIFF) details:
  SMS.r05_r05.IELM.pm-cpu_gnu.elm-topounit (Overall: DIFF) details:
```
Took one and submitted it by itself and it passes, so I can look into this further
```
ERS.ELM_USRDAT.IELM.pm-cpu_gnu.elm-surface_water_dynamics (Overall: PASS) details:
```

**Comment by thorntonpe** [comment]
This is the same behavior I was observing. Thanks for looking into it.

**Comment by peterdschwartz** [comment]
Ok, I can confirm that error is due to the new test `ERS.ELM_USRDAT.I1850CNPRDCTCBC.pm-cpu_gnu.elm-snowveg_arctic` using `MODAL_AER` in `ELM_CONFIG_OPTS`.

When run as a part of the test suite, the EXEROOT for a DIFF'ing test will be set to the new test:
```
EXEROOT: /pscratch/sd/p/pschwar3/IM3_testing/output/ERS.ELM_USRDAT.I1850CNPRDCTCBC.pm-cpu_gnu.elm-snowveg_arctic.C.20240912_133219_khssny/bld
```

The new test's `ELM_CONFIG_OPTS` are:
```
pschwar3@login35: ERS.ELM_USRDAT.I1850CNPRDCTCBC.pm-cpu_gnu.elm-snowveg_arctic.C.20240912_133219_khssny $
 --> ./xmlquery ELM_CONFIG_OPTS
        ELM_CONFIG_OPTS: -phys elm -phys elm -cppdefs -DMODAL_AER
```

But the DIFF'ing tests originally had:
```
pschwar3@login16: SMS_Ly2_P1x1.1x1_smallvilleIA.IELMCNCROP.pm-cpu_gnu.elm-fan.C.20240912_133219_khssny $
 --> ./xmlquery ELM_CONFIG_OPTS
        ELM_CONFIG_OPTS: -phys elm
```

I looked at the tests within the `e3sm_land_exeshare` that those tests all have modal aerosols enabled. So moving the test there should solve the issue.
```
pschwar3@login35: ERS.r05_r05.ICNPRDCTCBC.pm-cpu_gnu.elm-cbudget.C.20240912_133219_khssny $
 --> ./xmlquery ELM_CONFIG_OPTS
        ELM_CONFIG_OPTS: -phys elm -phys elm -cppdefs -DMODAL_AER
```

**Comment by rljacob** [comment]
The discussion above is confusing me especially this part  "When run as a part of the test suite, the EXEROOT for a DIFF'ing test will be set to the new test".

**Comment by peterdschwartz** [comment]
@rljacob In this case, for pm-cpu_gnu, the EXEROOT for `e3sm_land_developer` tests was being set to the test introduced by this PR (new test: `ERS.ELM_USRDAT.I1850CNPRDCTCBC.elm-snowveg_arctic`), but that test uses a compset that has different CPPDEFS than the other tests.  So the other tests will DIFF. 

The EXEROOT seems to be set (or influenced) depending on machine/compiler name so if the EXEROOT is set to a pre-existing test, the tests (except the new test) will share an executable built with the correct CPPDEFs.  That's why testing with this PR and the previous related land PR would give diffs on certain machine/compiler configs but not on others.

**Comment by thorntonpe** [comment]
@peterdschwartz do you have an estimate for when this will be merged to next? I'm giving an update to the NGEE Arctic team later today

**Comment by rljacob** [comment]
We are prioritizing PRs for the v3.0.1 tag this week.  This could go in next week.

**Comment by thorntonpe** [comment]
@peterdschwartz and @bishtgautam I'd like to get this integrated in advance of the 3.1beta bug fixes. Can we move it to the top of the list?

**Comment by peterdschwartz** [comment]
Sure, I don't see why we couldn't.

Note: The PR is still marked BFB, but it may be possible any tests diffs that were blessed from the arctic vegetation test may DIFF as result of this PR moving that test to the correct test suite.

**Comment by thorntonpe** [comment]
@peterdschwartz Thanks, and understood on the movement of tests in the test suite. We'll be watching for those.

**Comment by peterdschwartz** [comment]
merged to next

**Comment by peterdschwartz** [comment]
No unexpected diffs due to this PR as far as I can tell -- A couple of land tests had either a licensing issue or a time out issue.

So I will merge to master and  submit bless requests for the newly added test and the moved tests.

**Pull request merged**
