### PR TITLE
Remove sed usage for specifying batch options; instead set the BATCH_…

### LINKED ISSUE #2395: Problems with run_e3sm
I just tried running run_e3sm.template.csh from today's master (6/12/18) and 
1). acme.exe needs to be replaced with e3sm.exe for using old_executable functionality.
2). something changed in the way this line is handled:

"case.submit --batch-args  --job-name=test --output=batch_output/cori-knl.master.test.ne30_oECv3_ICG.o%j"

which causes that line to fail with this error: 

 "ValueError: invalid interpolation syntax in ' --job-name=test --output=batch_output/cori-knl.master.test.ne30_oECv3_ICG.o%j ' at position 76"

The offending characters are "%j"... when I remove them, case.submit works fine. @cameronsmith1 - do you know what the intention of %j was? @mfdeakin-sandia  and @jgfouca  - do you know what changed in the treatment of this %j?

### PR DESCRIPTION
**Pull request by mfdeakin-sandia**
…COMMAND_FLAGS xml variable for case.run and case.st_archive

Fixes #2395

### CODE REVIEW

**Comment by cameronsmith1** [comment]
This looks good to me.  I am always happy to replace sed commands with something cleaner.

**Comment by mfdeakin-sandia** [comment]
Sorry for the delay in the fix for this; I didn't realize this feature existed until Jim Edwards commented that there was a better way to do this.

**Comment by cameronsmith1** [comment]
The power of teamwork :-).

**Comment by jgfouca** [comment]
+1

**Pull request merged**
