### PR TITLE
mpas-ocean: Do not link petsc unless USE_PETSC is on

### PR DESCRIPTION
**Pull request by jgfouca**
[BFB]

### CODE REVIEW

**Review by amametjanov — APPROVED** [review]

**Comment by jonbob** [comment]
@jgfouca -- I added an entry for MPASO_USE_PETSC, and used it to this branch. However, we'll need changes in CIME as well for it to get picked up and used to set USE_PETSC

**Review by jonbob — APPROVED** [review]
Approved based on testing and visual inspection, though I realize this will require a CIME update as well to be fully integrated

**Comment by rljacob** [comment]
@jgfouca which version of CIME does this need?

**Comment by jgfouca** [comment]
@rljacob , the one I've been trying to bring in for a couple weeks: https://github.com/E3SM-Project/E3SM/pull/5812

**Comment by jgfouca** [comment]
The CIME update is done so I will integrate this.

**Pull request merged**
