### PR TITLE
 GNU Fortran: Wrap boz constant inside intrinsic to fix compilation issue

### PR DESCRIPTION
**Pull request by sarats**
This fixes having to set `-fallow-invalid-boz` flag for gfortran to 
build: wrap a couple of constants with a type-casting intrinsic. 
Also, clean up and remove flag duplicates in mach-specific cmakes.

[BFB]

===
 While looking into https://github.com/E3SM-Project/E3SM/issues/5726, encountered a couple of constants that required `-fallow-invalid-boz` flag for gfortran to build. This fixes that issue without the need for the GNU extension.

cc @rljacob

### CODE REVIEW

**Comment by ndkeen** [comment]
We already have work-arounds for these errors inside Depends.
https://github.com/E3SM-Project/E3SM/pull/4822

However, I never liked that we needed them at all and if casting as `int` works, would be good to do that instead.

**Comment by sarats** [comment]
This is to specifically remove the need for those workarounds. 

For cam_history, I tested the output. The ELM source is a copy/paste of the constant/hash function from cam.
`gen_hash_key_offset = z'000053db' with flag = gen_hash_key_offset = int(z'000053db') = 21467`

**Comment by sarats** [comment]
@rljacob I think this is good to go for testing on next.

**Comment by amametjanov** [comment]
Reproduced the initial build error with `SMS.ne4_oQU240.F2010.pm-cpu_gnu`:
```
/global/u2/a/azamat/saul/E3SM/components/elm/src/biogeochem/MEGANFactorsMod.F90:271:47:

  271 |     integer, parameter :: gen_hash_key_offset = z'000053db'
      |                                               1
Error: BOZ literal constant at (1) is neither a data-stmt-constant nor an actual argument to INT, REAL, DBLE, or CMPLX intrinsic function [see '-fno-allow-invalid-boz']
```
The case builds and runs OK with the updates.
There are additional occurrences of this flag in other gnu cmake files:
```
> grep -ir "fallow-invalid-boz" cime_config/
cime_config/machines/cmake_macros/gnu_anlgce-ub18.cmake:string(APPEND FFLAGS " -fallow-argument-mismatch -fallow-invalid-boz")
cime_config/machines/cmake_macros/gnu_anlgce.cmake:string(APPEND FFLAGS " -fallow-argument-mismatch -fallow-invalid-boz")
cime_config/machines/cmake_macros/gnu_spock.cmake:string(APPEND FFLAGS " -fallow-argument-mismatch -Wno-implicit-interface -fallow-invalid-boz ")
cime_config/machines/cmake_macros/gnu_docker-scream.cmake:  string(APPEND FFLAGS " -fallow-argument-mismatch  -fallow-invalid-boz ")
cime_config/machines/cmake_macros/gnu_eddi.cmake:  string(APPEND FFLAGS " -fno-unsafe-math-optimizations -fallow-argument-mismatch -fallow-invalid-boz")
cime_config/machines/cmake_macros/gnu_eddi.cmake:  string(APPEND FFLAGS " -g -fbacktrace -fbounds-check -ffpe-trap=invalid,zero,overflow -fallow-argument-mismatch -fallow-invalid-boz -Wall")
```
@sarats can I push a cleanup of these remaining flags to your branch?

**Comment by sarats** [comment]
@amametjanov Sure, go ahead.

**Review by amametjanov — APPROVED** [review]
Thanks. Done.

**Pull request merged**
