### PR TITLE
fix calculation of the ML-averaged Brunt-Vaisala frequency

### PR DESCRIPTION
**Pull request by alicebarthel**
This PR is correcting a bug in the calculation of the mixed-layer-averaged Brunt-Vaisala frequency
Changes included:
 1. Bug fix: corrected last layer thickness to partial in bruntVaisalaFreqML calculation
 2. Minor tweak: fetch index_temp as best practice (instead of assuming index_temp=1)
@vanroekel agreed this was a bug
@xylar read through the changes

Testing:
Following @xylar's suggestions, I ran the **compass nightly** and **PR** test suites on the new branch (with E3SM-Project/E3SM master as the baseline). 

**All tests passed**, except for the PHC_analysis_test, which returned the expected result in the log, i.e. that the **bruntVaisalaFreqML** variable in mixedLayerHeatBudget.0001-01-01.nc is different across both branches: 
20211221.mpaso.master.pr.anvil/ocean/global_ocean/QU240/PHC/analysis_test/forward/analysis_members/mixedLayerHeatBudget.0001-01-01.nc
bruntVaisalaFreqML  Time index: 0, 1, 2, 3
0: l1: 1.39087854710057e-01 l2: 3.78211615308643e-03 linf: 4.73636383462982e-04
1: l1: 1.43059632404768e-01 l2: 4.07490791830357e-03 linf: 5.16298006610050e-04
2: l1: 1.30955216565953e-01 l2: 3.95262852740002e-03 linf: 5.22962151300133e-04
3: l1: 1.16779244836792e-01 l2: 3.76342985792116e-03 linf: 5.19467445683437e-04

The log also reports some changes in speed (-20-20% range) when comparing timer of various compute/write steps, but small changes do not raise any concerns for me. Let me know if that is something that should be of concern. 
The tests were all run on anvil with the intel-mpi compiler.

[BFB]

### CODE REVIEW

**Review by vanroekel — APPROVED** [review]
approving by visual inspection and developer testing.

Thanks for the fix @alicebarthel!

**Comment by xylar** [comment]
@jonbob or @mark-petersen, could one of you recommend an E3SM test (baseline and comparison) that would exercise this analysis member?  I'd like to complement the compass testing with some E3SM testing as part of my review.

**Review by mark-petersen — APPROVED** [review]
Thanks @alicebarthel. Approving by visual inspection. I don't understand what the `difference` variable is, but your change follows the lines above, so if you and @vanroekel  agree with this correction, then I'm comfortable with it.

**Comment by mark-petersen** [comment]
@alicebarthel could you correct this comment line 273:
```
            !need the clearn up of how much is left to get to MLD mld - depth
            depth = depth - layerThickness(k, iCell)
            difference = dThreshMLD(iCell) - depth
```
I'm not sure if that supposed to be `clean up` or something else. @vanroekel do you know?

**Comment by mark-petersen** [comment]
@xylar said:
> could one of you recommend an E3SM test (baseline and comparison) that would exercise this analysis member? I'd like to complement the compass testing with some E3SM testing as part of my review.

This AM is on for all E3SM runs. See:
```
components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml:961:
<config_AM_mixedLayerHeatBudget_enable>.true.</config_AM_mixedLayerHeatBudget_enable>
```
Looking at a standard E3SM namelist mpaso_in
```
805 &am_mixedlayerheatbudget
806  config_am_mixedlayerheatbudget_compute_interval = '0000-00-00_01:00:00'
807  config_am_mixedlayerheatbudget_compute_on_startup = .false.
808  config_am_mixedlayerheatbudget_enable = .true.
809  config_am_mixedlayerheatbudget_output_stream = 'mixedLayerHeatBudgetOutput'
810  config_am_mixedlayerheatbudget_write_on_startup = .false.
811 /
```
and streams.ocean file:
```
398 <stream name="mixedLayerHeatBudgetOutput"
399         type="output"
400         precision="single"
401         io_type="pnetcdf"
402         filename_template="20211207.triskCV-test1.GMPAS-IAF.T62_EC30to60E2r2.cori-haswell.mpaso.hist.am.mixedLayerHeatBudget.$Y-$M-$D.nc"
403         filename_interval="00-01-00_00:00:00"
404         reference_time="01-01-01_00:00:00"
405         output_interval="none"
406         clobber_mode="truncate"
407         packages="mixedLayerHeatBudgetAMPKG">
408
409     <var name="xtime"/>
410     <var name="activeTracerForcingMLTend"/>
411     <var name="activeTracerHorMixMLTend"/>
412     <var name="activeTracerNonLocalMLTend"/>
413     <var name="activeTracerVertAdvectionMLTend"/>
414     <var name="activeTracerHorAdvectionMLTend"/>
415     <var name="activeTracerVertMixMLTend"/>
416     <var name="activeTracersML"/>
417     <var name="bruntVaisalaFreqML"/>
418     <var name="activeTracersTendML"/>
419 </stream>
```
but `output_interval="none"` so it never writes out. You could run any standard test, say on cori
```
./create_test SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu -q debug --walltime 00:30:00
or
./create_test -p e3sm -q debug --walltime 00:30:00 SMS_D_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
```
but change the `output_interval` on that stream to daily and compare the mixed layer budget output file.

**Comment by jonbob** [comment]
@xylar - sorry to take so long getting back to you. I'm guessing you are looking for a test in the suite that you could run that would automatically compare with the blessed results? So I was trying to understand which of our analysis members have their results compared as part of the automated testing, and how those files are selected. I'm still confused, but as far as I can tell this AM is not compared by default. I'll keep digging...

**Comment by xylar** [comment]
@jonbob, @mark-petersen's response is good enough for me to work with.  It sounds like the analysis member is on but not written out in any tests, so I'll just need to turn it on and compare myself.  That's fine.

**Comment by jonbob** [comment]
Sounds good, @xylar

**Comment by mark-petersen** [comment]
To provide more information, the _instantaneous_ stream for this PR is off in E3SM. That is intentional, as we don't use the instantaneous data for analysis. See here:
https://github.com/E3SM-Project/E3SM/blob/679cebf91bcbd032351e429293333eb395ecb0d3/components/mpas-ocean/cime_config/buildnml#L827
https://github.com/E3SM-Project/E3SM/blob/679cebf91bcbd032351e429293333eb395ecb0d3/components/mpas-ocean/cime_config/buildnml#L834

However, the variables computed by this analysis member are included in the monthly averages, here:
https://github.com/E3SM-Project/E3SM/blob/679cebf91bcbd032351e429293333eb395ecb0d3/components/mpas-ocean/cime_config/buildnml#L1066
https://github.com/E3SM-Project/E3SM/blob/679cebf91bcbd032351e429293333eb395ecb0d3/components/mpas-ocean/cime_config/buildnml#L1404-L1409

These variables are do not feed back into the E3SM model, as can be seen with a `git grep MLTend`.

For the purpose of testing these AMs, there are a few options (this is out of scope for this PR, but this AM is a convenient example, so bear with me)
1. Rely on compass for BFB testing before/after, BFB partition, BFB restart. (This is what we do now)
2. In addition to 1, add an E3SM test that writes out many instantaneous AM fields after a short time (days) and compares them
3. _or_ in addition to 1, run an E3SM test for a month and compare the monthly average fields.

I would propose to continue with 1 only, as this has not caused problems to date. Potential problems are that E3SM machines or configurations not covered by COMPASS could go unnoticed. The difficulty with 2 and 3 above is that E3SM testing compares coupler files, not ocean output files, and a monthly run for 3 is long for regular testing. For 2, we would need to add an additional 'AM testing comp set' to provide logic for the buildnml file to write and compare the instantaneous output.

**Comment by xylar** [comment]
@mark-petersen, I would propose a 4th option, similar to what we do in compass.  That would be to make a test in which the same variables used in monthly averages for production runs are instead added to daily averages.  Then, just run for one day and compare outputs.

However, I am pretty ignorant of E3SM testing so I don't know if:
1. a setup qualitatively different from production runs like I propose is supported and
2. there would be a way to compare the daily averaged output (it sounds like not from your comment about only looking at coupler output)

If this isn't possible, it seems like E3SM testing has some pretty serious limitations that should be relaxed in the future.

**Comment by jonbob** [comment]
@mark-petersen - I'm sorry, but E3SM testing does compare more than just cpl history files. In fact, it runs cprnc on many component output files -- here's example output from a test log:
```
2021-12-16 05:59:58: Comparing hists for case 'SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod.C.JNextProd20211216_023930' dir1='/compyfs/e3smtest/e3sm_scratch/SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod.C.JNextProd20211216_023930/run', suffix1='',  dir2='/compyfs/e3sm_baselines/intel/master/SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod' suffix2=''
  comparing model 'eam'
    SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod.C.JNextProd20211216_023930.eam.h0.0001-01-02-00000.nc matched eam.h0.0001-01-02-00000.nc
    SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod.C.JNextProd20211216_023930.eam.h1.0001-01-01-00000.nc matched eam.h1.0001-01-01-00000.nc
    SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod.C.JNextProd20211216_023930.eam.h2.0001-01-01-00000.nc matched eam.h2.0001-01-01-00000.nc
    SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod.C.JNextProd20211216_023930.eam.h3.0001-01-01-00000.nc matched eam.h3.0001-01-01-00000.nc
    SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod.C.JNextProd20211216_023930.eam.h4.0001-01-01-00000.nc matched eam.h4.0001-01-01-00000.nc
    SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod.C.JNextProd20211216_023930.eam.h5.0001-01-01-00000.nc matched eam.h5.0001-01-01-00000.nc
    SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod.C.JNextProd20211216_023930.eam.h6.0001-01-02-00000.nc matched eam.h6.0001-01-02-00000.nc
  comparing model 'elm'
    SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod.C.JNextProd20211216_023930.elm.h0.0001-01-02-00000.nc matched elm.h0.0001-01-02-00000.nc
    SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod.C.JNextProd20211216_023930.elm.h1.0001-01-01-00000.nc matched elm.h1.0001-01-01-00000.nc
  comparing model 'mpassi'
    SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod.C.JNextProd20211216_023930.mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc.base matched mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc.base
  comparing model 'mpaso'
    SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod.C.JNextProd20211216_023930.mpaso.hist.am.globalStats.0001-01-01.nc.base matched mpaso.hist.am.globalStats.0001-01-01.nc.base
  comparing model 'mosart'
    SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod.C.JNextProd20211216_023930.mosart.h0.0001-01-02-00000.nc.base matched mosart.h0.0001-01-02-00000.nc.base
    SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.compy_intel.allactive-wcprod.C.JNextProd20211216_023930.mosart.h1.0001-01-02-00000.nc.base matched mosart.h1.0001-01-02-00000.nc.base
```
It does not require month-long tests to get mpaso-specific output files to compare, and I'm sure we can include other mpas output in the testing if we need to.

**Comment by mark-petersen** [comment]
@jonbob thanks, I should have known that. It sounds like there are options for testing analysis member output in an E3SM test, either instantaneous or with a short time-average. Let's take the conversation to a new issue, so this PR can proceed.

**Comment by xylar** [comment]
## Testing

I created a baseline from the commit that this branch is based off of: 89d472679b
I edited 
https://github.com/E3SM-Project/E3SM/blob/679cebf91bcbd032351e429293333eb395ecb0d3/components/mpas-ocean/cime_config/buildnml#L834
to be:
```
        lines.append('        output_interval="00-00-01_00:00:00"')
```
I ran:
```
/create_test SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel -g -b fix-mld-heat-budget_20220106 --baseline-root /lcrc/group/e3sm/ac.xylar/e3sm_baselines/ --wait
```

For comparison, I made the same edit on this branch and ran:
```
/create_test SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel -c -b fix-mld-heat-budget_20220106 --baseline-root /lcrc/group/e3sm/ac.xylar/e3sm_baselines/ --wait
```

To my surprise, there were many more diffs that just in `bruntVaisalaFreqML`. See the following files in `/lcrc/group/e3sm/ac.xylar/scratch/chrys/SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel.C.20220106_063757_p26q53`:
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel.C.20220106_063757_p26q53.cpl.hi.0001-01-06-00000.nc.cprnc.out
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel.C.20220106_063757_p26q53.mpaso.hist.am.mixedLayerHeatBudget.0001-01-01.nc.base.cprnc.out
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel.C.20220106_063757_p26q53.mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc.base.cprnc.out
```
I am not at all familiar with these files but I understand them to show differences in many, many variables, too many to list here.

I could use some help understanding if I've done something wrong or if @alicebarthel's changes have had unintended consequences somehow.

**Comment by jonbob** [comment]
@xylar - I can do a similar thing, except test with master against a merge of this PR, if that helps

**Comment by xylar** [comment]
@jonbob, thanks, that would be super helpful.

**Comment by jonbob** [comment]
@xylar - I checked out master and ran the same test case you did, then merged this branch in and ran a second test. Running cprnc by hand, I saw only the differences I would expect (bruntVaisalaFreqML in the mixedLayerHeatBudget file) and everything else was BFB. So I can only think of two possible issues that might have caused the discrepancy in our results: 1. the baseline creation or 2. something in the difference between your baseline source code and the branch. I'll redo my test by making baselines like you did, just to rule that out.

**Comment by jonbob** [comment]
@xylar - there was a third option I hadn't considered, which was the platform. I had tested on anvil and you were using chrysalis. When I moved to chrysalis I saw the same failure you documented, but only in debug mode. So once again I'm confused -- apparently it's fine (meaning the DIFFs are exactly what we expect) on anvil for both debug and optimized and on chrysalis running optimized. But something causes more DIFFs only in debug and only on chrysalis.

**Comment by vanroekel** [comment]
@mark-petersen the `difference` variable is the thickness greater than the last layer in the mixed layer and the mixed layer depth itself.  and the comment should indeed by 'clean up'  I basically was writing that we need to add the contribution from that last little chunk of the mixed layer.

@xylar and @jonbob I'm a little confused by the later massive back and forth on a really simple PR.  Could one of you please confirm if this debug on chrysalis issue only occurs with this branch and not with master?  If that is true, I'd suggest reverting the index_temperature change.  It seems to me that is the only thing that could cause diffs in numerous variables.

**Comment by xylar** [comment]
@jonbob, I ran the following on the same test on `E3SM/master` both to generate the baseline and to do the comparison, and I'm seeing basically the same diffs. See:
```
/lcrc/group/e3sm/ac.xylar/scratch/chrys/SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel.C.20220107_044124_46tgck
```
  That's really odd, but unrelated to this PR.  It's just making it hard to test this PR.  I'll try testing the PR again but this time dropping debug mode.

**Review by xylar — APPROVED** [review]
When in run the test:
```
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
```
on a merge of this branch into `E3SM/master` and compare with `E3SM/master`, I see only the expected changes in `bruntVaisalaFreqML`.

I also printed out `index_temperature` and verified that it is always 1, as expected.

I think this is good to go and my trouble with testing was unrelated to this PR, as I said above.

**Comment by vanroekel** [comment]
Just to update this PR based on a slack discussion.  I wanted to be clear that my comment above should not be taken as being against the long discussion here and the extensive testing.  Just more surprised that a small PR like this would cause it, but illustrates no PR is too small to skip testing!  Thanks to @jonbob and @xylar for digging into this so deeply and exposing issues in this PR and potentially broader testing related issues.

Also @alicebarthel or @mark-petersen let me know if you want me to fix that comment in the code flagged above.

**Comment by jonbob** [comment]
passes BFB tests with master on chrysalis, merged to next

**Comment by jonbob** [comment]
Ran the tests with active ocean that failed last night on chrysalis using next. The following tests passed:
* ERP_Ld3.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-pioroot1 
* SMS_D_Ld1.ne30pg2_r05_EC30to60E2r2.WCYCL1850.chrysalis_intel
* ERS.ne11_oQU240.WCYCL1850NS.chrysalis_intel
* SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod
* PEM_Ln9.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel
So I think this PR is OK

**Comment by jonbob** [comment]
merged to master

**Comment by xylar** [comment]
Thanks @jonbob!  And congratulations, @alicebarthel, on our first E3SM PR!

**Pull request merged**
