### PR TITLE
Keziming/atm/chem uci chem mzt amip mam5

### PR DESCRIPTION
**Pull request by keziming**
This branch is to add in MAM5 full chemistry option into E3SM-V2 based on chemUCI branch

### CODE REVIEW

**Comment by rljacob** [comment]
Is this a v3 feature?

**Comment by keziming** [comment]
Yes.
My work email is ***@***.***
Not sure why it goes to my personal email.


BEST WISHES!
Ziming Ke

**Comment by rljacob** [comment]
discussion:  not certain this will go in.

**Comment by keziming** [comment]
@rljacob I plan modify this PR to merge into master after the chemUCI merging into master. This MAM5 version is based upon chemUCI. Not sure that if chemUCI is merged nor not.

**Comment by rljacob** [comment]
Will have a new PR for this feature.

**Pull request closed without merging**
