### PR TITLE
Adds support for co2 vertical interpolation

### PR DESCRIPTION
**Pull request by singhbalwinder**
The code changes introduced via  7fbec4f
facilitated horizontal interpolation but was missing the vertical
interpolation.

I have created a dummy state variable so that the interpolation
routines can read interface (or mid point) heights from the state
to enable vertical interpolation.

co2 tracer can be enabled only if we add -co2_cycle to
CAM_CONFIG_OPTS in env_build.xml file. To enable bi-linear
interpolation, we also need to add -cppdefs -DCO2_BILIN_REGRID
to CAM_CONFIG_OPTS in env_build.xml file.

[BFB] - Bit-For-Bit

### CODE REVIEW

**Comment by beharrop** [comment]
Thanks @singhbalwinder for working on this.  I have a question about your implementation.  Does using state_at_init in the advance_trcdata call mean that we are using the pressure levels at initialization to do the interpolation?  Maybe I am missing something, but I would have thought at each time step, we would want to use the current pressure levels to read in and interpolate the next emission entry.

**Comment by singhbalwinder** [comment]
You are right. We need the current state vector to do the interpolation. I will look into the code to see if we can send in the current state vector and modify the code accordingly.

**Comment by beharrop** [comment]
The new commits to handle the grids and error checking look OK to me, @singhbalwinder

**Comment by rljacob** [comment]
@singhbalwinder is this ready?

**Comment by singhbalwinder** [comment]
We are still working on testing an alternative algorithm for interpolation. it may take some time to fully implement it and test it in various scenarios. This PR will have no impact on the WCYCL experiments. It only affects the BGC experiments.

**Comment by rljacob** [comment]
Any further progress on this PR?  I know its not v2 but it is almost 2 months old.

**Comment by rljacob** [comment]
@singhbalwinder what is up with this old PR?

**Comment by singhbalwinder** [comment]
Closing this PR util it is ready.

**Pull request closed without merging**
