### PR TITLE
Update machine files for LANL IC machines badger and grizzly

### PR DESCRIPTION
**Pull request by jonbob**
This PR updates machine and compiler settings for LANL IC machines grizzly and badger. It reflects the new modules made available by the LANL HPC group, with many thanks to Jennifer Green. There is a similar PR for master (#3554).

No testing is performed on these machines, so the changes will not impact test results. However, it will likely change answers on cases run on these machines due to new compiler versions.

[BFB]

### CODE REVIEW

**Comment by stephenprice** [comment]
Overall, this looks good to me Jon. One thing I don't follow is why it looks like we changed the entry for the "modex" machine. I'm pretty sure we didn't do anything there but just flagging it in case.

**Comment by stephenprice** [comment]
I'm guessing you are ok to do the merge but let me know.

**Comment by jonbob** [comment]
Ah, my bad -- the cherry-pick wasn't completely clean and I brought the "modex" stuff in when I did the hand merging. Let me clean that up...

**Comment by jonbob** [comment]
Thanks for the catch, @stephenprice. I've cleaned up (I hope). Once you review this PR, it's your call when I merge it to maint-1.2

**Comment by stephenprice** [comment]
There's still something weird in the compilers config file. For badger / intel, I see this for the entry that we tested:
```
<compiler MACH="badger" COMPILER="intel">
  <PIO_FILESYSTEM_HINTS>lustre</PIO_FILESYSTEM_HINTS>
  <MPICC  MPILIB="impi">mpiicc</MPICC>
  <MPICXX MPILIB="impi">mpiicpc</MPICXX>
  <MPIFC  MPILIB="impi">mpiifort</MPIFC>
  <MPICC  MPILIB="!impi">mpicc</MPICC>
  <MPICXX MPILIB="!impi">mpic++</MPICXX>
  <MPIFC  MPILIB="!impi">mpif90</MPIFC>
  <SFC>ifort</SFC>
  <SCC>icc</SCC>
  <SCXX>icpc</SCXX>
  <SLIBS>
    <append>$SHELL{$ENV{NETCDF_ROOT}/bin/nc-config --libs}</append>
    <append>$SHELL{$ENV{NETCDF_ROOT}/bin/nf-config --flibs} -lnetcdff -llapack -lblas</append>
    <append>-mkl -lpthread</append>
  </SLIBS>
  <CXX_LIBS>
    <base>-lstdc++ -lmpi_cxx</base>
  </CXX_LIBS>
  <NETCDF_C_PATH>$ENV{NETCDF_ROOT}</NETCDF_C_PATH>
  <NETCDF_FORTRAN_PATH>$ENV{NETCDF_ROOT}</NETCDF_FORTRAN_PATH>
  <PNETCDF_PATH>$ENV{PNETCDF_ROOT}</PNETCDF_PATH>
</compiler>
```

The committed file here looks like it has some extra lines starting after the /CXX_LIBS near the bottom (lines 2153 - 2164 in the new file). 

Am I seeing that wrong?

I'm going to check of the config_machines.xml a bit more carefully here too.

**Comment by stephenprice** [comment]
Also just checking, but in that version of master that I tested on, there was still an entry for the machine "modex" in the config_compilers file. Now. it's gone, but it looks like it's still there on current master.

**Comment by stephenprice** [comment]
shoot ... that 'close' was a bad mouse placement. sorry about that! re-opened ...

**Comment by jonbob** [comment]
no problem. OK, all that threading stuff did show back up. I'll get rid of it as well -- I don't think it's bad, but we don't tend to run with threading on

**Comment by stephenprice** [comment]
Where is that stuff coming from? It should have been removed by my commits. Did it get merged back in somehow?

**Comment by jonbob** [comment]
It was from when I was doing the cherry-pickin'. There were conflicts in the merging and I left settings in instead of removing them, just erring on the side of not getting rid of anything.

**Comment by stephenprice** [comment]
I see. Ok, I looked over again and everything looks ok, BUT the support for "modex" has been removed from the compilers file. I don't see a "modex" in the machines file, so maybe that should be removed, but just checking to make sure.

**Comment by jonbob** [comment]
OK, I checked and no mention of modex now in this codebase. I looked at the head on maint-1.2 and that matches -- no modex there. It is a machine on master, so I think we just had grabbed it from there. So I hope this is clean now and good to go

**Comment by stephenprice** [comment]
Ahh, ok. That makes sense. I guess I will sign off on it then. Thanks for putting this on your to-do list for us!

**Comment by jonbob** [comment]
merged to maint-1.2

**Pull request merged**
