### PR TITLE
Fix extra coupler restart read and add more log info

### LINKED ISSUE #4513: Restart files are read back in again right after being written out, unnecessarily
In cime_comp._mod.F90 is the following code:

       !----------------------------------------------------------
       !| Write driver restart file
       !----------------------------------------------------------
       call cime_run_write_restart(drv_pause, restart_alarm, drv_resume)

...

       !----------------------------------------------------------
       !| RESUME (read restart) if signaled
       !----------------------------------------------------------
       if (len_trim(drv_resume) > 0) then
          if (iamroot_CPLID) then
             write(logunit,103) subname,' Reading restart (resume) file ',trim(drv_resume)
             call shr_sys_flush(logunit)
          end if
          if (iamin_CPLID) then
             call seq_rest_read(drv_resume, infodata,                          &
                  atm, lnd, ice, ocn, rof, glc, wav, esp, iac,                 &
                  fractions_ax, fractions_lx, fractions_ix, fractions_ox,      &
                  fractions_rx, fractions_gx, fractions_wx, fractions_zx)
          end if
          ! Clear the resume file so we don't try to read it again
          drv_resume = ' '
       end if

In a 1 month initial run (with restart write), the restart files are read back in immediately after being written out, after which the job ends. Also occurs for a continuation run. For a 2 month initial run with restart writes every month, the restart files are read back in immediately after being written out each time (twice, once per month). So, perhaps this is needed to verify the restart write? If not, does it makes sense to read it back in right before the job ends?

### PR DESCRIPTION
**Pull request by rljacob**
Make drv_resume a logical and set it to FALSE to prevent read of restart immediately after it is written.
Introduce drv_resume_file to use where a filename is really needed.

Also add a log message for the real restart read and make the seq_io_read_avs log messages more informative.

Fixes #4513

### CODE REVIEW

**Comment by worleyph** [comment]
@rljacob , I am in the process of reviewing. Does this match the current branch naming policy? I would have thought that it needed to be rljacob/driver/fix-extra-read or something similar?

**Comment by worleyph** [comment]
@rljacob , do you want to make similar changes to seq_io_write_avscomp that you made to seq_io_read_avscomp, i.e. fix routine header comment and subname?

**Comment by rljacob** [comment]
The branch name is close enough.  I'll fix seq__io_write in the PR for the history write bug.

**Comment by worleyph** [comment]
@rljacob , why the addition of the blank line at line 696 in come_comp_mod.F90?

**Comment by worleyph** [comment]
@rljacob, for consistency with the ordering of format statements in the rest of the file, please place the new format statement at line 1382 in cime_comp_mod.F90:

     103 format( 5A )     

before the existing format statement:

     104 format( A, i10.8, i8)

(so that they are 103, followed by 104). Also, please delete the extra white space at the end of format statement 103.

**Comment by worleyph** [comment]
@rljacob, I do not see any logic to ever set drv_resume to .TRUE., so this PR just disables the code in question?

**Comment by worleyph** [comment]
@rljob, please remove white space to the left of 'Driver' in comment in declaration of drv_resume (line 2425)

     logical               :: drv_pause            ! Driver writes pause restart file
     logical               :: drv_resume           !  Driver resets state from restart file 
     character(len=CL)     :: drv_resume_file      ! the restart file

and maybe capitalize 'the' in the comment for drv_resume_file, to be consistent with the other comments?

(Sorry for initial posting in the wrong location.)

**Comment by rljacob** [comment]
Yes this PR just disables.  I'm not sure yet that we just want to remove it.  I'll fix the rest.

**Comment by rljacob** [comment]
@worleyph you can re-review if you want.

**Comment by worleyph** [comment]
@rljacob , one final suggestion (sorry that I did not catch this the first time through). When changing drv_resume to drv_resume_file in calls to seq_rest_read and seq_resume_store_comp, the continuation '&' was pushed out of alignment with the following lines:

(line 3358 in cime_comp_mod.F90)

               call seq_resume_store_comp('x', drv_resume_file, 1,                      &
                    driver_id, iamroot_CPLID)
               call component_run(Eclock_e, esp, esp_run, infodata,                &


(line 3425 in cime_comp_mod.F90)

                  call seq_rest_read(drv_resume_file, infodata,                          &
                       atm, lnd, ice, ocn, rof, glc, wav, esp, iac,                 &
                       fractions_ax, fractions_lx, fractions_ix, fractions_ox,      &
                       fractions_rx, fractions_gx, fractions_wx, fractions_zx)

Please eliminate some of the white space to bring these back into alignment,

**Review by worleyph — APPROVED** [review]
Ran both initial and continuation run 2 month water cycle case experiments with restart writes monthly, and the erroneous 'resume' restart reads were eliminated. The modifications to the logging information also showed up correctly. Manually re-enabled resume restart reads, and these continued to "work" as they had in the unmodified code, so the underlying capability still exists. Visual inspection of the code looks good, with one minor remaining clean-up suggestion made.

**Pull request merged**
