### PR TITLE
Change hi-res tests to use the v3 grid configurations

### PR DESCRIPTION
**Pull request by jonbob**
The current high-resolutions tests use older grid configurations. This updates the tests to use the new RRSwISC6to18E3r5 mesh as well as r025 for trigrid tests.

[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
@rljacob -- I didn't test this yet. It looks like the e3sm_hi_res suite runs on pm-cpu, so I can try that

**Review by amametjanov — APPROVED** [review]

**Comment by jonbob** [comment]
A quick test running:
````
./create_test e3sm_hi_res
````
successfully built and submitted two of the tests. The third, 
````
SMS.ne120pg2_r025_RRSwISC6to18E3r5.WCYCL1950.pm-cpu_intel.eam-cosplite
````
failed in setup due to:
````
       ERROR : CLM build-namelist::ELMBuildNamelist::add_default() : No default value found for fsurdat.
````

**Comment by ndkeen** [comment]
I tried `SMS.ne120pg2_r025_RRSwISC6to18E3r5.WCYCL1850.pm-cpu_intel.eam-cosplite` (ie using 1850 instead) and it does build.  But looks like missing some files that are not on blues.

```
        Model elm no file specified for finidat
        svn export failed with output:  and errput svn: E170000: URL 'https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/cpl/gridmaps/ne120pg2/map_r025_to_ne120pg2_traave.20240328.nc' doesn't exist
        
        svn export failed with output:  and errput svn: E170000: URL 'https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/cpl/gridmaps/ne120pg2/map_r025_to_ne120pg2_trbilin.20240328.nc' doesn't exist
        
        svn export failed with output:  and errput svn: E170000: URL 'https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/share/domains/domain.lnd.r025_RRSwISC6to18E3r5.240328.nc' doesn't exist
```

**Comment by jonbob** [comment]
Thanks @ndkeen -- let me track down those files

**Comment by rljacob** [comment]
Go ahead and switch that test to 1850 .

**Comment by jonbob** [comment]
@ndkeen -- is that from master? I don't see those files in config_grids

**Comment by jonbob** [comment]
Two of the three tests ran successfully on pm-cpu but this one:
````
SMS.ne120pg2_r025_RRSwISC6to18E3r5.WCYCL1850.pm-cpu_intel.eam-cosplite
````
fails because we don't have default spunup ocn/ice ICs. We can either add a default set of IC files temporarily or try testing with WCYCL1850NS

**Comment by rljacob** [comment]
Using 1850NS would be ok.

**Comment by jonbob** [comment]
OK, I've submitted a test of:
````
SMS.ne120pg2_r025_RRSwISC6to18E3r5.WCYCL1850NS.pm-cpu_intel.eam-cosplite
````
If it runs successfully, I'll change the test in this PR to match

**Comment by jonbob** [comment]
The most recent test,
````
SMS.ne120pg2_r025_RRSwISC6to18E3r5.WCYCL1850NS.pm-cpu_intel.eam-cosplite
````
ran OK but timed out after three days. Trying now with SMS_Ld3

**Comment by jonbob** [comment]
Passes:
SMS_Ld3.ne120pg2_r025_RRSwISC6to18E3r5.WCYCL1850NS.pm-cpu_intel.eam-cosplite

Modified test to run for three days

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
