### PR TITLE
Make lnd build using CMake!

### PR DESCRIPTION
**Pull request by jgfouca**
Includes some minor fixes and cleanups for atm.

[BFB]

### CODE REVIEW

**Comment by jgfouca** [comment]
This seems to validate my theory that, once we got cam working, all other components that use the CIME Makefile are easy to convert to CMake. This would have been very easy if it were not for the dependency issue with bshr_assert_mod.

**Comment by jgfouca** [comment]
@bishtgautam , on melvin, this PR is flag-for-flag identical (with a couple minor exceptions) to master and BFB with master. I'd like to merge to next if you approve. I suspect this integration to go smoothly since most of the issues were already worked-out in the previous atm cmake PR.

**Comment by bishtgautam** [comment]
I'm waiting to hear back from @jinyuntang if my suggested changes to SBeTR are acceptable to him.

**Comment by jgfouca** [comment]
@bishtgautam , oh, I didn't realize you wanted to do that right away. That would be nice since it would allow us to remove some ugliness from the CMake file.

**Comment by jgfouca** [comment]
@bishtgautam, I'd like to keep my momentum on this cmake stuff, so if it's going to take a while to clean up sbetr, I'd prefer to just handle that in a later PR.

**Comment by bishtgautam** [comment]
@jgfouca I agree. I will approve this PR and we will fix SBeTR later.

**Comment by jgfouca** [comment]
Merged to next.

**Pull request merged**
