### PR TITLE
define new GMPAS, GPMAS, ECO compsets with JRA

### PR DESCRIPTION
**Pull request by maltrud**
Define new compset aliases that support marine BGC using JRA1.4 forcing.  Also allow GPMPAS configurations (with active ELM and MOSART) to work with WC14to60E2r3, EC30to60E2r2, and ARRM10to60E2r1 grids.

Fixes [#6209](https://github.com/E3SM-Project/E3SM/issues/6209) 

Fixes [#6208](https://github.com/E3SM-Project/E3SM/issues/6208)

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
notes:  Jon will work on.  Depends on conversation on supporting lots of compsets in bgc.

**Comment by jonbob** [comment]
@maltrud -- is there a reason to add aliases for all three flavors of JRA forcing? I think there will be a push for us to have more like representative compset aliases with the understanding that a more full list is accessible through compset long-names. Of course, it's also fine to just merge this as-is and think about changing which ones we keep in a later compset alias reduction PR

**Comment by maltrud** [comment]
@jonbob yes I'm fine with reducing the number of compsets with aliases--it is already getting out of hand.  just one flavor of JRA, and also (maybe?) no need for OECO.

**Comment by jonbob** [comment]
@maltrud -- OK, I just left the JRA1p4 versions of the new compsets, since JRA1p5 has issues right now. We can update that later if it becomes preferable

**Review by jonbob — APPROVED** [review]
Verified that all new files are available on the inputdata repo, and passes sanity testing.

**Comment by jonbob** [comment]
merged to next

**Comment by rljacob** [comment]
Are all the files in the right flavor of NetCDF?

**Comment by jonbob** [comment]
@rljacob -- I'll double-check that and fix them if not

**Comment by jonbob** [comment]
Thanks @rljacob -- good catch. They're converted and checked on the inputdata server as well as the local lcrc inputdata location.

merged to master

**Pull request merged**
