### PR TITLE
update mpas-source: cleanup of ocean split-explicit driver

### PR DESCRIPTION
**Pull request by mark-petersen**
This is a significant cleanup of the ocean split-explicit time integration driver to prepare for future GPU and other performance changes. See https://github.com/MPAS-Dev/MPAS-Model/pull/781

[non-BFB] on Intel w/ optimizations

### CODE REVIEW

**Comment by mark-petersen** [comment]
@philipwjones and @mattdturner, this is scheduled to be merged Monday. Could you test the head of this PR again as a final check?

**Comment by mark-petersen** [comment]
Passes:
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
```

**Comment by mattdturner** [comment]
@mark-petersen I'm testing on Compy and Anvil right now.  I'll post results as soon as the tests finish

**Comment by mattdturner** [comment]
```
PASS:
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi.C
  - PASS SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi BASELINE /compyfs/e3sm_baselines/pgi
/master:
```

It doesn't look like my Anvil runs are going to start anytime soon, but I believe the compy_pgi tests are sufficient

**Comment by mark-petersen** [comment]
Rebased. This is ready.

**Review by jonbob — APPROVED** [review]
Approved by visual inspection and developer testing

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
@mark-petersen, @mattdturner - this was not BFB on intel. Should it be reverted?

**Comment by rljacob** [comment]
Only the cases with oECv3 had diffs.  These tests were still BFB.
ERS.ne11_oQU240.A_WCYCL1850.sandiatoss3_intel
ERS_Ld5.T62_oQU120.CMPASO-NYF.sandiatoss3_intel
NCK.ne11_oQU240.A_WCYCL1850.sandiatoss3_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.sandiatoss3_intel
SMS_P12x2.ne4_oQU240.A_WCYCL1850.sandiatoss3_intel.allactive-mach_mods

**Comment by mattdturner** [comment]
I'm not familiar enough with the differences between the QUXXX and ECv3 configurations, or how that impacts the portions of code that are run to comment on why some tests would pass and others fail.  @mark-petersen do you have any thoughts/

**Comment by mark-petersen** [comment]
This is the only on/off flag change I see between QU and EC tests:
```
components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
 53 <!-- hmix -->
 55 <config_hmix_scaleWithMesh ocn_grid="oQU240">.false.</config_hmix_scaleWithMesh>
 57 <config_hmix_scaleWithMesh ocn_grid="oQU120">.false.</config_hmix_scaleWithMesh>
 59 <config_hmix_scaleWithMesh ocn_grid="oEC60to30v3">.true.</config_hmix_scaleWithMesh>
```
all others are values of time step or viscosity, so are not likely to cause a bfb difference. Let me see how this PR interacted with that flag.

@mattdturner or @philipwjones could you run a bfb comparison of a failed EC test with
```
 59 <config_hmix_scaleWithMesh ocn_grid="oEC60to30v3">.false.</config_hmix_scaleWithMesh>
```
We don't want that as a normal setting, but it's fine for a short bfb test.

**Comment by mark-petersen** [comment]
This one also differs between QU and EC by a flag, not a value
```
<!-- hmix_del2 -->
<config_use_mom_del2>.false.</config_use_mom_del2>
<config_use_mom_del2 ocn_grid="oEC60to30v3">.true.</config_use_mom_del2>
```
That is a more likely cause than the one above in my opinion.

**Comment by jonbob** [comment]
@mark-petersen - are you going to test that?

**Comment by mark-petersen** [comment]
I can reproduce the mismatch using intel optimized on grizzly with both QU240 and EC60to30 in MPAS standalone when `config_hmix_scaleWithMesh=true`. Does not occur with QU240 when `config_hmix_scaleWithMesh=false`.

**Comment by philipwjones** [comment]
Interesting...really don't know why this should be the case since none of the mods ever touch any code related to that. Only thing I can think of is that this is affecting some alignment in memory somewhere that Intel is picking up when vectorizing. Let me know if you want me to dive deeper for piece of mind...

**Comment by jonbob** [comment]
@philipwjones - thanks for offering. I would feel better if we had a clear understanding of why this changed answers only for some configurations. I'll make a bug report and assign you and @mattdturner and @mark-petersen ?

**Comment by philipwjones** [comment]
Ok, I can look into this today.

**Pull request merged**
