### PR TITLE
Reverting to CLUBBv1

### PR DESCRIPTION
**Pull request by wlin7**
This PR reverts clubbv2 and follow-up commits to obtain a code base that retain all up-to-present commits, except for clubbv2 which is reverted back to clubbv1. It is found that not all commits related to clubbv2 have to be reverted. PRs for bug fix and enhanced utility features are retained. Reverting of the main CLUBBv2 PR leading to only a small aamount of conflicts  in the following three files.

 components/cam/src/physics/cam/clubb_intr.F90
 components/cam/src/physics/clubb/advance_clubb_core_module.F90
 components/cam/src/physics/clubb/lapack_wrap.F90

[non-BFB] -- All tests involving atm component will return DIFF

### CODE REVIEW

**Comment by wlin7** [comment]
Hi @singhbalwinder and @kaizhangpnl ,

Both of you have made much effort working on CLUBB codes. I would like to ask you to give a review in case I missed something. The number of files changed are large. But the review may just focus on the few that show conflicts as listed on the commit message. It is interesting this PR shows no conflicts with the master. Likely the conflicts resolved during the reverting make the PR reconcile with the master.

@rljacob , I understand normally the person who created the feature branch should not be the one to integrate. Does the current case apply?

**Comment by kaizhangpnl** [comment]
Hi @wlin7 , I didn't find any problem with the revision (I didn't compile and run the model). Have you compared the CLUBB parameters used in this revision and those used in the older master (back to June 2019)? The parameters used in the old master are available on confluence: 

https://acme-climate.atlassian.net/wiki/spaces/EWCG/pages/1033666938/clubb+params+list

**Comment by wlin7** [comment]
Thanks to @kaizhangpnl and @singhbalwinder for the careful review. Kai, I checked the runtime parameter printout, which was added after clubbv2 but retained after reverting to clubbv1. They are identical to the list for CLUBBv1 as you tabulated on the confluence page mentioned above. And C1b = 1.335 as intended for compset F20TRC5-CMIP6.

**Comment by wlin7** [comment]
Merged to master

Tests requested to be blessed: anvil (3), compy (29), cori-knl(2), melvin (9), sandiatoss3 (42)

Special attention (need to be blessed, but not yet):
```
SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.sandiatoss3_intel.allactive-v1cmip6 FAIL since Jan 6
SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.cori-knl_intel.allactive-v1cmip6 DIFF since Feb. 26
Compy tests that have been FAIL.
```

**Pull request merged**
