### PR TITLE
Revert the revert of lightning NOx bug fix and rename chem package

### PR DESCRIPTION
**Pull request by wlin7**
This is to reactivate the bug fix. It was merged but then reverted to maintain v3alpha02 code base.

The campp autogenerated files associated with the updated mechanism are also committed to
let the bug fix take effect.

The chem package superfast_mam5_resus_mom_soag is renamed as chemuci_linozv3_mam5_vbs, 
along with other changes in the codes and build scripts accordingly.

[CC]
[NML]

--------------------------------------------
Original bug fix PR is #5806 
The fix was reverted via #5823, which was merged to #5781 and then took effect in master.

Note that the fix is via the mechanism file, and the mechanism file  for consolidated v3 compsets, pp_chemUCI_linozv3_mam5_vbs.in, is no more specified via usr_mech_file, the revert of revert alone has no effect. The chem preproocessor need to rerun with the update mechanism, then commit the auto-generated files.

### CODE REVIEW

**Comment by wlin7** [comment]
The commit history for the big fix went into master via #5781 (itself via #5823). The original merge commit was reverted via #5823. So, essentially yes, the bug fix not activated in master. This PR will revert the revert, and activate the original bug fix to the mechanism file. But revert the revert alone wouldn't enable the fix, now that we stop using user specified chem_mech. The new commit ([4cfa26b](https://github.com/E3SM-Project/E3SM/pull/5867/commits/4cfa26b8fdb50a5f78e5b78151a8e1988b876c78)) will do it, with the updated auto-generated file associated with the updated mechanism. With that, this PR is NBFB.

**Comment by wlin7** [comment]
> We can still make this BFB if we make alternate chem mech files, e.g., instead of editing `components/eam/chem_proc/inputs/pp_chemUCI_linozv3_mam4_resus_mom_vbs.in`, copy a new `components/eam/chem_proc/inputs/pp_chemUCI_linozv3_mam4_resus_mom_vbs_noxfix.in` from it and edit it, while keeping the old ones. Then, these could be activated in v3alpha03 without having to make this PR CC.

@mahf708 , in previous format of running simulation, yes, this is a way to have the fix in place for use via usr_mech_file in run script. Going forward, we want to make the updated mechanism default. We can still decided when to put this PR in. We could let it go into #5860 to test the combined effect of Lightning NOx fix (plus tuning, say, 5x) and UCI interpolation, as you suggested. BTW, I like your idea of combining them for required simulations, particularly the long coupled run, given their major direct effect are on ozone.

**Comment by wlin7** [comment]
@tangq , @keziming , some additional info that may be helpful when you review.
Two tests were done. One specified the updated pp_chemUCI_linozv3_mam5_vbs.in via usr_mech_file, which trigger campp and auto-generate the files. The other without specifying usr_mech_file, but with updated chem_mech.in and other autogenerated files commiteed. The two runs were verified BFB.

BTW, for the older mechanism files under eam/chem_proc/inputs, they are usually accompanied with a .inp file? Is it also needed for pp_chemUCI_linozv3_mam5_vbs.in? Look like .inp file is only used when maunally running campp from a working directory under components/eam/chem_proc. (It may still be useful to include, just in case one day someone wants to do that. Would like to have your opinion on this.)

**Review by tangq — APPROVED** [review]
The changes are straightforward and look good to me.

@wlin7 , regarding the *.inp file, that's optional and it's fine to leave it there.

A separate note, the pp directory name would be misleading to users familiar with campp because the string after "pp_" should match the *.in file name. For those users, they would think this pp_superfast_mam5_* directory uses the superfast mechanism. Perhaps, it can be fixed in a future PR.

**Comment by wlin7** [comment]
Thanks for the reminder, @tangq . I did plan to also change the chem package name chemUCI_linozv3_mam5_vbs in this PR. I will keep you posted.

**Review by keziming — APPROVED** [review]

**Comment by wlin7** [comment]
Through [ae3b0c9](https://github.com/E3SM-Project/E3SM/pull/5867/commits/ae3b0c9672b19d9fd230ad2e6b61b9ded76b2a45), the chem package name is changed from `superfast_mam5_resus_mom_soag` to `chemUCI_linozv3_mam5_vbs`. The chem package name in Fortran codes, namelist file, and several pre-processing scripts use lower case. To be consistent, `chemuci_linozv3_mam5_vbs` in  all files involved.

1-month F20TR test verified the results are BFB before and after these changes.

**Comment by tangq** [comment]
Hi @wlin7 , thanks for implementing this. I will use the chemistry name `chemUCI_linozv3_mam5_vbs` to replace the `uci1` reaction existence checks later today and let you know how it goes.

> Through [ae3b0c9](https://github.com/E3SM-Project/E3SM/pull/5867/commits/ae3b0c9672b19d9fd230ad2e6b61b9ded76b2a45), the chem package name is changed from `superfast_mam5_resus_mom_soag` to `chemUCI_linozv3_mam5_vbs`. The chem package name in Fortran codes, namelist file, and several pre-processing scripts use lower case. To be consistent, `chemuci_linozv3_mam5_vbs` in all files involved.
> 
> 1-month F20TR test verified the results are BFB before and after these changes.

**Comment by tangq** [comment]
Hi @wlin7 , while changing the `uci1` reaction existence checks, I realized that using `uci1` to check if chemUCI is used is more convenient than the chemistry name string (e.g., `chemUCI_linozv3_mam5_vbs`) because chemUCI may be associated with multiple chemistry names in the future. Therefore, I decided NOT to change the `uci1` checks.

A separate note:
While reviewing the code, I noticed a couple minor issues (loop ordering and typos) and fixed them in [5802685](https://github.com/E3SM-Project/E3SM/pull/5867/commits/5802685eb177e653672f1792f2d233ec585586bb). I've confirmed that the commit [5802685](https://github.com/E3SM-Project/E3SM/pull/5867/commits/5802685eb177e653672f1792f2d233ec585586bb) is BFB.

**Comment by wlin7** [comment]
Merged to next.

**Comment by wlin7** [comment]
Merged to master.

**Pull request merged**
