### PR TITLE
Prevents leaf and livestem from turning negative immediately after harvest

### PR DESCRIPTION
**Pull request by evasinha**
- This modification prevents leaf and livestem from turning negative immediately after harvest. 
-  This error was eventually causing leafc to turn positive at the start of the year instead of after crop emergence.
- Positive leafc was eventually cascading to positive GPP even before crops emerged. 

The crops test result in DIFF but this difference is expected because of the modifications made in the PR.
 For crops, the modification results in gap mortality flux for leaf and livestem to be estimated only when crops are alive.
[non-BFB] for Crop Tests

### CODE REVIEW

**Comment by evasinha** [comment]
Based on suggestion by @bbye, I investigated whether `leafc` was negative at the start of the year.

**Comment by evasinha** [comment]
Based on suggestion by @bbye, I investigated whether `leafc` was negative at the start of the year. 

`leafc` was indeed turning negative at the start of the year and it occurred immediately after harvest. The reason `leafc` goes negative is because of gap mortality flux for `leafc`  (`m_leafc_to_litter`).

* At the time of harvest, `hrv_leafc_to_prod1c`  is estimated as a fraction of `leafc` and the rest goes to litter ( `leafc_to_litter` ) .
* Then the gap mortaility flux is subtracted from `leafc` and this causes `leafc` to turn negative when finally `hrv_leafc_to_prod1c`  and `leafc_to_litter`  are subtracted from it.
* Furthermore, even after `leafc` is negative `m_leafc_to_litter`  keeps getting estimated and being subtracted from `leafc`.

```
- call EcosystemDynNoLeaching2()
	- call Phenology()
		- call CNCropHarvest()
			- hrv_leafc_to_prod1c(p)  = presharv(ivt(p)) * ((t1 * leafc(p)) + cpool_to_leafc(p))
	- call CarbonStateUpdate1()
		- veg_cs%leafc(p) = veg_cs%leafc(p) + veg_cf%leafc_xfer_to_leafc(p) * dt		
        - veg_cs%leafc(p) = veg_cs%leafc(p) - veg_cf%leafc_to_litter(p) * dt
		- veg_cs%leafc(p) = veg_cs%leafc(p) + veg_cf%cpool_to_leafc(p) * dt 
	- call GapMortality()
		- m  = am/(dayspyr * secspday)
		- veg_cf%m_leafc_to_litter(p) = veg_cs%leafc(p) * m 
	- call CarbonStateUpdate2()
		- veg_cs%leafc(p) = veg_cs%leafc(p) - veg_cf%m_leafc_to_litter(p) * dt 
		- veg_cs%leafc(p) = veg_cs%leafc(p) - veg_cf%hrv_leafc_to_litter(p) * dt
		- veg_cs%leafc(p) = veg_cs%leafc(p) - veg_cf%hrv_leafc_to_prod1c(p) * dt
	- call CarbonStateUpdate3()
		- veg_cs%leafc(p) = veg_cs%leafc(p) - veg_cf%m_leafc_to_fire(p) * dt
		- veg_cs%leafc(p) = veg_cs%leafc(p) - veg_cf%m_leafc_to_litter_fire(p) * dt
```

This error is fixed by estimating `m_leafc_to_litter` for crops only when crops are alive. The same check was implemented for `m_livestemc_to_litter`, `m_leafn_to_litter`, `m_livestemn_to_litter`, `m_leafp_to_litter`, and `m_livestemn_to_litter`.

**Review by bbye — APPROVED** [review]

**Comment by peterdschwartz** [comment]
Can clarify under what configurations will have non BFB results due to these changes?  When you say BFB do you just mean for the current test cases?

**Comment by evasinha** [comment]
@peterdschwartz - Yes, BFB results for the current E3SM-Land-Developer-testsuite.

**Comment by peterdschwartz** [comment]
Well running the  e3sm_developer test suite after merging to next shows these two tests DIFF.
```
SMS_Ly2_P1x1.1x1_smallvilleIA.IELMCNCROP.chrysalis_intel.elm-force_netcdf_pio (Overall: DIFF) details:
  SMS_Ly2_P1x1.1x1_smallvilleIA.IELMCNCROP.chrysalis_intel.elm-per_crop (Overall: DIFF) details:
```

**Comment by evasinha** [comment]
@peterdschwartz - Sorry, I made a mistake when reading the results of running the E3SM-Land-Developer-testsuite. I only searched for tests that FAILED. 

You are right that these two tests are showing a DIFF when compared to the baseline. I examined the difference further and they only occur in test with CROPS on and in which harvest occurs. This difference is expected based on the edits made in this PR.  

I have modified the description to state that BRB except for test with crops on in which harvest occurs.

**Comment by peterdschwartz** [comment]
Thanks, Merged to next.

**Comment by evasinha** [comment]
@peterdschwartz - Thanks for reviewing and merging.

**Comment by peterdschwartz** [comment]
Merged to master and submitted bless requests

**Pull request merged**
