### PR TITLE
Restore implementation of time step convergence test

### PR DESCRIPTION
**Pull request by singhbalwinder**
The test was implemented in v0.1 (see Confluence page at
https://acme-climate.atlassian.net/wiki/spaces/ATM/pages/15074009/Time-step+convergence+test)
But some switches related to stratiform cloud macrophysics
and microphysics got lost during the v1 development.
This commit restores those switches.

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
Can you also add a test that excercises this capability?

**Comment by singhbalwinder** [comment]
I added a test. @huiwanpnnl would you please take a look at it to ensure everything is okay? I did do a test run to make sure it works.

**Comment by huiwanpnnl** [comment]
The test looks good to me. Thank you @singhbalwinder.

**Comment by wlin7** [comment]
@singhbalwinder and @huiwanpnnl , 
On the comparison of  if-conditional-blocks for microp_scheme == 'RK' and 'MG' for l_st_mac and l_st_mic:

With RK, The microphysics and  macrophysics will be called when either l_st_mac or lt_st_mic is true. 

With MG, l_st_mac and l_st_mic blocks are more exclusive if only one of them is true. Are these intended?

On l_vdiff block in tphysac, the call of clubb_surface is now not subject to l_vidff condition.  vertical_diffusion_tend does much more, but the update with surface constituent fluxes are common between using CLUBB_SGS and that using the alternative. Is this change (i.e., moving clubb_surface out of l_vdiff conditional) always by design?

I am just curious about these two blocks. All else look good to me.

**Comment by huiwanpnnl** [comment]
Hi @wlin7, thanks a lot for your careful review. The answers to your questions have to do with the different ways how processes are "packaged" in the older and newer models.

When microp_scheme == 'RK', the same subroutine stratiform_tend contains both the macro- and microphysics calculations, hence it is called when either l_st_mac or l_st_mic is true. When microp_scheme == 'MG', the macro- and microphysics calculations are done in separate subroutines called by tphysbc, hence they are switched on or off separately using l_st_mac and l_st_mic.

As for l_vdiff, I introduced this flag back in V0 when CLUBB was not implemented and turbulence was represented by schemes packed in subroutine vertical_diffusion_tend. In the V1 code, CLUBB is called at the place where cloud macrophysics is calculated (hence controlled by the "l_st_mac" switch), and there is no longer the freedom to turn off turbulence (or shallow convection) while leaving macrophysics active, but the clubb_surface subroutine (called in tphysac close to the old vertical_diffusion_tend) provides surface boundary condition for CLUBB. In other words, clubb_surface needs to be called when l_st_mac  = True. So I decided to move "call clubb_surface" out of the l_vdiff conditional to make sure that the boundary conditions are properly set. This way, when CLUBB is turned on, l_vdiff will have no effect. Sorry that this is not straightforward.

**Comment by wlin7** [comment]
Thank you @huiwanpnnl for the excellent explanation.

**Comment by wlin7** [comment]
Merged to next.

**Comment by wlin7** [comment]
@singhbalwinder and @rljacob , the fix on missing parentheses is likely solely responsible for next failing to run? Next is closed now. But should this PR be pushed in?

**Comment by singhbalwinder** [comment]
I have already pushed the fix to next. Are you asking about pushing the PR to master?

**Comment by rljacob** [comment]
Yes if your PR resulted in the CLOSED message, you're allowed to still merge things to fix it.

**Comment by wlin7** [comment]
Merged to master.

**Comment by rljacob** [comment]
@wlin7 you need to file a ticket to have a baseline created for the new test on skybridge and chama.
https://acme-climate.atlassian.net/servicedesk/customer/portal/2   The test has been showing fail since it was added because there is no baseline.

**Pull request merged**
