### PR TITLE
Replaces CLUBB with new version of CLUBB (V2)

### PR DESCRIPTION
**Pull request by singhbalwinder**
The v1 version of CLUBB left pockets of supersaturation for the microphysics.   To mitigate this, the
v2 version of CLUBB does CLUBB's saturation adjustment immediately before microphysics when
ipdf_call_placement = ipdf_pre_advance_fields.

CLUBB_v2 includes performance optimizations that may lead to speedups, but also may be vitiated
by a performance degradation in the CLUBB interface that was introduced in order to change the
position of the saturation adjustment.

CLUBB_v2 also adds new options that may be interest when tuning E3SMv2:

 * CLUBB's gustiness can be enhanced if C_wp2_splat is set to non-zero values.  This may enhance the benefits found with Po-Lun Ma connection of CLUBB's gustiness and surface processes.

 * CLUBB_v2 can now prognose momentum fluxes if l_predict_upwp_vpwp = .true.  This is designed to reduce ocean surface stress in cumulus regions.

[NBFB]

### CODE REVIEW

**Comment by singhbalwinder** [comment]
I have recently rebased this branch. I am running some tests and will soon update the PR description with the new diagnostics info.

**Comment by rljacob** [comment]
telecon:  encountering issues with testing on different machines.

**Comment by singhbalwinder** [comment]
I have run the model for 6 years and diagnostics from 2nd to 6th year are at: https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/bsingh/2-6yr/SMS.ne30_ne30.FC5AV1C-L.anvil_intel.clbv2_rbsd_1_0cb6bd4-SMS.ne30_ne30.FC5AV1C-L.anvil_intel.def_mstr_b5aaa6b7d228_clbv2_rbsd_1/

Tagging @golaz  and @polunma  so that they can take a look at the diagnostics.

**Comment by singhbalwinder** [comment]
This PR is ready to merge after it is approved.

**Comment by rljacob** [comment]
@golaz please approve this.

**Comment by golaz** [comment]
@singhbalwinder : can you document this in a little more details on Confluence? If already done, please add link here. In particular I'd like to see:

- Details about simulations (both base and new CLUBB version): code base, script, output location, ...
- E3SM Diags for model vs obs (both simulations) as well as model vs model.

**Comment by singhbalwinder** [comment]
Thanks @golaz ! @vlarson is working on creating a design document. @vlarson or I will add a link here once it is ready.

For the diagnostics, would it be okay to run AMWG? I have those setup so it will be easy to run those with obs.

**Comment by vlarson** [comment]
> Thanks @golaz ! @vlarson is working on creating a design document. @vlarson or I will add a link here once it is ready.
> 
> For the diagnostics, would it be okay to run AMWG? I have those setup so it will be easy to run those with obs.

@golaz , @singhbalwinder , I have started a design doc [here](https://acme-climate.atlassian.net/wiki/spaces/ED/pages/1001390288/A17+CLUBB+v2+Design+Doc).  Please let me know what I need to add.

**Comment by golaz** [comment]
@vlarson : thanks for working on the design document.

@singhbalwinder: I can live with AMWG figures for now, but it would be good if you learned how to use E3SM Diags in the future. I think it's pretty straightforward.

**Comment by singhbalwinder** [comment]
@golaz : Here are the E3SM diags:

[CLUBBV2 Vs. Default model](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/bsingh/e3sm_diags/SMS.ne30_ne30.FC5AV1C-L.anvil_intel.def_mstr_b5aaa6b7d228_clbv2_rbsd_1-SMS.ne30_ne30.FC5AV1C-L.anvil_intel.clbv2_rbsd_1_0cb6bd4/viewer/)

[CLUBBV2 Vs. OBS](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/bsingh/e3sm_diags/SMS.ne30_ne30.FC5AV1C-L.anvil_intel.clbv2_rbsd_1_0cb6bd4-%20obs/viewer/)

[Default Vs. OBS](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/bsingh/e3sm_diags/SMS.ne30_ne30.FC5AV1C-L.anvil_intel.def_mstr_b5aaa6b7d228_clbv2_rbsd_1-SMS.ne30_ne30.FC5AV1C-L.anvil_intel.clbv2_rbsd_1_0cb6bd4/viewer/)

There are all 6 years of simulations where 2nd to 6th year are compared.

The model output and climo files are on Anvil. Is there a preferred place I should move these files to?

**Comment by singhbalwinder** [comment]
Thanks to @vlarson and @huebleruwm , I have now added latest commits to update CLUBBv2 to bring it up to its latest version. These commits were answer changing but the effect seems very minor from the annual averages. Here are the new diagnostics:

[CLUBBV2 Vs. Default model](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/bsingh/e3sm_diags/SMS.ne30_ne30.FC5AV1C-L.anvil_intel.def_mstr_b5aaa6b7d228_clbv2_rbsd_1-SMS.ne30_ne30.FC5AV1C-L.anvil_intel.clbv2_rbsd_1_ed716943a4c/viewer/)

[CLUBBV2 Vs. OBS](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/bsingh/e3sm_diags/SMS.ne30_ne30.FC5AV1C-L.anvil_intel.clbv2_rbsd_1_ed716943a4c-%20obs/viewer/)

**Comment by golaz** [comment]
@singhbalwinder : thanks for running these new simulations. I agree that the differences between CLUBBV2 and Default model are quite small.

What code base and compset did you use for the default configuration? The base climate in your default configuration and CLUBBV2 appears to be quite different from the E3SMv1 DECK AMIP simulations. I don't think it's related to the CLUBBV2 changes, but might indicate other changes (code changes on master, tuning, compset).

It's particularly obvious for precipitation. E3SMv1 AMIP A1 vs GPCP v2.2:

https://portal.nersc.gov/project/acme/coupled/DECKv1/20180316.DECKv1b_A1.ne30_oEC.edison/e3sm_diags/1985-2014/viewer/latitude-longitude/gpcp_v22/prect-global-gpcp_v22/ann.html

Current code:

https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/bsingh/e3sm_diags/SMS.ne30_ne30.FC5AV1C-L.anvil_intel.clbv2_rbsd_1_ed716943a4c-%20obs/viewer/latitude-longitude/gpcp_v22/prect-global-gpcp_v22/ann.html

**Comment by singhbalwinder** [comment]
Sorry, I should have mentioned these details earlier. Here are the details:
Compset: FC5AV1C-L
Resolution: ne30_ne30

These are 6 year simulations with years 2-5 analyzed (1 year spin up). DECK simulations might be using a different compset and input data.

**Comment by golaz** [comment]
@singhbalwinder : thanks for the info (that's also why I'd like to eventually have every simulation documented on Confluence). 

Yes, the the DECK simulations were using different compsets (forcing and tunings). I hope that this can explain the differences (but I'm not entirely convinced that it does). For example, I don't recall seeing a configuration with a global mean precipitation of 3.23 mm/day.

Anyway, this is a side discussion. Based on the evidence presented here, the CLUBBv2 modifications do not seem to make significant differences compared to your default, so we should go ahead and merge.

@rljacob : once master settles, the first thing I'm planning to do is evaluate the current master against E3SMv1 DECK simulations to see if the climate is still the same. What comes after will depend of what we find.

**Comment by rljacob** [comment]
The description for the PR should include a few sentences on what is new/different/improved in this new version of CLUBB.

**Comment by singhbalwinder** [comment]
@rljacob : I have updated the description above. I copied this text from the summary section of the design document.

**Comment by singhbalwinder** [comment]
@golaz : I have updated the design document with the location of diagnostics and simulation details. Where should I put the climo files and the model output? Right now they are on Anvil. Should I move them to NERSC HPSS under my account?

**Comment by rljacob** [comment]
@wlin7 this is approved.  Please start integrating.

**Comment by wlin7** [comment]
@rljacob , this PR is expected to be non-BFB for all tests that involves active atm. Is it good to go in today? Thanks.

**Comment by rljacob** [comment]
We have a coupled of cases with full atmosphere and diffs that we are trying to understand.  So wait for tomorrow.

**Comment by wlin7** [comment]
Ok.

**Comment by wlin7** [comment]
@rljacob,  the dash board looks good. Can I go ahead now (if no other major PR going in)?

**Comment by rljacob** [comment]
Yes go ahead.

**Comment by wlin7** [comment]
Thanks Rob. Merged to next.

**Comment by wlin7** [comment]
Merged to master and submitted requests to bless DIFFs for sandiatoss3 (37), melvin(7) and anvil(2).

**Comment by rljacob** [comment]
2 PET tests failed.   Those will require a closer look:
 PET_Ln9_PS.ne30_oECv3_ICG.A_WCYCL1850S.sandiatoss3_intel.allactive-mach-pet
PET_Ln5.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.allactive-mach-pet

**Comment by wlin7** [comment]
@singhbalwinder , are you aware whether this PR could cause threading to be non-BFB? The two PET tests apparently say so.

@rljacob , at this point, should the merge be reverted? It may take a while to investigate.

**Comment by wlin7** [comment]
@singhbalwinder , I just checked slack and noticed you were doing tests on this threading issue. Thanks.

**Comment by wlin7** [comment]
Reverted the commit on master and next.
Resubmitted the requests to bless the previous DIFFs on sandiatoss3, melvin and anvil.

**Comment by rljacob** [comment]
@wlin7 you can't submit the bless until after the tests run with the new code.  After tonight.

**Comment by wlin7** [comment]
@rljacob , @wade did comment that he can't bless anything else today. I will resubmit the request based on the test results tomorrow. That said, I don't understand why it can't be done with the master after this PR is reverted.  The master is essentially back to what it was yesterday. The DIFFs that would come up tomorrow (for next and master) are expected to be the same as we saw today for next tests. I was thinking with re-blessing, the baselines that were in place before today's blessing would all be restored.

**Comment by rljacob** [comment]
The bless command is script that works in one direction:  it copies output from the run of testing on "next" to the baselines.   And we have just one set of baselines that both next and master are compared against.

**Comment by wlin7** [comment]
I see now. Thanks for the explanation, @rljacob. 
I thought master would be used during blessing to update the baseline because normally we merge the PR  to master before requesting to bless.

**Comment by singhbalwinder** [comment]
Thanks to Zhun Guo and @vlarson , the PET test is now passing. I am now running the fully coupled PET test to ensure that I get a PASS there as well. After that, it should be good to go.

**Comment by singhbalwinder** [comment]
I got PASS on both the tests. I think it is good to go now.

**Comment by rljacob** [comment]
Its to late to affect tonights test run.

**Comment by wlin7** [comment]
Great work, @singhbalwinder.  Thanks. Nightly tests probably have started. I will wait until tomorrow.

**Comment by wlin7** [comment]
Rob, is there any other non-BFB scheduled for Thursday? If not and next open, i will merge it in the morning and ask our integrators to hold on.

**Pull request merged**
