### PR TITLE
v2 SL and physgrid remap performance, mass conservation

### LINKED ISSUE #3588: Mass conservation with pg2 grids
While testing CO2 conservation with the v2alpha-clubbv2 branch, I noticed that the mass conservation is not maintained with the ne4pg2 grid, but is with ne4np4.  I have been using CO2_FFF (fossil fuel flux CO2 tracer) to test for mass conservation because when there is no emissions file prescribed, the fluxes are exactly zero and conservation should be maintained (to machine level round off).  To demonstrate the conservation issue, I have attached a figure showing the relative error in the global mean CO2_FFF from its starting value using ne4pg2 and ne4np4 grids.  I have also copied the printouts of the global dry mass of that tracer from the gmean_mass calls for the two grids.

I am tagging a few people that I think might be interested @wlin7 , @susburrows , @kvcalvin , @kaizhangpnl , @whannah1 , @jonbob .  These runs were done on Compy, intel compiler, and FC5AV1C-04P2 compset (with CAM_CONFIG_OPTS="-co2_cycle" added to enable CO2).

image

				ne4np4				ne4pg2
m=42name=CO2_FFF		5.6285784223748E+00		5.6282525870713E+00
m=42name=CO2_FFF		5.6285784223748E+00      	5.6282525870669E+00
m=42name=CO2_FFF 		5.6285784223748E+00      	5.6282525870615E+00
m=42name=CO2_FFF 		5.6285784223748E+00      	5.6282525870628E+00
m=42name=CO2_FFF 		5.6285784223748E+00      	5.6282525870583E+00
m=42name=CO2_FFF 		5.6285784223748E+00      	5.6282525870570E+00
m=42name=CO2_FFF 		5.6285784223748E+00      	5.6282525870590E+00
m=42name=CO2_FFF 		5.6285784223748E+00      	5.6282525870572E+00
m=42name=CO2_FFF 		5.6285784223748E+00      	5.6282525870523E+00
m=42name=CO2_FFF 		5.6285784223748E+00      	5.6282525870430E+00

### PR DESCRIPTION
**Pull request by ambrad**
Improve vectorization and threading in SL transport, physgrid remap, and theta-l.

Fix a mass conservation error due to finite precision effects.

These code mods would cause no answer change in exact arithmetic but are non-BFB in finite precision.

Summary:
- Physgrid remap: Switch indexing from (:nf,:nf) to (:nf2) to improve vectorization.
- SL transport:
   * Speed up global CAAS by locally reducing what can be reduced decomp-BFB.
   * Improve own_q, rmt_q thread load balance.
   * Flip level, q indexing to improve memory locality.
   * After a performance regression to calc_q a few months ago to work around a compiler bug, address the performance issue in a different way. I avoid using pragma ivdep but get the performance that annotation provides by explicitly blocking. The result is effective vectorization of a key computation in SL transport.
- Fix dp_fv so it agrees numerically with the pdel calculation in dp_coupling.F90: derived_physics.
- Add a C++ block to the cori-knl/intel19 block in config_compilers.xml.
- Work around an Intel 17 -O3 bug to fix a standalone-Homme test on Anvil.

Fixes #3588.

[non-BFB] 4 EAM tests and 3 standalone Homme tests

### CODE REVIEW

**Comment by ambrad** [comment]
Standalone Homme tests:
```
The following tests FAILED:
   21 - thetah-sl-test11conv-r1t2-cdr20 (Failed)
   22 - thetah-sl-test11conv-r0t1-cdr30-rrm (Failed)
   23 - thetah-sl-dcmip16_test1pg2 (Failed)
```
These are expected. Since this PR makes no change in exact arithmetic -- changes have finite precision effects only -- the diffs are small.

**Comment by ambrad** [comment]
e3sm_developer on sandiatoss3 has these diffs:
```
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.cam-thetahy_pg2
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.cam-thetahy_sl_pg2
ERS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.cam-thetahy_sl_pg2
```
In the ERS test, COMPARE_base_rest passes.

**Comment by ambrad** [comment]
Documentation, including performance results, on this [confluence page](https://acme-climate.atlassian.net/wiki/spaces/COM/pages/1448378562/SL+Transport+and+Physgrid+v2+performance+improvement+PR).

**Comment by ambrad** [comment]
@rljacob this PR is ready and has Chris Golaz's approval. Would you assign an integrator for this PR? Thanks.

**Comment by ambrad** [comment]
Hi @AaronDonahue is there anything you would like me to do to help you merge this PR? Thanks.

**Comment by AaronDonahue** [comment]
@ambrad , Thank you for the reminder.  I didn't see that I had been assigned this.  I'll get on it once I get the green light that next is open.

**Comment by AaronDonahue** [comment]
@ambrad , can you let me know which tests are expected to fail for the NBFB so I can keep a look out tomorrow and issue the bless requests?

**Comment by ambrad** [comment]
Hi @AaronDonahue. The following tests will diff. From e3sm_developer:
```
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.cam-thetahy_pg2
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.cam-thetahy_sl_pg2
ERS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.cam-thetahy_sl_pg2
```
These diffs will appear on
```
sandiatoss3	￼e3sm_integration_next_intel
melvin	￼e3sm_developer_next_gnu
```
I'm not sure whether standalone Homme requires one or multiple bless requests. These standalone Homme tests will diff:
```
The following tests FAILED:
   21 - thetah-sl-test11conv-r1t2-cdr20 (Failed)
   22 - thetah-sl-test11conv-r0t1-cdr30-rrm (Failed)
   23 - thetah-sl-dcmip16_test1pg2 (Failed)
```
It will show up as one diff on
```
sandiatoss3	￼homme_integration_next_intel
```
as test
```
HOMME_P24.f19_g16_rx1.A.sandiatoss3_intel
```

**Comment by AaronDonahue** [comment]
@ambrad , excellent, thank you.

**Comment by ambrad** [comment]
I just checked the logs for sandiatoss3 homme_integration_next_intel, and they look as expected.

**Pull request merged**
