### PR TITLE
Add checkpoint of timing data immediately after initialization

### PR DESCRIPTION
**Pull request by worleyph**
Currently a timing checkpoint is saved at the end of the first
simulation day, capturing both initialization cost and possibily
anomalous first simulation day performance. However, when
evaluating performance of initialization for high resolution
cases, this may not be sufficiently fine grain, especially if the
evaluation job runs out of time before completing the first
simulation day. Here an additional timing checkpoint is output
immediately before the beginning of the run loop, with a name
consistent with the other checkpoint timing files, i.e. including
the simulation timestamp in the suffix.

Existing timer names associated with the writing out of performance
data are modified slightly, to better attribute time associated
with the new performance data write. Also, missing documentation
for the TPROF_TOTAL env_run.xml variable is added to
config_component_e3sm.xml.

[BFB] - Bit-For-Bit

### CODE REVIEW

**Comment by worleyph** [comment]
This feature was requested by @ndkeen and @brhillman to make development and testing of high resolution cases (where initialization can take a long time) easier. I added the two obvious (to me) checkpoints to the initialization, but more could be added if useful using the same logic. As always, my grasp of coding standards for CIME is shaky, and CIME developers will need to pass judgement on this as well.

I have run sanity and functionality experiments using F cases on Cori-KNL. This affects only the writing out of checkpoint performance data and the renaming of a few existing timers, so I expect it to work fine in general testing. @ndkeen and @brhillman should first test that it is useful for them, and whether the design needs to be tweaked.

**Comment by ndkeen** [comment]
It feels heavy-weight (modifying namelists) for what it's doing, but if this is natural way of doing it and it's done, I'd like to try it. 

One request: Can we go ahead and just write the value of those timers during init in e3sm.log? At least the total time for init, but one or two other important pieces would also be great.  I predict those times would be looked at often as this is the first hint a user can get regarding how it's running.

**Comment by worleyph** [comment]
If this is going to be optional, it has to be controlled somehow, and that means a namelist or compile-time flag.

> One request: Can we go ahead and just write the value of those timers during init in e3sm.log? 

I don't understand the question? This is not how the timing library is used. If you just want something written to e3sm.log, then you should add some calls to MPI_WTime and write this out directly? Something like how time per day is written out to the cpl.log? If this is what you want, then I misunderstood your request andwe should kill this PR and you can submit your own. Or this would be a new, complementary, PR?

**Comment by ndkeen** [comment]
Another way of making it optional is maybe to use:
`tprof_option = "ndays"`
Say, if this is set to ndays, then write a checkpoint during and/or just after init in addition to the other checkpointing requested. ?

Yes, something like how we write timing data to cpl.log for each day (which, btw, is a very useful set of timing data).

**Comment by worleyph** [comment]
It is already set for "ndays" implicitly . So, you prefer always having the checkpoint timing file output for initialization? Please give it a try first, as I have two additional checkpoint files specified. If 2 is one too many, I can back off to one and revisit the design and perhaps make it mandatory instead of optional.

I'll let you do the PR to add the write to cpl.log or e3sm.log.

**Comment by worleyph** [comment]
@ndk and @brhillman , I'll be reworking this PR to examine removing the NML. If it works out, I'll update here and you can try the new design.

**Comment by worleyph** [comment]
@ndk and @brhillman , please take a look at this. This probably does what you want, if I finally understand your goals. It is cleaner (not NML) and more consistent with existing behavior.

**Comment by brhillman** [comment]
@worleyph sorry this has been low priority since I got ne512 to run through a day. I'm ultimately going to punt to @ndkeen on this, because I don't think I will personally use the added functionality much, but I'm going to play around with it a little today and give feedback or approve. I will say that the added documentation is much appreciated though, and I don't see anything here that looks out of place, and the changes appear to be good improvements.

**Comment by ndkeen** [comment]
Pat: I still think that if the user requests any checkpointing, we shoudl go ahead and write a checkpoint after Init. So I think that should be default on.  ?  
Having the timing in Init be separate from the simulations in the checkpoint data seems most intuitive.

However, adding options to allow for even finer checkpointing could still be useful. But maybe only for someone debugging and/or profiling Init.

Also -- regarding checkpoints and options -- I personally find the accumulation method in checkpoints to be not-what-I-would-expect. It would be great to have the option of asking for the checkpoint data to be exclusive time -- that is, the second checkpoint would NOT include the time already recorded in the first checkpoint.  We could post-process to get one from the other, of course. I went down that path using a script, but it's a little tricky to do in general.

**Comment by worleyph** [comment]
> Pat: I still think that if the user requests any checkpointing, we shoudl go ahead and write a checkpoint after Init. So I think that should be default on. ?

Please reread the description and the code changes. As you requested, there is no option any more. You always get a checkpoint timing file at the end of Init.

>  I personally find the accumulation method in checkpoints to be not-what-I-would-expect.

This is a GPTL "feature". Can't reset without losing the running totals, which is still what you need for the full run performance summary. Enabling this would be nontrivial I believe.

**Comment by ndkeen** [comment]
Ah. Sorry about that. I saw the code changes on a laptop in poor lighting and I missed that code in red means it's no longer there. 

So then, yea, I think this is a nice-to-have when doing checkpoints.

**Comment by worleyph** [comment]
Hi @jgfouca , your turn next :-). Thanks.

**Comment by jgfouca** [comment]
@worleyph , merged to next. Should I wait for integration testing?

**Comment by worleyph** [comment]
@jgfouca , yes. You should wait for integration testing. (Thanks for asking).

**Pull request merged**
