### PR TITLE
Add topo and atmsrf files for ne120pg2

### PR DESCRIPTION
**Pull request by wlin7**
This PR adds bnd_topo and drydep_srf_file (atmsrf) files for ne120pg2.

[BFB]

### CODE REVIEW

**Comment by whannah1** [comment]
This is redundant wit PR #3568. I added a tri-grid config with ne120pg2 which also adds these files.

**Comment by whannah1** [comment]
@singhbalwinder why did you approve this?
We need to figure out whether to use these files or the ones I made previously in PR #3568?

**Comment by singhbalwinder** [comment]
@whannah1 : I didn't realize that your files are different from the ones in this PR (just looked at the drydep file). I thought this PR probably can go in relatively easily (less # of changes) and then #3568 can be modified to remove these files or it won't matter. 
Like you mentioned, if the files are different, we need decide which ones to choose.

**Comment by whannah1** [comment]
@singhbalwinder I don't know if they are fundamentally different. I had Andrew Bradley create them for me because I was having trouble building the HOMME tool.
But either way, my PR has been ready for awhile now, so it's probably easier to just merge that in and delete this PR rather than make me go back and remove the files.

**Comment by singhbalwinder** [comment]
I agree. If your PR is ready to go, we should probably close this PR. @wlin7 : do you agree?

**Comment by wlin7** [comment]
@whannah1 , thanks for bringing to our attention of PR #3568. I agree this PR can be closed and I am closing it. Before #3568 is merged, I can just specified the topo and atmsrf files in the run script.

**Comment by whannah1** [comment]
@wlin7 great, thanks, and sorry for the delay on that PR.

**Pull request closed without merging**
