### PR TITLE
Fix ftype1 in NH theta

### PR DESCRIPTION
**Pull request by oksanaguba**
Fixing ftype1 for NH runs, previously, NH variables were not updated in dp_coupling layer.

### CODE REVIEW

**Comment by oksanaguba** [comment]
eam_theta passed against today's master except for ftype1_thetanh test, as expected. will run whole suite tomorrow.

**Comment by mt5555** [comment]
Looks good and more modular.  Can you remove applyCAMforcing_dynamics()?  This entire subroutine is now just an elem loop, so it looks like it no longer makes sense to exist with this newer design.

**Comment by mt5555** [comment]
@bartgol this new interface will have to be back ported to hommexx?   we could instead keep the old interface an only change code in EAM.

**Comment by bartgol** [comment]
So, other than the added modularity, the main difference is that phi and w_i were not forced with ftype 1? I think we ever handled ftype 1 in hommexx. I only see support for ftype 0 and 2. I guess we can add ftype 1 as well.

**Comment by oksanaguba** [comment]
told to do it in 1-file PR.

**Pull request closed without merging**
