### PR TITLE
update the machine configs for livermore computing machines

### PR DESCRIPTION
**Pull request by AaronDonahue**
Updates the livermore computing machine config entries to match the current 2023-09-07 configuration of the machines.

### CODE REVIEW

**Comment by rljacob** [comment]
@AaronDonahue go ahead and merge.

**Comment by AaronDonahue** [comment]
@rljacob , I'm back from vacation and just now getting to merge this.  I actually don't have authorization to push to next (and presumably master).  I am no longer officially an integrator so perhaps my user ID has been taken off of the list?

```
remote: error: GH006: Protected branch update failed for refs/heads/next.
remote: error: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.
To https://github.com/E3SM-Project/E3SM.git
 ! [remote rejected]       next -> next (protected branch hook declined)
error: failed to push some refs to 'https://github.com/E3SM-Project/E3SM.git'
```

**Comment by rljacob** [comment]
@AaronDonahue please merge.

**Comment by rljacob** [comment]
@AaronDonahue please merge.

**Review by rljacob — APPROVED** [review]

**Pull request merged**
