### PR TITLE
Add support for performance archiving on Compy

### PR DESCRIPTION
**Pull request by worleyph**
Added logic for compy to provenance.py, specified
the location of the performance archive in the
compy entry in config_machines.xml (enabled for
all projects) and added the job progress monitoring
script syslog.compy. Also removed performance
archiving support for edison, now that it has been
decommissioned.

[BFB] - Bit-For-Bit

### CODE REVIEW

**Comment by worleyph** [comment]
@rljacob , please reassign reviewers and integrator as appropriate. Thanks.

**Comment by sarats** [comment]
Hmm... I see that /compyfs (without e3sm suffix) is being used everywhere in the machine file. So, perhaps that's not a concern. Default permission enable group write to performance_archive. So, it's fine as long as non-E3SM users can't meddle with it.

**Comment by worleyph** [comment]
> So, it's fine as long as non-E3SM users can't meddle with it.

What is your concern? Vandalism of some sort? Shouldn't be anything sensitive or critical being written to the performance archive.

**Comment by sarats** [comment]
I was just thinking of accidental deletes and thought /compfs/performance_archive may not convey that it's related to e3sm. 

I'm used to our project specific directories at the LCFs. Anyway, I see /compyfs used everywhere in the machine file. So, this is not a problem.

**Comment by worleyph** [comment]
@sarats , thanks for asking about this. This is a BER system, and the accounts (once we start using them consistently) will allow us to differentiate between jobs in the performance archive. For example, at NERSC all supported projects (acme, m2830, m2833) archive in the same location. This isn't supported at the OLCF because of the directory permissions policies in proj-shared.

**Comment by worleyph** [comment]
Would be nice to get this intergrated before people jump on and start using the system. @singhbalwinder and @bibiraju , could you please do quick reviews (or ask to be unassigned)? Thanks.

**Comment by worleyph** [comment]
Thanks @bibiraju , @singhbalwinder , and @sarats . This is ready to go @jgfouca .

**Comment by rljacob** [comment]
Reassigning this to @bibiraju since its Compy related and JimF is pretty busy.

**Pull request merged**
