### PR TITLE
Update MMF tests

### PR DESCRIPTION
**Pull request by whannah1**
The MMF "test" compsets were originally created to shorten the run time of tests, but without any special development needs these compsets are unnecessary and just clutter up the compset configuration. If we decide we need smaller tests again it will be better to add a specific test mod rather than a special compset. 

[non-BFB] only for MMF tests since they will change

### CODE REVIEW

**Comment by brhillman** [comment]
Not sure if this needs the non-BFB label, this will change the MMF test we use in the integration tests, but the code itself is BFB. New baselines will need to be added.

**Comment by whannah1** [comment]
I updated the text to mention that it's non-BFB

**Comment by whannah1** [comment]
Updated the branch to address a couple minor conflicts created by recent PRs.

**Comment by brhillman** [comment]
Merged to next.

**Comment by brhillman** [comment]
Merged to master.

**Pull request merged**
