### PR TITLE
remove seq_flds dependency for mpas_moabmesh

### PR DESCRIPTION
**Pull request by iulian787**
mpas framework should not depend on driver-moab/shr
mpas ocean cannot be built in standalone mode with MOAB, because of this

[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
@iulian787 -- do we need to do something similar for mpas-albany-landice? Or has moab not been integrated for all components?

**Comment by rljacob** [comment]
We haven't done land ice yet.

**Comment by rljacob** [comment]
I mean we have not integrated MOAB to land ice so nothing to do there in this PR.

**Comment by rljacob** [comment]
@sbrus89 can you approve this?

**Review by jonbob — APPROVED** [review]
Approved based on a quick sanity test and visual inspection

**Review by sbrus89 — APPROVED** [review]
Approved based on successful standalone compilation on Perlmutter.

**Comment by rljacob** [comment]
merged to next

**Pull request merged**
