### PR TITLE
Update LISIO test to include ocn-glcshelf coupling

### PR DESCRIPTION
**Pull request by matthewhoffman**
This PR replaces the MPAS_LISIO_TEST ("LandIce-SeaIce-Ocean") test with a new compset that is more up to date and updates test coverage for OCN-GLC coupling work in development.  It makes the following changes:
* updates compset and grid definition to use JRA1p5 data atmosphere instead of CORE II-NYF
* updates ocean mesh to use oQU240wLI mesh, which is cheaper and includes ice-shelf cavities
* introduces a testmod that activates ocn-glcshelf coupling. That coupling was added in PR https://github.com/E3SM-Project/E3SM/pull/2726, but a test was never added.

The PR also includes a small MPAS-Ocean bug fix that activating ocn-glcshelf coupling revealed.

### CODE REVIEW

**Comment by xylar** [comment]
Refer to https://github.com/E3SM-Ocean-Discussion/E3SM/pull/95 for additional discussion.

**Comment by jonbob** [comment]
@matthewhoffman - we might want to make the description more obvious that we're replacing the MPAS_LISIO_TEST compset and not just updating it

**Review by jonbob — APPROVED** [review]
Approved based on visual inspection and testing

**Comment by jonbob** [comment]
Passes:
* SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.chrysalis_intel.mpaso-jra_1958
* ERS_Ld5.T62_oQU120.CMPASO-NYF.chrysalis_intel
* ERS_Ld5.TL319_oQU240wLI_ais20.MPAS_LISIO_JRA1p5.chrysalis_intel.mpaso-ocn_glcshelf (new test)

merged to next

**Comment by jonbob** [comment]
merged to master and new test blessed except on pm-cpu developer_gnu, which has not yet reported

**Comment by jonbob** [comment]
Also blessed new test on pm-cpu developer_gnu

**Pull request merged**
