### PR TITLE
updates machine file to update module settings on Crusher

### PR DESCRIPTION
**Pull request by grnydawn**
module updates including:

* cce/15.0.0
* cray-hdf5-parallel/1.12.2.1
* cray-netcdf-hdf5parallel/4.9.0.1
* cray-parallel-netcdf/1.12.3.1

No baseline is supported on Crusher yet.

[non-BFB]

### CODE REVIEW

**Comment by sarats** [comment]
With cce 15.0.0, just check if you encounter runtime errors like the following: 
```
  1  0: /home/jenkins/crayftn/craylibs/google-perftools/src/tcmalloc.cc:647] Attempt to free invalid pointer: 0xd4c7f60
```

**Review by sarats — APPROVED** [review]

**Comment by dqwu** [comment]
@grnydawn @sarats
To fix recent spio build errors on Crusher, please consider downgrading CMake from 3.23.2 to 3.21.3 for Crusher, thanks.

**Review by amametjanov — APPROVED** [review]
This appears to be okay.

**Comment by grnydawn** [comment]
Closing this PR because all the changes in this PR are merged into master from sarats/machinefile/frontier.

**Pull request closed without merging**
