### PR TITLE
Update modules for chicoma-cpu

### PR DESCRIPTION
**Pull request by xylar**
Several modules are no longer available after a recent machine upgrade.

### CODE REVIEW

**Comment by xylar** [comment]
I tested this on Chicoma on Aug 31st: https://github.com/E3SM-Ocean-Discussion/E3SM/pull/62#issuecomment-1700811583

But it certainly needs to be retested.  I unfortunately don't have time to do it now.

**Comment by jonbob** [comment]
Thanks @xylar! I'll do some quick testing

**Review by rljacob — APPROVED** [review]

**Comment by jonbob** [comment]
Passes:
* SMS.ne11_oQU240.WCYCL1850NS.chicoma-cpu_gnu
* SMS_D.ne11_oQU240.WCYCL1850NS.chicoma-cpu_intel

**Review by jonbob — APPROVED** [review]
Approved based on testing

**Comment by jonbob** [comment]
sanity tested, passes:
* ERS_Ld5.T62_oQU240.DTESTM.chrysalis_intel
* ERS.ne11_oQU240.WCYCL1850NS.chrysalis_intel

merged to next

**Comment by jonbob** [comment]
merged to master

**Comment by xylar** [comment]
Thanks so much, @jonbob

**Pull request merged**
