### PR TITLE
Reduce ELM test build times with shared executables

### PR DESCRIPTION
**Pull request by amametjanov**
Reduce ELM test build times with shared executables: e.g. on Chrysalis
- before: 74 mins
- after: 17 mins (4x faster)

[BFB]

Testing with baseline comparisons: https://my.cdash.org/viewTest.php?buildid=2124812

### CODE REVIEW

**Comment by rljacob** [comment]
So you split land_developer in to (4 or so) suites that can share an executable?   I wonder why they can't all share one executable?

**Comment by amametjanov** [comment]
Initial attempt to have all cases share one executable produced 3 run fails, 10 diffs: https://my.cdash.org/viewTest.php?buildid=2123943 .

Building of `e3sm_integration` is taking several hours: e.g.
- Chrysalis+intel: 184 mins
- Ascent+gnu: 126 mins
- Ascent+ibm: 262 mins
- Ascent+pgi: 352 mins

**Comment by rljacob** [comment]
Are those timings after your mods to the land_developer suite?

**Comment by amametjanov** [comment]
No, these timings are with master.

**Review by peterdschwartz — APPROVED** [review]

**Pull request merged**
