### PR TITLE
fixes OpenACC bugs introduced by recent layerThickEdge changes

### LINKED ISSUE #4865: Missing layerthicknessedge decl with pgigpu
With the latest `next` branch, nvfortran is raising a build error on Summit and [Ascent](https://my.cdash.org/viewTest.php?buildid=2148166) for
```
./cime/scripts/create_test SMS_Ld1.T62_oEC60to30v3.CMPASO-NYF --compiler pgigpu
```
which appears to be from conversion of `layerThicknessEdge` to `layerThicknessFlux` in E3SM-Project/E3SM#4832.
```
NVFORTRAN-S-0038-Symbol, layerthicknessedge, has not been explicitly declared (
/gpfs/alpine/cli115/proj-shared/azamat/e3sm_scratch/SMS_Ld1.T62_oEC60to30v3.CMPASO-NYF.summit_pgigpu.20220331-hadv-openacc/bld/cmake-bld/core_ocean/shared/mpas_ocn_thick_hadv.f90: 140)

140       !$acc parallel loop &
141       !$acc     present(tend, normalVelocity, dvEdge, layerThicknessEdge, edgeSignOnCell, &
142       !$acc     minLevelEdgeBot, maxLevelEdgeBot) &
143       !$acc     private(i, k, invAreaCell, flux)
144       do iCell = 1, nCellsOwned
145         invAreaCell = 1.0_RKIND / areaCell(iCell)
146         do i = 1, nEdgesOnCell(iCell)
147           iEdge = edgesOnCell(i, iCell)
148           do k = minLevelEdgeBot(iEdge), maxLevelEdgeTop(iEdge)
149             flux = normalVelocity(k, iEdge) * dvEdge(iEdge) * layerThickEdgeFlux(k, iEdge)
150             tend(k, iCell) = tend(k, iCell) + edgeSignOnCell(i, iCell) * flux * invAreaCell
151           end do
152         end do
153       end do
```
FYI ^@brian-oneill

### PR DESCRIPTION
**Pull request by philipwjones**
During a recent addition of layerThickEdgeFlux/Mean variables, some GPU errors were introduced

   - layerThickEdgeXXX vars were missing from some OpenACC update directives
   - the use of array syntax when layerThickEdgeFlux set to
     layerThickEdgeMean was causing the operation to happen on
     host (with bad data) rather than device when OpenACC turned on
   - replaced complicated string conditionals with case construct to improve performance and clarity
   - the conditionals above were moved to diagnostics init
   - cleaned up the thickness edge routine a little
   - fixed related OpenACC present data issues in surface pressure calculation by moving option conditionals outside loop and splitting loop accordingly

Tested on Summit w/ PGI in QU240 and bfb when OpenACC turned on

Fixes #4865 
[BFB]

### CODE REVIEW

**Comment by philipwjones** [comment]
Also passes compass pr test suite on Chrysalis/Intel

**Review by cbegeman — APPROVED** [review]
@philipwjones Thanks for making these fixes. I ran the `drying_slope` test case, which uses the upwinding capabilities, on cpu on badger with this branch and all looks good.

**Review by mark-petersen — APPROVED** [review]
Passes nightly regression stand-alone with gnu and intel, both in debug.

**Review by amametjanov — APPROVED** [review]
Passes E3SM GPU test with this PR merged into latest `next` locally:
```
[azamat@login4.summit E3SM-summit]$ git log --merges -n 1 | grep Merge:
Merge: 5fc3f63afb ac5cf5a409

[azamat@login4.summit E3SM-summit]$ ./cime/scripts/create_test SMS_Ld1.T62_oEC60to30v3.CMPASO-NYF --compiler pgigpu --test-id 0405 &
```

**Comment by jonbob** [comment]
Test merge passes:
* SMS_D_Ld3.T62_oQU120.CMPASO-IAF.chrysalis_intel
* ERS.ne11_oQU240.WCYCL1850NS.chrysalis_intel

merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
