### PR TITLE
Adds reservoir stratification to MOSART-heat

### PR DESCRIPTION
**Pull request by bishtgautam**
The new module is able to better simulate the effect of reservoirs on stream
temperature seasonality and amplitude.

- The stratification flag (rstraflag) should be set to "true" in "user_nl_mosart" for the scheme to be active
- Inflow/outflow are considered for the advection process
- A new reservoir dataset (geometry, number of layers, and outlet location) is also prepared.
- These reservoir parameters can be modified by users(for example, reservoir outflow location).
  If required and/or additional reservoir data observation is available.
- User can also specify initial reservoir temperature(inittemp), vertical discretization points
  for reservoir geometry (ngeom), and the maximum number of layers allowed (layers)

[BFB]

### CODE REVIEW

**Comment by bishtgautam** [comment]
@jgfouca Need your review for CIME changes.
@jqyin Need your review for MOSART changes.

**Comment by rljacob** [comment]
So how are you doing the cime changes?  Are they on their own branch which this PR switches the submodule to?

**Comment by jgfouca** [comment]
@bishtgautam , i'm unable to review your CIME changes since the submodule pointer update in this PR has a bunch of stuff unrelated to your work. Please make a CIME PR and add me as a review for that.

**Comment by bishtgautam** [comment]
Here the commit-graph of CIME
```
*   9a4936785 (HEAD, origin/master, origin/HEAD, bishtgautam/mosart/stratification) Merge pull request #3627 from ESMCI/bishtgautam/mosart/stratification
|\
| * 4bfc27d7a (origin/bishtgautam/mosart/stratification) Modifications in MCT to support MOSART stratification
* |   7b238f284 (origin/container-development-bd) Merge pull request #3628 from ESMCI/whannah/add_ne45_support
|\ \
| * | 9f41556de Add default ATM_NCPL=72 for ne45 (E3SM)
* | |   8e4329c1f Merge pull request #3632 from ESMCI/jgfouca/remove_e3sm_subtree_mgmt_code
|\ \ \
| * | | 5d63604a9 Remove E3SM CIME subtree managent tools and libraries
|/ / /
* | | a82674b68 Emergency hotfix for e3sm
* | |   e1ae39f25 Merge pull request #3626 from ESMCI/jgfouca/scream_cime
|\ \ \
| |/ /
|/| |
| * | 7a8f69812 disable unused arg pylint warning
| * | f440b0761 CIME changes to support SCREAM
* | |   cf6c5c3df Merge pull request #3624 from mnlevy1981/update_highres_maps
|\ \ \
| |/ /
|/| |
| * | ee424328e Update TL319 -> tx0.1v3 ATM2OCN map
* | |   df201d467 (master) Merge pull request #3622 from ESMCI/jgfouca/fix_clean
|\ \ \
| * | | ec84995a9 (origin/jgfouca/fix_clean) Minor fix to get_case
| * | | 2e2ff6bfb Fix pylint errs
| * | | f0febd06c Make _create_test return casedirs, add build clean test
| * | | d8514b8c1 Fix build clean for e3sm
| | |/
| |/|
* | |   0d2b31adf Merge pull request #3625 from ESMCI/jgfouca/fix_false_pass
|\ \ \
| |/ /
|/| |
| * | 677a278ba Minor fix
| * | 49d51ffeb Make hist_utils a bit more robust to existing cprnc.out files
|/ /
* |   893441098 Merge pull request #3620 from ESMCI/PET_test_system_tests_common_fix
```

When I started my branch in E3SM, the CIME submodule was at `893441098`. I created a branch in CIME and made the `4bfc27d7a` commit. I issued PR-https://github.com/ESMCI/cime/pull/3627 for my code modifications and my branch was merged to CIME master (`9a4936785`). 

Then, in my E3SM branch, I updated the CIME submodule to `9a4936785` because this commit is on a CIME master not on CIME branch and we (E3SM) want to track CIME master and not a branch in CIME. But, I do understand my PR is bringing in additional CIME commits such as `0d2b31adf`, `df201d467` etc. What is the best workflow to bring E3SM-related CIME changes in E3SM? Should there be a branch in CIME (say `master-for-e3sm`) in which we merge E3SM-related CIME changes via PR and also merge those changes in CIME master?

**Comment by jgfouca** [comment]
@bishtgautam , the workflow is to make a PR to ESMCI/CIME first, get it accepted and merged to master, then update the submodule to latest master in your PR or just wait for me to update the sub which I do frequently.

**Comment by bishtgautam** [comment]
In that case, this PR is updating the CIME submodule to a latest ESMCI/CIME master.

**Comment by jgfouca** [comment]
@jqyin  , I'm already integrating a cime update, so your PR will have a conflict. Just take what's on next/master for cime when you integrate this.

**Comment by bishtgautam** [comment]
Let me rebase the branch of the latest master.

**Comment by bishtgautam** [comment]
just realized that #3747, which updates the CIME submodule, is only on next. So, rebasing is will not work. Let's wait till #3747 is merged to master and then I will rebase this branch

**Comment by jgfouca** [comment]
@bishtgautam , it's in master now.

**Comment by bishtgautam** [comment]
I have forced pushed my branch and it now only contains MOSART-related changes.

**Review by hydrotian — APPROVED** [review]

**Comment by rljacob** [comment]
@bishtgautam I'm going to let you self integrate this since its been reviewed by others.

**Pull request merged**
