### PR TITLE
Fix an issue in nudging code

### PR DESCRIPTION
**Pull request by zhangshixuan1987**
This commits addresses two issues in nudging code (PR#4098)

  1. Generally a user would like to run with nudging turned on if a nudging data file
     is mentioned in the namelist. However, current nudging code would allow the model
     to continue to run even if the nudging data file is not found. The code changes are
     made to add an endrun call so that the model exists with an error message if
     nudging file is not found rather than silently (or with a warning) continuing with
     the nudging turned OFF.
  2. The character length of the nudging file name is defined as 80 in current nudging.f90.
     If the nudging file name is longer than 80 characters, the nudging code can not
     get the full name for the nudging file. In this way, nudging will not be applied.
     To avoid this problem, code changes are made to extend the character length of
     the nudging file name to 256.

[BFB]: no impact on other tests.

### CODE REVIEW

**Review by kaizhangpnl — APPROVED** [review]

**Comment by golaz** [comment]
@rljacob : while we don't need this specifically for the v2 Water Cycle simulation campaign, this PR should still be on the future maint-2.0 branch since some users will want to use the nudging capability with v2.

**Comment by rljacob** [comment]
Ok.
We should think about adding a test with nudging on.

**Review by rljacob — APPROVED** [review]

**Review by tangq — APPROVED** [review]

**Comment by rljacob** [comment]
The old warning message has me curious:  "analyses file NOT FOUND. Switching nudging OFF to coast thru the gap."  What was the use case where they wanted this behavior?  Was it just a run length that was longer than the nudging period?

**Comment by tangq** [comment]
@rljacob , there are user name list variables to control the start and end dates of nudging, so the code can handle the simulation length longer than the nudging period (a typical application of nudging runs). I guess it is more likely for the cases when the nudging files have missing dates.

Since the nudging files are normally created from analysis/reanalysis files, it's out of our control if there are missing dates. Thinking this a bit more, we may want to add a name list variable for this. For example, nudging_file_all_exist is 1) true, then end run if some nudging files are not found within the nudging period; 2) false, then continue with a warning message (old behavior).

@rljacob, what do you think?

**Comment by zhangshixuan1987** [comment]
> The old warning message has me curious: "analyses file NOT FOUND. Switching nudging OFF to coast thru the gap." What was the use case where they wanted this behavior? Was it just a run-length that was longer than the nudging period?

@rljacob:  I do not know the use case for the developer who added this warning information. But one scenario in my mind is that nudging with incomplete reanalysis data, say, if your nudging window is 6-h, but we only have analysis at 00z, 06z, and 18Z, while the analysis data at 12z is missing. If you still want to run the model with nudging using only the available analysis, then the old way is one option. However, I do not think this is a clean way for nudging simulation.

**Comment by zhangshixuan1987** [comment]
> Since the nudging files are normally created from analysis/reanalysis files, it's out of our control if there are missing dates. Thinking this a bit more, we may want to add a name list variable for this. For example, nudging_file_all_exist is 1) true, then end run if some nudging files are not found within the nudging period; 2) false, then continue with a warning message (old behavior).

**Comment by zhangshixuan1987** [comment]
> @rljacob , there are user name list variables to control the start and end dates of nudging, so the code can handle the simulation length longer than the nudging period (a typical application of nudging runs). I guess it is more likely for the cases when the nudging files have missing dates.
> 
> Since the nudging files are normally created from analysis/reanalysis files, it's out of our control if there are missing dates. Thinking this a bit more, we may want to add a name list variable for this. For example, nudging_file_all_exist is 1) true, then end run if some nudging files are not found within the nudging period; 2) false, then continue with a warning message (old behavior).
> 
> @rljacob, what do you think?

Hi @tangq: I think that @tangq's idea is one option, but I think that this may also

**Comment by rljacob** [comment]
Take a look at this statement around line 1691:
 if(.not.Nudge_File_Present) return

Maybe that is the place for a fatal error if the nudging file isn't found.

**Comment by tangq** [comment]
> > @rljacob , there are user name list variables to control the start and end dates of nudging, so the code can handle the simulation length longer than the nudging period (a typical application of nudging runs). I guess it is more likely for the cases when the nudging files have missing dates.
> > Since the nudging files are normally created from analysis/reanalysis files, it's out of our control if there are missing dates. Thinking this a bit more, we may want to add a name list variable for this. For example, nudging_file_all_exist is 1) true, then end run if some nudging files are not found within the nudging period; 2) false, then continue with a warning message (old behavior).
> > @rljacob, what do you think?
> 
> Hi @tangq: I think that your idea is one option, but would this also add a potential danger that: if the users set nudging_file_all_exist = false., and turn on nudging, the model is still allowed to continue to run even if the nudging data file is not found.

@zhangshixuan1987 , the difference is that if the user sets the additional flag nudging_file_all_exist = false (default value is true), the user is expected to know that turning nudging on alone doesn't guarantee nudging is effective and the user has checked that not all the nudging files exist and decide to set nudging_file_all_exist = false.

I agree that there is no perfect way to handle all the nudging scenarios, but some flags like this one can avoid misuse of nudging to an extent.

**Comment by zhangshixuan1987** [comment]
> nudging_file_all_exist

Hi @tangq : I agree with you. I think that the users at least know what will happen by setting  "nudging_file_all_exist = .false." (i.e. allow nudging to continue even if the nudging file does not exist). I have a question regarding the name of this flag, would it be better to name it "nudging_allow_mising_file" ?

**Comment by rljacob** [comment]
Is this supposed to be merged after #4098?   Why not just add commits to #4098?

**Comment by rljacob** [comment]
Oh I see, #4098 is for maint-1.0

**Comment by tangq** [comment]
@zhangshixuan1987 , I like your suggestion about the flag name.

**Comment by golaz** [comment]
What's the status of this?

**Comment by zhangshixuan1987** [comment]
@golaz: Hi Chris, I think the PR is ready to merge.

**Review by singhbalwinder — APPROVED** [review]

**Comment by singhbalwinder** [comment]
I will start merging this once the repo opens.

**Comment by singhbalwinder** [comment]
Merged to next

**Pull request merged**
