### PR TITLE
Update CIME submodule

### PR DESCRIPTION
**Pull request by jgfouca**
to ad68a5d352c98207a05c350e7929be12fb9476f6

Changes:
1) Update case status to include jobid on batch system
2) allows WAV to be identified as the primary component for compsets with WAVEWATCH III
3) Drop support for python2!!
4) Adds git submodule info to provenance
5) Reset a test that is rerun after a run failure
6) if DIN_LOC_ROOT does not exist, create it
7) Adds feature to capture CIME commands in a script, replay.sh in $CASEDIR
8) Switch location of E3SM share buildlib scripts
9) Modify ERI test for EAM: ERI will edit user_nl_cam to run.

Fixes:
1) fix py3 error in srun syntax
2) Fixes phase 1 of multisubmit not executing during rerun

[BFB]

### CODE REVIEW

**Review by rljacob — CHANGES_REQUESTED** [review]
Need to update to ad68a5d352c98207a on CIME master.

**Comment by jgfouca** [comment]
@rljacob , good catch. Thought I was on latest master. I force pushed an update.

**Comment by rljacob** [comment]
You need to update the PR description.

**Comment by jgfouca** [comment]
@rljacob , done.

**Review by rljacob — APPROVED** [review]

**Comment by jgfouca** [comment]
Merged to next.

**Pull request merged**
