### PR TITLE
Fix hommexx+eam build

### PR DESCRIPTION
**Pull request by oksanaguba**
Fixing preqxx build in eam. Add thetaxx tests to skybridge hommebfb suite.

[nonbfb] for skybridge hommebfb suite because of new tests.

### CODE REVIEW

**Comment by AaronDonahue** [comment]
@oksanaguba,  I wanted to check in on the status of this PR.

**Comment by oksanaguba** [comment]
Current commit was built on anvil. I will run this on skybridge for hommebfb suite.

**Comment by oksanaguba** [comment]
skybridge run was ok, this is ready and can be merged tomorrow.

**Comment by oksanaguba** [comment]
@AaronDonahue this is ready, if you want i can merge it myself tomorrow.

**Comment by AaronDonahue** [comment]
@oksanaguba, I'm happy to integrate.  Should it be reviewed first?

**Comment by oksanaguba** [comment]
@AaronDonahue please, don't merge today. there is another homme pr in next right now. tomorrow should work.

about review, i don't see who would review it, maybe, @ambrad .

**Comment by AaronDonahue** [comment]
I think because it just adds tests it might not actually need review.  @rljacob would it be alright to proceed with integration tomorrow without review?

**Comment by rljacob** [comment]
Yes that's fine.

**Review by ambrad — APPROVED** [review]

**Comment by AaronDonahue** [comment]
@oksanaguba , it looks like next is open.  I'm guessing everything went well with the homme PR yesterday and I can start integrating this PR?

Also, do we expect to need new baselines after this PR goes in?

**Comment by oksanaguba** [comment]
This can be merged. New baselines will be needed on skybridgebecause of new tests.

**Comment by AaronDonahue** [comment]
This has been merged to next

**Comment by AaronDonahue** [comment]
@oksanaguba , just to confirm that the test that needs new baselines is `HOMMEBFB_P24.f19_g16_rx1.A.sandiatoss3_intel` which is now failing in the test suite `homme_integration_next_intel`

**Pull request merged**
