### PR TITLE
Update CIME submodule again

### PR DESCRIPTION
**Pull request by jgfouca**
Change list:
* Remove E3SM CIME subtree managent tools and libraries
* Add default ATM_NCPL=72 for ne45
* Modifications in MCT-driver to support MOSART stratification (adds  coszen field)
* Archive atm_chunk_costs with other performance data

Bug fixes:
* Use SRCROOT instead of CIMEROOT in key places

[BFB] - but adds a new field, so tests will DIFF

### CODE REVIEW

**Comment by rljacob** [comment]
Adds a new field to what?   We're going to need more info on these submodule update PRs.

**Comment by jgfouca** [comment]
@rljacob , done

**Comment by rljacob** [comment]
I'm not sure all tests will diff.  Just ones with MOSART.

**Comment by jgfouca** [comment]
@rljacob, my "A" compset tests were diffing

**Comment by jonbob** [comment]
@jgfouca - that's expected if you're now passing a new field through the cpl. The A-cases dummy up data to pass based on the number of fields

**Comment by jgfouca** [comment]
Thx @jonbob

**Comment by rljacob** [comment]
That's the X-case.  The A-case is all data models but I think one of those was modified to send the new field even if there is no full MOSART model.

**Comment by jonbob** [comment]
Sorry -- @rljacob is completely correct. My bad...

**Comment by jgfouca** [comment]
> The A-case is all data models but I think one of those was modified to send the new field even if there is no full MOSART model.

@rljacob , @jonbob , is that something we need to change before merging this PR?

**Comment by jonbob** [comment]
@jgfouca - what did the A-case DIFFs look like? Do you have the output from cprnc?

**Comment by rljacob** [comment]
@jgfouca no you don't need to change anything.

**Comment by jgfouca** [comment]
@jonbob, they just reported that the hist file had an extra field when compared to the baseline. There were no "real" diffs.

@rljacob , thanks, I will merge to master.

**Pull request merged**
