### PR TITLE
Corrects thin ice/snow treatment of enthalpy and other tracers

### LINKED ISSUE #5124: MPAS-SI crashes on small timesteps
See issue #5072: "MPAS-SI crashes when running in thermodynamic mode (F cases) with small time steps."
When dtime=1, as used in the time step convergence (TSC) test, an issue occurs with MPAS-SI at a particular time step.

It seems to depend on input data, as for different initial atmosphere / land conditions causes the problem to appear at different time steps (https://github.com/E3SM-Project/E3SM/issues/5072#issuecomment-1191829234).

### PR DESCRIPTION
**Pull request by njeffery**
This fix redistributes enthalpy and other tracers evenly in snow and ice when their respective thicknesses are  < 1e-15 . Previously, these tracers were zero'd non-conservatively.

Also corrects a bug in the zeroing of snow thicknesses, and removes snow in thickness_changes if the ice vanishes.

Fixes #5124 

[non-BFB]

### CODE REVIEW

**Comment by njeffery** [comment]
Code was tested in a 15-year fully coupled simulation.  MPAS-Analysis of the sea ice can be found here: https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.jeffery/E3SMv2/thin-ice-enthalpy-constant-feature-snow/

Baseline is thin-ice-enthalpy-constant-master
Feature branch is thin-ice-enthalpy-constant-feature-snow

**Comment by njeffery** [comment]
Plots of salt, mass and energy conservation :

[ConservationComparison_FeatureplusSnowMaster.pdf](https://github.com/E3SM-Project/E3SM/files/11314443/ConservationComparison_FeatureplusSnowMaster.pdf)

**Comment by njeffery** [comment]
@jonbob :  Could you make sure this fixes issue #5124

**Comment by jonbob** [comment]
testing now -- thanks @njeffery

**Comment by jonbob** [comment]
@njeffery - this branch does pass my simplified test for the originally reported bug

**Comment by njeffery** [comment]
Great!  thanks @jonbob.

**Review by eclare108213 — APPROVED** [review]

**Comment by jonbob** [comment]
@proteanplanet - when you get a chance, could you please review this? Thanks

**Comment by jonbob** [comment]
Successfully completes, but shows expected DIFFs for:
* SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod
* ERS.ne11_oQU240.WCYCL1850NS.chrysalis_intel
* PET_Ln5.T62_oQU240.DTESTM

merged to next

**Pull request merged**
