### PR TITLE
update mpas-source: Move surface pressure and zMid before EOS

### PR DESCRIPTION
**Pull request by mark-petersen**
See https://github.com/MPAS-Dev/MPAS-Model/pull/796. Computations are identical, just moves computations before EOS for future EOS development.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
passes
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PEM_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-haswell_gnu
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
```
In MPAS stand-alone, passes nightly regression on grizzly with optimized and debug, both gnu 5.2 and intel 17. Compares bfb with ocean/develop with optimized gnu and intel for nightly regression suite.

**Review by jonbob — APPROVED** [review]
Looks good, based on visual inspection and development testing

**Comment by jonbob** [comment]
@mark-petersen - this branch doesn't match the naming convention. Could you please next time remember to include "ocean"?

**Comment by jonbob** [comment]
merged to next

**Comment by mark-petersen** [comment]
> Could you please next time remember to include "ocean"?

Yes, will do.

**Comment by jonbob** [comment]
merged to master

**Comment by xylar** [comment]
Thanks very much @jonbob and @mark-petersen for shepherding this work through the complicated workflow.  It's very much appreciated!

**Pull request merged**
