### PR TITLE
[WIP] Adds support for DATM=CLM1PT

### PR DESCRIPTION
**Pull request by bishtgautam**
Restores the support of user-defined atmospheric forcing for ELM
that was broken during renaming of the land model.

[BFB]

### CODE REVIEW

**Comment by bishtgautam** [comment]
This PR will be rebased once the https://github.com/ESMCI/cime/pull/3845 is merged to CIME master and the CIME submodule in E3SM is updated. Then, a new test will be added for `DATM=CLM1PT`.

**Comment by rgknox** [comment]
Sorry I missed this review request, I will give it a try.

**Comment by bishtgautam** [comment]
Closing this PR because the CIME changes in this PR are now in E3SM master.

**Comment by rgknox** [comment]
This worked for me, thanks @bishtgautam

**Pull request closed without merging**
