### PR TITLE
update mpas-source: stand-alone ocean output to single precision

### PR DESCRIPTION
**Pull request by mark-petersen**
Change stand-alone default streams to single precision. Does not alter E3SM streams file. See https://github.com/MPAS-Dev/MPAS-Model/pull/414

[BFB]

### CODE REVIEW

**Review by jonbob — APPROVED** [review]
Looks good by visual inspection, and will test during the merge

**Comment by mark-petersen** [comment]
passes `SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu`

**Comment by jonbob** [comment]
passed anvil sanity testing, merged to next

oops, this comment never went out?

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
