### PR TITLE
update mpas-source: COMPASS only

### PR DESCRIPTION
**Pull request by mark-petersen**
Update COMPASS initialization scripts. Does not affect E3SM simulations.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
The merge order needs to be: #3391, #3561, #3560.

**Comment by mark-petersen** [comment]
Changed this one to be after #3560.

**Comment by mark-petersen** [comment]
Rebased this branch, and updated mpas-source. It is still only COMPASS files, plus the one line change in #3560 so it can go in after that.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master -- but curious why it's not showing up here already

**Pull request merged**
