### PR TITLE
Fix multi-instance specifier string

### LINKED ISSUE #2427: Unexpected multi-instance infile names
The pythonization of the pearl `components/*/cime_config/buildnml` scripts changed the multi-instance component infile names to the form `COMPONENT_inNINST` instead of the previous `COMPONENT_in_NINST`. 

This leads to errors like: 
```
FIO-F-209/OPEN/unit=97/'OLD' specified for file which does not exist.            
File name = atm_in_0001
In source file $E3SM/components/cam/src/control/runtime_opts.F90, at line number 394
```
When I run cases using the multi-instance capability. 

Which form should the infile names take? 
**New:** `COMPONENT_inNINST`
**Old:** `COMPONENT_in_NINST`

I expect that the old form should be maintained. 

---

Note: the pythonization happened across multiple component specific PRs:
 
PR #2364 via commit ef9e9580 
PR #2363 via commit c56babcf 
PR #2355 via commit 52c654ea 
PR #2347 via commit a9cb397b 
PR #2344 via commit c41bcb69 
PR #2342 via commit 10d68b12 
PR #2335 via commit e4d9adfc 

I've already got a branch off of #2364 (see below) with the fix for all of the affected components, however, should I instead create create an individual bug-fix PR for each component?

### PR DESCRIPTION
**Pull request by jhkennedy**
The pythonization of the pearl `components/*/cime_config/buildnml` scripts changed the multi-instance specifier string from `_NINST`  to `NINST`.  This leads to unexpected file names, like `atm_in0001` instead of `atm_in_0001`, and errors like:

```
FIO-F-209/OPEN/unit=97/'OLD' specified for file which does not exist.            
File name = atm_in_0001
In source file $E3SM/components/cam/src/control/runtime_opts.F90, at line number 394
```
when using the multi-instance capability. 

Importantly, the bug was only found in the active components, not the data models, so the multi-instance test `NCK.f19_g16_rx1.A` in the `e3sm_developer` test set did not pick it up. I've added `NCK.ne4_oQU240.A_WCYCL1850` to the `e3sm_integration` set, which is an all-active compset and should catch issues with any of the multi-instance components. (Note, because there is a `buildnml` script per component, we need an all-active test to test them all.) 

Fixes #2427

[B4B]

### CODE REVIEW

**Comment by rljacob** [comment]
Do you know how long that new test takes to run?

**Comment by jhkennedy** [comment]
@rljacob about 20 min (walltime) on Titan w/ 32 procs. I'm not married to a particular grid or compset; it could be a single active component, but that would assume that any changes to the multi-instance build are applied uniformly across the components. That's probably okay, but is a clear error path, especially when changes come in multiple PRs.

**Comment by jgfouca** [comment]
Thanks, @jhkennedy

**Comment by jgfouca** [comment]
Merged to next.

**Comment by rljacob** [comment]
The new test didn't pass so this should not have been merged to master.

**Pull request merged**
