### PR TITLE
Adding Land Use Translator code

### PR DESCRIPTION
**Pull request by lchini**
The Land Use Translator (LUT) converts either historical or future land-use data 
(in Land-Use Harmonization 1 format) into land cover changes in terms of 16 different 
plant functional types. The output of the LUT is used by mksurfdata for generating 
surface files for E3SM. This version of the LUT does not directly interact with the 
E3SM code - it is just a tool that generates inputs for E3SM. This version of the LUT
 is modified from the version used for iESM and from the original version created by
 Peter Lawrence, although it still retains a significant amount of code from those versions.

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
@bishtgautam are the changes ok?

**Comment by bishtgautam** [comment]
@rljacob, There are a few more changes that I would like to request (i.e. remove hard-coding of the path the inputdata, add a makefile).

**Comment by rljacob** [comment]
@lchini please make requested changes ASAP.

**Comment by bishtgautam** [comment]
@lchini made the requested changes and it is ready to be merged. I will merge it to next today.

**Comment by rljacob** [comment]
@bishtgautam please merge this to master.

**Pull request merged**
