### PR TITLE
Remove extra history write and reorg

### LINKED ISSUE #4519: Redundant code in cime_comp_mod.F90 associated with history write
In cime_comp_mod.F90 is the code

            !----------------------------------------------------------                                                                                                                                
            !| Write history file, only AVs on CPLID                                                                                                                                                   
            !----------------------------------------------------------                                                                                                                                
            call cime_run_write_history()
     
            if (iamin_CPLID) then
     
               call cime_comp_barriers(mpicom=mpicom_CPLID, timer='CPL:HISTORY_BARRIER')
               call t_drvstartf ('CPL:HISTORY',cplrun=.true.,barrier=mpicom_CPLID)
               if ( history_alarm) then
                  if (drv_threading) call seq_comm_setnthreads(nthreads_CPLID)
                  if (iamroot_CPLID) then
                     write(logunit,104) ' Write history file at ',ymd,tod
                     call shr_sys_flush(logunit)
                  endif
     
                  call seq_hist_write(infodata, EClock_d, &
                       atm, lnd, ice, ocn, rof, glc, wav, iac, &
                       fractions_ax, fractions_lx, fractions_ix, fractions_ox,     &
                       fractions_rx, fractions_gx, fractions_wx, fractions_zx, trim(cpl_inst_tag))
     
                  if (drv_threading) call seq_comm_setnthreads(nthreads_GLOID)
               endif
     
               if (do_histavg) then
                  call seq_hist_writeavg(infodata, EClock_d, &
                       atm, lnd, ice, ocn, rof, glc, wav, iac, histavg_alarm, &
                       trim(cpl_inst_tag))
               endif
     
          ...

While the routine cime_run_write_history is

       subroutine cime_run_write_history()
     
         !----------------------------------------------------------                                                                                                                                   
         ! Write history file, only AVs on CPLID                                                                                                                                                       
         !----------------------------------------------------------                                                                                                                                   
     
         if (iamin_CPLID) then
     
            call cime_comp_barriers(mpicom=mpicom_CPLID, timer='CPL:HISTORY_BARRIER')
            call t_drvstartf ('CPL:HISTORY',cplrun=.true.,barrier=mpicom_CPLID)
            if ( history_alarm) then
               if (drv_threading) call seq_comm_setnthreads(nthreads_CPLID)
               if (iamroot_CPLID) then
                  write(logunit,104) ' Write history file at ',ymd,tod
                  call shr_sys_flush(logunit)
               endif
     
               call seq_hist_write(infodata, EClock_d, &
                    atm, lnd, ice, ocn, rof, glc, wav, iac, &
                    fractions_ax, fractions_lx, fractions_ix, fractions_ox,     &
                    fractions_rx, fractions_gx, fractions_wx, fractions_zx, trim(cpl_inst_tag))
     
               if (drv_threading) call seq_comm_setnthreads(nthreads_GLOID)
            endif
     
            if (do_histavg) then
               call seq_hist_writeavg(infodata, EClock_d, &
                    atm, lnd, ice, ocn, rof, glc, wav, iac, histavg_alarm, &
                    trim(cpl_inst_tag))
            endif
     
            call t_drvstopf  ('CPL:HISTORY',cplrun=.true.)
     
         end if
     
     104 format( A, i10.8, i8)
       end subroutine cime_run_write_history

Note that the code in cime_run_write_history is identical to the code that immediately follows the call to cime_run_write_history, except for the terminating call to the CPL:HISTORY timer (t_drvstop). I am guessing that the subroutine call (and the subroutine) should be deleted since the code following the subroutine call continues, with the call to  t_drvstopf  ('CPL:HISTORY',cplrun=.true.) occurring after this additional code, but this is just conjecture on my part.

### PR DESCRIPTION
**Pull request by rljacob**
Move the auxilary history writes to the cime_run_write_history routine
and remove the duplicate regular history write from cime_run.  Add
one argument to cime_run_write_history

Fixes #4519

[BFB]

### CODE REVIEW

**Review by worleyph — APPROVED** [review]
Code changes pass visual inspection. Passed sanity check experiments: BFB numerically and history writes are no longer duplicated. Looks good.

**Comment by worleyph** [comment]
I don't know what the ci/circleci:build failure is about.

**Comment by rljacob** [comment]
The circle ci fail is because I started this branch when it was temporarily broken on master after #4488 was merged.

**Comment by rljacob** [comment]
merged to next

**Pull request merged**
