### PR TITLE
make vtheta_thresh a namelist variable

### PR DESCRIPTION
**Pull request by mt5555**
change default value of vtheta_thresh from 10K to 100K
Also add the ability to specify a different value in user_nl_eam

As this is very rarely triggered, labeling:
[BFB]

### CODE REVIEW

**Comment by mt5555** [comment]
on next

**Comment by golaz** [comment]
@mt5555 : can this be merged to master?

**Comment by rljacob** [comment]
I think it can be.  @mt5555 why wasn't there a namelist diff with this?

**Comment by golaz** [comment]
@rljacob : do you want to merge it?

**Comment by mt5555** [comment]
I can merge late this afternoon, if Rob doesn't do it first.

Took the morning off

**Comment by rljacob** [comment]
merged.

**Comment by mt5555** [comment]
FYI, there was no namelist diff because the option was only added to namelist_definition.xml (but not namelist_defaults and buildnml).    So a user can set it in user_nl_eam, but otherwise it wont appear in atm_in.   This is following existing practice for many of the esoteric atmosphere parameters that are only of interested to developers.

**Comment by oksanaguba** [comment]
This PR changed vtheta_thresh value from 10 to 100. The same change should have been done in 

src/theta-l_kokkos/cxx/CaarFunctorImpl.hpp

**Pull request merged**
