### PR TITLE
Add support for JRA55 forcing on oEC60to30v3wLI ocean grid.

### PR DESCRIPTION
**Pull request by darincomeau**
Adds support for JRA55 forcing (atmosphere and runoff) for the oEC60to30v3wLI ocean/sea-ice grid.

[BFB]

### CODE REVIEW

**Comment by darincomeau** [comment]
Here's a snapshot of the solid ice runoff from the coupler, to confirm that it is not sending runoff under ice shelves:

jra55_rofi_oEC60to30v3wLI

**Comment by rljacob** [comment]
Waiting on the next cime merge.

**Comment by darincomeau** [comment]
Given the JRA changes that came in with the latest cime merge, I'll need to update this once our existing JRA compsets have been updated.

**Comment by rljacob** [comment]
@darincomeau that cime merge happened so can you update this?

**Comment by darincomeau** [comment]
@rljacob sure - it's on my list this week to put together a broader PR to update JRA support given the recent cime merge, so it may make sense to close this PR and incorporate it there. Either way I'll get this resolved soon.

**Comment by darincomeau** [comment]
Given the changes to the JRA compset brought in by the latest cime merge, I'm going to close this and incorporate it into a new PR.

**Pull request closed without merging**
