### PR TITLE
Update cori machine files for maint-1.2

### LINKED ISSUE #3431: maint-1.2 does not build on Cori
Similar to #3304 , the maint-1.2 branch currently does not build on Cori, due to machine file updates and NERSC dropping support for python 2.7. The following PRs have necessary updates missing in maint-1.2:

Machine file updates: #3097 
Update python 3 in cvmix and BGC: #3308 

After cherry-picked commits from these PRs (and the relevant commits to mpas-source), I can get maint-1.2 to build on Cori-KNL.

### PR DESCRIPTION
**Pull request by jonbob**
This PR updates the cori machine files for maint-1.2 through cherry-picks from commits made to master:

- [#3097](https://github.com/E3SM-Project/E3SM/pull/3097)
- [#3404](https://github.com/E3SM-Project/E3SM/pull/3404)
- [#3476](https://github.com/E3SM-Project/E3SM/pull/3476)

as well as hand changes necessary to merge some changes that were inconsistent with this older version of the scripts.

Fixes #3431

[BFB] according to cherry-picked PR's

### CODE REVIEW

**Comment by jonbob** [comment]
passed SMS_D.T62_oQU240.GMPAS-IAF.cori-knl_gnu test

**Comment by darincomeau** [comment]
Successfully built and ran a GMPAS-DIB-IAF-ISMF.T62_oEC60to30v3wLI smoke test.
Note this does not build with python3, and we will need https://github.com/E3SM-Project/E3SM/pull/3308 to be brought into maint-1.2 as well.

**Comment by jonbob** [comment]
Also passed SMS.T62_oQU240.GMPAS-IAF.cori-knl_intel

**Comment by stephenprice** [comment]
Atta boy ...

On Mar 12, 2020, at 8:13 AM, Jon Wolfe <notifications@github.com<mailto:notifications@github.com>> wrote:


passed SMS_D.T62_oQU240.GMPAS-IAF.cori-knl_gnu test

**Comment by darincomeau** [comment]
For completeness, I also built GMPAS-DIB-IAF-ISMF.T62_oEC60to30v3wLI on cori-haswell and successfully ran a smoke test.

**Comment by jonbob** [comment]
merged to maint-1.2

**Pull request merged**
