### PR TITLE
Update component config files to support 1950 F compsets

### PR DESCRIPTION
**Pull request by wlin7**
Config files for CAM and data ocean components are updated to allow creation
of 1950 F compsets: F1950C5-CMIP6-LR, F1950C5-CMIP6-LRtunedHR and F1950C5-CMIP6-HR.
Use case files for CAM and CLM already exist from corresponding B-cases.

This update is to make the use cases recognized in F-case configuration.

New 1950 SSTICE climatology is introduced: sst_ice_CMIP6_DECK_E3SM_1x1_1950_clim_c20180910.nc

CLM's config_component.xml is also updated to recognize the specification of finidat
for F1950C5-CMIP6-LRtunedHR compset.

 modified:   cime/src/components/data_comps/docn/cime_config/config_component.xml
 modified:   components/cam/cime_config/config_compsets.xml
 modified:   components/clm/cime_config/config_component.xml

[BFB]

### CODE REVIEW

**Comment by wlin7** [comment]
Hi @PeterCaldwell  and @singhbalwinder , I am requesting you both to take a look.
Specifically for the change in clm/cime_config/config_component.xml:
 
Somehow I had to add a new entry 
         _<value compset="1950_CAM5%CMIP6-LRtunedHR_CLM">1950_CMIP6LR_control</value>_

in order  to automatically pick up the settings in 1950_CMIP6_LR_control for lnd for compset F1950C5-CMIP6-LRtunedHR. Supposed it is included in the wildcard in existing entry as follows,
           _<value compset="1950_CAM5%CMIP6-LR*_CLM">1950_CMIP6LR_control</value>_

If we figure out to make the wildcard work, I will reverse this change.

**Comment by singhbalwinder** [comment]
> Supposed it is included in the wildcard in existing entry as follows

Try using a `.` in front of `*`as follows in the above wildcard to see if it works:
`<value compset="1950_CAM5%CMIP6-LR.*_CLM">1950_CMIP6LR_control</value>`

**Comment by PeterCaldwell** [comment]
Hi @wlin7 - Thanks for working on this. I've also had problems with pattern matching in clm compset generation (#2396) but it worked the opposite way: the first match was always getting triggered even when it shouldn't have been. I have no idea for how to fix this (beyond hoping Balwinder's suggestion works) and am fine with merging it in its current slightly inelegant form.

**Comment by wlin7** [comment]
Thanks Balwinder and Peter for the quick review. The wildcard issue is a little strange. The regex looks reasonable. Balwinder's suggestion is nice and also used in other entries in CLM's config_component.xml. However, I am afraid it would cause new problem: can not recognize the 1950_CMIP6-LR, because the LR compset is defined as  "1950_CAM5%CMIP6-LR_CLM45" with no character between "LR" and "_CLM45". 

I will do some more tests. Maybe just "CMIP6-L.*_CLM45".  At worst, we can keep the change as is.

**Comment by wlin7** [comment]
@singhbalwinder  and @PeterCaldwell : Interestingly, the exact format suggested by Balwinder works out well for both %CMIP6-LR_CAM5 and %CMIP6-LRtunedHR_CAM5. I am now curious how the cime's parser treats the ".". In normal regex, ".*" is for one or more of any characters. In the current case, it appears even 0 character is ok.

**Comment by PeterCaldwell** [comment]
Thanks for the sleuthing, Wuyin! I looked around a bit but didn't dig deep enough. I'm glad to understand this.

**Comment by wlin7** [comment]
Merged to next.

**Comment by rljacob** [comment]
@jgfouca can you comment on parsing questions above?

**Comment by jgfouca** [comment]
@wlin7 @rljacob , CIME should be using standard regex syntax here. As you realized, ".*" is zero or more of any character, ".+" is one or more. Regex syntax is (mostly) consistent across languages. Whatever worked in Perl should work in Python.

**Pull request merged**
