### PR TITLE
Update machine files to match new directory names at NERSC

### PR DESCRIPTION
**Pull request by jonbob**
This PR updates the machine files to reflect directory name changes from "acme" to "e3sm" on cori-knl and cori-haswell. It was cherry-picked from #3516 with some other slight modifications.

Do not merge -- waiting for a test run to get through the queue

[BFB]

### CODE REVIEW

**Comment by darincomeau** [comment]
@jonbob thanks for bringing this in. I built and ran a GMPAS-DIB-IAF-ISMF.T62_oEC60to30v3wLI 5 day test successfully - any other testing you'd like me to do?

**Comment by jonbob** [comment]
How'd you beat me through the queues?? No, if you're happy then I'm happy, @darincomeau !

**Comment by stephenprice** [comment]
If this is the new 1.2 tag I'm happy to try out a B-case test at some point.

**Comment by darincomeau** [comment]
@stephenprice I think what you're really after is https://github.com/E3SM-Project/E3SM/pull/3513, which should be the last of the code changes needed to bring into 1.2.

**Comment by jonbob** [comment]
@stephenprice - I'll aim to get both PR's in as soon as possible, so hopefully we'll have something for you to test on Monday

**Comment by stephenprice** [comment]
Great. I'll look for it. Thanks

**Comment by jonbob** [comment]
@ndkeen - whenever you have a chance, could you please make sure this looks right to you? The cherry-pick of your commit wasn't clean and I just want to be sure

**Comment by jonbob** [comment]
@darincomeau - what compiler did you use for your test? So far my tests are passing with intel but failing with gnu...

**Comment by darincomeau** [comment]
> @darincomeau - what compiler did you use for your test? So far my tests are passing with intel but failing with gnu...

I only used intel - I'll try gnu now.

**Comment by jonbob** [comment]
@darincomeau - for what it's worth, I don't think the gnu problem is related to this PR...

**Comment by jonbob** [comment]
And it may be an issue mostly for CAM -- I tried a SMS.ne4_oQU240.A_WCYCL1850.cori-knl_gnu test and it fails when it's initializing the atm

**Comment by darincomeau** [comment]
> And it may be an issue mostly for CAM -- I tried a SMS.ne4_oQU240.A_WCYCL1850.cori-knl_gnu test and it fails when it's initializing the atm

Ah yeah I was only doing a G-case. My gnu case compiled, just waiting in the queue, but I suppose that won't be all that helpful.

**Comment by jonbob** [comment]
Thanks @ndkeen

**Comment by jonbob** [comment]
@darincomeau - it will still be useful to see if gnu has problems beyond CAM

**Comment by darincomeau** [comment]
Yeah the G-case with gnu did indeed die, I think at the first time step. I don't see any errors in the component logs, but from the e3sm.log:

``` 133: Program received signal SIGILL: Illegal instruction.
 133:
 133: Backtrace for this error:
 134: #0  0x20f205af in ???
 134:   at /home/abuild/rpmbuild/BUILD/glibc-2.26/nptl/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
 134: #1  0x204f3c2d in ???```

**Comment by jonbob** [comment]
Yeah, I saw similar things. But I'm pretty sure it has nothing to do with these paths -- so I'll get this PR in and maybe we can open an issue about gnu

**Comment by jonbob** [comment]
Oops, I put this in the wrong PR:
@ndkeen has an open issue about GNU being broken on cori (#3270)

**Comment by jonbob** [comment]
merged to maint-1.2

**Pull request merged**
