### PR TITLE
Add conusx4v1pg2_r05_IcoswISC30E3r5 resolution

### PR DESCRIPTION
**Pull request by jonbob**
Adds the conusx4v1pg2_r05_IcoswISC30E3r5 resolution to support moving testing to v3 meshes. Also updates the conusx4v1pg2 <-> r05 mapping files to the v3 naming and algorithm convention. All new mapping and domain files are staged in the inputdata repo.

[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
Successfully completed SMS_D_Ln5.conusx4v1pg2_r05_IcoswISC30E3r5.F2010.chrysalis_intel

**Comment by rljacob** [comment]
Instead of a separate PR, can you add this to rljacob/update-test-v3res ?

**Comment by jonbob** [comment]
@rljacob -- sure. I'll add it there and close this PR

**Comment by jonbob** [comment]
Adding to [PR #6202](https://github.com/E3SM-Project/E3SM/pull/6202) instead of separate PR

**Pull request closed without merging**
