### PR TITLE
Add oARRM60to10 tri-grid support

### PR DESCRIPTION
**Pull request by jonbob**
This PR adds support for ne30pg2_r05_oARRM60to10 and ne30pg2_r05_oARRM60to10_ICG configurations. The oARRM60to10 mesh was previously supported only for C- and G-compsets, so this adds fully-coupled capability.

[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
passed test-ARRM.A_WCYCL1850S.ne30pg2_r05_oARRM60to10.anvil

**Comment by stephenprice** [comment]
@jonbob, the 'cmip6' version of this is in the queue now on Grizzly. But the queues are so bad there right now that I won't likely know until next week (even a 5 day tests takes forever). I'll keep you posted.

**Comment by stephenprice** [comment]
Sorry for the long delay on this. My initial 5-day test case failed on Griz., in the atm. w/ this 

error: set_time_float_from_date: error return from ESMF_TimeSet for set_time_float_from_date
ERROR: CHKRC

Let me know if that means anything to you (I suspect not). I will go back and check over the case setup, build, etc. again this morning.

**Comment by jonbob** [comment]
@stephenprice - no worries. And what a shock, an ESMF problem! Please let me know if I should take a look at it as well...

**Comment by stephenprice** [comment]
You did not see similar on Anvil I'm assuming. Does that suggest an issue w/ the version of ESMF on IC? I don't really have a good feeling for where to go from here. Is there somewhere it makes sense to look into this deeper within the build logs?

**Comment by jonbob** [comment]
Or send me the path to your test and I can see what's different?

**Comment by stephenprice** [comment]
The case directory is here: 
/lustre/scratch3/turquoise/sprice/e3sm_cases/20200604.A_WCYCL1850S_CMIP6.ne30pg2_r05_oARRM60to10_ICG.grizzly.intel.openmpi.master.lrgLayout

The build / run dirs are here:

/lustre/scratch4/turquoise/sprice/E3SM/scratch/20200604.A_WCYCL1850S_CMIP6.ne30pg2_r05_oARRM60to10_ICG.grizzly.intel.openmpi.master.lrgLayout

**Comment by jonbob** [comment]
OK, so it doesn't really use ESMF -- just gives me nightmares seeing those letters! There's a fake esmf time_manager that I think was a brainchild of John Michalakes, just a way of claiming he was using esmf because he was using their api for time. Anyway, that's besides the point, except to say it's not a grizzly issue with any software version. But it does point at some issue with a time value somewhere, and there are plenty of calls in CAM to that routine. Could we try one thing quickly? And that's to turn off the cosp simulator -- you would just have to add this to user_nl_cam:
``` cosp_lite              = .false.```
Otherwise, I can try the cmip6 compset on anvil and see if I have the same issue? Or you could try the vanilla water-cycle compset on grizzly so we could more directly compare? Whichever one makes more sense to you...

**Comment by stephenprice** [comment]
Thanks. I'll try that. Not easy to debug this on Griz. due to the queue, but I'll let you know ASAP.

**Comment by stephenprice** [comment]
I can also build / submit the vanilla WC 1850S. I'm not sure cmip6 nuance is important to us ... as long as we can run a hist and rcp 8.5 from those init. conds.

**Comment by jonbob** [comment]
Well, try the vanilla version on grizzly instead then and I'll see what the cmip6 one does on anvil? At least then we'll have a more complete set of information...

**Comment by stephenprice** [comment]
If that is not too much of a pain for you, that would be great. Hopefully maybe it's useful for fleshing out any bugs in that compset that might be used with other grids.

**Comment by stephenprice** [comment]
The CMIP6 compset run w/ the altered cam nl value is in the queue. When trying to build the the 'vanilla' 1850S on Griz. I get an error I have never seen before:

Out of memory allocating the message block.compilation aborted for /lustre/scratch3/turquoise/sprice/e3sm_repo/E3SM/components/clm/src/data_types/ColumnDataType.F90 (code 1)

No idea what to make of that one but will revisit it tomorrow.

**Comment by stephenprice** [comment]
@jonbob -- unfortunately, adding that  cam nl option doesn't seem to change anything for me. I still see that same error at run time.

**Comment by stephenprice** [comment]
To summarize: OOM errors seem to be node specific and something to do w/ the state Griz is in right now. Other runtime errors appear to have been due to input data (cam/chem files) being truncated during data download, leading to some time management errors. When the correct input data are used, the configuration runs as expected (cc'ing @wlin7 on the last bit of info).

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
