### PR TITLE
Initial icepack integration

### PR DESCRIPTION
**Pull request by eclare108213**
Installs Icepack in E3SM.

This PR includes MPAS-seaice changes necessary to run Icepack in equivalent physics configurations as the original column package code. The entire Icepack repository is installed as a submodule linked from the main branch of E3SM’s Icepack fork.

Some minor changes were made to the original column package code for consistency with Icepack during testing. Icepack replaces colpkg as the default column physics package in this PR. 

Fully coupled E3SM v3alpha trigrid with Icepack physics is statistically compatible with the 100-year control at the 99% confidence interval.

Icepack is thoroughly and promptly documented in its git repository (the source code is in icepack/doc/).

[NML]
[CC]

### CODE REVIEW

**Comment by eclare108213** [comment]
@apcraig @dabail10 FYI

**Comment by proteanplanet** [comment]
Results for this branch as of this afternoon:
  ERS_Ld5.T62_oQU240.DTESTM.anvil_intel (Overall: PASS): Exact Restart D-case
  ERS.ne11_oQU240.WCYCL1850NS.chrysalis_intel (Overall: PASS): Exact Restart B-case
  PEM_Ln5.T62_oQU240wLI.DTESTM.anvil_intel (Overall: PASS): Processor Count D-case
  PET_Ln5.T62_oQU240.DTESTM.anvil_intel (Overall: PASS): Threading Test D-case
  SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.anvil_intel.mpassi-jra_1958 (Overall: PASS): Smoke Test D-case

**Comment by proteanplanet** [comment]
Icepack for this branch up to [511c002](https://github.com/E3SM-Project/E3SM/pull/5958/commits/511c0022ef979e7db6441d3f33b50763d3260495) produces similar results to ColPkg in a [B-case 22-year test](https://acme-climate.atlassian.net/wiki/spaces/ICE/pages/3930259466/B12.merge.icepack.icepack-integration.eclare108213.anvil).

**Comment by proteanplanet** [comment]
This branch is failing on initialization of the F-case.  See /lcrc/group/e3sm/ac.afroberts/E3SM-Polar/F12.icepack.iceiccheck.eclare108213.anvil

**Comment by proteanplanet** [comment]
F-cases are running on Anvil. I have added @wlin7 as a reviewer to check F-case simulations are as desired.

**Comment by proteanplanet** [comment]
@eclare108213  Please take a look a the ice.log files. e.g. /lcrc/group/e3sm/ac.afroberts/E3SM-Polar/D1.merge.fsdcheck.FSD_flag_only.erinethomas.anvil/run.k000.  There is gobbledegook that does not exist in ColPkg log files for the WARNINGS.

**Comment by eclare108213** [comment]
$ gunzip /lcrc/group/e3sm/ac.afroberts/E3SM-Polar/D1.merge.fsdcheck.FSD_flag_only.erinethomas.anvil/run.k000/ice.log.654785.230928-135945.gz
gzip: /lcrc/group/e3sm/ac.afroberts/E3SM-Polar/D1.merge.fsdcheck.FSD_flag_only.erinethomas.anvil/run.k000/ice.log.654785.230928-135945: Permission denied

**Comment by eclare108213** [comment]
The column physics driver within MPAS-seaice was refactored so that icepack could be implemented and compared in parallel with the original (colpkg) code. As bugs were found that produced non-bit-for-bit results in standard test configurations, they were PR’d separately into E3SM master. Other changes were made to the colpkg code for consistency with Icepack, which were not BFB but were found to not be climate-changing.

Icepack’s interface specifies many optional arguments, so that driver codes such as MPAS-seaice can configure it as needed. As such, contents of the two ice_constants_colpkg.F90 modules in colpkg (for standalone and coupled configurations) have been consolidated into mpas_seaice_constants.F, from which Icepack’s parameters are initialized.

The old column package code will be deprecated in a future PR; it remains available here for the ongoing biogeochemistry merge.

Some new capabilities in Icepack are now available to E3SM but have not been fully implemented in MPAS-SI. These will be added in later PRs and include water isotopes and forcing the new floe size distribution with wave data from the ocean. Many stealth features remain in MPAS-SI from before the Icepack merge. Warnings or aborts for all stealth features will be added in a future, BFB PR.

This code has undergone continuous testing throughout the merge process, including D cases (usually 3 months duration) with energy conservation and debugging diagnostics and, when results were not bit-for-bit, CICE-QC comparisons in 5-year D cases. Final testing includes G and B cases with SMS, ERS, PEM and PET tests.

Icepack’s documentation is updated as part of each relevant code PR, and is automatically compiled and posted online using readthedocs.

For additional information, see the [New feature overview document](https://acme-climate.atlassian.net/wiki/spaces/ICE/pages/3952476924/Overview+of+Icepack+physics+merge+into+MPAS-SI) (in prep).

**Comment by eclare108213** [comment]
Several configuration options have been added or changed. 
Changes:

- `config_use_column_package` to `config_use_column_physics` for clarity (T/F)
- `config_pond_flushing_timescale` to `config_pond_flushing_factor`, which modifies the time scale but is not itself a time scale
- `config_ridiging_efolding_scale` to `config_ridging_efolding_scale` to correct a spelling error
- `seaiceIceOceanDragCoefficient` to `config_ice_ocean_drag_coefficient` for tuning via namelist

New configuration flags:

- `config_column_physics_type` chooses between icepack and column_package
- `config_snow_thermal_conductivity` for tuning via namelist
- `config_frazil_coupling_type` to specify the type of frazil coupling used by the driver
- `config_salt_flux_coupling_type` to specify the type of salt flux coupling used by the driver
- `config_use_shortwave_redistribution` to prevent thermodynamic errors in completely melted ice or snow layers
- `config_shortwave_redistribution_fraction` to specify the fraction of energy moved from the melting layer
- `config_shortwave_redistribution_threshold` to specify the temperature threshold at which energy is moved
- `config_snow_redistribution_factor` to specify the ratio of snow depth on level ice versus ridges (was fixed at 0.3 in colpkg and is now tunable; this is not used in E3SM’s standard snow model configuration)
- `config_use_floe_size_distribution` to turn on the floe size distribution capability (aborts for now)
- `config_nFloeCategories` to specify the number of floe size categories
- `config_floediam` to specify the default floe diameter when FSD is not in use
- `config_floeshape` to specify a floe shape parameter when FSD is not in use

**Comment by eclare108213** [comment]
This PR is ready for review.  Additional information is in https://acme-climate.atlassian.net/wiki/spaces/ICE/pages/3952476924/Overview+of+Icepack+physics+merge+into+MPAS-SI, including links to complete testing results.

**Review by proteanplanet — APPROVED** [review]
Based on my testing in the E3SM v3alph04-trigrid B-case configuration, where this branch was substituted for master and MPAS-SI was run with config_column_physics_type = 'icepack' with an otherwise identical physical configuration, I approve this PR. 

For the case cited above, the climate between the two simulations after 100 years was comparable for the E3SM WCYCL1850 ne30pg2_r05_EC30to60E2r2 configuration.  The version with Icepack maintains a stable climate analogous to the control. The sea ice climate between the two simulations is statistically identical at the 99% compatibility interval for key metrics of global sea ice extent, volume, and snow-on-sea ice volume, as indicated in the sea ice lemnisc below.

E3SM_sea_ice_lemnisc 0001-0100 ColPkg Icepack PI extent volume snow 3

The above figure summarizes daily sea ice phase average (solid) and interquartile range (gray). Dashed red lines indicate the null hypothesis for days of the year that MPAS-SI with Icepack is different from the standard version of MPAS-SI at the 99% compatibility interval. Traces start on January 1, passing the northward equinox (•), northern solstice (◦), southward equinox (•), and southern solstice (◦) to the end of December (→)

**Review by darincomeau — APPROVED** [review]
Approved based on documentation and extensive testing by the integration group over the past several months, including the recent coupled simulations by @proteanplanet .

**Comment by jonbob** [comment]
@eclare108213 - we have a process with some semi-automated scripts to make the E3SM bld files match changes in Registry files, but it looks like this has been done by hand for this PR. I ran the scripts and they found issues in four different files:
````
#	modified:   components/mpas-seaice/bld/build-namelist
#	modified:   components/mpas-seaice/bld/build-namelist-group-list
#	modified:   components/mpas-seaice/bld/build-namelist-section
#	modified:   components/mpas-seaice/bld/namelist_files/namelist_definition_mpassi.xml
````
How do you want to handle the differences? I am hesitant to overwrite any of the changes you made, mostly because it looks like there are a lot of changes to the namelist definitions. Those are usually extracted from Registry files, so we may want to change Registry to get some of those descriptions?

**Comment by proteanplanet** [comment]
@eclare108213 @jonbob @wlin7 :  A new [PR](https://github.com/eclare108213/E3SM/pull/44) is awaiting review and merge into [this branch](eclare108213:eclare108213/seaice/icepack-integration) to fix F-case simulations with Icepack.

**Comment by jonbob** [comment]
@eclare108213 - it is a complicated relationship between the standalone models and what E3SM uses, but Registry is included in both and we have scripts to take what's in Registry and make the E3SM bld files consistent with it. I'll work on making the descriptions in Registry match what you've added to the namelist definitions and we can sync up next week.

I can handle the conflict in .gitmodules when I merge this PR, so don't worry about that

**Comment by wlin7** [comment]
[F2010 simulation](https://acme-climate.atlassian.net/wiki/spaces/CM/pages/3967254529/20231019.v3alpha04-icepack.F2010.chrysalis) using the icepack in prescribed seaice mode shows the impact of switching to icepack is largely negligible.

[e3sm_diags for model vs model comparison with v3alpha04 baseline](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.wlin/E3SMv3_dev/20231019.v3alpha04-icepack.F2010.chrysalis/e3sm_diags/atm_monthly_180x360_aave_mvm/v3alpha04-Icepack_vs_v3alpha04-CTL_0002-0011/viewer/)

**Review by wlin7 — APPROVED** [review]
Also verified icepack is used by default.

**Review by jonbob — APPROVED** [review]
Approved based on developer testing and long run by the coupled model group

**Comment by jonbob** [comment]
Passes sanity testing during merge with expected results, merged to next

**Comment by jonbob** [comment]
merged to master and expected NML and regular DIFFs will be blessed with PR #5999, which was merged at the same time

**Pull request merged**
