### PR TITLE
[YAKL] Update YAKL and PAM submodules

### PR DESCRIPTION
**Pull request by abagusetty**
Update the YAKL submodule, and update PAM submodule to work with the YAKL update. Non-BFB only for MMF2.

[non-BFB]
[YAKL]

### CODE REVIEW

**Review by xyuan — APPROVED** [review]

**Comment by rljacob** [comment]
@brhillman can you take are of this?

**Comment by whannah1** [comment]
@mrnorman @xyuan @abagusetty I see there are some more recent updates to the main YAKL repo, should we include those here? Seems like some of them might be involved with recent PAM dev?

**Comment by mrnorman** [comment]
Might as well upgrade. I can help if you get build errors associated with the template parameter type for `SArray` and `FSArray` objects.

**Comment by mrnorman** [comment]
Biggest changes are Intel SYCL backend and CPU performance improvements for YAKL, increasing vectorization by switching to `size_t`.

**Comment by rljacob** [comment]
@abagusetty based on above discussion, YAKL should be updated again on this branch.

**Comment by rljacob** [comment]
@brhillman thanks for cleaning up the history with a force-push.  You can start merging this.

**Comment by brhillman** [comment]
No problem. MMF tests are currently failing to build with this though, looking into that now.

**Comment by brhillman** [comment]
PAM PR https://github.com/E3SM-Project/PAM/pull/138 will fix the build error, but now I'm getting runtime errors that I'm working on debugging.

**Comment by rljacob** [comment]
Please update the PR title/description to mention the PAM update.

**Review by whannah1 — APPROVED** [review]

**Comment by rljacob** [comment]
@brhillman you can start merging this.

**Comment by brhillman** [comment]
This looks like it will be non-BFB for MMF2 on pm-cpu at least. Updated description and tags to show that.

**Comment by whannah1** [comment]
@brhillman non-BFB changes are fine - I'm planning some additional non-BFB changes, and the model stability is unacceptable for real science - so I'm not concerned about breaking it.

**Comment by brhillman** [comment]
To clarify, that wasn't a complaint, I just wanted to document the change in the description for provenance. But since this is non-BFB, it needs to wait until Monday.

**Comment by rljacob** [comment]
This is now part of #6153

**Pull request closed without merging**
