### PR TITLE
Update mpas-source: pgi syntax fix

### PR DESCRIPTION
**Pull request by mattdturner**
This replaces array syntax in one loop in the ocean tend_tracer routine with explicit loops to
work around a compiler issue with PGI.

See https://github.com/MPAS-Dev/MPAS-Model/pull/806

[BFB]

### CODE REVIEW

**Comment by mattdturner** [comment]
Passes
```
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
```

Also BFB in MPAS-O standalone for Intel and GNU (both optimized and debug)

**Review by jonbob — APPROVED** [review]
Looks good from a visual inspection

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
passed sanity testing

**Comment by jonbob** [comment]
merged to master -- overnight ocean-only tests passed

**Pull request merged**
