### PR TITLE
Add project id's to list so that more E3SM jobs at NERSC can have provenance data saved

### PR DESCRIPTION
**Pull request by ndkeen**
There are now quite a few E3SM jobs running at NERSC and we are *not* saving info.
This change adds several project ID's that have recently run larger-node/longer-time E3SM jobs.

[bfb]

### CODE REVIEW

**Comment by sarats** [comment]
As I mentioned in https://github.com/E3SM-Project/E3SM/issues/5753, I would like to assess the impact of inclusion of any non-core ERCAP project. 

For that purpose, I would like to get the name of the project, PI contact info and planned runs. If there are plans for running large number of small or single node runs or small-scale ensembles, I don't wish to archive them in PACE and would like them to provide assurance and understand disabling archiving for such runs (`./xmlchange SAVE_TIMING=FALSE`)

Either this information can be listed here or on Confluence.

One additional aspect to consider is the performance archive location and ability for users in some of these projects to write to that location.

The limiting constraint for archiving any and all runs is the limited storage capacity on the PACE server (for database and raw data).

**Comment by ndkeen** [comment]
OK, so you are going to take this Sarat? 
I think it would be fine to add these, and remove any if they are too frequent.
It's true there would be a problem if they could not write to the dir.

**Comment by rljacob** [comment]
Should we just add the ones mentioned in #5753 now and other's later after a conversation with the PI?

@ndkeen do you have PI contact info for all the projects you're adding?

**Comment by sarats** [comment]
FYI, I discussed this topic today with the EXEC during our call and they noted that this is a low-priority.

**Pull request closed without merging**
