### PR TITLE
update mpas-source: Alter vertical transport in stage 1 of split explicit

### PR DESCRIPTION
**Pull request by mark-petersen**
Add back computation of vertical transport. The original change was done to make the first stage of split explicit Lagrangian in the vertical. This PR changes it back, to aid stability and heat transport problems.

See comments in https://github.com/MPAS-Dev/MPAS-Model/pull/699

[non-bfb]

### CODE REVIEW

**Comment by mark-petersen** [comment]
Passes:
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PEM_Ld5_P512.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_intel
PET_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-haswell_intel
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
```

**Review by jonbob — APPROVED** [review]
Looks as expected by visual inspection

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master and expected DIFFs blessed for all machines except sandiatoss3, which failed to report today (and will have DIFFs)

**Pull request merged**
