### PR TITLE
Adds print statement to add a print out of BFBFLAG

### PR DESCRIPTION
**Pull request by singhbalwinder**
[BFB]

### CODE REVIEW

**Comment by singhbalwinder** [comment]
This is good to go now.

**Comment by rljacob** [comment]
It would also be good to add this as a global attribute in the history if you want to take that on.

**Review by rljacob — APPROVED** [review]

**Comment by singhbalwinder** [comment]
Thanks @rljacob for the suggestion. I have added the BFBFLAG as a global attribute to the history files.

**Review by rljacob — APPROVED** [review]

**Comment by singhbalwinder** [comment]
Merged to next

**Pull request merged**
