### PR TITLE
Update CIME submodule

### PR DESCRIPTION
**Pull request by jgfouca**
... to 12142ee0c003c135e66265528247518339c0b067

Fixes:
1) Updates to cprnc build system to fix various issues
2) Fix a string that should be raw
3) case.submit: Fix no-batch mode
4) fix issue getting correct parameters for job subgroups
5) jenkins_generic_job: Should probe branch of main src repo, not cime repo
6) check_input: If chksum is off, don't try to download_checksum_file
7) Fix .env_mach_specific.sh when unsetting env
8) Fix recursive call
9) Update initial conditions in PGN and TSC tests.
10) fix component-only  (no coupler) testing.

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
@jgfouca can you update this again?  I just merged https://github.com/ESMCI/cime/pull/4513 to CIME master.

**Comment by rljacob** [comment]
updated and remerged to next.

**Comment by amametjanov** [comment]
E3SM needs a CIME update to fix
1. ERP_Ld9.ne4pg2_ne4pg2.FIDEAL.chrysalis_intel.allactive-pioroot1 (previously ERP_Ld9.ne4_ne4.FIDEAL.chrysalis_intel.allactive-pioroot1)
2. ERS.f09_g16_g.MALISIA

These 2 were passing on `next` with 83bd429 on Feb-18 and started failing with ed475e4 on Feb-19.

**Comment by rljacob** [comment]
The above fails appear to be from this CIME PR:  https://github.com/ESMCI/cime/pull/4580

**Comment by rljacob** [comment]
Fails from this PR fixed in https://github.com/E3SM-Project/E3SM/pull/6278

**Pull request merged**
