### PR TITLE
Fix summit pnetcdf linking

### LINKED ISSUE #3487: e3sm.exe linked with PnetCDF 1.9.0 or higher versions fails on Summit (used to work)
The default (and the only one that is available so far) PnetCDF module installed
on Summit is parallel-netcdf/1.8.1

I have also installed some custom versions (including 1.8.1) under
/gpfs/alpine/cli115/world-shared/3rdparty/pnetcdf to test E3SM.

Version 1.11.2 used to work until recently. In scorpio (or scorpio classic) code,
when PnetCDF calls ncmpi_inq_dimid() on certain opened input files (e.g. cami_mam3_Linoz_ne4np4_L72_c160909.nc), it always returns an error code
NC_EBADID (-33), causing E3SM case run to fail at a very early stage.

This issue is reproducible with custom PnetCDF 1.9.0 or higher versions on Summit,
but not reproducible with version 1.8.1 (system module or the custom version). 

It is confirmed that this issue is caused by PR #3043 and PR #3359. If not fixed, some
E3SM cases run on Summit might not be able to use higher versions of PnetCDF.

It is likely a specific e3sm.exe build/link issue (related to PR 3043 and 3359) on Summit:
PnetCDF 1.9.0 or higher versions still works on other machines like Cori or anlworkstation.
Also, stand-alone PnetCDF or scorpio test programs on Summit cannot reproduce this
error with the same input files.

I have created some feature branches to reproduce this issue. These branches all
switched default PnetCDF 1.8.1 to custom 1.11.2 for testing. A small X Case is used
in the scenarios below (only requires 1 compute node and 1-min of walltime), with
default scorpio classic and IBM XL compiler. Actually, it is also reproducible with ne4
F case, scorpio and GNU compiler.

[Scenario 1]
Before PR 3043 was merged, no errors.
```
git clone --branch dqwu/test_summit_pnetcdf_d15f283 https://github.com/E3SM-Project/E3SM.git E3SM_d15f283
cd E3SM_d15f283
git submodule update --init
cd cime/scripts
./create_newcase --case X_f19_g16_d15f283 --compset X --res f19_g16 --walltime 00:01
cd X_f19_g16_d15f283
./xmlchange STOP_N="1"
./xmlchange REST_OPTION="none"
./case.setup
./case.build
./case.submit
```
[Scenario 2]
After PR 3043 was merged (also include PR 3325 to fix Depends.ibm.cmake), PnetCDF
returns NC_EBADID.
```
git clone --branch dqwu/test_summit_pnetcdf_18922c8 https://github.com/E3SM-Project/E3SM.git E3SM_18922c8
cd E3SM_18922c8
git submodule update --init
cd cime/scripts
./create_newcase --case X_f19_g16_18922c8 --compset X --res f19_g16 --walltime 00:01
cd X_f19_g16_18922c8
./xmlchange STOP_N="1"
./xmlchange REST_OPTION="none"
./case.setup
./case.build
./case.submit
```
case.run error
`pio_support::pio_die:: myrank= -1 : ERROR: nf_mod.F90: 1293 : NetCDF: Not a valid ID`

Note, "./case.build --use-old" still works until PR 3359 was merged.

[Scenario 3]
Before PR 3359 was merged, no errors if we build e3sm.exe with "--use-old" option.
```
git clone --branch dqwu/test_summit_pnetcdf_5696a44 https://github.com/E3SM-Project/E3SM.git E3SM_5696a44
cd E3SM_5696a44
git submodule update --init
cd cime/scripts
./create_newcase --case X_f19_g16_5696a44 --compset X --res f19_g16 --walltime 00:01
cd X_f19_g16_5696a44
./xmlchange STOP_N="1"
./xmlchange REST_OPTION="none"
./case.setup
./case.build --use-old
./case.submit
```
[Scenario 4]
After PR 3359 was merged, PnetCDF returns NC_EBADID even if we build e3sm.exe
with "--use-old" option.
```
git clone --branch dqwu/test_summit_pnetcdf_09304fb https://github.com/E3SM-Project/E3SM.git E3SM_09304fb
cd E3SM_09304fb
git submodule update --init
cd cime/scripts
./create_newcase --case X_f19_g16_09304fb --compset X --res f19_g16 --walltime 00:01
cd X_f19_g16_09304fb
./xmlchange STOP_N="1"
./xmlchange REST_OPTION="none"
./case.setup
./case.build --use-old
./case.submit
```
case.run error
`pio_support::pio_die:: myrank= -1 : ERROR: nf_mod.F90: 1293 : NetCDF: Not a valid ID`

Comments:
PR 3043 is a big PR that switches E3SM's default build-system to be cmake-based.

However, for Summit, PR 3359 is just a small PR that moves some link flags from
LDFLAGS to SLIBS. This only changes the position of some specific linker flags for
PnetCDF with old build-system:
`mpif90 -o e3sm.exe ... -L/gpfs/alpine/cli115/world-shared/3rdparty/pnetcdf/1.11.2/xl-16.1.1/lib -lpnetcdf ...`

I guess PR 3043 has also changed the position of linker flags for PnetCDF with new
cmake-based build-system.

It is still unknown why this trivial position change of linker flags might cause PnetCDF (1.9.0
or higher versions) to return NC_EBADID on Summit if it is linked to e3sm.exe.

### PR DESCRIPTION
**Pull request by jgfouca**
Fixes #3487 

[BFB]

### CODE REVIEW

**Comment by jgfouca** [comment]
With this change:

```
% ./create_test SMS.f19_g16.X --wait
No project info available
Creating test directory /gpfs/alpine/cli115/proj-shared/acmetest/e3sm_scratch/SMS.f19_g16.X.summit_ibm.20200312_145507_sv03r1
RUNNING TESTS:
  SMS.f19_g16.X.summit_ibm
Starting CREATE_NEWCASE for test SMS.f19_g16.X.summit_ibm with 1 procs
Finished CREATE_NEWCASE for test SMS.f19_g16.X.summit_ibm in 1.817064 seconds (PASS)
Starting XML for test SMS.f19_g16.X.summit_ibm with 1 procs
Finished XML for test SMS.f19_g16.X.summit_ibm in 0.332197 seconds (PASS)
Starting SETUP for test SMS.f19_g16.X.summit_ibm with 1 procs
Finished SETUP for test SMS.f19_g16.X.summit_ibm in 3.639812 seconds (PASS)
Starting SHAREDLIB_BUILD for test SMS.f19_g16.X.summit_ibm with 1 procs
Finished SHAREDLIB_BUILD for test SMS.f19_g16.X.summit_ibm in 101.118350 seconds (PASS)
Starting MODEL_BUILD for test SMS.f19_g16.X.summit_ibm with 6 procs
Finished MODEL_BUILD for test SMS.f19_g16.X.summit_ibm in 29.346558 seconds (PASS)
Starting RUN for test SMS.f19_g16.X.summit_ibm with 1 proc on interactive node and 84 procs on compute nodes
Finished RUN for test SMS.f19_g16.X.summit_ibm in 3.638265 seconds (PEND). [COMPLETED 1 of 1]
Waiting for tests to finish
Test 'SMS.f19_g16.X.summit_ibm' finished with status 'PASS'
    Path: /gpfs/alpine/cli115/proj-shared/acmetest/e3sm_scratch/SMS.f19_g16.X.summit_ibm.20200312_145507_sv03r1/TestStatus
test-scheduler took 229.657431126 seconds
```

**Comment by dqwu** [comment]
@jgfouca 
Thanks for a quick fix. I manually tested this feature branch with a simple X case (same steps in issue 3487) and it passed. However, if I use "case.build --use-old", there are link errors related to PnetCDF libs, like:
cime/src/share/util/shr_mct_mod.F90:510: undefined reference to `__netcdf_NMOD_nf90_open'

Could you please try to reproduce it?

**Comment by dqwu** [comment]
@jgfouca 
For  "case.build --use-old", if you look at e3sm.bldlog, you will notice that there are no libs for NetCDF, only libs for PnetCDF.

**Comment by jgfouca** [comment]
@dqwu it looks like the Makefile macro generator doesn't support negation.

```
ifeq ($(MPILIB),!mpi-serial)
```

**Comment by jgfouca** [comment]
This shouldn't be too hard to fix.

**Comment by dqwu** [comment]
@jgfouca 
Also, GNU (confirmed) or PGI might have the same issues.
Could you please extend your fix to following sections as well?
```
<compiler MACH="summit" COMPILER="gnu">
<compiler MACH="summit" COMPILER="pgi">
<compiler MACH="summit" COMPILER="pgiacc">
```
I can test these compilers later.

**Comment by dqwu** [comment]
@jgfouca 
PS, before this PR will be merged to master, please revert the change to default PNETCDF_PATH.
So far, we should still use default PnetCDF 1.8.1 provided by system module.
We can request Summit IT to build PnetCDF modules for higher versions.
Before that, the existing custom versions might be used for testing in other feature branches.

**Comment by jgfouca** [comment]
@dqwu , i think I have all the fixes you asked for except for the reversion to the original pnetcdf.

**Comment by dqwu** [comment]
@jgfouca 
Thanks for the update. I will test latest PR on other compilers and scorpio.
The reversion can be done before merging.

**Comment by dqwu** [comment]
@jgfouca 
It seems that Summit has changed some default modules recently:
`xl/16.1.1-5   spectrum-mpi/10.3.1.2-20200121`

This PR upgrades xl/16.1.1-3 to xl/16.1.1-4, is it better to use the default xl/16.1.1-5 instead?

Also, could you please apply the latest mpi module for ibm to gnu and pgi.* as well?
`<command name="load">spectrum-mpi/10.3.1.2-20200121</command>`

You might remove "ibm" in the title of this PR, as it also fixes similar issues for gnu and pgi*.

PS, there is a hanging issue when PIO_VERSION is set to 2, but it seems that rebuilding custom PnetCDF 1.11.2 with xl/16.1.1-5 and spectrum-mpi/10.3.1.2-20200121 can fix that.

Overall, this PR is ready to be approved, thanks a lot for your work.

**Comment by dqwu** [comment]
@jgfouca 
You might also need to upgrade pgi/19.4 to pgi/19.9 in this PR

pgi/19.4 is a hidden module now and pgi/19.9 is the default one.
```
module availe pgi
   pgi/18.7    pgi/18.10    pgi/19.9 (D)    pgi/19.10    pgi/20.1
```

**Comment by jgfouca** [comment]
@dqwu , done

**Comment by jgfouca** [comment]
This doesn't appear to have had any negative impact on the dashboard.

**Pull request merged**
