### PR TITLE
Updates CNP balance for dynamic PFT

### PR DESCRIPTION
**Pull request by bishtgautam**
Refactors the subroutine responsible for CNP mass conservation due changes in
PFT cover associated with LULC. The subroutine refactor is required to support
dynamic landunits.

[non-BFB] for only tests with active land BGC

### CODE REVIEW

**Comment by susburrows** [comment]
Is this PR required for the v1.1 CBGC experiment?

**Comment by bishtgautam** [comment]
@susburrows, This PR is targetted towards the v2 model and is non-BFB for when landuse is turned on with active BGC (i.e. a transient run with active BGC). The PR is non-BFB because the order of operations has changed. Will v1.1 CBGC experiment run a transient simulation with active BGC? If yes, would you like this PR not be merged PR till a v1.1 tag is made?

**Comment by susburrows** [comment]
After discussion with @qzhu-lbl , yes, we would like to request that merging of this PR be postponed until after v1.1.  The v1.1 CBGC experiment will include transient simulations with active BGC, and this PR could potentially introduce unnecessary confusion.

**Comment by bishtgautam** [comment]
It is fine to postpone this PR after v1.1. Btw, what is a tentative timeline for generating v1.1? A month? Few months?

**Comment by susburrows** [comment]
@bishtgautam we haven't set a specific timeline yet.  I'll discuss with Rob.

**Comment by jqyin** [comment]
Merged #2135

**Pull request merged**
