### PR TITLE
Use consistent casing (all-caps) for build_threaded value

### LINKED ISSUE #2826: Multi-threaded cases are not built with threading flags
Current master (`v1.1.0-beta-1202-g6e47b9f`) appears to have dropped threading flags (`-qopenmp` for Intel compiler) for multi-threaded cases such as `SMS_P12x2.ne4_oQU240.A_WCYCL1850`.

### PR DESCRIPTION
**Pull request by jgfouca**
Three different casing styles were being used for this value
and Make does case-senstive comparisons, so it was incorrectly
interpretting build_threaded to be false.

Fixes #2826 

[BFB]

### CODE REVIEW

**Comment by jgfouca** [comment]
@amametjanov , can you confirm this fixes the issue? I confirmed on melvin, but I'd like to be sure. This was a pretty significant bug.

**Comment by jgfouca** [comment]
I'm pretty eager to get master into a better state, so I'm going to merge.

**Comment by amametjanov** [comment]
Thanks Jim. If it worked on melvin, I'm pretty sure it'll work on other machines too.

**Comment by amametjanov** [comment]
It looks like there is one other remaining place to convert `true` to `TRUE` for `compile_threaded`:
```
components/mpas-source/src/Makefile.in.CESM
components/mpas-source/src/Makefile.in.ACME
```

This leads to omission of `-DMPAS_OPENMP` from cpp flags, which in turn leads to threading test fails in MPAS-Ocean in fully coupled cases.

**Comment by jgfouca** [comment]
@amametjanov , you're a life saver! It looks like the git grepping I did to ensure I hit all the build_threaded was not recursive (didn't go into submodules).

**Comment by ndkeen** [comment]
Is this in master yet?
I'm still seeing these lower-case instances here: 

```
./bld/ocn/source/Makefile.in.ACME:1:# Duplicate logic from Tools/Makefile to set compile_threaded
./bld/ocn/source/Makefile.in.ACME:2:compile_threaded = false
./bld/ocn/source/Makefile.in.ACME:4:   compile_threaded = true
./bld/ocn/source/Makefile.in.ACME:8:      compile_threaded = true
./bld/ocn/source/Makefile.in.ACME:66:ifeq ($(compile_threaded), true)
./bld/ocn/source/Makefile.in.CESM:1:# Duplicate logic from Tools/Makefile to set compile_threaded
./bld/ocn/source/Makefile.in.CESM:2:compile_threaded = false
./bld/ocn/source/Makefile.in.CESM:4:   compile_threaded = true
./bld/ocn/source/Makefile.in.CESM:8:      compile_threaded = true
./bld/ocn/source/Makefile.in.CESM:66:ifeq ($(compile_threaded), true)
```

**Pull request merged**
