### PR TITLE
correction of last commit that used incorrect variable names

### PR DESCRIPTION
**Pull request by xyk-ornl**
The last PR I submitted which fixes the outputs has a problem. The incorrect variable names were used in that PR (those are from the current master but I did not notice they are slightly different between current master and maint 1.1). The are corrected in this PR. Thanks

### CODE REVIEW

**Comment by xyk-ornl** [comment]
@jonbob Can you merge this into maint-1.1? Sorry for the extra work! Thanks so much!

**Comment by acme-y9s** [comment]
I tased the changes with one of the BGC future compost and they worked.

**Comment by jonbob** [comment]
Yes, I'll get this merged asap -- but I'm traveling today and may not be able to until tomorrow afternoon.


Jon

________________________________

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
