### PR TITLE
Infrastructure upgrade to support finite volume physics grid

### PR DESCRIPTION
**Pull request by whannah1**
This PR updates the atmosphere grid infrastructure to allow for a finite volume physics grid (hereafter referred to as “physgrid”) as an alternative to the traditional approach of having physics columns coincide with the GLL nodes of the dynamics grid. Although this requires many large code changes, (mostly in dyn_grid.F90) the model is still BFB when run with a typical configuration.

The motivation for this new grid option is two-fold. Initially, a problematic amount of grid imprinting (i.e. corner nodes rain more than middle nodes) was discovered in the super-parameterized E3SM that can only be addressed by removing the inherent heterogeneous nature of the GLL grid. A smaller degree of grid imprinting is also detectable in the standard E3SM with parameterized convection. We think the SP-E3SM problem is partly due to having more realistic cloud sensitivity to rising motion on the GCM grid, so it could also become more problematic in E3SM as the cloud scheme is improved. 

The second motivation for supporting a new physics grid is for performance reasons, since this can reduce the number of physics columns. A recent paper by Adam Herrington and Peter Lauritzen shows that there is no degradation of the model climate with 2x2 FV cells per element (pg2). In my F-compset tests I found the pg2 cases to have roughly ~20% larger throughput. The pg1 cases would be much higher, which may be useful for cheap testing of larger grids, but probably won't ever be used for real simulations.

The current mapping technique implemented here between dynamics and physics grid uses a “low-order” piecewise constant approach when mapping from physics to dynamics grids. This has the advantage of simplicity as it does not require information from outside the dynamics element.

Following the approach of Peter Lauritzen et al., the initial state in the “cami” file remains on the GLL grid and gets copied to the physgrid during initialization, whereas the topography is supplied on the physgrid and copied to the dynamics grid. There was a lot of discussion about how to handle these things and we felt that keeping topography on the physgrid makes the most sense due to the gravity wave parameterizations that utilize the sub-grid topography variance (SGH). Fortunately, many aspects of the model, such as the ability to restart and choose a load balancing options, are not affected by the new physgrid. I’ve also verified the ability to for pg2 runs to output a new “cam.i” files and use that file to start a new run. Tests with realistic land and topography have been limited to ne30pg2 F-compset runs. Aside from the typical issues associated with spinning up a new grid and creating new input files, I do not foresee any problems with using the physgrid with fully coupled configurations. 

**A note on land and ocean domain files**
When the land or ocean components are on the pg2 grid it is very important to include “cubed_sphere_map = 2” in the atm_in namelist file. This is because I have updated TempestRemap to be able to create the scrip files used to generate the domain files for these components, and the locations of cells ends up being slightly different is the default cubed sphere mapping option is used. The word on the street is that we will be moving towards having the land and ocean components on a different grid so this issue probably won’t matter in the future, but this is still important in the current paradigm. 

**A note about topography**
As noted above, the topography is prescribed on the physics grid and then copied to the dynamics grid during initialization. I struggled a bit with how to generate topography on the pg2 grid that was adequately smoothed. After some failed attempts to develop my own smoothing routine, I got a successful run by following the usual recipe and adding in step #3 below:
Use cube_to_target to downscale hi-res topography to np4 grid
Use HOMME to smooth downscaled topography
Use TempestRemap to interpolate smoothed np4 topo to the pg2 grid
Use cube_to_target on smoothed topography to generate consistent SGH fields
We will likely want to revisit this approach in the future. 

**A note on supported grids**
Many new grids were added (ex. ne35, ne40, ne45) to facilitate aquaplanet convergence testing over a large range of resolutions. I haven’t uploaded initialization or domain files to the inputdata repo for all these grids and have “dummy” file names where they are specified in namelist_defaults_cam.xml. I can fix all this and upload the input files if that is desired, but I feel that it would be better to leave them defined but not fully supported, since anyone wanting to use this will need to consider the model spin-up on a case by case basis, unless I also go back and create spun-up cami files. 

The plot below shows a comparison of the average precipitation for a single year with physics on np4 (top) and pg2 (bottom) grids. The data is plotted on the native physics grid. 

image

More details and analysis of various tests can be [found here](https://confluence.exascaleproject.org/display/ADSE15/Grid+Imprinting+-+SOLUTION+-+FV+physics+grid)

### CODE REVIEW

**Comment by rljacob** [comment]
@brhillman Have you tried an ERS test with this?

**Comment by whannah1** [comment]
@rljacob, I've been doing ERS and SMS tests along the way to make sure it's BFB. I haven't done a whole test suite yet, but I think they should all pass if an ERS passes.

**Comment by whannah1** [comment]
I just realized how many conflicts there. It might be easier if I rebase on the current master and resubmit the PR. I'm not sure though.

**Comment by brhillman** [comment]
@whannah1 you/we should do a baseline compare with the e3sm_developer suite. In particular, we should check that it passes ERP in addition to ERS, since ERP also changes the PE layout. I can do that if you want, or wait until you rebase if you’re planning on doing that to deal with the conflicts first.

**Comment by whannah1** [comment]
@brhillman, I'm doing a rebase right now. I think this will be worth it since some of these conflicts are a little tricky.
I'll generate baselines for the developer suite so I can run the tests afterwards.

**Comment by whannah1** [comment]
Closing this and creating a new PR with a rebased branch.

**Pull request closed without merging**
