### PR TITLE
Add coupled dycore tests using shared execs 

### PR DESCRIPTION
**Pull request by oksanaguba**
Add tests for coupling mechanisms in EAM and for SL transport with theta dycore for coupled atmosphere. Tests re-use executables; only 2 builds are required, one for preqx dycore and another one for theta.

[Non-BFB] because new baselines are required.

### CODE REVIEW

**Comment by oksanaguba** [comment]
@jgfouca could you please look at changes i put in cime/config/e3sm/tests.py ? I want two sets of tests, eam_preqx_ftypes and eam_theta_ftypes, to run in nightlies, but it seems that including them into e3sm_atm_developer set does not work: if i run `create_test e3sm_atm_developer`, then each test in ftypes sets has a bld folder. If i try to run `create_test --single-exe e3sm_atm_developer`, then all tests, ftype tests and not, use the same exec. What other options do i have? Should ftype sets go separately into nightlies then (not sure how to do it with cdash and jenkins)?

**Comment by jgfouca** [comment]
@oksanaguba, you're trying to do something pretty sophisticated: running a non-sharing suite which inherits multiple sharing suites. I didn't anticipate this usecase and implemented the share feature in the simplest way that was less-powerful. I have some free time today, so let me hack on create_test for a couple hours.

**Comment by oksanaguba** [comment]
On anvil this runs as expected
```
create_test eam_preqx_ftypes
create_test eam_theta_ftypes
```

**Comment by jgfouca** [comment]
@oksanaguba , if you rebase your branch onto latest master, you should get the build-sharing behavior you want.

**Comment by oksanaguba** [comment]
@jgfouca this is awesome! thanks! I ran 
```
brr=~/acme-b2
${brr}/cime/scripts/create_test --machine anvil --compiler intel e3sm_atm_developer
```
and all as expected: tests that do not belong to _ftypes suite use  their own execs, tests in _ftypes use 1 exec per suite. Now I this we should just expand _ftypes suited for all kinds of dycore tests that we need. I will rename suites and move SL test into theta suite.

**Comment by jgfouca** [comment]
@oksanaguba , how much time does this add to e3sm_developer on melvin?

**Comment by oksanaguba** [comment]
I do not know about melvin and I don't even know how to use melvin. On anvil this adds ~23 min to  build and ~15 min to run.

**Comment by jgfouca** [comment]
@oksanaguba , I timed it:
```
% ./create_test eam_preqx eam_theta
...
test-scheduler took 9907.42118788 seconds
```

The individual test run times:
```
Finished RUN for test SMS.ne4_ne4.FC5AV1C-H01A.melvin_gnu.cam-preqx_ftype0 in 2713.599132 seconds (PASS). [COMPLETED 1 of 12]
Finished RUN for test SMS.ne4_ne4.FC5AV1C-H01A.melvin_gnu.cam-preqx_ftype4 in 2765.425728 seconds (PASS). [COMPLETED 2 of 12]
Finished RUN for test SMS.ne4_ne4.FC5AV1C-H01A.melvin_gnu.cam-preqx_ftype1 in 2773.671674 seconds (PASS). [COMPLETED 3 of 12]
Finished RUN for test SMS.ne4_ne4.FC5AV1C-H01A.melvin_gnu.cam-thetahy_ftype1 in 1748.061975 seconds (PASS). [COMPLETED 4 of 12]
Finished RUN for test SMS.ne4_ne4.FC5AV1C-H01A.melvin_gnu.cam-thetahy_ftype2 in 1731.181842 seconds (PASS). [COMPLETED 5 of 12]
Finished RUN for test SMS.ne4_ne4.FC5AV1C-H01A.melvin_gnu.cam-thetahy_ftype4 in 1781.278377 seconds (PASS). [COMPLETED 6 of 12]
Finished RUN for test SMS.ne4_ne4.FC5AV1C-H01A.melvin_gnu.cam-thetahy_sl in 1738.782618 seconds (PASS). [COMPLETED 7 of 12]
Finished RUN for test SMS.ne4_ne4.FC5AV1C-H01A.melvin_gnu.cam-thetanh_ftype0 in 3055.692741 seconds (PASS). [COMPLETED 8 of 12]
Finished RUN for test SMS.ne4_ne4.FC5AV1C-H01A.melvin_gnu.cam-thetanh_ftype1 in 3074.318908 seconds (PASS). [COMPLETED 9 of 12]
Finished RUN for test SMS.ne4_ne4.FC5AV1C-H01A.melvin_gnu.cam-thetanh_ftype2 in 3064.935379 seconds (PASS). [COMPLETED 10 of 12]
Finished RUN for test SMS.ne4_ne4.FC5AV1C-H01A.melvin_gnu.cam-thetahy_ftype0 in 1714.389403 seconds (PASS). [COMPLETED 11 of 12]
Finished RUN for test SMS.ne4_ne4.FC5AV1C-H01A.melvin_gnu.cam-thetanh_ftype4 in 2095.280535 seconds (PASS). [COMPLETED 12 of 12]
```

e3sm_developer currently takes about 5 hours on melvin. This PR would add another 2.5 hours. Based on your anvil numbers, the impact on batch machines is much less, assuming there are free nodes.

@rljacob , do you have any thoughts on this? This PR significantly increases the overall computational cost of e3sm_developer.

**Comment by jgfouca** [comment]
@rljacob , @oksanaguba , I reran SMS.ne4_ne4.FC5AV1C-H01A.melvin_gnu.cam-thetanh_ftype0 on its own and it only took 832 seconds (opposed to 3055 seconds above). So it seems we are oversubscribing melvin to the point that performance is seriously degraded. I will investigate reducing the processor pool size for melvin. In the meantime, I think this PR is fine.

**Comment by jgfouca** [comment]
Merged to next.

**Comment by oksanaguba** [comment]
@rljacob thanks! I forgot about description (added now). I will change H01A to L. These tests use only 2 builds. Could I please keep tests together, either in _developer suite or in _integration? This way there will be no extra builds. Thanks for suggesting _integration instead of _developer, this way there is no issue with melvin. However, @jgfouca already merged it into next.

**Comment by jgfouca** [comment]
@oksanaguba , if the change of H01A to L makes them run faster, we can probably keep them on melvin (e3sm_developer).

**Comment by singhbalwinder** [comment]
These tests should use -L, as @rljacob mentioned, H01A is only meant for ne120 (high res) grid.

**Comment by oksanaguba** [comment]
With -L compset on anvil times are essentially the same, build is 15+15 min and run is ~4+12 min, so, comparable with what was there for -H01A settings. I would assume tilmestep is based on resolution, ne4, which stayed the same, but I don't have a hires compset built, so, it is only speculation. @jgfouca , @rljacob , can it go in now or do you want it in integration?

**Comment by rljacob** [comment]
If you don't want to break them up, move it all to integration.  Jim can re-merge to next.

**Comment by jgfouca** [comment]
I agree with Rob, these probably belong in e3sm_integration for now.

**Comment by oksanaguba** [comment]
thanks, done.

**Comment by jgfouca** [comment]
Merged to next.

**Comment by jgfouca** [comment]
@oksanaguba , several of these tests are failing on chama.

**Comment by oksanaguba** [comment]
cam-preqx_ftype0, cam-preqx_ftype1, cam-preqx_ftype4 -- fail in build, cmake related

SMS.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.cam-thetahy_ftype1 -- fail, instability

I will fix instability fail now and let's see if tomorrow preqx tests are built? @jgfouca how should I fix this? new PR?

**Comment by jgfouca** [comment]
@oksanaguba , just make additional commits to this PR branch and I'll re-merge to next.

**Comment by oksanaguba** [comment]
@jgfouca this last commit with cam_theta suite ran on skybridge. so, I hope this is it. Mark pointed out that it may not even be instability, it could be a spin up. My concern is that even if this suite (theta + ne4) runs on skybridge and anvil, there is still possibility it would crash on some other machine. So, I reduced tilmestep for both physics and dynamics (as Mark suggested), to make it less likely to crash. I think it is ready (again).

**Comment by jgfouca** [comment]
Re-merged to next.

**Comment by rljacob** [comment]
Does SMS.ne4_ne4.FC5AV1C-L.*.cam-thetahy_sl  replace 
SMS.ne4_ne4.FC5AV1C-L.*.cam-thetasl  ?

**Comment by oksanaguba** [comment]
@rljacob yes.

**Comment by rljacob** [comment]
@jgfouca this needs a bless request and merge to master.

**Comment by oksanaguba** [comment]
@jgfouca I am confused about what's going on with cdash. next shows these new tests and they are broken (so, blesses did not get thru?), master does not hav these tests, it has an old removed test thetasl. but master repo has right tests in tests.ry .

**Comment by oksanaguba** [comment]
@jgfouca never mind. tests ran on june 10th at 1 am. they did not run today.

**Pull request merged**
