### PR TITLE
Add timers to driver-mct to provide context to SCORPIO timers

### LINKED ISSUE #4522: new SCORPIO timers not associated with meaningful timers in CPL
SCORPIO has introduced some new timers. Unfortunately, the existing timers in CPL are not sufficient to localize where the SCORPIO calls are coming from. (This issue is a companion to a PR in preparation to address this in driver-mct/ .)

For example, for a run on Chrysalis:

           "CPL:init_aream"                                                     -       1    -       0.297017     0.297017     0.297017         0.000000
     *       "PIO:openfile"                                                     -      20    -       0.322871     0.102736     0.005914         0.000001
     *       "PIO:initdecomp_dof"                                               -      30    -       0.043455     0.006085     0.000937         0.000002
               "PIO:PIOc_initdecomp"                                            -      30    -       0.043385     0.006082     0.000935         0.000002
                 "PIO:box_rearrange_create"                                     -      30    -       0.041747     0.005819     0.000923         0.000002
     *             "PIO:pio_swapm"                                              -     359    -       0.055745     0.003022     0.000028         0.000025
     *       "PIO:PIOc_read_darray"                                             -     256    -       0.239484     0.059991     0.000224         0.000018
               "PIO:read_darray_nc"                                             -     256    -       0.198016     0.059798     0.000110         0.000018
               "PIO:rearrange_io2comp"                                          -     256    -       0.016895     0.000452     0.000036         0.000018
     *           "PIO:pio_swapm"                                                -     359    -       0.055745     0.003022     0.000028         0.000025
     *       "PIO:PIOc_sync"                                                    -      30    -       0.130076     0.037097     0.000001         0.000002
     *         "PIO:write_total"                                                -    1598    -       0.183868     0.037098     0.000001         0.000110
     *           "PIO:flush_output_buffer"                                      -      40    -       0.115731     0.033161     0.000002         0.000003
                 "PIO:flush_buffer"                                             -      13    -       0.015164     0.003913     0.000276         0.000001
                   "PIO:PIOc_write_darray_multi"                                -      13    -       0.015081     0.003897     0.000271         0.000001
                     "PIO:rearrange_comp2io"                                    -      13    -       0.012067     0.003230     0.000185         0.000001
                     "PIO:write_darray_multi_par"                               -      13    -       0.001823     0.000616     0.000008         0.000001
     *       "PIO:PIOc_freedecomp"                                              -      30    -       0.000782     0.000049     0.000009         0.000002
     *       "PIO:closefile"                                                    -      21    -       0.147596     0.031119     0.001807         0.000001
               "PIO:PIOc_closefile"                                             -      21    -       0.147572     0.031118     0.001806         0.000001
                 "PIO:PIOc_closefile_write_mode"                                -       1    -       0.006217     0.006217     0.006217         0.000000
     ...
           "CPL:RESTART"                                                        -       1    -       0.227893     0.227893     0.227893         0.000000
     *       "PIO:initdecomp_dof"                                               -      30    -       0.043455     0.006085     0.000937         0.000002
               "PIO:PIOc_initdecomp"                                            -      30    -       0.043385     0.006082     0.000935         0.000002
                 "PIO:box_rearrange_create"                                     -      30    -       0.041747     0.005819     0.000923         0.000002
     *             "PIO:pio_swapm"                                              -     359    -       0.055745     0.003022     0.000028         0.000025
     *       "PIO:PIOc_sync"                                                    -      30    -       0.130076     0.037097     0.000001         0.000002
     *         "PIO:write_total"                                                -    1598    -       0.183868     0.037098     0.000001         0.000110
     *           "PIO:flush_output_buffer"                                      -      40    -       0.115731     0.033161     0.000002         0.000003
                 "PIO:flush_buffer"                                             -      13    -       0.015164     0.003913     0.000276         0.000001
                   "PIO:PIOc_write_darray_multi"                                -      13    -       0.015081     0.003897     0.000271         0.000001
                     "PIO:rearrange_comp2io"                                    -      13    -       0.012067     0.003230     0.000185         0.000001
                     "PIO:write_darray_multi_par"                               -      13    -       0.001823     0.000616     0.000008         0.000001
     *       "PIO:PIOc_freedecomp"                                              -      30    -       0.000782     0.000049     0.000009         0.000002
             "PIO:createfile"                                                   -       1    -       0.009078     0.009078     0.009078         0.000000
               "PIO:PIOc_createfile"                                            -       1    -       0.009067     0.009067     0.009067         0.000000
             "PIO:PIOc_put_att_tc"                                              -    1301    -       0.016324     0.002210     0.000006         0.000090
     *         "PIO:write_total"                                                -    1598    -       0.183868     0.037098     0.000001         0.000110
     *           "PIO:flush_output_buffer"                                      -      40    -       0.115731     0.033161     0.000002         0.000003
                 "PIO:flush_buffer"                                             -      13    -       0.015164     0.003913     0.000276         0.000001
                   "PIO:PIOc_write_darray_multi"                                -      13    -       0.015081     0.003897     0.000271         0.000001
                     "PIO:rearrange_comp2io"                                    -      13    -       0.012067     0.003230     0.000185         0.000001
                     "PIO:write_darray_multi_par"                               -      13    -       0.001823     0.000616     0.000008         0.000001
             "PIO:put_var_0d_double"                                            -       2    -       0.000183     0.000112     0.000071         0.000000
             "PIO:put_var_0d_int"                                               -       8    -       0.000495     0.000114     0.000032         0.000001
     *         "PIO:PIOc_put_vars_tc"                                           -      13    -       0.000715     0.000163     0.000024         0.000001
             "PIO:write_darray_double"                                          -     252    -       0.021763     0.000133     0.000054         0.000017
               "PIO:PIOc_write_darray"                                          -     252    -       0.021462     0.000131     0.000053         0.000017
     ...
     *   "PIO:openfile"                                                         -      20    -       0.322871     0.102736     0.005914         0.000001
     *   "PIO:PIOc_read_darray"                                                 -     256    -       0.239484     0.059991     0.000224         0.000018
           "PIO:read_darray_nc"                                                 -     256    -       0.198016     0.059798     0.000110         0.000018
           "PIO:rearrange_io2comp"                                              -     256    -       0.016895     0.000452     0.000036         0.000018
     *       "PIO:pio_swapm"                                                    -     359    -       0.055745     0.003022     0.000028         0.000025
     *   "PIO:closefile"                                                        -      21    -       0.147596     0.031119     0.001807         0.000001
           "PIO:PIOc_closefile"                                                 -      21    -       0.147572     0.031118     0.001806         0.000001
             "PIO:PIOc_closefile_write_mode"                                    -       1    -       0.006217     0.006217     0.006217         0.000000
         "PIO:PIOc_get_att_tc"                                                  -      17    -       0.000483     0.000058     0.000023         0.000001
         "PIO:PIOc_get_vars_tc"                                                 -       4    -       0.030272     0.023972     0.000491         0.000000

and

     ...
            3 CPL:init_aream
           17 CPL:RUN_LOOP
           20   PIO:openfile
     
            4 CPL:init_aream
           13 CPL:RESTART
           13 CPL:RUN_LOOP
           30   PIO:initdecomp_dof
     ...
            4 CPL:init_aream
          252 CPL:RUN_LOOP
          256   PIO:PIOc_read_darray
     ...

where  CPL:RUN_LOOP is much too high level a timer to provide much context, and both CPL:init_aream and CPL:RESTART have a number of things going on internally.

### PR DESCRIPTION
**Pull request by worleyph**
SCORPIO has introduced some new timers. Unfortunately, the existing
timers in driver-mct are not sufficient to localize where the SCORPIO calls
are coming from. Here new timers are added to provide the missing
context. A few timers are also added to provide context for these
added timers and for some of the already existing timers.

While 22 new timers are introduced, in normal usage only 8 to 13 new
timers appear in the timing files.

Four existing timers were also renamed, in order to add a CPL prefix:

comp_init_cc_iac       => CPL:comp_init_cc_iac
driver_rofpost_histaux => CPL:seq_hist_writeaux-r2x
DRIVER_ROFPOST_BARRIER => CPL:ROFPOST_BARRIER
DRIVER_ROFPOST         => CPL:ROFPOST

Two existing timers were then renamed to eliminate collisions
from the previous renamings:

CPL:ROFPOST_BARRIER    => CPL:ROFRUNPOST_BARRIER
CPL:ROFPOST            => CPL:ROFRUNPOST

Fixes #4522

[BFB]

### CODE REVIEW

**Comment by worleyph** [comment]
Development and testing on Chrysalis using 

     --compset WCYCL1850-4xCO2 --res ne30pg2_EC30to60E2r2 --pecount XS

**Comment by rljacob** [comment]
@worleyph can you rebase this with latest master? I just merged the removal of the extra restart read.

**Comment by worleyph** [comment]
@rljacob , sure ... please remind me how to rebase. Or should I just start over with the latest master? It would be simple to implement these same changes in master.

**Comment by rljacob** [comment]
I guess start over after #4544 is merged to master.

**Comment by worleyph** [comment]
Will do. Thanks.

**Comment by rljacob** [comment]
master is now ready for you to redo this.

**Comment by rljacob** [comment]
@worleyph are you working on this?

**Comment by worleyph** [comment]
@rljacob , yes. Running final experiments now. However, out of town taking care of family responsibilities and unable to spend more than a few minutes on this per day. Arriving home on Saturday, late. Hopefully can get a new PR submitted on Sunday or Monday.

**Comment by rljacob** [comment]
Replaced by #4561

**Pull request closed without merging**
