### PR TITLE
Add CentOS7 modules on Anvil

### PR DESCRIPTION
**Pull request by amametjanov**
Add CentOS7 modules on Anvil

[BFB]

### CODE REVIEW

**Comment by amametjanov** [comment]
To test and run with new modules, please run with `--compiler intel18` directly from the login nodes (`ssh b512` not needed). Modules for Intel v.17.0.0 will be added as soon as they're installed. E.g.:
```
@blueslogin2:E3SM $ ./cime/scripts/create_test SMS.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6
```
I didn't see errors in `e3sm_integration` runs. If all is well, CentOS6 nodes can be rebooted with CentOS7 images.

**Comment by rljacob** [comment]
How does this relate #3182 ?

**Comment by amametjanov** [comment]
This has everything that #3182 has except for the constraint on "bad" thread counts. To check if this last piece is still an issue, I ran `SMS_P18x4.ne4_ne4.FC5AV1C-L.anvil-centos7_intel18` 11 times (1 initial 5-day run, 10 restart runs) and didn't get any NaN errors (like the ones previously on CentOS6+intel-17.0.0+mkl-2017.0.098). Besides CentOS7, this PR also includes newer `intel/18.0.4-443hhug` and `intel-mkl/2018.4.274-jwaeshj` modules.

**Comment by amametjanov** [comment]
Yes, after switching to CentOS7.

**Comment by ndkeen** [comment]
Nice to have the fix for the failing DEBUG build, but why was it in a PR to add Anvil modules?

**Comment by amametjanov** [comment]
The errors were showing up when testing new modules.

**Pull request merged**
