### PR TITLE
Change the name of a test in extra_coverage to be a compset that exists

### PR DESCRIPTION
**Pull request by ndkeen**
Fix typo of testname, use `GMPAS-JRA1p5-WW3` 
[bfb]

### CODE REVIEW

**Comment by rljacob** [comment]
I think this will download a lot of data without the other mods in https://github.com/E3SM-Project/E3SM/pull/5274/files

**Comment by ndkeen** [comment]
There are a few tests that still need to download a lot of data. We could comment the test out for now. Unless `GMPAS-JRA-WW3` is supposed to the right name, seems like we'd want to change the name to `GMPAS-JRA1p5-WW3`

On chrys it fails with:
```
 15: forrtl: severe (194): Run-Time Check Failure. The variable 'w3initmd_mp_w3init_$OPENED' is being used in '/lcrc/group/e3sm/ac.ndkeen/wacmy/nexty-may4/components/ww3/src/WW3/model/tmp/w3initmd.F90(545,15)' without being defined
 15: Image              PC                Routine            Line        Source
 15: e3sm.exe           00000000059DA18A  w3initmd_mp_w3ini         545  w3initmd.F90
 15: e3sm.exe           00000000055D4F60  wav_comp_mct_mp_w         796  wav_comp_mct.F90
 15: e3sm.exe           00000000004917DB  component_mod_mp_         257  component_mod.F90
 15: e3sm.exe           000000000043A648  cime_comp_mod_mp_        1476  cime_comp_mod.F90
 15: e3sm.exe           000000000048829D  MAIN__                    122  cime_driver.F90
 15: e3sm.exe           0000000000426522  Unknown               Unknown  Unknown
 15: libc-2.28.so       000015554E0BD493  __libc_start_main     Unknown  Unknown
 15: e3sm.exe           000000000042642E  Unknown               Unknown  Unknown

/lcrc/group/e3sm/ac.ndkeen/scratch/chrys/SMS_D_Ln3.TL319_EC30to60E2r2_wQU225EC30to60E2r2.GMPAS-JRA1p5-WW3.chrysalis_intel.20230504_153841_855dhg
```

**Comment by ndkeen** [comment]
Note that a GNU build does work on chrysalis
`/lcrc/group/e3sm/ac.ndkeen/scratch/chrys/SMS_D_Ln3.TL319_EC30to60E2r2_wQU225EC30to60E2r2.GMPAS-JRA1p5-WW3.chrysalis_gnu.20230504_185338_5waw9d`

**Comment by rljacob** [comment]
Closed in favor of #5274

**Pull request closed without merging**
