### PR TITLE
Update mapping and domain files for ne30pg2-oRRS18to6v3

### PR DESCRIPTION
**Pull request by jonbob**
Adds new domain and mapping files for the ne30pg2-oRRS18to6v3 resolution, as well as smoothed runoff between r05 and oRRS18to6v3

[BFB] for all tested configurations

### CODE REVIEW

**Review by vanroekel — APPROVED** [review]
approved by visual inspection

**Review by darincomeau — APPROVED** [review]
Approved based on developer testing

**Comment by jonbob** [comment]
passes:
* SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod
* ERS_Ld5.T62_oQU120.CMPASO-NYF.chrysalis_intel

merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
