### PR TITLE
update sbetr to remove redundant print to log

### PR DESCRIPTION
**Pull request by jinyuntang**
This avoids redundant output to log file.
Also suspend unit testing until pfunit fixed.
Update sbetr submodules to use ssh.  Get ready to fix obsolete 3rd party libs

[BFB]

### CODE REVIEW

**Comment by jinyuntang** [comment]
@ndkeen I checked the test ERS.f19_g16.I1850ELM.pm-cpu_gnu.elm-betr, it no longer produce the large log file. Please review. Thanks.

**Comment by ndkeen** [comment]
I see that you have commented (not removed) the debug print statement. But it kinda looks like other things were also changed?  I might ask others involved to verify those changes are inert -- or would benefit from a different PR -- or at least update to the title.

**Comment by rljacob** [comment]
The current version of sbetr being used is 66260f4991d6.  You should make a branch from that, fix just the debug statement, and then update the submodule to point to that branch.  Otherwise this is a much bigger "update sbetr" PR.

**Comment by rljacob** [comment]
The other updates looks like its just testing, not code, so maybe this is fine as is.

**Comment by ndkeen** [comment]
Yes, I also see they are testing related -- I just don't know if it was intentional, related, important, etc. So if you think it's ok, I will approve.

**Review by ndkeen — APPROVED** [review]

**Comment by rljacob** [comment]
Wait for @peterdschwartz or @bishtgautam to approve.

**Review by bishtgautam — APPROVED** [review]

**Comment by ndkeen** [comment]
Can we merge this?

**Comment by ndkeen** [comment]
Can we find someone more familiar with working with submodules?

**Pull request merged**
