### PR TITLE
Add regression test for gen_domain tool (WIP)

### PR DESCRIPTION
**Pull request by brhillman**
Add a regression test for the `gen_domain` tool in `cime/tools/mapping/gen_domain_files`. This adds a class to `scripts_regression_tests.py` to implement and run the test. The test compares against an existing domain file in the inputdata repository, using an existing mapping file in the repository. The `cprnc` tool is used to do the comparison. Test is successful if `cprnc` indicates that a new set of domain files generated by the `gen_domain` code are bit-for-bit with the existing domain files in the repository.

### CODE REVIEW

**Comment by brhillman** [comment]
I can do that. Temporary subdirectory of the scripts/tests directory, or in scratch somewhere? Regardless, does implementation make sense, and seem like a reasonable approach? I was rather hoping to make it a little easier for someone looking in the gen_domain directory to be clear how to run tests, but it was easiest I guess to make use of everything already in scripts_regression_tests.py.

**Comment by jgfouca** [comment]
@brhillman , the simplest is just use tempfile.mkdtemp() as some other tests are doing.

**Comment by rljacob** [comment]
should scripts_regression_tests.py, which is supposed to test things in cime/scripts, be testing things in cime/tools ?

**Comment by brhillman** [comment]
@rljacob would you suggest putting this elsewhere? There does not seem to be an overall testing framework for cime/tools. I started by writing a stand-alone script in cime/tools/mapping/gen_domain_files, which is nice because it is then obvious to someone looking at the code where that code gets tested, but ultimately we would like tests for these tools to be run as part of regular development so that they don't break (due to changes in CIME, build environments, etc.).

**Comment by rljacob** [comment]
I guess I'll leave that up to Jim.  We could put it there for now to get the test running but I think we ultimately want a separate test driver for tests in cime/tools.

**Comment by PeterCaldwell** [comment]
I think this is a case of our current needs outgrowing the original vision for the directory organization. This is a regression test in the sense that it is checking if code generated by this tool is bfb and it needs to do so using a script rather than by running the model because it is testing a tool that is separate from the model but packaged with the model code. I don't think it makes sense to put this test and its accompanying script in cime/scripts/ because - as Ben says - it is good to have the test live where the code its testing resides and the code tested really only makes logical sense to reside in cime/tools/mapping/gen_domain_files/. I think the best solution is probably to create a new test driver that looks a lot like scripts_regression_tests.py (and perhaps has the same name) under cime/tools/ or perhaps cime/tools/mapping/... 

Just throwing out a suggestion - you all have better knowledge of the nuances here so I defer to you.

**Comment by jgfouca** [comment]
I'm OK with this living in scripts_regression_tests.py for now.

**Comment by brhillman** [comment]
@PeterCaldwell thanks for chiming in here. I will take a look at what it would take to move the basic functionality into cime/tools/mapping/gen_domain_files, but I think for the time being at least we probably need to use the frameworks built up here for cime/scripts. Although maybe a prerequisite PR could add a similar framework into cime/tools, and we could leverage that for these types of tests and incorporate into some kind of regularly run (nightly? per merge?) tests.

**Comment by jgfouca** [comment]
@brhillman , is this ready to merge?

**Comment by brhillman** [comment]
@jgfouca I haven't addressed your concern about temporary files in the source directories. The build still produces object files in the gen_domain source. From your comment above, I got the impression that these needed to go into a temporary directory and then get cleaned up?

**Comment by jgfouca** [comment]
@brhillman , that's correct. I was just going through my open PRs.

**Comment by rljacob** [comment]
@brhillman please take care of cleaning up this old PR.

**Comment by brhillman** [comment]
@jgfouca I think this is creating the temp directory and cleaning up now for the gen_domain test (`M_TestGenDomain`). Does this look like what you wanted? Note that it DOES still compile code, so object files are created in the source tree...is that a problem?

**Comment by jgfouca** [comment]
@brhillman , it's a somewhat firm requirement that all testing artifacts be properly-managed (isolated to a single directory that gets cleaned-up after the test). Why not use that same temp directory for builds and runs?

**Comment by brhillman** [comment]
Yeah understandable. I think I might have to tweak the build for gen_domain and cprnc to accomplish that. I'll look into it.

**Comment by rljacob** [comment]
Can't we just put *.o and other artifacts in .gitignore?

**Comment by jgfouca** [comment]
@rljacob , we could, but that would essentially allowing the "pollution" and sweeping it under the rug. It would be better to not pollute in the first place.

**Comment by brhillman** [comment]
Closing this PR for now, tests for the domain tool should probably live outside the tests for CIME scripts, and would otherwise need to better manage build and tear-down of object files.

**Pull request closed without merging**
