### PR TITLE
Decrease cost of assign_chunks

### LINKED ISSUE #2496: high cost of create_chunks in ATM initialization at scale
As part of an investigation into decreasing initialization cost for high resolution compsets, a scaling issue was identified in the assign_chunks routine for large process and chunk counts when using phys_loadbalance=2. In particular, this routine contains a doubly nested loop of lengths nprocs and nchunks, respectively. On Cori-KNL for an ne120 resolution and an 86400x4 decomposition, the number of iterations of this loop is 86400*86400*4 and takes a little over 7 minutes.

A new implementation with improved complexity has been implemented, and a PR will be submitted that resolves this issue.

### PR DESCRIPTION
**Pull request by worleyph**
The routine assign_chunks is called as part of create_chunks in
phys_grid_init when determining what decomposition to use in the
CAM physics. It attempts to assign chunks to processes in such
a way as to minimize the amount of MPI communication required in
d_p_coupling and p_d_coupling when moving data between the dynamics
and physics decompositions. It uses a greedy heuristic that
identifies which process in the dynamics decomposition was assigned
the most columns in a given chunk, and assigns the chunk to that
process for the physics decomposition. If this process has already
been assigned its target number of chunks, the algorithm then attempts
to assign the chunk to the process assigned the second-most columns.
etc.

As implemented currently, there is a doubly nested loop of sizes
nprocs and nchunks, respectively, when using phys_loadbalance=2.
For ne120 experiments on 86400 processes with 4 threads per process
(for example, on Cori-KNL at NERSC), the number of iterations is
86400x86400x4, and the computation takes over 7 minutes. Here the
algorithm is reorganized, decreasing the loop over the number of
processes to something less than
  min(max(number of columns in a chunk), nprocs).
For this example, the number of iterations decreases to 3x86400x3 ,
and the execution time decreases correspondingly.

Note that at process count scale, especially when using
phys_loadbalance=2 (which uses a wrap map), identifying the
process with the maximum number of columns may not be worth the
cost. Finding any process that was assigned one of the columns in the
chunk is probably the best that can be achieved. If the new algorithm
still proves too expensive for these extreme cases, we can then look
to implement a hybrid algorithm, using the new algorithm when the
number of processes is moderate or when not using phys_loadbalance=2,
and something less costly when the number of processes is large.
However, experiments with the new algorithm show the cost to be less
than one second on Cori-KNL even for the extreme example described
previously.

Fixes #2496

[BFB]

### CODE REVIEW

**Comment by worleyph** [comment]
I have tested this on Titan and on Cori-KNL using F compsets of size ne4 and ne30 on Titan, and ne120 on Cori-KNL, with a variety of PE layouts. It is BFB (as it should be). It does change the assignment of chunks to processes as compared to the original algorithm somewhat. I could have retained the exact assignment, but the new one is actually a little better, and trying to retain the old ordering would have required an small increase in cost (and more complicated code - would have had to sort the list of chunk-specific processes).

It is difficult to claim comprehensive testing, but I have run with additional diagnostic output and tried to look at edge cases, and have seen no problems.

**Comment by worleyph** [comment]
pinging @singhbalwinder and @mt5555 .

**Comment by mt5555** [comment]
looks great.   did I read that right that the new algorithm reduces the cost from 7min to a few seconds?

**Comment by worleyph** [comment]
>  did I read that right that the new algorithm reduces the cost from 7min to a few seconds?

Yes - but this was the worst case (86400x4 on Cori-KNL, phys_loadbalance = 2). We typically will not be running production at that process count. For small process counts, typical of low resolution, there is no observable performance differences (might even be a little slower, but also < 1 second).

**Comment by singhbalwinder** [comment]
Thanks @worleyph. I will start merging this.

**Comment by singhbalwinder** [comment]
pushed to next

**Pull request merged**
