### PR TITLE
Add FRIS meshes

### PR DESCRIPTION
**Pull request by irenavankova**
Meshes with high resolution in the southern Weddell Sea and beneath the Filchner Ronne Ice Shelf (FRIS). The meshes go down to 1, 2, 4, and 8 km beneath FRIS and on the continental shelf in front of it.

Meshes are:
`FRISwISC01to60E3r1`
`FRISwISC02to60E3r1`
`FRISwISC04to60E3r1`
`FRISwISC08to60E3r1`

They are intended only for use in E3SM G-case simulations.  Mapping and domain files for supporting B-cases or other coupled configurations are not included and will not be supported.

Related Ocean Discussion is here:

https://github.com/E3SM-Ocean-Discussion/E3SM/pull/75

### CODE REVIEW

**Comment by xylar** [comment]
@irenavankova, do you have any links to analysis you have run for simulations with these meshes?  I know they aren't with this exact version of the branch but that would demonstrate that the meshes work as expected.

**Review by xylar — APPROVED** [review]
I ran 5-day smoke tests on the coarsest 2 meshes and shorter tests on the 2 finer meshes on Chrysalis.

I am also approving based on test results for each mesh that I have seen from @irenavankova over the past year.

**Comment by irenavankova** [comment]
> @irenavankova, do you have any links to analysis you have run for simulations with these meshes? I know they aren't with this exact version of the branch but that would demonstrate that the meshes work as expected.

No, as it is all run on chicoma there isn't web access, but I could put some on Anvil if you like?

**Comment by xylar** [comment]
That's up to you but I think it wouldn't hurt to have a few example results from these meshes if it's not too much trouble.

**Comment by irenavankova** [comment]
Here is an example of MPAS Analysis from the 4 km mesh, years 9-10, Gcase:

https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.vankova/analysis/F4_spinup/clim_9-10_ts_1-10/html/ocean/index.html

**Comment by xylar** [comment]
Very exciting, thanks @irenavankova!  The enhanced eddy activity from the higher resolution can be seen in:
image
and the ability to better resolve topography is also visible in transects like:
image

**Comment by rljacob** [comment]
notes:  needs netcdf3 conversion for some mapping files.

**Comment by xylar** [comment]
@jonbob and @rljacob, which mapping files need conversion?

**Comment by jonbob** [comment]
@xylar -- a lot of the ones I had made with my script. It turns out the tempest default output is not what e3sm wants to use. I was going to fix them today and be ready to merge this PR.

**Comment by xylar** [comment]
Okay, great!  I'm sorry for the extra work for you, though.

**Comment by jonbob** [comment]
The mapping files are now converted and Ill work on merging this as soon as I can

**Comment by jonbob** [comment]
confirmed all new files are in the correct format and on the inputdata server. Passes:
* ERS_Ld5.T62_oQU120.CMPASO-NYF.chrysalis_intel
* ERP_Ld3.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-pioroot1

merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
