### PR TITLE
Adds a new test for the multi-instance capability

### PR DESCRIPTION
**Pull request by bishtgautam**
An I-compset test is added that sets up two instances of ELM and MOSART.

[BFB]

### CODE REVIEW

**Review by whannah1 — APPROVED** [review]

**Comment by rljacob** [comment]
But just one instance of DATM?  That works?

**Comment by bishtgautam** [comment]
All prognostic components need to have the same number of instances, but the data components have the flexibility to have a single or multiple instances. This is based on the Section "Multi-instance component functionality" described in https://www2.cesm.ucar.edu/models/cesm1.2/cesm/doc/usersguide/ug.pdf which has the following example:

>For an F compset, only atm, lnd, rof are full prognostic components. The
ocn is a prescribed data component, cice is a mixed prescribed/prognostic
component (ice-coverage is prescribed) and glc and wav are stub components.
Lets say we want to run 2 instances of CAM in this experiment. The current
implementation of multi-instances will also require you to run 2 instances of
CLM, CICE and RTM. However, you have the flexibility to run either 1 or 2
instances of DOCN (we can ignore glc and wav since they do not do anything
in this compset).

**Review by rljacob — APPROVED** [review]

**Comment by peterdschwartz** [comment]
merged to next

**Comment by peterdschwartz** [comment]
merged to master.

Note:  pm-cpu has yet to report and may not today for this test.

**Pull request merged**
