### PR TITLE
Implement ELM v2 data architecture for mass and energy state and flux variables

### PR DESCRIPTION
**Pull request by thorntonpe**
Migrates mass and energy state and flux variables from CLM4.5 data structures, which mixed variables at multiple subgrid levels, to ELM v2 data structures, which separate the variables according to subgrid level. For example, carbon state variables are moved from a single type into three distinct types, one for gridcell-level, one for column-level, and one for vegetation (patch)-level variables. Methods acting on these types are also defined independently for each subgrid level. Migrates all energy, water, carbon, nitrogen, and phosphorus state and flux variables and data-type methods.

Leaves open the issue of how to structure subroutine calling interfaces. The original code uses a variety of methods. Here, an example is provided for the module biogeochem/CNCStateUpdate1Mod.F90 and all its upstream calls, based on explicit references to data type instances at the clm_driver() level, and passed references at all lower levels.

Branch tests bit-for-bit against the E3SM land developer test suite.

[BFB]

### CODE REVIEW

**Comment by thorntonpe** [comment]
Design document for this work is on the Land/Energy NGD Confluence page, at 
https://acme-climate.atlassian.net/wiki/spaces/NGDLE/pages/924451042/Design+Documents+for+new+PRs

**Comment by rljacob** [comment]
Given the number of conflicts, this is a case where you should merge master to the branch to help resolve them.

**Comment by rljacob** [comment]
Although you'll have to do all your testing again then.

**Comment by thorntonpe** [comment]
Thanks to help from @jqyin , the branch is rebased to yesterday's master (at commit 4f22ec). I have now pushed a new commit to clean up a few remaining conflicts, generated updated master baselines, and retested the branch against these baselines with the full land developer test suite. All PASS.

**Comment by thorntonpe** [comment]
While reviewers take some time to look over this PR, I am working on a new commit that will remove the CNDV code and references to it, as discussed on a previous Land/Energy NGD call.

**Comment by thorntonpe** [comment]
Reviewers for this PR: please provide initial comments this week. I would like to move forward with any modifications, and then head toward integration.

**Comment by bishtgautam** [comment]
@thorntonpe, Here are my comments/questions:

- What do you think about adding new subgrid-level in directories in `src/data_types/` and moving subgrid-level F90 in those new directories? Additionally, `<subgrid>DataTypes.F90` are split into multiple files? e.g.

```
├── src/
│   ├── data_types
│      ├── column
│      │  ├── ColumnType.F90
│      │  ├── ColumnEnergyFluxType.F90
│      │  ├── ColumnEnergyStateType.F90
│      │  ├── ColumnWaterFluxType.F90
│      │  ├── ColumnWaterStateType.F90
│      │  ├── ...
│      │  ├── ...
│      │  
│      ├── gridcell
│      │  ├── GridcellType.F90
│      │  ├── GridcellEnergyFluxType.F90
│      │  ├── GridcellEnergyStateType.F90
│      │  ├── GridcellWaterFluxType.F90
│      │  ├── GridcellWaterStateType.F90
│      │  ├── ...
│      │  ├── ...
│      │  
```
- The `src/data_types/CNStateType.F90` contains multiple subgrid level variables (e.g. `burndate_patch`, `gdp_lf_col`, etc). Will this file be refactored in a future PR?

**Comment by jqyin** [comment]
Hi @qzhu-lbl , could you add your review for this PR?

**Comment by thorntonpe** [comment]
@bishtgautam  thanks for these suggestions. Adding the suggested sub-grid directories to the data_types subdir seems like a good organization. I also like the idea of splitting the existing module files into several files, one for each data type. 
And yes, shifting the variables out of CNStateType.F90 and into the new data structures is also a good idea. I think that putting all of these changes into a subsequent PR makes sense.

> * What do you think about adding new subgrid-level in directories in `src/data_types/` and moving subgrid-level F90 in those new directories? Additionally, `<subgrid>DataTypes.F90` are split into multiple files? e.g.
> 
> ```
> ├── src/
> │   ├── data_types
> │      ├── column
> │      │  ├── ColumnType.F90
> │      │  ├── ColumnEnergyFluxType.F90
> │      │  ├── ColumnEnergyStateType.F90
> │      │  ├── ColumnWaterFluxType.F90
> │      │  ├── ColumnWaterStateType.F90
> │      │  ├── ...
> │      │  ├── ...
> │      │  
> │      ├── gridcell
> │      │  ├── GridcellType.F90
> │      │  ├── GridcellEnergyFluxType.F90
> │      │  ├── GridcellEnergyStateType.F90
> │      │  ├── GridcellWaterFluxType.F90
> │      │  ├── GridcellWaterStateType.F90
> │      │  ├── ...
> │      │  ├── ...
> │      │  
> ```
> * The `src/data_types/CNStateType.F90` contains multiple subgrid level variables (e.g. `burndate_patch`, `gdp_lf_col`, etc). Will this file be refactored in a future PR?

**Comment by thorntonpe** [comment]
@jqyin I think this PR is ready for integration.

**Comment by jqyin** [comment]
Merged to next.

**Comment by rljacob** [comment]
There was one build fail on gnu:
https://my.cdash.org/testDetails.php?test=45738002&build=1617984

And  diffs against baselines for the coupler history in 2 cases:
 SMS_Ln9.ne4_ne4.FC5AV1C-L.melvin_gnu.cam-outfrq9s
SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.anvil_intel.allactive-v1cmip6

**Comment by jqyin** [comment]
Build fail seems straightforward to fix.: add " use shr_log_mod         , only : errMsg => shr_log_errMsg".

DIFF for SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.anvil_intel.allactive-v1cmip6 is also small? :

 FSDS   (lndgrid,time)  t_index =      1     1
         83      866  (   712,     1) (   787,     1) (   248,     1) (   248,     1)
                 407   5.426869558599763E+02   0.000000000000000E+00 1.1E-13  2.802808119013097E+02 3.9E-17  2.802808119013097E+02
                 407   5.426869558599761E+02   0.000000000000000E+00          2.802808119013098E+02          2.802808119013098E+02
                 866  (   712,     1) (   787,     1)
          avg abs field values:    1.902832321701630E+02    rms diff: 2.5E-14   avg rel diff(npos):  3.9E-17
                                   1.902832321701630E+02                        avg decimal digits(ndif): 15.7 worst: 15.4
 RMS FSDS                             2.4889E-14            NORMALIZED  1.3080E-16

**Comment by thorntonpe** [comment]
@jqyin That fix for errMsg looks fine, can you make the needed commit?
For the DIFFs: These are very, very small, and seem to be happening in the first time step, although I'm not sure I'm interpreting the time part of this correctly. Is this the only field with DIFFs in the two failed cases? If so, is there an option to treat this as a roundoff level difference and leave it as is?

**Comment by jqyin** [comment]
I can make the needed commit for the build fail. 
@rljacob @bishtgautam what are your thoughts about the DIFF for SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.anvil_intel.allactive-v1cmip6. It's only for one field and really small.

**Comment by rljacob** [comment]
Its your PR so you can declare those diffs to be acceptable and ask for them to be blessed.  But you should know why they happened.

**Comment by rljacob** [comment]
The diffs are between coupler history files output at the end of the runs.  "Ln9" is 9 timesteps.  "Ld2" is 2 days".

**Comment by thorntonpe** [comment]
Regarding the DIFFS: every other time I have seen DIFFS in FSDS they propagate quickly to many other energy variables. The fact that this impacts only FSDS suggests that somehow the DIFF is not propagating. I'd be glad to explore further, but it seems like the simulation is progressing BFB in subsequent time steps.

**Comment by thorntonpe** [comment]
@rljacob just saw your message about time steps. Is there information in the DIFF output that indicates on which timestep the reported DIFF occurs?

**Comment by rljacob** [comment]
I'm going by the name of the files that were compared which is in the teststatus output on cdash.  You can also download a tar file of all the log files by clicking on the gold box next to the test name.

Questions to ask yourself:  why these cases and not other F or coupled cases?

**Comment by thorntonpe** [comment]
Based on what we know now, I think these DIFFS are acceptable, and would like to have them blessed. I would like to understand why they occur, and can set this as a new task to dig into these compsets and provide an answer. There is something special about how these compsets are working compared to all the other tests, and I'd work with the people most knowledgeable about these tests to sort it out. I would not ask to bless and proceed, even for small DIFFS, if this was propagating to the 30+ other coupler history variables that are typically impacted when a DIFF appears in FSDS.

**Comment by rljacob** [comment]
Ok.  @jqyin add your commit for the build fix, re-merge to next and wait for another round of testing.

**Comment by jqyin** [comment]
@thorntonpe the build and runtime fails are now clear, but SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.sandiatoss3_intel.allactive-v1cmip6 and SMS_D_Ln5.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.cam-cosplite_nhtfrq5 show large DIFFs on 18 fields, e.g.,

 CLMMODIS   (ncol,time)  t_index =      1     1
       8094    48602  (   615,     1) (     3,     1) ( 41423,     1) (    41,     1)
               46865   1.000000000000000E+02   0.000000000000000E+00 1.0E+02  1.000000000000000E+02 9.2E-02  0.000000000000000E+00
               46865   1.000000000000000E+02   0.000000000000000E+00          0.000000000000000E+00          2.000000000000000E+01
               48602  (   607,     1) (     3,     1)
          avg abs field values:    1.283964347839355E+01    rms diff: 7.8E+00   avg rel diff(npos):  9.2E-02
                                   1.321272659301758E+01                        avg decimal digits(ndif):  0.4 worst:  0.0
 RMS CLMMODIS                         7.7778E+00            NORMALIZED  5.9709E-01

 CLMODIS   (ncol,cosp_tau_modis,cosp_prs,time)  t_index =      1     1
      98756  2041284  ( 43674,     1,     1,     1) (     1,     1,     1,     1) ( 45013,     2,     1,     1) (   142,     1,     1,     1)
             1968330   1.000000000000000E+02          0.000000000000000E+00 1.0E+02  1.000000000000000E+02 4.2E-02  1.600000000000000E+01
             1968330   1.000000000000000E+02          0.000000000000000E+00          0.000000000000000E+00          0.000000000000000E+00
             2041284  ( 43674,     1,     1,     1) (     1,     1,     1,     1)
          avg abs field values:    1.200910091400146E+00    rms diff: 4.7E+00   avg rel diff(npos):  4.2E-02
                                   1.215296745300293E+00                        avg decimal digits(ndif):  0.1 worst:  0.0
 RMS CLMODIS                          4.6744E+00            NORMALIZED  3.8692E+00

more details on https://my.cdash.org/viewTest.php?onlyfailed&buildid=1620355

**Comment by rljacob** [comment]
So after fixing the build error you now have more diffs then before?

**Comment by rljacob** [comment]
The large diffs are in COSP (satellite simulator) fields so they are diagnostic and don't change answers.  Why would a land model change do that?

The FSDS diff is only in runs with the gnu compiler.

Only runs that have cam output show any diffs.  Most tests only compare coupler history with baselines.  No diffs there.

**Comment by thorntonpe** [comment]
@rljacob , yes, I am also confused by this. I'm looking at the list of diffs, all are *MODIS fields - I don't know anything about how those are generated, and I'm not sure what the connection - if any - to the land model is. Who is the expert on these *MODIS fields? Is it possible these diffs are coming from another merged PR?

**Comment by brhillman** [comment]
There was a bug fix for the MODIS simulator that was recently merged, and then reverted. Possible that the baseline and test case have inconsistent versions of this code change?

**Comment by rljacob** [comment]
I don't see anything in the recent history of next involving MODIS.

**Comment by thorntonpe** [comment]
One way or another, that seems a very likely culprit, given the diffs. I don't know enough about how the baselines are generated for testing on next to be able to track this down.

**Comment by rljacob** [comment]
Ok if you go back a week PR #2770 caused MODIS changes and has been sitting on next since then.  That's the reason.

**Comment by thorntonpe** [comment]
So is there anything that I need to do for integration of this PR?

**Comment by jqyin** [comment]
@rljacob I agree. The same DIFFs on prod_next starts on Mar. 7 https://my.cdash.org/index.php?project=ACME_Climate&date=2019-03-07.  Looks like it's due to PR #2770.  After the fix for debug mode F cases, it shows up now on integration next.

**Comment by jqyin** [comment]
Merged #2742

**Pull request merged**
