### PR TITLE
Add term to cpl budget for irrigation passed between lnd and rof

### PR DESCRIPTION
**Pull request by jonbob**
Adds a new line to the coupler water budget to track the water exchange between lnd and rof due to irrigation, which corresponds to the field Flrr_supply. This supports new water features added to ELM and already tracked in its internal budget.

[BFB]

### CODE REVIEW

**Review by hydrotian — APPROVED** [review]

**Comment by jonbob** [comment]
@hydrotian - can I ask you to check this one more time? I made a couple of other changes to make it more efficient, since this field is always available in the cpl for E3SM

**Comment by jonbob** [comment]
@hydrotian - I did verify that it gets reasonable budget numbers after the change for a run with irrigation on, as well as works when irrigation is off

**Comment by hydrotian** [comment]
@jonbob I have no problem with these changes.

**Review by hydrotian — APPROVED** [review]

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
