### PR TITLE
Fixes inline interpolation of land initial condition

### LINKED ISSUE #3276: Land in-line initial condition interpolation fails with tri-grid (ne30_r05_oECv3)
I'm trying out the new tri-grid functionality (48e617270e311a53a6f6bb26e05e9011893aeaac) with compset **F20TRC5-CMIP6** and resolution  **ne30_r05_oECv3**.

The model runs with land cold start; but when I try to use in-line interpolation for land initial conditions (finidat_interp), the model fails during land initialization:

```
100: e3sm.exe           00000000029D9E3D  pio_spmd_utils_mp         294  pio_spmd_utils.F90.in
100: e3sm.exe           00000000029C0048  box_rearrange_mp_         302  box_rearrange.F90.in
100: e3sm.exe           00000000029645F9  rearrange_mp_rear          80  rearrange.F90.in
100: e3sm.exe           000000000297E127  piodarray_mp_writ         583  piodarray.F90.in
100: e3sm.exe           0000000002982B00  piodarray_mp_writ         221  piodarray.F90.in
100: e3sm.exe           000000000241BFB5  ncdio_pio_mp_ncd_        1595  ncdio_pio.F90.in
100: e3sm.exe           0000000001B99812  initinterpmod_mp_         993  initInterp.F90
100: e3sm.exe           0000000001ABDAB8  clm_initializemod         771  clm_initializeMod.F90
100: e3sm.exe           0000000001AA8118  lnd_comp_mct_mp_l         281  lnd_comp_mct.F90
100: e3sm.exe           000000000043C5D4  component_mod_mp_         257  component_mod.F90
100: e3sm.exe           000000000042ACC4  cime_comp_mod_mp_        1343  cime_comp_mod.F90
100: e3sm.exe           0000000000439519  MAIN__                    122  cime_driver.F90
```

The last line in the land log file is:

` Interpolating: FSD24_VALUE`

so the model might be failing when interpolating `FSD24_VALUE`

For in-line interpolation, my settings were

```
finidat = ' '
finidat_interp_source = '/compyfs/zhan524/restart/20180316.DECKv1b_A1.ne30_oEC.edison.1980-01-01/20180316.DECKv1b_A1.ne30_oEC.edison.clm2.r.1980-01-01-00000_DECKv1.nc' 
finidat_interp_dest = 'finidat_interp_20180316.DECKv1b_A1.ne30_oEC.edison.1980-01-01.clm2.r.1980-01-01-00000.nc'
```
Hoping that @bishtgautam can help with this.

### PR DESCRIPTION
**Pull request by bishtgautam**
Corrects the array to be used to determine if the value is
NaN for output netcdf file.

Fixes #3276
[BFB]

### CODE REVIEW

**Comment by golaz** [comment]
Can we get this merged to master? I'd like to start a new simulation and I would prefer not to use a branch. Thanks.

**Comment by rljacob** [comment]
@bishtgautam you could merge this to next today.

**Comment by bishtgautam** [comment]
@rljacob, @golaz This PR is on next now.
@wadeburgess, This PR will attempt to pull a new file from E3SM inputdata server (`$DIN_LOC_ROOT/lnd/clm2/initdata_map/20180316.DECKv1b_A1.ne30_oEC.edison.clm2.r.1980-01-01-00000_DECKv1.nc'`). Will there be an issue pulling the new dataset on nightly test machines? Could you download the file by hand on Melvin and Sandiatoss3 to ensure we don't loose a testing because of missing inputdata? thanks.

**Comment by dqwu** [comment]
@bishtgautam 
The two new regression tests failed on melvin as expected due to missing input files:
https://my.cdash.org/viewTest.php?onlyfailed&buildid=1724840

```
Could not connect to svn repo 'https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata'
This is most likely either a credential, proxy, or network issue .
To check connection and store your credential run 'svn ls https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata' and permanently store your password
...
ERROR BFAIL baseline directory '/sems-data-store/ACME/baselines/gnu/master/SMS_Ld1.r05_r05.I1850CLM45.melvin_gnu.clm-inlineInterpolation' does not exist
```

**Comment by bishtgautam** [comment]
@dqwu The error msg at the end is not accurate as I do also see the following msg
```
Loading input file list: 'Buildconf/clm.input_data_list'
Trying to download file: 'lnd/clm2/initdata_map/20180316.DECKv1b_A1.ne30_oEC.edison.clm2.r.1980-01-01-00000_DECKv1.nc' to path '/sems-data-store/ACME/inputdata/lnd/clm2/initdata_map/20180316.DECKv1b_A1.ne30_oEC.edison.clm2.r.1980-01-01-00000_DECKv1.nc' using WGET protocol.
SUCCESS
```
I download the tar.gz files of the two tests and they both ran to completion. These tests are missing baselines, which is expected as they are new tests.

**Comment by amametjanov** [comment]
There are errors on sandiatoss3 and bebop: e.g. `SMS_Ld1.f09_f09.I1850CLM45.bebop_intel.clm-inlineInterpolation`
```
[253]  ERROR interpinic set_mindist: Cannot find the closest output ni,no,type= 
[253]        16369       20731 gridcell        
[253]  ENDRUN:
[253]  ERROR in initInterp.F90 at line 815                                            
[253]                                                                                 
[253]                                                                                 
[253]                                                                                 
[253]                                                                                 
[253]                                                                                 
[253]                                        
[253]  ERROR: Unknown error submitted to shr_abort_abort.
[253] Image              PC                Routine            Line        Source             
[253] e3sm.exe           0000000001537B6D  Unknown               Unknown  Unknown
[253] e3sm.exe           0000000001087A12  shr_abort_mod_mp_         114  shr_abort_mod.F90
[253] e3sm.exe           0000000000507A77  abortutils_mp_end          43  abortutils.F90
[253] e3sm.exe           00000000005E315B  initinterpmod_mp_         815  initInterp.F90
[253] e3sm.exe           00000000005E5B09  initinterpmod_mp_         253  initInterp.F90
[253] e3sm.exe           0000000000514C78  clm_initializemod         771  clm_initializeMod.F90
[253] e3sm.exe           0000000000501FB3  lnd_comp_mct_mp_l         281  lnd_comp_mct.F90
[253] e3sm.exe           0000000000436858  component_mod_mp_         257  component_mod.F90
[253] e3sm.exe           000000000042593A  cime_comp_mod_mp_        1343  cime_comp_mod.F90
[253] e3sm.exe           0000000000433909  MAIN__                    122  cime_driver.F90
[253] e3sm.exe           000000000041455E  Unknown               Unknown  Unknown
[253] libc-2.17.so       00002B6C9CB91495  __libc_start_main     Unknown  Unknown
[253] e3sm.exe           0000000000414469  Unknown               Unknown  Unknown
[253] application called MPI_Abort(MPI_COMM_WORLD, 1001) - process 253

```

**Comment by bishtgautam** [comment]
I'm going to remove the tests from this PR, so I can get this PR integrated in master as quickly as possible for @golaz. I will later work on figuring out why the interpolation test is failing on sandiatoss3 and bebop.

**Comment by golaz** [comment]
Thanks, @bishtgautam. I'm starting a new simulation to try this out.

**Pull request merged**
