### PR TITLE
Cray compilers: Remove obsolete flags

### PR DESCRIPTION
**Pull request by sarats**
`-h byteswapio` is a remnant from old Cray configs. Need to test impact and remove. `-N 255` needs to be removed for free-format files using Cray GPU configurations.

### CODE REVIEW

**Comment by sarats** [comment]
This file `cime_config/machines/cmake_macros/cray.cmake` is not used by Frontier/Crusher. However, this fix is applied for consistency. 

The ORNL AF machine (miller), Theta, Spock (gone) use it.

**Review by amametjanov — APPROVED** [review]

**Comment by sarats** [comment]
Running `e3sm_developer` on Frontier - 64/68 tests pass (others likely known fails before).

    FAIL ERS.f19_g16.I1850ELM.frontier_crayclang.elm-betr RUN time=42
    FAIL ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.frontier_crayclang.mosart-rof_ocn_2way RUN time=2722
    FAIL PEM_Ln5.T62_oQU240wLI.DTESTM.frontier_crayclang RUN time=79
    _PEND PEM_Ln5.T62_oQU240wLI.DTESTM.frontier_crayclang COMPARE_base_modpes_
    FAIL SMS_P12x2.ne4_oQU240.WCYCL1850NS.frontier_crayclang.allactive-mach_mods RUN time=35

**Review by grnydawn — APPROVED** [review]
The failures are caused from the known issues. I think that it is safe to be merged to next/master.

**Comment by sarats** [comment]
We can merge this to master, right?

**Comment by rljacob** [comment]
yes.

**Pull request merged**
