### PR TITLE
update mach config for Livermore Computing (maint-1.0)

### PR DESCRIPTION
**Pull request by jsbamboo**
- copy the mach config from scream repo 
- add ruby machine
- delete syrah machine

a A_WCYCLSSP585_CMIP6 compset run (same configurations as DECKv1b_P1_SSP5-8.5 production run) passed build

### CODE REVIEW

**Comment by jasonb5** [comment]
@jsbamboo I'm getting this build error on quartz when running `./scripts/create_test SMS.f19_g16.S`. The only module I had to load was python.

```
ld: ../../intel/mpich/nodebug/nothreads/lib/libpioc.a(spio_io_summary.cpp.o): undefined reference to symbol '_ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE@@GLIBCXX_3.4.21'
ld: /lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
```

**Comment by jasonb5** [comment]
@jsbamboo I had to add the following to `config_compilers.xml` under quartz and ruby.
```xml
<CXX_LIBS>-lstdc++ </CXX_LIBS>
```
I also added the following under `modules` sections of `config_machines.xml` for quartz and ruby. This is required if there's missing input data and it needs to be pulled from an svn repo.
```xml
<command name="load">subversion</command>
```
Could you verify these fix the issue and then update the PR. Thanks!

**Comment by jsbamboo** [comment]
Thank you Jason! With the added lines create_test also works now

**Comment by rljacob** [comment]
@jasonb5 please merge this.

**Pull request merged**
