### PR TITLE
EAM: ne0np4_northamericax4v1.pg2_r0125_ne0np4_northamericax4v1.pg2 config

### PR DESCRIPTION
**Pull request by ambrad**
This is the theta-SL-pg2 configuration for resolution
    ne0np4_northamericax4v1.pg2_r0125_ne0np4_northamericax4v1.pg2
with ocean mask oRRS15to5. It includes configurations for:
  * topography file
  * atmsrf file
  * map and domain files
  * theta-l defaults for this RRM grid.

[BFB]

### CODE REVIEW

**Comment by ambrad** [comment]
Input data are on the master inputdata server; @tangq's run on Cori confirms all the input data are fine.

**Comment by ambrad** [comment]
I'm running e3sm_developer on sandiatoss3 now and will update this comment when done.

**Comment by ambrad** [comment]
@tangq when you have a chance, would you look this over and approve it? It's the commit you've been using for the theta-SL-pg2 RRM runs. Thanks.

**Comment by tangq** [comment]
Looks good. It is ready to be merged.

**Comment by wlin7** [comment]
Merged to next.

**Comment by rljacob** [comment]
please merge this to master.

**Comment by wlin7** [comment]
Thanks for the reminder @rljacob . Merged.

**Pull request merged**
