### PR TITLE
Update mpas source framework for inc files

### PR DESCRIPTION
**Pull request by mark-petersen**
This is a minor MPAS framework update. It does not alter E3SM execution. It creates two new autogenerated config files on compile so that, in the future, each core may create a `core_config` module and include all the config flags at once, rather than declare each variable individually.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
Passed:
```
./create_test -p acme -q debug --walltime 00:30:00 \
  PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_intel
```
Also test compiled stand-alone MPAS with all cores, with gnu and intel on LANL IC.

**Comment by mark-petersen** [comment]
@jonbob this is ready to merge when the repo is open.

**Comment by jonbob** [comment]
Merged to  next

**Comment by jonbob** [comment]
Merged to master

**Pull request merged**
