### PR TITLE
Fixing restart for theta-l, round 2

### PR DESCRIPTION
**Pull request by oksanaguba**
Fixes 1 memory bug and 1 unnecessary EOS check up that were preventing restart runs for theta H and NH. Should be BFB because we don't have restart tests yet.

### CODE REVIEW

**Comment by oksanaguba** [comment]
This commit works ok for 2-day run vs 1+1 day run for H, usiing same scripts as in prev. restart PRs.

**Comment by oksanaguba** [comment]
...and NH runs are identical, too, for cpl file. NH used nsplit=20. it is still not clear why pnh_i check wasn't triggered in initialization of H run. The check is in pnh_and_exner_from_eos, that is called from get_temperature that is called from d_p_coupling which is called from stepon_run1 .

**Comment by mt5555** [comment]
can you resolve this question in the code:  "!what does pio decomp do? do i need ifdef, if here?"

**Comment by oksanaguba** [comment]
about values of phi_i: phi_from_eos sets phi, it is called from tests_finalize, which is called in set_thermostate, which is called in inindat, but not in restart.

**Comment by oksanaguba** [comment]
Removed that comment about pio decomp.

**Comment by mt5555** [comment]
Regarding you comment about phi_i:  that's the correct behavior?   in the NH model, phi_i will be read form the restart.  But in H mode, phi (and phi_i) are not prognostic variables and thus do not have to be set during the initial condition or during restart.

**Comment by oksanaguba** [comment]
This commit was ok for both H and NH running 2 days and 1+1 day runs, comparing cam.r and cpl.r files (identical).

**Comment by oksanaguba** [comment]
Does this need a review to be integrated?

**Comment by jgfouca** [comment]
@oksanaguba , that's up to you and Mark.

**Comment by oksanaguba** [comment]
@jgfouca  Mark approved it, so, it can be merged, thanks!

**Comment by jgfouca** [comment]
Merged to next.

**Pull request merged**
