### PR TITLE
Add performance data collection support for chrysalis

### LINKED ISSUE #4009: slurm job script output not treated correctly in performance archiving
In provenance.py, the job script output is treated differently on the different SLURM systems (anvil, compy, and the cori systems):

        elif mach == "anvil":
            globs_to_copy.append("%s*run*%s" % (case.get_value("CASE"), job_id))
        elif mach == "compy":
            globs_to_copy.append("slurm.err")
            globs_to_copy.append("slurm.out")
     ...
        elif mach in ["cori-haswell", "cori-knl"]:
            globs_to_copy.append("%s*run*%s" % (case.get_value("CASE"), job_id))

and none of these are correct (though they were at the time each system was first added or when moved to SLURM). They should instead be:

        if mach in ["anvil", "compy", "cori-haswell", "cori-knl"]:
            globs_to_copy.append("run*%s*%s" % (case.get_value("CASE"), job_id))

With the addition of chrysalis, the logic should be

        if mach in ["anvil", "chrysalis", "compy", "cori-haswell", "cori-knl"]:
            globs_to_copy.append("run*%s*%s" % (case.get_value("CASE"), job_id))

### PR DESCRIPTION
**Pull request by worleyph**
a) Add support for chrysalis to provenance.py

Created a new CIME branch (worleyph/chrysalis_support)
with a modified provenance.py that adds the chrysalis
system to the list of supported systems.

The CIME branch also (a) removes support for mira and
titan systems, and (b) fixes archiving of batch job
output files for slurm systems anvil, compy, cori-haswell,
and cori-knl.

After merging, CIME will point to this branch, moving the hash from
    5cef5558 to 5ffbaf480e

b) Add job monitoring script for chrysalis

Added syslog.chrysalis, to provide job progress monitoring
and checkpointing for the chrysalis system.

Fixes #4009 

[BFB]

### CODE REVIEW

**Comment by worleyph** [comment]
This PR involves changes to one file (provenance.py in CIME) and the addition of one file (syslog.chrysalis). I pushed a branch to CIME with the provenance.py changes, but have not submitted a CIME PR. This E3SM branch points at this CIME branch.

Please tell me if I need to do anything else. I prefer that someone else submit the CIME PR (using branch worleyph/chrysalis_support), and I do not know how this PR would then be modified to point at CIME master (after the merge) instead of at the CIME branch it currently points at.

I tested using an F case on chrysalis and anvil and compy. I can't run on cori-knl and cori-haswell at the moment - allocation has run out?

**Comment by worleyph** [comment]
Note that there is some urgency associated with this PR, so that full performance data collection will be enabled on chrysalis as soon as possible.

**Comment by worleyph** [comment]
Was able to run tests on cori-knl and cori-haswell using the "overrun" queue, and the everything worked as expected.

**Review by amametjanov — APPROVED** [review]

**Comment by sarats** [comment]
@rljacob Would be nice to get this in soon.

**Comment by sarats** [comment]
@rljacob Changes look good. Nice to get this in soon.

**Comment by rljacob** [comment]
Merged to next and was able to build/run an A case.

**Review by rljacob — APPROVED** [review]

**Pull request merged**
