### PR TITLE
update mpas-source: Add Wright (1997) equation of state

### PR DESCRIPTION
**Pull request by mark-petersen**
See https://github.com/MPAS-Dev/MPAS-Model/pull/313

Adds Wright (1997) equation of state as optional, not default.

[NML]
[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
@jonbob This adds one namelist and one flag:
```
<nml_record name="eos_wright">
		<nml_option name="config_eos_wright_ref_pressure"
```
@xylar I assume E3SM should use the same default of zero for this flag?

**Comment by mark-petersen** [comment]
Passes
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
PEM_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-haswell_gnu
```
with default JM eos and default on `config_eos_wright_ref_pressure=0`

**Comment by jonbob** [comment]
I ran the automated script to update the mpas-o bld files based on the changes to Registry and committed the updates. I'm doing some sanity testing on the resulting codebase, but looks good.

**Review by jonbob — APPROVED** [review]
Looks good from a visual inspection and sanity testing

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master and expected NML DIFFs blessed

**Pull request merged**
