### PR TITLE
Update mpas-source: Add ocn_config module

### PR DESCRIPTION
**Pull request by mark-petersen**
Add a new module ocn_config that has public declarations of all config flag variables. This allows us to greatly simplify the code, as we can simply `use ocn_config` and not declare and get config flags in every subroutine. This PR includes the changes to `mpas_ocn_tracer_hmix_del2.F` as an example.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
See https://github.com/MPAS-Dev/MPAS-Model/pull/409 and https://github.com/MPAS-Dev/MPAS-Model/pull/410 for more details.

**Comment by mark-petersen** [comment]
@jonbob I added the new module to the ocean.cmake file, so this should take care of the last problem.

**Comment by mark-petersen** [comment]
@jonbob this is ready to merge to `next`, and is a prerequisite to #3391.

**Comment by jonbob** [comment]
Test merge passed:
SMS.T62_oEC60to30v3wLI.GMPAS-IAF.anvil_intel

Merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
