### PR TITLE
update mpas-source: Fix core_ocean submodule checks in cmake

### PR DESCRIPTION
**Pull request by mark-petersen**
See https://github.com/MPAS-Dev/MPAS-Model/pull/808

From @jgfouca:
Need FATAL_ERROR instead of FATAL. Fix paths to submodules. I recently built an E3SM compset with MPAS components and I was checking some CMake stuff, so I ran the CMake command by hand and the output surprised me. CMake claimed "FATAL Missing core_ocean submodule ..." but still returned a 0 return code. Also, I confirmed that my submodules were initialized. A little digging and I found that both the existence checks and the corresponding error messages were broken. This PR fixes them.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
Currently includes code changes in #4077. Will rebase tomorrow.

**Comment by mark-petersen** [comment]
This is ready. @jgfouca please review, these are the changes you made in MPAS-Dev/MPAS-Model#808.

**Review by jgfouca — APPROVED** [review]

**Comment by jgfouca** [comment]
Thx @mark-petersen !

**Review by jonbob — APPROVED** [review]
Looks good from a visual inspection -- and @jgfouca's approval, since he is our resident cmake expert

**Comment by jonbob** [comment]
merged to next

**Pull request merged**
