### PR TITLE
Reverts ELM's topounit code changes

### LINKED ISSUE #5700: Rerunning E3SMv2 with maint-2.0 fails on chrysalis
I'm trying to rerun a portion of one the E3SMv2 simulation from the v2 simulation campaign to save additional output using current version of maint-2.0 on chrysalis (same machine as used originally).

Unfortunately, the model fails while initializing the land component. In particular, it fails during a check of PFT weights. Here is the error

 ```
Reading restart file v2.LR.amip_0101.elm.r.2000-01-01-00000.nc
 Reading restart dataset
 Opened existing file v2.LR.amip_0101.elm.r.2000-01-01-00000.nc         100
 ncd_inqvid: variable pfts1d_wttopounit is not on dataset
 check_weights ERROR: at t =           32 total PFT weight is 
  0.999999999992837      active_only =  T
 ENDRUN:
 ERROR in subgridWeightsMod.F90 at line 779
```
Files on chrysalis

/lcrc/group/e3sm/ac.golaz/E3SM/E3SMv2/v2.LR.amip_0101/tests/XS_1x10_ndays/run

Have there been changes to the ELM code that would cause this? Is there a new consistency check that needs to be disabled that was not present before?

### PR DESCRIPTION
**Pull request by bishtgautam**
This reverts commit 07ff719012d7f4fa3a958d3e5e4d487a4effdda2, reversing changes made to 7ce11b09c867f0bffafafb2af97dcfa148906331.

Conflicts:
	cime_config/tests.py
	components/elm/bld/namelist_files/namelist_defaults.xml
	components/elm/src/biogeochem/CH4Mod.F90
	components/elm/src/biogeophys/BalanceCheckMod.F90
	components/elm/src/biogeophys/CanopyHydrologyMod.F90
	components/elm/src/cpl/lnd_import_export.F90
	components/elm/src/dyn_subgrid/do_genf90
	components/elm/src/dyn_subgrid/dynHarvestMod.F90
	components/elm/src/dyn_subgrid/dynVarTimeUninterpMod.F90.in
	components/elm/src/main/elm_varctl.F90

Fixes #5700 
[BFB]

### CODE REVIEW

**Comment by bishtgautam** [comment]
@golaz, in discussion with @rljacob, I have reverted the ELM's topounit code to fix `maint-2.0`. Using your script [run.v2.LR.amip_0101_rerun-20230519-maint20.sh.txt](https://github.com/E3SM-Project/E3SM/files/11604202/run.v2.LR.amip_0101_rerun-20230519-maint20.sh.txt), ELM can successfully initialize, though the model crashes during the second initialization phase of EAM now. Could you please try out this branch?

**Comment by bishtgautam** [comment]
@shipf16 , @erinethomas , Can you check if this PR fixes the error you reported on #5728?

**Comment by bishtgautam** [comment]
@tangq I want to check if this PR is compatible with the ELM restart files that were generated with v2.0.1 or v2.0.2. Do you have a run script (similar to [run.v2.LR.amip_0101_rerun-20230519-maint20.sh.txt](https://github.com/E3SM-Project/E3SM/files/11604202/run.v2.LR.amip_0101_rerun-20230519-maint20.sh.txt)) that uses ELM restart files generated with v2.0.1 or v2.0.2 tag? Thanks.

**Comment by tangq** [comment]
@bishtgautam , this is one of the latest runs I used the v2 restart files to run new simulations. I used the maint-2.0 tag (not sure if it's close enough for v2.0.1/v2.0.2). The details, including the run script, can be found on this page:

https://acme-climate.atlassian.net/wiki/spaces/EWCG/pages/3436576769/v2.LR.amip+bonus

**Comment by rljacob** [comment]
"maint-2.0" is a branch, not a tag.  The run you pointed to above uses code after the 2.0.1 tag.

**Comment by bishtgautam** [comment]
@golaz This branch can successfully complete the simulation using your script ([run.v2.LR.amip_0101_rerun-20230519-maint20.sh.txt](https://github.com/E3SM-Project/E3SM/files/11604202/run.v2.LR.amip_0101_rerun-20230519-maint20.sh.txt)).

**Comment by erinethomas** [comment]
testing this branch with both PI control and historical runs on Perlmutter now....

**Comment by shipf16** [comment]
This morning I install `maint-2.0` on Perlmutter and conduct the branch run from the restart file using E3SM v2.0. However, I am sorry to find that this error still exists and I couldn't do the branch run with the previous restart files `(/home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101)`.  At your convenience, could you please offer further insight into how this issue may be resolved?

Please accept my apologies for any inconvenience caused and thank you very much! I would greatly appreciate any guidance or advice you could provide to help me resolve this problem.


e3sm_log

**Comment by bishtgautam** [comment]
@shipf16 The `maint-2.0` has been fixed yet and you need to instead use my branch `bishtgautam/lnd/fix-maint-2.0`

**Comment by shipf16** [comment]
Thank you very much for your great help! Your branch `bishtgautam/lnd/fix-maint-2.0` can fix this error due to the land restart. Now I could smoothly run the E3SMv2.0 using the previous restart files with your branch `bishtgautam/lnd/fix-maint-2.0`. Please accept my deepest thanks for your great help!

**Review by golaz — APPROVED** [review]
@bishtgautam : I have tested the modified code using both original v2 restart files and v2 restart files form a later rerun. Both tests ran successfully and produced results that were BFB with the original simulation.

**Comment by erinethomas** [comment]
confirming this branch successfully works for both my tests: a PI control and a historical run on Perlmutter.

**Review by rljacob — APPROVED** [review]

**Comment by erinethomas** [comment]
Hoping this gets merged into 'maint 2.0' soon. I would like to start my production runs soon using the official 2.0 branch.

**Comment by rljacob** [comment]
@bishtgautam what are you waiting for?

**Comment by bishtgautam** [comment]
Apologies as I missed the fact that I was assigned to merge this PR. I will do it now.

@rljacob Do we need a similar PR for maint-2.1?

**Comment by rljacob** [comment]
For 2.1, is this PR the only thing needed for 2.1 to read 2.0.0 restarts?  And will it still be able to read 2.1.0 restarts?

**Pull request merged**
