### PR TITLE
Update kokkos submodule to latest upstream master

### PR DESCRIPTION
**Pull request by amametjanov**
Add previous E3SM changes on top of upstream master from 2021-May-25.

[BFB]

### CODE REVIEW

**Comment by amametjanov** [comment]
Kokkos update is needed to build with latest Intel OneAPI compilers (icx / icpx / ifx) on JLSE testbed nodes.
The update does not exhibit any regressions based on e3sm_developer tests with oneapi-ifx compiler on skylake nodes.

**Comment by jgfouca** [comment]
@bartgol , if you approve, I will merge to next.

**Review by bartgol — APPROVED** [review]
Looks good.

**Comment by jgfouca** [comment]
I did a second merge to next which should clear most of the problems we saw last night.

**Comment by dqwu** [comment]
@jgfouca Could you please re-merge this PR to next? I just pushed a new commit for mpi-serial on anlworkstation.

**Comment by jgfouca** [comment]
@dqwu , sure

**Comment by rljacob** [comment]
This is still causing build fails everywhere.

**Comment by dqwu** [comment]
> This is still causing build fails everywhere.

On compy, anvil and cori-knl (not on mappy).

**Comment by jgfouca** [comment]
Looks like there are remaining kokkos build problems on compy, sandiatoss3, and anvil. I can take care of compy and sandiatoss3.

**Comment by rljacob** [comment]
@jgfouca merge this to master and bless the diffs on compy_pgi.

**Comment by jgfouca** [comment]
@rljacob , will do.

**Pull request merged**
