### PR TITLE
Move E3SM config files out of cime directory

### PR DESCRIPTION
**Pull request by rljacob**
Move all the e3sm config files from cime/config/e3sm to E3SM/cime_config.

This is preparation for converting cime to a submodule.

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
I did a run on compy called WcycTR2 on this branch.  @worleyph or @sarats can you check that all the profiling happened?   The Depends and template files are all found correctly.  Not sure about syslog.

**Comment by worleyph** [comment]
@rljacob , it looks good to me.

**Comment by worleyph** [comment]
Or maybe not - I need to try this myself I guess. There were some checkpoints, but only for the very beginning. I'll try running a longer job, and make sure that syslog would collect more information that we can check for.

**Comment by worleyph** [comment]
syslog worked fine for me (same case on Compy, but capturing checkpoints every 30 seconds).

**Comment by jgfouca** [comment]
Merged to next.

**Pull request merged**
