### PR TITLE
Add capability to read CO2 flux for all grids and grid resolutions

### PR DESCRIPTION
**Pull request by singhbalwinder**
This PR adds code to read CO2 flux (fuel and ocean) for all grids and grid resolutions. To activate the new code,  append "-cppdefs -DCO2_BILIN_REGRID" string to the "CAM_CONFIG_OPTS" variable in env_build.xml (the original code is still the default). The original code was not able to interpolate read-in lat-lon grid data on to an SE grid. New code has been added so that lat-lon data can be interpolated (bilinear interpolation) on any kind of grid. The new codes use the existing tracer_data.F90 routines (where netcdf files are read and interpolated) to be consistent with rest of the code.

tracer_data.F90 is modified so that state and pbuf2d variables are now optional. The primary reason to make this change was to accommodate CO2 flux interpolation where interpolation routines (e.g. co2_time_interp_fuel) are called from a  point in the code (atm_import_export.F90) where state and pbuf2d are not readily accessible	

[BFB]

### CODE REVIEW

**Comment by maltrud** [comment]
@singhbalwinder and @susburrows  do you know if the interpolation is bilinear or conservative?  i don't know anything about how CAM does interpolation, but i know that other flux fields must get interpolated at some point (like DMS), but has it ever really mattered if data fluxes are interpolated conservatively?

**Comment by susburrows** [comment]
@singhbalwinder thanks for adding the changes we discussed so that the new code (which we determined uses nonconservative bilinear regridding) can only be turned on by using a cpp directive.  Is further testing needed on this PR, and is the code ready for review?  Thanks!

**Comment by singhbalwinder** [comment]
Yes, the code is ready for a re-review. I have runs the model in both ways (with the  new CPP directive and without) and it produces the desired results. The code run using SE grids without the CPP directive crashes as expected due to the lack of the interpolating routines.

**Comment by susburrows** [comment]
Thanks Balwinder!  This will probably have to wait until after the project review as that is taking up a lot of time and attention at the moment.

**Comment by singhbalwinder** [comment]
@susburrows : Would you please look at my latest changes once more to see if everything is in place? Please let me know if it is missing something or if you want me to run more tests.

**Comment by susburrows** [comment]
I won't have time to look at this before next week, so @jonbob and @maltrud have agreed to help out.  They are going to run a quick test to cross-verify that the results of the regridding look as expected when the CPP directive is turned on.

**Comment by jonbob** [comment]
This PR passed the following test:
* SMS.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_20TR.anvil_intel
once we added these lines to user_nl_cam:
 ```
co2_readflux_fuel = .true.
co2flux_fuel_file = '/home/ccsm-data/inputdata/atm/cam/ggas/co2flux_fossil_1751-2006-monthly_0.9x1.25_c20100204.nc'
```
@maltrud looked at the results after a one-month run and verified that the fields are being read in and interpolated correctly

**Comment by singhbalwinder** [comment]
> @maltrud looked at the results after a one-month run and verified that the fields are being read in and interpolated correctly

Thanks @jonbob and @maltrud . I am assuming that you have compiled the code using `-DCO2_BILIN_REGRID` to check the interpolations. Is that right?

**Comment by jonbob** [comment]
@singhbalwinder - yes, you had that well commented

**Comment by singhbalwinder** [comment]
Great! Thanks! @susburrows : Would you please check to see if there are any remaining issues that still needs to be addressed? Otherwise, this PR is ready to be merged.

**Comment by maltrud** [comment]
@singhbalwinder , @susburrows , @jonbob : here is a comparison of the fossil fuel flux fields.  left is the input data for Jan 1850;  right is sfco2_fff from monthly cam.h0 file.  both are actually log(flux).
co2flux_fossilfuels1850

**Comment by susburrows** [comment]
Thanks, @maltrud and @jonbob .  I agree that this is ready to merge now.  It will be great to have this capability ready to turn on in the CBGC production simulations.

**Comment by wlin7** [comment]
merged to next.

**Comment by rljacob** [comment]
@wlin7 please merge this to master.

**Comment by wlin7** [comment]
@merged.  Thanks for the reminder, @rljacob . 
Somehow I didn't receive the regression status update since June 1.

**Comment by amametjanov** [comment]
I'm also not getting any integration status emails. It looks like emails from sandia.gov domain are filtered somewhere.

**Pull request merged**
