### PR TITLE
Update mpas-source: Allows for sea ice radiative transfer calculations

### PR DESCRIPTION
**Pull request by akturner**
Allows for sea ice radiative transfer calculations of aerosols and dust.

Merges https://github.com/MPAS-Dev/MPAS-Model/pull/818

[Non-BFB] for aerosol/BGC tests only

### CODE REVIEW

**Comment by njeffery** [comment]
@jonbob  and @akturner :  I don't have permission to access adrian's fork.

**Comment by jonbob** [comment]
@proteanplanet - can you see this fork OK?

**Comment by njeffery** [comment]
Thanks Jon. I can see it on github,  I just can't remote add the fork to my local copy.

________________________________
From: Jon Wolfe ***@***.***>
Sent: Monday, March 15, 2021 9:56:10 AM
To: E3SM-Project/E3SM
Cc: Jeffery, Nicole; Mention
Subject: [EXTERNAL] Re: [E3SM-Project/E3SM] Update mpas-source: Allows for sea ice radiative transfer calculations (#4154)


@akturner<https://github.com/akturner> - can you fix your fork so @njeffery<https://github.com/njeffery> can access it? Or is it a different problem?

**Review by njeffery — APPROVED** [review]
Based on a visual comparison, these code changes match the changes made in a test code base  that successfully completed two 38-year fully coupled runs with dust/BC aerosols active.

**Review by proteanplanet — APPROVED** [review]
Thank you for integrating this into E3SM so promptly.

**Comment by jonbob** [comment]
merged to next, passed sanity testing

**Comment by jonbob** [comment]
merged to master. @akturner, please feel free to delete that branch from your fork

**Pull request merged**
