### PR TITLE
Update the run_e3sm template to do the submodule command after checking out any branches

### PR DESCRIPTION
**Pull request by ndkeen**
Update the run_e3sm template to do the submodule command after checking out any branches.

Update the github location to refer to git@github.com:E3SM-Project/E3SM.git
Also remove reference to retired edison machine.
For the example "customknl" layout, switch to using the correct variable: MAX_MPITASKS_PER_NODE

[bfb]

### CODE REVIEW

**Comment by ndkeen** [comment]
After my changes, I tried the script as-is and I get the following error:

```
   Calling /global/cscratch1/sd/ndk/wacmy/ndk_run_e3sm_adjust-order-submodule-init/cime/src/build_scripts/buildlib.csm_share
Component csm_share build complete with 20 warnings
Traceback (most recent call last):
  File "/global/cscratch1/sd/ndk/E3SM_simulations/default.default.A_WCYCL1850_template.ne4_oQU240/case_scripts/case.build", line 165, in <module>
    _main_func(__doc__)
  File "/global/cscratch1/sd/ndk/E3SM_simulations/default.default.A_WCYCL1850_template.ne4_oQU240/case_scripts/case.build", line 160, in _main_func
    use_old=use_old, ninja=ninja, dry_run=dry_run)
  File "/global/cscratch1/sd/ndk/wacmy/ndk_run_e3sm_adjust-order-submodule-init/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 669, in case_build
    return run_and_log_case_status(functor, "case.build", caseroot=caseroot)
  File "/global/cscratch1/sd/ndk/wacmy/ndk_run_e3sm_adjust-order-submodule-init/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1720, in run_and_log_case_status
    rv = func()
  File "/global/cscratch1/sd/ndk/wacmy/ndk_run_e3sm_adjust-order-submodule-init/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 668, in <lambda>
    save_build_provenance, use_old, ninja, dry_run)
  File "/global/cscratch1/sd/ndk/wacmy/ndk_run_e3sm_adjust-order-submodule-init/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 632, in _case_build_impl
    save_build_provenance=save_build_provenance)
  File "/global/cscratch1/sd/ndk/wacmy/ndk_run_e3sm_adjust-order-submodule-init/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 653, in post_build
    save_build_provenance_sub(case, lid=lid)
  File "/global/cscratch1/sd/ndk/wacmy/ndk_run_e3sm_adjust-order-submodule-init/cime/scripts/Tools/../../scripts/lib/CIME/provenance.py", line 122, in save_build_provenance
    _save_build_provenance_e3sm(case, lid)
  File "/global/cscratch1/sd/ndk/wacmy/ndk_run_e3sm_adjust-order-submodule-init/cime/scripts/Tools/../../scripts/lib/CIME/provenance.py", line 79, in _save_build_provenance_e3sm
    os.symlink(the_match, generic_name)
OSError: [Errno 17] File exists
```

**Comment by cameronsmith1** [comment]
Given the issue https://github.com/E3SM-Project/E3SM/issues/3528 these changes appear to reasonable to me.

**Comment by rljacob** [comment]
@sarich ping.

**Comment by rljacob** [comment]
@sarich go ahead and start merging this.

**Pull request merged**
