### PR TITLE
Update mpas-source: fix landIceMask bug

### PR DESCRIPTION
**Pull request by mattdturner**
Fix bug in MPAS-O landIceMask computation in diagnostics.  

See MPAS PR https://github.com/MPAS-Dev/MPAS-Model/pull/672

Fixes https://github.com/E3SM-Project/E3SM/issues/3797 

[BFB]

### CODE REVIEW

**Comment by mattdturner** [comment]
Passes the following E3SM tests:
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
```

**Comment by xylar** [comment]
Before this gets merged, it would be important to run a test where the mask that is part of the initial condition is different from the one that the forward code would have been calculating.  This won't be the case for any tests on `oEC60to30v3wLI` but should be the case for any `ECwISC30to60` tests or anything else with `wISC` in the mesh name.

**Comment by xylar** [comment]
@jonbob or @darincomeau, could one of you run whatever tests you used to confirm that cherry-picking my fix worked? I think that should be sufficient.

**Comment by jonbob** [comment]
@xylar - I'll test merge the ECwISC30to60 commits with this PR and make sure it still works, as part of the testing

**Comment by darincomeau** [comment]
I've got a `A_WCYCL1850-DIB-ISMF_CMIP6.ne30_ECwISC30to60E1r2` case built with this, currently waiting in the queue.

**Comment by jonbob** [comment]
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_intel worked for me

**Comment by jonbob** [comment]
Also passes SMS.ne11_oQU240.A_WCYCL1850.anvil_intel sanity test

**Comment by darincomeau** [comment]
> I've got a `A_WCYCL1850-DIB-ISMF_CMIP6.ne30_ECwISC30to60E1r2` case built with this, currently waiting in the queue.

Still in the queue, and given current Anvil usage, will probably be there a few more hours.

**Comment by jonbob** [comment]
@darincomeau - can you test with a G-case so we can get this PR reviewed and merged? @xylar - if you're still up can you please add a review?

**Comment by darincomeau** [comment]
@jonbob there are only 8 nodes free on Anvil right now (and for the next few hours it would seem), so I won't be able to get a G-case through either. I'm inclined to just approve, since I've already tested the MPAS PR in E3SM with the ECwISC30to60E1r2 grid.

I'm building a case now on Cori and using the debug queue - should have it done in 30 minutes or so.

**Comment by jonbob** [comment]
@darincomeau - are you comfortable with us merging this without @xylar's review?

**Comment by darincomeau** [comment]
@jonbob yes, based on the testing done here and in https://github.com/MPAS-Dev/MPAS-Model/pull/672.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
