### PR TITLE
Update RRTMGP inputdata data and fix read issue

### LINKED ISSUE #2565: Can't read inputdata for RRTMGP runs on titan
E3SM run on titan using the RRTMGP radiation option (specified by adding '-rad rrtmpg' to CAM_CONFIG_OPTS) fails during initialization with an error while loading necessary input files:

load_and_init(): can't open file /lustre/atlas1/cli900/world-shared/cesm/inputdata/atm/cam/rad/rrtmgp_coefficients_sw_c180724.nc

The files exists, so there must be something else going on (file permissions? netcdf version issues?)

### PR DESCRIPTION
**Pull request by brhillman**
Update RRTMGP inputdata with new absorption coefficient data from the main RRTMGP repo, and convert to proper format to be read on OLCF and NERSC machines. Fixes #2565. Should be BFB for all tests other than the RRTMGP test, which will produce a namelist compare error and a baseline compare error due to the differing absorption coefficients, but this is expected.

[NML]
[NBFB]

### CODE REVIEW

**Comment by singhbalwinder** [comment]
@brhillman : I have added NBFB and NML to this PR's description as it will break a test in our testing suites.

**Comment by brhillman** [comment]
@singhbalwinder great, thanks!

**Comment by brhillman** [comment]
@polunma because the dimension names are in an array, so all strings have to have the same length. Different compilers will handle this differently. I think intel handled this fine, PGI truncated "swband" to "swb" because the smallest string (lev) had length 3, and GNU I think will just throw a compile-time error.

**Comment by singhbalwinder** [comment]
merged to next

**Pull request merged**
