### PR TITLE
Add missing fates_levleaf dim

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Adding missing fates_levleaf dim, which is used for defining
the fates_levleaf variable

This PR is non-BFB for FATES tests.

[non-BFB]

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
Without this fix, the fates_levleaf is created with an incorrect ("lon") dimension,
```
  int fates_levleaf(lon) ;
    fates_levleaf:long_name = "FATES leaf+stem level" ;
    fates_levleaf:units = "VAI" ;
```

**Comment by jayeshkrishna** [comment]
This PR is non-BFB for the following FATES tests,
```
  ERS_Ld20.f45_f45.IELMFATES.anlgce_gnu.elm-fates (Overall: DIFF) details:
  SMS_Ld20.f45_f45.IELMFATES.anlgce_gnu.elm-fates_eca (Overall: DIFF) details:
  SMS_Ld20.f45_f45.IELMFATES.anlgce_gnu.elm-fates_rd (Overall: DIFF) details:
  SMS_Ld30.f45_f45.IELMFATES.anlgce_gnu.elm-fates_satphen (Overall: DIFF) details:

```
The dimension of the fates_levleaf variable is different in the ELM history files for these tests with this change

**Comment by jayeshkrishna** [comment]
@rgknox : If you are going to fix this issue in your PR we can close this one and let your PR fix the issue.

**Comment by rgknox** [comment]
my changes are tied in with a large PR on the FATES side and may not make its way in that quickly. I'm fine with your suggestion, but don't want to hold up the E3SM team on fixes.

**Review by glemieux — CHANGES_REQUESTED** [review]
The following is also missing in `hist_addfld2d` further down in this file:
```
case ('fates_levleaf')
   num2d = nlevleaf
```

**Comment by jayeshkrishna** [comment]
ok, I will add the above change too

**Review by glemieux — APPROVED** [review]

**Comment by rljacob** [comment]
@rgknox your change has been added.  Jayesh is on vacation for a few weeks.

**Review by rgknox — APPROVED** [review]
Looks good!

**Comment by peterdschwartz** [comment]
merged to next

**Comment by peterdschwartz** [comment]
merged to master since the tests were already blessed. Will submit perlmutter bless requests once the results are back.

**Pull request merged**
