### PR TITLE
Update perf-tests to match v3 configurations

### PR DESCRIPTION
**Pull request by amametjanov**
Update perf-tests to match v3 configurations. Also,
- add high-res perf-test suite
- update grids in superBFB tests
- add S,M,L PE-layouts for v3-grid WCYCL cases on Anvil

[BFB]

### CODE REVIEW

**Review by rljacob — APPROVED** [review]

**Comment by amametjanov** [comment]
Testing on pm-cpu -- all pass: https://my.cdash.org/viewTest.php?buildid=2601101

**Comment by rljacob** [comment]
Please update the title and description to include the high-res work.

**Review by jonbob — APPROVED** [review]
looks perfect

**Comment by rljacob** [comment]
@amametjanov is this ready to start merging?

**Pull request merged**
