### PR TITLE
Update mpas-source: Port ocean velocity to GPU

### PR DESCRIPTION
**Pull request by mattdturner**
This is the first phase of a GPU implementation of all the baroclinic velocity tendencies.

See https://github.com/MPAS-Dev/MPAS-Model/pull/772

[non-BFB]

### CODE REVIEW

**Comment by mattdturner** [comment]
This PR passes MPAS-O standalone tests as BFB for Intel, GNU, and PGI.

In E3SM, it passes:
```
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_gnu
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
  - PASS SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu BASELINE next_20210114
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
  - PASS SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel BASELINE next_20210114
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
```

It fails the baseline comparison for `SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi`.  However, generating a new baseline for the same test w/ Debug enabled and then re-testing this branch (again, with debug) yields BFB results.

**Comment by jonbob** [comment]
@philipwjones - can you please review this whenever you have time?

**Review by philipwjones — APPROVED** [review]
Approved based on previous discussions and testing by @mattdturner

**Comment by jonbob** [comment]
merged to master and expected compy_pgi DIFFs blessed

**Pull request merged**
