### PR TITLE
Update CIME to ESMCI cime5.8.1

### PR DESCRIPTION
**Pull request by jgfouca**
Update CIME to ESMCI cime5.8.1

Squash merge of jgfouca/branch-for-to-acme-2019-04-08

Features:
* Support optional components by filling in stub models for any missing component class
* cprnc: Make FIELDLIST message more informative
* cprnc: allow differences in field lists for time-constant fields

Bug fixes:
* The check for an rpointer.drv file did not consider multidriver mode.
* Fix ./case.build --clean
* PET and ERP tests were not setting compile_threaded correctly.
* Fixes inconsistency between MPASCICE and MPASSI, change all occurances of the former to the latter

This is non-BFB for A cases due to:
https://github.com/ESMCI/cime/pull/3053

[non-BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
I think you should wait on a merge until https://github.com/ESMCI/cime/pull/3055 has been added to CIME.

**Comment by rljacob** [comment]
Also they just tagged 5.8.1

**Comment by jgfouca** [comment]
I can do another merge when 3055 is ready. I'll update the PR name to reflect that this is 5.8.1.

**Comment by jgfouca** [comment]
@jonbob , note the MPASCICE -> MPASSI change.

**Comment by jgfouca** [comment]
This seems to be working now, at least on melvin with e3sm_developer. Merging to next.

**Comment by jgfouca** [comment]
Squash-merged.

**Pull request closed without merging**
