### PR TITLE
Adds tests for land BGC

### LINKED ISSUE #2465: ERS.f19_g16.I1850GSWCNPECACNTBC fails on restart
ERS test fails for I1850GSWCNPECACNTBC during the COMPARE_base_rest stage

```
  ERS.f19_g16.I1850GSWCNPECACNTBC.edison_intel.clm-eca_f19_g16_I1850GSWCNPECACNTBC (Overall: FAIL) details:
    PASS ERS.f19_g16.I1850GSWCNPECACNTBC.edison_intel.clm-eca_f19_g16_I1850GSWCNPECACNTBC CREATE_NEWCASE
    PASS ERS.f19_g16.I1850GSWCNPECACNTBC.edison_intel.clm-eca_f19_g16_I1850GSWCNPECACNTBC XML
    PASS ERS.f19_g16.I1850GSWCNPECACNTBC.edison_intel.clm-eca_f19_g16_I1850GSWCNPECACNTBC SETUP
    PASS ERS.f19_g16.I1850GSWCNPECACNTBC.edison_intel.clm-eca_f19_g16_I1850GSWCNPECACNTBC SHAREDLIB_BUILD time=770
    PASS ERS.f19_g16.I1850GSWCNPECACNTBC.edison_intel.clm-eca_f19_g16_I1850GSWCNPECACNTBC MODEL_BUILD time=452
    PASS ERS.f19_g16.I1850GSWCNPECACNTBC.edison_intel.clm-eca_f19_g16_I1850GSWCNPECACNTBC SUBMIT
    PASS ERS.f19_g16.I1850GSWCNPECACNTBC.edison_intel.clm-eca_f19_g16_I1850GSWCNPECACNTBC RUN time=244
    FAIL ERS.f19_g16.I1850GSWCNPECACNTBC.edison_intel.clm-eca_f19_g16_I1850GSWCNPECACNTBC COMPARE_base_rest
    PASS ERS.f19_g16.I1850GSWCNPECACNTBC.edison_intel.clm-eca_f19_g16_I1850GSWCNPECACNTBC MEMLEAK
    PASS ERS.f19_g16.I1850GSWCNPECACNTBC.edison_intel.clm-eca_f19_g16_I1850GSWCNPECACNTBC SHORT_TERM_ARCHIVER
```

### PR DESCRIPTION
**Pull request by bishtgautam**
Adds ERS test for ECA and CTS for 1850 and 20-th century transient
at f19_g16 resolution with spun up initial conditions

Fixes #2465
[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
How exactly does this fix the restart test fail in #2465?  I thought you would have to edit some Fortran.

**Comment by jqyin** [comment]
@bishtgautam  you have commits that make changes to both cime and component files.  I see the logic though since the testmods_dirs is moving to component side now.

**Comment by bishtgautam** [comment]
@jqyin, thanks for catching the simultaneous mods to cime and non-cime files. Let me clean this PR.

@rljacob, It turned out that the surface dataset used to generate the initial condition and surface dataset actually being used in the test were different. When the initial file was regenerated via interpinic to have a consistent surface dataset, the test is bfb. But, why the difference in surface dataset resulted to non-bfb is not understood.

**Comment by bishtgautam** [comment]
@jqyin, I have now cleaned up the PR.

**Comment by rljacob** [comment]
There must be some difference in the initial vs. restart code in how that field is handled.

**Comment by jqyin** [comment]
Merged #2468

**Pull request merged**
