### PR TITLE
Update Compy config

### PR DESCRIPTION
**Pull request by amametjanov**
* Update cpu bindings
* Add low-res pelayouts

[BFB]

### CODE REVIEW

**Comment by amametjanov** [comment]
PE-layouts for low-res F-compset:
*  23 nodes: 5.1 sypd
*  68 nodes: 11.0 sypd
* 135 nodes: 22.3 sypd

Low-res coupled-compset:
* 30 nodes: 3.8 sypd
* 42 nodes: 5.3 sypd
* 84 nodes: 9.7 sypd

**Comment by worleyph** [comment]
@amametjanov , with your deleting the specification of slurm.out and slurm.err in config_batch.xml, this breaks some logic in provenance.py. Please wait until I give you, or commit, a fix for this. Thanks.

**Comment by rljacob** [comment]
@amametjanov is this ready or do you want to keep it open to add things?

**Comment by amametjanov** [comment]
This is ready.

Intel-MPI numbers:
* low-res F-compset:
** 23 nodes: 4.9 sypd
** 68 nodes: 13.5 sypd
** 135 nodes: 24.4 sypd

* low-res wcycle-compset:
** 27 nodes: 4.3 sypd
** 40 nodes: 6.3 sypd
** 80 nodes: 10.9 sypd
** 160 nodes: 16.9 sypd

**Comment by bibiraju** [comment]
@amametjanov can you add a reviewer who can review the changes? I won't be able to point out issues if any, as I am not familiar.

**Comment by amametjanov** [comment]
^ Rob?

**Comment by rljacob** [comment]
@bibiraju this is ready.

**Pull request merged**
