### PR TITLE
Vectorize loops in coupler attr-vector multiplications

### PR DESCRIPTION
**Pull request by amametjanov**
Vectorize loops in coupler attr-vector multiplications

[BFB]

### CODE REVIEW

**Comment by amametjanov** [comment]
This should give ~5% speedup. Checked with 145-node threaded high-res wcycl runs on Theta:
* 891.414 secs before
* 850.756 secs after
```
azamatm@thetalogin1:/projects/ClimateEnergy_2/azamatm/SMS_PMT.ne120_oRRS18v3_ICG.A_WCYCL1950S_CMIP6_HR.theta_intel.cam-cosplite.C.20180621_195857_fy91bh> grep -ir "wallmax" run/timing/model_timing_stats
name                                            processes  threads        count      walltotal   wallmax (proc   thrd  )   wallmin (proc   thrd  )
azamatm@thetalogin1:/projects/ClimateEnergy_2/azamatm/SMS_PMT.ne120_oRRS18v3_ICG.A_WCYCL1950S_CMIP6_HR.theta_intel.cam-cosplite.C.20180621_195857_fy91bh> grep -ir "\"cpl:run\"" ../SMS_PMT.ne120_oRRS18v3_ICG.A_WCYCL1950S_CMIP6_HR.theta_intel.cam-cosplite.G.20180621_184950_rgtf6i/run/timing/model_timing_stats
"CPL:RUN"                                            9280     9280 4.648800e+07   6.058071e+06   891.414 (  6265      0)     0.009 (  8830      0)
azamatm@thetalogin1:/projects/ClimateEnergy_2/azamatm/SMS_PMT.ne120_oRRS18v3_ICG.A_WCYCL1950S_CMIP6_HR.theta_intel.cam-cosplite.C.20180621_195857_fy91bh> grep -ir "\"cpl:run\"" run/timing/model_timing_stats
"CPL:RUN"                                            9280     9280 4.648800e+07   5.783957e+06   850.756 (  6265      0)     0.009 (  9015      0)
```

**Comment by rljacob** [comment]
Did you do multiple runs?  5% could be random between 2 runs with no changes.

**Comment by amametjanov** [comment]
Yes, both on KNLs (Theta) and Broadwells (Bebop).

**Comment by ndkeen** [comment]
I was curious about this improvement. What tests might be run to have the best chances of showing 5% improvement?  I ran several F compsets (on cori-knl) with and without the addition of the `simd` pragma and I don't see any differences in the times.

**Pull request merged**
