### PR TITLE
CIME Update

### LINKED ISSUE #4424: Bug: short term archiving moves MPAS hybrid restart files
There is a bug in short term archiving when it archives MPAS restart files. Instead of only moving restart files from the current simulation, it will also move restart files in the run sub-directory that are neded for a hybrid restart. This then causes the model to fail upon restart.

Specific example:

Case name of the simulation: `v2.LR.abrupt-4xCO2_0101`. This simulation is configured as a hybrid restart at year 0101 from `v2.LR.piControl`.

When short term archiving year 0101, the following two files

```
v2.LR.piControl.mpaso.rst.0101-01-01_00000.nc
v2.LR.piControl.mpassi.rst.0101-01-01_00000.nc
```

are moved out of the `run/` sub-directory and into:

```
v2.LR.abrupt-4xCO2_0101/archive/rest/0101-01-01-00000/
```

The next time the model tries to restart, it fails:

```
ERROR:  ERROR mpassi buildnml: missing specified restart file for branch or hybrid run: /lcrc/group/e3sm/ac.golaz/E3SMv2/v2.LR.abrupt-4xCO2_0101/run/v2.LR.piControl.mpassi.rst.0101-01-01_00000.nc
```

We should fix this for v2.0. (I recall running into the same problem during the v1 Water Cycle simulation campaign).

### PR DESCRIPTION
**Pull request by jgfouca**
to c6f489356fd385c465eec285b0321c09c12b2e97

Fixes:
1) check the size of read only xml files for 0 size
2) Fix e3sm archiving, GIT files, preview_run
3) Prepend the casename to mpas component restart file search in st_archive
4) Fix replay archive when replay.sh is not +w

Fixes #4424 

[BFB]

### CODE REVIEW

**Review by rljacob — APPROVED** [review]

**Comment by jgfouca** [comment]
@jonbob , the archive change doesn't seem to work:

```
ERROR: File mali.rst.1976-01-01_00000.nc was not copied to archive.
Traceback (most recent call last):
  File "/home/jgfouca/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 429, in _phase_modifying_call
    function()
  File "/home/jgfouca/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 381, in _st_archive_case_test
    result = self._case.test_env_archive()
  File "/home/jgfouca/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_st_archive.py", line 888, in test_env_archive
    _check_disposition(testdir)
  File "/home/jgfouca/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_st_archive.py", line 925, in _check_disposition
    expect(find_files(os.path.join(testdir,"archive"), _file) != [],
  File "/home/jgfouca/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 152, in expect
    raise exc_type(msg)
CIME.utils.CIMEError: ERROR: File mali.rst.1976-01-01_00000.nc was not copied to archive.
```

(this was for test ERS.f09_g16_g.MALISIA)

**Comment by jonbob** [comment]
Maybe we haven't patched mali to have the casenames yet? Let me check that -- I can think of a quick patch if that's true

**Comment by jonbob** [comment]
I'll have to try that and let you know -- it sure looks to me like the casename should be prepended for mali as well:
````
        lines.append('                      filename_template="{}.mali.rst.$Y-$M-$D_$S.nc"'.format(casename))
````

**Comment by jonbob** [comment]
I'm not sure where that error is coming from. When I run that test, I see the following mali restart file:

 ERS.f09_g16_g.MALISIA.chrysalis_intel.20210728_175609_9aiwsi.mali.rst.0001-01-07_00000.nc

**Comment by rljacob** [comment]
where is "1976" coming from?

**Comment by jonbob** [comment]
As near as I can tell, there's some built-in testing in the case_st_archive.py script that defines files with the 1976 datestring:
````
restfiles = [f for f in os.listdir(os.path.join(testdir,"archive","rest","1976-01-01-00000"))]
````
But I don't understand what it's doing. @jgfouca, git blame says you added this test_st_archive routine?

**Comment by rljacob** [comment]
@jgfouca are you saying ERS.f09_g16_g.MALISIA doesn't work for you or scripts_regression_tests is failing?

**Comment by jgfouca** [comment]
@rljacob , yes, the test ERS.f09_g16_g.MALISIA does not work. It runs fine, but fails the archiving step:
```
FAIL ERS.f09_g16_g.MALISIA.mappy_gnu (phase SHORT_TERM_ARCHIVER)
```

**Comment by jgfouca** [comment]
@jonbob , here are the nc files in my case:

```
./run/ERS.f09_g16_g.MALISIA.mappy_gnu.C.20210728_130016_q4xd96.mali.hist.am.0001-01-07_00000.nc
./run/ERS.f09_g16_g.MALISIA.mappy_gnu.C.20210728_130016_q4xd96.mali.hist.am.0001-01-01_00000.nc
./run/ERS.f09_g16_g.MALISIA.mappy_gnu.C.20210728_130016_q4xd96.mali.hist.0001-01-01_00000.nc
./run/ERS.f09_g16_g.MALISIA.mappy_gnu.C.20210728_130016_q4xd96.mali.rst.0001-01-07_00000.nc
./run/ERS.f09_g16_g.MALISIA.mappy_gnu.C.20210728_130016_q4xd96.cpl.r.0001-01-07-00000.nc
./run/ERS.f09_g16_g.MALISIA.mappy_gnu.C.20210728_130016_q4xd96.cpl.hi.0001-01-12-00000.nc
./env_archive_test/archive/rest/1976-01-01-00000/casename.cpl.r.1976-01-01-00000.nc
./env_archive_test/archive/cpl/hist/casename.cpl.ha.1976-01-01-00000.nc
./env_archive_test/archive/cpl/hist/casename.cpl.ha2x1d.1976-01-01-00000.nc
./env_archive_test/archive/cpl/hist/casename.cpl.ha2x1h.1976-01-01-00000.nc
./env_archive_test/archive/cpl/hist/casename.cpl.hi.1976-01-01-00000.nc
./env_archive_test/archive/cpl/hist/casename.cpl.hl2x1yr_glc.1976-01-01-00000.nc
./env_archive_test/archive/glc/hist/mali.hist.am.globalStats.1976-01-01.nc
./env_archive_test/archive/glc/hist/mali.hist.am.highFrequencyOutput.1976-01-01_00.00.00.nc
./env_archive_test/mali.rst.1976-01-01_00000.nc
./env_archive_test/mali.rst.am.timeSeriesStatsMonthly.1976-01-01_00000.nc
./env_archive_test/casename.cpl.r.1976-01-01-00000.nc
./env_archive_test/casenamenot.cpl.r.1976-01-01-00000.nc
```

Some of these don't look right. The string `casename` appears in several.

**Comment by jonbob** [comment]
Thanks @jgfouca. And that's strange, casename is only in the 1976 files. How do those files get made?

**Comment by jonbob** [comment]
I'd appreciate it -- it may make sense to you quickly when I would struggle with the syntax

**Comment by jonbob** [comment]
@jgfouca - in my test directory, I modified a section of env_archive.xml to prepend casename before the mali files, like this:
````
      <test_file_names>
        <tfile disposition="copy">rpointer.glc</tfile>
        <tfile disposition="copy">casename.mali.rst.1976-01-01_00000.nc</tfile>
        <tfile disposition="copy">casename.mali.rst.am.timeSeriesStatsMonthly.1976-01-01_00000.nc</tfile>
        <tfile disposition="move">casename.mali.hist.am.globalStats.1976-01-01.nc</tfile>
        <tfile disposition="move">casename.mali.hist.am.highFrequencyOutput.1976-01-01_00.00.00.nc</tfile>
      </test_file_names>
````
which is how the cpl files are treated. Then it passes the ERS test:
````
PASS ERS.f09_g16_g.MALISIA.chrysalis_intel CREATE_NEWCASE
PASS ERS.f09_g16_g.MALISIA.chrysalis_intel XML
PASS ERS.f09_g16_g.MALISIA.chrysalis_intel SETUP
PASS ERS.f09_g16_g.MALISIA.chrysalis_intel SHAREDLIB_BUILD time=167
PASS ERS.f09_g16_g.MALISIA.chrysalis_intel MODEL_BUILD time=229
PASS ERS.f09_g16_g.MALISIA.chrysalis_intel SUBMIT
PASS ERS.f09_g16_g.MALISIA.chrysalis_intel RUN time=14
PASS ERS.f09_g16_g.MALISIA.chrysalis_intel COMPARE_base_rest
PASS ERS.f09_g16_g.MALISIA.chrysalis_intel MEMLEAK insuffiencient data for memleak test
PASS ERS.f09_g16_g.MALISIA.chrysalis_intel SHORT_TERM_ARCHIVER
````
But looking through CIME, I have no idea how to automate that

**Comment by jonbob** [comment]
@jgfouca - I did find where to modify the env_archive.xml file. It's in E3SM as cime_config/config_archive.xml. I've modified that file so all the mpas components have "casename" prepended to their restart files and testing right now.

**Comment by jonbob** [comment]
@jgfouca - could you try with the changes in this branch: jonbob/scripts/fix-config-archive-for-mpas? Thanks

**Comment by jgfouca** [comment]
@jonbob , that worked! Should I bring that branch into this PR?

**Comment by jonbob** [comment]
Please do, if it makes sense. And if not, we can add an issue and do this PR separately to fix the bug

**Pull request merged**
