### PR TITLE
Common derived types for land BGC

### PR DESCRIPTION
**Pull request by bishtgautam**
Adds new common derived types (`nutrientstate_type` and `nutrientflux_type`) 
for CNP states and fluxes. The new derived types remove ~5000 duplicate
lines from CNP state and flux modules.

[BFB]

### CODE REVIEW

**Comment by bishtgautam** [comment]
This PR will be rebased after #2135 and #2320 are merged to master.

**Comment by thorntonpe** [comment]
This PR is undergoing review by the Land Group, with updates to follow.

**Comment by rljacob** [comment]
@thorntonpe what is the status of this PR?

**Comment by bishtgautam** [comment]
Closing this PR because there are too many conflicts. The central idea of this PR to have common derived types for nutrients in the land model might be incorporated in a future PR.

**Pull request closed without merging**
