### PR TITLE
Fix loop extents to avoid uninitialized array issues

### PR DESCRIPTION
**Pull request by jonbob**
Testing in debug mode with additional flags pointed at initialization problems in this subroutine. Fixing the loop extents avoids this issue and does not change answers.

[BFB]

### CODE REVIEW

**Comment by jonbob** [comment]
passes:
* ERS.ne11_oQU240.WCYCL1850NS.chrysalis_intel
* SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod

**Review by vanroekel — APPROVED** [review]
Approving based on visual inspection and testing by @jonbob

**Review by mark-petersen — APPROVED** [review]
Compiled with gnu and intel on chrysalis. Passes nightly suite for stand-alone using debug for both, matches bfb against V2.1.0 tag. Thanks @jonbob for catching this!

**Comment by jonbob** [comment]
passes:
* SMS_D_Ld3.T62_oQU120.CMPASO-IAF.chrysalis_intel
* ERS.ne11_oQU240.WCYCL1850NS.chrysalis_intel
* SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod

merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
