### PR TITLE
Make RRTMGP a submodule

### LINKED ISSUE #2798: RRTMGP code should be submodule?
Tagging this with the question label, because I'm not 100% sure this is the right thing to do but wanted to get input before I go ahead with it. Our new radiation package (RRTMGP) is maintained in a separate external repository. Currently, we have a copy of the code integrated into E3SM, but since RRTMGP is still under fairly active development, any time I want to pull in updates to the external repo, I need to copy over the files and commit on our end. This does not seem like the best way of doing this. Would it be appropriate to make the RRTMGP code a submodule, or is there a more preferred way of handling this now?

### PR DESCRIPTION
**Pull request by brhillman**
Make external RRTMGP code a submodule. This will allow us to more easily pull in changes to the RRTMGP code as that codebase continues to evolve. This code is developed external to E3SM, so making this a submodule to track the RRTMGP repository seems to make the most sense. This PR also pulls in the latest version of RRTMGP, which is NOT bit-for-bit with the version in master currently. Non-RRTMGP test cases should still be BFB (the only baseline comparison fail should be that for `ERS_Ld5.ne4_ne4.FC5AV1C-L.cam-rrtmgp` in the `e3sm_atm_integration` suite). This appears to be due to small differences in the values used for physical constants within the RRTMGP code, as well as a change in how the dry column molecular amounts are calculated within the RRTMGP code. These affect on the solution is small, however. Shown here are net shortwave and longwave clear-sky fluxes at the top of the atmosphere for two simulations at ne4np4 resolution, one with current master and one with these changes (with `-rad rrtmgp` selected for both):
Screen Shot 2019-03-15 at 4 31 45 PM
Screen Shot 2019-03-15 at 4 31 55 PM
Grey lines indicate the column difference, with a separate scale indicated on the right axis. Note that the differences are on the order of a few $W/m^2$, while the magnitude of the column values are hundreds of W/m^2.

Slight changes are needed in the E3SM code that interfaces with RRTMGP to accommodate a change in data structures in RRTMGP (`ty_gas_optics` is now abstract, and we access via `ty_gas_optics_rrtmgp`). This change is made in `radiation.F90` and in `cam_optics.F90`.

  Fixes #2798.

### CODE REVIEW

**Comment by brhillman** [comment]
@jgfouca I'm asking for a review from you simply to check that I handled the submodule aspect of this properly. You can disregard the rest of the changes.

**Comment by rljacob** [comment]
Did you delete the code in components/cam/src/physics/rrtmgp/external and commit that deletion?

**Comment by brhillman** [comment]
@rljacob I deleted the code in external and adding the submodule in the same commit. Do I need two commits to do this properly?

**Comment by rljacob** [comment]
Maybe I don't understand what github is showing me.  I expect it to say everything in cam/src/physics/rrtmgp/external was deleted.  Instead, its showing diffs.  And when I check out this branch, there is still code in cam/src/physics/rrtmgp/external before I initialize the submodule.

**Comment by brhillman** [comment]
@rljacob I think it would still show diffs either way, since the files are all mostly in the same paths. I can try explicitly deleting the code and making a separate commit before pulling in the submodule and see if that changes things. I also thought newer versions of git pulled in submodules upon checkout without needing an explicit `git submodule update --init`, so maybe that's why you're still seeing code before initializing?

**Comment by rljacob** [comment]
When you "added the submodule" it looks like you also committed new code in the externals directory.  I think this process should end with that directory empty. See the first 5 steps here:  https://gist.github.com/MJeorrett/50b707ab49d05cebb15a117f7fd6a20a.

**Comment by brhillman** [comment]
@rljacob does this look fixed now?

**Comment by jgfouca** [comment]
Do you plan on tracking a certain branch of RRTMGP?

**Comment by brhillman** [comment]
@jgfouca master.

**Comment by brhillman** [comment]
If this causes problems I can keep a separate branch where I pull in updates from master on a planned schedule. Do you have advice in this regard?

**Comment by rljacob** [comment]
Yes it looks ok now.  And thanks for force-pushing to remove the bad commits.

Most of our submodules track master so that's ok.

**Comment by jgfouca** [comment]
@brhillman , if you are tracking a branch, it can be helpful to add that metadata to the submodule:

```
git submodule add -b master ...
```

Not only is this useful for documenting what you intend to track, but it allows you to do:

```
git submodule update --remote 
```

Which is a convenient way to update the submodule to the latest commit on the tracked branch.

**Comment by brhillman** [comment]
Thanks @jgfouca can I set the remote tracking information for the branch after adding (i.e., without re-doing the `git add` commit)? Or does it default to master?

**Comment by jgfouca** [comment]
@brhillman , I think you can just add it manually to .gitmodules.

```
[submodule "components/cam/src/physics/rrtmgp/external"]
	path = components/cam/src/physics/rrtmgp/external
	url = git@github.com:RobertPincus/rte-rrtmgp.git
```

... would become:

```
[submodule "components/cam/src/physics/rrtmgp/external"]
	path = components/cam/src/physics/rrtmgp/external
	url = git@github.com:RobertPincus/rte-rrtmgp.git
        branch = master
```

**Comment by brhillman** [comment]
Thanks for the tip @jgfouca, I made that change with the last commits. I think this should be ready to go.

**Comment by brhillman** [comment]
Pinging @polunma for his review so we can get this merged. We have some updates to RRTMGP coming soon that I will need to merge, and this PR will make that a lot easier.

**Comment by brhillman** [comment]
@singhbalwinder pinging you to see when we might be able to get this merged. I have some development I need to do on the RRTMGP code and it would be good to branch off current master with these changes.

**Comment by singhbalwinder** [comment]
Thanks @brhillman for the reminder. I will merge this as soon as next opens again for merging. Right now next and master are closed for merging due to some unexpected failures on cdash.

**Comment by brhillman** [comment]
@singhbalwinder thanks!

**Comment by singhbalwinder** [comment]
Merged to next.

**Comment by brhillman** [comment]
Thanks @singhbalwinder!

**Pull request merged**
