### PR TITLE
Turn on additional output for SORRMv3 mesh

### PR DESCRIPTION
**Pull request by darincomeau**
Turns on the ocean conservation analysis member and ocean eddy analysis member for the SOwISC12to30E3r3 mesh.

This allows plotting of mass flux anomaly due to land ice fluxes and EKE in MPAS-Analysis.

[BFB]

### CODE REVIEW

**Comment by darincomeau** [comment]
Tested

SMS.ne30pg2_r05_SOwISC12to30E3r3.CRYO1850.chrysalis_intel
confirmed `mpaso_in` settings turned on here, and

SMS.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel
confirmed `mpaso_in` settings changed here for `SOwISC12to30E3r3` remained default off.

**Comment by proteanplanet** [comment]
Can you provide an estimate of the added computational overhead from this change?

**Comment by darincomeau** [comment]
@proteanplanet turning on the ocean eddy analysis member is in the noise/machine variability as far as I can tell.

Example PACE with ocean eddy analysis on: 
https://pace.ornl.gov/exp-details/201662, 8.13 SYPD

Example PACE with ocean eddy analysis off:
https://pace.ornl.gov/exp-details/199419, 8.13 SYPD

I don't have an estimate for the computational overhead of the ocean conservation analysis member here, since we always run with it on (and need it on). When I [turned it on for v2 meshes](https://github.com/E3SM-Project/E3SM/pull/5441), I found minimal impact in one-year B-case tests.

**Review by cbegeman — APPROVED** [review]
Thanks @darincomeau! I agree that this is what we want. Let me know if you'd like me to do any additional testing.

**Comment by darincomeau** [comment]
@proteanplanet I ran a pair of small one month `ne30pg2_r05_SOwISC12to30E3r3.CRYO1850` tests to estimate performance cost:

Baseline (additional analysis remains off): 1.85 SYPD
This PR (additional analysis on): 1.80 SYPD


So that's an estimated 2-3% overhead for the additional analysis members here.

**Review by proteanplanet — APPROVED** [review]
Approved.  Additional computation costs are minimal and necessary.

**Comment by jonbob** [comment]
Passes:
* ERP_Ld3.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-pioroot1

merged to next

**Pull request merged**
