### PR TITLE
Create F2010 LR CMIP6 compset

### PR DESCRIPTION
**Pull request by tangq**
This PR create the F2010 LR compset with CMIP6 forcings.

### CODE REVIEW

**Comment by rljacob** [comment]
@tangq please update the description to remove links to confluence and the path name.  You can add that material in comments under the description.   In the PR description, just use words or you can reference other hashes in the repo.

**Comment by wlin7** [comment]
All looks good, @tangq . Do need your confirmation on: 

1) aerosol forcing and emission files use those from 20TRC5-CMIP6 compset. Is it intended. I know it is [documented so on the confluence](https://acme-climate.atlassian.net/wiki/spaces/ED/pages/961250902/F2010C5-CMIP6-LR).

2) Have you tested that the specified finitdat and fsurdat can work together, even with consistency check?

**Comment by tangq** [comment]
The 1-day test run is successful and located at /global/cscratch1/sd/tang30/E3SM_simulations/edison.20190415_maint-1.0.tst_F2010C5-CMIP6-LR.ne30_oECv3

**Comment by tangq** [comment]
Hi @wlin7 , to answer your questions:
1. It seems to me that for the same grids, the F1850, F2010, and F20TR should use consistent aerosol files, so I use the year 2010 slice of the F20TR aerosol files. Different HR and LR aerosol files are related to the fact that obs4mips provides different aerosol raw files for CMIP6 HR and LR runs.
2. In my 1-day test above, I didn't turn off the consistency check. In the lnd log file, the following session confirms that this check is on.
finidat_consistency_checks settings:
 &FINIDAT_CONSISTENCY_CHECKS
 CHECK_FINIDAT_FSURDAT_CONSISTENCY       = T,
 CHECK_FINIDAT_YEAR_CONSISTENCY  = T,
 CHECK_FINIDAT_PCT_CONSISTENCY   = T
 /

**Comment by wlin7** [comment]
Thanks for the reply, @tangq . The spec for aerosol files are reasonable. Do you want @PeterCaldwell and @golaz to also review and approve this PR? I can start merging this PR to maint-1.0 anytime.

**Comment by tangq** [comment]
@PeterCaldwell , you are right. This compset is the "real" low-res compset, not with HR tuning.

**Comment by tangq** [comment]
@golaz , I agree that we need a better compset naming convention. When creating this compset, I followed the old convention. We can switch to the new one (when established) later.

Thank you all for checking and making sure the settings are correct.

@wlin7 , looks like this PR is ready to be merged. Thanks.

**Comment by PeterCaldwell** [comment]
@golaz  makes a good point that our compset names don't make logical sense, but I agree with Qi that we shouldn't change the convention in this PR... we should change all names in a future PR.
In particular, doesn't "c5" stand for "CAM5"? That's kind of awkward...

**Comment by golaz** [comment]
@rljacob : is it possible to have multiple aliases point to the same compset? If so, that would make it easier to come up with a better naming convention later without breaking previous configurations?

**Comment by golaz** [comment]
@tangq and @wlin7 : thanks for all the work on this.
Can we also have the new CMIP6 compsets on master?

**Comment by wlin7** [comment]
Merged to maint-1.0. 

@golaz, it is a good idea for using multiple aliases when switching to a new naming convention while keeping the existing one. Logically it should be fully supported to have multiple aliases pointing to the same compset. I just did a test anyway using this LR compset  and confirmed it.

BTW, reminded by @PeterCaldwell 's comments, even many of the longnames for the compset carry the tag of "CAM5". We may one day need to change that as well.

**Comment by golaz** [comment]
@wlin7, thanks for trying out. We could start by having multiple aliases but I agree with you and @PeterCaldwell that a long name with CAM5 in it doesn't make much sense any longer. I don't know how disruptive it would be to try to remedy this.

**Comment by wlin7** [comment]
@golaz , we can start to work to get these CMIP6 compsets on master. The F2010 HR compset still needs some update.  After that,  we can have a PR to include all the new compsets. We need a new branch that is based off the master, because merging the ones based off maint-1.0 may have issues.

**Comment by tangq** [comment]
@wlin7 , the F2010 HR compset is waiting for the finial evaluation of its performance. I already did a 5-year run (/global/cscratch1/sd/tang30/E3SM_simulations/cori-knl.20190214_maint-1.0.F2010C5-CMIP6-HR.dailySST.ne120_oRRS18v3). @PeterCaldwell will ask more people to take a look. If the results look good, I can finalize it.

**Comment by wlin7** [comment]
@golaz , as we can see from the files changed, changing CAM5 to a new name will affect the  config_compsets, config_component files, and the name of the use_case files.  The number of files affected is limited. The patterns are well defined. Once we decide on the new name, I should be able to write a script to automatically change them all.

**Pull request merged**
