### PR TITLE
Updating SCORPIO on maint-2.1 to v1.4.2

### PR DESCRIPTION
**Pull request by jayeshkrishna**
SCORPIO 1.4.2 includes,

* Fix for a performance bug where the NetCDF header was reallocated multiple times, slowing down runs that create large output files
* Support for ADIOS BP5 file format
* Preliminary support (disabled by default) for HDF5
* Improved performance by reducing some collectives
* Support for Perlmutter/Crusher/Frontier
* Minor bug fixes

[BFB]

### CODE REVIEW

**Review by dqwu — APPROVED** [review]
Tested maint-2.1 with scorpio v1.4.2 and intel compiler on pm-cpu.

**Comment by ndkeen** [comment]
I'm trying `e3sm_developer` now, but as several tests have already passed with Intel, I'm sure it will be OK.  Note that what we really need is a fix for the Intel build error on maint-2.0

**Comment by rljacob** [comment]
@ndkeen have you seen https://github.com/E3SM-Project/E3SM/pull/5983 ?

**Review by ndkeen — APPROVED** [review]
ran e3sm_developer with intel on pm-cpu (and a couple of tests with gnu)

**Pull request merged**
