### PR TITLE
Changing datestamp on JRA v1.5 runoff files to corrected versions (maint-2.1)

### PR DESCRIPTION
**Pull request by darincomeau**
This changes the datestamp on the JRA v1.5 runoff files to corrected versions that have fixed negative liquid runoff values around Greenland and Antarctica. These files have been staged in the public inputdata directory as world readable.

[non-BFB] for compsets with JRAv1.5 forcing

Fixes https://github.com/E3SM-Project/E3SM/issues/6378.

### CODE REVIEW

**Comment by darincomeau** [comment]
Confirmed new runoff files have minimum rofl = 0.

Passes

- SMS.TL319_EC30to60E2r2.GMPAS-JRA1p5.chrysalis_intel
- SMS.TL319_ECwISC30to60E2r1.GMPAS-JRA1p5-DIB-ISMF.chrysalis_intel
- SMS.TL319_EC30to60E2r2.DMPAS-JRA1p5.chrysalis_intel

and confirmed the 240411 datestamp runoff files are being used.

**Comment by darincomeau** [comment]
Already reviewed in the PR into master https://github.com/E3SM-Project/E3SM/pull/6379, @jonbob can I just add you as reviewer here or would you like me to ping someone else?

**Comment by jonbob** [comment]
Thanks @darincomeau -- I think it's fine for me to review, since the equivalent PR into master went through several other people

**Comment by jonbob** [comment]
merged to maint-2.1

**Pull request merged**
