### PR TITLE
Fixes the land initial conditions for CMIP6 compset

### PR DESCRIPTION
**Pull request by bishtgautam**
Adds the land/ocean mask for the existing land initial conditions to
only define a land initial condition file for appropriate resolutions.

[BFB]

### CODE REVIEW

**Comment by bishtgautam** [comment]
The changes in this PR are similar to the ones added by @jonbob in https://github.com/E3SM-Project/E3SM/commit/b4e57ed02e05a71109705b19ef235c4ab6aa3fd9.

**Comment by bishtgautam** [comment]
@cameronsmith1, I have added you as a reviewer because I was not sure whom should I ask to review the PR to make sure these changes don't break maint-1.0 for CMIP6 runs. Please feel to re-assign the review as you see fit. Thanks

**Comment by cameronsmith1** [comment]
Hi Gautam.   Sorry, the email notification got lost in my inbox.  I am probably not the best person to check the impact on maint-1.0.    Chris Golaz or Qi Tang would be good, if they have time.

Pinging @golaz and @tangq

**Comment by singhbalwinder** [comment]
Thanks @cameronsmith1 . I just verified that the CMIP6 F compset works fine if we use this branch. @golaz and @tangq : Would you please take a look at this change to see if it looks good to you? Thanks!

**Comment by singhbalwinder** [comment]
The code mods in this PR has already been merged in maint-1.0 via PR #2877 (Multiple mods for maint-1.0 to run compset F1850C5-CMIP6 and nbfb tests, hash: 722536bd1f1967ad97a4acc6f818df513db89845). I am closing this PR.

**Pull request closed without merging**
