### PR TITLE
EAM: enable output of vorticity and divergence 

### PR DESCRIPTION
**Pull request by mt5555**
enable outfld() calls for vorticity and divergence

add code to dp coupling layer to compute vorticity and divergence from u,v, and then DSS the results using the make_c0() routine.  

update all DSS calls in dp coupling layer and make_c0() routine to use
nlyr pack/unpack interface and have all routines use single edge_g buffer.
This reduces memory footprint and removes many edge buffer allocate/deallocate statements

[BFB]

### CODE REVIEW

**Comment by mt5555** [comment]
will most likely create conflicts with PR #2933 
this should be merged after PR #2933

**Comment by mt5555** [comment]
the ability to output vorticity and divergence is useful for tropical cyclone / storm detection and for dycore evalation.

**Comment by mt5555** [comment]
@bogensch : do you know why calls to outfld() of some dycore variables in the dp coupling layer are disabled when running single column?

**Comment by bogensch** [comment]
@mt5555 .  When constructing the SE SCM in E3SM we found we could not simply initialize the dycore with just one gauss lobatto point.  Thus, we tricked the model and told it that it only has one physics column, but initialize the full dynamics grid, even though only one column is active.  Since all outfld calls are done on the physics grid, this created an error/conflict when passing the full array.  I suppose it would work by just passing it the value for the single active column, but I imagine that output would be pretty much garbage anyway for the SCM for vorticity and divergence.

**Comment by mt5555** [comment]
thanks -makes sense.

**Comment by oksanaguba** [comment]
How to use this output? thanks!

**Comment by mt5555** [comment]
it adds to new variables for possible output, VOR and DIV, which you would add to your fincl= line in user_nl_cam.

**Comment by mt5555** [comment]
rebaselined after physgrid code went in. @whannah1 : I mucked around with a little of your code, can you take a quick look at the diff's for this PR?

**Comment by mt5555** [comment]
Also, as physics only ever returns 2 tendencies for momentrum, any objections if I remove the num_FM_vars() variable?

**Comment by whannah1** [comment]
@mt5555 I think I added that for the physgrid to simplify the code where the Oksana had added ifdefs for the theta dycor option.

**Comment by whannah1** [comment]
I'm a little confused, why did Oksana need 3 FM vars when MODEL_THETA_L is defined?

**Pull request merged**
