### PR TITLE
Initial scripts changes to add JRA support to mpas-ocean

### PR DESCRIPTION
**Pull request by jonbob**
This PR brings in the scripts changes to support JRA forcing in mpas-ocean, including new compsets and grids. These new configurations will need to be tested and validated before they can be considered scientifically supported. The JRA data itself is staged on anvil in the /home/ccsm-data/inputdata/ directory but will need to be moved to the public_htlm/inputdata directory for testing on other platforms. **This should be done prior to merging**

Tested with:
* SMS.TL319_oEC60to30v3.GMPAS-JRA.anvil_intel
* SMS.T62_oEC60to30v3.GMPAS-IAF.anvil_intel

[BFB] for all tested configurations

### CODE REVIEW

**Comment by jonbob** [comment]
@milenaveneziani , @111-1000 - could you all please review the changes I made to support both CORE and JRA forcing so I can get this in?

**Comment by 111-1000** [comment]
I am trying to perform some tests. Jobs are currently in the queue.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Comment by rljacob** [comment]
Copying the files isn't done with a PR.  Just copy them.

But there should be a PR to add a test that uses those files and tests the new compsets.

**Comment by milenaveneziani** [comment]
OK, that makes sense.

**Pull request merged**
