### PR TITLE
Fix ftype1 in NH theta

### PR DESCRIPTION
**Pull request by oksanaguba**
Fixing ftype1 for NH runs, previously, NH variables were not updated in dp_coupling layer.

[nonBFB] for cam-thetanh_ftype1 test.

### CODE REVIEW

**Comment by oksanaguba** [comment]
eam_theta passed against yesterday's master (the same one that was used for the branch) except for ftype1_thetanh (diff) test, as expected. will run whole suite tomorrow.

**Comment by mt5555** [comment]
should we add an "#ifndef CAM" around the line of code which applies the w tendency?  Currently I think we just assume that is zero and thus harmless to apply to w?

Or, since we dont have any test cases that actually generate a w tendency,  maybe we should remove it altogether?

**Comment by oksanaguba** [comment]
I ignored w, phi issue for HY runs just because in CAAR we also have w, phi local computations. Or were those removed?

**Comment by oksanaguba** [comment]
i misunderstood your question but now looking at the code i see that FM is used only with two components in some of the code in stepon while it is assumed that FM has 3 components. i will look more.

**Comment by mt5555** [comment]
just to expand more: I was thinking this line of code in applyCAMforcing_dynamics:

 elem(ie)%state%w_i(:,:,1:nlev,np1) = elem(ie)%state%w_i(:,:,1:nlev,np1) + dt*elem(ie)%derived%FM(:,:,3,:)

Not sure the right solution, but we can either assume FM(:,:,3,:)=0, or disable it in an ifndef CAM.

**Comment by oksanaguba** [comment]
e3sm_atm_integration all pass except for SMS.ne4_ne4.FC5AV1C-L.anvil_intel.cam-thetanh_ftype1 as expected.

**Comment by oksanaguba** [comment]
in next

**Pull request merged**
