### PR TITLE
Adds a print message if a fatal error occurs inside CLUBB core codes

### PR DESCRIPTION
**Pull request by singhbalwinder**
If CLUBB core codes experience a fatal error, the added print messages
print out location of the error (lat, lon and column) and the time step
at which the error occured.

[BFB] - Bit-For-Bit

### CODE REVIEW

**Comment by singhbalwinder** [comment]
@golaz and @rljacob : @vlarson would like to get this change into v2, if possible. This is a pretty minor BFB modification but can help the CLUBB developers debug the code in case the code experiences a fatal crash inside CLUBB core codes.

**Comment by singhbalwinder** [comment]
Please turn on "Hide whitespace changes" options as I removed a lot of white spaces from clubb_intr.F90 file.

**Review by vlarson — APPROVED** [review]
Thank you, Balwinder.  Looks good.  

This new error message will be helpful if E3SM crashes inside CLUBB.  It will avoid the need to re-run E3SM in order to determine the grid column in which the crash occurred.

**Review by rljacob — APPROVED** [review]

**Comment by wlin7** [comment]
Merged to next.

**Comment by wlin7** [comment]
Merged to master

**Pull request merged**
