### PR TITLE
Add argument parsing and update documentation for topography tool

### PR DESCRIPTION
**Pull request by brhillman**
Add a command line interface to the topography interpolation tool used to generate new topography inputdata for atmosphere simulations. Generating topography involves multiple steps:

1. Interpolate high resolution topography on cubed-sphere to target grid
2. Apply dycore-specific smoothing to interpolated topography so that atmosphere can run stably
3. Recompute subgrid surface roughness

This tool performs steps 1 and 3, while the smoothing needs to be handled by the dycore. However, using the tool in these two different modes required manual changes to the source code and recompiling for the two different use cases. Adding a command line interface to this tool allows a single executable to perform both of these tasks depending on the input arguments. This also enables more flexibility in the input filenames, which previously needed to have very specific names. The new usage is documented in the README (which has also been rewritten), as well as in a help message that can be displayed by running the code with no arguments or by passing the `--help` flag on the command line.

[BFB]

### CODE REVIEW

**Comment by mt5555** [comment]
nice improvement!  one request:  the comments refer to the SGH field.   Is it correct that the SGH30 field is also computed and downscaled to the target grid, but SGH30 does not depend on the smoothing?   If that's correct, can we add that information to the README?

**Comment by brhillman** [comment]
@mt5555 my apologies I am just now seeing your comment. Looking at the code, that appears to be correct. I'll add some commentary about that and push a commit shortly.

**Comment by brhillman** [comment]
@mt5555 please take a look at updated comments. This can be reworded. I mostly mimicked the language used in the cube sphere USGS file, but isn't SGH30 just the analogue to SGH but for the downscaling from the 30s USGS data to the 3km data? I.e., the estimate subgrid surface roughness in the 3km cube sphere data we are starting from?

**Comment by rljacob** [comment]
@mt5555 please review this PR.

**Comment by mt5555** [comment]
Agreed - so is this a correct summary:?

SGH30 is variance of (original - 30s data) computed on the high-res grid and then downscaled to the dycore grid

SGH is variance of (original - smoothed PHI) computed on the high-res grid and then downscaled to the dycore grid

**Comment by brhillman** [comment]
@mt5555 that's my understanding.

**Comment by singhbalwinder** [comment]
@brhillman : The changes in this PR are made to a tool, so I am assuming it is BFB PR. Please let me know if this is not correct.

**Comment by brhillman** [comment]
@singhbalwinder that's correct, none of this affects runtime, so should absolutely be bfb. I did not run e3sm_developer since none of the model code changes but can if you want.

**Comment by singhbalwinder** [comment]
Thanks @brhillman . I also think there is no need to run the tests. I will start the merging process.

**Comment by brhillman** [comment]
Thanks @singhbalwinder !

**Comment by singhbalwinder** [comment]
Merged to next. Skipping integration testing as these changes only affect cam/tools.

**Pull request merged**
