### PR TITLE
Bug fix for SCM tests on Anvil

### PR DESCRIPTION
**Pull request by whannah1**
This fixes the testing issues on Anvil that appeared after merging PR #4368.

### CODE REVIEW

**Review by lee1046 — APPROVED** [review]
Changes look good to me.

**Review by amametjanov — APPROVED** [review]

**Comment by whannah1** [comment]
I just ran SMS_Ln5.ne4_ne4.F-MMF1-SCM-ARM97 on Cori just to be thorough and it passed.

**Comment by brhillman** [comment]
Merged to next.

**Comment by brhillman** [comment]
Merged to master.

**Pull request merged**
