### PR TITLE
Add parabolic bowl test case

### PR DESCRIPTION
**Pull request by sbrus89**
This is an init mode only PR that creates the initial conditions for a parabolic bowl test case used to test wetting and drying.

[BFB]

### CODE REVIEW

**Comment by sbrus89** [comment]
This case can be tested with the compass PR found here: https://github.com/MPAS-Dev/compass/pull/670

**Review by mark-petersen — APPROVED** [review]
This ran successfully on LANL chicoma with gnu and chrysalis with intel, with both optimized and debug. Thanks!  Here is a sample of the output from the compass test case.
solution_090

**Comment by sbrus89** [comment]
Thank you, @mark-petersen!

**Comment by sbrus89** [comment]
@jonbob, this one is ready when you get a chance. Thanks!

**Comment by jonbob** [comment]
passes:
* SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod
* ERS_Ld5.T62_oQU120.CMPASO-NYF.chrysalis_intel

merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
