### PR TITLE
update mpas-source: Add diagnostics module for GPU performance

### PR DESCRIPTION
**Pull request by mark-petersen**
See https://github.com/MPAS-Dev/MPAS-Model/pull/745

This PR adds a new module to house the variables contained in diagnosticsPool in the ocean model. This also implements the use of the new module in the mpas_ocn_diagnostics.F file. 

These separate modules for diagnostics (and mesh, already added) are needed to pass variables to the GPU, but also work with the CPUs, and make the code simpler and more readable.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
Currently includes changes in #3935. Those will not show here after that merge.

**Comment by mark-petersen** [comment]
Rebased. Now includes changes in #3948 until that is merged to master.

**Comment by mattdturner** [comment]
Tested on compy for bit-for-bit.

The test `SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi` is bit-for-bit when comparing the results from this PR to #3948 .  I compared to #3948 instead of `master` because this PR includes code changes from 3948, which are not bfb.

**Comment by mark-petersen** [comment]
@vanroekel and @rljacob we would like this to be merged after #3948. It is bfb and helps us keep up progress on performance PRs this month.

**Comment by mark-petersen** [comment]
rebased. Passes:
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
```

**Comment by mattdturner** [comment]
After the recent rebase:
```
PASS:
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
```

Cori is offline, so I can't run my usual suite of tests there.

Currently failing 
```
PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_intel
```
but those 2 tests are failing on `master` as well.

**Comment by jonbob** [comment]
Runs of SMS_P480.T62_oEC60to30v3.GMPAS-IAF.compy_intel were BFB before and after a test merge of this PR

**Comment by jonbob** [comment]
@mattdturner - if you have time, could you run one of the PEM tests that fails with this setting in seaice?
config_use_high_frequency_coupling = .false.

**Review by jonbob — APPROVED** [review]
Looks good, based on extensive testing

**Review by vanroekel — APPROVED** [review]
approved based on extensive testing from @mattdturner and @jonbob

**Comment by mattdturner** [comment]
`PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_intel` PASSes if setting `config_use_high_frequency_coupling = .false.`

**Comment by jonbob** [comment]
Thanks @mattdturner !

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
