### PR TITLE
Output component MPI task to compute node mappings

### LINKED ISSUE #2485: Compact output of mapping of MPI tasks to compute nodes per component
Component-specific MPI task to compute node mapping information is output in two locations, once in CAM, where it is truncated after the first 256 MPI tasks, and once in CLM, where it is truncated after the first 100 MPI tasks, and only for these two components. These component-specific data are also written to the e3sm log file.

With PR #2458, we now have global MPI task to compute node mapping information written to the e3sm log. The current component-specific information is not useful as implemented. We could just leave this as is, but all of the following options would be enhancements.

a) remove all component-specific task-to-node mapping information from the log files.

b) use shr_taskmap_write in CAM and in CLM to write out all task-to-node mapping information in the new more compact representation, so no longer truncated.

c) use shr_taskmap_write in CAM and in CLM to write out all task-to-node mapping information in the new more compact representation, and direct the output to the associated component log file.

d) use shr_taskmap_write in CAM, CLM, Mosart, mpas-albany-landice, mpas-ocean, mpas-seaice to write out all task-to-node mapping information in the new more compact representation, and redirect the output to the associated component log file. 

Based on some recently noticed unexpected PE layout issues, (d) can be useful, and it is consistent across the active components.

### PR DESCRIPTION
**Pull request by worleyph**
Use shr_taskmap_write in CAM, CLM, Mosart, mpas-albany-landice, mpas-ocean, mpas-seaice to write out all task-to-node mapping information in the new more compact representation, and redirect the output to the associated component log file.

a) Output CAM MPI task to compute node mapping using share routine

MPI task to compute node mapping information in CAM
is output one line per task, and only for the first 256 MPI
tasks. A new share routine in CIME (shr_taskmap_write) is available
that writes out one line per compute node. Each line
contains the compute node name and the list of MPI tasks assigned
to that node for a given communicator. This share routine also
optionally returns the number of compute nodes and the
task-to-node mapping, information that is needed in the
internal CAM load balancing. Here the CAM logic in spmdinit (in
spmd_utils.F90) is removed and a call to shr_taskmap_write in
atm_init_mct (in atm_comp_mct.F90) is added, recording information for
all MPI tasks and in a more compact representation for each CAM
instance.

b) Output CLM MPI task to compute node mapping using share routine

MPI task to compute node mapping information in CLM
is output one line per task, and only for the first 100 MPI
tasks. A new share routine in CIME (shr_taskmap_write) is available
that writes out one line per compute node. Each line
contains the compute node name and the list of MPI tasks assigned
to that node for a given communicator. Here the CLM logic in spmd_init
(in spmdMod.F90) is removed and a call to shr_taskmap_write in
lnd_init_mct (in lnd_comp_mct.F90) is added, recording information for
all MPI tasks and in a more compact representation for each CLM
instance.

c) Output Mosart MPI task to compute node mapping using share routine

MPI task to node mapping information is output for ROF instances
using the new share routine shr_taskmap_write. The call is added to the
routine rof_init_mct in rof_comp_mct.F90.

d) Output mpas-albany-landice MPI task to compute node mapping

MPI task to node mapping information is output for mpas-albany-landglc instances
using the new share routine shr_taskmap_write. The call is added to the
routine glc_init_mct in glc_comp_mct.F.

e) Output mpas-ocean MPI task to compute node mapping using share routine

MPI task to node mapping information is output for mpas-ocean instances
using the new share routine shr_taskmap_write. The call is added to the
routine ocn_init_mct in ocn_comp_mct.F.

f) Output mpas-seaice MPI task to compute node mapping using share routine

MPI task to node mapping information is output for mpas-seaice instances
using the new share routine shr_taskmap_write. The call is added to the
routine ice_init_mct in ice_comp_mct.F.

Fixes #2485 

[BFB]

### CODE REVIEW

**Comment by worleyph** [comment]
Tested with -compset A_WCYCL1950S_CMIP6_LR -res ne30_oECv3_ICG on Cori-KNL. Expected output showed up in each component log file.

**Comment by rljacob** [comment]
Re-assigning because @sarats is not an integrator and 3 MPAS models are affected.   @singhbalwinder should review for atm and @bishtgautam for land/river.

**Comment by worleyph** [comment]
Reviewers should please look at issue #2485, especially the comment by @rljacob . It is not a given that this PR is a good idea. Review more than just the implementation.

**Comment by worleyph** [comment]
pinging @amametjanov , @ndkeen , @singhbalwinder and @jonbob .

To reiterate, this is an "enhancement" PR, and you should decide whether this makes sense to you for your components or system. A subsequent PR significantly decreases the verboseness of the task-to-node output (so not present in this branch, but already merged to master), but there is still one line per compute node.

If not acceptable for land or atmosphere, something will still need to be done for CAM and CLM, as the current component-specific task-to-node mapping output is useless. A separate PR can then be submitted to just disable this output for CAM or CLM.

**Comment by worleyph** [comment]
Reviewers, please look at @amametjanov 's Sept. 11 comment on github #2385 . Runtime control would be a good thing ... should this go in as part of this PR or as part of a future one? We'd also need to decide whether the control is one per component or for all components. I don't know about categorizing these as debug/no-debug options and we'd still need to decide on the appropriate defaults.
Again, this PR was to kind of support what is going on in CAM and CLM currently and to make it symmetric across all of the major components. (Should eventually add CPL as well if this PR goes in as is.) Outstanding question is whether there is any particular utility to it, given that the global task-to-node mapping is already in the model.

**Comment by sarats** [comment]
@worleyph I think this can go in in the current form especially with the compact output PR already merged. Adding the runtime/namelist options is a feature enhancement that can come later. 

I personally wouldn't mind this to be always enabled instead of just in debug mode. It's lightweight and would be invaluable in debugging any issues.

Just my 2 cents.

**Comment by rljacob** [comment]
yes go ahead and merge this.

**Comment by rljacob** [comment]
@jonbob and @singhbalwinder please enter your reviews.

**Comment by worleyph** [comment]
@rljacob , this PR is still needs to be merged (or eliminated).

@amametjanov , you have not approved (or dis-approved) this. Please enter your vote.

@amametjanov , can you provide guidance on how to add a CIME-level control to enable/disable component-level process-to-node mapping output? I'm not sure that I have ever done this from scratch - I've only made changes to parameters that were already there. I guess such a thing would go into env_run.xml and affect drv_in and be implemented then in the CIME driver and then passed down to the components? Is there an example parameter that has been added recently that I could use as a template?

**Comment by worleyph** [comment]
@amametjanov , I was thinking of a single env_run.xml parameter, say COMPONENT_TASKMAP_OUTPUT (TRUE or FALSE), that would then set 
multiple drv_in parameters, e.g. 

atm_taskmap_output
lnd_taskmap_output,
rof_taskmap_output
ocn_taskmap_output
ice_taskmap_output
glc_taskmap_output

each of which would then be passed down to the appropriate component by the CIME driver. SMP_PRESENT is a build-time parameter, so not really the same type of thing. Any other suggestions? :-) . (@rljacob ? @jgfouca  ?)

**Comment by worleyph** [comment]
@rljacob , can this be merged now? It would make my life simpler to be able to add component-side support for the new env_run.xml parameter to master after this is already in there.

**Comment by rljacob** [comment]
merged to next.

Pat, I tested this with --compset A_WCYCL1850S --res ne30_oECv3_ICG on anvil and didn't see any new info output to the ocn or ice logs.

**Comment by worleyph** [comment]
@rljacob - where did you run? I'll give this a try myself.

**Comment by rljacob** [comment]
Anvil. Output is in /lcrc/group/acme/jacob/acme_scratch/anvil/Wne30next/run

**Comment by worleyph** [comment]
$ cd /lcrc/group/acme/jacob/acme_scratch/anvil/Wne30next/run
-bash: cd: /lcrc/group/acme/jacob/acme_scratch/anvil/Wne30next/run: Permission denied

Could you please change permissions? or create a tarball and put it some place that I can grab?

Thanks.

**Comment by worleyph** [comment]
@rljacob , fyi, I ran the same experiment on Anvil using next and I see task-to-node mapping information in ocn.log and ice.log (and atm.log and lnd.log and rof.log).

**Comment by rljacob** [comment]
I put the log files in /lcrc/group/acme/robsrunlogs.tar

I think maybe I had to do a clean rebuild of the mpas models.  Let me try that.

**Comment by rljacob** [comment]
Probably.  The output is there now.

**Comment by rljacob** [comment]
No issues showed up in testing.

**Comment by worleyph** [comment]
Thanks @rljacob

**Comment by rljacob** [comment]
This PR seems to be reason that 2 tests are failing on melvin.  Not sure why.
SMS.ne30_f19_g16_rx1.A.melvin_gnu
ERS.ne11_oQU240.I20TRCLM45.melvin_gnu

**Comment by worleyph** [comment]
Bummer - not sure how I can help debug, without access to Melvin. Works on all of the production platforms, though I haven't tried these specific tests. What is the nature of the failure?

**Comment by worleyph** [comment]
taskmap_write does involve MPI, identifying the nodes assigned to each component, but this is already used for the whole model, so there should be nothing new going on here except (maybe) a subset of the processes running the algorithm, on a subcommunicator. There are also some routines with optional parameters, which sometimes causes problems?

**Comment by rljacob** [comment]
I don't know.  Need to get @wadeburgess or @jgfouca involved in debugging this.

**Pull request merged**
