### PR TITLE
Solve gas_ac=NAN issue 

### LINKED ISSUE #6304: debugging run with the v3 output is pointing to a line in chemistry.F90
a debugging run with the v3 output is pointing to a line in chemistry.F90:
```
 forrtl: error (182): floating invalid - possible uninitialized real/complex variable.
 e3sm.exe           0000000000E8EC7A  chemistry_mp_chem        1590  chemistry.F90
```
This is the line:
`               gas_ac_layers(:ncol,1) = gas_ac_layers(:ncol,1) + gas_ac(:ncol,k)`

_Originally posted by @rljacob in https://github.com/E3SM-Project/E3SM/issues/6284#issuecomment-2012904911_

bug report from Rob regarding `SMS_D_Ld1.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-wcprod`

### PR DESCRIPTION
**Pull request by hsiangheleellnl**
Skip gas_ac calculation when nstep = 0.  Otherwise a run in debug mode would fail.

Fixes #6304.

[BFB]

### CODE REVIEW

**Comment by tangq** [comment]
@hsiangheleellnl , does this PR fix https://github.com/E3SM-Project/E3SM/issues/6304?

**Comment by hsiangheleellnl** [comment]
@tangq Thank you for clarifying that. The changes of this pull request fixed the issue #6304.

**Review by tangq — APPROVED** [review]
The changes look good to me.

**Comment by wlin7** [comment]
@hsiangheleellnl @tangq , thanks for the fix. The updated SSP test (via #6335) in debug mode (SMS_D_Ld1.ne30pg2_r05_IcoswISC30E3r5.WCYCLSSP370) also failed without this fix.

**Comment by wlin7** [comment]
Merged to next.

**Pull request merged**
