### PR TITLE
Remove P96 from pg2 test

### PR DESCRIPTION
**Pull request by whannah1**
Removes the processor specification for pg2 test and also remove settings in config_pesall.xml that forced 96 processors on any platform.

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
merged to next.

**Comment by rljacob** [comment]
@whannah1 its still picking up 96 procs.  Did you specify that in cime/config/e3sm/allactive/config_pesall.xml ?

**Comment by whannah1** [comment]
ah, yes I did. I forget why I felt the need to do that. 
Can I just remove the pg2 entries in that file entirely? Or does it need to have a value there?

**Comment by rljacob** [comment]
You can remove them.

**Comment by whannah1** [comment]
Done.

**Pull request merged**
