### PR TITLE
Add check for invalid fp-ops for GNU in debug mode

### PR DESCRIPTION
**Pull request by amametjanov**
Add check for invalid fp-ops for GNU in debug mode.
Also, fix ncol/pcol indexes in 2 eam-chemistry subroutines
(flagged by `-ffpe-trap=invalid`).

[non-BFB] - in fully-coupled tests

### CODE REVIEW

**Comment by amametjanov** [comment]
`e3sm_integration` runs with
- `-ffpe-trap=invalid` and array-inits within components in E3SM-Project/E3SM#5801: https://my.cdash.org/viewTest.php?buildid=2370878
- just `-ffpe-trap=invalid`: https://my.cdash.org/viewTest.php?buildid=2370876

**Comment by ndkeen** [comment]
I suppose this Fixes https://github.com/E3SM-Project/E3SM/issues/5647 in the sense that it adds the flags. But we still may have debugging to do for a few tests that might fail as result.

**Comment by rljacob** [comment]
Waiting on #5801 and #5811

**Review by amametjanov — COMMENTED** [review]
Rebased onto latest master and re-checked with `e3sm_integration`: https://my.cdash.org/viewTest.php?buildid=2411304 .

**Review by rljacob — APPROVED** [review]

**Pull request merged**
