### PR TITLE
switch default dycore to theta-l

### PR DESCRIPTION
**Pull request by oksanaguba**
Make theta-l default dycore.

Keep SCM test with preqx.

switch to tensor HV for most grids.

[nbfb] for most cime tests with atmosphere.

### CODE REVIEW

**Comment by oksanaguba** [comment]
Running integration suite, fails to address
```
[ac.onguba@blueslogin4 as]$ ./cs.status.20201023_123811_rg8vyn | grep "Overall: FAIL"
  ERS_Ln9_P96x1.ne4pg2_ne4pg2.F-MMF1.anvil_intel.eam-crmout (Overall: FAIL) details:
  ERS_Ln9_P96x1.ne4pg2_ne4pg2.F-MMF1-RCEMIP.anvil_intel (Overall: FAIL) details:
  ERS_Ln9_P96x1.ne4pg2_ne4pg2.F-MMFXX.anvil_intel (Overall: FAIL) details:
  SMS_B.ne4_ne4.F-EAMv1-AQP1.anvil_intel.eam-hommexx (Overall: FAIL) details:
  SMS_D_Ln5.conusx4v1_conusx4v1.FC5AV1C-L.anvil_intel (Overall: FAIL) details:
  SMS.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.anvil_intel.elm-bgcexp (Overall: FAIL) details:
  SMS.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_1850.anvil_intel.elm-bgcexp (Overall: FAIL) details:
  SMS_R_Ld5.ne4_ne4.FSCM5A97.anvil_intel (Overall: FAIL) details:



MMF1

[ac.onguba@blueslogin3 run]$ pwd
/home/ac.onguba/as/ERS_Ln9_P96x1.ne4pg2_ne4pg2.F-MMF1.anvil_intel.eam-crmout.C.20201023_123811_rg8vyn/run

vi atm.log.244460.201023-162341

nsplit was computed as  3.3333E-01 based on dtime    1200 and tstep  6.0000E+02, which is outside the divisibility tolerance. Set tstep so that it divides dtime.
 ERROR: timestep_make_parameters_consistent: divisibility error


MMF2


[ac.onguba@blueslogin3 run]$ cd ../../ERS_Ln9_P96x1.ne4pg2_ne4pg2.F-MMF1-RCEMIP.anvil_intel.C.20201023_123811_rg8vyn/run
[ac.onguba@blueslogin3 run]$ vi atm.log.244457.201023-162232 

nsplit was computed as  3.3333E-01 based on dtime    1200 and tstep  6.0000E+02, which is outside the divisibility tolerance. Set tstep so that it divides dtime.
 ERROR: timestep_make_parameters_consistent: divisibility error


MMF3 -- XX


cat /lcrc/group/acme/ac.onguba/acme_scratch/anvil/ERS_Ln9_P96x1.ne4pg2_ne4pg2.F-MMFXX.anvil_intel.C.20201023_123811_rg8vyn/bld/e3sm.bldlog.201023-161032

  The installed Kokkos configuration does not support CXX extensions. ??? or something else within kokkos build


CONUS

cd ../SMS_D_Ln5.conusx4v1_conusx4v1.FC5AV1C-L.anvil_intel.C.20201023_123811_rg8vyn/run/
vi e3sm.log.244279.201023-134742

 93: forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable SC2GCI when it is not allocated
 93:
 93: Image              PC                Routine            Line        Source
 93: e3sm.exe           000000000B9F8B16  Unknown               Unknown  Unknown
 93: e3sm.exe           00000000047118D2  compose_mod_mp_co         276  compose_mod.F90
 93: e3sm.exe           00000000031180BF  prim_driver_base_         608  prim_driver_base.F90
 93: e3sm.exe           000000000311206A  prim_driver_base_         124  prim_driver_base.F90
 93: e3sm.exe           00000000046D38ED  dyn_comp_mp_dyn_i         149  dyn_comp.F90
 93: e3sm.exe           0000000002E641D3  inital_mp_cam_ini          36  inital.F90
 93: e3sm.exe           00000000008677FC  cam_comp_mp_cam_i         155  cam_comp.F90
 93: e3sm.exe           0000000000823EB4  atm_comp_mct_mp_a         315  atm_comp_mct.F90
 93: e3sm.exe           0000000000465394  component_mod_mp_         257  component_mod.F90


SMS.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.anvil_intel.elm-bgcexp
cd ../../SMS.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.anvil_intel.elm-bgcexp.C.20201023_123811_rg8vyn/run/

a bunch of seaice log*err files, nothing in atm, e3sm, ocean, cpl. ice log ends with 'initializing mesh'.


SMS.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_1850.anvil_intel.elm-bgcexp
cd ../../SMS.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_1850.anvil_intel.elm-bgcexp.C.20201023_123811_rg8vyn/run/

tail ice.log.244291.201023-150255
...
WARNING: Variable landIceMask not in input file.
WARNING: Variable xtime not in input file.
WARNING: File /home/ccsm-data/inputdata/ice/mpas-cice/oEC60to30v3/mpassi.rst.BCRC_CNPECACNT_1850_anvil02.0066-01-01.no-xtime.180418.nc does not contain a seekable xtime variable. Forcing a read of the first time record.
 seaice_init: Initialize sea-ice model
  Initialize mesh...


SMS_R_Ld5.ne4_ne4.FSCM5A97.anvil_intel

cd ../../SMS_R_Ld5.ne4_ne4.FSCM5A97.anvil_intel.C.20201023_123811_rg8vyn/run/

in atm.log:
 INITIALIZE_RADBUFFER: ntoplw =           1  pressure:   12.3825413055617
 ERROR: read_inidat: SCM does not work with cam target theta-l.
```

**Comment by oksanaguba** [comment]
Diffs are
```
[ac.onguba@blueslogin4 as]$ ./cs.status.20201023_123811_rg8vyn | grep "Overall: DIFF"
  ERP_Ld3.ne30_oECv3_ICG.A_WCYCL1850S.anvil_intel (Overall: DIFF) details:
  ERP_Ln9.ne4_ne4.FC5AV1C-L.anvil_intel (Overall: DIFF) details:
  ERP_Ln9.ne4_ne4.F-EAMv1-AQP1.anvil_intel (Overall: DIFF) details:
  ERP_Ln9.ne4_ne4.F-EAMv1-RCEMIP.anvil_intel (Overall: DIFF) details:
  ERS_Ld5.ne4_ne4.FC5AV1C-L.anvil_intel.eam-gust_param (Overall: DIFF) details:
  ERS_Ld5.ne4_ne4.FC5AV1C-L.anvil_intel.eam-rrtmgp (Overall: DIFF) details:
  ERS_Ln9.ne4_ne4.FC5AV1C-L.anvil_intel (Overall: DIFF) details:
  ERS.ne11_oQU240.A_WCYCL1850.anvil_intel (Overall: DIFF) details:
  NCK.ne11_oQU240.A_WCYCL1850.anvil_intel (Overall: DIFF) details:
  PEM_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel (Overall: DIFF) details:
  PEM_Ln9.ne30_oECv3_ICG.A_WCYCL1850S.anvil_intel (Overall: DIFF) details:
  PET_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel.allactive-mach-pet (Overall: DIFF) details:
  PET_Ln9_PS.ne30_oECv3_ICG.A_WCYCL1850S.anvil_intel.allactive-mach-pet (Overall: DIFF) details:
  REP_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel (Overall: DIFF) details:
  SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.anvil_intel.allactive-v1cmip6 (Overall: DIFF) details:
  SMS_D_Ld1.ne30_r05_oECv3.A_WCYCL1850.anvil_intel (Overall: DIFF) details:
  SMS_D_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel (Overall: DIFF) details:
  SMS_D_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel.eam-cosplite_nhtfrq5 (Overall: DIFF) details:
  SMS_Ld1.ne4_ne4.F-EAMv1-AQP1.anvil_intel.eam-clubb_only (Overall: DIFF) details:
  SMS_Ln1.ne4_ne4.FC5AV1C-L.anvil_intel.eam-chem_pp (Overall: DIFF) details:
  SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.anvil_intel (Overall: DIFF) details:
  SMS_Ln9.ne4_ne4.FC5AV1C-L.anvil_intel.eam-outfrq9s (Overall: DIFF) details:
  SMS.ne4_ne4.FC5AV1C-L.anvil_intel.eam-cosplite (Overall: DIFF) details:
  SMS_P12x2.ne4_oQU240.A_WCYCL1850.anvil_intel.allactive-mach_mods (Overall: DIFF) details:
```

**Comment by rljacob** [comment]
@bogensch why can't SCM work with theta-l ?

**Comment by PeterCaldwell** [comment]
Peter B can answer better, but the crude answer is that SCM still needs the dycore to handle vertical advection and theta-l changes the variables the dycore expects to advect. Peter is working on a PR to address this.

**Comment by ambrad** [comment]
1. re: CONUS test error. PR #3897 fixes this error. The error occurs in debug builds for RRM atm.
2. re: "ERROR: timestep_make_parameters_consistent: divisibility error": The direct error is that dt_tracer_factor=6 by default, so 1200/(6*600) = 1/3. Here, dtime=1200 is anomalous relative to other ne4 tests; MMF compsets use a small ATM_NCPL, set in cime/src/drivers/mct/cime_config/config_component_e3sm.xml in this block:
```
      <!-- a shorter timestep is needed for stability in MMF compsets -->
      <!-- (i.e. super-parameterization, MMF, CRM) -->
      <value compset="_EAM%SP"       grid="a%ne4np4">96</value>
      <value compset="_EAM%SP.*ECPP" grid="a%ne4np4">72</value>
      <value compset="_EAM%MMF"      grid="a%ne4np4">96</value>
      <value compset="_EAM%MMF"      grid="a%ne4np4.pg2">72</value>
```
One solution is to add a testmods user_nl_eam file for each MMF test that sets dt_remap_factor=2, but perhaps there is a better approach.

**Comment by oksanaguba** [comment]
thanks, @ambrad ! I am getting back to this.

For MMF tests, @whannah1 , can we add testmod files? I don't see any other solution than that.

**Comment by oksanaguba** [comment]
More on config fails for MMFXX: one issue is here
```
    if (COMP_NAME STREQUAL "eam")
      if (USE_YAKL)
        target_link_libraries(${TARGET_NAME} PRIVATE yakl)
      endif()
      if (USE_SAMXX)
        target_link_libraries(${TARGET_NAME} PRIVATE samxx)
      endif()
    endif()
    if (USE_KOKKOS)
      target_link_libraries (${TARGET_NAME} Kokkos::kokkos)
    endif ()
``` 
where PRIVATE keyword is used above but not for kokkos. Cmake complains to make it consistent, either use keywords in all or in none:
```
CMake Error at cmake/build_model.cmake:252 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "atm".  All uses of target_link_libraries with a target must be
  either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * cmake/build_model.cmake:245 (target_link_libraries)
   * cmake/build_model.cmake:248 (target_link_libraries)

Call Stack (most recent call first):
  cmake/atm/CMakeLists.txt:1 (build_model)
```
More on PRIVATE is here : https://cmake.org/cmake/help/latest/command/target_link_libraries.html . Not sure what 'link interface' is.

**Comment by oksanaguba** [comment]
For kokkos build, CXX extensions warning is a distraction.

**Comment by oksanaguba** [comment]
There are a few RRM setups, but only 3 of them will run with theta, conus (after this PR), northamerica, and antarctica. The rest won't be properly set, but this is out of scope of this PR. Conus is needed for nightlies.

<mesh_file hgrid="ne0np4_arm_x8v3_lowcon"  >atm/cam/inic/homme/arm_x8v3_lowcon.g</mesh_file>
<mesh_file hgrid="ne0np4_conus_x4v1_lowcon"  >atm/cam/inic/homme/conusx4v1.g</mesh_file>
<mesh_file hgrid="ne0np4_northamericax4v1"  >atm/cam/inic/homme/northamericax4v1.g</mesh_file>
<mesh_file hgrid="ne0np4_antarcticax4v1"  >atm/cam/inic/homme/antarcticax4v1.g</mesh_file>
<mesh_file hgrid="ne0np4_svalbard_x8v1_lowcon"  >atm/cam/inic/homme/svalbardx8v1.g</mesh_file>
<mesh_file hgrid="ne0np4_sooberingoa_x4x8v1_lowcon"  >atm/cam/inic/homme/sooberingoax4x8v1.g</mesh_file>
<mesh_file hgrid="ne0np4_enax4v1">atm/cam/inic/homme/enax4v1.g</mesh_file>
<mesh_file hgrid="ne0np4_twpx4v1" >atm/cam/inic/homme/twpx4v1.g</mesh_file>

**Comment by oksanaguba** [comment]
Based on these results https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/1665434012/2020+7+Constant-coefficient+vs+Tensor+HV+results we will turn on tensor HV for theta-l by default (excluding ne30) and reduce HV scaling to 3.0.

**Comment by oksanaguba** [comment]
MMF tests are using Eulerian transport, so I kept it in testmods.

**Comment by mt5555** [comment]
additional changes added:  theta-l dycore will switch to tensorHV for all grids (simplifying the defaults).  

latest XML was tested with the preqx dycore for these tests (and all passed NLCOMP):

  SBN.ne4_oQU240
  SBN.ne45pg2_r05_oECv3
  SBN.ne30pg2_r05_EC30to60E2r2
  SBN.ne120_ne120
  SBN.ne256pg2_r0125_oRRS18to6v3
  SBN.ne1024pg2_r0125_oRRS18to6v3
  SBN.northamericax4v1pg2_r0125_northamericax4v1pg2

**Comment by oksanaguba** [comment]
@mt5555 -- did you fix SBN test? if so, should the fix be committed here?

**Comment by mt5555** [comment]
I didn't fix the test, but found a workaround by adding the --no-build option

**Comment by oksanaguba** [comment]
Running NL changes with PR #3962 result is below. Changes are only in theta dycore, in cases that (I think) are not used anyway.
```
Comparison failed between '/lcrc/group/acme/ac.onguba/acme_scratch/anvil/SMS.antarcticax4v1_r0125_antarcticax4v1.FC5AV1C-L.anvil_intel.allactive-thetadycore.C.20201125_183122_uox2qw/CaseDocs/atm_in' with '/home/ac.onguba/as/acme-tests/master/SMS.antarcticax4v1_r0125_antarcticax4v1.FC5AV1C-L.anvil_intel.allactive-thetadycore/CaseDocs/atm_in'
  BASE: hypervis_scaling = 3.0
  COMP: hypervis_scaling = 3

Comparison failed between '/lcrc/group/acme/ac.onguba/acme_scratch/anvil/SMS.conusx4v1_conusx4v1.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0.C.20201125_183122_uox2qw/CaseDocs/atm_in' with '/home/ac.onguba/as/acme-tests/master/SMS.conusx4v1_conusx4v1.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0/CaseDocs/atm_in'
Differences in namelist 'ctl_nl':
  BASE: hypervis_scaling = 3.2
  COMP: hypervis_scaling = 3
  BASE: nu = 8.0e-8
  COMP: nu = 3.4e-8
  BASE: nu_top = 2.5e5
  COMP: nu_top = 1e5

Comparison failed between '/lcrc/group/acme/ac.onguba/acme_scratch/anvil/SMS.enax4v1_enax4v1.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0.C.20201125_183122_uox2qw/CaseDocs/atm_in' with '/home/ac.onguba/as/acme-tests/master/SMS.enax4v1_enax4v1.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0/CaseDocs/atm_in'
Differences in namelist 'ctl_nl':
  BASE: hypervis_scaling = 3.2
  COMP: hypervis_scaling = 3
  BASE: nu = 8.0e-8
  COMP: nu = 3.4e-8

Comparison failed between '/lcrc/group/acme/ac.onguba/acme_scratch/anvil/SMS.ne1024np4_360x720cru_ne1024np4.FC5AV1C-L.anvil_intel.allactive-thetadycore.C.20201125_183122_uox2qw/CaseDocs/atm_in' with '/home/ac.onguba/as/acme-tests/master/SMS.ne1024np4_360x720cru_ne1024np4.FC5AV1C-L.anvil_intel.allactive-thetadycore/CaseDocs/atm_in'
Differences in namelist 'ctl_nl':
  BASE: dt_tracer_factor = 6
  COMP: dt_tracer_factor = 8
  BASE: hypervis_scaling = 0
  COMP: hypervis_scaling = 3
  BASE: hypervis_subcycle_q = 6
  COMP: hypervis_subcycle_q = 8
  BASE: nu = 2.5e10
  COMP: nu = 3.4e-8
  BASE: se_tstep = 10
  COMP: se_tstep = 9.375

Comparison failed between '/lcrc/group/acme/ac.onguba/acme_scratch/anvil/SMS.ne11_ne11.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0.C.20201125_183122_uox2qw/CaseDocs/atm_in' with '/home/ac.onguba/as/acme-tests/master/SMS.ne11_ne11.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0/CaseDocs/atm_in'
Differences in namelist 'ctl_nl':
  BASE: hypervis_scaling = 0
  COMP: hypervis_scaling = 3
  BASE: nu = 2.0e16
  COMP: nu = 3.4e-8

Comparison failed between '/lcrc/group/acme/ac.onguba/acme_scratch/anvil/SMS.ne120_ne120.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0.C.20201125_183122_uox2qw/CaseDocs/atm_in' with '/home/ac.onguba/as/acme-tests/master/SMS.ne120_ne120.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0/CaseDocs/atm_in'
Differences in namelist 'ctl_nl':
  BASE: hypervis_scaling = 0
  COMP: hypervis_scaling = 3
  BASE: nu = 1.5e13
  COMP: nu = 3.4e-8

Comparison failed between '/lcrc/group/acme/ac.onguba/acme_scratch/anvil/SMS.ne16_ne16.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0.C.20201125_183122_uox2qw/CaseDocs/atm_in' with '/home/ac.onguba/as/acme-tests/master/SMS.ne16_ne16.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0/CaseDocs/atm_in'
Differences in namelist 'ctl_nl':
  BASE: hypervis_scaling = 0
  COMP: hypervis_scaling = 3
  BASE: nu = 7.0e15
  COMP: nu = 3.4e-8

Comparison failed between '/lcrc/group/acme/ac.onguba/acme_scratch/anvil/SMS.ne240_ne240.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0.C.20201125_183122_uox2qw/CaseDocs/atm_in' with '/home/ac.onguba/as/acme-tests/master/SMS.ne240_ne240.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0/CaseDocs/atm_in'
Differences in namelist 'ctl_nl':
  BASE: hypervis_scaling = 0
  COMP: hypervis_scaling = 3
  BASE: nu = 1.9e12
  COMP: nu = 3.4e-8

Comparison failed between '/lcrc/group/acme/ac.onguba/acme_scratch/anvil/SMS.ne45pg2_r05_oECv3.FC5AV1C-L.anvil_intel.allactive-thetadycore.C.20201125_183122_uox2qw/CaseDocs/atm_in' with '/home/ac.onguba/as/acme-tests/master/SMS.ne45pg2_r05_oECv3.FC5AV1C-L.anvil_intel.allactive-thetadycore/CaseDocs/atm_in'
  BASE: hypervis_scaling = 3.0
  COMP: hypervis_scaling = 3

Comparison failed between '/lcrc/group/acme/ac.onguba/acme_scratch/anvil/SMS.ne512np4_360x720cru_ne512np4.FC5AV1C-L.anvil_intel.allactive-thetadycore.C.20201125_183122_uox2qw/CaseDocs/atm_in' with '/home/ac.onguba/as/acme-tests/master/SMS.ne512np4_360x720cru_ne512np4.FC5AV1C-L.anvil_intel.allactive-thetadycore/CaseDocs/atm_in'
Differences in namelist 'ctl_nl':
  BASE: dt_tracer_factor = 6
  COMP: dt_tracer_factor = 8
  BASE: hypervis_scaling = 0
  COMP: hypervis_scaling = 3
  BASE: hypervis_subcycle_q = 6
  COMP: hypervis_subcycle_q = 8
  BASE: nu = 2.0e11
  COMP: nu = 3.4e-8
  BASE: se_tstep = 20
  COMP: se_tstep = 18.75

Comparison failed between '/lcrc/group/acme/ac.onguba/acme_scratch/anvil/SMS.northamericax4v1_r0125_northamericax4v1.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0.C.20201125_183122_uox2qw/CaseDocs/atm_in' with '/home/ac.onguba/as/acme-tests/master/SMS.northamericax4v1_r0125_northamericax4v1.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0/CaseDocs/atm_in'
  BASE: hypervis_scaling = 3.0
  COMP: hypervis_scaling = 3

Comparison failed between '/lcrc/group/acme/ac.onguba/acme_scratch/anvil/SMS.ne4_ne4.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0.C.20201125_183122_uox2qw/CaseDocs/atm_in' with '/home/ac.onguba/as/acme-tests/master/SMS.ne4_ne4.FC5AV1C-L.anvil_intel.eam-thetahy_ftype0/CaseDocs/atm_in'
Differences in namelist 'ctl_nl':
  BASE: hypervis_scaling = 0
  COMP: hypervis_scaling = 3
  BASE: nu = 5.0e17
  COMP: nu = 3.4e-8
```

**Comment by whannah1** [comment]
@oksanaguba Sorry I'm late to respond here. We can simply change the MMF time step to be compatible. We've found that we just can't set it as long as we would for the non-MMF configurations. I've settled on a 20 min physics time step as a good compromise, but it's perfectly reasonable to change the default to 15 or 10. I've seen a lot more intermittent failures when using a 30 min time step, so I'd like to avoid that. 

Although... if we just change the ATM_NCPL value to be higher then we'll be using a smaller dynamics time step, which is unnecessary. It would be nice to have a special default for any MMF case where the physics and dynamics time steps are just the same for any grid  (to make the testing simple), and then just requiring anyone using a finer grid to know that they need to alter the time step settings. I don't know how we do that though.

**Comment by mt5555** [comment]
Regarding ATM_NCPL:  if the MMF is using the theta-l dycore, then the new settings specify the dycore timesteps independent of the physics timstep.  So changeing ATM_NCPL will not effect the dycore timesteps.

**Comment by oksanaguba** [comment]
Right now my solution in this PR is to use parameters from the current MMF tests, including Euler transport, but changing dycore only. If needed, someone can revisit these tests later. It is out of scope of this PR.

**Comment by oksanaguba** [comment]
e3sm_integration for commit 528eec2:
```
[ac.onguba@blueslogin2 as]$ ./cs.status.20201201_161305_wj80ik | grep "Overall: FAIL"
  ERP_Ld3.ne30_oECv3_ICG.A_WCYCL1850S.anvil_intel (Overall: FAIL) details:
  SMS_B.ne4_ne4.F-EAMv1-AQP1.anvil_intel.eam-hommexx (Overall: FAIL) details:
  SMS_D_Ln5.conusx4v1_conusx4v1.FC5AV1C-L.anvil_intel (Overall: FAIL) details:
  SMS.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.anvil_intel.elm-bgcexp (Overall: FAIL) details:
  SMS.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_1850.anvil_intel.elm-bgcexp (Overall: FAIL) details:
```
ERP fail is a random anvil fail, resubmitted. hommexx build fail is expected, conus fail is fixed separately, BGC tests were failing  on anvil before but not anymore. 

I will revert changes to BGC tests to switch them to theta-l as well.

**Comment by oksanaguba** [comment]
ERP test failed again due to anvil issues. BGC tests won't run from this branch.

I suggest this is ready, in case these 3 tests are failing after merge, I will fix them separately.

**Review by mt5555 — APPROVED** [review]

**Comment by oksanaguba** [comment]
in next

**Pull request merged**
