### PR TITLE
Added single cell test case

### PR DESCRIPTION
**Pull request by akturner**
Updated single cell namelist file
Added single cell test case with simple plotting of results
Updated data download script

Fixes https://github.com/E3SM-Project/E3SM/issues/4619

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
@akturner please respond to above question.

**Comment by rljacob** [comment]
@akturner still needs response to reviewer question.

**Comment by akturner** [comment]
Instructions in components/mpas-seaice/testing_and_setup/testcases/single_cell/README

**Review by jonbob — APPROVED** [review]
From visual inspection, none of the changes are to code used by E3SM -- but I'll also test it before merging.

**Comment by jonbob** [comment]
Passes sanity testing, merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
