### PR TITLE
Fix allocations errors in RRTMGP for DEBUG mode

### PR DESCRIPTION
**Pull request by brhillman**
Fix allocation errors in RRTMGP interface code to enable running with DEBUG=True. These fixes do not seem to affect runs configured with DEBUG=False (RRTMGP tests are BFB), but without these fixes runs configured with DEBUG=True will fail.

[BFB]

### CODE REVIEW

**Comment by ndkeen** [comment]
Wasn't this only failing with GNU and DEBUG=TRUE?

**Comment by brhillman** [comment]
No it was failing with intel as well I believe. We do not do a debug test with any compiler (just one RRTMGP test in the test suite).

**Comment by ndkeen** [comment]
OK. NBD, but when I reported this to you, it was only failing with GNU & DEBUG for me. Just a shout out to the benefits of testing with more compilers.

**Comment by brhillman** [comment]
@ndkeen yes I remember, but I thought I remembered then trying with Intel and it failing as well. But that may have been after fixing one of the bugs showing up with GNU, which could have exposed another with Intel. At some point in this process DEBUG with Intel was failing as well though. And yup, I'll echo your praises for the benefits of testing with multiple compilers. I've found lots of stuff with GNU that didn't show up with Intel and vice versa.

**Comment by ndkeen** [comment]
Probably should not argue about something so easy to test. I just ran

`SMS_D_Lh6_P16x1.ne4_ne4.FC5AV1C-L.cori-knl_intel.cam-rrtmgp` 

with current master and it completes. With GNU it will fail.

With this branch, the following tests complete:

```
SMS_D_Lh6_P64x1.ne4_ne4.FC5AV1C-L.cori-knl_gnu.cam-rrtmgp
SMS_D_Lh6_P64x1.ne4_ne4.FC5AV1C-L.cori-knl_intel.cam-rrtmgp

SMS_Lh6_P64x1.ne4_ne4.FC5AV1C-L.cori-knl_gnu.cam-rrtmgp
SMS_Lh6_P64x1.ne4_ne4.FC5AV1C-L.cori-knl_intel.cam-rrtmgp
```

I note it "completes" as I'm not saying anything about the results.

I will approve, but based only on the above tests.

**Comment by singhbalwinder** [comment]
Merged to next

**Pull request merged**
