### PR TITLE
Update MPAS source for standalone time-varying forcing

### PR DESCRIPTION
**Pull request by xylar**
This pull request adds capability for stand-alone MPAS-Ocean to include time varying wind and pressure forcing. The added code is not called during E3SM simulations. Also adds associated COMPASS files for testing.

[BFB]

### CODE REVIEW

**Comment by xylar** [comment]
## Testing
Commits related to time-varying forcing were merged locally, tested by @mark-petersen  in E3SM with a variety of tests.  Passes:
```
PASS ERS_Ld3.T62_oQU240.GMPAS-IAF.cori-knl_intel RUN time=228
PASS PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel RUN time=202
PASS PEM_Ln9.ne30_oECv3wLI.A_WCYCL1850-DIB-ISMF_CMIP6.cori-knl_gnu RUN time=621
PASS SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu RUN time=715
PASS SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel RUN time=3080
```

COMPASS changes have no affect on any code involved in E3SM runs.

**Comment by xylar** [comment]
@jonbob, let me know if you are able to take this from here.  This is my first E3SM pull request so be gentle :-)

**Comment by mark-petersen** [comment]
@xylar thanks for pitching in on something new. I'm testing this exact commit now.

I didn't even look at email yesterday. After an hour of sickening turbulence, our pilot announced that we couldn't land in Santa Fe, and we turned around and went right back to Denver.

**Comment by mark-petersen** [comment]
FYI, E3SM developers typically push a PR branch named e.g. 
`xylar/ocean/add_standalone_mpaso_wind_pressure_forcing`
to E3SM-Project/E3SM rather than our individual forks.  

@rljacob, is that a preference by the workflow team, or just what people typically do?

**Comment by xylar** [comment]
> FYI, E3SM developers typically push a PR branch named e.g.

Thanks, I'm aware of that but then there was a complaint awhile back that there were over 500 branches. I figured I would do what I could to not add to that clutter.

**Comment by xylar** [comment]
> After an hour of sickening turbulence, our pilot announced that we couldn't land in Santa Fe, and we turned around and went right back to Denver.

That definitely doesn't sound like fun.  Better luck today, I hope.

**Comment by rljacob** [comment]
Developers can use direct branches or forks.  We're trying to shift to forks.

**Comment by jonbob** [comment]
@xylar - does this PR have more COMPASS changes or just the ones we have previously brought in?

**Comment by xylar** [comment]
@jonbob, I can split these into different PRs, but not right away since I'm at the GPU Hackathon this week.

> does this PR have more COMPASS changes or just the ones we have previously brought in?

I'm not sure I understand the question.  @mark-petersen  has tested thee COMPASS changes that are related to the time-varying standalone forcing: https://github.com/MPAS-Dev/MPAS-Model/pull/123#issuecomment-469720815

All changes including the COMPASS changes related to mesh generation were then tested by @mark-petersen in the tests above where he approved the PR.

**Comment by jonbob** [comment]
I guess I'm just trying to understand if this PR really contains two separate features or one with support for it. I understand that at least some of the COMPASS changes are related to the time-varying standalone forcing -- but there are also separate grid generation updates? If so, we do probably need two PR's: one for time-varying forcing (plus its testing) and a different one for grid generation.

**Comment by xylar** [comment]
Yep, there are 2 separate concept here.  @mark-petersen gave me the sense that they could be bundled because E3SM is affected in no way by either of these but it's fine with me to separate them.

**Comment by xylar** [comment]
@jonbob, I left a phone message which I'm sure you'll get but feel free to call me back on my cell if you have time to discuss this either this evening or tomorrow.  I'm not sure how to put `MPAS-Dev/MPAS-Model/e3ms/devleop` in a useful state for this PR.  It seems like maybe I should have merged `ocean/develop` into `e3sm/develop` with only some and not all of these commits, then made this PR, then merged the rest of the commits into `ocean/develop`, then merged `ocean/develop` into `e3sm/develop`, then made a second PR here.  That seems like a nutty workflow to me.  It means we can only advance `ocean/develop` at a pace compatible with E3SM.

**Comment by mark-petersen** [comment]
@xylar I backed up e3sm/develop to only merge in the atmospheric forcing change, not the V2 mesh changes.  Sorry for the trouble.

**Comment by xylar** [comment]
@mark-petersen, oh, are we okay with editing the history of `e3sm/develop`?  I assumed that was strictly off limits.  But I agree that it's the cleanest solution if it's not.

I assume you need me to reset the submodule here to point to the current `e3sm/develop`?

**Comment by xylar** [comment]
@jonbob, @mark-petersen has merged only the time-varying wind forcing and related COMPASS test case to `e3sm/develop`.  I have updated this PR accordingly and updated mpas-source to point to the new head of `MPAS-Dev/MPAS-Model/e3sm/develop`

**Comment by xylar** [comment]
Sorry, @mark-petersen, I didn't notice that you had also updated this branch.  But I think no harm done, since I needed to fix the commit message, too.

**Comment by jonbob** [comment]
Thanks @xylar - I'll get this into the repo as soon as it's available. Please feel free to create a new PR with the second set of updates and we'll get that in the queue as well.

**Comment by jonbob** [comment]
@mark-petersen - shouldn't this be going in via an update to MPAS-Dev/MPAS-Model?

**Comment by mark-petersen** [comment]
> shouldn't this be going in via an update to MPAS-Dev/MPAS-Model?

I should have pointed to this PR: https://github.com/MPAS-Dev/MPAS-Model/pull/123, which has lengthy discussions and revisions. That was the update into MPAS-Dev/MPAS-Model, and this is just the corresponding update of the E3SM submodule.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master. @xylar _ I believe you can now delete that branch from your fork. I usually delete branches from E3SM once the PR's are fulfilled, to keep the branch count from growing.

**Comment by xylar** [comment]
Thanks, @jonbob!

**Pull request merged**
