### PR TITLE
update path to cprnc on Cori

### PR DESCRIPTION
**Pull request by mt5555**
update path to cprnc on Cori for standalone HOMME builds

[BFB]

### CODE REVIEW

**Comment by AaronDonahue** [comment]
@mt5555 , since this is a machine file change should I wait for a review from say @ndkeen , or go ahead and start merging it?

**Comment by mt5555** [comment]
it's a 1 line change - I think you can merge it directly to next and master, and skip integration.

**Review by ndkeen — APPROVED** [review]

**Comment by rljacob** [comment]
@AaronDonahue go ahead and merge this.  No impact on WC.

**Comment by AaronDonahue** [comment]
@rljacob , excellent.  Done.

**Comment by AaronDonahue** [comment]
Since this is just a machine file change can I go ahead and merge to master?  Even though master has been closed for awhile now?

**Comment by rljacob** [comment]
Yes go ahead.

**Comment by AaronDonahue** [comment]
@mt5555 , this has now been merged to master.  Just giving you a heads up in case you want to delete the branch from your fork.

**Pull request merged**
