### PR TITLE
Disable land ice frazil salinity

### PR DESCRIPTION
**Pull request by cbegeman**
The option to have non-zero land ice frazil salinity was not fully supported. Here, we remove that option. This is BFB when land ice frazil salinity is zero, which has been the case in every configuration I am aware of.

See https://github.com/E3SM-Ocean-Discussion/E3SM/pull/91 for further discussion.

[NML]
[BFB]

### CODE REVIEW

**Review by xylar — APPROVED** [review]
This looks exactly like what we want.  Thanks @cbegeman!

**Review by darincomeau — APPROVED** [review]
Passes e3sm_cryo_developer test suite.

Approved based on testing and visual inspection.

Thanks @cbegeman !

**Review by jonbob — APPROVED** [review]
Approved based on checking bld file changes with semi-automated scripts and testing

**Comment by jonbob** [comment]
Passes:
* SMS_D_Ld1.TL319_IcoswISC30E3r5.GMPAS-JRA1p5-DIB-PISMF.chrysalis_intel.mpaso-jra_1958
* ERS_Ld5.T62_oQU120.CMPASO-NYF.chrysalis_intel

with expected NML DIFFs. Merged to next

**Comment by jonbob** [comment]
merged to master and expected NML DIFFs blessed -- except for pm-cpu prod and pm-cpu developer_gnu which have yet to report

**Comment by jonbob** [comment]
Also blessed NML DIFFs on pm-cpu prod and pm-cpu developer_gnu

**Pull request merged**
