### PR TITLE
Fix scorpio submodules after bad merge

### PR DESCRIPTION
**Pull request by brhillman**
Fix SHA1s for scorpio submodules after a bad merge to next and master
from PR #3832. This PR inadvertently changed these submodules to point
to older versions, so we reset the SHA1s to the correct versions here.

[BFB]

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
This PR reverts (to fix the bad merge as mentioned in the PR description above) to the latest version of Scorpio merged in PR #3831 .

**Review by jayeshkrishna — APPROVED** [review]

**Review by ambrad — APPROVED** [review]
This looks right to me.

**Review by rljacob — APPROVED** [review]

**Comment by brhillman** [comment]
Merged to next.

**Comment by jayeshkrishna** [comment]
Please don't forget to follow the commit message guidelines when merging changes to next/master (PR info, BFB info etc)

**Comment by brhillman** [comment]
@jayeshkrishna I think I just missed the BFB label in the merge, the rest should be correct. Do I need to re-merge to next to have the BFB label in there?

**Comment by jayeshkrishna** [comment]
I think it is ok (no remerge to next needed), but its @rljacob 's call

**Comment by rljacob** [comment]
Just make sure its in the master merge commit message.

**Comment by brhillman** [comment]
@rljacob no problem. Thanks!

**Comment by brhillman** [comment]
Merged to master.

**Pull request merged**
