### PR TITLE
ARKode-HOMME Interface

### PR DESCRIPTION
**Pull request by cjvogl**
This PR allows the user to enable an interface to ARKode (https://computation.llnl.gov/projects/sundials/arkode) in HOMME-NH. This allows for rapid implementation and testing of Additive Runge-Kutta methods within the HOMME-NH dycore. The interface code is wrapped in ifdef directives that evaluate to false by default, so these changes should be BFB unless the interface is enabled (via a flag to CMake).

### CODE REVIEW

**Comment by mt5555** [comment]
@cjvogl : I was about to merge this, but I noticed it has about 500 whitespace diffs throughout the code - something like the editor you use automatically fixes things like removing extra spaces at the end of a line.  But it creates a lot of trivial diffs making the PR hard to review. 

I found how to remove these on stackoverflow, which I did, but the procedure I used meant that all the commits will now be unfairly attributed to me instead of you.   Can you try the following, which will make a new branch without all the whitespace diffs:  (you can see my version of this in my branch:  mt5555/newarkode ) .   (ref: https://stackoverflow.com/questions/3515597/add-only-non-whitespace-changes/7149602#7149602 )

This does have the drawback of squashing all the commits and loosing all your previous commit messages.  


# get the "merge base" for this branch:
git checkout cjvogl/nonhydro/homme/lorenz2+arkode
git merge-base HEAD origin/master

output:  b3a0e50899ed5861a4a3802559559c6f5375c10d

# make a new branch at the merge-base:  
git checkout -b newarkode  b3a0e50899

# apply all the changes on nonhydro/homme/lorenz2+arkode *except* the whitepsace changes  to newarkode:

git diff -U0 -w --no-color ..nonhydro/homme/lorenz2+arkode | git apply --ignore-whitespace --unidiff-zero

#commit changes:
git add components/homme/src/arkode
git commit

# verify that the only differences between "newarkode" and "nonhydro/homme/lorenz2+arkode" are white space changes:
git diff nonhydro/homme/lorenz2+arkode

# push branch to github and make a new PR.
# (or force push and overwrite nonhydro/homme/lorenz2+arkode )
git push cjvogl newarkode

**Comment by mt5555** [comment]
One additional request:
there seem to be a strange regression in dcmip12_wrapper.F90.  Can you revert that to what it is master:

git checkout master -- components/homme/src/test_src/dcmip12_wrapper.F90

**Comment by cjvogl** [comment]
@mt5555, thanks for all the work on this.  I just pushed the changes from https://github.com/mt5555/E3SM/pull/3 that we discussed, including a refactor of `set_state_i` to avoid `pressure_thickness` from accessing arrays out-of-bounds.

**Comment by mt5555** [comment]
sorry - I should have updated this PR - I merged this to next yesterday.  
I'll remerge today to pick up these new changes.

**Comment by mt5555** [comment]
merged to next.

**Pull request merged**
