### PR TITLE
Update mpas-source: Improved sea ice column error messages

### PR DESCRIPTION
**Pull request by akturner**
Improved error messages generated by errors in the sea ice column vertical physics routines.
Adds https://github.com/MPAS-Dev/MPAS-Model/pull/801

[BFB]

Fixes https://github.com/E3SM-Project/E3SM/issues/4088

### CODE REVIEW

**Review by proteanplanet — APPROVED** [review]
This is tentatively approved, however it should include testing in an E3SM B-case for a full annual cycle to make sure there are no unforeseen issues. This is because it includes changes to the column thermodynamics code. The test can be completed on the lowest resolution ice-ocean mesh for brevity, but must include a full annual cycle.

**Comment by jonbob** [comment]
merged to next - passed sanity testing. @akturner - just for next time, the branch naming convention should include your git user name as well, so something like akturner/seaice/improved_column_error_messages

**Comment by jonbob** [comment]
I'll leave a longer run going overnight, as requested by the reviewer

**Comment by jonbob** [comment]
merged to master. Both automated testing and a longer run overnight were successful

**Pull request merged**
