### PR TITLE
create_test: Add new single-exe option

### PR DESCRIPTION
**Pull request by jgfouca**
Allows for all cases to share a single build.

[BFB]

### CODE REVIEW

**Comment by jgfouca** [comment]
@oksanaguba , can you give this a try and see if it speeds up your HOMME testing on chama?

**Comment by jgfouca** [comment]
@oksanaguba bump

**Comment by rljacob** [comment]
How could we use this in our test suites?  We might need 3 executables instead of one.  Some new way of organizing/parsing tests.py?

**Comment by oksanaguba** [comment]
Jim did this per my request -- we are getting new code for different ftypes (coupling mechanisms) in EAM. I want to get new ftypes tested, they do not need new builds (2 different dycore targets for 4 different ftypes), so, this pr will significantly reduce build time.

**Comment by rljacob** [comment]
I've been asking for this too.  To speed up test suite runs.

**Comment by jgfouca** [comment]
@rljacob , @oksanaguba , we could potentially make better use of this feature by adding an additional field to each test entry in the suite definitions to indicate build compatibility.

**Comment by rljacob** [comment]
Sounds good.  That could wait for another PR.

Will I be able to use this option with create_newcase?

**Comment by jgfouca** [comment]
Hey @oksanaguba , I'd like to merge this soon.

**Pull request merged**
