### PR TITLE
Switching default I/O library to Scorpio

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Switching the default I/O library from Scorpio classic
to Scorpio

Also updating Scorpio to the latest version (1.1.0)

[BFB]

### CODE REVIEW

**Comment by dqwu** [comment]
e3sm_integration test suite run on anlworkstation recently shows no test that passes with scorpio classic but fails with scorpio.

**Comment by jayeshkrishna** [comment]
Integration test results from Anvil on this branch,

Scorpio classic (generate): https://my.cdash.org/buildSummary.php?buildid=1796884
Scorpio (compare with Scorpio classic results): https://my.cdash.org/buildSummary.php?buildid=1796882

The FAIL results need a little explanation (below),

ERS_Ld3.f45_f45.ICLM45ED.anvil_intel.clm-fates : DIFF (hopefully will be handled by https://github.com/E3SM-Project/E3SM/issues/3461)
PET.f45_g37_rx1.A.anvil_intel.allactive-mach-pet : DIFF (The test failed with scorpio classic, but now passes)
SMS.f09_g16_a.MALI.anvil_intel : FAIL (The test fails with Scorpio classic too)
SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.anvil_intel.allactive-v1cmip6 : FAIL (The test fails with Scorpio classic too)
SMS_D_Ld1.ne30_r05_oECv3.A_WCYCL1850.anvil_intel : FAIL (The test fails with Scorpio classic too)

**Comment by sarich** [comment]
@jayeshkrishna 
I believe this commit is causing next to hang on bebop

**Comment by dqwu** [comment]
@sarich 
Which test? Does it work on other machines?

**Comment by sarich** [comment]
@dqwu 
ERS.f09_g16.I1850CLM45CN.bebop_intel + 17 others. Look at the differences in the cdash board 3/27 and 3/29. The other machines look ok

https://my.cdash.org/viewTest.php?buildid=1798267&onlyfailed

**Comment by dqwu** [comment]
@jayeshkrishna 
For LCRC, I only have allocations on Anvil so far. It seems that the hanging issue is not reproducible on Anvil.

If you have allocations on Bebop, could you manually run one of the timeout (walltime 30 mins) tests, such as ERS.f09_g16.I1850CLM45CN.bebop_intel? That test only took 3m 54s run time before so you can use a shorter walltime (e.g. 10 mins). It might hang in one of the scorpio functions.

**Comment by dqwu** [comment]
@jayeshkrishna 
You might just try ERS.f19_f19.ICLM45.bebop_intel, it only took 1m 18s run time before.

**Comment by dqwu** [comment]
@jayeshkrishna @sarich 
Rob has reminded me that I should be able to run on bebop, so I will look into this issue.

The first thing I have noticed is that the default PnetCDF version on bebop is 1.6.1
`  Setting Environment PNETCDF_PATH=/soft/bebop/parallel-netcdf/1.6.1`

Looking at issue #3383, it seems that there are no PnetCDF 1.8.1 or higher versions on bebop so far. I will try to reproduce the hanging issue on bebop and see if it can be fixed by installing and using some custom versions of PnetCDF (1.8.1 or higher).

**Comment by dqwu** [comment]
@jayeshkrishna 
Some updates:
1) Bebop is using Lmod, and parallel-netcdf modules already include 1.8.1 and higher versions
2) ERS.f19_f19.ICLM45 can pass with scorpio classic
3) ERS.f19_f19.ICLM45 seems to hang with scorpio, even using PnetCDF 1.8.1

I will continue to find out why that test hangs in scorpio code.

**Comment by dqwu** [comment]
@jayeshkrishna 
By debugging on test ERS.f19_f19.ICLM45, I have found out that the place of hanging is a call to pio_swapm() inside rearrange_comp2io(). Note that pio_swapm calls the default MPI_Alltoallw (or its variations with flow control options).
```
int rearrange_comp2io(...)
{
    ...
    /* Data in sbuf on the compute nodes is sent to rbuf on the ionodes */
    LOG((2, "about to call pio_swapm for sbuf"));
    if ((ret = pio_swapm(sbuf, sendcounts, sdispls, sendtypes,
                         rbuf, recvcounts, rdispls, recvtypes, mycomm,
                         &iodesc->rearr_opts.comp2io)))
    ...
}
```
[More information]
1) compiler="intel" mpilib="mvapich" seems to work (no hanging)

2) compiler="intel" mpilib="impi" does not work (hanging) with default intel-mpi/2017.3
However, if PIO_REARRANGER is SUBSET and PIO_STRIDE is 1 (essentially no rearrange is performed), there is no hanging issue.

3) The hanging issue can be reproduced on Bebop with scorpio's performance replay tool
on a small decomposition file (dumped from a run of the same test with 16 tasks on anlworkstation) .
```
MPI version: default intel-mpi/2017.3
Decomposition: 360 x 720, npes 16, ndims 2, 
MPI tasks: 16
IO tasks: 4
PIO stride: 4
nvars: 25
rearranger: BOX
```
Not reproducible with intel-mpi/2018.4 (latest version is intel-mpi/2019.4)

[My view]
This is likely a bug related to MPI_Alltoallw with intel MPI 2017.3 (reproducible with scorpio's replay tool on a small dataset), seems to have been fixed by intel MPI 2018.4

[Suggested fix]
Upgrade intel-mpi from 2017.3 to 2018.4

**Comment by dqwu** [comment]
@sarich 
To fix the hanging issue on bebop with scorpio, you might have to update cime/config/e3sm/machines/config_machines.xml to use intel-mpi/2018.4 or higher versions.

You can take this opportunity to upgrade module versions for intel, intel-mkl, netcdf, netcdf-fortran, hdf5, intel-mpi, mvapich2 and parallel-netcdf.

Below are some recommended module changes for bebop. The dependencies still need to be checked with "module spider".
```
       <modules compiler="intel">
-        <command name="load">intel/17.0.4-74uvhji</command>
-        <command name="load">intel-mkl/2017.3.196-jyjmyut</command>
-        <command name="load">netcdf/4.4.1.1-prsuusl</command>
-        <command name="load">netcdf-fortran/4.4.4-ojwazvy</command>
+        <command name="load">intel/18.0.4-443hhug</command>
+        <command name="load">intel-mkl/2018.4.274-jwaeshj</command>
+        <command name="load">hdf5/1.10.5-3mk3uik</command>
+        <command name="load">netcdf/4.7.0-krelxcz</command>
+        <command name="load">netcdf-fortran/4.4.5-74lj75q</command>
       </modules>
       <modules compiler="intel" mpilib="impi">
-        <command name="load">intel-mpi/2017.3-dfphq6k</command>
-        <command name="load">parallel-netcdf/1.6.1</command>
+        <command name="load">intel-mpi/2018.4.274-4hmwfl6</command>
+        <command name="load">parallel-netcdf/1.11.0-acswzws</command>
       </modules>
       <modules compiler="intel" mpilib="mvapich">
-        <command name="load">mvapich2/2.2-n6lclff</command>
-        <command name="load">parallel-netcdf/1.6.1-mvapich2.2</command>
+        <command name="load">mvapich2/2.3.1-verbs-omjz3ck</command>
+        <command name="load">parallel-netcdf/1.11.2-7fy6qz3</command>
```

**Comment by sarich** [comment]
@dqwu 
I'll try updating the modules and make sure everything still works

**Comment by dqwu** [comment]
@sarich 
Since you are OK with the module upgrades for bebop, I can push a new commit to this PR.

Before merging it to next, we should make sure that the hanging issue is fixed on bebop. We need to check BFB test results. "intel + mvapich" should also be tested with upgraded modules.

**Comment by sarich** [comment]
@dqwu
Ok, sounds good to me

**Comment by dqwu** [comment]
@sarich @jayeshkrishna 
I have run some BFB tests on bebop with e3sm_developer suite (compiler=intel mpilib=impi).
I used current master branch (with default scorpio classic) to generate baselines.

7 tests failed with DIFFs, but there are no hanging (timeout) tests.

See https://my.cdash.org/viewTest.php?onlyfailed&buildid=1803797

**Comment by dqwu** [comment]
@jayeshkrishna @sarich 
It seems that the DIFFs are caused by upgraded modules. Using scorpio classic and the new modules, we also get the same 7 tests failed with DIFFs:
https://my.cdash.org/viewTest.php?onlyfailed&buildid=1803797

**Comment by rljacob** [comment]
Yes the compiler version was updated so some diffs are expected.

**Comment by dqwu** [comment]
@jayeshkrishna 
E3SM will be moving towards integration CIME via submodule soon.
Only a few last E3SM cime splits will be merged to CIME.
Not sure how it might affect the change of config_machines.xml in this PR.

**Comment by rljacob** [comment]
What is the status of fixing ERIO.ne30_g16_rx1.A.melvin_gnu ?

**Comment by dqwu** [comment]
@rljacob 
Jayesh can recreate (to some extent) the issue with the ERIO test (that fails on melvin), on anlworkstation. He has some information so far:
> It looks like an issue with netcdf4p (still need to debug version of hdf5 with issue etc). On anlworkstation it always worked, and apparently it was because of the ugly switch in Scorpio to try NetCDF when NetCDF4P fails to open files, on melvin the tests crash but on anlworkstation the tests pass (due to retry) - need to investigate further on why it happens though.

**Comment by rljacob** [comment]
ERIO.ne30_g16_rx1.A.sandiatoss3_intel is also failing from this PR

**Comment by jayeshkrishna** [comment]
I am still debugging the issue.
However now I have the same setup on anlworkstation as on melvin (I had to end up building static and dynamic versions of the entire software stack to debug build issues and to ensure I have the setup right). The issue is due to the NetCDF4P iotype (NetCDF+HDF5), for some reason on anlworkstation the calls with NetCDF4P fails and Scorpio defaults to NetCDF and on melvin the same calls cause a crash.
These issues are not recreatable with simple test programs from the Scorpio test suite.
Melvin has hdf5 1.8.12. On anlworkstation NetCDF4P calls fails with both hdf5 1.8.12 and hdf5 1.8.16 (however since the calls fail without a crash Scorpio defaults to NetCDF and the test succeeds - ugh)

**Comment by rljacob** [comment]
Note the same test is failing on sandiatoss3.

**Comment by jayeshkrishna** [comment]
Update: I am finally able to recreate this issue on anlworkstation. The issue seems to be incompatibility between NetCDF (NetCDF4P) and PnetCDF libraries.
I tried the latest version of PnetCDF but the test still crashed. I tried the latest version of the NetCDF C library with the latest version of PnetCDF and the test no longer crashes, but returns an error. I am going to debug the NetCDF library to get a better handle on the issue.

**Comment by jayeshkrishna** [comment]
To fix the ERIO test failures we need to upgrade the NetCDF C library. Upgrading the NetCDF library to the latest stable version (4.7.4) and using PnetCDF 1.12.0 (the latest stable version) fixes the crash on melvin with the ERIO test. 

Upgrading to the latest release of the NetCDF C library also requires a minor fix in Scorpio (https://github.com/E3SM-Project/scorpio/pull/298)

(The software stack used to run ERIO test successfully on anlworkstation : gcc 8.2.0, openmpi 2.1.5, zlib 1.2.11, szip 2.1, hdf5 1.8.12, PnetCDF 1.12.0, NetCDF C 4.7.4, NetCDF Fortran 4.4.4)

**Comment by rljacob** [comment]
The dashboard looks much better but ERIO.ne30_g16_rx1.A.sandiatoss3_intel is still failing.  May sandiatoss3 also needs a software stack update?

You can go ahead and merge this to master and make a separate PR for that test.

**Comment by jayeshkrishna** [comment]
Yes, sandiatoss3 will also need an update.

**Pull request merged**
