### PR TITLE
Update MALI to use new Albany basal friction law

### PR DESCRIPTION
**Pull request by matthewhoffman**
This merge updates MPAS source code to use the updated basal friction
law from Albany.  This is a Schoof-type basal friction law that accounts
for subglacial water pressure.

[BFB] for compsets without active ice sheet
[Non-BFB] for compsets with active MALI component
[NML]

### CODE REVIEW

**Comment by rljacob** [comment]
Is this really BFB?  even with an ice-sheet test?

**Comment by matthewhoffman** [comment]
@rljacob , no, this is only BFB for "standard" compsets that do not include active ice sheets.  I've updated the description to be more explicit - it wasn't clear to me how to handle this sort of situation.

**Comment by rljacob** [comment]
If its non-BFB for any test or case, I like to label the PR as non-BFB but you can add a comment with details as you did above.  When we later search for non-BFB PRs, its good to have ones with _any_ change included.

**Comment by rljacob** [comment]
Is this a v2 feature?  If so, it needs a code review document on confluence.

**Comment by jonbob** [comment]
@matthewhoffman - I think this PR will require a code review document

**Comment by jonbob** [comment]
A MALI test is included in the e3sm_integration suite, which is tested for baselines on sandiatoss3 and for machine coverage on anvil, compy, bebop and theta. Note that the MALI test currently passes only on sandiatoss3 and bebop. This PR updates the version of MALI on sandiatoss3 and cori, so for purposes of testing I've focused on cori. A test merge shows these results:
* SMS.f09_g16_a.MALI.cori-knl_intel    PASS
* ERS.f09_g16_g.MALISIA.cori-knl_intel    PASS
* SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel    PASS
* SMS.f09_g16_a.MALI.cori-knl_gnu   FAIL (no library for gnu)

@rljacob - we would still like to merge this PR today. MALI is not part of any upcoming simulation plans, so its absence on some platforms will not hold up progress.

**Comment by rljacob** [comment]
Go ahead.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master and expected NML DIFF's blessed

**Pull request merged**
