### PR TITLE
Restore Aquaplanet Capability

### LINKED ISSUE #2383: Aquaplanet compset is not an aquaplanet?
It appears as though the FC5AV1C-04P2-AQUAP compset is not actually an aquaplanet. I can configure, build, and run a case with this compset just fine, but the output reflects topography features in the surface pressure:

aqua_ps

So, either something isn't being set properly, or I am misunderstanding what "AQUAP" is supposed to mean in this compset definition.

### LINKED ISSUE #2719: data ocean component in cam source directory is obsolete
While working to resurrect the correct aquaplanet functionality (see issue #2383) I realized that the data ocean component in CIME:
`    cime/src/components/data_comps/docn/docn_comp_mod.F90`
is being used to set the SST, which was moved from the cam version 
`    components/cam/src/utils/cam_dom/`
that can only be used in a "standalone cam" configuration, which I doubt anyone using E3SM would have a use for.  There's also the "cam_aqua" directory
`    components/cam/src/utils/cam_aqua/`
that has it's own ocean component that is not needed. This was confirmed by Brian Medeiros at NCAR.

I'm planning to delete the cam directories for this in my PR that fixes the aqua planet compsets. My motivation for doing this comes the confusion it caused me when tracing through the code. I hope that removing these will help avoid confusing other people as well.

### LINKED ISSUE #2841: drydep() is called without ocnfrac and icefrac arguments
While working with aquaplanet compsets I wanted to avoid having to specify the drydep file, so I added an if statement in _get_landuse_and_soilw_from_file()_ to avoid loading this file when aquaplanet is used, since the file only contains information about land use and soil water content. 

However, this caused non-BFB diffs in regression tests because the default namelist value => _drydep_method = 'xactive_atm'_, leads to the dry deposition of gas-phase species to be calculated by _drydep_xactive()_ in mo_drydep.F90, but it is called from _gas_phase_chemdr()_ in mo_gas_phase_chemdr.F90 without the optional arguments for ocnfrac and icefrac. This leads to the dry deposition velocities being calculated based on the data in the drydep file. 

I think in addition to the check for aquaplanet to avoid specifying this file, we should add these optional arguments since they are already available in _gas_phase_chemdr()_.

This is somewhat related to issue #2803

### PR DESCRIPTION
**Pull request by whannah1**
Although there was a working aquaplanet compset that was sometimes used for testing, it included realistic topography that resulted in towering mountains of water. This PR adds new compsets to that are true aquaplanet configurations consistent with the Aquaplanet Experiment (APE) protocol. 

I adopted a different compset naming strategy instead of following the "FC5AV1" convention. The new compsets have short names like "F-EAMv1-AQP1", where the number at the end can be changed to match the SST patterns of the APE protocol (http://www.met.reading.ac.uk/~mike/APE/).  

The SST pattern is now controlled by "DOCN%AQP1" and set by the data ocean component in the CIME source directories. The old data ocean code in the atmosphere directories is obsolete, which is confusing, so I deleted it all. The atmosphere is set by "_CAM5%AQUA", which is very similar to the current FC5AV1C-L except that it includes the "-aquaplanet" flag that allows the domain and topography to be set internally without the need for external files.  

I also added a new cam.i file to the repo:
cami_aquaplanet_ne30np4_L72_c15-02-2019.nc

This PR resolves the following issues:
Fixes #2383
Fixes #2719 
Fixes #2841

Notes on regression tests: 
This PR replaces two existing tests (`ERP_Ln9.ne4_ne4.FC5AV1C-L-AQUAP` and `SMS_Ld1.ne4_ne4.FC5AV1C-L-AQUAP,cam-clubb_only`) with the following tests which use the new compset:
`ERP_Ln9.ne4_ne4.F-EAMv1-AQP1`
`SMS_Ld1.ne4_ne4.F-EAMv1-AQP1,cam-clubb_only`

Some caveats about these compsets:
- aerosols are still present, but the "constant droplet" mode is automatically activated. So while direct radiative impacts are still present, aerosol-cloud interactions should be effectively disabled.
- After doing some tests I noticed that the net TOA radiative balance was the opposite sign of what I normallly see from F-compsets. I think this is due to the combination of using different solar forcing data file and prescribed ozone. I based these choices on the current aquaplanet options in CAM6, but we may want to revisit how these things are set in the future. 
- A new use case was added to have special default namelist settings, but orbital parameters cannot be set this way. Therefore, following the CAM6 code, I added the CAM_USER_MODS section within config_component.xml, which sets some values in the user_nl_cpl file. I wish there were a cleaner way of setting these, but this method works pretty well.

[BFB] - This PR replaces two existing AQUAP tests with new ones

### CODE REVIEW

**Comment by whannah1** [comment]
So it turns out that the tests failed because of my new naming convention "_EAM%V1" made the tests expect files from the "eam" componen, but the names of the restart files and whatnot suggest they are from the "cam" component. 

The simplest fix was to keep the compset short names such as "F-EAMv1-AQP1" and change the long name to include "_CAM5%AQUA_". I verified that this made the tests pass. If anyone has a better idea for the compset short names I'm happy to change them.

I also uploaded uploaded initial condition files to the inputdata repo for ne4 and ne30 grids and verified that they are automatically downloaded on NERSC.

**Comment by rljacob** [comment]
You're right that the "CAM" part of the long name is expected because of other settings in CIME.  Changing that to EAM will have to be a major PR on its own.

**Comment by rljacob** [comment]
@whannah1 some of the files you uploaded to the input data server are not world readable.  Please fix.

**Comment by whannah1** [comment]
@rljacob, looking on blues I see that they are world readable. Am I missing something?

image

I had @brhillman add them for me since I was working from home yesterday and couldn't log on to blues.

**Comment by rljacob** [comment]
@minxu74 reported trouble reading them but not sure when that was.  Yes they seem to ok now.

**Comment by whannah1** [comment]
@rljacob that was probably the earlier files I uploaded then.

**Comment by wlin7** [comment]
Hi @mt5555 , you are requested by @whannah1 to review this PR. Can you please take a look? Thanks.

**Comment by whannah1** [comment]
@singhbalwinder I think this branch is ready to be merged, and I think the conflicts should be trivial, but let me know if you need any help or if I should assign someone else to merge

**Comment by singhbalwinder** [comment]
@rljacob : This PR modifies two existing tests. I believe, we would call this PR BFB as it is just like adding two new tests. Is that correct? Also, would it be okay if I start merging this PR today?

**Comment by rljacob** [comment]
If you know its BFB, and the tests are broken for other reasons you can say its BFB and mention the test changes in the description.

The description needs to be updated.  The "EAM" mentioned there had to be removed.  The fixed issues are not listed with the right keyword.  Also remove the embedded URL ("see here").

**Comment by singhbalwinder** [comment]
@whannah1 : I am assuming that this PR is BFB except for the two tests you modified. Is that correct?

**Comment by whannah1** [comment]
@singhbalwinder yes, that should be correct. I didn't do anything that would affect other tests.

But on that note, I just opened issue #2841, which affects the aqua tests, so I'm thinking it might be best to add those suggested changes to this PR. However, I need to check if it breaks the onther non-aqua tests. So maybe it's better to save for another PR, even though it will break the aqua test then.

**Comment by singhbalwinder** [comment]
Thanks @whannah1 . If it is easy to fix that, please do so in this PR and I will merge it when it is ready.

**Comment by whannah1** [comment]
ok, let me do some tests, hopefully they will go quickly. Afterwards I'll push the changes.

**Comment by whannah1** [comment]
@singhbalwinder, I just the change to make aquaplanet ignore the drydep file. so you are good to merge now. I didn't address the interface argument issue that I mentioned in #2841 because I'm not sure how that will affect things. It shouldn't matter either way after adding this simple fix.

**Comment by singhbalwinder** [comment]
Thanks @whannah1 ! Would you like to keep issue #2841 open? If not, I can add a line "Fixes #2841" in the PR description, which will automatically close that issue once this PR is merged to master.

**Comment by whannah1** [comment]
@singhbalwinder, it's probably best to close it. Someone who's more familiar with the drydep calculations should be in charge of whether the ocean and ice fraction should be in the arguments to drydep().

**Comment by singhbalwinder** [comment]
Pushed to next

**Pull request merged**
