### PR TITLE
Update mpas-source: Fix bug with high freq coupling in MPAS-Seaice

### PR DESCRIPTION
**Pull request by akturner**
This PR fixes a bug with high frequency coupling in MPAS_Seaice where the cell indices was used for the velocity fields instead of the vertex indices in step_therm1. CICE does the same but with a structured grid the consequences are less.

Fixes https://github.com/E3SM-Project/E3SM/issues/3989

[non-BFB] because high-frequency coupling in on by default currently

### CODE REVIEW

**Comment by jonbob** [comment]
the PEM test that had been failing is now passing:

PASS PEM_Ln9.ne30_oECv3_ICG.A_WCYCL1850S.anvil_intel

**Review by proteanplanet — APPROVED** [review]
Approved by visual inspection.

**Comment by jonbob** [comment]
Merged to next

**Comment by jonbob** [comment]
merged to master and expected DIFFs blessed

**Pull request merged**
