### PR TITLE
Build namelist one more time to make sure *_in files are updated

### PR DESCRIPTION
**Pull request by tangq**
Some user_nl settings are not transferred to *_in files. Add a call to
preview_namelists to make sure they are updated.

[BFB]

### CODE REVIEW

**Comment by PeterCaldwell** [comment]
I'm surprised that running preview_namelist more frequently is the best solution to this problem. @golaz and I have been complaining for a long time that building/submitting is really slow because preview_namelist is called lots of times... which seems really kludgy. Could we fix the CIME code to actually save the appropriate info to _in files in one call?

**Comment by golaz** [comment]
@PeterCaldwell and @mt5555: unfortunately yes. Until or unless CIME is changed, running 'preview_namelist' one more time within the run_e3sm script is the best option. With the current script, the *_in files generated in the run subdirectory are not up to date with user_nl_* after run_e3sm is executed. This is undesirable as it can be be confusing and misleading.

The long term solution would we a better engineered process to building namelists that doesn't require so many passes. But I don't see this happening soon, so the workaround that @tangq is suggesting here is probably our best recourse.

I'm not so concerned about the execution time of run_e3sm, which is typically run interactively on a login node. I'm much more concerned about the CIME overhead (up to 10 minutes) in batch jobs before the model actually starts (10 minutes with hundreds of nodes is expensive).

**Comment by tangq** [comment]
@mfdeakin-sandia , thanks for the suggestion. I just updated the version number to 3.0.21.

**Comment by mfdeakin-sandia** [comment]
I guess another thought is that if we're doing this before calling case.submit, we can remove the wasted time on the nodes by passing `--skip-preview-namelist` to the `case.submit` call. @jgfouca Can you confirm that's correct?

**Comment by tangq** [comment]
I used `--skip-preview-namelist ` in my DECK simulations. This is another reason that it is good to make sure user_nl and *_in files are synced after run_e3sm.

**Comment by jgfouca** [comment]
@mfdeakin-sandia , preview_namelists is always called in case.submit. It is also called, by default, at the beginning of case_run. If the user knows they will not be making changes between submit and run, then --skip-preview-namelist is safe to use.

**Pull request merged**
