### PR TITLE
Mask ocean time series stats variables

### LINKED ISSUE #5253: Fill values are not appearing in fields in timeSeriesStats
Even when we specify a fill mask and fill value in the registry, we're not seeing the fill mask get propagated to fields in `timeSeriesStats`.  See https://github.com/E3SM-Project/E3SM/pull/5251#issuecomment-1292526164

### PR DESCRIPTION
**Pull request by cbegeman**
This PR applies fill value masking to non-restart time series stats streams in the ocean component. It also specifies the masking array for a subset of variables in the Registry.

It builds on the PRs that add the masking option to the framework, https://github.com/E3SM-Project/E3SM/pull/5154 and https://github.com/E3SM-Project/E3SM/pull/5251. Discussion can be found at https://github.com/E3SM-Ocean-Discussion/E3SM/pull/32.

Fixes #5253

[BFB]

### CODE REVIEW

**Review by xylar — APPROVED** [review]
I ran the `CMPASO-JRA1p4_TL319_EC30to60E2r2` test case for a month and took a look at masking for a random sampling of different time series stats variables for which masking has been turned on in this PR.  Everything looked good to me.  Results are at:
```
/lcrc/group/e3sm/ac.xasay-davis/scratch/chrys/20221129.CMPASO-JRA1p4_TL319_EC30to60E2r2.fix-time-series-stats.chrysalis/run
```

**Comment by xylar** [comment]
@darincomeau, can you take a look at this when you get a chance?  It would be great to have another test or at least another pair of eyes on the test results I just produced before this goes in.

**Comment by darincomeau** [comment]
I ran a one month G case here: `/lcrc/group/acme/ac.dcomeau/scratch/chrys/20221130.GMPAS-JRA1p4.TL319_ECwISC30to60E2r1.chrysalis.intel/run`

Looking through `timeSeriesStatsMonthly` I'm seeing the new attributes in various variables that were not previously present, so looks good to me.

**Review by darincomeau — APPROVED** [review]

**Comment by cbegeman** [comment]
@darincomeau Thanks so much for reviewing!

**Comment by jonbob** [comment]
passes:
* SMS_D_Ld3.T62_oQU120.CMPASO-IAF.chrysalis_intel
* ERS.ne11_oQU240.WCYCL1850NS.chrysalis_intel
* SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod

merged to next

**Comment by xylar** [comment]
Woohoo!  Thanks @jonbob and @cbegeman!

**Comment by cbegeman** [comment]
@jonbob Thanks for your testing! I'm happy that we're a little closer to CF compliance

**Pull request merged**
