### PR TITLE
Merge PR #3569 to maint-1.0 for nudging bug fixes

### PR DESCRIPTION
**Pull request by tangq**
Some nudging runs are assigned by the E3SM leaders to use the maint-1.0 code. It requires the bug fixes in PR #3569. These fixes are on master, but not on maint-1.0. Cherry-picked in this PR for maint-1.0

@wlin7 and @jiansunpnnl : It is a bit time sensitive as the first test run is planned for the next week. Since these changes have been tested and merged on master, can we go ahead and merge it into maint-1.0? This part of code is isolated to the other parts, so it should not affect other code. Thanks.

### CODE REVIEW

**Comment by jiansunpnnl** [comment]
Hi, @tangq , the changes look good to me by eyes. Thanks.

**Comment by wlin7** [comment]
Looks good to me as well. In particular I double checked that the later fixes by @jiansunpnnl and @singhbalwinder after initial review are present in this PR.  Merged to maint-1.0.

**Comment by jiansunpnnl** [comment]
> Looks good to me as well. In particular I double checked that the later fixes by @jiansunpnnl and @singhbalwinder after initial review are present in this PR. Merged to maint-1.0.

Thanks, @wlin7 . I would like to mention one thing that may be useful for other readers who want to use the updated nudging code in their own branches. We also change the physpkg.F90 and namelist_definition.xml files together with the nudging code. These two files are likely to be different between branches (e.g., master vs. maint-1.0). Thus cautions are needed when merging the changes here in order to make the updated nudging code work properly.

**Comment by wlin7** [comment]
Good points and thanks for the cautious reminder, @jiansunpnnl . When I just saw your comment, I was concerned, and then went back to re-review the changes. It appears git-cherry-pick is smart enough to only incorporate the changes/fixes you and @singhbalwinder introduced to #3569. Though the base versions of namelist_definitions.xml and physpkg.F90 have diverged in the master from the ones in maint-1.0, only the changes purposed for the nudging fixes are picked up in this PR. You can see the changes highlighted in the two files are identical between the two PRs, though they are not at the same lines of codes. This must be the beauty of git-cherry-pick. I was not certain about that.

**Comment by wlin7** [comment]
Another note, @jiansunpnnl : My understanding is, as long as the nudging fix codes have zero dependency on the changes in namelist_definitions.xml and physpkg.F90 since master diverges from maint-1.0, all should be good.

**Comment by jiansunpnnl** [comment]
> Good points and thanks for the cautious reminder, @jiansunpnnl . When I just saw your comment, I was concerned, and then went back to re-review the changes. It appears git-cherry-pick is smart enough to only incorporate the changes/fixes you and @singhbalwinder introduced to #3569. Though the base versions of namelist_definitions.xml and physpkg.F90 have diverged in the master from the ones in maint-1.0, only the changes purposed for the nudging fixes are picked up in this PR. You can see the changes highlighted in the two files are identical between the two PRs, though they are not at the same lines of codes. This must be the beauty of git-cherry-pick. I was not certain about that.

Thanks, @wlin7 . When I first saw Qi's PR, I was wondering how he handles the difference between master and maint-1.0 for the same code. Thus I checked the master and maint-1.0 separately to ensure this PR only picks the changes related to nudging code on the master branch. As you suggested, it seems that git is powerful enough to deal with it automatically (though I am not sure about it, either).

**Comment by jiansunpnnl** [comment]
> Another note, @jiansunpnnl : My understanding is, as long as the nudging fix codes have zero dependency on the changes in namelist_definitions.xml and physpkg.F90 since master diverges from maint-1.0, all should be good.

Yes, I agree.

**Comment by tangq** [comment]
Thank you, @wlin7 and @jiansunpnnl for the prompt responses.

**Pull request merged**
