### PR TITLE
Update machine files for OLCF AF machine - HPC11

### PR DESCRIPTION
**Pull request by hyungyukang**
This PR updates the machine setting for the US Air Force Cray EX supercomputer (HPC11) at ORNL (firstly added by  #4781). Only GNU compiler is available on HPC11 at this moment.

### CODE REVIEW

**Comment by jonbob** [comment]
@rljacob -- I'm not sure I have access to this platform. Should I try to get an account? Or just merge it without testing there?

**Comment by rljacob** [comment]
You can merge with just a visual inspection.

**Review by jonbob — APPROVED** [review]
Approved based on visual inspection and sanity testing on chrysalis

**Comment by hyungyukang** [comment]
> merged to next -- I don't have easy access to HPC11 but did sanity testing on chrysalis to make sure other machines were not impacted

@jonbob , Thanks for testing and your approval. I'm sorry that you can't access to HPC11 with ease. The machine file is isolated only for HPC11, so it does not affect to other machines as you tested.

**Comment by jonbob** [comment]
Thanks @hyungyukang -- it looks like you did your own testing and a good job of modifying the machines files

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
