### PR TITLE
Fix MMF explicit scalar momentum transport (ESMT)

### PR DESCRIPTION
**Pull request by whannah1**
A few fixes to enable the scalar momentum transport scheme (ESMT) in the MMF. The main change is to just update the dimension ordering which were switched during the refactoring to support running the MMF on GPUs. 

[BFB] since we currently don't test this feature.

### CODE REVIEW

**Comment by rljacob** [comment]
@brhillman is this ready to merge?

**Comment by whannah1** [comment]
@rljacob this PR is ready, the main reason we held off is because of the ERP test issues we discovered awhile back, and perhaps another issue that I'm forgetting. But now that we switched to the ERS test for MMF we can merge this whenever.

**Comment by rljacob** [comment]
Lets merge #3639 first since that will fix the ERS test for the MMF compset.

**Comment by brhillman** [comment]
Merged to next.

**Comment by brhillman** [comment]
Merged to master.

**Pull request merged**
