### PR TITLE
Add performance benchmarking tests

### PR DESCRIPTION
**Pull request by amametjanov**
Add performance benchmarking tests for scaling and historical checkpointing:
* high- and low-res F-compset without IO
* high- and low-res G-compset without IO
* high- and low-res W-compset with production IO

Also, update PE-layouts on Anvil and Cori-KNL.

[BFB]

### CODE REVIEW

**Comment by amametjanov** [comment]
`cime/scripts/create_test e3sm_bench_g` on a machine will create 43 tests of GMPAS-IAF/T62_oRRS18to6v3 configuration scaled from 512 to 96000 cores (all available seaice v2 partitions).

**Comment by jgfouca** [comment]
Looks good to me. Where are we going to run these tests? What is going to drive them?

**Comment by amametjanov** [comment]
This is for reproducible benchmarking. For now, we'll run them manually at LCFs, NERSC, anvil and compy. Later, it'll be useful to launch them whenever a new tag/release is made.

**Comment by oksanaguba** [comment]
How are these tests going to be used? right now F cases in here use v1 configuration, so, preqx dycore, etc. If these tests are for future development, would it make sense to switch F cases (ne30) to ne30pg2, theta dycore, SL option, and ne120 to theta dycore and SL option (there is no pg2 setting for ne120 right now).

**Comment by oksanaguba** [comment]
Tried to switch to pg2 for ne30 F cases:
```
128: e3sm.exe           000000000169467A  compose_mod_mp_co         222  compose_mod.F90
128: e3sm.exe           00000000012DDD8F  prim_driver_base_         603  prim_driver_base.F90
128: e3sm.exe           0000000001685629  dyn_comp_mp_dyn_i         154  dyn_comp.F90
128: e3sm.exe           00000000011EA261  inital_mp_cam_ini          31  inital.F90
```
where line 22 in compose_mod is 
```
       call cedr_init_impl(par%comm, semi_lagrange_cdr_alg, &
            use_sgi, sc2gci, sc2rank, nelem, nelemd, nlev)
```
Without pg2 tests run:
Ran e3sm_bench_lores_f on anvil and 5400 ranks job ran out of time (the rest completed). Time limit was 31 minutes, while in the suite time limit is 1 hour. Not sure how time limit is computed for multiple tests in a suite. I did not add all options for theta dycore. These options will soon become default for theta dycore, so, they will be picked up. Not sure what to do about nonhydrostatic option though.

**Comment by oksanaguba** [comment]
Also, --kill-on-bad-exit did not help, the job stalled and never exited.

**Comment by oksanaguba** [comment]
Tried again, it seems that noio+pg2 option is not working (noir and usual ne30np4 grid worked):

Today's master (cdash also has pg2 runs):
cime/scripts/create_test --machine anvil --compiler intel SMS_P96x1.ne4pg2_ne4pg2.FC5AV1C-L.anvil_intel -- RAN

Took the same master, merged Az branch into (no latest diffs from me), trying 
cime/scripts/create_test --machine anvil --compiler intel SMS_P96x1.ne4pg2_ne4pg2.FC5AV1C-L.anvil_intel.bench-fcomp_noio CRASHED in a different place
60: e3sm.exe           0000000002454152  shr_abort_mod_mp_         114  shr_abort_mod.F90
60: e3sm.exe           000000000049EC63  seq_domain_mct_mp         693  seq_domain_mct.F90
60: e3sm.exe           000000000049A332  seq_domain_mct_mp         378  seq_domain_mct.F90
60: e3sm.exe           0000000000430093  cime_comp_mod_mp_        1896  cime_comp_mod.F90

After that tried the same master+Az without noio option
cime/scripts/create_test --machine anvil --compiler intel SMS_P96x1.ne4pg2_ne4pg2.FC5AV1C-L.anvil_intel ---- RAN

**Comment by oksanaguba** [comment]
I did not push latest diffs switching lores F tests to pg2 grid. Not sure what to do -- to abandon noio+pg2 grid for now?

**Comment by oksanaguba** [comment]
Reverting changes for F cases. My understanding is that we can switch these tests for v2 configurations later.

**Pull request merged**
