### PR TITLE
Fix array allocation error in BeTR

### LINKED ISSUE #5539: Fortran runtime error: Index '1' of dimension 2 of array 'this' outside of expected range SMS_D.f19_g16.I1850ELM.machine_compiler.elm-betr
Using `SMS_D.f19_g16.I1850ELM.pm-cpu_gnu.elm-betr`, see error below.
Can reproduce with master of May6th.

```
 0:  --------------------
 0: 
 0:   betr time :
 0: 
 0:   betr_time namelist settings :
 0: 
 0: &BETR_TIME
 0:  DELTA_TIME=  1800.0000000000000     ,
 0:  STOP_N=2          ,
 0:  STOP_OPTION="nyears  ",
 0:  RESTART_DTIME= -1.0000000000000000     ,
 0:  HIST_FREQ=-1         ,
 0:  /
 0: 
 0:  --------------------
 0: At line 124 of file /global/cfs/cdirs/e3sm/ndk/repos/nexty-mar30/components/elm/src/external_models/sbetr/src/betr/betr_core/TracerStateType.F90
 0: Fortran runtime error: Index '1' of dimension 2 of array 'this' outside of expected range (140725294609776:39784124)
 0: 
 0: Error termination. Backtrace:
 0: #0  0x1ecc26a in __tracerstatetype_MOD_initallocate
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/nexty-mar30/components/elm/src/external_models/sbetr/src/betr/betr_core/TracerStateType.F90:124
 0: #1  0x1ece91d in __tracerstatetype_MOD_init
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/nexty-mar30/components/elm/src/external_models/sbetr/src/betr/betr_core/TracerStateType.F90:78
 0: #2  0x1e133cd in __betrtype_MOD_init
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/nexty-mar30/components/elm/src/external_models/sbetr/src/driver/shared/BeTRType.F90:202
 0: #3  0x1df0988 in __betrsimulation_MOD_betrinit
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/nexty-mar30/components/elm/src/external_models/sbetr/src/driver/shared/BeTRSimulation.F90:464
 0: #4  0x1afc070 in __betrsimulationelm_MOD_elminit
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/nexty-mar30/components/elm/src/external_models/sbetr/src/driver/elm/BeTRSimulationELM.F90:199
 0: #5  0x6340ff in __elm_initializemod_MOD_initialize2
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/nexty-mar30/components/elm/src/main/elm_initializeMod.F90:650
 0: #6  0x5fa7f3 in __lnd_comp_mct_MOD_lnd_init_mct
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/nexty-mar30/components/elm/src/cpl/lnd_comp_mct.F90:286
 0: #7  0x43e20c in __component_mod_MOD_component_init_cc
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/nexty-mar30/driver-mct/main/component_mod.F90:248
 0: #8  0x425cb6 in __cime_comp_mod_MOD_cime_init
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/nexty-mar30/driver-mct/main/cime_comp_mod.F90:1446
 0: #9  0x437491 in cime_driver
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/nexty-mar30/driver-mct/main/cime_driver.F90:122
 0: #10  0x4375cd in main
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/nexty-mar30/driver-mct/main/cime_driver.F90:23

/pscratch/sd/n/ndk/e3sm_scratch/pm-cpu/nx-mar20/SMS_D.f19_g16.I1850ELM.pm-cpu_gnu.elm-betr.20230321_091643_pbugd5
```

With Intel on chrysalis:
`SMS_D.f19_g16.I1850ELM.chrysalis_intel.elm-betr`

```
 38: forrtl: severe (408): fort: (7): Attempt to use pointer TRACER_CONC_SOLID_EQUIL_COL when it is not associated with a target
 38:
 38: Image              PC                Routine            Line        Source
 38: libpnetcdf.so.3.0  0000155551014202  for_emit_diagnost     Unknown  Unknown
 38: e3sm.exe           00000000047EDF55  tracerstatetype_m         124  TracerStateType.F90
 38: e3sm.exe           00000000047EA810  tracerstatetype_m          78  TracerStateType.F90
 38: e3sm.exe           0000000004092B88  betrtype_mp_init_         202  BeTRType.F90
 38: e3sm.exe           0000000003FC5BA4  betrsimulation_mp         463  BeTRSimulation.F90
 38: e3sm.exe           00000000040FC859  betrsimulationelm         199  BeTRSimulationELM.F90
 38: e3sm.exe           00000000009DE417  elm_initializemod         650  elm_initializeMod.F90
 38: e3sm.exe           0000000000926411  lnd_comp_mct_mp_l         286  lnd_comp_mct.F90
 38: e3sm.exe           00000000004860DB  component_mod_mp_         257  component_mod.F90
 38: e3sm.exe           000000000042E8EA  cime_comp_mod_mp_        1446  cime_comp_mod.F90
 38: e3sm.exe           000000000047CB9D  MAIN__                    122  cime_driver.F90
 38: e3sm.exe           000000000041AE22  Unknown               Unknown  Unknown
 38: libc-2.28.so       000015554E665493  __libc_start_main     Unknown  Unknown
 38: e3sm.exe           000000000041AD2E  Unknown               Unknown  Unknown
```

### PR DESCRIPTION
**Pull request by jinyuntang**
Updates BeTR submodule to fix an error due to the obsolete use of 
an if-block for array allocation. The update hash for the BeTR submodule is 25c892a.

Fixes #5539 
[BFB]

### CODE REVIEW

**Comment by jinyuntang** [comment]
@ndkeen I have fixed the issue #5539. It is due to an obsolete use of IF block with the most recently fortran compilers. No answer change occurred. Please test. 
@bishtgautam please review.

**Comment by ndkeen** [comment]
I can verify this fix does allow the test to run.

**Comment by rljacob** [comment]
To fix this you must be updating the submodule for betr.  Please mention which hash of betr is being used now in the PR description above.

**Comment by jinyuntang** [comment]
> To fix this you must be updating the submodule for betr. Please mention which hash of betr is being used now in the PR description above.
@rljacob 
It is 25c892a, the most recent commit in the sbetr master branch.

**Review by bishtgautam — APPROVED** [review]

**Comment by ndkeen** [comment]
With mention of changes to betr submodule, would it be possible for someone to make a change to the maint-1.0 branch in betr?  I have copy of the file that needs to be replaced -- it's solely to get around issues discovered building with GCC version 10 and higher.

**Comment by bishtgautam** [comment]
PR #5679 addresses @ndkeen's comment [above](https://github.com/E3SM-Project/E3SM/pull/5676#issuecomment-1542707499).

**Pull request merged**
