### PR TITLE
disable excessive logging in chem

### PR DESCRIPTION
**Pull request by mahf708**
Disable per step logging of lightning NOx and linoz options.

[BFB]
---------------------------------------------------------------------------------------------------------------
Below is the original draft commit message, which is simplified as above for the merge commit.

This draft PR proposes disabling logging at every time step for two new chem features as part of v3. The logging wasn't enabled previously. For now, I simply commented these lines out. However, a more desirable solution may exist where logging can happen at the first step only or in the preamble. See below for how they appear in the targeted branch (v3) vs current master (v2).

<details><summary>v3</summary>
<p>

```
 nstep, te     3355   0.26237744405846009E+10   0.26237766411979456E+10   0.12167978652049336E-03   0.98536209073071703E+05
  
Global flash freq (/s), lightning NOx (TgN/y) =    31.7797    1.5737
 do_lin_strat_chem= T linoz_v2= F linoz_v3= T
 nstep, te     3356   0.26237397620288749E+10   0.26237414389949470E+10   0.92725490370622340E-04   0.98536171484701117E+05
  
Global flash freq (/s), lightning NOx (TgN/y) =    32.9714    1.6245
 do_lin_strat_chem= T linoz_v2= F linoz_v3= T
 nstep, te     3357   0.26236985440255389E+10   0.26237003970929694E+10   0.10246283025623514E-03   0.98536111961507355E+05
  
```

</p>
</details>  

<details><summary>v2</summary>
<p>

```
 nstep, te   161654   0.26248186663117232E+10   0.26248186801433063E+10   0.15298796601443216E-05   0.98517904983531611E+05
 nstep, te   161655   0.26248016109393911E+10   0.26248038598654752E+10   0.24874861661303263E-03   0.98517880091223531E+05
 nstep, te   161656   0.26247883409141140E+10   0.26247884387260523E+10   0.10818759561378321E-04   0.98517854836411469E+05
 nstep, te   161657   0.26247699333299103E+10   0.26247723163711505E+10   0.26358293082365497E-03   0.98517827478318446E+05
 nstep, te   161658   0.26247557334176493E+10   0.26247558912121325E+10   0.17453304318051123E-04   0.98517799951685549E+05
 nstep, te   161659   0.26247367740292397E+10   0.26247390657590075E+10   0.25348331656305147E-03   0.98517770691385624E+05
```

</p>
</details> 

--

[BFB]

### CODE REVIEW

**Comment by tangq** [comment]
@mahf708 , can you try adding `write(iulog,*)'do_lin_strat_chem=',do_lin_strat_chem,'linoz_v2=',linoz_v2,'linoz_v3=',linoz_v3` immediately before this line?
https://github.com/E3SM-Project/E3SM/blob/master/components/eam/src/chemistry/mozart/lin_strat_chem.F90#L185

It seems the better place to write the logging only one time at the beginning of a run.

As for the lightning NOx logging, it stores in a new output variable and will be able to show in ChemDyg. It should be okay to disable it. (I am not sure who turned that on...)

**Comment by tangq** [comment]
Don't need to change other lines. Leave them as-is. Does the new line work as expected? Thanks for testing.

**Comment by tangq** [comment]
If you make me the reviewer, I will approve it.

**Review by tangq — APPROVED** [review]

**Comment by sarats** [comment]
@mahf708 I added you to E3SM developers team in Github. I believe that you should be able to assign reviewers now.
FYI @rljacob

**Comment by sarats** [comment]
We have branch protection rules. So, we are reasonably guarded against accidental force-pushes. But keep being vigilant ;)

**Comment by wlin7** [comment]
Merged to v3atm/eam/master_MAM5_wetaero_chemdyg.

Note: the commented out lines could be removed outright. To be done in a future cleanup, as there are many more of such commented out lines in the codes.

**Pull request merged**
