### PR TITLE
Fix the call to `SatellitePhenology` when fates is active

### PR DESCRIPTION
**Pull request by glemieux**
Move the fates-specific `satellitephenology` call out of an area that is unreachable when `fates` is active.  

Fixes https://github.com/NGEET/fates/issues/953.

[Non-B4B]

### CODE REVIEW

**Comment by glemieux** [comment]
Perlmutter E3SM land developer tests against master are complete (I merge master locally, but did not push).  All but 2 tests are b4b.  One DIFF in the fates `satphen` test as expected.  The test with the `hcru_hcru` resolution failed to run however.  The testlog had an error I wasn't familiar with:
```
 ---------------------------------------------------
2022-12-01 15:20:17: OLD FAIL: Potentially broken merges:
3b28b97f2f3ab181b1cdabf8d618256f2360f8e6
c0381621ba5653261e70edc1463bd17b7bc87d4a
 ---------------------------------------------------
```

**Comment by bishtgautam** [comment]
@glemieux, I could not access the `/global/homes/g/glemieux/pm-scratch/e3sm-tests/pr5345.fates.pm-cpu.gnu.Cb4cb329d34-Fdef6b3e7`. Btw, instead of merging `master` locally, you can rebase your branch off the latest `master` before testing.

**Comment by glemieux** [comment]
Sorry about that @bishtgautam; I've opened up all the folders in my scratch directory to be readable by all now.  Thanks.

**Comment by glemieux** [comment]
Upon a resubmit the `hrcu_hrcu` test that failed to RUN is passing now.

**Review by rgknox — APPROVED** [review]
good stuff, thanks @glemieux

**Comment by bishtgautam** [comment]
This PR is now merged to next. A minor comment regarding renaming your future branches: E3SM is following the following naming convention: `<username/component-name/short-useful-name>`. So, this branch could be named `<glemieux/lnd/fates-satphen-mode>`.

**Comment by glemieux** [comment]
> This PR is now merged to next. A minor comment regarding renaming your future branches: E3SM is following the following naming convention: `<username/component-name/short-useful-name>`. So, this branch could be named `<glemieux/lnd/fates-satphen-mode>`.

Thanks for the reminder @bishtgautam

**Pull request merged**
