### PR TITLE
Add optional arguments and update documentation for mkmapdata

### PR DESCRIPTION
**Pull request by brhillman**
Update the mkmapdata script to add additional optional arguments to allow better control of execution
of underlying `ESMF_RegridWeightGen` command. Previously, this required setting environment
variables before calling the script to specify the ESMF path, inputdata location, MPI command and/or
number of MPI tasks. Optional arguments are added for each of these 
(`--esmf-path`, `--inputdata-path`, `--mpiexec`, `--ntasks`). 
An additional argument is added (`--output-filetype`) to override the netcdf format of the output 
maps. This was needed to force ESMF to write large files in 64bit-offset format instead of netcdf3, 
and so this can now be handled without individual customized scripts to override the default file type.
Some logic was also cleaned up in the script, and some consistent formatting applied (consistent 
4-space indent level as opposed to the mix of 3 and 4 that existed before). Documentation has also 
been updated for consistency with the changes, and clarified somewhat. Note that this script contains
some hard-coded in support for certain platforms. I imagine a lot of this is outdated and not 
maintained, so we should probably remove it at some point and require users to correctly specify paths 
and MPI commands as command line options, but we can save that for a future PR if there is 
consensus on that.

[BFB]

### CODE REVIEW

**Comment by bishtgautam** [comment]
@brhillman, clm4_0 is not supported anymore. So, we should remove `-p|--phys clm4_0`. Do you want to make changes to the script? Otherwise, I can also make the necessary changes. Thanks.

**Comment by brhillman** [comment]
No problem I'll do that right now.

**Comment by brhillman** [comment]
@bishtgautam should we remove the `--phys` option altogether?

**Comment by brhillman** [comment]
clm/bld/queryDefaultNamelist.pl still accepts a --phys argument, and appears to accept clm4_0 still.

**Comment by bishtgautam** [comment]
I suggest that we remove the option to specify `--phys` for `components/clm/tools/shared/mkmapdata/mkmapdata.sh` and hard-code the value `phys=clm4_5` for now. At some time in the future, the land team devs will remove all references/options for clm4_0.

**Comment by brhillman** [comment]
@bishtgautam would be acceptable to leave the `--phys` option in there, in the event that we have something like `phys=clm4_6` or something in the future, and just update the documentation to reflect the fact that clm4_0 is no longer supported? I'm not really a fan of hard-coding values in there, but the default is already set to clm4_5 so with no `--phys` argument passed to the script it will already behave as desired.

**Comment by bishtgautam** [comment]
@rljacob, While merging this PR to master, my local copy of brhillman/clm/update-mkmapdata was one commit behind and I mistakenly left out the last commit (e090091e7). Can I remerge this PR again to next and master making sure that I include e090091e7? Or, should I cherry-pick the last commit and open a new PR?

**Comment by rljacob** [comment]
Make a new PR.

**Comment by bishtgautam** [comment]
PR-#2816 is now open to include e090091

**Pull request closed without merging**
