### PR TITLE
Adds water budget in the land model

### PR DESCRIPTION
**Pull request by bishtgautam**
Following improvements to the water budget in the land model are added:
- Fixes the incorrect update of water state of unconfined aquifer at the beginning
   of the land driver. This fix improves the net water budget in the fully coupled
   simulation.
- Calculation of a grid-level water budget is now included.
- Diagnostics about water budget can be now outputted in the land logfiles
   by setting `do_budgets=.true.` in usr_nl_clm. The diagnostics includes:
   - Temporally integrated water fluxes over a given period (e.g. instantaneus,
      daily, monthly, annual, all-time). This diagnostic information is similar to
      the information outputted in the coupler logfile if `BUDGETS=TRUE` in
      env_run.xml.
   - Water states at the beginning and end of the integration period. This diagnostic
      information includes water stored in various land components (i.e. soil moisture, 
     canopy storage, etc).
- Additional data is saved in land monthly history tapes to recreate the land
  water diagnostics from model output.
- Additional data is saved in land restart file to support output of land water
   diagnostics when a simulation restarts in the middle of a month.

[non-BFB]

### CODE REVIEW

**Comment by bishtgautam** [comment]
@jonbob, This PR is now ready for you to test out a fully coupled simulation when you get a chance. Thanks.

**Comment by jonbob** [comment]
Thanks @bishtgautam! I'll get one started right away. And I think there's no need to wait for results from that run to get this onto master

**Comment by bishtgautam** [comment]
@jonbob, I have set the merge destination for this PR to be maint-1.0 and will open a new PR with the merge destination as master.

@susburrows, @kvcalvin, Though this PR is non-BFB for the land model, it improves net water budget in the land. You should consider if you want to incorporate these fixes on maint-1.1.

**Comment by susburrows** [comment]
@bishtgautam thanks for notifying us.  I will have a look and may have some follow-up questions.

**Comment by susburrows** [comment]
@bishtgautam it seems like this ould be useful to have in maint-1.1.  A couple of questions:

1. does do_budgets=.true. in usr_nl_clm turn on all of the different temporal frequencies of diagnostic outputs at the same time?

2. how large are the changes to state for the land model?  Do you have tests of this documented somewhere already?

Thanks!

**Comment by bishtgautam** [comment]
1. I followed a similar namelist convention that is used in`usr_nl_cpl`. Setting `do_budgets=.true.` only outputs monthly diagnostics. For instantaneous diagnostics set `budget_inst=1`, for daily diagnostics `budget_daily=1`, etc.
2. I haven't quantified the difference in state in the land model. Since the error only impacts urban columns in the land domain, I expect the total difference in land states to be small.

**Comment by susburrows** [comment]
Thanks for the clarifications @bishtgautam !

**Comment by jqyin** [comment]
@bishtgautam just to be clear, it is PR for maint-1.0 as it is labelled or for maint-1.1 as @susburrows suggested?

**Comment by bishtgautam** [comment]
This is for maint-1.0. I will open new PRs for maint-1.1 and master.

**Comment by rljacob** [comment]
Wait this is non-BFB for the land model?  So the v1 CMIP6 fully coupled case would change answers?  If so, it can't go on maint-1.0.

**Comment by rljacob** [comment]
> Is maint-1.0 only for PRs that are BFB w.r.t. v1 CMIP6 simulations?
Yes.

**Comment by bishtgautam** [comment]
On yesterday's call on water conservation, we decided not to fix maint-1.0. Will issue a new PR for master.

**Pull request closed without merging**
