### PR TITLE
Update mpas-source: seaice variational scheme refactor

### PR DESCRIPTION
**Pull request by akturner**
Refactor of the MPAS-Seaice variational scheme to easily allow other grids to use it other than the primary SCVT mesh

Merges https://github.com/MPAS-Dev/MPAS-Model/pull/846

[BFB]

### CODE REVIEW

**Review by proteanplanet — CHANGES_REQUESTED** [review]
Perhaps I am wrong, but it seems that this has passed through MPAS integration without testing.  For this PR, would it be possible to run ERS, smoke, processor count, and different compiler tests in E3SM.  Would it be possible to please test this before merging?

**Comment by mark-petersen** [comment]
@akturner, both this PR and MPAS-Dev/MPAS-Model#846 have no documentation of testing. We really need that before being next in line, as it takes time and issues can come up. Specifically,
1. Please show with testing that this PR is bit-for-bit with `E3SM/master` with several standard tests. 
2. Because there are module-level interface changes, this needs to be run on multiple compilers and machines, including PGI.

[Here are some recent examples](https://github.com/E3SM-Project/E3SM/pull/4219#issuecomment-819930132) of testing of this sort.

**Comment by jonbob** [comment]
@mark-petersen - I agree that testing is critical for MPAS PRs, but I think the level is something we should discuss in one of our meetings

**Comment by mattdturner** [comment]
```
PASS:
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi.C
  - PASS SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi BASELINE /compyfs/e3sm_baselines/pgi/master:
SMS_P12x2.ne4_oQU240.A_WCYCL1850.compy_pgi.allactive-mach_mods 
  - PASS SMS_P12x2.ne4_oQU240.A_WCYCL1850.compy_pgi.allactive-mach_mods BASELINE /compyfs/e3sm_baselines/pgi/master:

**Comment by mark-petersen** [comment]
Passes:
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
```

**Review by mark-petersen — APPROVED** [review]
Approved based on visual inspection and set of five tests above.

**Comment by jonbob** [comment]
Thanks for testing, @mark-petersen and @mattdturner

**Review by proteanplanet — APPROVED** [review]
This has passed the appropriate tests, and is now ready for testing as part of 'next' for E3SM.

**Comment by jonbob** [comment]
merged to next

**Pull request merged**
