### PR TITLE
Upgrading Summit modules

### LINKED ISSUE #2847: E3SM hangs in MPI finalize on Summit
E3SM hangs on Summit when running F case with ne4_ne4 resolution. This problem was reported by Tahsin Kurc (@tkurc) while testing E3SM+PIO2+ADIOS on Summit.

I observed the same issue with PIO2 tests on Summit.

This issue can be recreated using a simple MPI hello world program on Summit.

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Upgrading the summit cmake, essl and MPI modules.

Also updating the ROMIO version to prevent OOM errors.

Fixes #2847

[BFB]

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
Tried X cases successfully with ibm and pgi compilers on Summit

**Comment by sarats** [comment]
For the MMF runs, we had to add the following to bypass ROMIO out-of-memory errors.
Error: ``` 847 Out of memory in file ../../../../../../../opensrc/ompi/ompi/mca/io/romio321/romio/adio/ad_gpfs/ad_gpfs_rdcoll.c, line 1178 ```

Fix:
```
    <env name="OMPI_MCA_io">romio314</env>
```

**Comment by sarats** [comment]
A request: there is a new default cmake module. It might be good to update that as well.
cmake/3.13.4

**Comment by jayeshkrishna** [comment]
Sure, I will rebase the branch

**Comment by minxu74** [comment]
@sarats @jayeshkrishna I got the OOM error during running the high-res F case with IOs as mentioned by @sarats . So we need to add the fix into the machine file too.

**Comment by jayeshkrishna** [comment]
Ok, I will add the env and rebase the branch (@minxu74 : Did the env work for you?)

**Comment by sarats** [comment]
Just FYI. This explains the context for the env variable setting from OLCF page on Summit resolved issues. 
So, new ROMIO is needed for better performance of parallel HDF5 but seems to trigger OOM errors. I think we ought to try latest Spectrum MPI module and unload darshan-runtime to see if we still get OOM errors.

>>> Job hangs in MPI_Finalize

There is a known issue in Spectrum MPI 10.2.0.10 provided by the spectrum-mpi/10.2.0.10-20181214 modulefile that causes a hang in MPI_Finalize when ROMIO 3.2.1 is being used and the darshan-runtime modulefile is loaded. The recommended and default Spectrum MPI version as of March 3, 2019 is Spectrum MPI 10.2.0.11 provided by the spectrum-mpi/10.2.0.11-20190201 modulefile. If you are seeing this issue, please make sure that you are using the latest version of Spectrum MPI.

If you need to use a previous version of Spectrum MPI, your options are:

    Unload the darshan-runtime modulefile.
    Alternatively, set export OMPI_MCA_io=romio314 in your environment to use the previous version of ROMIO. Please note that this version has known performance issues with parallel HDF5 (see “Slow performance using parallel HDF5” issue below).

**Comment by minxu74** [comment]
@jayeshkrishna The test run is in the queue now. However, based on the response from @sarats , the fix is not needed because you already use the latest Spectrum MPI.   I did used the old Spectrum MPI and got the OOM.

**Comment by sarats** [comment]
@minxu74 To clarify, my OOM errors went away only after putting that environment variable.

**Comment by minxu74** [comment]
@jayeshkrishna @sarats My test run confirmed that the env setting fixed the OOM error.

**Comment by jayeshkrishna** [comment]
@minxu74 : Did you run the tests with the latest MPI module, spectrum-mpi/10.2.0.11-20190201 (and you needed the env setting to fix the OOM error)?

**Comment by minxu74** [comment]
@jayeshkrishna I ran the old spectrum MPI/10.2.0.10-20181214.  For the new version, I submitted a test run without the env fix and It is in the queue now.

**Comment by jayeshkrishna** [comment]
@minxu74 : Did your job complete? Does the new MPI lib need the romio environment variable?

**Comment by minxu74** [comment]
@jayeshkrishna The test case with the new MPI and w/o romio env actually used PIO2 and it failed on Summit with a segmentation error,  not OOM. So the new MPI may not need the romio env. But I will do another test with new MPI and PIO1, but without romio env to doubly check.

**Comment by jayeshkrishna** [comment]
When using PIO2 with E3SM you need to use the PIO2 in our fork (replace cime/src/externals/pio2 with master from https://github.com/E3SM-Project/ParallelIO). I will be updating the version of PIO in CIME soon.
Please try with PIO1 and see if you get the OOM error.

**Comment by minxu74** [comment]
@jayeshkrishna Thanks for the PIO2 tip. The run with the new MPI but w/o romio env failed with the same OOM error. So the romio env setting is needed. I have run a case successfully with the new MPI and romio env setting.

**Comment by jayeshkrishna** [comment]
Great, I will add the env setting to the branch and merge it to next

**Comment by jayeshkrishna** [comment]
@minxu74 / @sarats : Do the changes look good to you? I am planning to merge this to next and master today

**Comment by jayeshkrishna** [comment]
Tested the latest branch with X case (ran successfully) on Summit

**Comment by minxu74** [comment]
@jayeshkrishna The changes look good to me. Thanks a lot for your PR.

**Comment by jayeshkrishna** [comment]
Adding some text from Summit user guide ,
```
The following issue was resolved with the software default changes from March 12, 2019 that set Spectrum MPI 10.2.0.11 (20190201) as default and moved ROMIO to version 3.2.1
```
So the above doc seems to suggest that ROMIO version was upgraded to 3.2.1 (and the env should have only been needed with the older version of MPI lib). We can handle this issue in a future PR (Since @minxu74 observed that this env setting was required with the old and new MPI libs)

**Comment by jayeshkrishna** [comment]
These changes are only to summit machine files (should not impact nightlies or any other machine), so merging to master

**Pull request merged**
