### PR TITLE
Remove unused sea ice modules from MPAS-Ocean core

### PR DESCRIPTION
**Pull request by mark-petersen**
We had a sea ice module in the ocean core that was completely unused. This was added for early testing in 2013 and then transferred to the sea ice core. See https://github.com/MPAS-Dev/MPAS-Model/pull/827

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
passes:
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
SMS_Ln9_D.T62_oQU120.GMPAS-IAF.anvil_intel
```

**Review by jonbob — APPROVED** [review]
Looks good from a visual inspection and will test the merge

**Comment by jonbob** [comment]
merged to next - passed sanity testing

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
