### PR TITLE
ftype 4 for theta models

### PR DESCRIPTION
**Pull request by oksanaguba**
This PR adds ftype 4 (dribbling tendencies at each timestep) to theta models. Only theta-l model is tested wrt new code.

### CODE REVIEW

**Comment by oksanaguba** [comment]
When testing against master, as expected:
The following tests FAILED:
	 12 - thetah-test22 (Failed)
	 13 - thetanh-test22 (Failed)
	 14 - thetah-TC (Failed)
	 15 - thetanh-TC (Failed)
	 16 - thetanh-c-TC (Failed)
	 17 - thetanhwet-TC (Failed)

**Comment by oksanaguba** [comment]
While comparing this PR to baselines made in MT:lorenz3 branch, sw tests fail. My best guess is that it is because nonbfb PR is not in lorenz3 branch. If so, verifying that this branch did not break anything is harder.

**Comment by oksanaguba** [comment]
test1-shot1

**Comment by oksanaguba** [comment]
test1-shot2

**Comment by oksanaguba** [comment]
test2

**Comment by oksanaguba** [comment]
test3-shot1

**Comment by oksanaguba** [comment]
test3-shot2

**Comment by oksanaguba** [comment]
test3-shot3

**Comment by oksanaguba** [comment]
Above are plots for three dcmip16 tests for namelists r100, r50 hydro/nonhydro when applicable. Runs on the right were done from MT:lorenz3 branch with commit 1caeee68c7104734cf6c64ec75f5d50e78146b92 , runs on the right are from this branch, commit ea6e4e15ef0e8e34ec43eb489baad889ce997b3b . Plots were done automatically for each test (if there is an empty spot, it means a run did not finish due to instability). Each file was amended to mark lorenz3 run or ftype4 (this PR) run.  All namelists that were used have rsplit=3, and so, lorenz3 runs were done with ftype0, this branch's runs were done with ftype=4.

**Comment by oksanaguba** [comment]
test2-l3

**Comment by oksanaguba** [comment]
test2-f4

**Comment by oksanaguba** [comment]
test3-l3

**Comment by oksanaguba** [comment]
test3-f4r6

**Comment by mt5555** [comment]
TC results are very nice: ftype=4 removes the ugly gravity wave noise in r100 and r50-h

**Comment by oksanaguba** [comment]
this commit against master:
```
	 12 - thetah-test22 (Failed)
	 13 - thetanh-test22 (Failed)
	 14 - thetah-TC (Failed)
	 15 - thetanh-TC (Failed)
```
so, pr is not ready.

**Comment by oksanaguba** [comment]
besides tests, diffs in web interface show changes to mpas files, so, i may have done it wrong when merging master into this branch.

**Comment by oksanaguba** [comment]
tests pass now
```
100% tests passed, 0 tests failed out of 17
```

**Comment by oksanaguba** [comment]
The bug above would affect dry simulations. While I considered rerunning and replotting dcmip16 tests as above, only baro test has a dry option, other two are wet tests. Also, for baro test, I believe I ran only wet namelists. So I won't rerun unless requested by the integrator.

**Comment by oksanaguba** [comment]
Since there is no test for ftype3,4 yet, I ran dcmip16 baro test case for target preqx-nlev30-interp and namelist below from master  a6bb9a51e897  and from this branch for ftype3,4 and dry/wet moisture. All corresponding files are identical.
```
&ctl_nl
  se_ftype=3
  moisture          = 'wet'
  nthreads          = 1
  partmethod        = 4                         ! mesh parition method: 4 = space filling curve
  topology          = "cube"                    ! mesh type: cubed sphere
  test_case         = "dcmip2016_test1"         ! test identifier
  ne                = 8                         ! number of elements per cube face
  qsize             = 6                         ! num tracer fields
  ndays             = 5
  statefreq         = 24                        ! number of steps between screen dumps
  restartfreq       = -1                        ! don't write restart files if < 0
  runtype           = 0                         ! 0 => new run
  tstep             = 900                       ! largest timestep in seconds
  integration       = 'explicit'                ! explicit time integration
  tstep_type        = 5
  rsplit            = 0
  qsplit            = 1
  nu                = 3e16                      ! default= 1e15*(ne30/ne8)**3.2 = 6.9e16
  nu_s              = 3e16
  nu_p              = 3e16
  nu_top            = 0                         ! default = 2.5e5
  limiter_option    = 9
  hypervis_order    = 2                         ! 2 = hyperviscosity
  hypervis_subcycle = 1                         ! 1 = no hyperviz subcycling
  dcmip16_prec_type = 1                         ! 0=kessler physics
  dcmip16_pbl_type  = -1                        ! 0=reed-jablonowski pbl, -1 = none
/
&vert_nl
  vform             = "ccm"
  vfile_mid         = "../vcoord/camm-30.ascii"
  vfile_int         = "../vcoord/cami-30.ascii"
/
&analysis_nl
!  output_prefix     = "r400-wet-"
  output_dir        = "./movies/"               ! destination dir for netcdf file
  output_timeunits  = 2,                        ! 0=timesteps, 1=days, 2=hours, 3=seconds
  output_frequency  = 24                        ! every 24 hours
!  output_varnames1  ='T','ps','pnh','geo','u','v','w','omega','Th','Q','Q2','Q3','Q4','Q5','rho','precl','zeta'   ! variables to write to file
  output_varnames1  ='T','ps','pnh','geo','u','Th','Q','Q2','Q3','Q4','Q5','precl','zeta'   ! variables to write to file
  interp_type       = 1                         ! 0=native grid, 1=bilinear
  output_type       ='netcdf'                   ! netcdf or pnetcdf
  num_io_procs      = 16
!  interp_nlon       = 360
!  interp_nlat       = 181
  interp_gridtype   = 1
/
&prof_inparm
  profile_outpe_num   = 100
  profile_single_file   = .true.
/
```

**Comment by oksanaguba** [comment]
For the check for ftype3 and theta-l model, the check works but does not print line/file. Another thought is to put the check to namelist instead (now that there is preproc directive for theta-l), but it is not clear to me how it would work for the coupled run.

**Comment by oksanaguba** [comment]
This needs two things: first, while running ftype3,4 tests against master I did not use rsplit>1, so it tested nothing. Second, the pr needs ftype4 tests with preqx, theta-l and dcmip16 TC test.

**Comment by oksanaguba** [comment]
ftype3,4 dcmip16-1 runs were repeated for the nl above with rsplit=3, movies are identical.

**Comment by rljacob** [comment]
Should [wip] be added back to the title?  This doesn't seem to be ready to merge.

**Comment by oksanaguba** [comment]
It is actually almost ready. I will add 2 homme standalone tests to this pr and that's it. I will do it by monday.

**Comment by oksanaguba** [comment]
Now it is ready. Commit before the last added 2 tests, i configured and ran 'make check'. Two new tests got thru and output seems ok (no crashes). Tests are disabled. @mt5555

**Pull request merged**
