### PR TITLE
MALI thermal solver bug fix and improved iceberg handling

### PR DESCRIPTION
**Pull request by matthewhoffman**
This merge updates the E3SM-Project/E3SM repo with MALI improvements from MALI-Dev/develop since February 2024.  The primary update needed is a bug fix to the thermal solver that prevents model crashes in some situations when ice thickness is very small.  Bringing this to master is in preparation for enabling the MALI thermal solver in E3SM, which is required for completing ice-sheet/ocean coupling.

Additionally, this brings in improvements to the detection of icebergs and small islands that makes the velocity solver more robust.  There are a number of other changes related to the subglacial hydrology model and sea-level model in MALI, both of which are still in development for coupled E3SM applications.

Complete list of MALI-Dev/develop merges included:

* 119f046a54 Merge branch 'trhille/mali/remove_icebergs_in_each_rk_stage' into MALI-Dev/develop
* e23c401962 Merge branch 'alexolinhager/restrictedDomainTimestepFix' into MALI-Dev/develop
* 3799e8320f Merge branch 'alexolinhager/smooth_hydro_fields' into MALI-Dev/develop
* 8ea2412928 Merge branch 'trhille/mali/improve_remove_small_islands' into MALI-Dev/develop
* 46bce269d2 Merge 'trhille/mali/improve_remove_small_islands' into develop
* b2143d1ac3 Merge branch 'alexolinhager/mali/totalGLdischargeCellEdge' into MALI-Dev/develop
* 102782fbd0 Merge branch 'alexolinhager/mali/autoWaterFluxMask' into MALI-Dev/develop
* 7067f38968 Merge  branch 'trhille/mali/always_remove_small_islands' into MALI-Dev/develop
* 1c903050cb Merge branch 'mperego/removeBuildType' into develop
* 86f24750e4 Merge branch 'matthewhoffman/mali/thermal_err_handling' into MALI-Dev/develop 
* 07223245a0 Merge branch 'hollyhan/hollyhan/mali/call_SLM_subroutine_to_allocate_nglv_variables' into MALI-Dev/develop
* 8d3c556a4b Merge branch 'andrewdnolan/mali/hydro_regional_stats' into MALI-Dev/develop
* f79661cb42 Merge branch 'hollyhan/mali/add_restart_functionality_slm' into MALI-Dev/develop
* 8be18efd4a Merge branch 'cshafer/hydro_stats' into MALI-Dev/develop
* 6ef322e58d Merge branch 'matthewhoffman/mali/hydro_boundary_cleanup' into MALI-Dev/develop

[NML] for configurations with MALI
[BFB] because no production compsets use MALI at this time

### CODE REVIEW

**Comment by matthewhoffman** [comment]
@jonbob , there are 3 namelist changes associated with this PR that will need updating in the E3SM nl build system:

1. `config_slm_coupling_interval`: existing option that has updated **type** and default
2. `config_SGH_use_iceThicknessHydro`: new option, default from Registry should be default in E3SM
3. `config_SGH_iter_smooth_waterPressureSlopeNormal`: new option, default from Registry should be default in E3SM

**Comment by jonbob** [comment]
@matthewhoffman -- I'll work on that right now. Does it also make sense to update the ERS test in this PR?

**Comment by matthewhoffman** [comment]
@jonbob , oh, that's a good suggestion.  There are some changes to namelist defaults and streams that I would also need to make before that test will work correctly.  I will add those after you have made your changes, and then I will run that test again to make sure it now passes and if so, add it to the PR as well.  My namelist changes will activate the thermal solver by default, so we'll need to check all the MALI tests, including the ones that aren't run by default, and I'll need your help in identifying what that full list.

@stephenprice , I don't think we need anything from you on this for now, but once I have activated the thermal solver and run the existing tests, I will ask you to try this branch with any ongoing development/simulations you are working on.

**Comment by jonbob** [comment]
Thanks for pointing out the changes to the defaults, @matthewhoffman. I've updated the bld files to match, but as always please check and make sure it looks correct to you

**Review by trhille — APPROVED** [review]
Thanks for taking care of this @matthewhoffman. Approving based on inspection.

**Comment by jonbob** [comment]
Passes:
* e3sm_landice_developer on chrysalis with the gnu compiler
with expected NML and regular DIFFs

Passes:
* ERS_Ld5.TL319_oQU240wLI_ais20.MPAS_LISIO_JRA1p5.chrysalis_intel.mpaso-ocn_glcshelf
with expected NML DIFF

Passes:
* ERP_Ld3.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-pioroot1

merged to next

**Comment by jonbob** [comment]
merged to master and expected NML and regular DIFFs blessed

**Pull request merged**
