### PR TITLE
for add-inundation soil erosion model

### PR DESCRIPTION
**Pull request by tanzeli1982**
Hi,

Could you help review my soil erosion submission? In the model, soil erosion is calculated as a function of direct throughfall, rain drips and surface runoff. The eroded SOC is calculated based on the amount of soil erosion and the soil carbon content. The eroded SON and SOP are calculated based on the eroded SOC and the estimated C/N and C/P weight ratios in surface soil. When erosion takes place, the surface layer is truncated by the erosion height, and at the same time an amount of organic C, N and P corresponding to this erosion height is removed. As the thickness of soil layers is always conserved in the model, due to erosion, soils in the next soil layer are allocated to the surface layer by the amount of the erosion height and the organic C, N and P in the allocated soils are also moved. In this way, organic C, N and P from all the following soil layers move upward. We also assume that new substrates replacing the materials of the bottom soil layer are organic C, N and P free. Consequently, organic C, N and P in the last layer will decrease towards zero with erosion proceeding.

Zeli

### CODE REVIEW

**Comment by tanzeli1982** [comment]
Tony, 
I indeed ran the simulation with soil erosion turned off but I did not do bit-to-bit comparison for the simulation. Gautam will give me a presentation on how to use the E3SM land test suite for it. So, you can make your review on hold now until I go through the process, even though I do not expect my code will break anything.

**Comment by apcraig** [comment]
Sounds good, thanks.  Let me know how that turns out.    Just FYI, I do not believe the add-inundation branch has had a lot of rigorous testing, so if you test within that branch and have problems, someone may have to step back and do more testing on the add-inundation branch as well.

**Comment by bishtgautam** [comment]
@tanzeli1982, @apcraig, Is this PR correctly listing the merge destination to be `apcraig/mosart/add-inundation`? Or, should the destination be the `master` branch of E3SM?

**Comment by apcraig** [comment]
@bishtgautam Good question and I don't know.  The add-inundation branch has been used for quite a bit of elm-mosart development.   If this is part of that development, it's fine to merge on the branch.  If you are not sure whether to merge onto the add-inundation branch, you should ask Ruby about it.  Was the elm-erosion branch created from the add-inundation branch?

**Comment by rljacob** [comment]
@tanzeli1982 what is your intention here?  PRs are only for merging finished features to master.

**Comment by tanzeli1982** [comment]
I created two branches: one was originated from the master and one was originated from add-inundation. These two branches are separate and thus two pull requests are also separate. Soil erosion is a finished feature and Ruby has approved it for the master branch. I added it also to the add-inundation because there are some water management and irrigation features still only available in the add-inundation and I will use these new features in the new development for soil erosion.

**Comment by tanzeli1982** [comment]
Actually, for the add-inundation, I see there is no need for model review before merging. Because I have tested my model a lot on the add-inundation before, I may be able to submit it right now. For the master, I will go through the unit test and then Gautam can approve the merge.

**Comment by bishtgautam** [comment]
I'm going to close this because E3SM project uses PR to merge a feature branch into master and/or maintenance branches. If this feature branch needs to be merged into a user's branch, then it can be done directly via command line as long as the user agrees to merge that feature branch in his/her branch.

**Pull request closed without merging**
