### PR TITLE
Added 1D ridging sea ice  test case

### PR DESCRIPTION
**Pull request by akturner**
Update .gitignore for mpas-seaice
Rename config_use_special_boundaries_zero_tracers to config_use_special_boundaries_tracers
New ridging init option
Allow special boundaries to set tracers
Added 1D ridging test case
Fix test case locations in scripts

[NML]
[BFB]

### CODE REVIEW

**Comment by njeffery** [comment]
@akturner :  I ran the ridging_1D testcase on chrysalis without any issues.  Should the ridging_island testcase also run as part of this PR?

**Review by njeffery — APPROVED** [review]
The ridging_1D testcase ran correctly on chrysalis.  All stand alone testcases also passed. However, the set-up script DATA/get_data.py uses an obsolete function string.strip().  It can be replaced with str.strip() which works uses the latest e3sm-unified.   One testcase did not pass:  ridging_island. I've submitted this error as an issue.

**Comment by akturner** [comment]
@njeffery Thanks! Much appreciated

**Comment by jonbob** [comment]
merged to master and expected NML DIFFs blessed

**Pull request merged**
