### PR TITLE
Add initial superBFB tests for MPAS-Seaice

### PR DESCRIPTION
**Pull request by amametjanov**
Add initial superBFB tests for MPAS-Seaice

[BFB]

### CODE REVIEW

**Comment by proteanplanet** [comment]
Could you please explain what is meant by superBFB?

**Comment by rljacob** [comment]
https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/3438608385/E3SM+Code+Review+and+New+Feature+Process#Super-BFB-suite

**Review by proteanplanet — APPROVED** [review]
Approved. The tests successfully ran from this branch on Chrysalis using 
`./create_test --output-root ${CASE_ROOT} "e3sm_superbfb_ice"`

**Comment by jonbob** [comment]
@amametjanov -- could we use a v2 seaice grid instead of oEC60to30v3, which is from v1? Like EC30to60E2r2?

**Comment by proteanplanet** [comment]
We'll need to switch grids again during this year to accommodate the V3 versions.

**Comment by jonbob** [comment]
@proteanplanet - agreed, but we might as well start with what is most current

**Review by jonbob — APPROVED** [review]
Thanks for changing to v2 grids. Approved based on visual inspection

**Pull request merged**
