### PR TITLE
Homme cmake subdir

### PR DESCRIPTION
**Pull request by bartgol**
This PR allows to build HOMME with cmake from _within another cmake project_. This is needed by scream (in fact, this has already be done in the scream fork, but I want it to get in E3SM as well, so I can take care of merging E3SM master into the scream fork, taking care of the homme conflicts).

The logic is simple: if there's a cmake project defined already, do not define it, do not build execs/tests, just let the host cmake project drive everything.

This PR should have zero impact on standalone homme cmake build, and zero impact on cime-base builds.

Note: I added a bunch of reviewers that have to do with any combination of homme, cime, and cmake.

### CODE REVIEW

**Comment by oksanaguba** [comment]
It worked when I tried to build homme on skybridge in the usual way.

**Comment by jgfouca** [comment]
Merged to next...

Why was this branch requested to be merged into next instead of master?

**Comment by jgfouca** [comment]
@bartgol , I made a serious mistake with this PR. Since you requested that your branch be merged to next, the PR closed itself when I merged to next and I then forgot to merge to master. I just now merged this to master. Thanks to @oksanaguba for discovering this. @ambrad , you may be impacted by this mistake as well.

**Comment by bartgol** [comment]
@jgfouca whoops! Sorry for picking the wrong base.

**Pull request merged**
