### PR TITLE
Init an array (momaod) to zero

### LINKED ISSUE #3160: Bug in modal_aer_opt.F90
In the MAM verification work, we (@jiansunpnnl @kaizhangpnl) find that in modal_aer_opt.F90 (https://github.com/E3SM-Project/E3SM/blob/master/components/cam/src/physics/cam/modal_aer_opt.F90), the marine organic aerosol (MOA) burden fields are initialized twice, but the MOA AOD properties are not initialized. This looks like a bug and needs to be fixed. 

#if ( defined MODAL_AERO_4MODE_MOM )
   burdenmom(:ncol)      = 0.0_r8
#elif ( defined MODAL_AERO_9MODE )
   burdenpoly(:ncol)     = 0.0_r8
   burdenprot(:ncol)     = 0.0_r8
   burdenlip(:ncol)      = 0.0_r8
#endif
   ssavis(1:ncol)        = 0.0_r8

   aodabsbc(:ncol)       = 0.0_r8 
   dustaod(:ncol)        = 0.0_r8
   so4aod(:ncol)         = 0.0_r8
   pomaod(:ncol)         = 0.0_r8
   soaaod(:ncol)         = 0.0_r8
   bcaod(:ncol)          = 0.0_r8
   seasaltaod(:ncol)     = 0.0_r8

**#if ( defined MODAL_AERO_4MODE_MOM )
   burdenmom(:ncol)      = 0.0_r8
#elif ( defined MODAL_AERO_9MODE )
   burdenpoly(:ncol)     = 0.0_r8
   burdenprot(:ncol)     = 0.0_r8
   burdenlip(:ncol)      = 0.0_r8
#endif**

### LINKED ISSUE #3956: Use of uninitialized value in modal_aer_opt.F90 under MODAL_AERO_4MODE_MOM define
While debugging something else, I might have found an array being used before init. I hit this error:

```
0: forrtl: error (65): floating invalid
0: Image              PC                Routine            Line        Source
0: e3sm.exe           000000000C67FCE4  Unknown               Unknown  Unknown
0: e3sm.exe           000000000C2F7510  Unknown               Unknown  Unknown
0: e3sm.exe           00000000024C0E58  modal_aer_opt_mp_        1010  modal_aer_opt.F90
0: e3sm.exe           000000000205004E  aer_rad_props_mp_         272  aer_rad_props.F90
0: e3sm.exe           000000000141BCD0  radiation_mp_radi        1280  radiation.F90
0: e3sm.exe           00000000028156E1  physpkg_mp_tphysb        2706  physpkg.F90
0: e3sm.exe           00000000027DED04  physpkg_mp_phys_r        1045  physpkg.F90
0: e3sm.exe           000000000086317C  cam_comp_mp_cam_r         245  cam_comp.F90
0: e3sm.exe           0000000000826619  atm_comp_mct_mp_a         577  atm_comp_mct.F90
0: e3sm.exe           0000000000462C28  component_mod_mp_         737  component_mod.F90
0: e3sm.exe           000000000042B97D  cime_comp_mod_mp_        2897  cime_comp_mod.F90
0: e3sm.exe           000000000044A73C  MAIN__                    153  cime_driver.F90
```

And looking in:
`components/eam/src/physics/cam/modal_aer_opt.F90`

I see the following, where it looks like momaod() is used before init.
```
#if ( defined MODAL_AERO_4MODE_MOM )
                     aodc           = (absmom(i)*(1.0_r8 - palb(i)) + palb(i)*scatmom(i))*dopaer(i)
                     momaod(i)  = momaod(i) + aodc    !<-- line 1010
```

I'm trying to set it to zero like this:
```
#if ( defined MODAL_AERO_4MODE_MOM )
            scatmom(:ncol)  = 0._r8
            absmom(:ncol)   = 0._r8
            hygromom(:ncol) = 0._r8
            momaod(:ncol)   = 0._r8 ! ndk 
```
and when I do this init, it does seem to run beyond the fail.

To be complete, here is a description of how I found "floating invalid" at that location. Not sure if all of these settings are needed to reproduce. (Also not sure this uninitialized array is the cause of the floating invalid error)
```
set compset=FC5AV1C-L
set mach=cori-haswell
set res=ne11_ne11

./xmlchange CAM_TARGET=theta-l

cat <<EOF >> user_nl_eam
  semi_lagrange_cdr_alg = 3
  theta_hydrostatic_mode = .true.
  tstep_type = 5
  state_debug_checks = .true.
EOF

1 MPI and 1 thread.
```

### PR DESCRIPTION
**Pull request by ndkeen**
Init an array to zero.
momaod(:ncol)   = 0._r8

Fixes #3956
Fixes #3160

[bfb]

### CODE REVIEW

**Comment by ndkeen** [comment]
I made another commit to also zero 3 other arrays that are only used under `MODAL_AERO_9MODE` macro.
So I thought it would be good to include this in this PR.

Is there an existing test that would exercise this?

```
polyaod(:ncol) = 0._r8
protaod(:ncol) = 0._r8
lipaod(:ncol) = 0._r8
```

**Comment by singhbalwinder** [comment]
`MODAL_AERO_9MODE` is an experimental MAM package which is not currently tested. I am also not aware of anybody who is using it currently. It is still a good idea to fix these arrays.

**Review by susburrows — CHANGES_REQUESTED** [review]
I see that the AOD variables for other chemical species are initialized in lines 593-599, and I think that is where the momaod (and related diagnostic variables) should be initialized as well.  By adding the initialization at lines 701 and 712-714, which is inside the mode loop, I believe it will break the intended summation over the aerosol modes (lines 1014, 1017, and 1020 in the original code).

**Comment by ndkeen** [comment]
Yes that might be right, I missed that the AOD vars are different. I will let others decide where is best to init.

Also, I note that there appears to be duplicate lines of code to init some arrays to zero:

```
#if ( defined MODAL_AERO_4MODE_MOM )
   burdenmom(:ncol)      = 0.0_r8
#elif ( defined MODAL_AERO_9MODE )
   burdenpoly(:ncol)     = 0.0_r8
   burdenprot(:ncol)     = 0.0_r8
   burdenlip(:ncol)      = 0.0_r8
#endif
   ssavis(1:ncol)        = 0.0_r8

   aodabsbc(:ncol)       = 0.0_r8
   dustaod(:ncol)        = 0.0_r8
   so4aod(:ncol)         = 0.0_r8
   pomaod(:ncol)         = 0.0_r8
   soaaod(:ncol)         = 0.0_r8
   bcaod(:ncol)          = 0.0_r8
   seasaltaod(:ncol)     = 0.0_r8
#if ( defined MODAL_AERO_4MODE_MOM )
   burdenmom(:ncol)      = 0.0_r8
#elif ( defined MODAL_AERO_9MODE )
   burdenpoly(:ncol)     = 0.0_r8
   burdenprot(:ncol)     = 0.0_r8
   burdenlip(:ncol)      = 0.0_r8
#endif
```

**Comment by susburrows** [comment]
Thanks, Noel, yes the duplicate lines should clearly be removed.  I suspect that what happened here is that when I originally implemented this code some years ago, I copied the code block:
```
#if ( defined MODAL_AERO_4MODE_MOM )
   burdenmom(:ncol)      = 0.0_r8
#elif ( defined MODAL_AERO_9MODE )
   burdenpoly(:ncol)     = 0.0_r8
   burdenprot(:ncol)     = 0.0_r8
   burdenlip(:ncol)      = 0.0_r8
#endif
```
with the intention to change the variable names to the aod names, but then I forgot to actually do that.  Since the AOD variables are diagnostic variables that do not affect the model state, and they were not ones that I was evaluating, I never noticed the error.

**Review by susburrows — APPROVED** [review]
Thanks, Noel, the changes look good to me now.

**Comment by ndkeen** [comment]
Nice catch Susannah -- clearly I did not check that results were actually BFB, just verified it no longer used uninit array.

**Review by hwangacme — APPROVED** [review]

**Comment by singhbalwinder** [comment]
Merged to next

**Pull request merged**
