### PR TITLE
Update mpas-source: Fix cmake for tool exes

### PR DESCRIPTION
**Pull request by mark-petersen**
see https://github.com/E3SM-Project/E3SM/pull/3918 and https://github.com/MPAS-Dev/MPAS-Model/pull/737. 
Regardless of MPAS_TOOL_DIR, the tool exes need to be targets
and targets that depend of these exes need to always depend on the
needed exe. This will ensure the exes get built regardless of which
targets the user is building.

@jgfouca tested this change with the E3SM case `ne4pg2_r05_oQU480 A_WCYCL1850`. Tested both case.build and case.build --separate-builds with both MPAS_TOOL_DIR enabled and disabled.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
@jgfouca please approve. @jonbob can merge today if the schedule allows.

**Comment by mark-petersen** [comment]
Passes:
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
```
as sanity tests. But I think that does not test the specific changes here.

**Review by jgfouca — APPROVED** [review]
I approve the CMake changes. It looks like there are also changes to src/core_init_atmosphere/mpas_init_atm_static.F

**Comment by mark-petersen** [comment]
Yes, that is expected because we merge from the MPAS `develop` branch. It does not affect E3SM.

**Comment by jonbob** [comment]
can the atm changes be handled separately? is there some reason that has to be included?

**Comment by mark-petersen** [comment]
Because the workflow is from `develop` to `e3sm/develop`, and MPAS-Atmosphere changes were previously merged into `develop`. I could split them into two E3SM PRs if you prefer.

**Comment by jonbob** [comment]
Yes, in general we're trying to avoid having unrelated changes tag along on these PR's

**Comment by mark-petersen** [comment]
Done. The cmake changes are now merged separately into MPAS develop and MPAS e3sm/develop. We will need to merge `develop` into `e3sm/develop` with atmospheric changes later.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
passes SMS_D.ne4pg2_r05_oQU480.A_WCYCL1850.anvil_intel sanity test

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
