### PR TITLE
Add support for PnetCDF for HOMME on Anvil and Chrysalis

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Adding support for PnetCDF for HOMME standalone builds on
Anvil and Chrysalis

[BFB]

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
This PR should fix the build issues with HOMME standalone tests on Chrysalis and Anvil after PR #6525

**Comment by jayeshkrishna** [comment]
We also have a ticket with LCRC systems to install newer versions of NetCDF Fortran library but that might take more time than this workaround of adding support for PnetCDF for HOMME standalone builds.

(Note: After PR #6525 we need NetCDF Fortarn library > 4.5.0 for SCORPIO builds without PnetCDF)

**Comment by oksanaguba** [comment]
do we need to wrap these new lines in, say, `if machine==chrysalis` ? just trying to avoid new behaviour on machines we use otherwise, weaver, pm, mappy.

**Comment by jayeshkrishna** [comment]
These cmake files are specific to the machines (this change should only affect chrysalis and anvil)

**Comment by rljacob** [comment]
@mahf708 should the "scream defaults" tests above be running on this PR?

**Comment by mt5555** [comment]
standalone HOMME has always been able to run with netcdf and/or pnetcdf.  This PR is implying that standalone HOMME will now always require pnetcdf?   

IIUC, the build error is because of the "nf_64bit_data" type, which HOMME gets from SCORPIO.     Is this a recent SCORPIO change?   How did older versions of SCORPIO make this available when one was only building with netcdf, and wouldn't that older capability of SCORPIO be good to maintain?




pfs/fs1/home/e3smtest/jenkins/workspace/ACME_chrysalis_homme/E3SM/components/homme/utils/externals/scorpio/src/flib/pio_types.F90(281): error #6592: This symbol must be a defined parameter, an enumerator, or an argument of an inquiry function that evaluates to a compile-time constant.   [NF_64BIT_DATA]
   integer, public, parameter :: PIO_64BIT_DATA = nf_64bit_data
--------------------------------------------------^
/gpfs/fs1/home/e3smtest/jenkins/workspace/ACME_chrysalis_homme/E3SM/components/homme/utils/externals/scorpio/src/flib/pio_types.F90(281): error #6404: This name does not have a type, and must have an explicit type.   [NF_64BIT_DATA]
   integer, public, parameter :: PIO_64BIT_DATA = nf_64bit_data
--------------------------------------------------^
compilation aborted for /gpfs/fs1/home/e3smtest/jenkins/workspace/ACME_chrysalis_homme/E3SM/components/homme/utils/externals/scorpio/src/flib/pio_types.F90 (code 1)
\

**Comment by jayeshkrishna** [comment]
> standalone HOMME has always been able to run with netcdf and/or pnetcdf. This PR is implying that standalone HOMME will now always require pnetcdf? (edit: after reading #6525, is this PR needed because the regular netcdf on LCRC is too old?)
> 
> IIUC, the build error is because of the "nf_64bit_data" type, which HOMME gets from SCORPIO. Is this a recent SCORPIO change? How did older versions of SCORPIO make this available when one was only building with netcdf, and wouldn't that older capability of SCORPIO be good to maintain?
> 
> pfs/fs1/home/e3smtest/jenkins/workspace/ACME_chrysalis_homme/E3SM/components/homme/utils/externals/scorpio/src/flib/pio_types.F90(281): error #6592: This symbol must be a defined parameter, an enumerator, or an argument of an inquiry function that evaluates to a compile-time constant. [NF_64BIT_DATA] integer, public, parameter :: PIO_64BIT_DATA = nf_64bit_data --------------------------------------------------^ /gpfs/fs1/home/e3smtest/jenkins/workspace/ACME_chrysalis_homme/E3SM/components/homme/utils/externals/scorpio/src/flib/pio_types.F90(281): error #6404: This name does not have a type, and must have an explicit type. [NF_64BIT_DATA] integer, public, parameter :: PIO_64BIT_DATA = nf_64bit_data --------------------------------------------------^ compilation aborted for /gpfs/fs1/home/e3smtest/jenkins/workspace/ACME_chrysalis_homme/E3SM/components/homme/utils/externals/scorpio/src/flib/pio_types.F90 (code 1) \

This change is specific to Anvil and Chrysalis. So on these two machines HOMME standalone builds would need PnetCDF available (its already vailable on these machines, and is used by E3SM).
A recent update to the default NetCDF 64bit_data file type (moving from 64bit offset to 64bit data - this change is required for writing large variables and is already set by all production run scripts for ex) requires support for it in NetCDF Fortran libraries. The current version of the Fortran library in Anvil/Chrysalis does not have support for the type (The NetCDF C library on these machines do, so does PnetCDF) and we are in the process of updating the NetCDF Fortran library on Anvil/Chrysalis.
However adding support for PnetCDF on these machines lets HOMME standalone builds and standalone tests use the new NetCDF output type without upgrading the NetCDF Fortran libraries (Gets the HOMME standalone nightly tests running right away on these machines)

**Comment by jayeshkrishna** [comment]
We have been thinking of updating the default NetCDF output format to 64bit_data for a while (and more and more users are running into the format constraints of the older NetCDF output format at runtime).

**Comment by jayeshkrishna** [comment]
As long as you have relatively newer versions of NetCDF Fortran libraries available HOMME standalone tests should work/build 
 without any change.

**Comment by jayeshkrishna** [comment]
@oksanaguba / @mt5555 : If you are ok with the change please go ahead and approve/merge this change (Merging this change will get the HOMME standalone nightly tests running again on Anvil/Chrysalis)

**Review by oksanaguba — APPROVED** [review]

**Comment by oksanaguba** [comment]
done

**Comment by jayeshkrishna** [comment]
@oksanaguba : Was this PR merged to next?

**Comment by jayeshkrishna** [comment]
> @oksanaguba : Was this PR merged to next?

I see it now, thanks

**Pull request merged**
