### PR TITLE
Added support to allow eam history tapes up to 15 for maint-2.0

### PR DESCRIPTION
**Pull request by wlin7**
This is to mirror PR #4892 for master to increase eam history tapes
up to 15 to accomodate more extensive output configurations.

[BFB]

### CODE REVIEW

**Comment by wlin7** [comment]
Hi @tangq , @beharrop , this is the same as #4892 but using a  branch that is based on maint-2.0 and for maint-2.0. Please help take a quick look.

The changes should be the same as in #4892 -- note that the differences between master and maint-2.0 in namelist_definition.xml do not showed up in the review page. The other two files, cam_history.F90 and cam_history_support.F90 remain identical between master and maint-2.0.

**Review by tangq — APPROVED** [review]
@wlin7 , how did you make this PR without showing numerous older commits?

**Review by beharrop — APPROVED** [review]
Looks good to me.  Thanks

**Comment by tangq** [comment]
I noticed that the "squash and merge" button is not grey for my account. Does this mean users who are not integrators can merge changes into the maint-2.0 branch?

**Comment by rljacob** [comment]
That should be fixed.  Thanks for pointing it out.

**Comment by wlin7** [comment]
Merged to maint-2.0.

**Pull request merged**
