### PR TITLE
New algorithm for determining tropopause and additional diagnostic output

### PR DESCRIPTION
**Pull request by wlin7**
Add a new algorithm for determining tropopause: cold point parabolic.
Output at additional levels in the stratosphere are also added.
While the new algorithm is enabled during runtime, no additional variables
are saved by default.

[BFB]

### CODE REVIEW

**Comment by tangq** [comment]
Hi @wlin7 , we made quite a bit changes in the chemistry branch (https://github.com/E3SM-Project/E3SM/pull/4707) to implement the E90 tropopause (both 2D and 3D) for chemistry. I noticed this PR also made changes to tropopause.F90. It would be good to make sure these tropopause won't conflict each other.

**Review by golaz — APPROVED** [review]
Approving by visual inspection; the changes look as requested.

**Comment by wlin7** [comment]
Hi @tangq , thanks for calling this out. There will be some small conflicts that need to be resolved when #4707 is merged. The total number of algorithm will become 9. We can make either CPP or E90 the 9th. Currently both are the 8th in their separate PR. The good thing is they are using different designated letter (E for E90 and F for CPP). I noticed you assigned #4707 to me. I will take care of these when merging.

**Comment by wlin7** [comment]
Merged to next.

**Comment by rljacob** [comment]
Is this need for some v2 sims?

**Comment by golaz** [comment]
@rljacob : yes, this is some additional diagnostics output we want to have for additional historical simulations part of a large ensemble with v2.

**Pull request merged**
