### PR TITLE
Widen halo for Redi hmix computation

### LINKED ISSUE #3958: PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF fails on compy
The extra_coverage testing suite, which runs once a week, shows that this test has been failing since early September but passed before that. I ran some additional tests that indicate [PR #3825](https://github.com/E3SM-Project/E3SM/pull/3825) is responsible for introducing the failure. Also note that PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF.compy passes, so the problem appears to be in the ice shelf melt flux code.

### PR DESCRIPTION
**Pull request by mark-petersen**
A computation in the Redi hmix needed to be widened by one halo ring. Otherwise, partition tests failed - but only in E3SM and only with DIB-IAF-ISMF (data iceberg, ice sheet melt fluxes).  I also removed incorrect variables in an OpenMP private statement, and removed an unused variable. See https://github.com/MPAS-Dev/MPAS-Model/pull/780.

Fixes #3958. 
[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
Currently includes code changes in #4023. Will rebase after that is merged.

Passes MPAS-O nightly regression with gnu and both debug and optimized. Passes E3SM test that caused the original problem in E3SM-Project/E3SM#3958:
```
PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
```
as well as a variety of others tested:
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
PEM_Ld5_P512.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_intel
PEM_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-haswell_gnu
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
PET_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-haswell_intel
```

**Comment by mark-petersen** [comment]
@mattdturner could you run your standard tests on this as well?

**Comment by mattdturner** [comment]
Sure.  I'll go ahead and start my suite of tests on Cori and Compy

**Comment by mattdturner** [comment]
On Compy, it passes:
```
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
  - PASS SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi BASELINE /compyfs/e3sm_baselines/pgi/master:
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
```

On Cori it passes:
```
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
PET_Ln3_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PET_Ln3_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PEM_Ln9_D.T62_oQU240.GMPAS-IAF.cori-haswell_intel
PEM_Ln9_D.T62_oQU240.GMPAS-IAF.cori-haswell_gnu
```

No tests that I ran failed

**Review by mattdturner — APPROVED** [review]

**Comment by mark-petersen** [comment]
Rebased to current master. @jonbob this is ready. Running a few quick sanity tests as well...

**Comment by mark-petersen** [comment]
Passes:
```
PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PEM_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-haswell_gnu
PET_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-haswell_gnu
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
```

**Review by jonbob — APPROVED** [review]
From visual inspection and testing

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Comment by jonbob** [comment]
@mark-petersen - this seems to have impacted the ocean BGC results. Is that expected?

**Comment by jonbob** [comment]
@mark-petersen - more in-depth testing does prove that this PR changed answers for ocean BGC. But it also fixed a PEM issue with BGC as well, so I'll bless the BGC DIFFs and we can figure this killed two birds with one stone...

**Comment by jonbob** [comment]
I requested blesses for the BGC DIFFs -- my testing shows that this PR was responsible for those changes

**Pull request merged**
