### PR TITLE
Adds CIME testing excludes

### PR DESCRIPTION
**Pull request by jasonb5**
CIME's archive configuration is used for determining which history files are compared during the COMPARE_PHASE of tests. There was a fix in CIME that corrected the generated regex that was used to search for these files. Since the fix additional active component history files are being matched and generating test failures as they are required for archiving but not for the COMPARE_PHASE of a test.

This PR excludes these components from the COMPARE_PHASE of tests.

This PR includes a CIME update:

Changes:
1) jenkins_generic_job: Add flag for ignoring memleaks
2) Always use the BATCH_COMMAND_FLAGS argument.
    This allows users to alter with xmlchange and append with --append
3) Default to single-build in PEM tests
4) Adds the force-rebuild argument to create_test and cs.status.
    This argument will set the SHAREDLIB_BUILD_PHASE to PEND
    for all tests.
5) Do not re-invoke make on repeat case.build calls
6) env_batch: replace PROJECT arg with nothing if PROJECT not required
7)     - Adds --driver to query_config
    - Deprecates --comp_interface for query_config
    - Fixes driver_choices in create_test
8) Add support for MPASO_USE_PETSC
9) Better error for missing config_machines.xml file
10) Adds skip-submit argument to case.build
11) change method of detecting fv3 dycore in cam and path to libfv3.a
12) add which to find ncdump and an error message if not found
13) do not allow EXEROOT or OBJDIR or LIBROOT to be CASEROOT
14) Add flexible controls of GPU configuration
15) Removes DAE.ww3a.ADWAV from cime_developers
16) Fixes hist_files excluding components during actual compare

Fixes:
1) Fix create_test --single-exe option
2) Fixes issue causing case context to exit early. This would result in
    ERROR: Cannot modify case, read_only... errors.
3)  Fixes regex pattern used to match history files. Only considers .nc
    files when copying history files for a tests COMPARE_PHASE. Adds
    a new optional attribute exclude_testing for comp_archive_spec
    which allows a components history files to be archived but excluded
    from the COMPARE_PHASE of tests when active.
4)  Fixes creating directory for input data
5) batch: improve the account remove and add support for slurm
6) Docker CI fixes

[BFB]

### CODE REVIEW

**Comment by jasonb5** [comment]
@jgfouca This is the fix that goes along with https://github.com/ESMCI/cime/pull/4452. It's possible there might be other instances like MPASS where we want the history files archived but not used for the COMPARE_PHASE of tests.

How should we go about merging this and bringing the CIME version back to current?

**Comment by jgfouca** [comment]
@jason5, I ran e3sm_developer on my local machine and there were a number of problems.

The following tests had issues:
```
DIFF ERS.f09_g16_g.MALISIA.mappy_gnu (phase BASELINE)
DIFF ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.mappy_gnu.mosart-rof_ocn_2way (phase BASELINE)
DIFF ERS.r05_r05.IELM.mappy_gnu.elm-V2_ELM_MOSART_features (phase BASELINE)
DIFF ERS_Ld5.T62_oQU120.CMPASO-NYF.mappy_gnu (phase BASELINE)
DIFF ERS_Ld5.T62_oQU240.DTESTM.mappy_gnu (phase BASELINE)
DIFF PEM_Ln5.T62_oQU240wLI.DTESTM.mappy_gnu (phase BASELINE)
DIFF PET_Ln5.T62_oQU240.DTESTM.mappy_gnu (phase BASELINE)
DIFF SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu (phase BASELINE)
DIFF SMS.f09_g16_a.IGELM_MLI.mappy_gnu (phase BASELINE)
DIFF SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.mappy_gnu.mpassi-jra_1958 (phase BASELINE)
DIFF SMS_Ld1.T62_oQU240wLI.GMPAS-IAF-DISMF.mappy_gnu (phase BASELINE)
DIFF SMS_P12x2.ne4_oQU240.WCYCL1850NS.mappy_gnu.allactive-mach_mods (phase BASELINE)
```

I wrote a simple script to analyze the TestStatus logs and found that the following tests had "real" diffs (an actual difference in hist files):
```
ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.mappy_gnu.mosart-rof_ocn_2way
SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.mappy_gnu.mpassi-jra_1958
```

There were lots of missing counterparts:
```
Analyzing case ERS.f09_g16_g.MALISIA.mappy_gnu
  Missing compare counterpart: 'ERS.f09_g16_g.MALISIA.mappy_gnu.C.20230726_101325_gz34eo.mali.hist.am.0001-01-07_00000.nc'
  Missing original counterpart: 'mali.hist.am.0001-01-07_00000.nc.rest'
Analyzing case ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.mappy_gnu.mosart-rof_ocn_2way
  /ascldap/users/jgfouca/acme/scratch/ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.mappy_gnu.mosart-rof_ocn_2way.C.20230726_101325_gz34eo appears to have real diffs
  Missing compare counterpart: 'ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.mappy_gnu.mosart-rof_ocn_2way.C.20230726_101325_gz34eo.mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc'
  Missing original counterpart: 'mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc.base'
  Missing compare counterpart: 'ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.mappy_gnu.mosart-rof_ocn_2way.C.20230726_101325_gz34eo.mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc'
  Missing original counterpart: 'mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc.base'
  Missing compare counterpart: 'ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.mappy_gnu.mosart-rof_ocn_2way.C.20230726_101325_gz34eo.mosart.h0.0001-01-02-00000.nc'
  Missing original counterpart: 'mosart.h0.0001-01-02-00000.nc.base'
Analyzing case ERS.r05_r05.IELM.mappy_gnu.elm-V2_ELM_MOSART_features
  Missing compare counterpart: 'ERS.r05_r05.IELM.mappy_gnu.elm-V2_ELM_MOSART_features.C.20230726_101325_gz34eo.mosart.h0.0001-01-12-00000.nc'
  Missing original counterpart: 'mosart.h0.0001-01-12-00000.nc.base'
Analyzing case ERS_Ld5.T62_oQU120
  Missing compare counterpart: 'ERS_Ld5.T62_oQU120.CMPASO-NYF.mappy_gnu.C.20230726_101325_gz34eo.mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc'
  Missing original counterpart: 'mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc.base'
Analyzing case ERS_Ld5.T62_oQU240.DTESTM.mappy_gnu
  Missing compare counterpart: 'ERS_Ld5.T62_oQU240.DTESTM.mappy_gnu.C.20230726_101325_gz34eo.mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc'
  Missing original counterpart: 'mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc.base'
Analyzing case PEM_Ln5.T62_oQU240wLI.DTESTM.mappy_gnu
  Missing compare counterpart: 'PEM_Ln5.T62_oQU240wLI.DTESTM.mappy_gnu.C.20230726_101325_gz34eo.mpassi.hist.am.regionalStatistics.0001.01.nc'
  Missing original counterpart: 'mpassi.hist.am.regionalStatistics.0001.01.nc.modpes'
Analyzing case PET_Ln5.T62_oQU240.DTESTM.mappy_gnu
  Missing compare counterpart: 'PET_Ln5.T62_oQU240.DTESTM.mappy_gnu.C.20230726_101325_gz34eo.mpassi.hist.am.regionalStatistics.0001.01.nc'
  Missing original counterpart: 'mpassi.hist.am.regionalStatistics.0001.01.nc.single_thread'
Analyzing case SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu
  Missing compare counterpart: 'SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.C.20230726_101325_gz34eo.mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc'
  Missing original counterpart: 'mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc.base'
  Missing compare counterpart: 'SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.C.20230726_101325_gz34eo.mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc'
  Missing original counterpart: 'mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc.base'
  Missing compare counterpart: 'SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.mappy_gnu.C.20230726_101325_gz34eo.mali.hist.am.0001-01-01_00000.nc'
  Missing original counterpart: 'mali.hist.am.0001-01-01_00000.nc.base'
Analyzing case SMS.f09_g16_a.IGELM_MLI.mappy_gnu
  Missing compare counterpart: 'SMS.f09_g16_a.IGELM_MLI.mappy_gnu.C.20230726_101325_gz34eo.mali.hist.am.0001-01-01_00000.nc'
  Missing original counterpart: 'mali.hist.am.0001-01-01_00000.nc.base'
Analyzing case SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.mappy_gnu.mpassi-jra_1958
  /ascldap/users/jgfouca/acme/scratch/SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.mappy_gnu.mpassi-jra_1958.C.20230726_101325_gz34eo appears to have real diffs
  Missing compare counterpart: 'SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.mappy_gnu.mpassi-jra_1958.C.20230726_101325_gz34eo.mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc'
  Missing original counterpart: 'mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc.base'
Analyzing case SMS_Ld1.T62_oQU240wLI.GMPAS-IAF-DISMF.mappy_gnu
  Missing compare counterpart: 'SMS_Ld1.T62_oQU240wLI.GMPAS-IAF-DISMF.mappy_gnu.C.20230726_101325_gz34eo.mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc'
  Missing original counterpart: 'mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc.base'
  Missing compare counterpart: 'SMS_Ld1.T62_oQU240wLI.GMPAS-IAF-DISMF.mappy_gnu.C.20230726_101325_gz34eo.mpaso.hist.am.globalStats.0001-01-01.nc'
  Missing original counterpart: 'mpaso.hist.am.globalStats.0001-01-01.nc.base'
Analyzing case SMS_P12x2.ne4_oQU240.WCYCL1850NS.mappy_gnu.allactive-mach_mods
  Missing compare counterpart: 'SMS_P12x2.ne4_oQU240.WCYCL1850NS.mappy_gnu.allactive-mach_mods.C.20230726_101325_gz34eo.mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc'
  Missing original counterpart: 'mpassi.hist.am.timeSeriesStatsDaily.0001-01-01.nc.base'
  Missing compare counterpart: 'SMS_P12x2.ne4_oQU240.WCYCL1850NS.mappy_gnu.allactive-mach_mods.C.20230726_101325_gz34eo.mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc'
  Missing original counterpart: 'mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc.base'
```

A missing "compare" counterpart means the case had a hist file that it wanted to compare against something in the baselines but found no file to compare it against. A missing "original" counterpart means the inverse.

**Comment by jasonb5** [comment]
@jgfouca I'll take a look at those, thanks.

**Comment by rljacob** [comment]
notes:  Jim and Jason are working on a plan to fix the baselines.

**Comment by amametjanov** [comment]
With the CIME update, `"$JOB_WALLCLOCK_TIME"` in
```
<arg flag="-l walltime=" name="$JOB_WALLCLOCK_TIME"/>
```
is now getting resolved with a whitespace prefix:
```
qsub -q workq -l walltime= 00:31:40 -A CSC249ADSE15_CNDA  .case.test
                          ^here
```
and job submits are failing on ALCF Sunspot.

@jasonb5 @jgfouca can you take a look and fix?

**Comment by jgfouca** [comment]
@amametjanov , thanks for finding this. I will take a look.

**Pull request merged**
