### PR TITLE
Enables output of land fraction used in dust mobilization

### PR DESCRIPTION
**Pull request by bishtgautam**
Adds a new member variable (`lnd_frc_mbl_patch`) to `dust_type` to
allow the output of land fraction sued in dust mobilization. This new variable
is added to the ELM history file and is inactive by default.

[BFB] Except for the prod test suite as a new variable is added to output

### CODE REVIEW

**Comment by bishtgautam** [comment]
@rljacob, Based on discussion with @wlin7, @yfenganl, and me, we would like this PR to be included as part of the v3.0.1 tag, so the new dust-related variable can be included in ELM history files for the AMIP ensembles that have not yet started.

**Review by rljacob — APPROVED** [review]

**Comment by yfenganl** [comment]
Thanks Gautam. Could you please change the long_name to "bare soil fraction for dust mobilization", if possible.

**Review by yfenganl — APPROVED** [review]
Thanks Gautam. Could you please change the long_name to "bare soil fraction for dust mobilization"?

**Comment by rljacob** [comment]
Is there a CF standard name for this?

**Comment by bishtgautam** [comment]
@yfenganl Updated the long_name.
@rljacob Yes, I don't believe this is a standard variable.

**Review by rljacob — CHANGES_REQUESTED** [review]
Since this field will be output in production cases, please update the "prod" test mods to include it.  This will then create diffs in testing.

**Comment by wlin7** [comment]
The new variable is added to the wcprod testmods. (appended to hist_fincl1 in user_nl_elm).
On reviewing, it is also found we don't need that many testmods. Some are identical, for example, the three wcprod testmods for eam). Similarly for several allactive wcprod mods. Removing duplicated testmods will change some test names though.

**Review by rljacob — APPROVED** [review]

**Comment by peterdschwartz** [comment]
merged to next

**Review by wlin7 — APPROVED** [review]
The changes to associate lnd_frc_mbl_patch with the new output field look good and treated consistently.

**Comment by rljacob** [comment]
I'm seeing "diff_test: the two files DIFFER only in their field lists" in prod tests which is expected but you have to be careful when blessing because the SSP prod tests are also affected by #6597 which needs another day on next.  Maybe just wait and merge them both Monday.

**Comment by peterdschwartz** [comment]
merged to master

**Pull request merged**
