### PR TITLE
Adds missing files to preqx_kokkos build

### PR DESCRIPTION
**Pull request by oksanaguba**
Adds missing files to preqx_kokkos standalone build. Won't affect nightlies, CAM run with hommexx core builds.

[bfb]

### CODE REVIEW

**Comment by jgfouca** [comment]
Is this a work in progress?

**Comment by oksanaguba** [comment]
Not really, it is good except I haven't decided what to do about 3 summit cmake files. I will make up my mind soon, thanks.

**Comment by oksanaguba** [comment]
@rljacob I found this one, too, which I am going to sort now. thanks.

**Comment by oksanaguba** [comment]
@jgfouca @rljacob is it ok if I reassign it to myself and push it to next and master today? it only affects preqx_kokkos standalone build, which is used in nightlies (yet).

**Comment by jgfouca** [comment]
@oksanaguba , yes that's fine.

**Comment by oksanaguba** [comment]
Will merge when repos are open.

**Comment by oksanaguba** [comment]
Merged to next and master.

**Pull request merged**
