### PR TITLE
fixed bad path for gotm in standalone ocean build

### LINKED ISSUE #4330: bad gotm path in mpas-ocean standalone build
There is a bad path for gotm in the build_options.mk file for ocean standalone builds. This was fixed once previously but somehow got reintroduced.

### PR DESCRIPTION
**Pull request by philipwjones**
This one line change fixes a bad path for the gotm library in ocean standalone builds. 
Fixes #4330
b4b

### CODE REVIEW

**Comment by mark-petersen** [comment]
@philipwjones When I compile the current `master` with intel or gnu on grizzly and cori without this change, everything compiles and links without any trouble.

When I compile with gnu on grizzly, I get this with every compile line:
```
f951: Warning: Nonexistent include directory 
‘/turquoise/usr/projects/climate/mpeterse/repos/E3SM/pr4331_gotm_path/components/mpas-ocean/src/gotm/build/modules’ [-Wmissing-include-dirs]
```
and indeed `components/mpas-ocean/src/gotm/build` does not exist. 

What error are you getting that this fixes, and with which compiler?

**Comment by philipwjones** [comment]
The pgi compiler is the one that hits this - it seems to do a deeper recursive include so all builds with pgi fail. This was a bug we had reported and was fixed earlier on the MPAS repo. Not sure how it snuck back in.

**Comment by mark-petersen** [comment]
@philipwjones I rebased and made the simplifications we discussed, updated the gotm submodule. Compiles with intel and gnu on grizzly with no problem. Can you test with pgi? Thanks.

**Comment by philipwjones** [comment]
@mark-petersen yes, this compiles and runs b4b with pgi on summit. Thanks.

**Review by mark-petersen — APPROVED** [review]
Passes
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
```
This is ready to be merged.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
