### PR TITLE
Turn eddyProductVariables AM on by default

### PR DESCRIPTION
**Pull request by jonbob**
This PR turns the mpas-ocean eddyProductVariables analysis member on by default for all grids. It does not impact any results, just simply adds an output stream. For some ultra-low resolutions, this has previously been turned off, so there may be namelist changes for those tests.

[NML]
[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
Thank you @jonbob and @vanroekel. We should have done this originally, but at least we are changing it now. Since low-res does not matter, let's just make it simple and only have a single line:
```
<config_AM_eddyProductVariables_enable>.true.</config_AM_eddyProductVariables_enable>
```
and no exceptions.

Are the product variables written in the monthly time average by default? They probably are.

**Comment by jonbob** [comment]
Modified to have on by default for all grids, though that make cause namelist diffs for tests with low-res. Also fixed the output interval so that turning this on actually creates output. @mark-petersen, I did check  and the eddy product variables are written in the monthly time average by default.

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master and NML DIFFs blessed

**Pull request merged**
