### PR TITLE
add -ffpe-summary=none to stand-alone MPAS Makefile for gnu

### PR DESCRIPTION
**Pull request by mark-petersen**
Currently, gnu-compiled executables produce a summary table of exceptions at the end, which is some version of:
```
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_DENORMAL
```
and prints one line per processor on finalize for both debug and optimized runs. When running on hundreds of cores, this is a headache.

Looking at on-line material [1](https://wiki.usask.ca/display/MESH/IEEE+errors+using+GNU+compiler) [2](https://fluka-forum.web.cern.ch/t/the-following-floating-point-exceptions-are-signalling/593) [3](https://stackoverflow.com/questions/39350816/floating-point-exceptions-are-signalling-in-new-gfortran-version) other modeling groups see this with gnu 5+ as well, and say to ignore it or add `-ffpe-summary=none`. See [gnu compile flags](https://gcc.gnu.org/onlinedocs/gfortran/Debugging-Options.html).

I have had numerous students and post-docs tell me they had errors when they see this. The error messages are confusing and not useful, because there is no back-trace. Note that actual IEEE errors are caught during debug with `-ffpe-trap=invalid,zero,overflow` and include a back-trace. The `-ffpe-trap` is the normal way we catch the errors.

This affects MPAS-seaice and MALI as well. This Makefile is not used for E3SM compiling.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
Tested `pr` regression suite on grizzly with `make gfortran` and cori with `make gnu-nersc`. Passes `pr` suite for both debug and optimized on both. Ran some QU240 and baroclinic channel forward runs with before/after executables, and could see that summary table of IEEE exceptions was removed.

**Comment by ndkeen** [comment]
Ah. We might want to use this flag in other places as well. Thanks Mark.

**Comment by mark-petersen** [comment]
In this process, I found that `gnu-nersc` is not using `-ffpe-trap=invalid,zero,overflow` like the other gnu compilers in the Makefile. I have to think that was an oversight. I added an intentional divide by zero, and indeed the current settings don't produce an error, but with this last commit, we get a floating-point exception and trace-back, as expected.

**Review by philipwjones — APPROVED** [review]
Can you also please add the flag to the gfortran-clang target?

I built/ran a version and confirm that it ran successfully and did not generate the usual underflow messages.  They were kinda annoying so thanks @mark-petersen

**Comment by mark-petersen** [comment]
Added `-fbounds-check -fbacktrace` to gnu-nersc debug flags, so it matches gfortran. I tested on cori, including with and without an intentional divide by zero, and it all works as expected. Also added `-ffpe-summary=none` to gfortran-clang per @philipwjones's request.

@matthewhoffman and @akturner if you could run a standard test on MALI and MPAS-seaice with this Makefile, I think that is enough to test this PR.

**Comment by mark-petersen** [comment]
@xylar I think additional testing from you is not required. You can read my testing above. You've been involved with Makefile changes in the past, so wanted you to see this PR.

**Review by xylar — APPROVED** [review]
This looks good to me and passed the `nightly` regression suite on my laptop with gnu compilers.  I see:
```
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
```
without these changes but not with them.  Thanks for this work!

**Review by matthewhoffman — APPROVED** [review]
I tested on Cori with gnu using MALI, and ran into no problems.  It will be nice to eliminate those confusing output messages!

**Review by akturner — APPROVED** [review]
Passed MPAS-Seaice testing

**Comment by jonbob** [comment]
passes sanity testing, merged to next

**Comment by jonbob** [comment]
merged to master

**Pull request merged**
