### PR TITLE
Add ESMT to SAM++

### PR DESCRIPTION
**Pull request by xyuan**
Add ESMT functionality to the C++ SAMXX code. Comparisons were made with the standalone model and the full E3SM-MMF run and show good agreement. 

[BFB]

### CODE REVIEW

**Review by whannah1 — APPROVED** [review]

**Comment by whannah1** [comment]
A note about the ifdefs (since I know @brhillman  will yell at me for that) - While I'm 99.9% sure this will be a feature that we want on all the time for 2D CRMs, I think we need to do a little more investigating (particularly in regard to surface friction issues and the new variance transport). Once we decide that we do want ESMT to be on by default I'll be happy to create another PR that removes the ifdefs in favor of control via a namelist variable in both the fortran and C++ CRM code. I assume that future PR will also be able to remove the "USE_ORIG_FFT" blocks.

**Comment by mrnorman** [comment]
Has this been tested on the GPU?

**Comment by xyuan** [comment]
> Has this been tested on the GPU?

Yes, I compared with CPU and GPU runs, and the Fortran CPU runs as well.

**Comment by mrnorman** [comment]
@whannah1 , I agree, now that we've vetted the new FFT routines, we can get rid of USE_ORIG_FFT. Thanks @xyuan for doing this. Please let me know offline how painful it was to code in C++ YAKL and what I can improve to make it more user-friendly.

**Comment by brhillman** [comment]
Is this BFB for the default config?

**Comment by whannah1** [comment]
@brhillman yes, ESMT is still disabled by default and this shouldn't affect non-ESMT configurations.
And since we're still controlling this with ifdefs there won't be any namelist diff.

**Comment by brhillman** [comment]
Adding the BFB flag then.

**Review by mrnorman — APPROVED** [review]

**Comment by brhillman** [comment]
Merged to next.

**Comment by brhillman** [comment]
Merged to master.

**Pull request merged**
