### PR TITLE
Add ne4pg2_r2_QU480 bigrid and trigrid configurations

### PR DESCRIPTION
**Pull request by jonbob**
Adds support for ne4pg2_r2_QU480 configurations for ultra-low-res testing, both as bigrid (ne4pg2 atm/lnd, r2 rof, QU480 ocn/ice) and trigrid (ne4pg2 atm, r2 lnd/rof, QU480 one/ice).

[BFB] for all tested configurations

### CODE REVIEW

**Comment by jonbob** [comment]
@bishtgautam - for the trigrid to work, we'll need an r2 ELM surfdata. I'm not sure how much work that is...

**Comment by jonbob** [comment]
passes SMS_P64.ne4pg2_oQU480.A_WCYCL2000.chrysalis_intel

**Review by rljacob — APPROVED** [review]

**Comment by jonbob** [comment]
merged to next

**Comment by jonbob** [comment]
merged to master

**Comment by rljacob** [comment]
Did the r2 land data get made?  I missed that.

**Comment by jonbob** [comment]
No, it's not made yet but I thought we could bring that in separately

**Comment by bishtgautam** [comment]
I created the r2 land dataset yesterday, but the land model is throwing up an error with the new dataset. So, I'm debugging it.

**Pull request merged**
